### ISSUE TITLE
Leseprobleme bei SAP und Telekom

### ISSUE THREAD

**Issue by jfilter** [corona-warn-app/cwa-documentation#1]
Sehr geehrte Damen und Herren,

aufgrund des Satzes

> Aus Gründen der einfachen Lesbarkeit wird auf die geschlechtsspezifische Differenzierung verzichtet. Entsprechende Begriffe gelten im Sinne der Gleichbehandlung grundsätzlich für alle Geschlechter.

kommt ich zu der Schlussfolgerung, dass es Lese-Probleme bei Mitarbeiter:innen von SAP und Telekom gibt. Haben Sie sich diesbezüglich schon medizinischen Rat eingeholt?

Wann werden Sie die Texte zeitgemäß auch an nicht-männliche Personen richten?

Mit freundlichen Grüßen

Johannes Filter

**Comment by jarjarbentley** [comment]
Thank you for your comment. We will have our editors review the language used. SAP Corona Warn App Open Source Team - JB
