### ISSUE TITLE
Does the user have to verify a positive test before the diagnosis keys are uploaded?

### ISSUE THREAD

**Issue by marcopashkov** [corona-warn-app/cwa-documentation#105]
## Where to find the issue

Paragraph in question:

> In order to prevent misuse, users need to verify that they have been tested positively before being able to upload their keys. Through this integrated approach, the verification needed for the upload of the diagnosis keys does not require any action from the users.

## Describe the issue

The paragraph probably needs some clarification. To me those are opposing statements: in the first sentence it says that a user has to verify that they have been tested positive in order to upload their keys, while the second sentence states that the user does not have to do anything for the keys to be uploaded.

## Suggested change

Probably something like this:
> In order to prevent misuse, users need to verify that they have been tested positively before being able to upload their keys. Through this integrated approach, the verification needed for the upload of the diagnosis keys does not require **further** any action from the users (the app/framework? handles the upload).

Not sure though, hence I did not post a pull request.

**Comment by mh-** [comment]
For clarity maybe add something like: “In any case, upload will only be initiated after explicit user consent.”

**Comment by tklingbeil** [comment]
That’s right. The users only need to give consent to upload their keys instead of having to enter a teleTAN manually.

**Comment by tklingbeil** [comment]
@marcopashkov: I was expecting the **further** to be in there - not sure where it went in the text...

However, I think the next sentence in the text makes it pretty clear, that the user needs to give consent:

> They only have to confirm to the app and the Exposure Notification Framework that they are willing to share their diagnosis keys.
