### ISSUE TITLE
Development Process not consistent with BSI TR-03161 and OWASP Application Security Verification Standards

### ISSUE THREAD

**Issue by TomTeeJay** [corona-warn-app/cwa-documentation#11]
German BSI developed an technical advisory for digital health applications BSI TR-03161 "Sicherheitsanforderungen an digitale Gesundheitsanwendungen" (Direct Link: <https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03161/BSI-TR-03161.pdf?__blob=publicationFile&v=2>)

The BSI TR is intended to serve as a guide to assist healthcare mobile application developers in creating secure mobile applications following Confidentiality, Integrity and Availability "Vertraulichkeit, Integrität und Verfügbarkeit" and makes strong reference to common known OWASP Application Security Verification Standards.

The developing process of the German Corona App is initially not following these targets in using an unsecure 3rd party platform and violating basic assumptions made in OWASP Application Security Verification Standard, Section 1.1.1 from which I quote: 

> Verify the use of a secure software development lifecycle that addresses security in all stages of development.

To give you an example: Recent Commits of this Corona App are made by the user named "rathlein" but with different GPG signatures. How can a commit validated when even GitHub marks his GPG signatures as "not verified"?

![Screenshot](https://pics.jakobs.systems/uploads/big/dc3ad408539d3ec774cf99d8ad978358.png "Screenshot")

Not to mention that I need to trust Microsof/ Github at all, what I don't. The fact that even Microsofts' own GitHub Account was hacked recently (see <https://www.heise.de/security/meldung/Angreifer-verschafft-sich-Zugang-zu-Microsoft-GitHub-erbeutet-nichts-Wertvolles-4717415.html>) makes the choice of GitHub as Secure and trustworthy Development platform at least questionable.

**Comment by MalteJ** [comment]
The git protocol secures every commit by creating a hash of the diff. The platform the git repo is distributed over is therefore not relevant as soon as you check the git commit hash.
So I will close this as this is a non-issue.
