### ISSUE TITLE
How does the polling work in detail?

### ISSUE THREAD

**Issue by marcopashkov** [corona-warn-app/cwa-documentation#110]
## Your Question

* Documentation File: [solution_architecture.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md)
* Line / Paragraph:
> Step 4a: After signing up for notifications in step 1, the user’s phone regularly check on the Verification Server whether test results are available (polling, figure 3, steps 5-8). This way, no external push servers need to be used.
* Question: It sounds like the app is not using Apple's or Google's Push services, but constantly polls the verification server itself. How does the app prevent being shut down by the OS, or does the polling happen via the `Exposure Notification Framework`?

**Comment by tklingbeil** [comment]
Hi Marco,

this is partially a duplicate of #80, as those things were discussed there as well.

The app will definitely have to download data from remote servers in the background (diagnosis keys). This needs to happen regularly, so together with the `com.example.apple-samplecode.ExposureNotificationSampleApp.exposure-notification` entitlement comes also the benefit of "more background time to ensure that the app can test and report results promptly" (see [here](https://developer.apple.com/documentation/exposurenotification/building_an_app_to_notify_users_of_covid-19_exposure)).

Best,
Thomas

**Comment by marcopashkov** [comment]
Thank you and sorry for the duplicate! That's exactly what I wanted to know.
