### ISSUE TITLE
Can a user be identified through TAN requests?

### ISSUE THREAD

**Issue by marcopashkov** [corona-warn-app/cwa-documentation#113]
## Your Question

* Documentation File: https://github.com/corona-warn-app/cwa-documentation/blob/master/images/solution_architecture/figure_3.svg
* Line / Paragraph: Step 8, 9, 11
* Question: Maybe I am missing something. Could an attacker listen for `/tan` requests on a local network to identify devices/users that have received a positive result?

If I understand correctly the app will request a TAN, if it received a prior positive result by the verification server (Figure 3, steps 8, 9). If the only reason a TAN request is fired is a positive covid-19 result then a malicious network user could listen for such requests. 

This could be problematic e.g. for captive wifi portals (e.g in airports, hotels etc), which often require personal data in order to gain access (for home or cellular connections Internet-Service-Providers also have that data). If the operator of that portal is listening for `/tan` requests sent to the verification server then they know who has received a positive result.

Potential solution: The Tan should be attached to the `/result` response in step 6, if there is a positive result. This way an attacker cannot simply sniff for a URL of a request, but would have to break the HTTPS encryption of the POST request.

**Comment by tklingbeil** [comment]
Hi Marco,

we have discussed including the TAN right away with the result. However, at the time of delivering the result to the users we don't know, whether users would like to upload their diagnosis keys. If they decided against uploading their keys, we would have an unused TAN on our Verification Server. This in turn is not acceptable from a data privacy/protection perspective, as unneeded data for a user would be created...

The TAN request could (and should) also be issued in the context of plausible deniability (see #83 ). This would recreate the request pattern of an actual person checking for test results and optionally submitting keys. This makes it harder for a listener to decide whether the request was real or not.

However, the `POST /tan` will also be sent over an HTTPS connection, which should (assuming an HTTPS connection) not be visible from the outside.

Best,
Thomas

**Comment by marcopashkov** [comment]
Thanks Thomas!

> The TAN request could (and should) also be issued in the context of plausible deniability

Can you elaborate on this? I probably misunderstood something. In #83 the plausible deniability appears to be achieved by requesting TANs regardless of whether they will be used, but that would go counter to your prior point of having `unused TAN on our Verification Server`. Or are you sending TAN request with a `dummy TAN request` flag, which would receive an empty response?

> However, the POST /tan will also be sent over an HTTPS connection, which should (assuming an HTTPS connection) not be visible from the outside.

Will the polling occur in random intervals? Even with HTTPS encryption (assuming the app uses DNS not DoH) an attacker could listen for strictly periodic requests and look out for a non-periodic request to a specific host, indicating the TAN request, after the users approval to publish they diagnostic keys.

**Comment by tkowark** [comment]
Hi @marcopashkov , as Thomas mentioned, this is mostly along the same lines as #83 . I'd close this issue here as a duplicate and invite you to take further questions to the other discussion.
