### ISSUE TITLE
SD-Card

### ISSUE THREAD

**Issue by Irgend-Wer** [corona-warn-app/cwa-documentation#114]
I am not sure if I am at the right and proper adress to suggest this feature. Otherwise I would kindly ask you to move my idea forward.

## What is missing

I would love to see the possibility to move the app to sd card (a feature that is on Android plattform possible for some apps).
## Why should it be included

This would be great for all users of a cheap smartphone with low amount of internal memory like Motorolas Moto E 1. Gen. or other lowbuget phones. So the using of the app will be easier on lowbuget devices.
## Where should it be included

In the documentation it should be included in the section ”Installation”.

**Comment by egandro** [comment]
> Motorolas Moto E 1. Gen.

This device has no BLE.

**Comment by Irgend-Wer** [comment]
> > Motorolas Moto E 1. Gen.
> 
> This device has no BLE.

Oh that's true... So maybe it (moving to sd) would be just a nice, comfortable feature, and such old/low budget smartphones are not able to use the app, anyway.
That leads me to the question:
How much percent of the smartphones used in Germany will be able to use it (circa)?

**Comment by tklingbeil** [comment]
I'm think allowing the install on the SD card is not good, as we need to rely on the app to be apple to constantly download new keys, poll for updates etc (see [developer documentation](https://developer.android.com/guide/topics/data/install-location#ShouldNot)):

> When the user enables USB mass storage to share files with their computer (or otherwise unmounts or removes the external storage), any application installed on the external storage and currently running is killed. The system effectively becomes unaware of the application until mass storage is disabled and the external storage is remounted on the device. Besides killing the application and making it unavailable to the user, this can break some types of applications in a more serious way. In order for your application to consistently behave as expected, you should not allow your application to be installed on the external storage if it uses any of the following features, due to the cited consequences when the external storage is unmounted:

**Comment by treysis** [comment]
@tklingbeil 
USB mass storage isn't being used since Android 4.something anymore. Furthermore, it is clear that the app in general can't guarantee to work 100% of the time. Therefor I don't see any limitation why SD-card storage shouldn't be allowed.

**Comment by Lutzion** [comment]
@tklingbeil
I see your point that installing on sd card is not 100% reliable.
On the other hand it is politically wanted that as many people as possible install the app.
How many of them will buy a new mobile phone because there is no space left on the internal memory?
Wouldn't it be better if they have a not 100 % reliable app compared to they have no app?

**Comment by tklingbeil** [comment]
The current size of the app is ~13MB. I understand that in some cases that might just be too large to install it - but otherwise I would consider that pretty slim.  

Apart from that: It's not only about the app being unreliable: It would fail silently, i.e. the users might have a false sense of security, because they expect the app to work, even though it is not even running anymore.

**Comment by treysis** [comment]
Why would it fail at all? Why wouldn't it fail on internal memory?

**Comment by Lutzion** [comment]
@treysis:
Thomas already linked the android documentation:
https://developer.android.com/guide/topics/data/install-location#ShouldNot

**Comment by treysis** [comment]
@Lutzion And like I wrote before as well: USB mass storage mode isn't used since at least Android 5.0 anymore. This applies only if someone ejects the card.

**Comment by rawabe803** [comment]
I would like to have the possibility to move this app to the SD-Card. It makes sense also on more modern smartphones (such as Samsung A3 (2017)), having not so much memory. Nevertheless the Corona-Warn-App runs on this device on Android 8. 
I belong to the people not throwing away functional devices every year. I cannot understant the constraints against shifting the app to a SD card ("security", "malfunction", and so on). I shift all applications to SD card wherever possible, and had no problem doing that.
