### ISSUE TITLE
Question: Why server-side Key-Generation/ Derivation?

### ISSUE THREAD

**Issue by TomTeeJay** [corona-warn-app/cwa-documentation#115]
For the onboarding process the CWA collects the GUID and sends it to the Verification Server. Server-side this GUID is somehow taken for a key-generation (more documentation or code needed) and a Registration Token is derived. 

Both GUID and Registration Token remain as Hashes on the Server while the Registration Token is sent back to the CWA.

This means, the server is omniscient and "knows" all his clients. But the server also "knows" private keys temporary alongside the hashes of the Device-GUID and Registration Token, used for Authentification. Basicaly the server is enabled to use the GUID-Hash against other collected data, e.g. RKI Datenspende App.

**Question: Why is the key generation not done client side instead of sending GUID and private key back and forth?**

I am missing something? In doubt that this is in accordance with the [CCC checklist](https://www.ccc.de/de/updates/2020/contact-tracing-requirements) I quote (and translate) point  No 5):

> A completely anonymous "contact tracing" without central omniscient servers is technically possible. It is not technically necessary to rely solely on the trustworthiness and competence of the operator of the central infrastructure to protect the privacy of the users properly. We therefore reject concepts based on this as controversial from the very beginning.

**Comment by tklingbeil** [comment]
Hi,

the GUID comes from the already existing Laboratory Information System and was introduced specifically to allow the electronic retrieval of test results.

I don't see how the server knows private keys. Where exactly do you see private keys being generated - and where do you see them used?

There will be dedicated documentation artefacts for the Verification Server, as well regarding the Technical Security Concept and Data Privacy Concept (as mentioned in the README.md).

Best,
Thomas

**Comment by TomTeeJay** [comment]
Alright I missed the point that Figure 3 represents the data flow of results transmission, I accidentally thought this is an onboarding process, I close this isse.
