### ISSUE TITLE
What authority is creating accounts for the TAN web-Interface?

### ISSUE THREAD

**Issue by marcopashkov** [corona-warn-app/cwa-documentation#116]
## Your Question

* Documentation File: [solution_architecture.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md)
* Line / Paragraph:
> The teleTAN is then issued to the officer (4-5)
* Question: Is there some documentation of who creates TAN web-interface accounts - or who counts as employee of a health authority?

This could be a potential weak point if the TANs can be generated by a malicious users. If they gains access to the TAN web-interface server they could sent false "exposure notices" to users.

Would it be possible to only allow TANs to be created when they are linked to a positive Lab result?

**Comment by tklingbeil** [comment]
Hi Marco,

by definition TANs are only created once a registration token is presented to the user (see your last ticket).

TeleTANs are generated while the users are on the phone with either the health authority (they call the users upon a positive test) or when they call the hotline to request a teleTAN. And in those cases only if the users have specifically confirmed that they need a teleTAN.

There will be dedicated documentation artefacts for the *Verification Server*, as well regarding the *Technical Security Concept* and *Data Privacy Concept* (as mentioned in the README.md).

Best,
Thomas

**Comment by tkowark** [comment]
Thanks for your question, @marcopashkov ! I hope that @tklingbeil 's preliminary answer and the upcoming, additional documentation answer your question. Feel free to reopen this issue, if that's not the case.
