### ISSUE TITLE
estimation of download size for "aggregated keys" from CDN

### ISSUE THREAD

**Issue by jbrekle** [corona-warn-app/cwa-documentation#117]
- Documentation File: [solution_architecture.md](../blob/master/solution_architecture.md)
- Line / Paragraph:
> Step 4a: After signing up for notifications in step 1, the user’s phone regularly check on the Verification Server whether test results are available (polling, figure 3, steps 5-8). This way, no external push servers need to be used.
- Question: Is there already an estimation of the file size? Especially for situation with many new infections. What level of QoS can be guaranteed for which level of load?

Background:
I did an estimation myself (very rough, please correct me if I misunderstood). 
I have these assumptions:
Every newly infected user would consent to sharing his keys of the last 14 days.
The keys are randomly regenerated every 15 minutes.
Every key is a 16 byte GUID.
There are 40.000 new infections on a given day. I heard somewhere that this is the estimated the capacity limit of the german health care system. Of course this is a arbitrary number, just for estimation of the worst case scenario before a lockdown.
So if we calculate, each user had 14d * 24h * 4 = 1344 keys in the last 14 days.
40.000 new infections * 1344 keys * 16 byte per key = 860,160,000 byte (~ 860MByte)
Of course with current new infections it's only a fraction. But digital contact tracing is most crucial with high infection rates that might occur in the future.
Each user would have to download that every day. Of course ISP could exclude that from billing, but still you would need a high speed connection, people in remote areas will take a long time to download.
Then my estimation goes on with the distribution server: 
This 860MB file would be downloaded millions of times. Some surveys report 50-70% willingness to use the app. That would mean 860MB * 40.000.000 users = 34400 Terabyte daily. 
Then it would be certainly needed to spread the downloads over the day, to avoid a DOS. But then you would give some users old data. So you would need to implement some kind of rolling window.

**I might be off by a order of magnitude (or more?) in my estimation, but certainly this should be documented better to avoid fundamental design flaws that can not be easily fixed when infections suddenly increase.**

**Comment by raethlein** [comment]
Hey @jbrekle, thanks for your question. The "key" to be generated every 15 minutes you are referring to is the Rolling Proximity Identifier. The keys to be uploaded are the Temporary Exposure Keys (TEKs) (also called Diagnosis Keys when linked to a positive test result). Those TEKs are recreated every 24 hours. 

From the architecture document:

> New identifiers are derived from a Temporary Exposure Key (TEK) that substitutes daily at midnight (UTC) through means of cryptography, which will be explained in more detail in Figure 10. When the TEKs are linked to a positive test, they remain technically the same, but are called Diagnosis Keys.

See also Figure 10 which shows this.
As a result, you upload 14 Keys, not 1344 Keys. So, in your calculation it would be 
40.000 * 14 * 16 byte per key = ~9MByte

**Comment by jbrekle** [comment]
Thank you for the detailed answer.
Oh I should RTF[M](https://covid19-static.cdn-apple.com/applications/covid19/current/static/contact-tracing/pdf/ExposureNotification-CryptographySpecificationv1.2.pdf)...
> Because Diagnosis Keys are sets of Temporary Exposure Keys with their associated
ENIntervalNumber , each of the clients can again derive the sequence of Rolling Proximity
Identifiers that were broadcast over Bluetooth from users who tested positive

Ok, so this makes 360 Terabyte daily, still a big number but probably manageable for a good CDN. 
Is anything like a download delay or rolling window planned?

**Comment by tklingbeil** [comment]
I'd like to refer you to the chapter **_Data transfer and data processing_** of the solution architecture document. There the spreading of the data transfer is explained.

The bandwidth estimations can be found in the chapter **_Bandwidth estimations_**.
Encapsulated in the (Apple/Google) defined protocol buffer, the keys will be 28 bytes each.

As this is also part of the architecture document, I'll close this issue.
