### ISSUE TITLE
Use a static site generator for better UX

### ISSUE THREAD

**Issue by squidfunk** [corona-warn-app/cwa-documentation#12]
I'm the author and maintainer of [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/), a theme for the static site generator MkDocs which generates a static site from a set of Markdown files. The UX is much better than browsing GitHub pages, it includes a client-side search, TOC and great mobile UX. There are also features like [callouts](https://squidfunk.github.io/mkdocs-material/extensions/admonition/#usage), [tabbed content](https://squidfunk.github.io/mkdocs-material/extensions/pymdown/#tabbed), [footnotes](https://squidfunk.github.io/mkdocs-material/extensions/footnotes/#inserting-the-reference), [syntax highlighting](https://squidfunk.github.io/mkdocs-material/extensions/codehilite/) and many more.

![Screenshot](https://raw.githubusercontent.com/squidfunk/mkdocs-material/master/.github/assets/screenshot.png)

It's also [already used by SAP](https://sap.github.io/ui5-tooling/).

I'm happy to help and can submit a PR. Otherwise feel free to close this issue.

**Comment by MalteJ** [comment]
We are currently working on a website for this open source project. Probably we will start with a simple static site without embedded docs, but we plan to integrate this in the future.
So thanks a lot for this offer!
I will keep this issue open and come back to you as soon as we are working on the docs integration.

**Comment by squidfunk** [comment]
Awesome! Happy to assist.

**Comment by SebastianWolf-SAP** [comment]
OK, it took a while.. In the meantime, [our website repo](https://github.com/corona-warn-app/cwa-website) went live and we also made some extensions to it. 

Unfortunately, our first approach to an automated integration of the respective markdown documents from cwa-documentation resulted in some issues (especially with tables and references) which we couldn't resolve with a reasonable amount of resources. As a consequence, we will continue linking the most important documents, but don't continue working on an automated integration of the markdown files and will therefore also close this issue.

However, in case somebody wants to contribute a fully working integration, PRs to cwa-website are always welcome.

Thanks for your understanding.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by MalteJ** [comment]
We could also open a `features/docs` branch so you can provide small increments, work together with other helping hands and don't need to fix the whole documentation thing with just one pull request.
