### ISSUE TITLE
Bandwidth estimations too low

### ISSUE THREAD

**Issue by jbrekle** [corona-warn-app/cwa-documentation#120]
- Documentation File: [solution_architecture.md](../blob/master/solution_architecture.md)
- Line / Paragraph: [Bandwidth estimations](../blob/master/solution_architecture.md#bandwidth-estimations)
> When considering 2000 new cases for a day, a transmission overhead (through headers, handshakes, failed downloads, etc.) of 100% and 30 million clients
- Question: Is this estimation useful? We had already more than [6000 daily new cases](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/2020-03-28-de.pdf). And this app should even support higher cases numbers - or it could fail, when we need it most. [Surveys](https://www.tagesschau.de/inland/corona-tracing-app-101.html) report 47% approval so, 39 million clients. An Oxford survey even reported 70% approval. [Some experts](https://www.research.ox.ac.uk/Article/2020-04-16-digital-contact-tracing-can-slow-or-even-stop-coronavirus-transmission-and-ease-us-out-of-lockdown) aim for 60% for it to be effective. I think the estimations are too low and I hope you can also support higher load.

**Comment by tklingbeil** [comment]
Rest assured. We have taken those higher numbers into consideration as well and are prepared.
