### ISSUE TITLE
QR-Code : Creation and content not clear

### ISSUE THREAD

**Issue by HolgerMayer** [corona-warn-app/cwa-documentation#122]
## Where to find the issue
Solution Architecture
probably in other documents too

## Describe the issue

In the documentation Step 1 (1) it reads

> The QR code contains a globally unique identifier  (GUID).

in Step 1(3) it reads

>  with the data from the QR code 

the last sentence part gives the Impression there is more than only the GUID.

And with the document you mix Format, Content,... Can I use every kind of QR-Code - definitly not.

## Suggested Change
Be more precise and don' t mix data and format.

The data is a test probe identifier(TPI) (what is its function?)
The data format is  a GUID
The exchange Format is a QR Code with a specific data content.

By the way you need at least two equal QR-Code-Labels one for the lab and one for the patient and preferably a third for the doctor as backup (i.e. in case of a lab mixup of tests for verification of the test result). 

You should not forget about the creation of these. There needs to be an Epic for doctors to get / create TPI's as QR-Codes!

How I would write Step 1:

(1) When a test is conducted a test probe indentifier (TPI)  is either created as a set of two (three)  QR-Codes on-site or is already available as a stack of pre-printed QR Code sets of two(three). The TPI consists only of a GUID. The QR code contains only the TPI.
(2) Optionally, they can scan the TPI from the QR code with the Corona-Warn-App (Figure 3, step 1) – if users decide against using the test retrieval functionality of the Corona-Warn-App, they still receive their test results through the regular channels explained before.
(3) When the TPI  is scanned, a web service call (REST) is placed against the Verification Server (Figure 3, step 2), linking the phone with  the TPI  through a registration token, which is generated on the server (Figure 3, step 3) and stored on the phone (Figure 3, step 4).

**Comment by tklingbeil** [comment]
The creation of QR codes is out of scope, as the Laboratory Information Systems already exists, as shown in Figure 1. We can't include the internal details of all external components into our high-level architecture document. The purpose of the document is still to give a high-level overview, i.e. it shall be more easy to read than a maintenance manual. Therefore terms such as "scanning a QR code" are in my opinion fully acceptable.

We also just cannot create the term "Test Probe Identifier" if in the external system the exact thing is only called GUID - technically correct or not: That's just how it is called.

**Comment by HolgerMayer** [comment]
And the moment the Lab System in the future changes the format from QR-Code to something else all your documentation needs to be updated though no content has changed.

**Comment by HolgerMayer** [comment]
You should really revisit the cross-system processes in your analysis. 
Then you should define use cases from an external entity point of view (I.e. Lab, doctor)
These need to include descriptions for the exceptions (alternate flows)

And then you need to implement test cases for each of these alternate flows.

If you don’t you will not get a stable system.
