### ISSUE TITLE
Does the App for Android work for android devices without play services enabled ?

### ISSUE THREAD

**Issue by F3000** [corona-warn-app/cwa-documentation#126]
See this as a general question

**Comment by ironjan** [comment]
See #5 and #52. The Contract Tracing API will be a part of Google Play Services. Consequently, the app will not work on devices without enabled play services.

**Comment by tklingbeil** [comment]
This is correct.

**Comment by F3000** [comment]
Thanks . I hope this works in my setup from my company . 


We use Samsung phones with activated KNOX container . 

Outside the container we deactivate Platz services . Inside it is allowed .

**Comment by tens0rfl0w** [comment]
As stated in [this](https://www.theverge.com/2020/4/13/21220033/android-covid-19-tracking-updates-google-play-contact-tracing) article from 04/13/2020 in "The Verge" about Huaweis approach to implement the Exposure Notification API: 

> "For those phones, Google intends to publish a framework that those companies could use to replicate the secure, anonymous tracking system developed by Google and Apple. It will then be up to Huawei, Xiaomi, and other Chinese manufacturers (or the Chinese government) to decide whether to use the system."
& 
> "..., but did note that it will offer code audits to companies that want to adopt a similar system."

So there is a chance that we will see the Exposure Notification API on Android devices without Google Play services sometime soon. (Or a third party API that is compatible with the official implementation.) But still no official statement.

**Comment by hjacobs** [comment]
This is now solved by the [new open source app available on F-Droid](https://f-droid.org/packages/de.corona.tracing/) :tada:
See also #478
