### ISSUE TITLE
Bandwidth estimation

### ISSUE THREAD

**Issue by tomjoro** [corona-warn-app/cwa-documentation#127]
## What is missing

What is the estimated number of keys that will be uploaded from user with a newly submitted diagnosis?

In the math in section "Bandwidth estimation" am I understanding that you are considering that the average newly diagnosed user only has 14 keys to upload? 

"While each set of 14 diagnosis keys only has the small size of 392 Byte, all newly submitted diagnosis keys of a time period need to be downloaded by all mobile phones having the application installed."

It seems that an average user would have at least 10x this number of key (around 140?) from collecting them over the 14 day time period. This means each diagnosed user would upload 5.4KB of data. If there are 2000 newly diagnosed users per day, then this is 11MB of data which needs to be sent to the 30 millions users. Again, instead of 42.8TB I get almost 10x the data requirements ~400TB.

## Why should it be included

Accurate bandwidth estimation will give better understanding of the cost.

## Where should it be included

Bandwidth estimation

**Comment by tklingbeil** [comment]
Related to #120. 

Please read the corresponding section of the architecture document.

A user will at most upload 14 diagnosis keys, each with 16 Bytes payload and 28 Bytes total size including metadata in the protocol buffer defined by Apple/Google.

The users only collect RPIs from other devices and those are supposed to NEVER leave the device.

**Comment by tomjoro** [comment]
Thanks. My mistake. I didn't understand that those TEK keys that are rotated once a day and the actual contacts are cryptographically secured using that rotating key. So regardless of number of contacts, the TEK amount is constant for uploading.
