### ISSUE TITLE
Hotline creating teleTan missing in figure 4

### ISSUE THREAD

**Issue by HolgerMayer** [corona-warn-app/cwa-documentation#128]
## Where to find the issue
Solution architecture figure 4

## Describe the issue
Hotline is missing creating a teleTan

## Suggested change
Add „Hotline“ below employee Health Authority oder draw an individual rectangle for the hotline with neccessary  data flow

**Comment by tklingbeil** [comment]
The hotline would most likely be acting on behalf of the health authority. That's why we consider it already covered.

**Comment by HolgerMayer** [comment]
In figure 1 they are both displayed.
In the text they are both mentioned with there own reasoning.
And they are legally very different. They both probably have very different access to verification information. They probably have a quite different employment background (security!)

If you don‘t consistently split them you especially on the high level you  probably miss existing differences.

**Comment by tklingbeil** [comment]
The main target of the solution architecture document is to present an overview and clarify how the End-to-End process is being realized. As you can see, Figure 4 focuses on the interaction between the server components, not on how the user creating the TAN is being authenticated. 

**Please don't forget that there will me in-depth documentation for the Verification Server, as well for the Portal server, where such issues will be adressed**

**Comment by HolgerMayer** [comment]
So you write this only for „interested persons“ to understand while you use a different set of documentation internally for requirements?

**Comment by tklingbeil** [comment]
No. But there are different detail levels with regards to individual artefacts of the documentation.

As you can see [here](https://github.com/corona-warn-app/cwa-documentation/blob/master/README.md#technical-documentation), more detailed documentation will be published soon.
