### ISSUE TITLE
Can sorting the diagnosis keys save space?

### ISSUE THREAD

**Issue by marcopashkov** [corona-warn-app/cwa-documentation#132]
## Your Question

* Documentation File: [solution_architecture.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md)
* Line / Paragraph: 
> The possibility to identify temporary exposure keys belonging together (i.e. to the same user) is given, as they are posted together – resulting in them being in a sequential order in the database. To prevent this, the aggregated files will be shuffled, e.g. by using an ORDER BY RANDOM on the database side while fetching the data for the corresponding file. Alternatively, returning them in the lexicographic order of the RPIs (which are random) is a valid option as well.
* Question: Did you test whether there is a payload size difference when considering `ORDER BY RANDOM` vs `lexicographic order`?

In a very simplified version of this problem I was able to save ~4% of payload size, which could add up if it holds true for the production data format.

```py
import uuid
import gzip

DAYS = 14 # 1 key is stored per day per person
CASES = 6000 # number of people that have a positive result (sliding window of 14 days)
DIAGNOSIS_KEYS = DAYS * CASES

def main():
    keys = []
    for x in range(DIAGNOSIS_KEYS):
        keys.append(str(uuid.uuid4()))

    unsorted_keys = "\n".join(keys)
    sorted_keys = "\n".join(sorted(keys))

    with gzip.open("unsorted_keys.gz", "wt") as us:
        us.write(unsorted_keys)
    with gzip.open("sorted_keys.gz", "wt") as so:
        so.write(sorted_keys)

if __name__ == '__main__':
    main()
```

**Comment by tklingbeil** [comment]
Thank you for your research! In practice, those diagnosis key will be part of a protocol buffer, which also contains metadata (see Figure 8), but I assume the effect remains.

A thing you might need to consider is that not all keys of a single day are put into a single package. When doing the test with a bath size of 500 cases, I was able to achieve ~2,5% savings on average. Still very good. 

However, this question probably belongs to the cwa-server repository, where you can then also find the specific implementation. I'll still add a note to the architecture document.
