### ISSUE TITLE
Is it really coming in Mid June?

### ISSUE THREAD

**Issue by capsload2** [corona-warn-app/cwa-documentation#136]
I just saw some reports, that this CoronaWarn App is coming in Mid June.

Does it really take that long?

**Comment by SebastianWolf-SAP** [comment]
Thank you for your request. However, I'd like to ask you for you understanding that we don't comment on timelines here on GitHub.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
