### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by AndiLeni** [corona-warn-app/cwa-documentation#138]
Hello,

while reading the documentation I came across the sentence "Devices starting with Android and integrated BLE chips will be supported."
This suggests the lack of a specific Android version, from which the app should work.
Maybe you could also specify an API level here.

* Documentation File: solution_architecture.md
* Line / Paragraph: #mobile-applications

**Comment by SebastianWolf-SAP** [comment]
The requirements and minimum API level are described precisely by Google in their API documentation, see https://static.googleusercontent.com/media/www.google.com/no//covid19/exposurenotifications/pdfs/Android-Exposure-Notification-API-documentation-v1.3.2.pdf

It currently says Android 6.0+, API level 23 - of course with the latest updates to Google Play Services as they contain the Exposure Notification Framework.

As the external documentation may be updated without prior notice and as it‘s defined exclusively by Apple and Google, we don‘t mirror content from there in our official documents.

**Comment by SebastianWolf-SAP** [comment]
Sorry for the premature issue closing. Just saw that we mentioned the minimum iOS version as well and that the minimum Android version is missing. We‘ll update that...

**Comment by MikeJayDee** [comment]
Please note that the Google reference app uses a minimum API version of 21 (Android 5.0):

https://github.com/google/exposure-notifications-android/blob/master/app/build.gradle

I'm not sure if this is an error, or whether Google is still discussing on whether to use version 21 or 23. This would make a significant difference as a minimum API version of 23 would cover ~85% of Android devices, whereas a minimum API version of 21 would cover ~94%.

**Comment by tklingbeil** [comment]
Google specifies this as follows: 

> For your app to work on a device, the device must be running Android version 6.0 (API version 23) or higher.

If you have a look at the change log within [Google's documentation](https://static.googleusercontent.com/media/www.google.com/no//covid19/exposurenotifications/pdfs/Android-Exposure-Notification-API-documentation-v1.3.2.pdf), it is specified under version 1.3

> Updated the minimum supported version from API 21 (Android 5.0) to API 23 (Android
6.0)

**Comment by MikeJayDee** [comment]
I agree with this, but let's keep an eye on those two issues:
https://github.com/google/exposure-notifications-android/issues/16
https://github.com/DP-3T/dp3t-sdk-android/pull/96
