### ISSUE TITLE
Figure 3 Flow (7) label title

### ISSUE THREAD

**Issue by HolgerMayer** [corona-warn-app/cwa-documentation#140]
## Where to find the issue
Figure 3 Flow (7)

## Describe the issue
For consistency reasons the text inside the rectangle should read "Test result" and not only result

## Suggested change
Please change text

**Comment by tkowark** [comment]
Thanks for pointing that out, @HolgerMayer . We'll look into it!

Maybe also just as a quick suggestion: Such minor issues are also great candidates for Pull Requests. @tklingbeil and colleagues are constantly working on many aspects of this and the upcoming documents. Hence, just having something to approve could really reduce the time it takes until fixed (and is usually not more time consuming on your end compared to creating the issue itself).

**Comment by tkowark** [comment]
As @tklingbeil just reminded me, changing the graphics, of course, is not that simple. So please ignore that remark for this issue - mea culpa!

Nevertheless, if you have any improvements where also a PR makes sense, we encourage you to use this method to get your input reflected in the documents much faster. Thanks again for all your input!

**Comment by HolgerMayer** [comment]
I could edit it (Affinity Designer) but I would not because you probably model in a design tool and export the SVGs. In that case your model needs to be updated after a change in  an image file. And that would very fast lead to inconsistent documentation.
