### ISSUE TITLE
Is it possible to be added as a testflight tester ?

### ISSUE THREAD

**Issue by aminreh** [corona-warn-app/cwa-documentation#141]
Is it possible to help u guys by being added as an external tester to Testflight? I am more than happy to provide my apple id if i can help.

**Comment by ironjan** [comment]
To quote @raethlein (4 days ago): "As of now, Testflight builds will only be available for the project team and the RKI." - https://github.com/corona-warn-app/cwa-documentation/issues/92#issuecomment-630662127

**Comment by tkowark** [comment]
As @ironjan (and @raethlein ) pointed out, this is currently not possible. We'll let you know as soon as this changes!
