### ISSUE TITLE
Extend Figure 3 Verification Server data with test result flag

### ISSUE THREAD

**Issue by HolgerMayer** [corona-warn-app/cwa-documentation#142]
## Where to find the issue
Figure 3 inside the Verification Server rectangle

## Describe the issue
Inside the Rectangle there should be three different data sets linked together.

- hash(GUID) 
- hash(Registration Token)
- test result Flag (unkown , plus , negativ) 

textual description Step 3 reads:
"As soon as the test result is available (i.e. the samples have been processed), the software running locally in the lab (lab client) transmits the test result to the Laboratory Information System, together with the GUID from the QR code. The Laboratory Information System hashes the GUID and the test result. **It is made available to the Verification Server through a REST interface**."

There are to possible scenarios
1)  Double polling
- Phone polls Verification Server
- Verification Server polls LIS
2) Single polling
- LIS initiates test result flag transfer to Verification Server
- Phone polls Verification Server for results
- If flag is set positive Verification Server  sends test results to phone
--if test results include more than a simple positive , negativ answer the Verification Server must first poll the LIS for detailed test results. But only one time.

There should be no privacy problems with version 2 because there is no transparent connection between GUID, registration token and personal record. Only the Phone nows the registration Token.

Double polling of results for thousands of users tested is a bit inefficient.

## Suggested change
extend data model in Verification Server for result token

**Comment by tklingbeil** [comment]
The document has been update to show a new component, the **Test Result Server**, which receives the test results from the Lab Information System, which in turn is then queried by the Verification Server (see the [specific documentation](https://github.com/corona-warn-app/cwa-verification-server/blob/master/docs/architecture-overview.md) for more information.

Those components are very close to each other (you could actually compare them to micro services), so the "double polling" from (2) is nothing to worry about.

**Comment by mynchau** [comment]
Hi Holger, 

As tklingbeil commented earlier, the document has been updated. Please feel free to open a new issue in case you see other aspects of this issue not addressed. 
Best regards
MC
Corona Warn-App Open Source Team
