### ISSUE TITLE
Registration Token not necessary for teleTAN-Workflow

### ISSUE THREAD

**Issue by HolgerMayer** [corona-warn-app/cwa-documentation#143]
## Where to find the issue

In and around figure 4

## Describe the issue

If the user enters a teleTAN he is authorized to start an automatic upload if the teleTAN is valid and not used yet.

- The user enters the teleTAN
- He is asked to acknowledge that his Diagnosis Keys are uploaded. 
- If he declines a message to disable the teleTAN is send to the verification server
- If he accepts the teletTAN is send to the verification server (POST /TAN)
- the verification server checks the validity of the teleTAN (existing and unused)
- If teleTAN is invalid  - do nothing or send error
- if teleTAN is valid create TAN and send to Phone immediately 

This also means the association hash(TeleTan) and hash(Reg. Token) is not necessary.

## Suggested change
Change protocol between Phone and Verification Server in teleTAN workflow

---
Internal Tracking ID: EXPOSUREAPP-1920

**Comment by tklingbeil** [comment]
I think you have forgotten one aspect: There are multiple (currently 2) uploads required.

As the teleTAN needs to be short-live, it is exchanged for the registration token.

**Comment by HolgerMayer** [comment]
Well yes, but lets read the sentence concerning this:

> This means, the registration token may not be invalidated after the first upload but must remain active. The TANs sent to the Corona-Warn-App Server are only valid for a single use. In case of the teleTAN, an **additional** registration token is created, which then allows the application to retrieve TANs for individual uploads.

This additional (two!) is nowhere to be seen in the flow! And how do you verify that the token is used only once (or twice). And if you always need two TANs (besides sending them on midnight what would be very bad because everybody calls at midnight) why not keep them ready for exactly two uses every time?

Now we are back to the registration token. It in this case the registration token is a two time „ Transaction Access Number“ to get two separate TANs.

You are right we need this number, but for a different reason than the QR-Code-Flowe where a long time between entering and results happens. And the reason is at least smelly.

**Comment by tklingbeil** [comment]
Yes... Wording... There is only one registration token.

**Comment by HolgerMayer** [comment]
**Assumption  1:  The attacker can sniff data like the TAN from data transfer.** 

Then the registration token is no save method either within the interval from first generation to second TAN.

**Assumption 2: We only want to disable multiple use of teleTANs**

Then there are two possibilities:

- Use a registration token (the current case)
- Use the previous TAN for verification on the Verification Server side

The latter can be used as security mechanism by storing the first tan as a validator for the second access from the phone

In this case the data tuple on the verification server would store the TAN we send in step (13). Then when the phone polls the second time it sends together with the registrationToken (or teleTAN) the TAN it used to get the Diagnosis Keyes as a verification token. The Verification server checks if 

a) there is a record for the registration key or teleTan
b) verifies that the sent TAN was enabled as a first data access TAN
c) only then it sends a new TAN to the Phone (and sets the tuple to not valid for further TAN generation unless you want to allow further polling, then store the last used TAN for later verification)

Now the registration token is not necessary under assumption 1 because TAN and Registration token are sniffable - but because the TAN is sent later in case of this scenario an attacker has less time to decrypt or do harm than with a registration token.

Lets put it all together :

There are in fact three different access controllers:

- The teleTan to verify the first access 
- The registration token to verify the first and second access
- The TAN to verify the Access to the CWA Server

Then why not using the TAN for nonvisible accesses? 

After verifying the first access on the Verification Server the following accesses describe a very simple state machine. The state is the TAN. Every request to the verification server gives you a new TAN. Access to the verification server is only possible

- The first time with a teleTAN without a tan returning a TAN to the phone
- All  other times with the teleTAN and the previously returned TAN

So instead of a registration code that is long living you use shorter living TANs. The attack time for an attacker is reduced from the lifetime of a registration token to the time between the usage of two TANS.

**Comment by BrittaTSI** [comment]
We will check this topic and consider if it makes sense to add it to our backlog for future releases.
@SantiagoJay

**Comment by Ein-Tim** [comment]
Nearly two years passed without any further development on this topic. Is there any update available here @tklingbeil / @BrittaTSI?

**Comment by larswmh** [comment]
Closing this issue as the related internal ticket is set to `obsolete`.
