### ISSUE TITLE
Consider Laboratory Server push vs pull of test results

### ISSUE THREAD

**Issue by theodiefenthal** [corona-warn-app/cwa-documentation#145]
In the current architecture, any unauthorized user (with a valid but easy to obtain registration token) can ask for testresults. The query for the testresult is forwarded to the laboratory server which is out of control of the corona app environment. 

There is no documentation about the laboratory server available yet, but I have some assumptions about it.
As per doc, the laboratory server is a pre-existing component. 
I assume it to be not running on OTC and not being as scalable as all other CWA components.
I also assume that those systems are usually not exposed to the public internet and that for the current CWA architecture to work, there need to be some firewall rules, VPN or similar connecting CWA services with the laboratory services/network. 
It would be great if you could comment and falsify those assumptions, but if they are true, then this raises some concerns for me: 

The laboratory system is probably much more vulnerable to DoS attacks or just very high peak loads from all running app instances querying there results regularly. 
If CWA would have a downtime e.g. due to a DoS attack, the biggest harm is that users might get notified a bit later about a positive test and contact to positive tested persons. If the laboratory server is going to be done e.g. due to a DoS attack, I assume that the employees can't work properly anymore because they can't enter results into the system. 

To conclude, the current module of asking the laboratory server for new results opens up a huge list of security and stability concerns. Especially, if an attacker gets access to CWA, he can also try to access laboratory systems. 

A solution to all this concerns would be that the laboratory system publishes new test results to the verification service (e.g. via a mTLS connection) where they are stored for some time like 14 days. The GUIDs can still be emitted hashed by the laboratory system so that it should cause no problems in terms of GDPR.

**Comment by tklingbeil** [comment]
`assumptions = false`

It’s also a cloud service running in the same cloud environment.

Duplicate of #80.

More information on security aspects and other components will follow.
