### ISSUE TITLE
Cluster data amount by region ids

### ISSUE THREAD

**Issue by oberinspector** [corona-warn-app/cwa-documentation#146]
Proposal:
Each app instance has an e.g. 2 byte region id which is provided or selected at time of installation. Large countries may have multiple regions and small countries maybe only 1 or 2. Goal ist to get almost equipartition regions related to population and expected infection rate. Also the regions must be large enough to respect the privacy of the users.

Each app sents own region id with the BT beacon and the receiving app seperates and collects all received region ids. So 2 Bytes of the BT payload would be needed to transfer own region id.

In case of infection and authorisation of a health organization the app uploads the EphIds of the acquisition period together with the own region id.

Apps retrieve only EphIds from infected individuals with the, during the acquisititon period, received region ids. For the vast majority of users this will only be one region id.

With this proposal it should be possible to have only one app for all participating countries and no national app solutions.

**Comment by oberinspector** [comment]
Same as [Cluster data amount by region ids](https://github.com/DP-3T/documents/issues/302) at [DP-3T](https://github.com/DP-3T/documents)

**Comment by tklingbeil** [comment]
We have also thought about that.
However, broadcasting the region ID is currently not part of the Exposure Notification framework, so it's not possible to build this.

Having one single app for all countries is a completely different approach, which is out of our scope (as we are developing a national app).

**Comment by tkowark** [comment]
Thanks for bringing up this idea, @oberinspector ! as tklingbeil mentioned, we are currently focused on the exposure notification framework. We will, however, closely monitor the discussions around the DP-3T issue you linked! To keep this repo focused on the current approach, I'd close this issue here.
