### ISSUE TITLE
Issue Locking/Closing

### ISSUE THREAD

**Issue by oiime** [corona-warn-app/cwa-documentation#149]
Hello,

I really don't want to get too much into your internal processes, but I do not think it is beneficial to close or limit issues when they are still not implemented.unless they are being spammed.

eg: #134  and #61

**Comment by SebastianWolf-SAP** [comment]
Dear @oiime,

we only lock issues if discussions become heated, off-topic or if they are being spammed. We close issues for several reasons - they might be out-of-scope, it might be the wrong forum here, the issues might have been fixed, the question might have been answered etc. 

The rationale behind locking #61 was simple: We stated several times that the source code of all components will be published eventually, soon and completely. Moreover, we also said that we can't give you a precise date as this depends on several aspects and this is also different from sub-project to sub-project. Despite these clear statements, we've seen several separate issues asking the same question in different nuances like "where is the source code", "when will the source code be released" etc. In the end, the overall amount of different issues with the same content lead us to the decision to keep one single issue open, but lock the conversation. As you could see in the past days, we delivered according to our promises and will continue to do so. Once we have open sourced all sub-components, we will close #61 accordingly.

And in #134 we provided a very detailed explanation/answer to the question you've raised. If you think that the question wasn't answered to your satisfaction, comments are still open. Please put in your thoughts there and we will see if we can give more details and maybe even reopen the issue if we see a chance that additional discussions solve the discussion in a mutual agreement.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
