### ISSUE TITLE
Choose a Platform that Supports Private Downstream Forks in Syria

### ISSUE THREAD

**Issue by Bengt** [corona-warn-app/cwa-documentation#15]
Disclaimer:

I am not a lawyer and this topic touches on international law, so verify before making a decision.

User Story:

> As a user located in Syria, I want to fork CWA and work on it in private, while downstreaming changes from this repository.

GitHub does not allow that:

> [...] due to U.S. trade controls law restrictions, GitHub is unable to provide private repository services [...] to accounts in [...] Syria [...].

Source: https://help.github.com/en/github/site-policy/github-and-trade-controls

In contrast to the US', the EU' sanctions on Syria are more narrow in scope:

> The [...] export of arms [...], as well as equipment which might be used for internal repression, to Syria [...] shall be prohibited [...].

Source: https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02011D0273-20111114

The EU regulation allows anything that is not immediately an arm to be exported:

> [The restriction] shall not apply to [...] non-lethal military equipment or of equipment which might be used for internal repression, intended solely for humanitarian or protective use [...].

Source: https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02011D0273-20111114

Thus, granting users in Syria access to a code hoster located in the EU *seems* (IANAL) legal. Since paid GitHub instances are sold by the same company, they still restrict access from Syria.

> © 2020 GitHub, Inc.

Source: https://github.com/enterprise

Instead of GitHub, fulfilling this user story would require using a code hoster based in a EU member state without additional export restrictions prohibiting access from Syria. The Netherlands for example have not decreed any sanctions against Syria on their own:

> [Absence of a statement at the relevant page.]

Source: https://www.government.nl/topics/international-peace-and-security/compliance-with-international-sanctions/sanctions-against-syria

In the Netherlands, there is GitLabHost, which is a hosted GitLab service:

> Fully managed GitLab hosting

Source: https://gitlabhost.com/

GitLab endorses GitLabHost by naming them in their documentation:

> Some 3rd party vendors also offer a single-tenant managed offering, such as GitLabHost.

Source: https://about.gitlab.com/gitlab-hosted/#as-an-existing-githost-user-what-options-do-i-have

GitLab is open source and can therefore be hosted by anybody:

> GitLab [...] the leading collaboration tool for DevOps

Source: https://about.gitlab.com/

Workaround:

A user based Syria who wants to work downstream to this repository in private could use GitLabHost on their own like this:

```
[                     GitHub.com                        ]
user@github/cwa-public  <-- mirror-fork -- cwa@github/cwa

                  ↓                  mirror using a personal access token of GitHub's API

user@gitlabhost.com/cwa-documentation-public --- fork + merge request --> user/cwa-documentation-private
[                                          GitLabHost.com                                               ]
```
Note that GitLab supports this, but it does not actually work currently, due to a bug. See:

https://gitlab.com/gitlab-org/gitlab/-/issues/217571

However, such a workaround requires the user to switch between code hosting platforms.

Fix:

Please consider using a platform which supports this user story on its own.

**Comment by TomTeeJay** [comment]
basically touching my closed issues:

https://github.com/corona-warn-app/cwa-documentation/issues/9
https://github.com/corona-warn-app/cwa-documentation/issues/11

It seems to me that SAP and Telekom are already excluding and discriminating users in the design process.

**Comment by s-martin** [comment]
The scope of this app is for Germany.
While it would be desirable that this app could be used and forked everywhere I don't think that should be the biggest concern right now.

**Comment by niklas2810** [comment]
I'm not quite sure how relevant this user story is for the repository. This project is obviously primarily focused on Germany and therefore the German developer community, even though they explicitly want to address "interested parties in the global developer community who do not speak German" (as the authors wrote in the README). However, I don't think that the potential exclusion of Syrian users, even though it's unfair, would justify a complete switch of the version control platform.

**Comment by TomTeeJay** [comment]
> Please keep in mind that GitHub is an industry standard and therefore already widely adopted,

Eh... not really. Git is a standard not GitHub. In addition to this issue Chinese Developers are blocked as well by GitHub and who knows how the US administration will react to EU tarriffs or  german cars in the future?

**Comment by Ablesius** [comment]
@TomTeeJay @Bengt you could always contribute via patches sent via mail, i. e. by git-send-email. You're not forced to use Github. Git is decentral by design.

**Comment by Ryuno-Ki** [comment]
The mail address was mentioned in https://github.com/corona-warn-app/cwa-documentation/issues/9#issuecomment-627868171

**Comment by TomTeeJay** [comment]
> The scope of this app is for Germany.

May I ask then why the primary language is English when the scope of the App is Germany?

**Comment by ceedee666** [comment]
I think this is obvious. Not only German developers will be working on the app.

**Comment by Bengt** [comment]
> [...] I don't think [this app could be used and forked everywhere] should be the biggest concern right now.

@s-martin This limitation of GitHub discriminates against people based on their current country of residence. GitHub is an US-based company and thus abiding US law. But I would expect SAP and T-Systems as a contractor of the German state to be bound by German and European law. Specifically, the German constitution (Grundgesetz) prohibits discriminating against people for various reasons. The EU' regulation does not legitimate denying access to Syrian residents, either. How is this not a concern?

**Comment by s-martin** [comment]
See https://github.com/corona-warn-app/cwa-documentation/blob/master/README.md#working-language

**Comment by Bengt** [comment]
> [...] I don't think that the potential exclusion of Syrian users, [...] would justify a complete switch of the version control platform.

As far as I can see, this is the only repository and it is not even integrated in GitHub Actions, yet. Does not seem to bad for me, given that GitLab can even import virtually anything from Github.

**Comment by niklas2810** [comment]
> As far as I can see, this is the only repository and it is not even integrated in GitHub Actions, yet. Does not seem to bad for me, given that GitLab can even import virtually anything from Github.

This repo already exists and even though they don't make use of GitHub-only features yet, switching the repository would cause a lot of confusion (e.g. this repository was already mentioned in various articles. Adding a permalink to GitLab would be a suboptimal soltion, staying here simply makes more sense than taking this extra mile.

Syrian developers can participate via mail, as @Ablesius and @Ryuno-Ki already mentioned (if there actually are Syrian developers who really want to work on the code as this project's focus is Germany).

**Comment by tkowark** [comment]
Thanks @Bengt for raising these concerns. Since the the project is open-source under the Apache 2.0, everybody can just setup a repository mirroring to GitLab or any other Git server by themselves.

Also, as already mentioned in https://github.com/corona-warn-app/cwa-documentation/issues/9#issuecomment-627868171, it is possible to contribute without creating a Github Account just via email.
