### ISSUE TITLE
Get a new prompt after changing settings

### ISSUE THREAD

**Issue by benekuehn** [corona-warn-app/cwa-documentation#151]
* Documentation File:
scoping_document.md
* Line / Paragraph:
> E01.03, E01.04, E01.05 
* Question:
What happens after I turn notifications on and successfully onboard but afterwards turn either bluetooth, the COVID-19 exposure logging or notifications off? Do I get a new prompt when opening the app again to make the user aware of the necessity?

**Comment by benekuehn** [comment]
To specify, E03.03 talks about changing in the app settings but on iOS the notification settings, BLE and exposure notification are handled through the settings app and the app cannot show me any consequences before disabling them.

**Comment by tkowark** [comment]
@benekuehn as visible in the ui screens and the current app status, users will see this information prominently on their home screen.
