### ISSUE TITLE
Finding information/FAQ before agreeing on any terms

### ISSUE THREAD

**Issue by benekuehn** [corona-warn-app/cwa-documentation#154]
* Documentation File:
scoping_document.md
* Line / Paragraph:
> E02.01
* Question:
How can a user reach the menu to get more information when he is prompted to agree on terms, BLE, etc? The FAQ and links to further information should be accessible at all times in my opinion.

**Comment by tkowark** [comment]
FAQs and all documents are already available on coronawarn.app and there are currently implementations underway to add download links for terms of use and data privacy documents directly to the apps.
