### ISSUE TITLE
Where to find the terms of use and data privacy information at any time

### ISSUE THREAD

**Issue by benekuehn** [corona-warn-app/cwa-documentation#155]
## Where to find the issue
> scoping_document.md / E02.05 

## Describe the issue
All other user stories in this category (E02.01; E02.02; E02.03; E02.04) specified the information to be available in the menu.

## Suggested change
Please specify where this information will be found to be precise and consistent.

**Comment by benekuehn** [comment]
@raethlein according to the iOS app the terms of use and data privacy information is also located in the menu "App Informationen". Should I update the documentation?
![Simulator Screen Shot - iPhone 11 - 2020-05-31 at 14 19 13](https://user-images.githubusercontent.com/41262108/83352144-e64d7f00-a349-11ea-8fcf-6d82121d5532.png)

**Comment by tkowark** [comment]
Hi @benekuehn , the scoping doc states that `The app provides simple access to the terms of use and data privacy information.`. This includes the menu, but let's not limit it to that particular spot in the scoping document.

**Comment by benekuehn** [comment]
@tkowark was just mentioned for all other in their respective user stories but not in this one. But I am fine with how it is!
