### ISSUE TITLE
Second notification inside the app besides system notification possible?

### ISSUE THREAD

**Issue by benekuehn** [corona-warn-app/cwa-documentation#156]
* Documentation File:
https://github.com/corona-warn-app/cwa-documentation/blob/master/scoping_document.md#exposure-contact-with-an-infected-person
* Question:
Is there a way in the exposure notification API that allows the cwa app to notify me inside the app as well so that I get notified regardless of my notification settings? (send all to notification center on iOS for example)

**Comment by tkowark** [comment]
Thanks for your question, @benekuehn .

Do you have something like a [modal alert](https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/modality/) in mind, or are there any other other properties that the notification should have?

**Comment by benekuehn** [comment]
@tkowark yeah, guess a modal alert seems fine. But I can also think of directing the user directly to the page she gets to after pressing on the system notification. Just to eliminate the possibility that a user does not notice that she has been exposed

**Comment by tkowark** [comment]
Thanks for the clarification! Unfortunately, I do not (yet) have a concrete answer for this and your other questions regarding the UX. 

Can we kindly ask you to bear with us for a couple of more days and check your questions again, once UX documentation and the real implementations are available? We'll give you a short notice in this issue, once this information is available.

**Comment by benekuehn** [comment]
@tkowark okay, thanks for letting me know and please do ping me :)

**Comment by tkowark** [comment]
@benekuehn as visible in the ui screens and the current app implementation the risk level is prominently displayed on the app's home screen in case there were any recent exposure events
