### ISSUE TITLE
Is it possible to use the "exposure notification API" on Android without Google Play Services?

### ISSUE THREAD

**Issue by feinstaub** [corona-warn-app/cwa-documentation#157]
Hello,
I could not find information about whether it will be possible to install and use the app without the need for Google Play Services or another implementation detail that requires the user to open and use a Google account. This information would be helpful for all LineageOS users.
Thank you in advance for your feedback!

**Comment by tkowark** [comment]
Thanks for your question, @feinstaub . Could you check whether #5 answers your question and close this issue, if that's the case?

**Comment by feinstaub** [comment]
Yes, this gives some answers. Thanks for the reference.
