### ISSUE TITLE
Process for False Positive

### ISSUE THREAD

**Issue by herionhonig** [corona-warn-app/cwa-documentation#161]
## What is missing

If there was made a mistake by the lab resulting in a false positive. Is there planed any process for revoking this lab result? 
Otherwise, there are actions started unnecessarily with some consequences e.g. quarantine for victim and contacts.
- revoke lab result *before* user publishes it in cwa
- revoke lab result *after* user publishes it in cwa

## Why should it be included

see above

## Where should it be included

integration in architecture

**Comment by tklingbeil** [comment]
The issue here is that the Exposure Notification Framework on the mobile devices is pretty much stateless, i.e. there is no way of revoking a single set of diagnosis keys.

Unfortunately, I currently don't see a proper way to revoke a false positive.

**Comment by MikeJayDee** [comment]
False positives are rare in the first place, but I think it will be even much rarer that a false positive will be identified as such sufficiently quickly for such a revocation to have any impact.

**Comment by sventuerpe** [comment]
@tklingbeil Does any of the involved parties – Gapple, our Federal Government, you developers – have a roadmap beyond version 1.0?

@MikeJayDee Has anybody done risk assessment across the entire testing and notification process to figure out failure modes and effects, and estimate their probability? There are multiple sources for errors: the tests themselves, the testing procedure and handling of results, BLE-based contact tracing. Do we have the slightest idea how reliable or unreliable the whole thing is going to be in the end?

**Comment by mh-** [comment]
BTW, Google's [recommendation](https://github.com/google/exposure-notifications-server/blob/master/docs/server_functional_requirements.md) is: "You should design your database to accommodate bulk deletion due to abuse, broken apps, human error, or incorrect lab results."

**Comment by tkowark** [comment]
As @tklingbeil answered the initial question, I'll close this issue. If you have further, concrete questions regarding roadmaps and risk assessment, we kindly ask you to raise them in separate issue to increase search-ability of the repo.

Best regards,
TK
Corona Warn-App Open Source Team
