### ISSUE TITLE
Including personal risk level (e.g. through transmission risk level)

### ISSUE THREAD

**Issue by lennarto** [corona-warn-app/cwa-documentation#163]
## What is missing
Currently I don't see that the personal risk level is included in the Corona Warn App. 
Or is it not planned due to privacy issues? 

## Why should it be included
If I have a high personal risk, such as pre-existing conditions ("Vorerkrankungen"), the overall risk level might be higher. 

## Where should it be included
The personal risk level could be included in the app-defined transmission risk level. 

### Documentation:

https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#risk-score-calculation
> Note that the transmission risk level plays a special role: It can be defined by the app and be associated with each individual diagnosis key (i.e. specific for each day of an infected person) that is being sent to the server. It contains a value from 1 to 8, which can be used to represent a calculated risk defined by the health authority.

https://developer.apple.com/documentation/exposurenotification/enexposureconfiguration
> Transmission risk is intended to reflect the status of infection in the affected user and its effect on risk of transmission. The value is based on the affected user’s symptoms, when symptoms first appeared, level of diagnosis verification, or other determination from the app or a health authority.

**Comment by tklingbeil** [comment]
The transmission risk level does not relate to your personal level of infection, but it relates to an individual's level of transmitting Covid-19.

The API requires it to be determined on the local device for each individual diagnosis key (i.e. each day) before it is uploaded to the server. According to the documentation, it could for example depend on symptoms, onset of symptoms etc.

The personal infection risk is something different and is currently not within the scope of the app.

**Comment by MikeJayDee** [comment]
I don't think that's relevant as the app cannot protect against infections. So once you are notified it is already too late to prevent infection.

However, what is relevant is the personal risk level of the contact persons. Assuming the risk level of the contact is communicated to the user (I hope it is), I assume that people would behave sensibly. If I were to receive a risk level 1 alert, even if I am not asked to isolate, I would probably not visit an elderly relative.
