### ISSUE TITLE
Allow to track GPS (without sharing, for local user only)

### ISSUE THREAD

**Issue by theodiefenthal** [corona-warn-app/cwa-documentation#164]
With the latest corona virus update of Christian Drosten (episode 44), it seems to become much more important to identify "clusters" quickly. 

The idea is that we should be able to react as early as possible on an identified cluster and if we could quarantäne the people in a cluster quickly, we could control the virus much better. 

Therefore, I propose to implement the following user story:

"As a user, in case I got positively tested for Corona virus, I want to be able to see the locations I've been to in the last few days with the exact time span I stayed there". 

With the news from the podcast, it could become much more important to tell the health authority at which places I have been in the last few days in order to identify clusters and notify contact people there. (even if I wasn't in direct contact, e.g. <2m to those persons, but in the same room). If I am asked today where I have been in the last few days with exact timing, e.g. at which time I was at a local restaurant, it will be hard to tell for me. But if I see my GPS positions on a map over the course of the last days, it becomes easy to tell which locations I were at and at which times exactly. Of course, GPS will not identify e.g. at which floor or room in a building I've been to, but if I see "On that day, I was in that building", I will easily remember where I've been there and what I was doing there. 

This can be implemented with full privacy, i.e. there is no need to upload the GPS data, but store it locally on the device only. If I get tested positive, I can decide which information I share looking at the GPS history and notify the health authority about places and times.

Of course, such tracking apps exist already, but I think, asking the user to install two apps will increase the burden on the user. Furthermode, I can think of a manually updated database of the health authority, collecting clusters with rough GPS position, description and times. My phone could download those events the same way as it downloads diagnosis keys and if it finds a match in GPS and time, I could be notified about it with more details (e.g. telling me that there was a cluster in that building, floor 13, course of lecturer Hans Müller about privacy) and I can identify if I was part of that specific cluster and if I feel so, ask for a test and maybe self-isolate myself correspondingly. 

As GPS tracking is very battery intensive operation, the user should be able to opt-in to that feature and decide accuracy (GPS or Cell-phone) and record-interval of the position. I think, a rough tracking like one record every 10minutes should be sufficient to help people memorize where they were at which times.

**Comment by tklingbeil** [comment]
The use of GPS within the app has already been discussed in other issues (e.g #119 with another context).

Access to the location data is neither allowed by Apple, nor Google ([see also my comment in the other issue](https://github.com/corona-warn-app/cwa-documentation/issues/119#issuecomment-631388355))

As the integration of location data is not possible, I will close this issue.

**Comment by akuckartz** [comment]
Such a feature can be provided by a different app.
