### ISSUE TITLE
Describe forensics risks and countermeasures

### ISSUE THREAD

**Issue by sventuerpe** [corona-warn-app/cwa-documentation#165]
This may already be in the working (#71 / #123) but I thought I’d raise it here just in case.  

## What is missing

An analysis of what can be found out through forensic analysis of an app user’s device and how this information could be used or abused, a description of countermeasures (a) within the apps and (b) in the underlying platforms, and an analysis of how effective these countermeasures are in practice. 

## Why should it be included

Consider the following scenario: An app user receives is notified of possible exposure through the app but chooses to ignore this warning, trusting that everything would be anonymous and voluntary. Subsequently this user has contact with another person. Both turn out infected later and the app user is accused of having caused bodily harm. A criminal investigation commences, in the course of which law enforcement officers confiscate the app user’s electronic devices and examine them for evidence. 

Since a specific legal regulation pertinent to CWA is apparently not planned, all common legal obligations apply to app users even though using the app as such is voluntary. To make informed decisions whether and how to use the app, potential users need to understand all consequent risks as well as the extent to which technical countermeasures offer protections. 

At the end of the day practical countermeasures may rely mostly on platform features like device encryption and locking, but it would be good to have an explicit statement with regard to this topic. 

## Where should it be included

Security documentation or app documentation

**Comment by agowa338** [comment]
I'd like to add to the story that there is also a risk for "beacon users" e.g. Users that submitted being positive but were identified either by identifying them selves or by getting access to there phone.

Than one (including law enforcement and intelligence agencies) could use this information to identify if a specific user had been in close proximity to the "beacon user" (as the full list of IDs is transmitted).
Also this "beacon users" could be devices that are placed on specific locations of interest (e.g. placing a device close to the hideout of some criminal, in the middle of some protest) and will therefore look like "normal users" to the system.
Than as soon as the responsible party needs evidence (assuming they already have all subject they're interested in) they could just flip the switch to have the "beacon user" device transmit that it is positive (or just look at the ID list). Resulting in all persons that were close enough to that beacon to become identifiable.

**Comment by tkowark** [comment]
Some of the aspects should be covered by the [Security Overview](https://github.com/corona-warn-app/cwa-documentation/blob/master/overview-security.md) and there is currently no additional documentation planned on that matter.
