### ISSUE TITLE
support other mobile OS, e.g. UBports (not just iOS/Android)

### ISSUE THREAD

**Issue by riidom** [corona-warn-app/cwa-documentation#166]
Not sure where else to put this, sorry.

For the necessary high usage count of this app, it should be available on as much operating systems as possible.

Edit: Much relevant discussion in #5 . Any news on the topic welcomed.

**Comment by mynchau** [comment]
Hi riidom, thanks for your contribution. As my colleague stated earlier "there is no additional information from our side beyond the comments that @MalteJ already made in [#5 (comment)](https://github.com/corona-warn-app/cwa-documentation/issues/5#issuecomment-627834039) and [#5 (comment)](https://github.com/corona-warn-app/cwa-documentation/issues/5#issuecomment-627860999).

Deutsche Telekom and SAP have the task to develop an application based on the Google/Apple framework which can be delivered to the public via the respective stores. Any functionality/capability which goes beyond that can't be guaranteed by us and would probably need to be implemented by the community by code/reuse or an alternative implementation of the specification.

With this, I'm closing your issue. 
Best regards
MC 
Your Corona Warn-App Open Source Team
