### ISSUE TITLE
Update illustrations of people to wear face masks

### ISSUE THREAD

**Issue by FloEdelmann** [corona-warn-app/cwa-documentation#168]
The screens shared in [ui_screens.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/ui_screens.md) include some vector graphic illustrations.

Would it make sense to update the people in those illustrations to wear face masks? Maybe that could help share the fact that face masks still play a role in reducing the infection risk, alongside the app.

**Comment by jarjarbentley** [comment]
Thank you for your suggestion.  Per the statement in the [.md file](https://github.com/corona-warn-app/cwa-documentation/blob/master/ui_screens.md)  **"We highly appreciate your feedback on these screens! Though, please, bear in mind that major changes cannot be implemented without a decision by the Ministry of Health and the Robert Koch Institute. Further documentation, e.g. about questions of accessibility, will follow soon."**

So, the change can't be included in the first version, but we will take that suggestion to the designers.

Thanks again, your Corona-Warn-App Open Source Team. JB

**Comment by timbodeit** [comment]
> please, bear in mind that major changes cannot be implemented without a decision by the Ministry of Health and the Robert Koch Institute

I support the idea of having Ministry and RKI sign off certain changes. Looking at the iOS Repository it seems that BSI employees are [raising issues](https://github.com/corona-warn-app/cwa-app-ios/issues/2) directly within the issue tracker of the repository. Might it make sense to bring in a RKI and Ministry of Health contact in a similar capacity? I wouldn't expect them to actively follow the project without being explicitly mentioned, but I feel it would be nice to keep government review of open-source contributions within the open-source context.
More specifically I am wondering: Can such changes usually be approved by a single RKI / ministry employee or do they require a more formalized process? Is this something that you as the core maintainer team would be open to?

**Comment by SebastianWolf-SAP** [comment]
Dear @FloEdelmann,

we consulted with our UX/UI designers and with our partners. I'm sorry to tell you that your idea won't be pursued. The reason is that the illustrations show people either outdoors or in their private living space where wearing a mask is not the default or not regulated by law.

Thank you for your understanding!

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by FloEdelmann** [comment]
Thanks @SebastianWolf-SAP for sharing this information. I'm sorry to hear that but I can understand the motivation behind this decision.

Have a nice weekend!
