### ISSUE TITLE
Alternative software allowed to interface with backend?

### ISSUE THREAD

**Issue by t3sserakt** [corona-warn-app/cwa-documentation#169]
@zoobab if you don't trust your smart phone you are free to build an implementation on the hardware device of your choice (e.g. ESP32). The BLE specs will be released by Google/Apple and also the API to our backend.

_Originally posted by @MalteJ in https://github.com/corona-warn-app/cwa-documentation/issues/5#issuecomment-627844731_

That means an alternative app made for another OS than Android or iOS or even any software is allowed to interface with your backend system!? Are there any special requirements to be allowed to talk to your backend?

**Comment by KevinMuessig** [comment]
Hello @t3sserakt ,

thank you for your input. We will look into that and get back to you soon.

Best,

KM

**Comment by egandro** [comment]
> According to #62 and [corona-warn-app/cwa-server#82](https://github.com/corona-warn-app/cwa-server/issues/82), device attestation will not be used. The back-end should therefore accept any client that abides by the access protocols. Or am I missing anything?

We discussed that before here. There is some limitation of the Google API for creating Tokens. However a ESP Atmel Microcontroller with Bluetooth might be used to fake a cell phone. The ESP has a WiFi interface and one can think about a Android VM that is used to generate the tokens. 

I think this can be done very very easy.

**Comment by svnk** [comment]
If you want to have clients that don't use the GAEN (Google / Apple Exposure Notification) API, they would still need to be compatible on the Bluetooth-End. The [Bluetooth spec](https://covid19-static.cdn-apple.com/applications/covid19/current/static/contact-tracing/pdf/ExposureNotification-BluetoothSpecificationv1.2.pdf) and the [crypto spec](https://covid19-static.cdn-apple.com/applications/covid19/current/static/contact-tracing/pdf/ExposureNotification-CryptographySpecificationv1.2.pdf) are public. 
On a first glance, that should be enough for a clean-room implementation.

**Comment by mh-** [comment]
@svnk Yes, and that's discussed e.g. here: https://github.com/corona-warn-app/cwa-app-android/issues/75

**Comment by tkowark** [comment]
As mentioned https://github.com/corona-warn-app/cwa-documentation/issues/169#issuecomment-636122152 device attestation is not being used, so in principal, clients should be able to interface with the backend. If there are any concrete issues when doing that, please open a dedicated issue in the CWA server repository.
