### ISSUE TITLE
App availability in English

### ISSUE THREAD

**Issue by MenOfWar** [corona-warn-app/cwa-documentation#17]
Hello,

Thank you for your efforts in this. Since I did not find any documentation about this I wanted to ask early on: will the app be available in English for the end user?

There are many people working in Germany who do not speak German (such as myself), and since you are developing everything in English to promote globalisation, I would like to request you to keep in mind to have the app available in English to the end user.

Thank you and good luck!

**Comment by tkowark** [comment]
Thanks for your question. E01.06 in the [Scoping Document](https://github.com/corona-warn-app/cwa-documentation/blob/master/translations/scoping_document.de.md) mentions that the app will support multiple languages.
