### ISSUE TITLE
Clarify design with respect to red/green weakness

### ISSUE THREAD

**Issue by egandro** [corona-warn-app/cwa-documentation#170]
According to the first screenshots that where published from the App, the color "green" is used to indicate no infections.

As experienced UI developers know, in the group of male > 45 a Red Green weakness is very common.

Please document in great details why this isn't honored in the app.

Edit: Please DON'T do it in the SAP way "add a new button toggle for red/green weakness" :)

**Comment by cfritzsche** [comment]
Hi @egandro,

As the documentation states:

> Once available, it will support all accessibility features within the operating systems such as zooming to enlarge text, screen readers like VoiceOver for iOS and TalkBack for Android, or **special color contrasts**.

Also, it’s not the color alone giving the information but also the text in the App.
Frankly, I think there is nothing more the app developers could do.

**Comment by egandro** [comment]
You assigned a color to a semantic function :)

What are you talking about?

**Comment by w9n** [comment]
The UI improvement suggestion from egandro is to add something like a thumb, traffic light or smiley for the risk indicator here:
https://github.com/corona-warn-app/cwa-documentation/blob/master/images/ui_screens/ios/cwa_home_ios.png
This would help users with red/green weakness to identify their risk status more easily.

**Comment by egandro** [comment]
> The UI improvement suggestion from egandro is to add something like a thumb, traffic light or smiley for the risk indicator here:

Please DON'T!!! put words in my mouth!

As adult I can speak for myself. I didn't imply, suggest or meant anything you just mentioned.

A UI designer - with experience - will know what to do - while the current doesn't!

Red/Green Weakness is a major issue for 8-10% in our population in Germany. That's why it's covered by any UI design related university course in Germany...

**Comment by SebastianWolf-SAP** [comment]
Dear @egandro,

please consider this message as a warning according to our code of conduct. We won't accept shouting or any other inappropriate language in this forum.

You saw that there is already a colleague assigned to this issue - in other words, we accepted it and will follow up accordingly. It won't help your case if you accuse the current UX/UI designers that they don't know what do you. Let's treat each other with respect and courtesy. Thanks!

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by egandro** [comment]
> please consider this message as a warning according to our code of conduct. We won't accept shouting or any other inappropriate language in this forum.

Dear @SebastianWolf-SAP,

I sincerely apologize for any caps written words.

Since @w9n is also endorsed and/or related to SAP I had a very strange feeling that this issue might put to the attic as I had the feeling that happened to other issues before. 

So - let's do everything here that this won't happen again!

**Comment by SebastianWolf-SAP** [comment]
Apologies accepted, thanks for your message! 

We will discuss this and other UX/UI related issues/questions which are already there (e.g. #168) with our UX/UI designers next week. However, as already outlined in the UI screens document, any changes might need to be included in a later version as we have a pretty tough timeline...

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by w9n** [comment]
@egandro also sorry from my side, I didnt want to insult you or speak in behalf of you, just wanted to point out that the contribution is coming from your side. My sole intention was to clarify and transform the good request into an actionable item for the team to help progress asap :)

In future Ill avoid summarizing in the name of others and stay by the topic.

**Comment by SebastianWolf-SAP** [comment]
In the meanwhile we consulted our UX/UI experts and they completely agree with @cfritzsche. The red/green color coding is just _one_ element out of many, e.g. the text and the change of other UI elements in case there is a warning. 

As a consequence, we will close this issue accordingly.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by egandro** [comment]
> As a consequence, we will close this issue accordingly.

Ok cool!

So just let me document this here for the "Beauftragter der Bundesregierung für die Belange von Menschen mit Behinderungen".

In UI / UX design (accredited studies B.Sc./M.Sc.) red/green weakness is covered in this references:

- ISO 9241
- Nielsen Heuristics
- Shneidermans "10 Golden Rules for Interface Designing"

Why is that important?

There are multiple versions of red/green weaknesses - e.g. Protanopie and Deuteranopie. Deuteranopie is the more dangerous of both. 

Please keep this as reference here in case of issues.

As far as I understood the SAP development process preferences, there might be a sprint / release just for polishing the UI and this might become handy.

However - I am not sture about the legal situation / contracts - the "Beauftragter der Bundesregierung für die Belange von Menschen mit Behinderungen" might cover this at a very early point.

**Comment by SebastianWolf-SAP** [comment]
Well, everybody agrees that red/green weakness is an important factor and everybody agrees that red or green color must never be used as _sole_ element to convey a certain message. And we don't do that - it's just yet another element in addition to other ones. This happens in accordance to the respective laws and regulations.

To put it the other way round: Just because there is this red/green weakness, it doesn't mean that we should immediately stop using red or green color as additional means of information. These colors are still a good indicator for many people and well established in our culture.

Mit freundlichen Grüßen/Best regards,
SW
Corona Warn-App Open Source Team

**Comment by egandro** [comment]
> To put it the other way round: Just because there is this red/green weakness, it doesn't mean that we should immediately stop using red or green color as additional means of information. These colors are still a good indicator for many people and well established in our culture.

Just let me mark this as your personal opinion. The ISO 9241 has scientific proof of the contrary.

So a 20 years old book "Microsoft Windows User Experience (Microsoft Professional Editions) (Englisch) Taschenbuch – 8. Oktober 1999" marks red/green weakness as major issue (even as a cultural issue for international software).

@SebastianWolf-SAP let's just keep this as reference here! And it's your SAP/Telekom decision not to fix this.

**Comment by HolgerMayer** [comment]
Green is a bad design choice. The apps main color schema is blue.  From a design point of view that is bad because the color transports no additional information. 

In  case of a low risk it should be blue like the core app color schema.  Blue means all cool no problem.

 A red color for high infection risk  would be of because a break of the color schema with the purpose as a sign of importance. That is good design.

With a blue/red schema your problems with red/green blindness are gone too.

**Comment by SebastianWolf-SAP** [comment]
Dear @egandro,

I would - once again - ask you to remain professional. You already got a warning, you apologized and the last comment is - honestly - close to the level of yet another warning and additional consequences. 

I explained the decision and the background. You only picked one part of the explanation ignoring that red and green color is definitely not the only differentiator here and - even more - claiming that my statement is just a personal opinion. These are both unfair tactics in a discussion and I would kindly ask you to refrain from that in the future.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
