### ISSUE TITLE
ENA Acronym is where defined?

### ISSUE THREAD

**Issue by HolgerMayer** [corona-warn-app/cwa-documentation#172]
## Your Question
As I understand this project space the Application is called ENA.
1) This acronym is nowhere declared
2) Why did you not use CWA

I refer you to 
https://github.com/corona-warn-app/cwa-documentation/issues/90

3) Who is updating the documentation?

**Comment by SebastianWolf-SAP** [comment]
Added it to the glossary, see https://github.com/corona-warn-app/cwa-documentation/blob/master/glossary.md

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
