### ISSUE TITLE
Who will operate the backend?

### ISSUE THREAD

**Issue by HrFlorianHoffmann** [corona-warn-app/cwa-documentation#173]
Searched around a bit but didn’t find anything about it. We say in which cloud the servers will run. Shouldn’t we also say who will be the responsible devops for the server components? An SAP team? A Telekom team?

**Comment by raethlein** [comment]
The information is stated in the [Readme](https://github.com/corona-warn-app/cwa-documentation/blob/master/README.md): "Deutsche Telekom is providing the network and mobile technology **and will operate and run the backend for the app** in a safe, scalable and stable manner."

**Comment by sventuerpe** [comment]
@raethlein 

1. Will Deutsche Telekom also be data controller with regard to the GDPR, or rather act as a data processor on behalf of the German Federal Government or RKI?
1. The [privacy statement](https://www.coronawarn.app/en/privacy/) on the website identifies SAP as the operator (of the website).

Who will be responsible?

**Comment by tkowark** [comment]
Dear @sventuerpe , 

I hope that the current [Datenschutzerklärung](https://www.coronawarn.app/assets/documents/cwa-privacy-notice-de.pdf) answers your questions, too. If there are new questions, we kindly ask you to open a separate issue to make searching in the repo easier.

Best regards,
TK
Corona Warn-App Open Source Team
