### ISSUE TITLE
Deployment code and documentation (Kubernetes)

### ISSUE THREAD

**Issue by saschagrunert** [corona-warn-app/cwa-documentation#176]
## What is missing

Im just wondering where the documentation and source code about the general server side deployment resides. Is the source code already available somewhere?
## Why should it be included

I think it’s an important part of the application, especially from the security point of view. 
## Where should it be included

Maybe here or in a dedicated repository.

**Comment by tkowark** [comment]
This repo should include the required information: https://github.com/corona-warn-app/cwa-server

**Comment by hilmarf** [comment]
https://github.com/corona-warn-app/cwa-server/issues/1793
