### ISSUE TITLE
improve readability of pictures

### ISSUE THREAD

**Issue by tuxwurst** [corona-warn-app/cwa-documentation#177]
Hi,
thanks for your great effords.
regarding the UI https://github.com/corona-warn-app/cwa-documentation/blob/master/ui_screens.md 
on screen 2 the picture for "have you got tested?" should be a mouth with a q-tip, a test tube or something simelar, that relates more to a corona-test then a phone.

**Comment by MaStrOD** [comment]
on screen 4 the three phones could be connected with a line to symbolize the key exchange. so the picture does not show just some random people standing arround;)

**Comment by SebastianWolf-SAP** [comment]
Dear @tuxwurst,

thank you for your proposal. We consulted with our UX/UI experts and according to them, the existing visuals are OK with respect to readability and comprehensibility - also in the first usability tests. Parts of your suggestion may be included in future revisions, but we don't plan concrete changes to them in the foreseeable future.

Thank you for your understanding!

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
