### ISSUE TITLE
Apps main screen could be abused as proof of usage

### ISSUE THREAD

**Issue by rjungbeck** [corona-warn-app/cwa-documentation#178]
The screen layout looks very much like the Chinese layout. (Even the green color for low risk).
It allows the abuse of the main screen as a kind of proof of usage ("Show me your smartphone with the app's screen)" to be allowed to enter eg a building or area (like they did in China).
 
Is this compatible with the data security objectives?

**Comment by mynchau** [comment]
Hi @rjungbeck thanks for your contribution. The user interface and experience has been developed together with diverse stakeholders, aiming at the best experience for end users of the app. I'm closing your issue, as we refrain from speculations "Apps main screen could be abused as proof of usage". 
Best regards
MC
Your Corona Warn-App Open Source Team

**Comment by HolgerMayer** [comment]
I support the concerns of rjungbeck. 

There should at least be a hint in the application after receiving a positiv result and transfer of the data, that the app can be deleted for personal security.

After receiving the positve result and data transfer back to the server there is absolutly no reason why the positive result should  be displayed again!

I personally would delete the app right at the moment, but not everybody is privacy savy.

You should reopen this call and discuss it with the stakeholders. Without a good explanation for the way you handle it the acceptance rate of the app definitely will drop a lot.

**Comment by rjungbeck** [comment]
I still see the issue. This screen can be easily used to coerce  app usage on an unwilling user. (And my concern is not only after a  positive test has been entered or after a warning has been shown).

**Comment by corneliusroemer** [comment]
Good points and I don't think the way this issue was closed is constructive. "We refrain from speculations" basically means we don't think about threats and thus we don't think about security. Is this really the spirit behind this project?
I add this to my list of examples to show the need of a good #IssueClosePolicy
