### ISSUE TITLE
False bluetooth detections

### ISSUE THREAD

**Issue by AndiLeni** [corona-warn-app/cwa-documentation#179]
Hello,

I have a few questions about Bluetooth detection.
How exactly can the app prevent detection, e.g. through walls? 
Suppose my colleague and I are sitting in two offices separated by a wall. The Bluetooth signal will most likely still be recognized as a "contact". During a normal working day, the duration will also most likely exceed 30 minutes, which the API already classifies as high.
If one of us is tested positive, the other one would probably also receive a message even though he definitely had no contact.
Such a scenario is in my opinion not that unlikely in German offices or other working environments.
Is there a document describing how to deal with such situations or a note in the API?

Kind regards
Andreas

**Comment by tkowark** [comment]
Dear @AndiLeni ,

first of all, thanks for your question and sorry for the late response. With the current Exposure Notification API it is not possible to mark individual exposure events as invalid (e.g., based on user input). This would require to provide great detail (e.g. concrete time and duration) about the exposure event to the user, which is not [available through the API](https://developer.apple.com/documentation/exposurenotification/enexposureinfo).

Kind regards,
TK
