### ISSUE TITLE
How do you ensure security for the use of Bluetooth low-energy technology in older Android versions and on old chips?

### ISSUE THREAD

**Issue by CodeExplorer22** [corona-warn-app/cwa-documentation#18]
How do you ensure security for the use of Bluetooth low-energy technology in older Android versions and on old chips that are no longer supported by the manufacturer?

Keyword: SweynTooth vulnerabilities. Recently discovered. Is this technology suitable to create such an app? Doesn't that open the door to hackers ? Older chips even have more and other vulnerabilities.

I can already see 22 forks here and there will surely be many more. How do you want to prevent everyone from writing their own compatible Corona app, that does send what ever they want, e.g. "I have Corona" just for fun?

**Comment by MalteJ** [comment]
> How do you ensure security for the use of Bluetooth low-energy technology in older Android versions and on old chips that are no longer supported by the manufacturer?

We don't. We cannot fix everything. Those security issues are up to the user and the device manufacturer.

> I can already see 22 forks here and there will surely be many more. How do you want to prevent everyone from writing their own compatible Corona app, that does send what ever they want, e.g. "I have Corona" just for fun?

The device itself does not broadcast it is infected. It only broadcasts an ID. Until we release our architecture docs, you can get an impression how this system works in general by reading up the docs from DP3T:
https://github.com/DP-3T/documents

**Comment by TomTeeJay** [comment]
> The device itself does not broadcast it is infected

Well. let's wait and see. Due to the fact that the app will have a centralized content management system regarding to <https://github.com/corona-warn-app/cwa-documentation/issues/13> I wouldn't be sure about this.

**Comment by Narsail** [comment]
> I can already see 22 forks here and there will surely be many more. How do you want to prevent everyone from writing their own compatible Corona app, that does send what ever they want, e.g. "I have Corona" just for fun?

Easy. Apple and Google only allow apps submitted by government backed programs.

**Comment by ddroescher** [comment]
> Well. let's wait and see. Due to the fact that the app will have a centralized content management system regarding to #13 I wouldn't be sure about this.

No, that is not possible. Please read this: https://github.com/DP-3T/documents/blob/master/public_engagement/cartoon/de/comic-de.pdf

**Comment by tkowark** [comment]
> Well. let's wait and see. Due to the fact that the app will have a centralized content management system regarding to #13 I wouldn't be sure about this.

As already asked in #13 , please wait for the architecture documents and the source code to be published, before jumping to such final conclusions.

Since the original questions have been answered, I'll close this issue for now.
