### ISSUE TITLE
Local public health

### ISSUE THREAD

**Issue by jakobschumacher** [corona-warn-app/cwa-documentation#181]
I suggest to clarify the interaction of the app with the local public health offices (Gesundheitsamt). I'd expect this somewhere in the userstories.

**Comment by SebastianWolf-SAP** [comment]
The scoping document - which includes the user stores - focuses primarily on the behavior of the client apps (Android, iOS) and user interactions there. The local health authorities (Gesundheitsamt) have no direct influence on the client apps themselves. They only interact with the user in the context of the Corona-Warn-App in case they need to provide a teleTAN. This behavior (alongside many other interactions) is clearly outlined in our [solution architecture document](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md).

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
