### ISSUE TITLE
Correct numbering of two substeps in fig. 2

### ISSUE THREAD

**Issue by Holger-Peine** [corona-warn-app/cwa-documentation#186]
## Where to find the issue
Fig. 2 ("Interaction flow for verification process"), step 3

## Describe the issue
The numbering of the substeps 2a (give Tele-TAN to patient) and 2b (get Tele-TAN from verification server) should be the other way round: First get the Tele-TAN, then give it to the patient.

## Suggested change
Replace "(2a)" by "(2b)" and vice versa.

**Comment by SebastianWolf-SAP** [comment]
The user is referencing the solution architecture document. @tklingbeil, please have a look, thanks!

**Comment by tklingbeil** [comment]
You are absolutely right. I'll also add the (visual) information that a teleTAN is only created if it is actually needed.
