### ISSUE TITLE
By using the App Terms of Use are accepted

### ISSUE THREAD

**Issue by TomTeeJay** [corona-warn-app/cwa-documentation#19]
Regarding to the Onboarding process in User Story ID # E01.02 of documentation <https://github.com/corona-warn-app/cwa-documentation/blob/master/translations/scoping_document.de.md#anbahnung-und-installation-onboarding-prozess>, the answer is too unspecific and misleading, I quote:

> Mit Nutzung der App akzeptiert der App-Nutzer die Nutzungsbedingungen und Datenschutzbestimmungen. (in English: By using the app the user accepts the terms of use)

This is not legal due to the fact that such consent must always be an active act. 
The documentation should be more precise about this.

**Comment by tkowark** [comment]
Thanks for your suggestion for increasing clarity of the documentation. I've changed the label accordingly and we aim to make it clearer in future versions.

**Comment by Ryuno-Ki** [comment]
Plus, as far as I know, there needs to be some paper trail about when the consent was given in case data is sent to a server.

I wonder, how a revoke / right to be forgotten / request for my data would work here (likely new issues).

**Comment by MalteJ** [comment]
All data you send to the servers are deleted after ~14 days automatically.

**Comment by MalteJ** [comment]
Please wait until the app UX is released. If then you still see a problem, feel free to reopen this issue.

**Comment by F3000** [comment]
> Please wait until the app UX is released. If then you still see a problem, feel free to reopen this issue.

when will you release a first view of the UX ?

**Comment by mojoaxel** [comment]
> when will you release a first view of the UX ?

@F3000 see #26
