### ISSUE TITLE
UI-Design, current use of signal color (alone)

### ISSUE THREAD

**Issue by tik-boomer** [corona-warn-app/cwa-documentation#191]
**Issue**: 
Please take into account that a substantial number of citizens have a restricted color vision ("color blindness"). It is estimated that this affects up to approx. 9% of the male poulation in Germany, and a lower percentage of the overall population. This especially affects "red" and "green" vision for many of these citizens. Chosing "special color contrasts" from general accessibility settings does not help these app users, when color alone is used for the purpose of "intuitive" status information.

## Suggested Enhancement
**Suggestion / Request**: 
add a status symbol to each status information / status screen, so that the status is intuitively clear for users with restricted color vision. The status symbols should be different in outline. "Traffic lights" are usually not good symbols for this purpose. More suitable symbols could be e.g. "Smiley / Neutral / Frownie" or "Thumb up / Question Mark / Lightning" or similar, or ask an expert for inclusive UI design... This would even enhance usaibility for users who have full color vision.

**Test**: 
Produce copies of the user interface screens where the actual text is replaced by dummy text and print it using greyscale printing only. The status represented should then be obvious from the carefully chosen status symbol only.

Please note that this applies to the Android UI as well as to the iOS UI. Please coordinate for both UIs. If necessary copy the issue to the iOS UI issues, too. 

## Current Implementation
**Referring to**: 
This is referring to the current user interface samples with green status text background and the following sentence from this document ui_screens.md : "The design of the central overview, the usage of signal color to highlight the current risk level, as well as the explanatory illustrations ensure an intuitive consumption of the app."

## Expected Benefits
Better, more intuitive usability for more citizens, thus higher overall UI quality and higher overall user acceptance.

**Comment by tik-boomer** [comment]
Thanks for the explanation, I had not seen #170. 

I would like to reopen and focus my request on: 

_"update Android and iOS app screens to include an **iconic** graphical representation of the app user's status, in addition to color indication and text - and use color invariant and color independent status icons for this purpose"_

... and I suggest keeping it open until this has been evaluated for the completed UI design, handling the status similar to #168 and the explanation by @jarjarbentley there.

The rationale essentially stays the same. The discussion in #170 and #168 do not cover my enhancement request fully.

Thank you and best regards. :-)

**Comment by SebastianWolf-SAP** [comment]
Hi @tik-boomer,

jut got a reply by our UX/UI experts. I'm sorry to tell you that we won't reopen this issue. Several reasons for that:

1. The prominent title, stating the risk-level, is the main information element
2. The content and icons change between the different risk-levels to further differentiate and explain the levels
3. The solid colored background emphasizes the importance of the risk-level card vs. all other elements on the home-screen
4. The app is of course supporting the OS-built-in color filters for users with color vision deficiencies, such as protanopia, deuteranopia or tritanopia 

Thank you for your understanding.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
