### ISSUE TITLE
Interoperability with other apps

### ISSUE THREAD

**Issue by carallo** [corona-warn-app/cwa-documentation#193]
The European Commission guidelines (see the [Common EU Toolbox for Member States](https://ec.europa.eu/health/sites/health/files/ehealth/docs/covid-19_apps_en.pdf), specifically chapter 3: cross-border interoperability, cybersecurity, safeguards) clearly point out that all apps developed in EU countries should be able to communicate with each other.

Apps using the Exposure Notification API are not able to communicate with others that rely on other approaches, thus this should be fixed since it's in contrast with the European Commission Guidelines.

**Comment by mynchau** [comment]
The interoperability with other European apps will be done later as it is described in the [solution architecture](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md). The prioritization is a matter of the German Federal government, which can be contacted at https://www.bundesregierung.de/breg-en/federal-government/federal-press-office
Therefore, I'm closing this issue. 
Best regards
MC 
Your Corona Warn-App Open Source Team
