### ISSUE TITLE
Key exchange

### ISSUE THREAD

**Issue by AndiLeni** [corona-warn-app/cwa-documentation#196]
Hello,
I wanted to ask if there is a document that explains the exchange between two smartphones in more detail.
The document for the solution architecture describes very nicely what happens when you want to upload your data, but I'm looking for information that explains the exchange in more detail.
The information how the keys are generated, when they are generated, how they look like and so on would be very interesting.
Is there perhaps also a document here which describes the exchange between mobile phones step by step?

Kind regards
Andreas

**Comment by tkowark** [comment]
Hi @AndiLeni ,

this time a quicker answer :) Google has a very good [FAQ page](https://www.google.com/covid19/exposurenotifications/) for this information, including details about [cryptographics](https://blog.google/documents/69/Exposure_Notification_-_Cryptography_Specification_v1.2.1.pdf). I hope this is what you're looking for.

Best regards,
TK
Corona Warn-App Open Source Team

**Comment by AndiLeni** [comment]
@tkowark thanks for the quick response :)
And thanks for teh links.
I thought there might be additional documents from the Corona-Warn-App that explain this function in more detail or in a more specific way.
I will definitely have a look at the document and get back to you if some questions araise.

Kind regards
Andreas

**Comment by SebastianWolf-SAP** [comment]
Dear @AndiLeni,

in case you have any additional questions especially with respect to the app and its infrastructure, please open another issue. As @tkowark provided you the link to the respective documents, we will close this issue now.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
