### ISSUE TITLE
Privacy Notice should list complete smartphone’s exposure logging functionality

### ISSUE THREAD

**Issue by mh-** [corona-warn-app/cwa-documentation#207]
## Where to find the issue
Privacy Notice ([de](https://www.coronawarn.app/assets/documents/cwa-privacy-notice-de.pdf) and [en](https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf))

## Describe the issue
The current version reads 

In addition to the random IDs received from other smartphones, your smartphone’s exposure logging functionality records and stores the following contact data:
• **Date of the contact**
• Duration of the contact
• Bluetooth signal strength of the contact.

## Suggested change
• Date of the contact

should be replaced by

• Date **and time** of the contact

**Comment by tklingbeil** [comment]
As the [documentation](https://developer.apple.com/documentation/exposurenotification/enexposureinfo) states, we only get the [date](https://developer.apple.com/documentation/exposurenotification/enexposureinfo/3583713-date) of the exposure event from the exposure notification framework.

Same applies to Android ([bottom of page 7 of the API documentation](https://static.googleusercontent.com/media/www.google.com/en//covid19/exposurenotifications/pdfs/Android-Exposure-Notification-API-documentation-v1.3.2.pdf)).

Internally, a higher precision might be needed upon matching of the RPIs, to verify that the time, when the specific RPI was captured, matches the time of its validity.

**Comment by mh-** [comment]
> Internally, a higher precision might be needed upon matching of the RPIs, to verify that the time, when the specific RPI was captured, matches the time of its validity.

Your assumption is right, 
and as the Privacy Notice gives a statement about "your smartphone’s exposure logging functionality" (not about the app), this statement should be correct.

**Comment by kbobrowski** [comment]
Agree with @mh- , the statement in privacy notice is not correct, smartphones log date and time of received RPI. @tklingbeil if you want to just inform user what information is received by CWA from EN framework then received RPIs should not be even mentioned in this place, since they are not made available to CWA.

If this is the intention then wording probably should be changed from "smartphone's logging functionality" to "information shared by Exposure Notifications with CWA".

**Comment by SebastianWolf-SAP** [comment]
Dear colleagues,

thanks again for the issue. We published a new revision of the privacy notice ([DE](https://www.coronawarn.app/assets/documents/cwa-privacy-notice-de.pdf), [EN](https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf)) which includes the proposed change (as well as some other elements which describe the details more precisely).

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
