### ISSUE TITLE
Clarify privacy protection / clarify legal implications for TeleTAN Process

### ISSUE THREAD

**Issue by egandro** [corona-warn-app/cwa-documentation#208]
**Using the TeleTAN process in case of an infection might cause legal implications for the user that he or she is not aware of.**

If an infected user calls the hotline for a TeleTAN please clarify (in the App / EULA) about the dataprotection.

- Is the TeleTAN saved in combination with the users address at the hotline system?
- Is the phone number used (this will be in a lot of cases the Phone with the Corona-App) stored in the hotline system? 
- We have a lot of hotlines e.g. psychological help  where the phone number isn't stored for privacy reasons. Please clarify the status of the Tan Hotline.

 **How is this important?**

Is personal data (address, TeleTAN, phone nummer, ...) is stored in the Hotline?

A basic foundation of the Corona App is 100% anonymity, privacy protection and being voluntary.

Possible data protection issue: **If authorities learn about a person is asking for a Corona App TeleTAN and also have the Address of the person, they learn that the person is using the Corona App.**

So if the code isn't used within a specific time - authorities might use **legal actions** against the person who installed the Corona App - e.g. seize the phone. 

In more simple words: you use plausible deniability. 

Please clarify how the App / Hotline Process protects the anonymity of the user (or might be isn't) in the EULA or in the "Call TAN Hotline" button.

**Why isn't the QR process an issue?**

The QR process might or might not be used. Authorities only know - in the moment the user decides to use the phone - about the fact he or she has the App installed.

**Comment by SebastianWolf-SAP** [comment]
This question is clearly answered in the [data privacy notice of the Robert Koch Institute](https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf). Please see section 6c).

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by egandro** [comment]
Dear SebastianWolf-SAP,

thank you for pointing me to this document.

Section 6c is very clear on not storing the (mobile) number calling.

```
Your mobile/telephone number will only be temporarily stored for this purpose
and deleted within one hour at the latest
```

Also the document speaks about this:

```
The legal basis for this processing of your access data and health data (random IDs,
test result, TAN and, if applicable, TeleTAN) is your consent to using the feature for
sharing your test result
```

However my other question isn't answered. Can you please clarify this?

- Person Name
- Address

Is this implied to be part of the "test result"? "test result" isn't defined by that document.

**Comment by SebastianWolf-SAP** [comment]
Please reach out to the Robert Koch Institute (contact data is also in the privacy notice) in case you have any additional questions concerning this document.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
