### ISSUE TITLE
Include the comic explaining DP-3T in the README of this repository

### ISSUE THREAD

**Issue by schauder** [corona-warn-app/cwa-documentation#21]
Several issues created on this repository leave me with the impression they are based on a fundamental misunderstanding of the basic concept of the application.

Presenting that comic on the front page of this repository (and possibly all other repositories for the app) might help to spread the knowledge about how the application is supposed to work.

I'm referring to this comic: https://github.com/DP-3T/documents/tree/master/public_engagement/cartoon

**Comment by MalteJ** [comment]
We are building a website for this project. Maybe we can add a comic like this to the new website.
I will provide your ticket as input to our web designers and comms team :)

**Comment by s-martin** [comment]
I second that, please include at least the comic from https://github.com/DP-3T and refer to the DP-3T documents more prominently.

**Comment by TomTeeJay** [comment]
I am also in favor of this idea. In the original DP-3T idea User "Alice" only made identifyable through an active and voluntary act without any further incentives or additional incentives created by mixing functions (see closed issue #23).

**User "Bob" is considered anonymous as long as he is just collecting IDs.**

Issue #13 stands in clear contrast to the original nature of the idea when tresholds and data are manipulated remotly directly on Bobs' devices. This is intended though a centrlazied content management system and also violates the decentralized approach and nature.

The not shown evil user "Eve" gets additional tracking possibilities and markers for deanonymization due to the fact of just collecting behavioral data of "Bob" when he readings faq, watching videos, opening websites all within or triggered by the Corona-Warning-App.

## Conclusion

The RKI Corona-Warning-App with its current state and feature-set stands in stark contrast to this DP-3T comic.

**Comment by s-martin** [comment]
Like @tkowark said in #13 we should wait until more docs are provided.

From my point of view it's your conclusion that data is being "manipulated" remotely, we don't know yet until more docs and details are provided.

**Comment by TomTeeJay** [comment]
> Like @tkowark said in #13 we should wait until more docs are provided.
> 
> From my point of view it's your conclusion that data is being "manipulated" remotely, we don't know yet until more docs and details are provided.

Well as already mentioned elsewehere I am looking forward though if the features and documentation already ridiculous, how code can become better?

**Comment by s-martin** [comment]
> Well as already mentioned elsewehere I am looking forward though if the features aka "User Stories" and documentation already are ridiculous, how code can become better?

Maybe by providing constructive feedback and refrain from condescending remarks? 😉

**Comment by TomTeeJay** [comment]
@s-martin 
> Maybe by providing constructive feedback and refrain from condescending remarks? 😉

You're right. Well though nobody was harmed please let me put it in another way.

When the comic and agenda sets sails in one direction, and the knwon documentation is already actively sailing in another, then I can't imagine how more documentation or a single line of code can reconcile these opposing positions.

**Comment by pitsch** [comment]
the alice and bob is not directing away from the fact that this app is a client without a server. the QR code is an "air gapped" way to avoid a registration and interaction with a server (such as SORMAS) which would complete the use case. adding a third party of a call center (hotline) in front of the health authority will add new privacy issues and does not replace a missing specification of the client-server protocol.

**Comment by TomTeeJay** [comment]
> the design flaws of DP3T are replicated..

seems to me they are not just replicated, important considerations are security issues are left out when reading this comment

https://github.com/corona-warn-app/cwa-documentation/issues/41#issuecomment-629083682

**Comment by SebastianWolf-SAP** [comment]
We already mentioned that we forward this proposal to our designers. Until we have something here, I'd like to ask you to stay on topic and only discuss visual extensions to the documentation/website here. 

If you want to discuss protocol-related aspects, please either reach out to Apple and Google (for the foundation protocol) or open a dedicated issue in case it affects the Corona-Warn-App itself. Thank you for your understanding.

**Comment by kheinz57** [comment]
I like the idea of that comic a lot. The technology seems a little bit different, but for non technical people similar enough. 
For tech people I have done a video to explain the contact tracing specification from google and apple here: https://www.youtube.com/watch?v=GARHDP99ECs Not sure if it is correct, but maybe it does help to understand.
Unclear for me is when this implementation is availabel in which smartphones

**Comment by tkowark** [comment]
Link will be added to README with https://github.com/corona-warn-app/cwa-documentation/pull/385 and we also add the official explanation video to the website: https://github.com/corona-warn-app/cwa-website/pull/198
