### ISSUE TITLE
[Minor] Add contact email to GitHub organization metadata | verified status

### ISSUE THREAD

**Issue by Shegox** [corona-warn-app/cwa-documentation#211]
It would be an option to additionally add some further meta data to the GitHub organization (Organization -> Settings -> Profile) to make these information easier to find.
Mainly adding the contact Email, which is as well listed in the [`CONTRIBUTING.md`](https://github.com/corona-warn-app/cwa-documentation/blob/master/CONTRIBUTING.md#engaging-in-our-project): `corona-warn-app.opensource@sap.com`.

--- 

Additionally [verifying the organizations domains](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/verifying-your-organizations-domain) (`coronawarn.app` and (if the email is added) the `sap.com` domain) would verify the organizations identity and would allow verified back linking. (And tbh. it looks kinda cool.)

**Comment by SebastianWolf-SAP** [comment]
Thanks for the hint! E-Mail is added, working on the verified status, that might take a while... 

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by christianneu** [comment]
Thanks for your input! We discussed it internally and verified the e-mail contact. :-)

Therefore I will close the ticket.

Mit freundlichen Grüßen/Best regards,
CN
Corona Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@christianneu 
Sorry for off topic but could you please make your Membership of the CWA Organisation visible (or get a Member)
Thanks and thanks for your and the teams great work!
