### ISSUE TITLE
Legal status of Images / Copyright Texts

### ISSUE THREAD

**Issue by egandro** [corona-warn-app/cwa-documentation#212]
Please clarify what Logos / Icons / Copyright Texts needs to be replaced for a derived App.

**Comment by SebastianWolf-SAP** [comment]
A derived app needs to acknowledge, i.e. honor the permissions, limitations and conditions of the Apache 2.0 license. 

As the Apache 2.0 license doesn't grant trademark rights and as the "Corona-Warn-App" logo is a registered trademark of The Press and Information Office of the Federal Government, you must not use this logo or derivatives of this logo and the name in a derived app.

Hope that answers your question.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by egandro** [comment]
Thank you.

What about the "legal texts" and the "copyright text".

Can you please give a clear statement about this?

**Comment by SebastianWolf-SAP** [comment]
The license clearly states what needs to be done with copyright notices and all content. By law we must not provide any legal counseling in this forum. Please contact a person who is officially entitled to do so in case you have any questions concerning legal issues.

Mit freundlichen Grüßen/Best regards,
SW
Corona Warn-App Open Source Team
