### ISSUE TITLE
Display of Risk Calculation Parameters

### ISSUE THREAD

**Issue by FranzBumes** [corona-warn-app/cwa-documentation#213]
## Feature description

I´d like to see the risk calculation parameters ( e.g. distance to contact, duration of contact) within the app.
Could be in the Info Tab
This contains:
- actual risk calculation params
- risk calculation params at contact time (if relevant)

## Problem and motivation
The Parameters used for calculation the risk are not visible .For transpartency this should be shown within the app. So everybody get a better understanding, what to do and what the risks are.

**Comment by SebastianWolf-SAP** [comment]
Dear @FranzBumes,

we already outlined the detailed description of the calculation parameters in a section in our [solution architecture document](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#risk-score-calculation). Some information from this area will also be covered in the FAQs which will be available directly in the app.

Moreover, we will most probably get some additional insights in the research and the background of these parameters in dedicated documents in the near future.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by FranzBumes** [comment]
Dear @SebastianWolf-SAP 
Thank you for the answer.
My intention for this fesature is, to show the user, what things to avoid to reduced risk.
As i understand, the risk params can change on behalf of the actual situation.

So it would be useful, if the app would suggest hiw to act.

regards 
    mFranz
