### ISSUE TITLE
Run without GMS

### ISSUE THREAD

**Issue by Niwla23** [corona-warn-app/cwa-documentation#216]
Hi, I have no GMS installed on my mobile since it steals data and drains my battery. Will I be able to use the app?

If not so, it would be nice to have some priviliged extension app for root users who removed googles bloat.

**Comment by ironjan** [comment]
Related to #52 and #126. 
> The Contract Tracing API will be a part of Google Play Services. Consequently, the app will not work on devices without enabled play services.

https://github.com/corona-warn-app/cwa-app-android/issues/75 could also be of interest.

**Comment by tkowark** [comment]
Thanks for your question. The issues linked by @ironjan (thanks a lot!) should answer your question and keep you up to date on new developments in that area.

Best regards,
TK
Corona-Warn-App Open Source Team
