### ISSUE TITLE
Missing User story: Local Statistics about contacts without warning

### ISSUE THREAD

**Issue by Wallgauer** [corona-warn-app/cwa-documentation#217]
As a user I want to know if the app really works on my phone. So I would like to see how many contacts (without warning) the phone recognized in the last period of time.  

For sure there must be a disclaimer that those contacts could be the same person or different ones, because of the changing pseudonyms...  

I guess this statistics would give visibility to the user and therefore is important for the acceptance of the app.

This feature for sure can be enhanced by a self-control scale and Gamification aspect for "Good distancing" until "A lot of contacts".

**Comment by tkowark** [comment]
Hi @Wallgauer, thanks for your question. 

This information is not available to the application as it is not exposed via the [Exposure Notification Framework API](https://developer.apple.com/documentation/exposurenotification). Hence, the app also cannot display it and it could currently only be added on operating system level (e.g., as part of the preferences screen).
