### ISSUE TITLE
20 million euro? Seriously? 

### ISSUE THREAD

**Issue by MDXDave** [corona-warn-app/cwa-documentation#224]
20 million euros?

For a relatively simple app with backend that uses an existing API developed by Apple/Google? How many programmers were involved? 2000?

Please break down transparently how this exorbitantly high sum is made up except for the fact that it is "made" by "SAP". 🤦‍♂️

https://www.heise.de/news/Corona-Warn-App-kostet-den-Bund-rund-20-Millionen-Euro-4781235.html

**Comment by tkowark** [comment]
Dear @MDXDave,

while we understand the interest concerning the project costs, please understand that this **technical** forum is not the right medium for such questions.

As stated in our [FAQ](https://www.coronawarn.app/en/faq/), please use the [contact form of the Federal Government](https://www.bundesregierung.de/breg-en/service/contact) for such questions.

Additionally, we would like you to remind you of our [code of conduct](https://github.com/corona-warn-app/cwa-documentation/blob/master/CONTRIBUTING.md#code-of-conduct) with respect to implying that costs are artificially inflated and using facepalm emojis in that context.

Kind regards,
TK
Corona-Warn-App Open Source Team

**Comment by mohe2015** [comment]
Ich habe soeben eine Antwort vom Bundesministerium für Gesundheit erhalten:

> Sehr geehrter Herr x,
>
> vielen Dank für Ihre E-Mail vom 1. Juli 2020 und Ihr Interesse an der Corona-Warn-App. Das Vertrauen einer großen Anzahl von Nutzerinnen und Nutzern in die Corona-Warn-App beruht nicht zuletzt auf dem transparenten Entwicklungsprozess. In Ihrer Nachricht bitten Sie um weitergehende Informationen zu den Kosten für die Entwicklung und den Betrieb der Corona-Warn-App durch die jeweiligen Vertragspartner. Das Bundesministerium für Gesundheit ist bestrebt, die in technischer und datenschutzrechtlicher Hinsicht bestehende Transparenz auch hinsichtlich der Zusammensetzung der Kosten herzustellen. Vorangestellt ist anzumerken, dass es sowohl der Erwartungshaltung der Bundesregierung als auch der Öffentlichkeit entsprach, dass die Corona-Warn-App schnell, transparent, sicher, nutzerfreundlich und auch ansonsten hohen qualitativen Anforderungen genügend entwickelt und betrieben wird. Die Erfüllung dieser Anforderungen haben entscheidend zu den unten aufgeführten Kosten beigetragen.
>
> Die Kosten von rund 20 Mio. Euro für die Entwicklung der Corona-Warn-App umfassen im Wesentlichen mit bis zu rund 11 Mio. Euro die Entwicklungskosten für die technische Umsetzung der App durch SAP. Ergänzt wird dies um die Konzeption einer automatischen Laboranbindung und die Einbindung von Laboren, umfangreiche Testmaßnahmen, Konzeption und Aufbau einer technischen Hotline sowie einer Verifikationshotline, Aufbau und Bereitstellung angemessener IT-Sicherheitsmaßnahmen sowie den Aufbau und die Bereitstellung angemessener Netzwerkkapazitäten durch T-Systems. Weiterhin fanden durch T-Systems erste Vorarbeiten für die Schaffung einer europäischen Interoperabilität der Tracing-App-Ansätze statt. Nicht zuletzt wurde das Thema der Open-Source-Strategie sowie des Community-Managements umfassend umgesetzt und auch hierdurch als Teil der Entwicklung finanziert. Die Entwicklungskosten der T-Systems belaufen sich damit auf bis zu rund 7,8 Mio. Euro bis zum Start der App.
>
> Die voraussichtlichen Betriebskosten von monatlich rund 2,5 bis 3,5 Mio. Euro umfassen die Kosten für den Betrieb der notwendigen Infrastruktur einschließlich Serverleistungen durch T-Systems. Hierfür fallen im Jahr 2020 voraussichtlich rund 9,6 Mio. Euro an und im Jahr 2021 bis Ende Mai rund 5,2 Mio. Euro. Hinzu kommen Kosten für den Betrieb von Hotlines durch T-Systems: im Jahr 2020 voraussichtlich rund 12,1 Mio. Euro und im Jahr 2021 bis Ende Mai rund 5,8 Mio. Euro. Hinzu kommen Kosten für die notwendige Pflege der Software. Teile der Betriebskosten sind volumenabhängig nach Nutzerzahlen, anfallendem Datenvolumen bzw. Anruferzahlen. Vorkehrungen für eine Anpassung der Kapazitäten an den Bedarf wurden getroffen.
>
> Ich hoffe Ihnen mit dieser Antwort helfen zu können.
>
> Mit freundlichen Grüßen
> Im Auftrag
>
> x

Wer weitere Fragen stellen möchte: Poststelle BMG <Poststelle@bmg.bund.de>
