### ISSUE TITLE
How is ExposureConfiguration set in CoronaWarn?

### ISSUE THREAD

**Issue by pdehaye** [corona-warn-app/cwa-documentation#229]
[EDITED, in reaction to first comment below]

The [CoronaRiskScoring](https://github.com/PersonalDataIO/CoronaRiskScoring/) project is trying to assess how different contact tracing apps are being parametrized. We are first focusing on apps using the [Apple API](https://github.com/PersonalDataIO/CoronaRiskScoring/wiki/Apple-Exposure-Notification-framework-configuration) as it will enable quickest comparison. 

**What we need**
We need pointers to the places in the code where the following parameters are set:
* `ENExposureConfiguration`.**[`attenuationLevelValues`](https://developer.apple.com/documentation/exposurenotification/enexposureconfiguration/3586319-attenuationlevelvalues)**, 
* `ENExposureConfiguration`.**[`daysSinceLastExposureLevelValues`](https://developer.apple.com/documentation/exposurenotification/enexposureconfiguration/3586320-dayssincelastexposurelevelvalues)**,
* `ENExposureConfiguration`.**[`durationLevelValues`](https://developer.apple.com/documentation/exposurenotification/enexposureconfiguration/3586321-durationlevelvalues)**, 
* `ENExposureConfiguration`.**[`transmissionRiskLevelValues`](https://developer.apple.com/documentation/exposurenotification/enexposureconfiguration/3586323-transmissionrisklevelvalues)** and 
* `ENExposureConfiguration`.`metadata`.**[`attenuationDurationThresholds`](https://developer.apple.com/documentation/exposurenotification/enexposureconfiguration/3586322-metadata)**

**Nice to have**
We would also like to understand what is done with `ENExposureDetectionSummary` and `ENExposureInfo`, after the risks are calculated. 

**Excellent to have**
This is only the beginning for us. We want the above so we can track how the parameters are being changed. It is likely actually that this is passed dynamically to the apps. If so, we need to know the process behind these changes, so we can ask the right people for this information. 

If you have pointers in the right direction, they would be greatly appreciated.

~~This is addressed [here](https://github.com/PersonalDataIO/CoronaRiskScoring/issues/7).~~

**Comment by SebastianWolf-SAP** [comment]
Thanks for the question. We have some additional documentation planned, but no ETA yet. 

One general remark: Please always enter the full description of your issue here, a simple link to your own personal project is not optimal as everybody always needs to check the other repository for updates. This question concerns this organization, so the discussion should ideally happen here.

Thanks for your understanding!

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by mh-** [comment]
While the title of this question refers to ExposureNotification, I think you are interested in ExposureConfiguration?

The apps download this from COUNTRY_APPCONFIG_DOWNLOAD_URL, see https://github.com/corona-warn-app/cwa-app-android/search?q=COUNTRY_APPCONFIG_DOWNLOAD_URL

**Comment by christian-kirschnick** [comment]
The configuration values are also no secret as they are part of the servers codebase:

- [Exposure Config](https://github.com/corona-warn-app/cwa-server/blob/master/services/distribution/src/main/resources/master-config/exposure-config.yaml)
- [Attenuation Duration Config](https://github.com/corona-warn-app/cwa-server/blob/master/services/distribution/src/main/resources/master-config/attenuation-duration.yaml)
- [App Config ](https://github.com/corona-warn-app/cwa-server/blob/master/services/distribution/src/main/resources/master-config/app-config.yaml)(with Min Risk Score)

**Comment by pdehaye** [comment]
Thanks to all, I just made various corrections to the way I have structured the GitHub issue, will look at all your pointers. Searching is sometimes difficult because each national app has idiosyncrasies, especially as the projects tend to accumulate obsolete code when they switch to the GAEN framework.

**Comment by SebastianWolf-SAP** [comment]
As the relevant files were all referenced in this issue and as we just released the [Epidemiological Motivation of the Transmission Risk Level](https://github.com/corona-warn-app/cwa-documentation/blob/master/transmission_risk.pdf), I close this issue now.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by pdehaye** [comment]
Thank you for aggregating all the docs, and especially for storing all the config data in neat files.
