### ISSUE TITLE
App discriminates users by mixing functions

### ISSUE THREAD

**Issue by TomTeeJay** [corona-warn-app/cwa-documentation#23]
By mixing the functions a) contact tracing and b) communication and dealing with test results the app violates the voluntary nature of its use. I am referencing to User Story ID # E06.02

> Der App-Nutzer erhält eine Benachrichtigung, sobald ein verifiziertes Testergebnis vorliegt.

By nudging and offering additional functions the app usage is not voluntary anymore. 
The recieved data recordsets might be biased.

## Conclusion

Remove any additional functions that might be discriminating or nudging users

**Comment by tkowark** [comment]
This would only be true if the app was the only way of getting test results. Please refrain from such speculations.
