### ISSUE TITLE
Replace "Cough/sneeze into a tissue" with "stay home, get tested when showing symptoms"?

### ISSUE THREAD

**Issue by corneliusroemer** [corona-warn-app/cwa-documentation#232]
On the base screen of the app you give behavioural recommendations like the following:
- "Cough/sneeze into a tissue"

These behavioural tips may seem like a small thing, but given that millions of people will see them, it's very important these are well vetted and checked by an appropriate authority.

Question: Who decided which tips to put there? The cough into tissue is potentially harmful. Current guidelines by RKI are to get tested if you show respiratory disease symptoms. Coughing is one. So the most important thing in this case is to get tested and stay at home, not to feel fine and go out because you're coughing into a tissue.

Please reach out to RKI/Gesundheitsministerium and ask them which tips you should include. This decision shouldn't be made by a designer/developer.

Washing hands isn't as important as wearing masks and staying away from people, too. You should consider changing the priorities and tips.
<img width="312" alt="Screenshot 2020-06-12 at 15 10 45" src="https://user-images.githubusercontent.com/25161793/84506617-eccfe500-acbf-11ea-802d-fd9d2553d863.png">

This is a good place to start in terms of priority. But please reach out to an appropriately authority and don't make this up yourself: https://www.infektionsschutz.de/fileadmin/infektionsschutz.de/Downloads/200520_BZgA_Atemwegsinfektion-Hygiene_schuetzt_A4.pdf

**Comment by mynchau** [comment]
Hi corneliusroemer, 
Thanks for your contribution. The RKI guidelines include coughing/sneezing into a tissue. Regarding your question “who decides which tips to put” I’d like to clarify that this content is coming from RKI and not from designers or developers. 
Best regards,
MC
Your Corona Warn-App Open Source Team

**Comment by corneliusroemer** [comment]
Hi @mynchau, thanks for your response.

Sure the guidelines include that. But other (imo) more important tips have been left out.

Just to clarify: Who decided which 4 tips to include on that screen? You seem to suggest it was the RKI but it's not 100% clear to me from your response.

**Comment by mynchau** [comment]
Hi corneliusroemer, 

It's the RKI that is responsible for the app, including content as such mentioned in this issue. 

Best regards,
MC
Your Corona Warn-App Open Source Team
