### ISSUE TITLE
Release plans and public testing

### ISSUE THREAD

**Issue by corneliusroemer** [corona-warn-app/cwa-documentation#235]
I've read in the media that you plan to go live this Tuesday, in 4 days.

Are there any plans to have a public beta test before you have everyone in Germany install it? Say, on Monday, before official announcement on Tuesday, interested people can download and test it on the whole wide variety of devices to uncover obvious issues that may have slipped through the cracks so far and be able to fix them before announcement?

Or do you intend to recommend installation initially only to a subset of the population so as not to waste the precious one shot you have with too many people?

**Comment by SebastianWolf-SAP** [comment]
Dear @corneliusroemer,

as mentioned in our FAQ, beta/test versions of the app are currently available only to the project team of the Corona-Warn-App and our partners. As soon as the app is released, you will be able to download it from the Apple App Store or Google Play Store.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
