### ISSUE TITLE
Checksum for User Trust: Enhancement Request

### ISSUE THREAD

**Issue by melancholyaeon** [corona-warn-app/cwa-documentation#245]
Hi!

Thanks for listening. In the past, some malicious actors have published code and then released Apps on the App repositories/stores that didn't actually match the published code. . . they inserted dubious code for the App store versions.

Since trust is the big issue with this app, is there a checksum or other method by which users installing the app can verify that the app they are downloading is actually the unmodified code we see here on Github? 

Or is there a section in the documentation that deals with this issue? 

Ty again.

**Comment by ironjan** [comment]
This seems to be closely related to the reproducible builds of  #14. Quote:
> "allow Android users to run reproducible builds to verify that the version downloaded from Google Play is 100% equivalent to the source code here on Github"

**Comment by SebastianWolf-SAP** [comment]
Yes, @ironjan is right, please follow-up in #14. We will keep this issue in cwa-documentation as we need to talk about both versions.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
