### ISSUE TITLE
CORONA-WARN-APP SOLUTION ARCHITECTURE

### ISSUE THREAD

**Issue by marowsky** [corona-warn-app/cwa-documentation#248]
Wird es die Dokumentation der CORONA-WARN-APP SOLUTION ARCHITECTURE auch auf Deutsch geben?

**Comment by SebastianWolf-SAP** [comment]
Dear @marowsky,

I‘m sorry to tell you that a German version is currently not planned. However, that might change in the future...

Mit freundlichen Grüßen/Best regards,
SW
Corona Warn-App Open Source Team

**Comment by marowsky** [comment]
Schade, wie möchte man Vertrauen zur Bevölkerung aufbauen wenn die Dokumentation nicht in der Landessprache geplant ist.
Trotzdem wünsche ich Ihnen Erfolg, aber ohne mich.

Gruß
Peter Marowsky

**Comment by SebastianWolf-SAP** [comment]
Die App sowie die komplette Endnutzerdokumentation ist natürlich auf Deutsch verfügbar. Zum Thema Sprache für entwicklungsnahe Inhalte wie die Architekturdokumentation haben wir uns hier geäußert: https://github.com/corona-warn-app/cwa-documentation/blob/master/translations/README.de.md#arbeitssprache

Vielen Dank für Ihr Verständnis.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
