### ISSUE TITLE
Google Play: Expand allowed countries of residence

### ISSUE THREAD

**Issue by P-Takenaka** [corona-warn-app/cwa-documentation#249]
Although a Person is currently living in Germany, their Google Account might be set to a different country. The app cannot be downloaded in this case, due to a country restriction for the app. In my case, this is Japan. 

The Google Account country is not trivial to change for users - as Google only changes the country if you connect a payment method of the respective country. 

Is it actually necessary to have such a limitation?

**Comment by SebastianWolf-SAP** [comment]
We are aware of this issue, please see https://github.com/corona-warn-app/cwa-app-android/issues/478

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
