### ISSUE TITLE
Deutsch als Hauptsprache oder Zusatzsprache der Dokumentation

### ISSUE THREAD

**Issue by dit-j** [corona-warn-app/cwa-documentation#253]
Die Dokumentation sollte auf Deutsch sein, damit möglichst viele die funktionsweise der App nachvollziehen können. Nicht nur Entwickler. Der Link zu der Repository ist überall in den Medien zu finden.

Es gibt überhaupt keinen Grund die Dokumentation auf English zu verfassen. Sieht cool aus, können nur die wenigsten nutzen/verstehen.

Grüße

**Comment by tkowark** [comment]
Sehr geehrter @dit-j ,

die Gründe für die vorwiegende Nutzung von englisch als Arbeitssprache haben wie [hier](https://github.com/corona-warn-app/cwa-documentation/blob/master/translations/README.de.md#arbeitssprache) bereits dargelegt, und wie sie weiterhin [hier](https://github.com/corona-warn-app/cwa-documentation/tree/master/translations) sehen, werden die wichtigsten Dokumente die sich nicht nur an Entwickler wenden auch entsprechend übersetzt.

Mit freundlichen Grüßen,
TK
Corona-Warn-App Open Source Team
