### ISSUE TITLE
Feature Request: Anonymous statistical functions in App or as API

### ISSUE THREAD

**Issue by hajo62** [corona-warn-app/cwa-documentation#254]
What's about **anonymous** statistics?

- How many of the phones my phone _saw_ have used the App?
- How many people have I met?
- ...

At least I would be interested to see that kind of information's.
If the App would be to complicated, when offering those info, what about an expert mode or an secured API to get that info?

**Comment by tklingbeil** [comment]
Hi,

this data is not even available through the API provided by Apple and Google.

Let me get into the details a little bit:
With the functionality enabled, the phones constantly broadcast BLE message with the service `FD6F` ([see Bluetooth specification](https://covid19-static.cdn-apple.com/applications/covid19/current/static/contact-tracing/pdf/ExposureNotification-BluetoothSpecificationv1.2.pdf)) To find out how many of the phones you have "seen" have the app installed, those other phone would need to consistently (and constantly) broadcast something specific as well - and they don't. So you can't get that number.

To find out how many people you have met (with the functionality enabled), we would need access to the collected Rolling Proximity Identifiers (RPIs), or at least to a counter. To preserve privacy, Apple and Google have protected those. Even the matching takes places completely inside the framework, so we only get information of the exposure in return (but not the specific RPIs or even diagnosis keys).

I hope that helps to understand why such a functionality is currently not possible.
