### ISSUE TITLE
Switch for only checking diagnosis keys when in WLAN

### ISSUE THREAD

**Issue by nils4cosee** [corona-warn-app/cwa-documentation#255]
I'm opening this issue here, because it affects both apps.

In today's press-conference, it was mentioned that the traffic caused by using the apps is free of charge, at least in Germany.

Nevertheless, it would be good to have an option to only check for diagnosis keys when in a WLAN. This would help people that are on holiday in a foreign country, and people live near the border and work in a neighbouring country...

**Comment by SebastianWolf-SAP** [comment]
Dear @nils4cosee,

please use the built-in functionality in the respective operating system to switch off data in foreign countries to avoid costs for roaming. 

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by nils4cosee** [comment]
I don't think this is an adequate solution, since this would disable any network traffic, normal web-browsing and messaging-apps as well.
