### ISSUE TITLE
Describe precise algorithm with numbers and scenarios for "High risk"

### ISSUE THREAD

**Issue by corneliusroemer** [corona-warn-app/cwa-documentation#256]
The app only seems to provide a binary risk assessment: low and high risk.

While the general algorithm is described in the Exposure API docs, it would be very valuable to know what precise values are used in this particular implementation and what this means in a variety of scenarios.

What values were chosen and why? How long do I need to be in contact for High risk to be triggered?

If I remember it correctly, you can define various risk values from 0-9 for a variety of buckets and categories (encounter 14 days ago, 13 days ago,... / low risk person, high risk person / 0-5min, 5-10min,... / signal strength, ...)

I guess I could look up the numerical details in the code, but it would be helpful if someone who actually chose the numbers explained why they chose the exact values they did.

**Comment by SebastianWolf-SAP** [comment]
Please see the information in the [architecture document](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md) and the [Epidemiological Motivation of the Transmission Risk Level](https://github.com/corona-warn-app/cwa-documentation/blob/master/transmission_risk.pdf).

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by corneliusroemer** [comment]
Sorry, what you shared is interesting but doesn't answer the question about what the weights are you are setting in the app.

Also, it doesn't allow one to understand where you set the threshold between low and high risk.

@SebastianWolf-SAP How can you close issues so aggressively without properly answering the question? Please get someone else to help with request triaging. I'm reopening this issue.

**Comment by pdehaye** [comment]
This is somewhat of a duplicate/followup to #229.

**Comment by pdehaye** [comment]
@corneliusroemer You might be interested in comparing this across countries. 

This is what we do in this project:

https://github.com/PersonalDataIO/CoronaRiskScoring/issues?q=is%3Aissue+is%3Aopen+label%3AExposureConfiguration

Immuni, for instance, changed the parameters suddenly with no public communication about it. 

Consider also helping for the other issues!

**Comment by pdehaye** [comment]
This question is still unanswered, but was consolidated in #336 alongside all the others.
