### ISSUE TITLE
App is region-locked in the play store

### ISSUE THREAD

**Issue by moegyver** [corona-warn-app/cwa-documentation#259]
Steps to recreate:

Use a Google account that wasn't created in DE. Try to install the app. Fail.

Should be available worldwide, lots of people who live in DE or visit use a foreign google account for the play store.

Source: pretty much all international friends and co-workers I have, myself (primary play store account was created when I lived in a different country), all the tourists

**Comment by moegyver** [comment]
Apologies, duplicate.

**Comment by hajo62** [comment]
Duplicate of which issue?

**Comment by hajo62** [comment]
https://github.com/corona-warn-app/cwa-documentation/issues/260
