### ISSUE TITLE
QR code to notify contacts?

### ISSUE THREAD

**Issue by flowl** [corona-warn-app/cwa-documentation#263]
The Tagesschau is communicating in a [video](https://www.facebook.com/tagesschau/videos/273641953747825/) (0:28) that a QR code is generated and used to notify all "contacts" when I announce beeing infected.

What does "contacts" mean in that context?
What information does the QR code contain?

Please provide me with an example QR code.
I can't find information about it anywhere.

**Comment by tkowark** [comment]
Unfortunately, there is an important part missing in the Tageschau App. As explained on the [Website](https://www.coronawarn.app/de/), the QR code is only used to allow submission of diagnosis keys in case of a positive test result. Alternatively, the teleTan can be obtained from the Hotline to also allow this upload. Contacts are then warned when they download the diagnosis keys and *locally* check whether they had any contact events with the corresponding phones.

I hope that clarifies the meaning of the code a bit.

**Comment by flowl** [comment]
@tkowark I am talking about the other QR code, please watch ther video I have linked.
I am not talking about the QR code to verify infection, but the QR code mentioned by Tagesschau to "notify contacts".

Please give me a sample QR code so I can verify privacy and decentrality are not hijacked.

**Comment by flowl** [comment]
"Das Gesundheitamt erteilt einen QR code, mit dem meine Kontakte benachrichtigt werden."

Is the Gesundheitsamt trying to circumvent privacy?

**Comment by tkowark** [comment]
Yes, understood. But there is no second QR code other than the one for test result retrieval. Details on that can be found in the [Solution Architecture](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md).

**Comment by flowl** [comment]
Thanks for the link, helpful. 
I think it's important for the success of the app that communication is accurate and Tagesschau did not do a good job with their videos. MHO.
Your work is very appreciated, thanks for clarifying!
