### ISSUE TITLE
add FAQ-entry w.r.t. funding of this project

### ISSUE THREAD

**Issue by cknoll** [corona-warn-app/cwa-documentation#265]
## What is missing

The current state of documentation (especially the FAQ-section e.g. https://www.coronawarn.app/de/faq/) lacks information about the funding of this project: Who pays for the development and operation of the app. And ideally also how much (allthough this information is not as crucial).

## Why should it be included
For such an app it is crucial, that users trust the development team and the entity which runs the backend. It is much easier to trust an entity with a transparent and comprehensible motivation. If an app is paid or displays adds motivation is quite obvious. This app does neither, so the question arises why is this project happening? I suppose that public money is involved, and personally I think this like it should be. But it should also be transparent to the users (and to the tax payers).

Currently the information provided is vague and insconsitent:

- [english version](https://github.com/corona-warn-app/cwa-documentation#who-we-are): "The German government has **asked** SAP and Deutsche Telekom" (IMHO does not imply public funding)
- [german version](https://github.com/corona-warn-app/cwa-documentation/blob/master/translations/README.de.md#wer-wir-sind): "Die deutsche Regierung hat SAP und die Deutsche Telekom **beauftragt**" (IMHO does imply public funding)

## Where should it be included
FAQ-sections (german, english) of the [website](https://www.coronawarn.app/de/faq/) and who-we-are-sections of the above linked README-Files.

**Comment by hjacobs** [comment]
Agreed. [Code paid by the people should be available to the people](https://publiccode.eu/), so highlighting the public funding is important.

**Comment by cknoll** [comment]
For the record: It now seems to be official that this project is funded with public money: https://www.tagesschau.de/inland/corona-app-downloads-101.html. Still it should be mentioned in the docs and on the website.

**Comment by boldsuck** [comment]
Lobbyism undermines democracy.
https://www.rbb-online.de/kontraste/archiv/kontraste-vom-25-06-2020/corona-warn-app-ziemlich-teuer.html
