### ISSUE TITLE
Understanding E02.05

### ISSUE THREAD

**Issue by sunilgknair051** [corona-warn-app/cwa-documentation#274]
## Where to find the issue

Under the heading _Overview of User Stories_ in scoping_document.md, under the sub-heading _Information and Instructions for Using the App_.

## Describe the issue

The acceptance criteria states: 
    _1. The app provides simple access to the terms of use and data privacy information._
I am trying to understand what simple access here means, is it one-click access or easy readability?

## Suggested change

I would change it to _one-click/understandable and easily accessible_ terms but, I did not want to pull and correct right away until I hear from the experts.

**Comment by tkowark** [comment]
Thank you very much for the question and we're terribly sorry for the extremely late reply. This issue just got lost in the post-launch crazyness.

To given an answer: simple access refers to how easy it is to navigate to the respective information. Hence, it should not be hidden somewhere deep in the menu structure but reachable through only very few interactions. It's not one-click, but all the information is available in the "App information" screen.
