### ISSUE TITLE
UX Legal Notice language

### ISSUE THREAD

**Issue by mrascher-cosee** [corona-warn-app/cwa-documentation#279]
## Where to find the issue
Page legal notice (Android App)

## Describe the issue
Text is complete in english. But why?

**Comment by tkowark** [comment]
Hi @mrascher-cosee Could you please be more specific about the documents you are referring to? Is this something in the app, one the website, or on Github?

**Comment by mrascher-cosee** [comment]
@tkowark sure:

Android -> open menu -> App information ->Legal Notice (Rechtliche Hinweise)

**Comment by tkowark** [comment]
Thank you for the clarification. These are the licenses of third party open source components used within the app and included for legal reasons. As mandated by many of the licenses themselves, the copy of the license provided the project shall be used. Hence, they are all in english.
