### ISSUE TITLE
[minor] link repository in Appstore page

### ISSUE THREAD

**Issue by stheid** [corona-warn-app/cwa-documentation#282]
I think it increases the trustworthyness and spreed in the community if the github page is directly linked in the appstore.

**Comment by SebastianWolf-SAP** [comment]
Dear @stheid, thanks for bringing up that issue. However, please understand that the representation in the app stores is the exclusive responsibility of the Robert Koch Institute. Please reach out to them at coronawarnapp@rki.de or via the other contact options listed on https://www.rki.de/EN/Service/Contact/Contact_node.html

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
