### ISSUE TITLE
Difference between "Feature Request" and "Enhancement" labels

### ISSUE THREAD

**Issue by corneliusroemer** [corona-warn-app/cwa-documentation#285]
Dear maintainers,

You sometimes tag issues with "Feature Request", sometimes with "Enhancement" and sometimes with both.

Can you explain what the difference is between them? I'm confused.

Thanks!

**Comment by tkowark** [comment]
There is no difference, using Feature Requests as an additional label in the website repository was just a mistake on my end. Thanks for spotting that!

**Comment by corneliusroemer** [comment]
Thanks for the explanation @tkowark 

Would it make sense to remove the duplication then? Since you closed the issue without mentioning a PR it seems like nothing is changing. Usually, when issues are justified and fixed, the PR is referenced that closes the issue. And the issue is only closed when the fix is shipped.

**Comment by tkowark** [comment]
I removed the labels with [this commit](https://github.com/corona-warn-app/cwa-website/commit/e841c400555cc1ace973296c7e7c53f48b4a7c0a) and by deleting the label in the repo. Your issues was a question, which I answered. Hence, the issue was closed.

**Comment by corneliusroemer** [comment]
True, but your answer turned it into a bug

**Comment by corneliusroemer** [comment]
@tkowark when will the fix come into effect? I still see both Feature Request and Enhancement when opening new issues in the android repo.

**Comment by tkowark** [comment]
Yes, you're right. With the original question only referring to labels, I was just looking into repos that have this label (cwa-website). Should have looked into the PR templates, too.

Quickly about the intended distinction:
* Feature requests should contain new features that are currently not present
* Enhancements should improve existing feature by making them easier to use

I've added the label to the app repos so now issues created with the respective templates should be labeled properly from now on. Of course, this also affects existing issues as these might have been wrongly labeled. I'll check that tomorrow and adapt accordingly.

**Comment by corneliusroemer** [comment]
Thanks :)
