### ISSUE TITLE
Code of Conduct: Who investigates reports that are made against community leaders?

### ISSUE THREAD

**Issue by ge37kax** [corona-warn-app/cwa-documentation#287]
The code of conduct mentions:
> Enforcement
>Instances of abusive, harassing, or otherwise unacceptable behavior may be reported to the community leaders responsible for enforcement at corona-warn-app.opensource@sap.com. All complaints will be reviewed and investigated promptly and fairly.

If a report against one or several community leaders is made, who will investigate? How is fairness of the process ensured, given that community leaders know each other?

**Comment by SebastianWolf-SAP** [comment]
Thanks for asking this question, @ge37kax. Of course, any report against anybody will be treated fairly and according to the standards which are outlined in the code of conduct, this includes reports against community managers. The community managers are formally appointed by the partners SAP and Deutsche Telekom (see your question in #288). Therefore, they are also responsible for this platform. In the end, they decide how to deal with reports.  

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
