### ISSUE TITLE
Code of Conduct: Who are the community leaders?

### ISSUE THREAD

**Issue by ge37kax** [corona-warn-app/cwa-documentation#288]
The code of conduct gives an important role to **community leaders**, but the term is not defined in the code of conduct.

Thus, my question is: Who are the community leaders? How are they chosen?

**Comment by SebastianWolf-SAP** [comment]
Thanks for asking this question, @ge37kax. The community leaders (or you could also call them community managers) are a group of people that has been defined by Deutsche Telekom and SAP. These entities which have been contracted to publish and manage the Corona-Warn-App as open source project, therefore they are also in charge to appoint them.

You can identify the community managers in the respective issues and pull requests while engaging as moderators and by commenting with the signature containing "Corona Warn-App Open Source Team".

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
