### ISSUE TITLE
Deletion of App and Data Retention

### ISSUE THREAD

**Issue by TomTeeJay** [corona-warn-app/cwa-documentation#29]
![Abbildung 5: User Journey](https://github.com/corona-warn-app/cwa-documentation/blob/master/translations/user_journey.de.png?raw=true "User Journey")

This image gives an schematic overview how the app is working.

The last step in the app lifecycle "Deinstallation" says "ggf. Löschen sämtlicher Daten auf dem Gerät". This means "eventually" or "maybe" and is quite unspecific. When deleting the app the user expects all data is deleted. This includes system logs, crash reports, browser history and all system-wide locations that could be used to track and trace a user.

In addition to this User Story ID # E03.02 says that 

> Die App kann über eine Einstellung in den Auslieferungszustand zurückgesetzt werden, die gespeicherten Traces der letzten Tage **bleiben aber erhalten**.

This means that data won't be deleted entirely even when a user is requesting a reset to the delivery status of the App. 

The documentation is not clear in this matter. How will the App guarantee, that all data is removed entirely from a device?

**Comment by KevinMuessig** [comment]
Dear @TomTeeJay ,

thank you for your question, I will communicate the opened issue with the respective team.

Best,

KM

**Comment by danielburkard** [comment]
Hi,

just regarding the iOS Framework (https://developer.apple.com/documentation/exposurenotification): it seems that it's not possible for the app to delete exposure keys already generated.

Kind Regards,
Daniel

**Comment by wuerzebesser** [comment]
Also I don't understand the use case for such a reset-function when not deleting the sent and collected IDs. According to the documentation (E03.02) the user can then reconfigure the app, but what configurations are we talking about?
I'd assume that changing language, toggling push-notifications and bluetooth, etc. can be done in a typical 'settings' menu item.

**Comment by TomTeeJay** [comment]
Observed from a legal point of view: When a users deletes an app, this can be interpreted as clear will not to use it anymore and as a clear withdraw of any previously given consent. I refer 3.4.1 of the audit of the Austrian Corona-Tracing App created by noyb.eu, epicenter.works and Austrian Red Cross: 

> Since the majority of data processing is based on the consent of the user, a withdrawal of consent must lead to the deletion of these data, unless there is another legal basis on which the data are processed (see Article 17(1)(b) GDPR). According to the information available, this must concern the UUID, the User IDs and the asymmetric key pair, but not the data generated or disclosed in the course of a notification.

Further the audit discovered problems in 3.4.2. Data deletions apart from withdrawal / retention periods where multiple and opposing retention periods were quite unclear.

This app and documentation should take these issue  into account.

**Comment by TomTeeJay** [comment]
Just changed the title to reflect the concept of data withdrawal. In my understanding this app should be absolutely clear in its statements.

**Comment by LukasMasuch** [comment]
I added some more technical information in https://github.com/corona-warn-app/cwa-documentation/issues/36#issuecomment-628536276 about the deletion of the observed identifiers. To summarize: we are still waiting for more clarity on key deletion from Apple/Google.

**Comment by danielburkard** [comment]
I think it’s pretty clear that Apple won’t allow apps to delete the ids or to change any permissions. Since the user can do this (securely) in the main iOS settings. 

![image](https://user-images.githubusercontent.com/1938136/81932343-f8aa8780-95eb-11ea-9352-9cc8e7f9cd89.jpeg)
