### ISSUE TITLE
Metric: Number of Contacts within the App

### ISSUE THREAD

**Issue by stritti** [corona-warn-app/cwa-documentation#292]
## What is missing

To see how good the tracking quality is, it would be nice to see how many contacts the app has exchanged keys with.

## Why should it be included

Then everybody could compare this number (per day) with the number you have in your head to get a feeling how reliable the app's statement is.

## Where should it be included

Should be shown next to the activity counter within the mobile app.

Could this be a privacy issue? If you only have contact with a few people a day. I'm not so sure. What do the experts think?

For other metrics see also: #258

**Comment by mh-** [comment]
The [API](https://static.googleusercontent.com/media/www.google.com/de//covid19/exposurenotifications/pdfs/Android-Exposure-Notification-API-documentation-v1.3.2.pdf) that the Corona Warn App has to use does not give out this information.
Information will only be available after matching with "Diagnosis Keys", i.e. after infected users have uploaded their Temporary Encryption Keys, and after the app has downloaded them and supplied them to the API. Only if matches are found, a little bit of information will be available (which should help understand the risk).

**Comment by SebastianWolf-SAP** [comment]
Big thank you to @mh- - you already explained it why this feature can't be implemented with the current infrastructure. Therefore, I need to close this issue.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by stritti** [comment]
Today I noticed, that there is a logging of code generation in Settings of iOS, but it is not very useful designed for endusers:

![ICovid-19-Kontaktprotokoll](https://user-images.githubusercontent.com/184547/86021902-f1b7c700-ba29-11ea-8d2a-71e9fa51f1d8.jpg)

![IKontaktüberprüfung](https://user-images.githubusercontent.com/184547/86021910-f2e8f400-ba29-11ea-8eb1-cdda5d3fc75c.jpg)

![IDetails prüfen](https://user-images.githubusercontent.com/184547/86021917-f5e3e480-ba29-11ea-8173-050ae57897c2.jpg)
