### ISSUE TITLE
UX: change standard color at none-risk to grey

### ISSUE THREAD

**Issue by AlexanderKaeppler** [corona-warn-app/cwa-documentation#293]
Just a UX point of view. Please read my thoughts and the comments at linkedin: https://www.linkedin.com/pulse/die-gr%C3%B6%C3%9Fte-gefahr-der-corona-warn-app-ist-nicht-sondern-k%C3%A4ppler/, so I would recommend to change the standard color, if no risk was detected to grey, not to give a too good feeling of everything seems to be OK, not to animate people to lower their sensitivity

## Where to find the issue
general basic start-screen, the green color of the "no risks detected" section should always be grey and only in case of risks it should turn to red

## Describe the issue
s. intro

## Suggested change
s. where to find

**Comment by SebastianWolf-SAP** [comment]
Thanks for reporting that, @AlexanderKaeppler. However, I'm sorry to tell you that this request has already been discussed in #220. Moreover, we do not animate people to lower their sensitivity. We state "low risk" and not "no risk". Moreover, there are clear guidelines - even at "low risk" - that people still should stick to the official recommendations.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by AlexanderKaeppler** [comment]
Thank you for the reply, I´m just saying, that the subtile message could be missunderstood... If you discuss that issue in #220 - fine
