### ISSUE TITLE
How will the community be involved in further app development that are not documented in scoping docs?

### ISSUE THREAD

**Issue by corneliusroemer** [corona-warn-app/cwa-documentation#301]
@cfritzsche posted this in response to my question what further features are planned:

> Minimal Roadmap hier: https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Warn_App.html unter der Frage „Wie die Corona-Warn-App weiterentwickelt wird“ wird über Erfassung des Symptombeginns und freiwillige statistische Meldung für wissenschaftliche Begleitung ans RKI gesprochen.

It would be great to hear what the plans are for the community to be involved in these developments. Open Source Community involvement shouldn't end with shipment of the first release. We should also be a part of further developments and be allowed to give feedback and constructive criticism to further developments.

What are your plans regarding the further involvement of the community?

On RKI's website this is provided as a roadmap, is this scoped/documented here?
<img width="502" alt="Screenshot 2020-06-18 at 18 04 37" src="https://user-images.githubusercontent.com/25161793/85044975-a6cac380-b18e-11ea-9a81-de5f2b6c05c3.png">

**Comment by SebastianWolf-SAP** [comment]
Dear @corneliusroemer, dear colleagues,

as already outlined in the project scope at https://github.com/corona-warn-app/cwa-documentation#project-scope, SAP and Deutsche Telekom are 'only' the contractors in this project. The project scope might change over time as new requirements need to be included or existing ones change. We appreciate feedback to all elements of the project. However, additional features or any other content changes beyond fixes need to be aligned on by all partners. 

To streamline the process, to give the community a better overview what's actually planned and what originated from issues by the community, we created the dedicated repositories `cwa-backlog` and `cwa-wishlist`. 

The repository cwa-backlog contains future improvements of the Corona-Warn-App that will be implemented for the next app releases. Please note that this is not a complete backlog but a communication of a subset of planned extensions where we more or less know that they are coming. The repository cwa-wishlist is a place that shall give community members the opportunity to propose and discuss feature additions and improvements for Corona-Warn-App.

We plan to talk regularly with our partners which of the cwa-wishlist contributions can make it to the final product. Updates will be made in the respective issues as soon as we have received news. Until then, the issues will remain open to the community for further discussion and refinements.

These are our plans for now. Thanks for asking this question!

Best regards,
SW
Corona-Warn-App Open Source Team

**Comment by cfritzsche** [comment]
Thanks for this step, I think it will help clarity of what is an issue, what is an idea and what is planned. Since cwa-wishlist will probably become a creative zoo, did you consider a voting system to pre-sort the ideas from community perspective? It could be as easy as counting positive and negative emoticons on the first issue post.
We are already free to react and comment on these. A common understanding of how to rate issues could help though.

**Comment by SebastianWolf-SAP** [comment]
A simple thumbs up vs. thumbs down on the issue itself would be the best and most straight-forward way of doing it, I suppose. 

Of course, you can already get started. However, we still need to get through all repos and move the backlog/wishlist issues accordingly. That might take a few days - depending on the requests that will come in during the same time. But thanks for the support, we really appreciate that you like the new approach. That was exactly what we were hoping for. :)

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
