### ISSUE TITLE
Some close exposures lasting > 10 min are thrown away according to Docs

### ISSUE THREAD

**Issue by CosmicGans** [corona-warn-app/cwa-documentation#307]
## Where to find the issue  
So far people have been referred to this document explaining how the risk assessment is made: 
https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md 

## Describe the issue
As written, I would consider this to be a *very* questionable choice:  
"All exposures for a diagnosis key that lasted less than 10 minutes in total (regardless of how close the smartphones came during that time) or during which the smartphones were more than 8 meters (73 dBm) apart on **average** (regardless of how long the exposure lasted) are discarded as harmless." (Emphasis mine)  

Unless my understanding of the definition of an exposure is wrong, this would lead to an exposure being thrown away where Person A interacts for 10 minutes at close distance with Person B, but afterwards stay in the same larger area for another hour (say a club, or a protest rally). The average distance in that scenario would be higher than 8 meters, and thus the exposure would be discarded, although A and B interacted with each other for 10 minutes at a close distance.

## Suggested change
Since there was no reference in the risk assessment file where to find the actual implementation, I did not verify whether the risk assessment is actually implemented as described. If not, I would suggest to update the documentation, otherwise summing the minutes during which distance was smaller than 8 meters, and discarding those events that do not reach 10 minutes.

**Comment by keugens** [comment]
I would assume, that this choice was taken by the RKI. So the question could be: how they arrived at this choice, what are the relevant research results and studies for this. If the app follows the RKI-rule (< 2 m and > 15 min), the question has to be related to this rule as well.

To my understanding, these calculations are performed by the Google/Apple api and are controlled by parameters, which are defined by the health authority. Attenuation is used as a replacement quantity for some distance in Meter. There is a calculation of the relevant attenuation as an average of single attenuation values, weighted (somehow) by the corresponding durations.

**Comment by SebastianWolf-SAP** [comment]
Thanks for the note that we forgot to reference the actual parameter values in the risk assessment. We just updated the references which were already mentioned in #229, please see https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md#current-configuration

More background information about these parameters were mentioned by @BenzlerJ in #257 

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by pdehaye** [comment]
This issue has not been addressed in the document referenced ( https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md#current-configuration ) but has nevertheless been closed, together with many other issues. 

Since the  document does answer some of the questions, I have consolidated all that remain, to the best of my ability, in #336.

**Comment by corneliusroemer** [comment]
I totally agree with @pdehaye that OP's question is not answered in either of the linked resources. I've noticed this bad pattern be repeatedly employed by maintainers. Yes, I understand, some questions could be solved by reading the documentation - but please assume good faith when people make the effort to write important questions - especially if they come up repeatedly as evidenced by all the issues referenced in #336
