### ISSUE TITLE
App chain of trust unclear

### ISSUE THREAD

**Issue by sme-gmbh** [corona-warn-app/cwa-documentation#310]
In the documentation I am missing a description how the interested user checks whether the app in the app store is actually built from the code on github.

Normally everybody should be able to compile an open source project on his own and get a binary identical version of that which is beeing rolled out. But the deployment of that self compiled version is prohibited as the notification layer only works if the app is signed by RKI. So at least a user should be enabled to check that the installed app is exactly compiled from the code on github. Otherwise the whole open source concept of the app is useless as the vendor could just add code right before roll-out that nobody can verify. 

In my opinion the vendor lock in is totally unnecessary and breaks the chain of trust. Anyone who wants to compile and run that app code on his own just needs to implement the bluetooth protocol specification on an open device / operation system of his choice.

So please present a description how to perform the binary verification of the version in the app store against the source code in the github repository. And better please let google remove that totally useless vendor lock-in so everyone who is concerned in data security is able to compile and run his own version on non open phone targets and not only on linux phones / desktops with high amount of engineering work.

**Comment by mh-** [comment]
Please see https://github.com/corona-warn-app/cwa-documentation/issues/14

**Comment by mynchau** [comment]
Hi sme-gmbh, thank you for your contribution. As mh- already pointed out, your question has been asked earlier and a comment will be posted by the team there. To avoid duplicate issues, I'm closing this one. Please feel welcome to add your comments in #14 and see updates according to https://github.com/corona-warn-app/cwa-documentation/issues/14#issuecomment-644292622
Best regards,
MC
Your Corona Warn-App Open Source Team
