### ISSUE TITLE
Determination of the exposure configuration parameters 

### ISSUE THREAD

**Issue by ay-kay** [corona-warn-app/cwa-documentation#312]
* Source File: https://github.com/corona-warn-app/cwa-server/blob/eb8be6c3e9c723c62c619784e41889d10054cc93/services/distribution/src/main/resources/master-config/exposure-config.yaml#L13-L58
* Line(s): 13-58
* Question: Does RKI publish how the risk score calculation parameters were determined (#576)? At first glance, it's surprising that there are hardly any gradations in the level values, particularly in duration and attenuation, which are all rated with the lowest risk level.

**Comment by pdehaye** [comment]
@CosmicGans This is indeed a concern, see #322. I think combined with what's described in #228 it can lead to false negative attacks.

**Comment by pdehaye** [comment]
@CosmicGans The [Apple doc](https://developer.apple.com/documentation/exposurenotification/enexposureconfiguration) says

> The attenuation (transmission power - RSSI) can vary during an exposure event. Attenuation values >0 are weighted by the duration at each risk level and averaged for the overall duration. The framework measures and calculates this value.

which seems to be the source of that "on average" statement, which should be corrected. This is nevertheless problematic.

**Comment by SebastianWolf-SAP** [comment]
Sorry that we haven't gotten back to you earlier. We also missed to inform you about the addition by Fraunhofer IIS that we received a few weeks ago: https://github.com/corona-warn-app/cwa-documentation/blob/master/2020_06_24_Corona_API_measurements.pdf

That should explain the background of the determination of the exposure configuration parameters.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by pdehaye** [comment]
Thank you for this document. I see that the "real-life train scenario" was done in a warehouse with people sitting on wooden chairs (except for a handful which were some kind of exhibition chairs). This looks very unrealistic compared to some experiments conducted by an Irish team in a [real train carriage](https://www.scss.tcd.ie/Doug.Leith/pubs/bluetooth_rssi_study.pdf). That experiment concluded there would be significant obstacles to using the app productively in such scenario, due (for instance) to the metal in the real train seats, and the confined "cigar" shape of a train carriage). 

Has a more realistic experiment been performed since? Where?

**Comment by SebastianWolf-SAP** [comment]
Thanks for providing the reference to the Irish project. I just reached out again to our contacts at Fraunhofer IIS. Will get back to you once we have additional information.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by pdehaye** [comment]
I see that they have a more recent paper, where they actually tested the CoronaWarnApp [configuration settings in a real life light rail train](https://www.scss.tcd.ie/Doug.Leith/pubs/luas.pdf). 

Conclusion:

> We  find  that the  Swiss  and  German  detection  rules  trigger  no  exposure notifications  on  our  data,  while  the  Italian  detection  rule generates a true positive rate of 50% and a false positive rate of  50%.  Our  analysis  indicates  that  the  performance  of  such detection rules is similar to that of triggering notifications by randomly  selecting  from  the  participants  in  our  experiments, regardless of proximity
