### ISSUE TITLE
ux: hotline / help 

### ISSUE THREAD

**Issue by kosmar** [corona-warn-app/cwa-documentation#313]
- i feel the hotline is not obvious and usable enough to be found by people that do have actual technical problems and are therefore already in a stressed mindset.

- language ist an aspect here too and the current placement will prevent many non-en/de-speaking user from finding it effectively, i would expect. (it is now under 'App-informationen' the 6th item in a list of 7)

- anecdotal reference: https://www.zeit.de/digital/mobil/2020-06/corona-warn-app-gesundheitsaemter-anfragen-hotline-nutzer-downloads

- i propose to put a section on the mainscreen in an appropriate position, probably before or inside the FAQ teaser.

```
Haben Sie technische Probleme oder Fragen? [individual OS lang i18n]
Do you have technical problems or questions? [english]

[ +49 800 754001 (kostenfrei, free call) ]

```

- in addition i would like to propose a [help icon] next to [share icon] as a persistant access to help/faq/hotline

- secondary, i dont quite understand, why the hotline ist restricted to technical issues. 

**thank you for your work so far, your doing a good job in a good way**

**Comment by tkowark** [comment]
As this is a cross-platform suggestions, we're moving it to the documentation repo.

**Comment by SebastianWolf-SAP** [comment]
Small update from our side: This is one topic of the upcoming discussions with our partners. So we hopefully have an update soon.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by SebastianWolf-SAP** [comment]
We now have the official answer - as a consequence, we will close this issue for now:

> During the launch-phase of the App, there has indeed been an high volume of phone calls, which reached both the technical hotline as well as the health authorities. 
> In the meantime, there has been a significant decline in the phone call volume. In addition to that, the official campaign, information websites (e.g. by the RKI, Bundesregierung) and the App FAQ have been optimized are now widely known, so information is accessible to users via many other channels as well.
> Taking these 2 factors into account, it doesn’t seem to be necessary to adapt the placement of the hotline info for now.
We will still monitor this matter closely and reevaluate the hotline placement, if it becomes necessary.

Mit freundlichen Grüßen/Best regards,
SW
Corona Warn-App Open Source Team

**Comment by kosmar** [comment]
thanks for considering.

sorry to say, but getting only few hotline calls as a reason for _not_ making it easier to call the hotline
sounds like https://en.wikipedia.org/wiki/Survivorship_bias to me
