### ISSUE TITLE
Can I as a user see statistics, about my bluetooth contacts?

### ISSUE THREAD

**Issue by hayrom42** [corona-warn-app/cwa-documentation#32]
## What is missing

I did not see a user story/epic that shows me as a user, what the app collected during the days. I could envision a statistical view, how many devices have been close to me within a certain range for a certain amount of time.
## Why should it be included

This gives transparency to the user, what the app is doing and collecting.
## Where should it be included

In the user stories during the 'Nutzung im Regelprozess'

**Comment by LukasMasuch** [comment]
Hey @hayrom42, Thanks for your suggestion. The [Exposure Notification API](https://www.google.com/covid19/exposurenotifications/) from Apple/Google does not allow the app to access (or count) the observed Identifiers for protection of the user's privacy. So, it is not technically possible for the app to aggregate this statistic.
