### ISSUE TITLE
artifact in architecture-overview.md

### ISSUE THREAD

**Issue by MichaelPFrey** [corona-warn-app/cwa-documentation#323]
## Where to find the issue

https://github.com/corona-warn-app/cwa-verification-server/blob/master/docs/architecture-overview.md#user-journey-tan-verification-based-on-integrated-laboratories Step 1:
`[You can use numbers for reference-style link definitions][1]`
 

## Describe the issue

`[You can use numbers for reference-style link definitions][1]` looks like an artifact from editing the file.

## Suggested change

Remove `[You can use numbers for reference-style link definitions][1]` or replace it with the correct link (if applicable)

**Comment by tkowark** [comment]
Artifact was removed in the meantime. Thanks for spotting that issue.
