### ISSUE TITLE
Smart watch support

### ISSUE THREAD

**Issue by devurandom** [corona-warn-app/cwa-documentation#325]
## What is missing

Information whether the Android app can utilise smart watches while they are out of range from their telephones.

I would imagine to be able to do sports with just a watch on and once I return to my telephone the IDs encountered during sports are transferred from the watch to the phone. Does the app support something like that?

## Why should it be included

Apart from shopping my main point of contact with other people is sports. During sports I do not carry my telephone with me. I wonder whether it would make sense to get a smart watch in order to keep my community safe using this app.

## Where should it be included

I tried searching the cwa-app-android, cwa-documentation and cwa-website repositories for "watch", but could not find a specific answer relating to whether smart watches are supported for my use case. (i.e. I would expect the information to be included in at least one of these places)

**Comment by SebastianWolf-SAP** [comment]
Dear @devurandom,

thanks for reporting that issue. However, this has been asked and answered several times already, it is currently not planned and we already have respective information on our website.

Please see the issues https://github.com/corona-warn-app/cwa-documentation/issues/240, https://github.com/corona-warn-app/cwa-wishlist/issues/12, https://github.com/corona-warn-app/cwa-app-ios/issues/709 and our FAQ at https://www.coronawarn.app/de/faq/#smartwatch for details.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
