### ISSUE TITLE
Slightly incorrect statement in "Designentscheidungen" document

### ISSUE THREAD

**Issue by mh-** [corona-warn-app/cwa-documentation#327]
## Where to find the issue

https://www.coronawarn.app/assets/documents/cwa-datenschutz-folgenabschaetzung-anlage1.pdf
Page 10, 1. Anwendungsphase: App läuft im Hintergrund:

## Describe the issue
"Außerdem speichert das Gerät automatisiert und **_verschlüsselt_** die kurzlebigen Zufalls-IDs, die von in der Nähe befindlichen Geräten gesendet werden, einschließlich definierter Parameter über die Entfernung und Dauer des Kontakts der Geräte."

## Suggested change
"Außerdem speichert das Gerät automatisiert die kurzlebigen Zufalls-IDs, die von in der Nähe befindlichen Geräten gesendet werden, einschließlich definierter Parameter über die Entfernung, **_Zeitpunkt_** und Dauer des Kontakts der Geräte."

**Comment by SebastianWolf-SAP** [comment]
Hi @mh-,

thanks for bringing that up. We will forward this to our legal team and the RKI - both are in charge of the data privacy impact assessment.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by SebastianWolf-SAP** [comment]
Got some information - as any change needs to be aligned among many parties (especially legal), the change might take a while (1-2 weeks+). We'll keep you posted!

Mit freundlichen Grüßen/Best regards,
SW
Corona Warn-App Open Source Team

**Comment by GPclips** [comment]
Hello @mh-,

today I checked with our documentation team. They have added your improvement to the docuemntation.
Sorry for the late feedback and thank you for your support and sharing your ideas.

Thanks,
LMM

Corona Warn-App Open Source Team

**Comment by mh-** [comment]
@GPclips can you please show where the changes in the documentation can be found? 
The currently published version https://www.coronawarn.app/assets/documents/cwa-datenschutz-folgenabschaetzung-anlage1.pdf still has the incorrect statement.

**Comment by GPclips** [comment]
Hello @mh- ,

thanks for letting me know. I will reach out internally, to check with the team.

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
This is corrected in https://github.com/corona-warn-app/cwa-website/blob/master/src/assets/documents/cwa-datenschutz-folgenabschaetzung-anlage1a.pdf

----
Corona-Warn-App Open Source Team
