### ISSUE TITLE
how does the qr-code / Tan-System verification work in detail ?

### ISSUE THREAD

**Issue by fabianus76** [corona-warn-app/cwa-documentation#328]
## Your Question
I am not sure if this is the right place for my question.
Once I installed the Corona-Warn-App I posted a motivating message on facebook to invite friends to do the same. The reactions I received were quite mitigated. So I decided to poste a little explanatory video to give some more "technical" insight in order to increase objectivity. 
The video got more intention than I expected (otherwise I would have given more effort into it). 
Here it is: [video on facebook](https://www.facebook.com/fabianvonberlepsch/videos/10220192741667560/?id=10220192748787738&overlay=1&notif_id=1592553381919745&notif_t=story_reshare)

Divers question come up and I answered them as good as I could without spending time looking into the code. And now I have a question that I would love to clear up but I am not able without the help of somebody that knows the details: 

People mind what happens if someone wants to disturb the system intentionally and declare a false positive. I explained that ether a qr-code or a TAN-System are put into place to prevent this. 
But someone stated, that those qr-codes - if they are not bound to the person - could be falsified. In order to respond to this I would like to know how the qr-code and TAN-System are working. 
An idea could by that an anonymous ID is created at the server by the testing laboratory and once the infected app-user is publishing the positiv test by mean of the qr-code, the existence of the said anonymous ID is verified. Just describing this hypothetical scenario to give an idea of the details that I would like to know in order to give them to the facebook community. 

Thanks a lot for any feedback - ether on my question or about the right place to ask it.

**Comment by mh-** [comment]
@fabianus76 you don't need to read source code, you could just read the documents, like 
https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md 
https://github.com/corona-warn-app/cwa-server/blob/master/docs/ARCHITECTURE.md 
https://github.com/corona-warn-app/cwa-verification-server/blob/master/docs/architecture-overview.md

**Comment by SebastianWolf-SAP** [comment]
A big thank you go to @mh- for already answering the question. Our documentation should hopefully answer your questions, @fabianus76 

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
