### ISSUE TITLE
Incompatibility with the App Immuni

### ISSUE THREAD

**Issue by OlafRadicke** [corona-warn-app/cwa-documentation#329]
## Describe the bug

I've runned your App for some days and everything was fine. Than I installed the Add "Immuni" (https://play.google.com/store/apps/details?id=it.ministerodellasalute.immuni). On the first look it was fine too, but one day later I opened the  corona-warn-app and I saw that tracking has stopped. I've seen the message: Corona-Warn-App does not track your location and doesn't have the permission to do this. So I switched this on again. But now, I get the same warning from the other App  "Immuni". With other words: only one of this Apps can run. 

## Steps to reproduce the issue

- Install and start corona-warn-app
- Install "Immuni" (https://play.google.com/store/apps/details?id=it.ministerodellasalute.immuni). 
- wait 10 minutes
- Reopen corona-warn-app and you will see, that is stopped.
- Reactivate corona-warn-app
- Switch back to "Immuni" and see the warning and that the App is stopped now

## Technical details

- Mobile device: Nokia 7 plus
- Android version: 10

## Additional context

- It's not rooted device
- All Apps are downloadned from Playstore

**Comment by jurkov** [comment]
A workaround would be to use two different phones. It's not great to carry always two phones, but it's the safest way.

**Comment by sventuerpe** [comment]
Is everyone aware of the recently released [European interoperability guidelines](https://ec.europa.eu/health/ehealth/key_documents_en#anchor0)? Would they solve this problem?

**Comment by sventuerpe** [comment]
To answer my own question in abstract terms after skimming the documents: Once this interoperability solution is implemented, everyone uses the app of their home country with its respective back-end. National apps are extended so that they can register travel to other participating countries, e.g., based on user input. Diagnosis keys are exchanged between national back-ends so that contacts can be properly notified in cross-border situations. 

(Please correct me if I misunderstood anything.)

**Comment by SebastianWolf-SAP** [comment]
Dear colleagues,

sorry for the late answer! It seems that the relevant information has already been shared, thanks to @mh- and @sventuerpe! Cross-border interoperability will be worked on - please follow-up with issue https://github.com/corona-warn-app/cwa-backlog/issues/14. The idea is that you will only need to install one app - the one from your "home" country and the diagnosis keys will be exchanged across the respective backends. Many details will still need to be found out, but as the "Highlander Principle" is forced by the Google/Apple framework, we can't solve this issue.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
