### ISSUE TITLE
iOS 14 compatibility

### ISSUE THREAD

**Issue by daleky** [corona-warn-app/cwa-documentation#334]
(First off, I know iOS 14 is really new and not available to everyone yet. I just noticed this and wanted to report on it)
I got the iOS 14 Beta for developers today and when I tried to start the Corona-warn-App all I get is a black screen. I tried reinstalling the app but exposure logging can’t be enabled and the app freezes when trying to enable notifications. I know this isn’t a main problem because almost no one has iOS 14 at this point, I just wanted to make sure the issue is known. 
Thanks!

**Comment by tkowark** [comment]
Thanks for pointing that out. The ENF is unfortunately not available in the iOS 14 Beta:
https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-14-beta-release-notes

We will add an FAQ item for that since there seem to be many very early adopters :)

**Comment by tkowark** [comment]
We also added this question and the corresponding answer to the FAQs on the website: https://www.coronawarn.app/en/faq/#ios_14_beta
