### ISSUE TITLE
How were some of the parameters decided on?

### ISSUE THREAD

**Issue by pdehaye** [corona-warn-app/cwa-documentation#336]
## Consolidation
After prodding a bit in #229, #256, #257, #307, we get some more information about [how and where](https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md#current-configuration) the parameter values are set in the code:

- [Exposure Configuration](https://github.com/corona-warn-app/cwa-server/blob/master/services/distribution/src/main/resources/master-config/exposure-config.yaml)
- [Attenuation & Duration Configuration](https://github.com/corona-warn-app/cwa-server/blob/master/services/distribution/src/main/resources/master-config/attenuation-duration.yaml)
- [App Configuration, including minimum risk score](https://github.com/corona-warn-app/cwa-server/blob/master/services/distribution/src/main/resources/master-config/app-config.yaml)
- [Risk Score Classification](https://github.com/corona-warn-app/cwa-server/blob/master/services/distribution/src/main/resources/master-config/risk-score-classification.yaml)

## Background
The configuration of CoronaWarn, as described in the [solution architecture document](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#risk-score-calculation), leverages two parts of the GAEN API: an "Exposure Score" (based on a per exposure summary) and a "Normalized Total Risk Score" (based on an aggregate) to calculate the risk. The interesting bit is that SwissCovid relies on the first, while Immuni relies on the second. So in a perfect world, each component of this risk score would match each of those other deployments (no?). 

## Remark

We still don't have clarity (#307) on the bold part of

> All exposures for a diagnosis key that lasted less than 10 minutes in total (regardless of how close the smartphones came during that time) or during which the smartphones were more than 8 meters (**73 dB attenuation) apart on average** (regardless of how long the exposure lasted) are discarded as harmless.

except that [this line is probably the mean this is achieved](https://github.com/corona-warn-app/cwa-server/blob/0c1794e002070063c2fa1ac46fd221a505ff869b/services/distribution/src/main/resources/master-config/exposure-config.yaml#L51).

## Questions

I still have a few questions though:
1. why is there this clipping at 73dB "on average"? what does "on average" mean? (this was #307, left unaddressed there, even though the issue is now closed)
2. why isn't the [weight 0 for exposures between 10 and 15 minutes](https://github.com/corona-warn-app/cwa-server/blob/0c1794e002070063c2fa1ac46fd221a505ff869b/services/distribution/src/main/resources/master-config/exposure-config.yaml#L34)?  This differs from the [Immuni configuration](https://get.immuni.gov.it/v1/settings?platform=ios&build=1), for instance (this is https://github.com/corona-warn-app/cwa-server/issues/601 on the server repo)
3. what are the `app_defined` factors? what do they mean, beyond a numeric value of risk?
4. what is the idea behind the `deault-bucket-offset` (currently [set to 0](https://github.com/corona-warn-app/cwa-server/blob/0c1794e002070063c2fa1ac46fd221a505ff869b/services/distribution/src/main/resources/master-config/attenuation-duration.yaml#L19), not really explained in the [solution architecture](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#risk-score-calculation))
5. given that `default-bucket-offset` is 0, I would have expected that your configuration of `attenuationThresholds` should match the Swiss one for that part, but it differs significantly. With the same weights as you of `[1, 0.5, 0]`, they chose [`[50, 55]`](https://www.pt.bfs.admin.ch/v1/config?appversion=&osversion=&buildnr=) while you chose [`[55, 63]`](https://github.com/corona-warn-app/cwa-server/blob/0c1794e002070063c2fa1ac46fd221a505ff869b/services/distribution/src/main/resources/master-config/attenuation-duration.yaml#L12-L18
). Given what I said in the Background above, I am very surprised by this difference. What am I missing?
6. How was the [Risk Score classification threshold value of `15`](https://github.com/corona-warn-app/cwa-server/blob/0c1794e002070063c2fa1ac46fd221a505ff869b/services/distribution/src/main/resources/master-config/risk-score-classification.yaml#L15-L18) chosen?
7. what does ["the attenuation is weighted by the duration at each risk level and averaged for the overall duration"](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#risk-score-calculation) mean?

In general we can now tell where each factor is set, and what the value is, but not _how_ it was decided to set it to that value (even once the [solution architecture](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#risk-score-calculation) was chosen). The [risk scoring documentation](https://github.com/corona-warn-app/cwa-documentation/blob/master/transmission_risk.pdf) does not answer those questions either.

**Comment by SebastianWolf-SAP** [comment]
Dear @pdehaye,

I'm sorry that I forgot to update all references in the respective issues to the [central cwa-wishlist issue](https://github.com/corona-warn-app/cwa-wishlist/issues/34) that I explicitly reopened yesterday to address these open questions. As the other issue was opened earlier and especially has seen quite an interesting discussion already, I copied your detailed questions over to the other issue so that we can address them altogether. I hope that is OK for you!

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by jensjensenjens** [comment]
See also my attempts in the PR  #320 to link these into the documents. @SebastianWolf-SAP What's the workflow regarding such PR's. Haven't heard anything from your team about it?

**Comment by SebastianWolf-SAP** [comment]
The workflow is that for major improvements, we first need to have a handshake via a GitHub issue that somebody can work on that. Otherwise there might be the problem that people work on things which we are not able to change or only very hard as legal discussions are needed. See also the README:

> We appreciate feedback to all elements of this project scope document. However, additional features or any other content changes beyond fixes to grammatical issues or typos need to be aligned on by these partners before they can be included in the document. Thank you for your understanding!

We definitely need to communicate that more explicitly for example like already done in the iOS and Android repositories: https://github.com/corona-warn-app/cwa-app-ios/blob/develop/.github/pull_request_template.md

Our team will keep you updated. We will tackle the open issues and PRs over the next days/next week with respective answers. Thanks for your understanding that things simply take their time and we want to give proper answers to everybody.

Mit freundlichen Grüßen/Best regards,
SW
Corona Warn-App Open Source Team
