### ISSUE TITLE
Corona-Warn-App | iOS 14 Support

### ISSUE THREAD

**Issue by manuelfrick** [corona-warn-app/cwa-documentation#337]
Hallo Zusammen,

leider funktioniert die Corona-Warn-App mit iOS 14 nicht mehr. Es erscheint nur noch ein leerer Bildschirm beim Öffnen der App.

Könnt ihr das evtl. asap beheben, sodass auch „Beta-Tester“ Zugriff auf die App haben?

Mit freundlichen Grüßen
Manuel

**Comment by cfritzsche** [comment]
Hi @manuelfrick, this was already reported and is tracked in https://github.com/corona-warn-app/cwa-wishlist/issues/33

**Comment by tkowark** [comment]
Yes, and it is also part of our [FAQ](https://www.coronawarn.app/de/faq/#ios_14_beta). We hope it gets fixed, soon, but from an application side cannot solve that issue at the moment.
