### ISSUE TITLE
Add examples for the Risk calculation to make the decision making of the app more transparent

### ISSUE THREAD

**Issue by hagct** [corona-warn-app/cwa-documentation#338]
## What is missing

I read the docs for the calculation of the risk parameters, but its not very transparent and some informations give opposing results. Eg. the varible for the signal strength is always "1" when the dampening is below 73 dB. But the risk calculation document says, that further calculations are done, when the dampening was smaller than 63 dB and 55 dB. But how this calculation is exactly done is nowhere explained.

Also the variable for the days gone since the contact is always the same for the last 14 days. Instead the Transmission risk value now represents the time passed between the usage of the key and the transmission to the server for a warning.

To claryfy things I would suggest, that the documentation about the calculation of the risk should have at least one or two complete example calculations, where all real parameters and numbers are used. One calculation should be just below the threshold to give out a warning and one should be above. 
 

## Why should it be included

Its unclear for users, how the score is exactly calculated. But this is a core functionality and it should be as transparents as the datasecurity. If people know, how the calculation is done, they would give more trust in the app, when they get a red warning.

## Where should it be included

the calculation examples should be added to https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md

**Comment by SebastianWolf-SAP** [comment]
Thanks for that feedback. We will work on that and provide some examples soon.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by jensjensenjens** [comment]
How about integrating #320 ? It contains some clarification and examples. The PR was submitted almost week ago, but no feedback. What's the workflow of getting PRs merged?

**Comment by tkowark** [comment]
Dear @jensjensenjens , we are in the process of preparing some examples, and the colleagues from RKI will also have a look at your proposals in #320 for that matter.

**Comment by tkowark** [comment]
Example is now available in https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md#an-example
