### ISSUE TITLE
Manual process with TANs

### ISSUE THREAD

**Issue by TomTeeJay** [corona-warn-app/cwa-documentation#34]
User Stories ID # E06.04, E06.05 and E06.06 describe a manual process. Honestly I wonder how this should work if by then the user is not known and still anonymous and therefore not identifiable? Does this mean, that there is some kind of manual key exchange with a call-center agent? Assuming there will be 82 Mio users how long must a key be to maintain entropy and to prevent replay-attacks? How to ensure that the caller triggering the manual process is the person he/she claims to be?

**Comment by MalteJ** [comment]
Please wait until the architecture docs are released. You will find more info in those docs.
