### ISSUE TITLE
Export/import of data?

### ISSUE THREAD

**Issue by PolynomialDivision** [corona-warn-app/cwa-documentation#340]
Can I save the necessary data to a backup to restore the data after a wipe of my phone or switching to another device?

**Comment by n-thumann** [comment]
No, this data isn´t part of the backup ✌️ 
See https://www.coronawarn.app/de/faq/#backup

**Comment by PolynomialDivision** [comment]
> No, this data isn´t part of the backup v
> See https://www.coronawarn.app/de/faq/#backup

Why not adding an export/import feature in the android app, so that I can export the data to some plain json object?

**Comment by tkowark** [comment]
Because the app cannot access the data store containing the RPIs. We do have a wishlist item for that use case, in case technical foundation in the future allows that: corona-warn-app/cwa-wishlist#8
