### ISSUE TITLE
Do some apps only receive but do not send RPIs?

### ISSUE THREAD

**Issue by BudickDa** [corona-warn-app/cwa-documentation#348]
## Do some apps only receive but do not send RPIs?
I stumbled upon this [issue](https://github.com/corona-warn-app/cwa-app-android/issues/688) but did not want to hijack the discussion.

As far as I understood, the app needs Android 6 and Bluetooth Low Energy to install, but also need to be able to transmit in peripheral mode.
This means, there are users that have the app installed, but do not send RPIs thus being invisible to other apps.
Did I understand this correctly?

Are there estimation about how many users use the app this way?

Are those users informed about it? If not, why?

A lot of people are using the app to protect their friends and family. 
If they are using the app without sending RPIs, they only protect themself. 
I think they should know about it, and should be given the choice to upgrade their hardware (like Frau Bär proposed) or should start keeping track of their contacts by other means ([pen and paper](https://github.com/corona-warn-app/cwa-documentation/issues/40)).

**Comment by monikaschmitt** [comment]
Hi @BudickDa 
Thanks a lot for bringing this up. We will get back to you as soon as possible.
Best
MS
Corona Warn-App Open Source Team

**Comment by geos-github** [comment]
Just to clear up some misconception ("If they are using the app without sending RPIs, they only protect themself.")
The app under no circumstances can or does protect its user. Even if someone (just) receives RPIs, the only benefit the app can provide is to inform that person about a encounters with a infected person that happened a few days ago. At the time of notification by the app the encounter has already happened and thus either the user of the app has or has not been infected. The app cannot protect its users. This point apparently cannot be stressed enough. All the app can do is to notify the user, which might prompt some action (i.e. get tested, self-quarantaine, whatever), which might prevent further infections by that app user to third parties (completely irrespective of the latter ones using the app or not, by the way).
So the above sentence should read "if they are using the app without sending RPIs, they can protect only the people whom they later would have come into contact with (not the ones their contacts will come into contact with)".

**Comment by BudickDa** [comment]
@geos-github I did use the word protect because I had no other. 
Of course: software on a smartphone cannot prevent an infection.
But to protect their loved one is a big motivation for a lot of users. And as long as we don't have a better word, I will use "protect".
And in a way the app (if everything works) protects people, by getting it's users into isolation faster.

But it also protects the vulnerable in a more direct way:
If Person A, B and C have the app.
Person A gets infected, the app registered the risk, but does not send RPIs. Person B had contact with A and later with C. Person C gets Covid and dies, because Person B thought he/she was save and got the news of A's infection too late, because A thought the app would inform B.
If A had know about the "half-working" app they could have warned their contacts faster, but they did not, because of the app.

This is why I think the app must inform the user if the smartphone can't send RPIs or it could result in tragedy.

I hope this example made my question/issue more clear.

**Comment by monikaschmitt** [comment]
Dear @BudickDa 
This issue is known. We would therefore like to refer you to this issue #688 and close this issue here.
I also saw that you're already active in this issue as well.
Thanks and BR
MS 
Corona Warn-App Open Source Team
