### ISSUE TITLE
Impact of changing transmissionRiskDefaultVector ?

### ISSUE THREAD

**Issue by christianbrb** [corona-warn-app/cwa-documentation#349]
## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Question has not already been asked in another issue

## Your Question
I have a question regarding PR https://github.com/corona-warn-app/cwa-app-ios/pull/608

What is the impact of changing the `transmissionRiskDefaultVector `?

What happens if different keys are associated with different `transmissionRiskDefaultVector`?

**Comment by mh-** [comment]
@christianbrb If you want to read up more details on this already now, it's explained here: https://github.com/corona-warn-app/cwa-documentation/blob/master/transmission_risk.pdf (case 4 / Figure 14)

**Comment by christianbrb** [comment]
Hey @tkowark and @mh- :) Thanks for your answers!

Is it an intentional design, that the risk vector is configured within the app? Was there a specific design decision to not configure it centrally within the cwa-server? 

It seems to be a very important parameter and it is just controlled by the PR review process. I haven't found test using it.

**Comment by mh-** [comment]
> I haven't found test using it.

Actually, there is one [test](https://github.com/corona-warn-app/cwa-app-android/blob/master/Corona-Warn-App/src/test/java/de/rki/coronawarnapp/util/ProtoFormatConverterExtensionsTest.kt) in the Android App now: https://github.com/corona-warn-app/cwa-app-android/pull/679/files#diff-d64cec3d2ea0a64d0536da01937b6092

**Comment by christian-kirschnick** [comment]
> Is it an intentional design, that the risk vector is configured within the app? Was there a specific design decision to not configure it centrally within the cwa-server?

Yes, it was a conscious decision to not make it part of the app configuration. The app config shall only contain values which are subject to change at some point in time.

The transmission risk vector is sufficiently stable and we do not anticipate any changes there.

**Comment by tkowark** [comment]
In the meantime we added the example to the risk assessment document, which provides much more detail on how transmission risk levels are applied to the uploaded keys: https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md#an-example

We hope that also clarifies the effects of a changed default vector. If there are further questions, your can of course always open up a follow-up issue.
