### ISSUE TITLE
Translation of the app to Spanish: where and how to contribute

### ISSUE THREAD

**Issue by ouboub** [corona-warn-app/cwa-documentation#350]
## Your Question

I am not sure whether this is the right forum to ask. If it is not I apologize and would like to ask for a pointer.
I am extremely interested in the Spanish translation of the app. 
Since this is an open source project: where and how could I contribute?
thanks and regards
Uwe Brauer

**Comment by mynchau** [comment]
Hi ouboub, 
thank you for your interest in contributing to Spanish translations.
We do have a dedicated team of certified translators and legal experts that focuses on texts and translations in alignment with the RKI which means that for now there is no additional support needed.

Best regards, 
MC
Your Corona Warn-App Open Source team

Please close this issue if this answered your question. If no action by you is being taken, this issue will be closed in a few hours.

**Comment by thilakm-git** [comment]
Sorry to revive this question. In response to an [answer](https://twitter.com/cem_oezdemir/status/1304064631217020930) to a member of German parliament from the German government regarding costs (€250k) involved for an additional language support in CWA. Why don't we involve the community and do crowd translation for additional "unofficial" languages? You could include "Kurdisch (inofiziell)" to show this isn't an officially supported language / hasn't been verified. 

Either way, it would create immediate impact by a) engaging the community (transparency) and b) reaching more people in Germany (more effective).

**Comment by cfritzsche** [comment]
Thanks for your offer. This would certainly help engaging users and the community.

Knowing how conservative RKI has been just with releasing the app to additional countries due to legal questions, I think there is zero chance that the community will get to translate the data privacy and legal texts within the app. It would just pose too high a legal risk.

**Comment by carstenhag** [comment]
The solution could be to accept a PR, then have the RKI revise the translation. The cost would be way lower (not the 250.000€ amount).
