### ISSUE TITLE
Change directory layout to full fill multi language spellchecking

### ISSUE THREAD

**Issue by dreh23** [corona-warn-app/cwa-documentation#352]
For multi-language spellchecking we should change to a better directory layout [see](https://github.com/corona-warn-app/cwa-documentation/pull/215#issuecomment-645627697)

**Comment by tkowark** [comment]
For the foreseeable future, we will only have english documents in the main folder and german translations in the the translation repository. So, we can leave the folder structure as-is for now and only apply german spellchecking for the translations folder.

**Comment by dreh23** [comment]
Sounds good. This is easily changeable if needed.
