### ISSUE TITLE
Feat: Implement a naming convention on filenames

### ISSUE THREAD

**Issue by dreh23** [corona-warn-app/cwa-documentation#353]
Let's implement a naming convention on filenames.

**Comment by tkowark** [comment]
The lower and uppercase names are in fact due to the translations of standard [Github health files](https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file). What else do you have in mind?

**Comment by dreh23** [comment]
Basically just decide on underscore OR hyphen. Right now we have a mix.

**Comment by SebastianWolf-SAP** [comment]
We just discussed that and unfortunately need to close this ticket with 'wontfix'. Changing the existing filenames would probably create quite some effort with existing links and not add much additional benefit.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
