### ISSUE TITLE
Technical documentation - Spanish translation

### ISSUE THREAD

**Issue by adrianapintod** [corona-warn-app/cwa-documentation#354]
I consider that this development, which puts the user privacy as the highest priority, will be impactful in other geographies far away from Europe. Therefore, I would like to translate the technical documentation into Spanish. I have seen that
Latin America is the current epicenter of the COVID-19 pandemic. Statistics showcase a grim future for this region, and a contact tracing app implementation based on this project will be hugely beneficial. The translation will be helpful since Latin American countries lack expertise in the English language, and the English only documentation will be a barrier when trying to get to apply this solution.

**Comment by jarjarbentley** [comment]
Hi adrianapintod,

thank you for your interest in contributing to Spanish translations.
We do have a dedicated team of certified translators and legal experts that focuses on texts and translations in alignment with the RKI (app ownership team) which means that for now there is no additional support needed.

Best regards,
JB
Your Corona Warn-App Open Source team

Please close this issue if this answered your question. If no action by you is being taken, this issue will be closed in a few hours.
