### ISSUE TITLE
As a linter target a trailing whitespace detector would be useful

### ISSUE THREAD

**Issue by dreh23** [corona-warn-app/cwa-documentation#355]
Right now we have quite some trailing whitespaces:

```
find . -not -path "*node_modules*" -not -path "*.github*" -name \*.md | \   
xargs -n 1 grep -c -H -n -i -o '[[:blank:]]$' | \
tee /dev/tty | cut -d ':' -f2- | paste -sd+ | bc | grep -P 0

./backend-infrastructure-architecture.md:0
./CODE_OF_CONDUCT.md:2
./INSTALL.md:0
./glossary.md:5
./README.md:0
./pruefsteine.md:7
./cwa-risk-assessment.md:0
./CONTRIBUTING.md:1
./ui_screens.md:0
./solution_architecture.md:29
./overview-security.md:40
./translations/pruefsteine.de.md:3
./translations/LANGUAGE_STYLE.de.md:2
./translations/README.de.md:2
./translations/cwa-risk-assessment.de.md:0
./translations/scoping_document.de.md:2
./scoping_document.md:0
```
A Makefile target and a CI run would help avoid these problems..

**Comment by SebastianWolf-SAP** [comment]
The Markdown linter is part of the regular CI job after each commit and it includes the [MD009](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md009) check for trailing whitespaces. Therefore closing this issue and once again thank you for your work on this! :)

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
