### ISSUE TITLE
URL/URI, Ports for firewall whitelists

### ISSUE THREAD

**Issue by gizmo21** [corona-warn-app/cwa-documentation#356]
Is there any documentation about which URLs/Ports a firewall (BLOKADA, PI-hole...)  should not block to use the app?
I found some in sources, but perhaps there are more:

SUBMISSION_CDN_URL=https://submission.coronawarn.app
DOWNLOAD_CDN_URL=https://svc90.main.px.t-online.de
VERIFICATION_CDN_URL=https://verification.coronawarn.app

This could help to locate problems.

**Comment by tkowark** [comment]
We moved this issue since it affects general documentation of the project, not only the android app.

**Comment by GPclips** [comment]
This thread will be closed since the question has been answered by @jakobmoellersap. If there is a need to continue the discussion, it will be reopened.

**Comment by GPclips** [comment]
Hello @gizmo21 ,

I will reopen the issue due to your idea to document the URLs somewhere for the community.
this I will discuss internally.

thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
Answered in https://github.com/corona-warn-app/cwa-documentation/issues/458, specifically https://github.com/corona-warn-app/cwa-documentation/issues/458#issuecomment-722424509

----
Corona-Warn-App Open Source Team
