### ISSUE TITLE
Problem of Exposure Notifications loading keys

### ISSUE THREAD

**Issue by gitbrueck** [corona-warn-app/cwa-documentation#358]
## What is missing

I want to understand the problem of Exposure Notifications to load the keys. See https://github.com/corona-warn-app/cwa-app-android/issues/737 . It's open source, isn't it?

## Why should it be included

Problem loading keys.

## Where should it be included

There should be a state diagram showing the state transitions in the communication of the mobile device with the key server.

**Comment by SebastianWolf-SAP** [comment]
Sorry that it took a little longer to reply. Please follow-up in https://github.com/corona-warn-app/cwa-app-android/issues/737 to get updates about the reasons and especially the solution to the problem. Commits which solve/address the issue will most certainly only be referenced there.

Thank you for your understanding!

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
