### ISSUE TITLE
Two risk encounters without actually leaving the flat much

### ISSUE THREAD

**Issue by AsfalothDE** [corona-warn-app/cwa-documentation#359]
## Avoid duplicates

* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is not already reported in another issue

I'm not sure if this IS a bug, but the question category also doesn't really fit, because it's not a question about the code.

My app currently reports 2 risk encounters, one on Wednesday (1st of July) and one today (3rd of July). The risk level is still shown as low (green), so the encounters must have been short (but longer than 5 minutes obviously) and with enough distance. Still this seems very strange to me as I'm rarely leaving my flat. And if I do, I only go the supermarket (at non crowded hours) or to the bakery.

Additionally Herr Spahn said yesterday that so far only 300 infections have been reported via the app. So it does seem highly unlikely to me that I have met TWO of these people on those rare and short occasions when I do leave my flat.

A friend of mine is outside and amongst people much more than I am and he sees no risk encounters in his app.

Could it be possible that my phone somehow recognized one of the fake keys as risk encounter? Or could it be the same person perhaps living next to me and divided by a wall or a ceiling?
---
Internal Tracking ID: EXPOSUREAPP-1915

**Comment by daimpi** [comment]
Interesting Case. Related: #344 

> Could it be possible that my phone somehow recognized one of the fake keys as risk encounter? 

My guess is: this shouldn't happen. Afaiu this would require some cryptographic collision which should be basically impossible. But I'm not an expert in this topic, so maybe someone more knowledgeable could elaborate on this point.

> Or could it be the same person perhaps living next to me and divided by a wall or a ceiling?

That is possible. Especially Iphones seem to be broadcasting beacons with high tx power (cf. #341) which would probably allow you to pick up signals even at quite some distance/through a wall. That would also be consistent with receiving the “low risk” status, as the distance measured would be too large for the app to consider this a risky encounter.

Another option could o/c be that you just got really unlucky and passed someone during the few trips you made outside your home.

**Comment by AsfalothDE** [comment]
> Another option could o/c be that you just got really unlucky and passed someone during the few trips you made outside your home.

That was my initial thought when I saw the first encounter - but meeting TWO infected people on the street when I leave my flat once a week sounds highly unlikely to me, especially as there are not so many infections reported in the app. That's why I got suspicious that there perhaps is something wrong in the app itself.

**Comment by tens0rfl0w** [comment]
Hey @AsfalothDE,

The two risk encounters can be from the same person/device. As you already mentioned that this is unlikely to happen when rarely leaving your apartment, I would guess that these risk encounters are false positives, so some one living next door has been tested positive and your phone has recorded their keys. 

A scenario where you have been exposed to a „fake“ key attack is nearly impossible as there are under 20,000 keys to compare with right now, so the chance that someone spoofed the right key to trigger a risk encounter on your device is near 0.

**Comment by daimpi** [comment]
Thanks for the explanation @tens0rfl0w 

I have an additional question regarding
> The two risk encounters can be from the same person/device.

I understand that one device can count as multiple encounters as the TEKs change every day. But shouldn't this lead to only one "notification" (of x encounters) on the day after the person uploaded their result? B/c @AsfalothDE is saying that she got two "notifications" on two different days (one on Wednesday and one on Friday).

**Comment by tens0rfl0w** [comment]
Hey @daimpi,

You are totally right! I have totally over read this sentence, I'm sorry.

If @AsfalothDE /s in app counter increased on two different days, then the two exposures can't be from the same person/device, because if you register positive in the app all your keys get uploaded at once and are included in the next data set, so the exposure has been with two different infected people. That is really interesting. At this point guessing the real cause gets a little abstract, but as we are talking non technical right now, a possible cause could be two persons living together in one flat and both got tested positive.

**Comment by daimpi** [comment]
@tens0rfl0w thanks for the explanation 🙂 

> a possible cause could be two persons living together in one flat and both got tested positive.

I agree. This was also the first explanation I was thinking of: if they got their results with some delay between them and uploaded them on different days that could explain this.

**Comment by AsfalothDE** [comment]
> If @AsfalothDE /s in app counter increased on two different days, then the two exposures can't be from the same person/device, because if you register positive in the app all your keys get uploaded at once and are included in the next data set

But what happens if the phone of the first infected person encounters my phone again after the infection was reported in the app? Is the exchanged key then again reported as "infected"? Because in my opinion that should be the case. Imagine the infected person ignores quarantine and continues going outside, their phone will still exchange keys with other phones and all those keys should again be flagged as "infected" keys and cause another risk encounter notification in the app. And it that case my two risk encounters on different days could still be from the same person. Or am I wrong here?

**Comment by daimpi** [comment]
> But what happens if the phone of the first infected person encounters my phone again after the infection was reported in the app? Is the exchanged key then again reported as "infected"?

No it is not. 
See [here](https://github.com/corona-warn-app/cwa-documentation/issues/326) for discussion on that topic. One reason why the TANs are not allowed to validate future keys is that this could invite abuse: you could generate any number of RPIs with it and broadcast them everywhere to generate a large amount of false positive warnings. 

If someone is tested positive and gets into contact with other people afterwards even though they should be self quarantining, the best that could probably be done is to give them another TAN later on.

**Comment by mh-** [comment]
>  could it be the same person perhaps living next to me and divided by a wall or a ceiling?

This is most likely what happened.

**Comment by stefct** [comment]
Couldn't it be two members of the same household who both tested positive, but received (and reported) their test results on two different days? IMHO this is much more likely than two entirely separate incidents.

**Comment by akuckartz** [comment]
@stefct That alternative was mentioned before.

**Comment by stefct** [comment]
> @stefct That alternative was mentioned before.

True - I must have overlooked that, sorry. However, I am still wondering why the discussion in the thread has moved away from this scenario. Unless someone is tested twice, shouldn't it be impossible to be notified on two different days about that same person?

**Comment by MikeJayDee** [comment]
@AsfalothDE Did your app show one encounter first and then two on another day? Or did it jump directly to showing 2 risk encounters (those bring on 1 and 3 July)?

If the latter, this could be from a single person you received the beacon from on 1 and 3 July, and who reported to be infected some days later.

Someone in another flat in your house is a possibility, or someone you met on both days in the store.

As the status is green I wouldn't worry.

However, it would be nice if the app could give as much detail as it receives from the framework (i.e. the risk level and duration of each encounter).

**Comment by AsfalothDE** [comment]
> Did your app show one encounter first and then two on another day? Or did it jump directly to showing 2 risk encounters (those bring on 1 and 3 July)?

I got the first risk encounter on 1st of July and then one day nothing and the next day the second one (3rd of July).

It has to be the house then, because I just can't imagine meeting 2 out of 300 people when I go once per week to the bakery. I should play the lottery then... I would also have liked to see the actual days those encounters happened - just to be able to figure out how where it happened.

**Comment by stefct** [comment]
> It has to be the house then, because I just can't imagine meeting 2 out of 300 people when I go once per week to the bakery.

I don't think the house is a convincing explanation. If you were living door to door with one infected person, the app might have notified you about a larger number of encounters - but you would have still received all these notifications on the same day (the day they uploaded their test result). There wouldn't have been a second notification two days later.

Do you really think it is unlikely that you met a couple at the bakery, for example, where both members were infected? Or a parent and a child? Two close friends? I believe that among the 300 people, these kinds of infection chains among close contacts must have occurred frequently.

**Comment by stefct** [comment]
Addendum: This is assuming that the app won't notify you about the exact date of each risk encounter. Mine clearly doesn't. It displays one risk encounter, too (also with a low risk level), but without indicating a date. To my understanding, in case of increased risk, it will tell you when the last risk encounter happened (but not the exact dates of earlier additional risk encounters).

**Comment by MikeJayDee** [comment]
If you have it, what is your Operating System showing? On Android (but not completely rolled out, so you may not have the menu): Settings -> Google -> COVID-19 exposure notification -> Check for possible encounter -> then click through the list until you find the relevant encounter.

**Comment by stefct** [comment]
On iOS, I wasn't able to find any such data. The only information available is the data described here: https://github.com/austrianredcross/stopp-corona-ios/issues/107#issuecomment-654279114 

Since I was first notified about my 1 risk encounter, the "Anzahl der abgeglichenen Schlüssel" is 1 once a day (otherwise 0). However, the app keeps telling me that I had exactly 1 risk encounter - the number does not increase. There is no information about when that risk encounter might have occurred.

**Comment by GPclips** [comment]
Hello @AsfalothDE and community,

thanks for driving this discussion. From what I understand is that you missing the information that one can see in the app, when which risk encounter has occurred, as @stefct is saying in his last post: https://github.com/corona-warn-app/cwa-documentation/issues/359#issuecomment-655789949.
I will forward this to our dev team.

To add the FAQ article to this discussion: here we describe how the encounters are tracked: https://www.coronawarn.app/en/faq/#encounter_but_green

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by AsfalothDE** [comment]
@GPclips Thank you for picking this up. Yes, I would really like to see the date on which the "harmless" encounter took place to be able to assess the risk for myself. Since reporting the above I had two more low risk encounters (and I'm still leaving the flat only to go to the bakery or to the supermarket perhaps once per week). Both encounters appeared within three days and were vanished two (the first) and one (the second) day after they showed up in the app. So I know when these encounters actually happened (two weeks before they vanished from the app). On these dates I definitely didn't leave my flat at all. So it's impossible I met those people on the street. Also I had another person with me the whole day the encounter happened and the app from them didn't report a risk encounter at all. So I'm still very confused about my four low risk encounters and I'm not sure if I even can trust the app to work as it should. :( I have to add though that I had the buggy iOS 13.7 installed on my phone when the last two risk encounters were reported, so they could be invalid anyway.

**Comment by MikeMcC399** [comment]
https://www.coronawarn.app/en/blog/2020-12-17-risk-calculation-exposure-notification-framework-2-0/ says:

**Less encounters with a low risk**
With the introduction of Corona-Warn-App version 1.9, a new version of the Exposure Notification Framework (ENF) from Apple/Google is used, version 2.0. The data from this interface is used as the basis for calculating the individual risk.

Previously, the number of non-critical encounters displayed in the app could not be filtered. Up to version 1.7.1, very short encounters with users who later tested positive for COVID-19 were also counted and displayed in the app. However, due to the stored criteria for the risk calculation, these were only displayed as low-risk encounters.

In simplified terms: Under Exposure Notification Version 2.0, the operating system also logs encounters with a risk lower than "low risk" (green). **However, since these encounters are not relevant from the current epidemiological perspective, the Corona-Warn-App filters them out.**

---

So perhaps this issue can now be closed? Version 1.9 was rolled out starting Dec 17, 2020 and Version 1.10 is currently in rollout.

**Comment by dsarkar** [comment]
@MikeMcC399 Many thanks for your latest post. As suggested this issue will be closed now.

@AsfalothDE, @stefct, @daimpi, @tens0rfl0w, @MikeJayDee, @akuckartz, Thanks to all of you for contributing here. Best, DS


---
Corona-Warn-App Open Source Team
