### ISSUE TITLE
1 Exposure on App - when does the counting begin? 

### ISSUE THREAD

**Issue by TeRe20200** [corona-warn-app/cwa-documentation#363]
Not sure if this is the right place to ask, but I have a question concerning the Coronaapp in Germany. 

Since Saturday I have _one exposure_ that is still rated as _“low risk” (green mode)_ which I understand was my phone being not too near and not too long next to someone who was tested positive. 

Let’s imagine I met this person on July 1st. That person got themselves tested on 5th of July, got the result on July 7th and checked in on the App as “positive” the same day. Does the App show me the “1 exposure status” for 14 days after the person checked in positive on the App (July 7th) or does the App count from the day on I was near that person (July 1st) -  meaning the status ends for me on July 15th?

Let’s exaggerate this so you guys understand my question:
I met person A on July 1st, the person feels sick 8 days after, gets the positive result on July 12. That means I get the status “1 exposure” for only 3 days, right?

**Comment by jensjensenjens** [comment]
As far as I've understood the documentation only the temporary exposure keys of the last 14 days are stored and analysed by the app. Hence, the status should end on July 15th in your first example, if July 1st was the only exposure to this person.

**Comment by TeRe20200** [comment]
> As far as I've understood the documentation only the temporary exposure keys of the last 14 days are stored and analysed by the app. Hence, the status should end on July 15th in your first example, if July 1st was the only exposure to this person.

Thank you for your reply, that is actually what I thought! 

But that also means if you get the “1 exposure” notification on July 15th and it’s gone three days after, that I can name the exact date I saw the “positive” person (in this example 4th). Is that right?

**Comment by jensjensenjens** [comment]
As far as I understood the App would say which day you had the encounter when warning the first time:

https://github.com/corona-warn-app/cwa-app-android/blob/b2d00d076d94773b929e8125f4828f2f31df7ed0/Corona-Warn-App/src/main/res/values-de/strings.xml#L309

**Comment by TeRe20200** [comment]
> As far as I understood the App would say which day you had the encounter when warning:
> 
> 
> 
> https://github.com/corona-warn-app/cwa-app-android/blob/b2d00d076d94773b929e8125f4828f2f31df7ed0/Corona-Warn-App/src/main/res/values-de/strings.xml#L309
> 
> 
> 
> 

Ok ok, this is WAY too complicated for me 😕
Is there a way I can check on that inside the App or maybe inside the Exposure-Checks. 

The only thing I can see is that since saturday I have one matched count **but where can I check when that encounter with that matched key was?**

**Comment by mh-** [comment]
> The only thing I can see is that since saturday I have one matched count **but where can I check when that encounter with that matched key was?**

With the current app, you can't.
There's an enhancement request that would cover this: https://github.com/corona-warn-app/cwa-wishlist/issues/100

**Comment by SebastianWolf-SAP** [comment]
Dear @TeRe20200,

thanks to @mh- and @jensjensenjens your question has already been answered. Please follow up in https://github.com/corona-warn-app/cwa-wishlist/issues/100 (vote, comment...) for that feature request.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
