### ISSUE TITLE
Submit laboratory results to corona-warn-app - How to?

### ISSUE THREAD

**Issue by PaulGraf-GECKOmbH** [corona-warn-app/cwa-documentation#364]
Hello everyone!
First of all, congrats to such a good piece of work you did here!
We are currently working on a platform for a bio-tech-company that does Covid-19 testing at airports and such and they of course want to be able to put QR codes on their result PDFs so that customers can easily register their positive results in your app. 
Now, we got that we will send you a SHA256 hash as ID and a result enum (1..3) and then we put the same hash on our result PDFs.

What we do NOT know is: 
1. what is the productive API address to "talk" to? 
2. do you have a test-system, or how can we test our implementation?

It would be really great to get some answers to this rather soon, as you can imaging ;) 
You can also email me, or I can call the support or anything. Please just point me in the direction I have to run to get the answers. 

THANK YOU!
All the best,
Paul

**Comment by SebastianWolf-SAP** [comment]
Dear Paul,

please send us an e-mail to corona-warn-app.opensource@sap.com with your inquiry. There are dedicated contact addresses for testing laboratories which we would like to forward your request to. :)

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
