### ISSUE TITLE
Will a VPN affect the correct detection of exposure?

### ISSUE THREAD

**Issue by christhomas** [corona-warn-app/cwa-documentation#366]
I use a VPN and this means I'm technically in Frankfurt, yet I'm physically in Berlin.

I'm getting, roughly every two weeks, a notification that my region might not be correct and I assume this is because the app is detecting I'm connected through a different location than my physical location. I'm being told to confirm in the exposure settings the correct application I should be using. I can't remember the exact wording, but I assume you guys know what notification I'm talking about? I'm using iOS.

Will this affect the detection of exposure in any way by making the application send incorrect assumptions about my location to the backend server and give me a false diagnosis?

I'm sorry but I don't have the notification anymore, I didn't have the presence of mind to screenshot it either, so I can maybe do that the next time if you're unsure what I'm referring to.

Can anybody help with that please? Thanks!

**Comment by tkowark** [comment]
Hi @christhomas ,

a VPN should not affect the correct detection of exposure. No information about your location within Germany is transferred to the backend server and you will always get the full set of diagnosis keys for Germany to test your local contact events regarding their potential risk.

The warning you get is specific to Apple devices and should be gone with iOS 13.6: https://www.coronawarn.app/de/faq/#iphone_region_change

Best regards,
TK
Corona-Warn-App Open Source Team

**Comment by christhomas** [comment]
Thanks a lot for your quick response!
