### ISSUE TITLE
Fix inconsistent risk parameter levels: Either 0-8 or 1-8

### ISSUE THREAD

**Issue by corneliusroemer** [corona-warn-app/cwa-documentation#368]
This was created from PR #345 which doesn't seem to have an issue attached to it.

> Within the chapter [Risk Score Calculation](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#risk-score-calculation) the range for `transmission risk factor` is from 0-8, but in the beginning of chapter [Backend](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#back-end) it ranges from 1-8.
> This PR will update the range to 0-8 at the beginning of the backend-chapter.

**Comment by tkowark** [comment]
Thanks for providing the issue for the PR. We hopefully answered the underlying question with https://github.com/corona-warn-app/cwa-documentation/pull/345#issuecomment-658807772 and therefore also close this issue.
