### ISSUE TITLE
Enhancement/Idea: Indicate Tracing Data not being Deleted on Factory Reset

### ISSUE THREAD

**Issue by eaglerainbow** [corona-warn-app/cwa-documentation#37]
* Documentation File: https://github.com/corona-warn-app/cwa-documentation/blame/cb991f6d5d103130a448ae728919b0109ef0bd06/translations/scoping_document.de.md#L134
* Line / Paragraph: line 134, E03.02
* Improvement idea:

I am always unsure myself in similar situations: What portion of data is deleted, if I trigger the "Reset" (you call it "Delivery Default") button?

The documentation already clearly states that the tracking data should not be deleted in such an event. 
In that case, I suggest to also explicitly state in an (own item of the) acceptance criteria that the app user will be informed about the limited scope of deletion upfront. I.e. I could think of the the safety question shown before to read something like 

>  Do you really want to reset all configuration settings to defaults (Note: your tracking data will not be affected)?

**Comment by kheinz57** [comment]
I am assuming you are not deleting the daily tracing key. If that is the case it would be the best to do so. Although passing a phone from one person to the next will not be supported. I just want to mention this, but I personally believe it is better to not delete

**Comment by tkowark** [comment]
Thanks for your suggestion. 

As currently implemented, the App clearly states on the reset screen that the contact data needs to be separately deleted via the system preferences. I hope that suffices.

Best regards,
TK
Corona-Warn-App Open Source Team
