### ISSUE TITLE
iOS 14 Support

### ISSUE THREAD

**Issue by egalgitarrist2** [corona-warn-app/cwa-documentation#370]
On current iOS 14 Public Beta (18A5319i) the App is just showing a black screen. Furthermore in Settings->Privacy->Health no active App is recognised.

**Comment by SebastianWolf-SAP** [comment]
Please see our FAQ and the iOS Beta release notes. The Exposure Notification Framework is not yet available in iOS 14 Betas: https://www.coronawarn.app/en/faq/#ios_14_beta

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
