### ISSUE TITLE
Grammar errors in cwa-risk-assessment.md

### ISSUE THREAD

**Issue by corneliusroemer** [corona-warn-app/cwa-documentation#372]
Issue that is resolved by PR #371 

Two commits to merge:
The first one is an obvious grammar error, an "and" that shouldn't be there.
The second replaces incorrect usage of "last" with the correct "latest"/"most recent". This is a typical false friend error made by Germans. More info for example here: https://www.italki.com/question/385224?hl=de
The same error is probably widespread elsewhere in the documentation.

**Comment by SebastianWolf-SAP** [comment]
Thank you very much, @corneliusroemer! PR was merged!

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
