### ISSUE TITLE
How to handle the case when you're healthy again? (from Zeit article)

### ISSUE THREAD

**Issue by rugk** [corona-warn-app/cwa-documentation#377]
## Your Question

* Documentation File: https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#upload-schedule-for-diagnosis-keys
* Line / Paragraph: figure 5
* Question: **["Where is the 'I am healthy again' button?"](https://www.zeit.de/digital/mobil/2020-07/corona-warn-app-positives-ergebnis-infiziert-reaktion/komplettansicht)** (German; "Wo ist nur der "Ich bin wieder gesund"-Knopf?") is a title from a Zeit article from Lisa Hegemann yesterday. Read the full one for more information.

Related to https://github.com/corona-warn-app/cwa-documentation/issues/326, but this is only about parts of these issues and drifts off-topic.

I would summarize the questions like these:
1. Why is there no "I am healthy again" button? RKI recommends to delete the app again… However, _if_ COVID-19 infected persons are not (forever) immune, they actually very much would like to use the app again afterwards. There is no use case here that handles/documents this.
2. The app seems to assume everyone adheres to the quarantine. Hegemann criticizes that as a naive approach. The problem treated as "infected keys". As such, when you go out for some small things or do not adhere to the quarantine, the app will not warn others.
3. The hotline says keys are deleted after 14 days. So after this time, people should be able to use the app again? Still seems to need reinstalling/resetting though.(?)
4. After the user reset the app, she says it showed error messages for three days.

-> Generally, as it criticizes, what you should do in such a case, should be documented in the FAQ [on the website](https://github.com/corona-warn-app/cwa-website/). (Maybe move that issue there, if you feel it's more appropriate.)

**Comment by SebastianWolf-SAP** [comment]
Dear @rugk,

thanks for this idea. However, we have already received this proposal in our cwa-wishlist repository: https://github.com/corona-warn-app/cwa-wishlist/issues/115 Please follow-up there and vote for it!

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
