### ISSUE TITLE
How to detect version of Exposure Notifications API?

### ISSUE THREAD

**Issue by gitbrueck** [corona-warn-app/cwa-documentation#378]
## Your Question

* Documentation File:
https://developers.google.com/android/exposure-notifications/release-notes
* Line / Paragraph:
Version 1.5 of the Exposure Notifications API started rolling out on 2020-07-09. There are no behavior changes in existing functionality, but we have introduced bug fixes and new features that aim to provide developers with more data and make the API easier to test and debug. ...
* Question:
Which version of this API is on my device?
It shows "Version: 202414000" on "Einstellungen"->"Google"->"Benachrichtigungen zu möglicher Begegnung mit COVID-19-Infizierten"

**Comment by corneliusroemer** [comment]
Maybe try asking here - should affect all projects using GAEN.
https://github.com/google/exposure-notifications-android/issues

**Comment by SebastianWolf-SAP** [comment]
Please reach out to Google to get this information, especially about the detailed version number. From the release notes it seems that you can determine if you are running the newest version if you get the System user experience changes as outlined on https://developers.google.com/android/exposure-notifications/release-notes#ux-changes

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by SebastianWolf-SAP** [comment]
Small update as we directly reached out to Google. :)

If you want to know if you have received the latest update, please open the Exposure Notification settings page (Settings -> Google -> COVID-19 Exposure Notifications) and check the mentioned version number. If it starts with '15', you already have the newest version. If not, you still need to wait a bit. So '202414000' as mentioned by @gitbrueck still doesn't contain the newest version.

Mit freundlichen Grüßen/Best regards,
SW
Corona Warn-App Open Source Team

**Comment by gitbrueck** [comment]
> 
> 
> Small update as we directly reached out to Google. :)
> 
> If you want to know if you have received the latest update, please open the Exposure Notification settings page (Settings -> Google -> COVID-19 Exposure Notifications) and check the mentioned version number. If it starts with '15', you already have the newest version. If not, you still need to wait a bit. So '202414000' as mentioned by @gitbrueck still doesn't contain the newest version.
> 
> Mit freundlichen Grüßen/Best regards,
> SW
> Corona Warn-App Open Source Team

Big thanks to Google and Apple. I admire the power of bringing such a perfect API to billions of smartphones.

Best regards,
gitbrueck
