### ISSUE TITLE
Fehlende Worst-Case-Betrachtung der Komplexität der Hintergrundabfragen

### ISSUE THREAD

**Issue by HolgerMayer** [corona-warn-app/cwa-documentation#38]
In Phase Anwendung 1) Hintergrund heißt es:

>  In regelmäßigen Abständen holt sich die App vom Server eine Liste der Pseudo-IDs der sich freiwillig infiziert gemeldeten Nutzer und vergleicht diese mit den gespeicherten Pseudo-IDs im Gerät, um einen möglichen Kontakt zu ermitteln.

Sollte das Infektionsgeschehen trotz App wieder stark anwachsen und die App wird stark genutzt, dann ergibt sich ein hoher Traffic.

Wenn

 n die Anzahl der User ist 
m die Anzahl der neu infizierten User

Dann überträgt man regelmässig n * m  Datensätze. Ist m klein, dann wird über einen längeren Zeitraum die Last verteilt. Steigt aber die Infektionsrate an, dann wird sehr viel Traffic in kurzer Zeit erzeugt.

Im Endeffekt würde bei 100%iger Infektionsrate am Ende ein Gesamttraffic von n^2 entstehen. Nicht gut, wenn die App ein Erfolg wird, es aber keinen Impfstoff gibt.

**Comment by C0FFEEC0FFEE** [comment]
Based on the [Exposure_Notification_-_Bluetooth_Specification](https://blog.google/documents/62/Exposure_Notification_-_Bluetooth_Specification_v1.1.pdf), the Rolling proximity identifiers are 16 bytes in length.

So this worst case would be about 80 MByte of data for n=m=80,000,000.

**Comment by TomTeeJay** [comment]
If the BT payload consists of randomly diced 16 Bytes then tracing for approx 80.000.000 (8 Bytes) simply can't be done without enough entropy to maintain anonymity or to prevent massive false positive through same IDs.

**Comment by mynchau** [comment]
Please wait until the architecture docs are released. You will find more info in those docs. For further contributions please be kindly reminded to use the English language. Thanks.

**Comment by HolgerMayer** [comment]
> Based on the [Exposure_Notification_-_Bluetooth_Specification](https://blog.google/documents/62/Exposure_Notification_-_Bluetooth_Specification_v1.1.pdf), the Rolling proximity identifiers are 16 bytes in length.
> 
> So this worst case would be about 10^17 Byte of data for n=m=80,000,000.
> 
> But if this worst case happens we don‘t need thee app anymore. Also: This case will not happen.

Will this app be used in the whole EU? Or even more countries?
Does this app assume a data plan without data transfer restrictions?
