### ISSUE TITLE
Feature Request: Report being tested negative after being tested positive

### ISSUE THREAD

**Issue by bloodmandarin** [corona-warn-app/cwa-documentation#381]
In this [Zeit-article](https://www.zeit.de/digital/mobil/2020-07/corona-warn-app-positives-ergebnis-infiziert-reaktion/seite-2), an infected patient reports that it was a) quite difficult to reach the hotline (see related issue #313) and b) impossible to feed back to the app that one was healthy again after being tested positive. Given that there are a lot of consequences to the ecosystem if one is infected, there should be a way to indicate being recovered/"genesen".

**Comment by tkowark** [comment]
Thanks for your proposal. This is already being tracked and discussed here: https://github.com/corona-warn-app/cwa-wishlist/issues/115
