### ISSUE TITLE
License for use of the corona-warn-app Icon for other purposes like T-Shirts prints

### ISSUE THREAD

**Issue by kheinz57** [corona-warn-app/cwa-documentation#382]
I would like to help spreading the app and therefore print a T-Shirt (for myself and probalby friends only). 

- Am I allowed to use the Icon for that purpose?
- If yes: is there a higher resolution image available somewhere as well?
- Maybe it would help spreading the app to make such a design available for T-Shirt print services

Heinz

**Comment by SebastianWolf-SAP** [comment]
Dear @kheinz57,

unfortunately, the icon can't be used without the explicit approval by the German Federal Government as it's a registered trademark. We also mention that in https://github.com/corona-warn-app/cwa-documentation#licensing

Please reach out to the German Federal Press Office with your ideas. English: https://www.bundesregierung.de/breg-en/service/contact?view= and German: https://www.bundesregierung.de/breg-de/service/kontakt?view=

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by kheinz57** [comment]
Thank you for the feedback. I have forwarded the question to the german federal press office. Will comment here if I get any feedback

**Comment by tkowark** [comment]
Dear @kheinz57 , you can also check out the package offered here:
https://styleguide.bundesregierung.de/sg-de/basiselemente/programmmarken/corona-warn-app-baukasten/corona-warn-app-der-baukasten-fuer-unterstuetzerinnen-und-unterstuetzer-1756534
