### ISSUE TITLE
Transmission risk level paper correction

### ISSUE THREAD

**Issue by daimpi** [corona-warn-app/cwa-documentation#384]
## Where to find the issue
This issue concerns the “Epidemiological Motivation of the Transmission Risk Level” (TRL) document here: https://github.com/corona-warn-app/cwa-documentation/blob/master/transmission_risk.pdf. In particular Section 3.1 “Infectiousness Profile due to Viral Shedding” which seems to be largly based on He et al. Nat. Med. 2020.

## Describe the issue
There has been a major correction to He et al. which yields a significantly different infectivity profile:
- [author thread](https://twitter.com/Peter_Ashcroft/status/1283305510993891328) 
- [arXiv paper](https://arxiv.org/abs/2007.06602)

## Suggested change
Coordinate with the RKI to adjust the TRL documentation and implementation as necessary in light of the correction.

**Comment by SebastianWolf-SAP** [comment]
Thanks for the information. We will reach out to RKI to get feedback in that case.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by hoehleatsu** [comment]
See also https://github.com/ehylau/COVID-19/issues/2

**Comment by hoehleatsu** [comment]
Correction of the He et al. (2020) paper now posted: https://www.nature.com/articles/s41591-020-1016-z

**Comment by hoehleatsu** [comment]
Could the CWA maintainers please provide us with some information on what type of deadlines they have in their SOP when answering such issues involving the RKI? This would help the community adjust their expectations on either how large a workload the maintainers are facing or how the transparancy statement of the App development is to be understood.

From https://www.coronawarn.app/en/:

> The app is based on technologies with a decentralized approach and notifies users if they have been exposed to SARS-CoV-2. Transparency is key to both protect the app's end-users and to encourage adoption.

As suggested in the PR #418, there are different ways to address the issue including "doing nothing", but in the spirit of transparency some kind of answer can be expected after 56 days...

**Comment by daimpi** [comment]
@hoehleatsu if you want you can join our [community Slack](https://github.com/corona-warn-app/cwa-documentation/issues/379) (we're mainly in the #cwa channel) 🙂.

**Comment by GPclips** [comment]
Hello @daimpi,

to keep you in the loop, I have been told, that the document adjustment has been done.
Currently, we are reviewing the document and will inform you as soon as possible, when the updated document is available.

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by hoehleatsu** [comment]
Finally fixed as part of f03f4cd which is now part of CWA v1.5.0. released today (2020-10-19). 90 days after the issue was opened.

**Comment by daimpi** [comment]
@hoehleatsu great, thanks for the info I'll close this issue then 🙂.
