### ISSUE TITLE
Wording of RKI

### ISSUE THREAD

**Issue by gitbrueck** [corona-warn-app/cwa-documentation#386]
## Where to find the issue

Google Play Store

## Describe the issue

The wording is different:
I agree with this: "Leider wurde das Schnittstellenproblem, das zur fehlenden Risikoermittlung führt, von Google noch nicht behoben."
I disagree with this: "(39508) in Zusammenhang mit der fehlenden Risikoermittlung wird aktuell gemeinsam mit Google behoben."

## Suggested change

The key role of Google must become totally clear to the user.

**Comment by SebastianWolf-SAP** [comment]
Well, as Corona-Warn-App can also improve to mitigate the error, see e.g. in https://github.com/corona-warn-app/cwa-app-android/issues/816#issuecomment-659988221, we will most certainly keep the wording that says that it a joint effort. In case you have proposals how to improve the wording, please follow-up in https://github.com/corona-warn-app/cwa-app-android/issues/816 and https://github.com/corona-warn-app/cwa-app-android/issues/774. We will therefore close this issue.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
