### ISSUE TITLE
Notification: Risikobegegnung

### ISSUE THREAD

**Issue by bgunro** [corona-warn-app/cwa-documentation#388]
The Notification "Risiko Begegnung" in combination with the green screen is misleading.
This should mean according to the hotline an noncritical contact with an infected person.
According to the FAQs Risikobegegning means a critical contact.
Here should be used another wording like. " 1 Unkritischer Kontakt erfasst" resp. XX unkritische Kontakte erfasst" in contrast to Risikobegegnung.

**Comment by SebastianWolf-SAP** [comment]
Improvements to this status display are already in the backlog and will be addressed soon. Please follow-up in https://github.com/corona-warn-app/cwa-backlog/issues/23.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
