### ISSUE TITLE
Active Days stuck at x/14 days 

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#389]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

Since more than 2 weeks, the screen shows "Risiko-Ermittlung war für 12 der letzten 14 Tage aktiv". 
That's really implossible, because I've installed the App on it's launch day and never deactivated "Risiko-Ermittlung" 
At night I activate flightmode & turn off Bluetooth.

![IMG_8188](https://user-images.githubusercontent.com/67682506/88410488-bf09b000-cdd6-11ea-870f-cb5f95f18586.PNG)

## Expected behaviour

The screen should show: "Rikio-Ermittlung dauerhaft aktiv".

## Steps to reproduce the issue

--

## Technical details

- iOS Version: 13.6
- Device: iPhone XR
- CWA-Version: 1.1.1 (3)

## Possible Fix

No idea. Neither the update to iOS 13.6 nor the updates form the App fixed the problem... 

## Additional context

I'm not sure but I think the issue first occured under iOS 13.6 Public Beta 3. But now I'm on the offical version...

---
Internal Tracking ID: EXPOSUREAPP-1909

**Comment by SebastianWolf-SAP** [comment]
Transferred this issue to cwa-documentation as it affects both operating systems

**Comment by daimpi** [comment]
I just heard from someone that their iOS App (1.1.2) is stuck at 10 of 14 days: https://twitter.com/JakobFekete/status/1289547379255808000

They [told me](https://twitter.com/JakobFekete/status/1289594933012312064) that they have their device on "airplane mode" from time to time.
Is "airplane mode" time subtracted from the 14 days under iOS (this seems not to be the case for [Android](https://github.com/corona-warn-app/cwa-app-android/issues/920))? That could explain, why it counted up to 10, but got stuck from then on.

**Comment by tkowark** [comment]
Yes, airplane mode on iOS deactivates Bluetooth, and accordingly the ENF. This time is deducted from the "active days".

**Comment by Ein-Tim** [comment]
2 days ago my active days went down to 11,then yesterday went back up to 12 and today they went back to 11...

**Comment by Ein-Tim** [comment]
Yeah!
It works now! 
@danidoedel What about you?

**Comment by danidoedel** [comment]
Yep I can confirm, it seems to work as expected. Even if it's hard to figure out what the expected behavior is 😁

**Comment by Ein-Tim** [comment]
Okay, I will close this now.

**Comment by Ein-Tim** [comment]
Closed this because for us two the issue has been solved.

**Comment by vaubaehn** [comment]
Don't read - this is soley a test together with @Ein-Tim .

**Comment by vaubaehn** [comment]
Test finished. Thanks for paying no attention. Good night.
