### ISSUE TITLE
Will ein App Nutzer diese Dinge wirklich?

### ISSUE THREAD

**Issue by schauder** [corona-warn-app/cwa-documentation#39]
In verschiedenen User Stories werden Bedürfnisse eines App Users unterstellt. Zum Beispiel in den folgenden beiden.

E01.04 | Als App-Nutzer möchte ich bei erstmaliger Nutzung der Applikation gefragt werden, ob die Applikation auf die Bluetooth-Funktion des Smartphones zugreifen darf, damit ich die mobiltelefonseitige Nutzung der Applikation kontrollieren kann.
-- | -- 
E01.05 | Als App-Nutzer möchte ich bei erstmaliger Nutzung der Applikation gefragt werden, ob die Applikation mir Benachrichtigungen schicken darf, damit in verschiedenen Situationen Push-Notifications ausgespielt werden können.

Ich als potentieller Benutzer bin mir ziemlich sicher, dass ich nicht gefragt werden will. 
Diese ständigen Popups und Abfragen sind eigentlich eher nervig.

Ich denke die Wünsche oder/die Akteure hier sind andere, z.B:
* Als rechtlich Verantwortlicher möchte ich das Gesetzte, wie z.B. DSGVO eingehalten werden, damit keine Kosten durch Beschwerden und Klagen entstehen.
* Als App-Nutzer möchte ich nicht, dass die App Kommunikationsmechanismen meines Handies nutzt, ohne dass ich darüber und über die Gründe dafür informiert bin, damit ich dies sinnvoll und fundiert kontrollieren kann.

Eventuell macht es Sinn, die User Stories in diesem Sinne zu reviewen. Bisher lesen die sich mehr wie klassische Anforderungsspezifikationen die sich als User Stories tarnen ;-)
Das kann natürlich auch gewollt sein, ich kenne euren Entwicklungsprozess ja nicht.

**Comment by s-martin** [comment]
Ich als Nutzer möchte stattdessen gefragt werden 😉

User Stories sind nicht allgemein gültig für alle und jeden, das ist klar.

Unter'm Strich macht es aber wenig Unterschied für die Funktion der App, ob die User Stories so formuliert sind wie im Original oder wie von dir.

**Comment by schauder** [comment]
> Ich als Nutzer möchte stattdessen gefragt werden 😉
Also wegen dir bekomme ich die ganzen Cookie und Notification popups auf allen Webseiten? 
Na schönen Dank auch ;-)

> Unter'm Strich macht es aber wenig Unterschied für die Funktion der App, ob die User Stories so formuliert sind wie im Original oder wie von dir.

Das ist in meiner Erfahrung anders und nach meinem Verständnis der Grund warum die Idee von User Stories überhaupt entwickelt wurden: Verstehen, was das eigentliche Problem ist das gelöst werden soll und welche Ziele damit verfolgt werden, damit in anschließenden Gesprächen Lösungen gefunden werden können ohne den Entscheidungsrahmen unnötig einzuschränken.

Da mit den Cookies ist ein schönes Beispiel: Wenn der User ein Cookie popup möchte, sollte man es natürlich bauen. Und da er es so toll finden mit 500 Cookies die einzeln deaktivieren muss.
Wenn es aber um die Einhaltung der DSGVO geht ist ein viel besserer Weg auf Cookies möglichst zu verzichten.

Aber wie gesagt: Euer Entwicklungsprozess. Macht den Issue ruhig zu, wenn ihr das anders seht.

**Comment by s-martin** [comment]
> Aber wie gesagt: Euer Entwicklungsprozess. Macht den Issue ruhig zu, wenn ihr das anders seht.

Disclaimer: Arbeite weder für SAP noch Telekom.

**Comment by schauder** [comment]
Verdammt, habe ich den zu gemacht? Dicke Finger. Sollte dann schon das Team machen.

**Comment by simontb** [comment]
Da sowohl Android als auch iOS Berechtigungen zur Laufzeit abfragen, möchte ich das als User wirklich. Oder möchtet ihr, dass jede installierte App die Tracing Function beschrieben in E01.04 ohne Einwilligung des Nutzers benutzen kann?

Bei E01.05 bin ich mir nicht mehr so sicher. Also bei Android muss ich einer App nicht explizit die Berechtigung geben mir Notifications zu schicken, bei iOS ist das, wenn ich mich richtig erinnere, jedoch so.

**Comment by schauder** [comment]
> Oder möchtet ihr, dass jede installierte App die Tracing Function beschrieben in E01.04 ohne Einwilligung des Nutzers benutzen kann?

Nein, das möchte ich nicht. 
Aber ich habe auch kein Interesse an der Frage selbst. Sonst würde ich mir ja eine Applikation wünschen, die erstmal ohne jeden weiteren Sinn solche Fragen stellt.

Genau das ist der feine Unterschied: ich möchte nicht das die App Dinge nutzt ohne dass ich das weiß, die Gründe dahinter verstehe und es unterbinden kann wenn es mir nicht gefällt.
Das ist das Problem das gelöst werden muss.

Das Abzufragen ist eine mögliche Lösung. Es gibt potentiell andere (wenn auch vielleicht nicht in dem konkreten Beispiel). Daher sollten User Stories das Problem beschreiben und nicht die Lösung.

**Comment by simontb** [comment]
> Das Abzufragen ist eine mögliche Lösung. Es gibt potentiell andere (wenn auch vielleicht nicht in dem konkreten Beispiel). Daher sollten User Stories das Problem beschreiben und nicht die Lösung.

Bei meinem Verständnis der zugrunde liegenden Plattformen Android und iOS ist das die einzig mögliche Lösung für App Entwickler (sollte es andere geben, wäre ich daran interessiert diese zu erfahren).

Du hast Recht: Eventuell ist die Formulierung nicht ideal, jedoch sollte es aus meiner Sicht zum richtigen Ergebnis führen (die App kann Kontakte tracen, jedoch nur mit Zustimmung des Nutzers).

**Comment by SebastianWolf-SAP** [comment]
Danke für die durchaus interessante Diskussion, was ein Nutzer oder eine Nutzerin am Ende wirklich will. :) Am Ende muss man sich bei den User Stories aber eben auf eine gewisse Formulierung einigen... 

So oder so: Entscheidend ist, was am Ende bei rumkommt und da besteht offensichtlich wenig Dissenz: Dass die Punkte abgedeckt werden, die der OP @schauder schon angesprochen hat. Ich würde deshalb das Issue schließen.
