### ISSUE TITLE
Telefonnummer in Datenschutzerklärung

### ISSUE THREAD

**Issue by bennyrolle** [corona-warn-app/cwa-documentation#390]
Die Datenschutzerklärung enthält in Abschnitt 6c eine Telefonnummer für das TeleTAN-Verfahren: +49 (0)800 7540002
Bei dieser Telefonnummer muss die eingeklammerte Null entfernt werden.

Zumindest auf Android ist diese Telefonnummer anklickbar und die Telefonieren-App macht aus der Telefonnummer +4908007540002 mit einer Null zu viel. Ob das Problem zusätzlich auch bei iOS auftritt, muss geprüft werden.

Ich bin mir unsicher, von welcher Stelle die Android-App die Datenschutzerklärung lädt. In jedem Fall sollte in der App nach dem Beheben des Fehlers geprüft werden, ob die Rufnummer nach Anklicken korrekt an die Telefonieren-App übertragen wird.

---
Internal Tracking ID: EXPOSUREAPP-1464

**Comment by SebastianWolf-SAP** [comment]
Phone number is not clickable on iOS -> should be done as well with the correct encoding.

**Comment by GPclips** [comment]
Hello @bennyrolle,

I just checked the error on an iPhone, there it works as expected.
I will doublecheck with the dev team if it has been fixed already.
We will keep you in the loop.

TCorona-Warn-App Open Source Teamhank you,
LMM

Corona-Warn-App Open Source Team

**Comment by marcussc** [comment]
@GPclips @bennyrolle Ich kann den Fehler in der aktuell veröffentlichten Version (1.3.2) nicht mehr nachstellen. 

I can't reproduce this bug in the currently released version 1.3.2 anymore.

**Comment by heinezen** [comment]
Not reproducible anymore from our side, so we will close this issue.

----
Corona-Warn-App Open Source Team
