### ISSUE TITLE
Missing Information When Riskikobegegnung dissapears again

### ISSUE THREAD

**Issue by uklbaer** [corona-warn-app/cwa-documentation#391]
For me as a User the following case is Not clear and i have Not found Any explanation 

I had a Risiko Begegnung appearing on saturday but on monday it dissapeared again 

What is the criteria for it to dissapear

Is ist 2 weeks? So was it the case That the Meeting Happened 2 Weeks Back on monday and the Other Person Added His or her positiv Test on Friday so That i got the Information on saturday 

And the Risk dissapeared on Monday as the Meeting was 2 Weeks back

This is my assumption But ist is Not stated somewhere in the doc 

So for Users such Situation is Not clear and leads to confusion

**Comment by SebastianWolf-SAP** [comment]
Usually, risk encounters with low risk (you obviously saw these ones) should disappear after two weeks as the risk encounters are anyway only persisted for two weeks. We have seen a missing reset on the home screen for these low risk encounters in https://github.com/corona-warn-app/cwa-app-android/issues/911 which our dev colleagues are working on. Additional documentation about these risk encounters is already in the backlog, please see and follow-up in https://github.com/corona-warn-app/cwa-backlog/issues/23 for details.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by daimpi** [comment]
@uklbaer Interesting: Are you under iOS? B/c I just saw [someone else on Twitter](https://twitter.com/twybn/status/1289866295748571137) with iOS saying that their risk-encounter disappeared after some time (which is the expected behavior). 
This would be an indication that https://github.com/corona-warn-app/cwa-app-android/issues/911 is actually an Android exclusive problem.

**Comment by uklbaer** [comment]
Yes iOS. It was only present for 3 days.
