### ISSUE TITLE
What is the advantage of "Proritized Background Activity"?

### ISSUE THREAD

**Issue by gitbrueck** [corona-warn-app/cwa-documentation#392]
## Your Question

* Documentation File:
* Line / Paragraph:
https://www.coronawarn.app/de/faq/#no_risk_update
* Question:
I open my CWA daily at least. One time per day it's updating automatically and shows the risk level to me. I am satisfied. I never switched on "Proritized Background Activity". What would be the advantage to do so?

**Comment by SebastianWolf-SAP** [comment]
If you are always opening the app yourself at least once a day, there is really no difference. Only if you forget to open it from time to time, the background task automatically does the risk calculation for you automatically. In addition to the explanation in our FAQ you can find additional information on https://dontkillmyapp.com/problem

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
