### ISSUE TITLE
Bad link to wish list in Android README.md

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#395]
## Where to find the issue

https://github.com/corona-warn-app/cwa-app-android/blob/dev/README.md
Line 54 in Section [Support & Feedback](https://github.com/corona-warn-app/cwa-app-android#support--feedback)

## Describe the issue

The link https://github.com/corona-warn-app/cwa-whishlist/issues/new/choose in the table referring to "Feature Requests" produces an HTTP 404 error.

## Suggested change

The correct link to open a new Feature Request is https://github.com/corona-warn-app/cwa-wishlist/issues/new/choose 

(Apologies for not creating a Pull Request as I am still very new to GitHub and I don't want to break anything!)

---
Internal Tracking ID: EXPOSUREAPP-2008

**Comment by GPclips** [comment]
Hello @MikeMcC399,

thanks for pointing that out.
I will share this issue with our development team.

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
From my point of view this issue can be closed, since the fix has been applied to
https://github.com/corona-warn-app/cwa-app-android/blob/dev/README.md .
