### ISSUE TITLE
Bad link to Exposure Notifications API in Wiki

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#396]
## Where to find the issue

[**Google Exposure Notification API**](https://github.com/corona-warn-app/cwa-app-android/wiki/4-Google-Exposure-Notifications-API) Wiki
https://github.com/corona-warn-app/cwa-app-android/wiki/4-Google-Exposure-Notifications-API
with link to Android Exposure Notification API Documentation v1.3.2

## Describe the issue

The link to to [Android Exposure Notification API Documentation v1.3.2](https://static.googleusercontent.com/media/www.google.com/de//covid19/exposurenotifications/pdfs/Android-Exposure-Notification-API-documentation-v1.3.2.pdf) points to 
https://static.googleusercontent.com/media/www.google.com/de//covid19/exposurenotifications/pdfs/Android-Exposure-Notification-API-documentation-v1.3.2.pdf
which throws an HTTP 404 error on an attempt to access it.

## Suggested change

Perhaps there is a more up-to-date PDF describing the Google Exposure Notification API? Otherwise https://developers.google.com/android/exposure-notifications/exposure-notifications-api may be the best online documentation resource and appropriate location to link to. The [Corona Warn App FAQs](https://www.coronawarn.app/en/faq/#ENF_version) in fact already refer to this location.

**Comment by GPclips** [comment]
Hello @MikeMcC399,

thanks for your investigation. It looks like that is is a known issue: https://github.com/google/exposure-notifications-android/issues/43

The correct link would be https://developers.google.com/android/exposure-notifications/exposure-notifications-api.

I will share this internally to solve this as soon as possible.

Thank you,
LMM

Corona-Warn-App Open Source Team

**Comment by GPclips** [comment]
Hello @MikeMcC399 ,

this issue has been corrected.

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
Hi @GPclips 

Thank you for fixing the bad link in https://github.com/corona-warn-app/cwa-app-android/wiki/4-Google-Exposure-Notifications-API referred to by https://github.com/corona-warn-app/cwa-app-android/blob/dev/README.md !

> It looks like that is is a known issue: [google/exposure-notifications-android#43](https://github.com/google/exposure-notifications-android/issues/43)

That was an identical issue with another README
https://github.com/google/exposure-notifications-android/blob/master/README.md from Google itself and that has also been fixed apparently.

**Comment by GPclips** [comment]
Hi @MikeMcC399,

yes, you are right!
Thanks for your great help and support :-)

Best Regards,
LMM

Corona-Warn-App Open Source Team
