### ISSUE TITLE
Incorrect usage of the verb "teilen" in the German language version of CWA

### ISSUE THREAD

**Issue by geos-github** [corona-warn-app/cwa-documentation#399]
## Describe the bug

The verb "teilen" in German is not necessarily a correct translation of the English verb "to share". In order to convey the meaning of sharing German uses " (etwas) mit jmdm. teilen", " (etwas) untereinander/miteinander teilen" oder "sich (etwas") teilen". Unless the appropriate context has already been established by a previous sentence or reference the verb "teilen" with no further attributes is not an appropriate translation for the English "to share", regardless whether such improper usage is widely seen in machine translations and other mediocre translations. (and yes, there are some exceptions such as "sein Wissen teilen").
"Teilen" when used on its own or with a direct object only typically carries the meaning of "to partition", "to divide", "to split" (cf. the noun "der/das Teil").
Thus the sentence "Teilen Sie Ihre Zufallscodes, damit andere gewarnt werden können." to anyone with a proper understanding of German (and no affinity to and knowledge of the technical concept of CWA or similar apps) should raise the clueless question "Durch was soll ich die Codes denn teilen?"/"What should I divide the codes by?"

To make the story short: please use proper language that adequately expresses the intended message instead of garbled word-by-word translations.
There are probably further instances where the verb "teilen" is incorrectly used to express the meaning of "to share". For the sake of a quality product (geared vastly towards a German-speaking audience) please make sure to use quality language.

## Expected behaviour

Proper wording

## Steps to reproduce the issue

read the text (without thinking along the lines of the English expression)

## Possible Fix

A correct literal translation would be "Teilen Sie Ihre Zufallscodes mit anderen", although this is rather lengthy and in that situation probably not the best of message. The message you want to convey to the user in that situation has the option to share, i.e. to upload their keys. So a possible wording in German could be "Veröffentlichen/publizieren Sie Ihre Zufallscodes" (correct description of the essence of the process, but probably sounds quite formal) or, if you want to be more technical, "Laden Sie Ihre Zufallscodes hoch".
In my opinion the best, most natural and most appropriate expression in that situation is "Stellen Sie Ihre Zufallscodes zur Verfügung" because it properly conveys the message of "donating" (or "sharing") one's codes (to the public), which is what the decision is about in that situation.

Unfortunately I would assume that there are further instances within CWA's German text where the verb "teilen" is used as an improper direct translation of "to share". I cannot judge to what extent further languages suffer from the same issue.

## Additional context

The same issue of course applies to IOS as well, so you might prefer to consolidate them.

https://github.com/corona-warn-app/cwa-app-android/blob/2d02523cf429b7329ddb3fd265d4dee6bc4b0607/Corona-Warn-App/src/main/res/values-de/strings.xml#L982

---
Internal Tracking ID: EXPOSUREAPP-2004

**Comment by GPclips** [comment]
Hello @geos-github,

thanks for sharing your thoughts. After an internal discussion, I will go forward and close this issue. With that decision, we also rely on the comment of @vaubaehn.

Thanks,
LMM

Corona-Warn-App Open Source Team
