### ISSUE TITLE
We already have a working prototype of an app

### ISSUE THREAD

**Issue by BudickDa** [corona-warn-app/cwa-documentation#40]
We already have a working prototype with the following features:
- recognises people with and without smartphones around the user using a sophisticated neural network 
- works offline and 100% p2p, without the need of a back end
- data is persisted on the device and can only be shared with the consent of the owner
- data format is universally known, only needs translation of date-format and the word "contact"

We shared some images of the UI here: https://twitter.com/zenturee/status/1260830223546961920?s=20

Contact me, if you are interested.

**Comment by egandro** [comment]
Please be nice.

**Comment by MalteJ** [comment]
:smile:
