### ISSUE TITLE
[CWA-Appstore] Google Play Store and Apple App Store should recommend permanent exposure logging

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#404]
## Where to find the issue
Google Play Store
https://play.google.com/store/apps/details?id=de.rki.coronawarnapp&hl=en

and Apple App Store
https://apps.apple.com/de/app/corona-warn-app/id1512595757

Section: HOW THE APP WORKS

## Describe the issue
Play Store says: "Whenever you leave the house, activate the exposure logging feature - it is the heart of the App."

The text in the Google Play Store says that exposure logging should be switched on whenever (each time) leaving the house and it implies that it should be switched off when returning to the house.

This is in conflict with the instructions in the Android app which says that exposure logging should be active permanently.

`risk_details_information_body_period_logged`
<string name="risk_details_information_body_period_logged">"Your risk of infection can be calculated only for periods during which exposure logging was active. The logging feature should therefore remain active permanently."</string>

## Suggested change
In the Google Play Store text, remove the reference to leaving the house and instruct to activate exposure logging. For instance:

"After installing the app, activate the exposure logging feature - it is the heart of the App." or more explicitly:

"After installing the app, activate the exposure logging feature - it is the heart of the App. When enabled, smartphones exchange encrypted random IDs with other devices using Bluetooth. It is recommended for the logging feature to remain active permanently."

This would then align with the instructions in the Android app itself.

(The issue seems to apply to iOS as well. Certainly the text in the App Store is identical.
Unfortunately I cannot check what iOS displays on an iPhone since I don't personally have access to an iOS device.)

---
Internal Tracking ID: EXPOSUREAPP-2189

**Comment by GPclips** [comment]
Hello @MikeMcC399,

thanks for reaching out. This we might should check for the iOS app as well, therefore I have added the label app to your issue. I forwarded it to the development team.

Thank you,
LMM

Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
The iOS app V1.2.1 offering viewed in the iTunes Store has the same text as the Android app in the Google Play Store:
 "**Whenever you leave the house**, activate the exposure logging feature - it is the heart of the App."

**Comment by MikeMcC399** [comment]
There has been no progress on the fundamental position of advice about whether the app should be permanently activated or only when not at home!

The stores imply activating only when not at home.

The app says keep it activated all the time.

**Comment by heinezen** [comment]
@MikeMcC399 we have recently drafted a few text changes for a better description. However, I do not know when they will be rolled out.

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@heinezen 
If the exposure logging is stopped, then not only are no Rolling Proximity Identifiers (RPI) being exchanged with other mobile devices, also no risk evaluation is carried out.

Let's assume that somebody follows the advice in the [Google Play Store](https://play.google.com/store/apps/details?id=de.rki.coronawarnapp&hl=en) "_Whenever you leave the house, activate the exposure logging feature_" and they enable exposure logging when they leave home and disable it when they return home. They are also following lockdown advice to reduce contacts to a minimum and don't leave home again for the next days.

Whilst they were out, their device receives an RPI from another device which is close by, and the person owning that other device later declares they are infected and reports this through CWA.

The person who has followed the advice in the [Google Play Store](https://play.google.com/store/apps/details?id=de.rki.coronawarnapp&hl=en) will not be warned about the risk encounter because they have disabled the exposure logging feature as implied by the play store text.

The play store is giving bad advice.

![Exposure logging stopped](https://user-images.githubusercontent.com/66998419/101537494-dc14d900-399b-11eb-8b7a-ce76d960d48c.jpg)

**Comment by MikeMcC399** [comment]
There hasn't been any change to the text in the stores which still recommend only activating the app when leaving the house.

Doing it this way means that a user who has been exposed to a reportedly infectious person will only find out the next time they leave the house, because there will not have been any exposure checks done in the meantime if exposure logging is not activated. So they delay getting informed.

**I don't really understand why this text in the stores hasn't been changed. It is bad advice to only activate exposure logging when leaving the house and it contradicts the instructions in the app, which say logging should remain active permanently.**

The only mitigating point is that many people will not read it. In the [Google Play Store](https://play.google.com/store/apps/details?id=de.rki.coronawarnapp&hl=en) you need to click on READ MORE to display this part of the text. Similarly in [Apple's App Store](https://apps.apple.com/de/app/corona-warn-app/id1512595757) the text is only displayed after an additional click.

**Comment by dsarkar** [comment]
@MikeMcC399 Text changed are currently undertaken.

**Comment by MikeMcC399** [comment]
@dsarkar 

The German text on https://play.google.com/store/apps/details?id=de.rki.coronawarnapp&hl=de looks good:

WIE DIE APP FUNKTIONIERT

Die Risiko-Ermittlung der App ist das Herzstück der Software und sollte immer aktiviert sein. Wann immer sich Nutzerinnen und Nutzer begegnen, tauschen ihre Smartphones über Bluetooth verschlüsselte Zufalls-IDs aus.

---
The English text on https://play.google.com/store/apps/details?id=de.rki.coronawarnapp&hl=en should be saying the same, **but it doesn't**:

HOW THE APP WORKS

Exposure logging is the element of the app and should always be active. Whenever you leave the house, activate the exposure logging feature. When enabled, smartphones exchange encrypted random IDs with other devices using Bluetooth.

## Suggestion

Remove the sentence **Whenever you leave the house, activate the exposure logging feature.** from the English text on the [Google Play Store](https://play.google.com/store/apps/details?id=de.rki.coronawarnapp&hl=en).

Then it would be a translation of the German text and it would be giving good advice.

**Comment by Ein-Tim** [comment]
Same for Apple App Store.

**Comment by dsarkar** [comment]
@Ein-Tim, @MikeMcC399 

Thanks for checking, will forward this information now.

**Comment by dsarkar** [comment]
@Ein-Tim   @MikeMcC399 got feedback: Issue will be completed with release 1.12. (Actually, we knew that already ... label was set to Fix 1.12)

**Comment by MikeMcC399** [comment]
@dsarkar 
Thanks! I was just checking the Google Play Store looking for the latest app version and I saw Updated January 27, 2021, so I thought that an attempt to change the text had already been made. OK, so we wait now for 1.12 again.

**Comment by Ein-Tim** [comment]
This is **not** fixed with 1.12.1 in the Apple App Store:

![IMG_815EE6CDA145-1](https://user-images.githubusercontent.com/67682506/107767323-19e40400-6d35-11eb-8101-4eda8580685b.jpeg)

**Comment by MikeMcC399** [comment]
@dsarkar 
>got feedback: Issue will be completed with release 1.12. (Actually, we knew that already ... label was set to Fix 1.12)

Unfortunately https://play.google.com/store/apps/details?id=de.rki.coronawarnapp&hl=en (like @Ein-Tim reported for iOS), the text has remained the same with the Android 1.12.0 release. 😞

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim ok! Thanks for checking. Will forward info.

**Comment by MikeMcC399** [comment]
This issue has been resolved together with the release of the 1.13.x version according to the content of the following links:

Language \ Store | Google | Apple
--- | --- | ---
EN | [Google Play Store (English)](https://play.google.com/store/apps/details?id=de.rki.coronawarnapp&hl=en) | [App Store (English)](https://apps.apple.com/de/app/corona-warn-app/id1512595757?l=en)
DE | [Google Play Store (German)](https://play.google.com/store/apps/details?id=de.rki.coronawarnapp&hl=de) | [App Store (German)](https://apps.apple.com/de/app/corona-warn-app/id1512595757?l=de)

**EN (Google & Apple)**

"Exposure logging is the core of the app and should always be active. When enabled, smartphones exchange encrypted random IDs with other devices using Bluetooth."

**DE (Google & Apple)**

"Die Risiko-Ermittlung der App ist das Herzstück der Software und sollte immer aktiviert sein. Wann immer sich Nutzerinnen und Nutzer begegnen, tauschen ihre Smartphones über Bluetooth verschlüsselte Zufalls-IDs aus."

**Comment by dsarkar** [comment]
@MikeMcC399 Thank you for checking!
