### ISSUE TITLE
Result Synchronization

### ISSUE THREAD

**Issue by PepperLewis** [corona-warn-app/cwa-documentation#407]
How often are the test results sent to the app? Does this happen on the fly or only once a day?

**Comment by GPclips** [comment]
Hello @PepperLewis,

please read through the following article: https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md. Generally, the diagnosis keys are downloaded once a day. Does this answer your question or is there something else you like to know. If yes, please be more specific with your question. 

Thank you,
LMM

Corona-Warn-App Open Source Team

**Comment by PepperLewis** [comment]
Hi, thanks for your answer. That makes it a bit clearer.
So if the lab does not evaluate the test until today, the answer will not come until tomorrow.

**Comment by thomasaugsten** [comment]
Do you mean the result of a scanned qr code test?
This will be checked every 2h in the background, at start or when you click on refresh in the test.
Some Labs are not yet connected to the App this means you will get your result via phone or mail but not via app.

**Comment by PepperLewis** [comment]
All right, this is another answer as the one of GPclips.
But all in all I have to wait untilthe result arrives at my app.
Thanks
Christian
