### ISSUE TITLE
Order of entries in „Begegnungsüberprüfungen“

### ISSUE THREAD

**Issue by jj7-hub** [corona-warn-app/cwa-documentation#408]
Hi there, in the documentation I could not find any Information about the order of the eintries in „Begegnungsüberprüfungen“ on the iPhone. There are 1-14 entries per day. Can you tell me, in which order they are listed? E.g. is the first entry whith the date of today referring to contacts of yesterday, and the second entry with the Date of today referring to contacts two days ago, and so on...? That would be great to find our, on what day there was a low-Risk-rated contact.

Thank you!
joe

**Comment by thomasaugsten** [comment]
We cannot ensure any order there are ordered when ENF ob the iPhone processed the file successful this means this list is maybe ordered or random.

**Comment by jj7-hub** [comment]
Thank you for the explanation! Is there any possibility, to find out, on which day there was a los-Risk-rated contact? Or would it be possible, to add this as a new feature?

**Comment by thomasaugsten** [comment]
We are planning this feature but from only the key list you cannot say this. Because it only says there was a match in this list of 1000 keys but this keys can be 1-14 days old

**Comment by jj7-hub** [comment]
Thanks.

**Comment by jj7-hub** [comment]
Thanks.

**Comment by daimpi** [comment]
@jj7-hub this might be interesting for you:
- https://github.com/corona-warn-app/cwa-backlog/issues/23

- https://github.com/corona-warn-app/cwa-wishlist/issues/100

For those "green" risk-encounters we will hopefully soon get a "yellow" risk status which will also provide more information:
https://github.com/corona-warn-app/cwa-app-android/issues/899#issuecomment-663475550 :)
