### ISSUE TITLE
Amend documentation/FAQ regarding the ENF Exposure Checks Details screen

### ISSUE THREAD

**Issue by SchoberMarc** [corona-warn-app/cwa-documentation#409]
I'm fully aware that this is primarily not an CWA issue, however since the ENF Exposure Check screens / data exports are partially covered by the CWA FAQ
https://www.coronawarn.app/en/faq/#keys_matches
I'd like to suggest an amendment to the documentation/FAQ so sufficient description is provided for all values shown (e.g. "Hash").

The Exposure Check logs also have been previously discussed in several issue cases, clearly showing that there is room for misinterpretation of the meaning ot these values. 

Thank you

**Comment by GPclips** [comment]
Hi @SchoberMarc,

I have transfered your issue to the documentation repo, that the right people get infrormed.
Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by tkowark** [comment]
Thanks for the proposal. Just so we get this right the first time. Currently missing are:
* Timestamp
* Data Source
* Hash

Anything else missing from your PoV, @SchoberMarc ?

**Comment by SchoberMarc** [comment]
> Anything else missing from your PoV, @SchoberMarc ?

Nope - looks pretty much complete to me. Thanks for the swift reply.

**Comment by tkowark** [comment]
Thanks again for the proposal, we've extended the FAQ with https://github.com/corona-warn-app/cwa-website/pull/303
