### ISSUE TITLE
Unable to scan QR code again

### ISSUE THREAD

**Issue by YashchenkoN** [corona-warn-app/cwa-documentation#411]
I accidentally removed a test result (it wasn’t available yet) within the app. Now I’m trying to add it again but receive “This QR code has been scanned already”.

Could you please advise how to prevent this error?

**Comment by DerVogel2020** [comment]
Similar to #960.

**Comment by thomasaugsten** [comment]
Hi
unfortunately we can't do anything it this case the message before deleting is clear:

Der Test wird endgültig aus der Corona-Warn-App entfernt und kann nicht wieder hinzugefügt werden. Dieser Vorgang kann nicht widerrufen werden.

The test will be permanently deleted from the Corona-Warn-App and cannot be added again. This procedure cannot be undone.


You have to wait for your result via phone or letter.
