### ISSUE TITLE
Information in the App is contradictory to the FAQ 

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#415]
## Where to find the issue
In the App (click on the Risk Card and scroll all the way down to "Risk of Infection") and [here](https://www.coronawarn.app/en/faq/#encounter_but_green) in the FAQ.

## Describe the issue
In the App (under the point "Risk of Infection") is written:
> [...] your encounter was restricted to a short time **AND** at a greater distance.

And in the FAQ is written:
> All exposures for a diagnosis key that lasted less than 10 minutes in total (regardless of how close the smartphones came during that time) **OR** during which the smartphones were more than 8 meters (73 dB attenuation) apart on average (regardless of how long the exposure lasted) are rated as harmless.

## Suggested change
Make sure that the FAQ and the App doesn't say different things. 

Edit: As I know now that the FAQ is correct, I think the Text in the App has to be updated.

---
Internal Tracking ID: EXPOSUREAPP-2357

**Comment by Marco2907** [comment]
Hello @Ein-Tim, 
thank you for reaching out. I have addressed your issue to our development team so that they can take care of it as soon as possible. 

Thank you,
MP

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
With the [updated Texts](https://github.com/corona-warn-app/cwa-backlog/issues/23#issuecomment-682485410) this problem would be solved, I will leave this issue open until it's finally released 👍

**Comment by Ein-Tim** [comment]
Are [these](https://github.com/corona-warn-app/cwa-backlog/issues/23#issuecomment-682485410) Texts now with 1.3.1, released?

**Comment by daimpi** [comment]
> Are [these](https://github.com/corona-warn-app/cwa-backlog/issues/23#issuecomment-682485410) Texts, now with 1.3.1, released? 

Yes they are... I've already seen ppl on Twitter sharing screenshots of them 🙂.

**Comment by Ein-Tim** [comment]
Thanks @daimpi 
Will close this Issue now
