### ISSUE TITLE
"COVID test reult is not yet available" meaning

### ISSUE THREAD

**Issue by lingfangtw** [corona-warn-app/cwa-documentation#419]
Hello everyone, I was wondering if I could get results after a COVID test even though I am negative.

Problem:
I took COVID test on 1st September, and until 3rd September still shows "test result is not yet available"
Since the clinic said that if the result is negative, they would not inform you. 
I am not sure if the result is still processing or my device is too old or a negative result or something not clear.

Detailed information:
Zenfone ZE554KL, Android 8.0
CWA 1.2.1
Clinic: Dr. Sibylle Katzenstein at Bürknerstraße 11, 12047 Berlin
(Muster OEGDb/E (6.2020) )

Thank you for your answering.
![Screenshot_20200903-141404](https://user-images.githubusercontent.com/70685117/92079436-2d6f6400-edc0-11ea-9cf7-05beba1f44cc.jpg)

**Comment by Ein-Tim** [comment]
Hey, when they said they won't inform you if you're negative, this is a little bit tricky. 

The App shows this screen when 
a) the Test Results aren't received yet
b) if you are negative and the Laboratory does not _inform_ the App.

So I would leave the Test inside the App for 2-3 more days, if this Screen stays it is most likely you're negative.
If you feel unsafe you could contact the Laboratory that tested you 👍

**Comment by daimpi** [comment]
> b) if you are negative and the Laboratory does not inform the App.

Unfortunately there were also cases where the test was positive but the result [didn't show up in the app](https://github.com/corona-warn-app/cwa-documentation/issues/400#issuecomment-674190785). But maybe the situation has improved in the meantime 🤷. 

Regarding the main question, I'll quote my reply to [a similar issue](https://github.com/corona-warn-app/cwa-documentation/issues/417#issuecomment-681011854):
> Afaik negative [and positive] test results should **always** be shown in CWA if everything is working correctly. But unfortunately not everything seems to be working correctly currently.
> Here is the FAQ entry: https://www.coronawarn.app/en/faq/#qr_test
> and here the GH issue: https://github.com/corona-warn-app/cwa-documentation/issues/400

**Comment by lingfangtw** [comment]
OK...@@
Firstly I will wait for some time, hopefully I could see the update in this app. 
Then if it already take too long time, I will ask the clinic. :/

**Comment by svengabr** [comment]
Hello everyone,

there are currently many open tickets regarding QR code handling.

The main issue is this one: https://github.com/corona-warn-app/cwa-documentation/issues/400

The CWA team is aware of the situation and it is currently a very high priority and is discussed as a topic in every daily meeting we have. Unfortunately, there are many parties involved to fix all related issues.

@lingfangtw I would kindly ask you to double check if this ticket here is necessary or if its better to contribute on the existing discussion. 

Best regards,
SG

Corona-Warn-App Open Source Team

**Comment by GPclips** [comment]
Please use the tickets referred by @svengabr to follow up. This issue will be closed.
