### ISSUE TITLE
Alvar Freude helps improving your code

### ISSUE THREAD

**Issue by Opa-Wurst** [corona-warn-app/cwa-documentation#421]
Dass hier alle Englisch reden und schreiben ist wohl so ein crazy Szene-Ding, wa? Ich mein, deutsche App, deutsche Entwickler? Whatever.

Just here to mention that Alvar did some audits on your cwa code. You find it here:

[https://mobile.twitter.com/alvar_f/status/1267705319280586753](https://mobile.twitter.com/alvar_f/status/1267705319280586753) 

Cheers ...

**Comment by Ein-Tim** [comment]
@Opa-Wurst 

We keep the Issues in English to ensure all developers (international) and non-german App users can understand them.

**Comment by thomasaugsten** [comment]
Das ist korrekt aber nicht alle Nutzer können Deutsch sprechen. Außerdem ist die App auch relevant für nicht deutsche Firmen und andere Länder die eine CWA bauen. Wir antworten auch gerne auf Deutsch. Der audit von Alvar wurde Anfang Juni erstellt und ist schon in unser Projekt eingeflossen.

**Comment by svengabr** [comment]
Hello @Opa-Wurst 

thank you very much for contacting us.

Unfortunately, we cannot answer questions that go beyond the open source process through this channel.

In case you have concrete questions regarding application architecture or source code, please post them in the respective repositories: https://github.com/corona-warn-app.

Best regards,
SG

Corona-Warn-App Open Source Team
