### ISSUE TITLE
Missing punctuation in risk_details_* German text

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#424]
## Where to find the issue
[values-de/strings.xml](https://github.com/corona-warn-app/cwa-app-android/blob/master/Corona-Warn-App/src/main/res/values-de/strings.xml)
Line 333  `risk_details_subtitle_period_logged` <string name="risk_details_subtitle_period_logged">"Dieser Zeitraum wird berücksichtigt"</string>
Line 335 `risk_details_information_body_period_logged` <string name="risk_details_information_body_period_logged">"Die Berechnung des Infektionsrisikos kann nur für die Zeiträume erfolgen, an denen die Risiko-Ermittlung aktiv war. Die Risiko-Ermittlung sollte daher dauerhaft aktiv sein"</string>

in Android app.
    
## Describe the issue 
`risk_details_subtitle_period_logged` and `risk_details_information_body_period_logged` are missing full stops (periods) at the end of the sentence in the German translation. The English text is correctly punctuated.

![EZ](https://user-images.githubusercontent.com/66998419/92719149-09cd9000-f363-11ea-9474-a194ce12accf.jpg)

![PL](https://user-images.githubusercontent.com/66998419/92719162-105c0780-f363-11ea-9d4e-040164be648a.jpg)

## Suggested change
Add a full stop "." to the end of the string `risk_details_subtitle_period_logged` and `risk_details_information_body_period_logged`.

---
Internal Tracking ID: EXPOSUREAPP-2632

Edit: Modified source link from dev to master and updated line numbers.

**Comment by heinezen** [comment]
Hello @MikeMcC399,

Thank you for your feedback. We have created Jira ticket EXPOSUREAPP-2632 for your issue and forwarded your suggestions to the developers.

Regards,
CH

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@heinezen Since you are a member, could you please make your membership of CWA public or get the Member label?
Thanks and sorry for off topic.

**Comment by heinezen** [comment]
@Ein-Tim Thanks for the hint. It should be visible now.

**Comment by MikeMcC399** [comment]
Cross-reference to https://github.com/corona-warn-app/cwa-app-android/issues/332

**Comment by janetback** [comment]
Hi @MikeMcC399 , thanks for pointing this out. I have corrected a bug in JIRA (#3650) and will fix this.

**Comment by Ein-Tim** [comment]
Related PR (iOS): https://github.com/corona-warn-app/cwa-app-ios/pull/1478

**Comment by MikeMcC399** [comment]
Fixed in https://github.com/corona-warn-app/cwa-app-android/pull/1558

**Comment by MikeMcC399** [comment]
Minor issue - closing although it has not been fixed in master or the next version to be released (1.6.0).
