### ISSUE TITLE
Spelling mistake in figure 9 of solution_architecture document

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-documentation#427]
## Where to find the issue

solution_architecture.md, figure 9

## Describe the issue

The box is named "Event Notification Framework", but should be "Exposure Notification Framework"

## Suggested change

---
Internal Tracking ID: EXPOSUREAPP-2717

**Comment by heinezen** [comment]
Hey @ndegendogo,

Good job at spotting this detail 👍  I've created a ticket in Jira for this issue (ticket ID: EXPOSUREAPP-2717), so this will hopefully be fixed soon.

Regards,
CH

Corona-Warn-App Open Source Team

**Comment by GisoSchroederSAP** [comment]
I provided a new version of figure_9 with corrected string "Exposure Notification Framework" on  Jan 29. Just need to be updated in GitHub documentation folder, and commented the respective JIRA issue.

**Comment by dsarkar** [comment]
PR https://github.com/corona-warn-app/cwa-documentation/pull/523
