### ISSUE TITLE
Use case: ID generation and storage for events, stores, restaurants etc

### ISSUE THREAD

**Issue by Wallgauer** [corona-warn-app/cwa-documentation#428]
In restaurants you must provide your personal data. This is cumbersome and security of the data could be an issue. To provide an additional alternative it would be great if the restaurant could provide a QR code - that can be scanned at the entrance with the app and stored together with a time-stamp. So the user can be warned qickly if the virus was spread in this restaurant. Can this be realized in the app?

**Comment by Ein-Tim** [comment]
Please see f.e.: https://github.com/corona-warn-app/cwa-wishlist/issues/138 and close this Issue. Thanks

**Comment by Wallgauer** [comment]
Thanks!
