### ISSUE TITLE
Include Blue Tooth signal strength information in ID emission

### ISSUE THREAD

**Issue by SchwertAs** [corona-warn-app/cwa-documentation#43]
This concerns a missing feature. Due to very different signal strength ability varying between different Smartphont types and even differnt Smartphones of equal type, it might be neccessary to send a reference value of the own blue tooth signal strenght together with the personal token to get valuable distance measures by strength of blue tooth signal.
## Where to find the issue
The issue should be added distibuted to the concerning user stories

## Describe the issue
A blue tooth receiver is only able to detect the received signal strength it is getting. To figure out the distance of an emitter the source signal strength must be known. There might be some less reliable methods by detecting singnal strength of the sender by time curve analysis whilst approach of the sender - but more reliable is a direct information of the emitters sending strength. This should be sent within the exchange of IDs to the approached smartphone. The signal strenght information should only be used for the distance detection and must not be saved to the contact list.

## Suggested change
add this to concerning user stories

**Comment by LukasMasuch** [comment]
Hey @SchwertAs, thanks for your suggestion. This issue concerns the [Exposure Notification API](https://www.google.com/covid19/exposurenotifications/) from Apple/Google and cannot be implemented from our developers for the Corona-Warn-App. The Exposure Notification API already has certain device metadata encrypted in the broadcasted identifier (e.g. transmit power level). You can find more information about technical details within the [Bluetooth Specification](https://blog.google/documents/70/Exposure_Notification_-_Bluetooth_Specification_v1.2.2.pdf).

**Comment by tklingbeil** [comment]
If you have a look at the Bluetooth specification (https://covid19-static.cdn-apple.com/applications/covid19/current/static/contact-tracing/pdf/ExposureNotification-BluetoothSpecificationv1.2.pdf), you'll see that the Associated Encrypted Metadata (AEM) contains the "transmit (Tx) power for better distance approximation".
