### ISSUE TITLE
Inaccurate Low Risk exposure statement "No exposure up to now"

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#430]
## Current Implementation
After the CWA Android app previously showed
"Low Risk / 1 exposure with low risk"
it changed on a later day to
"Low Risk / No exposure up to now"
where the string "No exposure up to now" is stored in `risk_card_body_contact`    

The statement "No exposure up to now" is not true. There was an exposure during the time up to now, however this exposure has been aged out of the risk calculation.

## Suggested Enhancement
Change `risk_card_body_contact`  to something like:
"No exposure" or
"No recent exposure" or
"No relevant exposure" or
"No current exposure" or

## Expected Benefits
Increase confidence in truth of risk card statements

---
Internal Tracking ID: EXPOSUREAPP-2833

**Comment by ugroempi** [comment]
I second the wish for an improvement and would appreciate an even more general fix, because the wording is misleading even for cases for which there were so far no risk encounters registered *in the app*. I have met real people who derived false confidence from the current worden.
So how about something like "no recent risk encounters registered"?

Best, Ulrike

**Comment by Ein-Tim** [comment]
The problem is only in the English version of the App, in German the text says: 
`Keine Risiko-Begegnung` which is correct.

**Comment by Ein-Tim** [comment]
This issue was also reported here: https://github.com/corona-warn-app/cwa-app-ios/issues/1507

**Comment by MikeMcC399** [comment]
@Ein-Tim 
>The problem is only in the English version of the App, in German the text says:
Keine Risiko-Begegnung which is correct.

In CWA Android Version 1.6.1 the issue is still visible in both English and German displays.

![Low Risk](https://user-images.githubusercontent.com/66998419/99768462-14479b00-2b05-11eb-8a9b-945e7f142942.jpg)

**Comment by Ein-Tim** [comment]
![image](https://user-images.githubusercontent.com/67682506/99768691-84eeb780-2b05-11eb-912b-415bdefd7f09.jpeg)

CWA Version 1.6.1 under iOS

**Comment by ugroempi** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/67682506/99768879-cc754380-2b05-11eb-8f68-d00a44638e1f.jpeg)
> CWA Version 1.6.1 under iOS (German - with English it's like under Android)

I would argue that this is still not adequate, because it overstates the truth. "Keine Risiko-Begegnungen registriert" ("no registered exposure") or something like that would more correctly report the status. After all, we meet many people who do not have the app, and we do not need over-confidence.

**Comment by Ein-Tim** [comment]
@ugroempi 
I know that it's not perfect, but if you click on the Risk Card and scroll to the very bottom you will see this "disclaimer":
![image](https://user-images.githubusercontent.com/67682506/99803216-58549300-2b39-11eb-95e9-872e5c1b8f16.jpeg)

**Comment by ugroempi** [comment]
@Ein-Tim 
Agreed, but who ever reads disclaimers? The big green risk communication field itself should be as clear as possible. Even the disclaimer does not explicitly mention the restriction that only infected *app users* are counted. I know it's blatantly obvious, but it can still get overlooked. But I'll stop being a pain right now ;-)

**Comment by Ein-Tim** [comment]
@ugroempi You're no pain, but since this is a bit off topic here I think it would be best if you open a new Issue regarding this 🙂

**Comment by dsarkar** [comment]
Dear @MikeMcC399, @Ein-Tim,

Thanks for bringing this up again. We will check with the developers the progress of this issue. 

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
`risk_card_body_contact` no longer exists in CWA Android, however `risk_card_low_risk_no_encounters_body` contains the string "No exposures" in Android Version 1.10.1 in [values/strings.xml](https://github.com/corona-warn-app/cwa-app-android/blob/4f7664467cb9be280f39e5e61f9e0eb5f6063613/Corona-Warn-App/src/main/res/values/strings.xml#L160-L161) ln 160-161

    
    <string name="risk_card_low_risk_no_encounters_body">"No exposures"</string>

This was fixed by PR https://github.com/corona-warn-app/cwa-app-android/pull/1948.

Now that  <string name="risk_card_low_risk_no_encounters_body">"No exposure up to now"</string> has been changed to <string name="risk_card_low_risk_no_encounters_body">"No exposures"</string> the issue is resolved.

Therefore closing.
