### ISSUE TITLE
Display of "Tage seit letzter Risiko-Begegnung" is irritating

### ISSUE THREAD

**Issue by vschoech** [corona-warn-app/cwa-documentation#433]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

"Tage seit letzter Risiko-Begegnung" are calculated differently at different times of the same day. It seems that sometimes, in the morning, it calculates 1 less than in the evening. I am 99% sure that the higher number, which is shown later in the day, is the correct one.

Today I took two screenshots to illustrate the issue. I noticed, that there was an update of "infected data" in between the screenshots. Maybe the "morning vs. evening" is actually "before vs. after the daily update"?

## Expected behaviour

According to expectation based on communication between humans, the displayed number must not change within one day. Accuracy/unambiguousness is very much desirable, because indicating the wrong day can raise a lot of questions and point into wrong directions (e.g., if one day I was in the office, and the other day I was strictly at home).

Instead of a relative expression of time ("vor n Tagen"), you could as well switch to expressing time in absolute terms ("Am 27. May"). Stating a precise date would probably be less prone to programming errors, and it would be less ambiguous and potentially more helpful for the user.

## Steps to reproduce the issue

First of all, you need to register a "Risiko-Begegnung". Then, repeatedly look at the app display over the course of a day. **The following screenshots were both taken today, at 7:16 AM and at 10:49 AM**, but I noticed the problem already a few times before:

![2020-08-10 07-15-58](https://user-images.githubusercontent.com/44493453/89767320-fe840c00-daf9-11ea-9766-b8999bf98de4.jpeg)
*(Screenshot taken 10-Aug-2020 07:15:58)*

![2020-08-10 10-48-56](https://user-images.githubusercontent.com/44493453/89767316-fdeb7580-daf9-11ea-9549-f17b4cd53ebb.jpeg)
*(Screenshot taken 10-Aug-2020 10:48:56)*

## Technical details

- iOS Version: 13.6
- Device: iPhone Xr

## Additional context

Reported the problem here already:
https://pandemie-forum.de/t/corona-warn-app-technische-probleme-und-updates/600/43?u=volker.berlin

---
Internal Tracking ID: EXPOSUREAPP-2406

**Comment by rude78** [comment]
> Hello everyone,
> 
> there is already an internal proposal for showing more information regarding risk encounters. We will open a new wishlist entry for this soon to make it more transparent for everyone.
> 
> An overhaul of risk encounters information UI/UX was implemented with the app version 1.3.1 which is already available.

I could not see any improvement in version 1.3.2. Is there an update on this issue.

**Comment by Ein-Tim** [comment]
@rude78 
Since Version 1.3.2 you should see an Information Text if you had Low Risk Encounters. 
(Open CWA -> Click the Risk Card -> you will see an Text ("Begegnungen mit niedrigem Risiko") if you had Low Risk Encounters.)

**Comment by ndegendogo** [comment]
I would also like to understand better how to read this "x Tage seit letzter Risiko-Begegnung".
afaiu you get this as number from ENF call and display as-is. So, please clarify with Apple and Google the following:
How is this "days since last exposure" calculated?
Is it correct understood as time difference between the matching RPI and the time of check?
How exactly is this time difference then rounded to days?

**And please be aware that the implementation of ENF might be different between A and G, and ask both of them.**

**Comment by sssfff** [comment]
Wouldn't it be far easier to show **the exact date and time** of the risk exposure (maybe the last timestamp of the contact with the other token)? It would help the user:
a) to self-evaluate his/her own risk ("ahhh, at this point in time i was in my car at a traffic light, so this may come from the car next to me = low risk" or "ahh I was attending a meeting with 4 other guys = high risk")
b) to get an indication of who (taken from my brain memory) may have caused the exposure warning, and get in touch with these potential spreaders (if known) w/o violating data privacy - this may help in breaking the spreader chains

In case of concerns about data privacy: What exactly are these concerns? No extra data are shared with anyone else, no additional data are collected. As the user is "owning" his/her own tokens and exposure touches with other tokens, this would increase transparency of the user's own data.

**Comment by sssfff** [comment]
> > It's quite bad to not explicitly stating the time frame when the contacts occurred, since this way you could narrow it down how the contact occurred.
> 
> @RubenKelevra _It's not a bug, it's a feature._ The precise time of the encounter is intentionally not given away because you don't want to expose the person that has reported being infected. Anonymity is an important aspect for broad acceptance. If it is easy to trace back who reported an infection, less infections will be reported.
> 
> That said, intentionally not giving a precise time frame is not the same as giving a time frame that _seems_ so be precise but is not consistent with other information (which is what this ticket is about).



> > It's quite bad to not explicitly stating the time frame when the contacts occurred, since this way you could narrow it down how the contact occurred.
> 
> @RubenKelevra _It's not a bug, it's a feature._ The precise time of the encounter is intentionally not given away because you don't want to expose the person that has reported being infected. Anonymity is an important aspect for broad acceptance. If it is easy to trace back who reported an infection, less infections will be reported.
> 
> That said, intentionally not giving a precise time frame is not the same as giving a time frame that _seems_ so be precise but is not consistent with other information (which is what this ticket is about).

We should re-think this argumentation with "not exposing the infected person" under the current escalating situation. Showing a time window of several hours for the exposure ("x Tage seit Begegnung") could lead to even more rumors and misleading speculations about infected contacts. The ability to narrow down the "suspicious" contact could help to avoid this, and may have other benefits, see: https://github.com/corona-warn-app/cwa-documentation/issues/433#issuecomment-720625881

**Comment by Ein-Tim** [comment]
@sssfff Just from the technical side: the ENF does not reveal the exact time an Encounter happened.

**Comment by sssfff** [comment]
> @sssfff Just from the technical side: the ENF does not reveal the exact time an Encounter happened.

I cannot imagine, that there are no technical solutions to bypass this strange limitation ....
And, by the way, there is an API call _GetExposureWindows_ (https://developers.google.com/android/exposure-notifications/exposure-notifications-api#getexposurewindows), which probably does what I have in mind (_exact_ time is not required IMHO, a window of 30 min to one hour should be "good enough" and far less irritating than "vor x Tagen" The new text could be something like "Letzte Risko-Begegnung am 2.11. gegen 18 Uhr (+/- 30 min)"

As a side node from the Google documentation: "Note: We strongly recommend migrating to ExposureWindow mode for enhanced risk calculation functionality."

**Comment by daimpi** [comment]
@sssfff 
> I cannot imagine, that there are no technical solutions to bypass this strange limitation ....

There are indeed ways to bypass this limitation, you just have to root your phone to do it 😉 

> And, by the way, there is an API call GetExposureWindows (developers.google.com/android/exposure-notifications/exposure-notifications-api#getexposurewindows), which probably does what I have in mind (exact time is not required IMHO, a window of 30 min to one hour should be "good enough" and far less irritating than "vor x Tagen" The new text could be something like "Letzte Risko-Begegnung am 2.11. gegen 18 Uhr (+/- 30 min)"

Even exposure window mode doesn't expose time-frames which are finer than one day afaik, so this wouldn't work.

> As a side node from the Google documentation: "Note: We strongly recommend migrating to ExposureWindow mode for enhanced risk calculation functionality."

Yes, I also hope we see a shift soon there. Here is the respective issue btw: https://github.com/corona-warn-app/cwa-documentation/issues/373

**Comment by vschoech** [comment]
> We should re-think this argumentation with "not exposing the infected person" under the current escalating situation. Showing a time window of several hours for the exposure ("x Tage seit Begegnung") could lead to even more rumors and misleading speculations about infected contacts. The ability to narrow down the "suspicious" contact could help to avoid this, and may have other benefits, see: [#433 (comment)](https://github.com/corona-warn-app/cwa-documentation/issues/433#issuecomment-720625881)

You are walking a very fine line here. If users decide not to use the app, or not to report their infection, the entire effort is in vain. As long as you're not living in a country where government can force people to use certain apps, the decision is theirs, not yours. Thus the users' concerns must be obeyed, whether you agree with them or not.

**Comment by sssfff** [comment]
> > We should re-think this argumentation with "not exposing the infected person" under the current escalating situation. Showing a time window of several hours for the exposure ("x Tage seit Begegnung") could lead to even more rumors and misleading speculations about infected contacts. The ability to narrow down the "suspicious" contact could help to avoid this, and may have other benefits, see: [#433 (comment)](https://github.com/corona-warn-app/cwa-documentation/issues/433#issuecomment-720625881)
> 
> You are walking a very fine line here. If users decide not to use the app, or not to report their infection, the entire effort is in vain. As long as you're not living in a country where government can force people to use certain apps, the decision is theirs, not yours. Thus the users' concerns must be obeyed, whether you agree with them or not.

Fully agree, that acceptance must not be impacted by unwanted features. On the other hand: Do we have a clear picture about user concerns (i.e. by statistically proof survey, votes or whatever), ore is our view on concerns more based on assumptions, speculations and gut feelings? I just want to ensure, that the app feature is not limited by some assumptions, while the majority of users welcomes the feature request described here.
Following a design thinking approach a version with and another without exact date/time presentation would be offered to user test groups.

**Comment by webermike** [comment]
Please show Date and Time of later on announced risk contacts, even if this leads to still having a green status.

As such contacts might occur only at shopping or eating in a restaurant, one can reconstruct with Date and Time where one habe been and if shopping or queuing anywhere is the risk reason.

This would enhance the analyse and discussion and avoiding of behavior in the future much, when it ia shown if the risk contact was at 8:00 in the bus ir at 12:00 in the McDonalds restaurant or at work at 10:00 o'clock at a certain date/day.

so it is not about "10 days ago" but about exact time and day.

Thanks for implementing that local showup fast.

**Comment by webermike** [comment]
Then use the timestamp of the computer. It is important to know if it is in the bus or at lunchtime.

**Comment by Ein-Tim** [comment]
@webermike See my comment here: https://github.com/corona-warn-app/cwa-wishlist/issues/100#issuecomment-723112813

**Comment by stherold** [comment]
> act time but only the day when the exposure occurred (see [here](https://github.com/corona-warn-app/cwa-backlog/issues/23#issuecomment-678692630) for more details on the response CWA gets from ENF). If you have a rooted android device you can bypass this restriction e.g. with the [corona-warn-companion-android](https://github.com/mh-/corona-warn-companion-android) though.

But it would be possible to show the absoloute date for the reported day, without the time component for the reposrted day. This would already help a lot to not have to calculate in mind which day it exactly was. In a friends app there stand "risk encounter 6 days ago" and on the next day it was still 6 days ago, which can be very irritating! Writing the abs day solves this.

**Comment by Blackjacx** [comment]
> act time but only the day when the exposure occurred (see [here](https://github.com/corona-warn-app/cwa-backlog/issues/23#issuecomment-678692630) for more details on the response CWA gets from ENF). If you have a rooted android device you can bypass this restriction e.g. with the [corona-warn-companion-android](https://github.com/mh-/corona-warn-companion-android) though.

But it would be possible to show the absoloute date for the reported day, without the time component for the reposrted day. This would already help a lot to not have to calculate in mind which day it exactly was. In a friends app there stand "risk encounter 6 days ago" and on the next day it was still 6 days ago, which can be very irritating! Writing the abs day solves this.

**Comment by sssfff** [comment]
I suggest to raise a feature request towards the creators of the Exposure Notification Framework (Apple/Google) to add the exposure time to the GetExposureWindow() call. While this is implemented, community can still discuss the data privacy impact, and developers can decide about using the new capabilities, or not to use them.

**Comment by Ein-Tim** [comment]
Version 1.8.0 and above will show the exact date of the last Risk Encounter (see https://github.com/corona-warn-app/cwa-app-ios/pull/1550)

**Comment by MikeMcC399** [comment]
It should be possible to close this issue. 

The blog post https://www.coronawarn.app/en/blog/2020-12-16-corona-warn-app-version-1-9/ (or https://www.coronawarn.app/de/blog/2020-12-16-corona-warn-app-version-1-9/ for German version), referring to the released version 1.9, shows an Increased Risk screen shot with an absolute date "Most recently on 15 Dec 2020" rather than a relative date such as  "x days since ...".

**Comment by dsarkar** [comment]
Dear @vschoech,  @Ein-Tim,  @sssfff,  @ir-fuel, @daimpi, @Blackjacx, @webermike,  @MikeMcC399, and community,

Thank you for all the contributions here. As suggested, we will close this issue now. 

Best wishes,
DS

---
Corona-Warn-App
