### ISSUE TITLE
Issue #401 closed, but still present

### ISSUE THREAD

**Issue by geos-github** [corona-warn-app/cwa-documentation#434]
Issue #401 has just been closed although it is actually still present in https://github.com/corona-warn-app/cwa-app-android/blob/master/Corona-Warn-App/src/main/res/values-de/strings.xml (in line 998)
You only fixed it on IOS.
Looks like I cannot reopen #401, so I need to open thing new issue instead.

PS: I'm surprised how long it takes to add one missing comma :-)

**Comment by heinezen** [comment]
@geos-github Thanks for the hint, I'll reopen the original issue.

---
Corona-Warn-App Open Source Team
