### ISSUE TITLE
[Translation] (de) Please translate "older logs" as "Ältere Aufzeichnungen" instead of "Ältere Tage".

### ISSUE THREAD

**Issue by schweer-guest** [corona-warn-app/cwa-documentation#437]
* [x] None of the other issue templates apply to this issue.

---
Internal Tracking ID: EXPOSUREAPP-1923

**Comment by svengabr** [comment]
Hey @schweer-guest, I moved your issue to `cwa-documentation` and added your screenshot to the linked Jira ticket.

Thank you very much for your feedback!

Best regards,
SG

Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Still affects iOS CWA Version 1.7.1.

**Comment by Ein-Tim** [comment]
This issue is obsolete as the text does not exist anymore. Please close it.

**Comment by schweer-guest** [comment]
closing

**Comment by dsarkar** [comment]
@schweer-guest @Ein-Tim Thanks for housekeeping, internal ticket set to obsolete.
