### ISSUE TITLE
2nd Corona-App renders some User Stories obsolete

### ISSUE THREAD

**Issue by TomTeeJay** [corona-warn-app/cwa-documentation#44]
Today a golem.de article reports that Germany is working on another Corona App aiming to support local health authorities ("Gesundheitsämter") and Users with information.

https://www.golem.de/news/coronapandemie-quarantaene-app-soll-gesundheitsaemter-entlasten-2005-148475.html  

This renders many of the "User Stories" in current documentation obsolete, esp. those ones where additional incentives like test notifications, information and dynamic content could be misused for nudging.

The User Stories in question are:

- E02.06
- parts of E04.01
- E04.02
- E05.02
- E06.02
- E10.01

Will this be considered in current documentation, the soon to published code and further development?

**Comment by mynchau** [comment]
This question is not related to this app. Please reach out to the respective contacts of the other app mentioned in that article.

**Comment by TomTeeJay** [comment]
Sorry, of course the list of User Stories in question is related to this app. In my Understanding these ones have nothing in common with the nature and purpose of a contact tracing app (I take reference to to the DP-3T comic in issue #21)  and due to the fact that there is a 2nd app aiming to inform users these User Stories are at least in question and basicaly doublettes.
