### ISSUE TITLE
[CWA-Documentation-Github] CODEOWNERS includes @tkowark

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#440]
## Where to find the issue
https://github.com/corona-warn-app/cwa-documentation/blob/master/CODEOWNERS

## Describe the issue
@tkowark is listed in several places in the [CODEOWNERS document](https://github.com/corona-warn-app/cwa-documentation/blob/master/CODEOWNERS), however he wrote in https://github.com/corona-warn-app/cwa-app-android/issues/1199#issuecomment-698160734 on Sep 24, 2020:
> ... I will not be around more often as I've transitioned out of the CWA project and are now working on other projects within SAP ...

## Suggested change
Check with @tkowark if he should be removed from [CODEOWNERS document](https://github.com/corona-warn-app/cwa-documentation/blob/master/CODEOWNERS), then remove or replace his github user name.

---
Internal Tracking ID: [EXPOSUREAPP-4291](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4291)

**Comment by christianneu** [comment]
Thanks for your input. I will replace contact names soon.

Mit freundlichen Grüßen/Best regards,
CN
Corona Warn-App Open Source Team

**Comment by daimpi** [comment]
@christianneu Just a small OT suggestion: You could add your CWA membership status to your Github profile 🙂.

**Comment by Ein-Tim** [comment]
@christianneu 
Vielleicht you could check the same for @SebastianWolf-SAP 
He also stated that he won't be part of the CWA Project anymore...

**Comment by MikeMcC399** [comment]
@christianneu 
> I will replace contact names soon.

Something seems to have prevented the change. I still see 
@tkowark in https://github.com/corona-warn-app/cwa-documentation/blob/master/CODEOWNERS

**Comment by Ein-Tim** [comment]
Any updates? The cwa-website repo also still includes @SebastianWolf-SAP as a CODEOWNER.

I could provide a PR here and in the website repo which removes them, but I suggest that you do that and add a new CODEOWNER.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for the offer. We will ask for updates.

**Comment by MikeMcC399** [comment]
@dsarkar 
Of course this is SAP's decision, but it seems strange to keep out-of-date names in the 
[CODEOWNERS document](https://github.com/corona-warn-app/cwa-documentation/blob/master/CODEOWNERS) for this repository.

**Comment by MikeMcC399** [comment]
Closing due to lack of progress.

**Comment by Ein-Tim** [comment]
The Codowners of the website repo were [updated](https://github.com/corona-warn-app/cwa-website/commit/2c4190045a2f5662bda79caa4bbb81e6742829dc).  
I suggest that you do the same in this repository.

**Comment by heinezen** [comment]
Fix is coming in https://github.com/corona-warn-app/cwa-documentation/pull/620
