### ISSUE TITLE
[CWA-Documentation-Github] Wiki packages missing information for new packages in releases 1.5 and later

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#442]
## Where to find the issue 
https://github.com/corona-warn-app/cwa-app-android/wiki/5-Packages

## Describe the issue
The Wiki document [5-Packages](https://github.com/corona-warn-app/cwa-app-android/wiki/5-Packages) referred to by https://github.com/corona-warn-app/cwa-app-android/blob/release/1.5.x/README.md does not describe any of the new packages introduced by [release/1.5.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/1.5.x).

## Suggested change
Add a paragraph of explanation to [5-Packages](https://github.com/corona-warn-app/cwa-app-android/wiki/5-Packages) for each of the new packages:

- appconfig
- diagnosiskeys
- environment
- playbook
- submission
- verification

---
Internal Tracking ID: [EXPOSUREAPP-4290](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4290)

**Comment by MikeMcC399** [comment]
With the release of 1.7.x there are even more packages which are not documented in https://github.com/corona-warn-app/cwa-app-android/wiki/5-Packages e.g.

- bugreporting
- deadman

**Comment by dsarkar** [comment]
FYI: Internal Tracking ID: EXPOSUREAPP-4290 DS
---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
It would be interesting to see documentation for the `deadman` package (see also comment in https://github.com/corona-warn-app/cwa-documentation/issues/442#issuecomment-735260084).

Reading the Android code at https://github.com/corona-warn-app/cwa-app-android/tree/main/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/deadman I think it fires the following notification if there hasn't been a successful exposure check for more than 36 hours. Is that correct?

`risk_details_deadman_notification_body`
"Please remember to open the Corona-Warn-App regularly to check your risk status."

(Note: there is currently an issue that the notification is truncated on Android. See https://github.com/corona-warn-app/cwa-app-android/issues/1850.)

**Comment by Ein-Tim** [comment]
> I think it fires the following notification if there hasn't been a successful exposure check for more than 36 hours. Is that correct?

Yes this is correct.

**Comment by MikeMcC399** [comment]
The packages in CWA Android 1.10.1 according to the directories listed in https://github.com/corona-warn-app/cwa-app-android/tree/main/Corona-Warn-App/src/main/java/de/rki/coronawarnapp are as follows. Many of them are not documented in https://github.com/corona-warn-app/cwa-app-android/wiki/5-Packages.

Package | 
--- | 
appconfig | 
bugreporting |
contactdiary |
deadman |
diagnosiskeys |
environment |
[exception](https://github.com/corona-warn-app/cwa-app-android/wiki/5-Packages#exception)| 
[http ](https://github.com/corona-warn-app/cwa-app-android/wiki/5-Packages#http)|
[nearby](https://github.com/corona-warn-app/cwa-app-android/wiki/5-Packages#nearby)|
notification |
playbook |
[receiver](https://github.com/corona-warn-app/cwa-app-android/wiki/5-Packages#receiver)|
[risk](https://github.com/corona-warn-app/cwa-app-android/wiki/5-Packages#risk)|
[service](https://github.com/corona-warn-app/cwa-app-android/wiki/5-Packages#service)|
[sharing](https://github.com/corona-warn-app/cwa-app-android/wiki/5-Packages#sharing)|
[storage](https://github.com/corona-warn-app/cwa-app-android/wiki/5-Packages#storage)|
submission |
task |
tracing |
[ui](https://github.com/corona-warn-app/cwa-app-android/wiki/5-Packages#ui)|
[update](https://github.com/corona-warn-app/cwa-app-android/wiki/5-Packages#update)|
[util](https://github.com/corona-warn-app/cwa-app-android/wiki/5-Packages#util)|
verification |
[worker](https://github.com/corona-warn-app/cwa-app-android/wiki/5-Packages#worker) |

The following packages are documented in https://github.com/corona-warn-app/cwa-app-android/wiki/5-Packages, however they are not present in https://github.com/corona-warn-app/cwa-app-android/tree/main/Corona-Warn-App/src/main/java/de/rki/coronawarnapp.

Package | 
--- | 
[timer](https://github.com/corona-warn-app/cwa-app-android/wiki/5-Packages#timer)
[transaction](https://github.com/corona-warn-app/cwa-app-android/wiki/5-Packages#transaction) |

**Comment by dsarkar** [comment]
Thanks, updated Internal Tracking ID: EXPOSUREAPP-4290. DS

**Comment by MikeMcC399** [comment]
It seems like new features and enhancements are not being documented at all. There is no mention of the 
- Contact Journal nor of the 
- Statistics

in the community-facing documentation. 😞

**Comment by MikeMcC399** [comment]
The contents of the [Wiki 5 Packages](https://github.com/corona-warn-app/cwa-app-android/wiki/5-Packages) has not been updated since June 12, 2020.

If there is no intention of keeping this document up to date, I suggest adding text at the top of  [Wiki 5 Packages](https://github.com/corona-warn-app/cwa-app-android/wiki/5-Packages) to say that the Wiki is not being maintained and it reflects the packages which were part of the original release in June 2020 only.

**Comment by dsarkar** [comment]
@MikeMcC399 ok, I will suggest this to the devs.

**Comment by Ein-Tim** [comment]
Since we're in the documentation repo here, that's how it looks on iOS:

https://github.com/corona-warn-app/cwa-app-ios/wiki was last updated on 24.08.2020. I'm quite sure that the iOS wiki is also missing some new things, but I can't check it at the moment.

For iOS there's also a GitHub Pages deployment: https://corona-warn-app.github.io/cwa-app-ios/
It was last updated on 22.10.2020.
I don't think the infos there are outdated but are also missing some parts.

**Comment by MikeMcC399** [comment]
https://github.com/corona-warn-app/cwa-app-android/wiki/5-Packages has been deleted.

**Comment by MikeMcC399** [comment]
@dsarkar 
The wiki deletions were carried out by @harambasicluka.
See https://github.com/corona-warn-app/cwa-app-android/pull/3117 and https://github.com/corona-warn-app/cwa-app-android/wiki/_history.

**Comment by dsarkar** [comment]
@MikeMcC399 ok, thanks for the info.

**Comment by MikeMcC399** [comment]
Closing, since the Wiki documentation has been deleted and no further feedback has been forthcoming.
