### ISSUE TITLE
Questions about influence of proximity for risk calculation and key exchange

### ISSUE THREAD

**Issue by A-speaking** [corona-warn-app/cwa-documentation#451]
Excuse me if this is the wrong thread to ask but I have a few questions:
1. I do work in an office (with a whole shopwindow) on a pedestrian zone, on a well-trafficked street. 
If people stand in front of the shopwindow and talk or stand and talk on the other side of the road or pass the office by with car or bike (even standing in a traffic jam in front of the office) could those be green Risikokontakte in my App, too?
In other words, I tried to understand what distance and what duration is logged in the App. Is it enough for someone to pass me by or is there a minimum distance and duration that is needed for my App to get different keys? I tried to read some parts of the documentation but I couldn`t fully understand...
2. My second question is:  Does everyones phone have a **certain key** or do those keys change? I read somewhere that someone had 20 green Risikokontakte in their App as they passed the door of their neighbour every day collecting new "Risikokontakt"-notification from the same person. That seemed odd to me, can someone explain if that is possible?

Thank you for reading my questions and taking the time to explain!
You guys are doing a great job here.

**Comment by daimpi** [comment]
Hi @A-speaking,


>   1. I do work in an office (with a whole shopwindow) on a pedestrian zone, on a well-trafficked street.
>        If people stand in front of the shopwindow and talk or stand and talk on the other side of the road or pass the office by with car or bike (even standing in a traffic jam in front of the office) could those be green Risikokontakte in my App, too?
>        In other words, I tried to understand what distance and what duration is logged in the App. Is it enough for someone to pass me by or is there a minimum distance and duration that is needed for my App to get different keys? I tried to read some parts of the documentation but I couldn`t fully understand...

Yes, someone passing by your office and/or standing in front of the window could in principle cause an encounter in CWA if they later test positive and share their keys. 
The way how the Exposure Notification Framework (ENF - which is the API by Google/Apple CWA docks onto) knows that you had a contact is by exchanging so called "rolling proximity identifiers" (RPIs) with other phones. Those are exchanged via Bluetooth low energy (BLE) which broadcasts on the 2.4 GHz frequency i.e. the same frequency as Wifi, so it can penetrate windows, walls, etc. to a certain degree. But usually it's not sending with lots of power so after a certain distance the signal will be too weak to be picked up by any other device (Iphones are [seemingly](https://github.com/corona-warn-app/cwa-documentation/issues/341) sending with higher power than Android devices and therefore can presumably be picked up over a larger distance). Over which exact distance a signal can still be picked up depends on a lot of factors including reflections, antenna orientation, (type of) objects in the radio pathway etc. But not every person passing by will necessarily be picked up by your phone even if they were in principle sending a signal strong enough for your phone to pick it up b/c while ENF is constantly broadcasting RPIs [it's only occasionally recording them](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#limitation) for a few sec every 2-5 min.
All the recorded RPIs are then stored in ENF and if one of those people later tests positive you will [at least see](https://github.com/corona-warn-app/cwa-backlog/issues/23#issuecomment-679231707) a green encounter in CWA. If the signal was very strong, the contact lasted long enough and the person was highly infectious this will trigger a red exposure. If you're interested to learn more details about how a red exposure is triggered, we [recently walked through some examples](https://covidapps.slack.com/archives/C0194ML0MLN/p1602134945259900) in the community Slack which you can join [here](https://github.com/corona-warn-app/cwa-documentation/issues/379). There is also a [document](https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md) here in the repo which describes the process in more detail (even though at the time of writing it's outdated in some aspects).


>  2. My second question is:  Does everyones phone have a **certain key** or do those keys change? I read somewhere that someone had 20 green Risikokontakte in their App as they passed the door of their neighbour every day collecting new "Risikokontakt"-notification from the same person. That seemed odd to me, can someone explain if that is possible?
 
We have to distinguish two types of keys here:
1. Rolling Proximity Identifiers (RPIs) change every 10-15 min and [are derived](https://blog.google/documents/69/Exposure_Notification_-_Cryptography_Specification_v1.2.1.pdf) from TEKs. RPIs are what your device broadcasts and records.
2. Temporary Exposure Keys (TEKs) change every 24h (at 00:00 UTC). TEKs will be uploaded to the server and distributed if you test positive and decide to share them. 

The number of encounters in CWA / the number of matches in the EN log should be equal to the number of TEKs you matched with. I've written about this in a bit more detail [here](https://github.com/corona-warn-app/cwa-app-ios/issues/1096#issuecomment-688235743). As any person who tests positive can upload up to 14 TEKs (one for each of the last 14 days) you could get over 10 matches/encouters from a single person (not  20 though if everything is working correctly ^^).

**Comment by A-speaking** [comment]
Thank you so much @daimpi for your time and effort trying to explain it to me.

Please bear with me as I might still ask some stupid questions regarding point 1.:

- Is it right that people being less than 2 minutes around me (and with "around me" I mean next to me, outside of my office etc.) won't be tracked at all? So is 2 minutes the minimum time that is needed to be "logged"? 
Or what do you mean with _"while ENF is constantly broadcasting RPIs it's only occasionally recording them for a few sec every 2-5 min."_? Does that mean my mobile randomly picks up people around me every 2-5 minutes which also means if me and my partner are standing at the same spot and someone passes us by ( who is tested positive three days later) could appear on my mobile but not on my partner's?

I am just trying to understand... so please, enlighten me :) Thank you so much!

**Comment by daimpi** [comment]
> Is it right that people being less than 2 minutes around me (and with "around me" I mean next to me, outside of my office etc.) won't be tracked at all? So is 2 minutes the minimum time that is needed to be "logged"?

No. Even contacts shorter than 2 min could be logged if they by chance fall into the few seconds wide [listening window](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#limitations) of your device.

>  Or what do you mean with _"while ENF is constantly broadcasting RPIs it's only occasionally recording them for a few sec every 2-5 min."_? Does that mean my mobile randomly picks up people around me every 2-5 minutes which also means if me and my partner are standing at the same spot and someone passes us by ( who is tested positive three days later) could appear on my mobile but not on my partner's?

Yes this is correct 👍. Once your device listens (every 2-5 min for a few sec) it will record all the RPIs it can see and if you and your partner's phone are not listening at the exact same time one of you might record something the other doesn't.

**Comment by TeRe20200** [comment]
Thank you so much for explaining it to me @daimpi !
Can I ask one last question that might be a little off topic from the previous topic, but I’ll still try my luck:

Lets imagine my Corona-Warnapp shows me 
1 green Risikokontakt on Monday 
and another one on Wednesday (so I have 2 green Risikokontakte displayed on Wednesday) 
and one gets deleted on Friday but on the same day I get two new ones (which makes it a total of 3) 
- is there any way I can see that one got deleted and that 2 new ones came in?

**Comment by daimpi** [comment]
Hi @TeRe20200 
> Lets imagine my Corona-Warnapp shows me
> 1 green Risikokontakt on Monday
> and another one on Wednesday (so I have 2 green Risikokontakte displayed on Wednesday)
> and one gets deleted on Friday but on the same day I get two new ones (which makes it a total of 3)
> 
> * is there any way I can see that one got deleted and that 2 new ones came in?

The answer is: It depends. First of all you'll have to take a look at the EN log on your device. Second, this only works on Android before CWA 1.5 or on iOS:

In the log you'll be able to see which package you had matches with. So if a contact which is phased out gets replaced with a new one, you'll see the number of matches going down in one package and going up in another one. I've written about this in some more detail here: https://github.com/corona-warn-app/cwa-app-android/issues/1302.

**Comment by TeRe20200** [comment]
@daimpi Thank you for answering!

**Comment by A-speaking** [comment]
Hey everyone, I have a quick question and didn't want to open a new issue, so I thought I try my luck here, maybe @daimpi is so kind to enlighten me. _It is a general question:_

I was at home on sunday and monday and I didn't turn on my bluetooth. I do turn it on every day exactly on the time the coronapp gets updated. It now says "Exposure logging 12 out of 14 days active". 

My question now is: 
I will stay home tomorrow the whole time, won't turn on my bluetooth. I will go out to buy groceries at 6 pm for approx. 2 hours and turn my bluetooth on for the time I was outside. 
**Question 1**: The App does track the bluetooth-signals found in the 2 hours I was outside, right? Even though bluetooth was turned off for 22 hours?
**Question 2**: Even if the app says "Exposure loggin 11 out of 14 days active" tomorrow at update time, it did count the keys it could get while I was in the supermarket. Is that right? 

For those of you wondering why I do turn off my bluetooth: I am living on a very highly frequented mainstreet in a very big city and during the last weeks, although I was home and inside most of the time I did have SO MANY green alerts - that is why.

Thank you so much for your help

**Comment by MikeMcC399** [comment]
@A-speaking 
> Question 1: The App does track the bluetooth-signals found in the 2 hours I was outside, right? Even though bluetooth was turned off for 22 hours?

So long as the app is showing EXPOSURE LOGGING ACTIVE (or in German RISIKO-ERMITTLUNG AKTIV) then the Bluetooth signals are being sent/received and exposures are being logged.

> Question 2: Even if the app says "Exposure loggin 11 out of 14 days active" tomorrow at update time, it did count the keys it could get while I was in the supermarket. Is that right?

Unfortunately the app is not good at recording and displaying the time if you've had exposure logging disabled. I had the same thing when I got green warnings which I couldn't explain and I decided to turn off exposure logging for a few days except when I was outside my flat. The app was telling me that complete days were missing, when this definitely was not true. To improve this, it would mean Apple / Google keeping track of the time each day that exposure logging is on, then passing that back to the app. I haven't heard anything about that type of enhancement being considered though. 

(I'm sure that @daimpi will add to my comments if necessary!)

**Comment by A-speaking** [comment]
> 
> 
> @A-speaking
> 
> > Question 1: The App does track the bluetooth-signals found in the 2 hours I was outside, right? Even though bluetooth was turned off for 22 hours?
> 
> So long as the app is showing EXPOSURE LOGGING ACTIVE (or in German RISIKO-ERMITTLUNG AKTIV) then the Bluetooth signals are being sent/received and exposures are being logged.
> 
> > Question 2: Even if the app says "Exposure loggin 11 out of 14 days active" tomorrow at update time, it did count the keys it could get while I was in the supermarket. Is that right?
> 
> Unfortunately the app is not good at recording and displaying the time if you've had exposure logging disabled. I had the same thing when I got green warnings which I couldn't explain and I decided to turn off exposure logging for a few days except when I was outside my flat. The app was telling me that complete days were missing, when this definitely was not true. To improve this, it would mean Apple / Google keeping track of the time each day that exposure logging is on, then passing that back to the app. I haven't heard anything about that type of enhancement being considered though.
> 
> (I'm sure that @daimpi will add to my comments if necessary!)

Thank you for your reply! That is ecactly what I want to know:

Does the app consider the keys logged while I was outside and turned on my bluetooth, even if it was just 2 hours? Or is the whole day missing then?

**Comment by MikeMcC399** [comment]
@A-speaking 
> Does the app consider the keys logged while I was outside and turned on my bluetooth, even if it was just 2 hours? Or is the whole day missing then?

It will consider everything that it recorded, even if that is only two hours. If I look at my exposure check history it shows it checked the keys every day for the past 16 days even if the display of the app tells me it was active for only 10 of the past 14 days. So that display is just misleading. I don't think you need to worry about this. If you had Bluetooth and the app activated whilst you were out, it will have been recording. It's the same problem if you reset the app, or if you were using an app from another country for part of the last 14 days. The keys are still saved and used, but the CWA may give a misleading count of days.

**Comment by A-speaking** [comment]
@MikeMcC399 Thank you so much for that clear answer, I was super confused and didn't want to destroy the loggin. Thank you for taking the time to explain.

**Comment by heinezen** [comment]
Hello everyone and @A-speaking ,

I hope the community could address all of your questions. Since your questions are answered, I'll close this issue to mark it as solved.

One small request for future questions: Please make the topic of your question also the title of the issue. Then others who have the same question can find it and all the answers by using the Github search. I have updated the title for this issue for you.

Regards,
CH

----
Corona-Warn-App Open Source Team
