### ISSUE TITLE
Out of date Risk Assessment document

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#453]
## Where to find the issue

Document title 
**How does the Corona-Warn-App identify an increased risk?** found on
https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md

and translated document title
**Wie ermittelt die Corona-Warn-App ein erhöhtes Risiko?**
https://github.com/corona-warn-app/cwa-documentation/blob/master/translations/cwa-risk-assessment.de.md

## Describe the issue

The document [cwa-risk-assessment.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md) makes no mention of the use of the onset of symptoms date which is used in the submission process starting from Version 1.5 of the CWA app. In the example, Anton's and Aisha's submissions on different days are treated differently although their symptoms started on the same day. They should now be treated the same in terms of the start date, even though the test results are submitted on different days.

According to the blog entry "Start of Symptoms" date or range of dates is now a possible captured parameter in the test result submission process.
**New features: Corona-Warn-App Version 1.5 is now available for download**
Janina Hoerdt on October 19, 2020
https://www.coronawarn.app/en/blog/2020-10-19-version-1-5/
Section "Symptom Recording" including the set of submission screen shots:

![submission screen shots](https://www.coronawarn.app/assets/img/blog/2020-10-19-version-1-5/symptoms_en.jpg)

## Suggested change
The document should explain how the onset of symptoms information is used in assessing risk.

Edit:
The document has become completely out-of-date due to the release of CWA 1.9 on Dec 9, 2020 using v2 / Exposure Window mode for Exposure Risk calculations.

The document now includes a temporary header with the following information:

---
**Later calculation improvements**

Improvements to the risk assessment calculations were made in app versions [V1.5 (Symptom Recording)](https://www.coronawarn.app/en/blog/2020-10-19-version-1-5/) and [V1.9 (Exposure Notification Framework v2)](https://www.coronawarn.app/en/blog/2020-12-16-corona-warn-app-version-1-9/) after this document was published. The FAQ section [Risk Assessment](https://www.coronawarn.app/en/faq/#risk_assessment) answers related questions.

---
Internal Tracking ID: [EXPOSUREAPP-3548](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3548)

**Comment by heinezen** [comment]
Hey @MikeMcC399 

Thanks for pointing out the inconsistency. I have created a Jira ticket (EXPOSUREAPP-3548) to address the missing information in the risk assesment docs. The devs will now have a look at the documentation and update it accordingly.

CH

----
Corona-Warn-App Open Source Team

**Comment by SebastianWolf-SAP** [comment]
Needs to be addressed together with #426.

**Comment by MikeMcC399** [comment]
The app itself, in the detailed risk card "Risk of Infection" section, refers to FAQ entry https://www.coronawarn.app/en/faq/#encounter_but_green which in turn refers to https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md.

So CWA users are currently being led to out-of-date reference material.

**Comment by MikeMcC399** [comment]
It would be good to get this central piece of documentation updated. Is there any news?

**Comment by dsarkar** [comment]
Dear @MikeMcC399,

I had a quick look at the internal ticket: The information will be updated in coordination with the RKI.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
Now with the release of CWA 1.9 (see https://www.coronawarn.app/en/blog/2020-12-16-corona-warn-app-version-1-9/) the [cwa-risk-assessment.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md) document (and German translation [cwa-risk-assessment.de.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/translations/cwa-risk-assessment.de.md)) needs to be updated to cover the transition to [Apple's v2 Exposure Notification Framework](https://developer.apple.com/documentation/bundleresources/information_property_list/enapiversion) and [Google's Exposure Notification System Exposure Window Mode](https://developers.google.com/android/exposure-notifications/exposure-notifications-api#rationale) which replaces the Legacy v1 mode.

**Comment by MikeMcC399** [comment]
Happy New Year everybody! 🥳 

@tklingbeil 
Can we get the risk assessments documents updated please so they describe the v2 implementation?

- [cwa-risk-assessment.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md)
- [cwa-risk-assessment.de.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/translations/cwa-risk-assessment.de.md)

It looks like the links to the configuration files at the bottom of the document are also obsolete.

Congratulations for your great presentation at rC3!

[Blog entry](https://www.coronawarn.app/en/blog/2020-12-30-cwa-behind-the-scenes/) which links to:

- [Risk calculation slides](https://www.coronawarn.app/assets/documents/cwa-rc3.pdf)
- [YouTube video](https://youtu.be/TIXsOIrp1dg)

**Comment by dsarkar** [comment]
@MikeMcC399  Happy New Year ! I forwarded your message to devs/tklingbeil. Best, DS

**Comment by tklingbeil** [comment]
@MikeMcC399 

A happy new year to you as well and thank you for the feedback on the session!

We will definitely update the various components of the documentation, so that the adapted risk calculation (as well as some other things) are properly represented there.

**Comment by MikeMcC399** [comment]
@tklingbeil 
> We will definitely update the various components of the documentation, so that the adapted risk calculation (as well as some other things) are properly represented there.

If the update to the documents is delayed, could we get a note added at the top of the document to cover the immediate future? That should explain:
- The document is under revision
- Improvements were made in v1.5 and v1.9 of the app to increase the accuracy of the risk assessment
- The FAQ article https://www.coronawarn.app/en/faq/#encounter_19_calc contains a summary of the risk assessment in app version 1.9 and later

Both the English language and German language documents are affected:

- https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md
- https://github.com/corona-warn-app/cwa-documentation/blob/master/translations/cwa-risk-assessment.de.md

I can submit a PR for this change if that would be helpful.

**Comment by MikeMcC399** [comment]
I have submitted PR #513 to bridge the gap until the documents can be fully updated.

**Comment by MikeMcC399** [comment]
The risk assessment description in the [Solution Architecture Document](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md) is based on v1 risk calculations. This document also needs updating to cover v2 risk calculations.

**Comment by dsarkar** [comment]
@MikeMcC399 Added your comment to the ticket. Thanks.

**Comment by MikeMcC399** [comment]
@dsarkar 
I noticed that the label changed to Fix 1.14, so the date for revising the documents has been pushed back once again. In the meantime the published documents are getting even more out of date.

Please consider either:

- merging PR #513 or
- at least adding a note to the existing documentation saying that it is out-of-date

**Comment by Ein-Tim** [comment]
Version 1.14 has been released. The Risk Assessment document seems to be still out of date, or?

**Comment by dsarkar** [comment]
@MikeMcC399 I think the team is extremely busy with all the new releases and changes. I will raise this issue again.

**Comment by dsarkar** [comment]
@MikeMcC399 Yes, please, re-submit the PR and we will merge it. Many thanks.

**Comment by MikeMcC399** [comment]
@dsarkar 
> Yes, please, re-submit the PR and we will merge it. Many thanks.

Done. It is PR https://github.com/corona-warn-app/cwa-documentation/pull/546

**Comment by MikeMcC399** [comment]
PR #546 is now merged.

**Comment by MikeMcC399** [comment]
@dsarkar 
This item has the Fix 1.15 label applied to it, however there has been no update published for the document and the app version 1.15 has been released today.

Is there any news on the plan to update the document?

**Comment by dsarkar** [comment]
@MikeMcC399 Internal Ticket says release 2.0.

**Comment by MikeMcC399** [comment]
The risk assessment documents:

**How does the Corona-Warn-App identify an increased risk?**
https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md
and
**Wie ermittelt die Corona-Warn-App ein erhöhtes Risiko?**
https://github.com/corona-warn-app/cwa-documentation/blob/master/translations/cwa-risk-assessment.de.md

which describe a core function of the CWA app have been waiting for an update for the past 6 months. Updates are made necessary, firstly due to the introduction of Onset of Symptoms followed by the transition from v1 to v2 / ExposureWindow mode, thereafter with continual optimization of risk assessment parameters using v2 / ExposureWindow mode.

The label on this issue is "Fix 2.0" and the app version 2.0.x was released today, April 21, 2021, so that implies that the documents will now be republished. 

I cannot see any update so far. Please revise the planning information if the documents will not be updated this week.

**Comment by dsarkar** [comment]
@MikeMcC399 Will try to get info. Thanks.

**Comment by MikeMcC399** [comment]
The [risk assessment document](https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md) does not includes information about how risks resulting from using [Event Registration](https://github.com/corona-warn-app/cwa-documentation/blob/master/event_registration.md), introduced in CWA 2.0, are assessed. This is described in FAQ https://www.coronawarn.app/en/faq/#check_in_qr_warning.

**Comment by ndegendogo** [comment]
Thanks @MikeMcC399 for linking this information here.

**Comment by MikeMcC399** [comment]
The [Solution Architecture document, Section: Risk Calculation](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#risk-calculation) discusses the use of Onset of Symptoms data for risk assessment. This is not mentioned in the [cwa-risk-assessment.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md) document. At least there should be a cross-reference added from the [cwa-risk-assessment.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md) document to the [Solution Architecture](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#risk-calculation) document if the [cwa-risk-assessment.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md) is not going to be otherwise updated.

**Comment by MikeMcC399** [comment]
- According to PR #829 the document:

**How does the Corona-Warn-App identify an increased risk?** found on
https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md

is to be deprecated, and by implication the translated document also:

**Wie ermittelt die Corona-Warn-App ein erhöhtes Risiko?**
https://github.com/corona-warn-app/cwa-documentation/blob/master/translations/cwa-risk-assessment.de.md

Once the documents have had a deprecation notice added, then this issue can be closed.

The replacement is the [Solution Architecture document, section Mobile Applications](https://github.com/corona-warn-app/cwa-documentation/blob/main/solution_architecture.md#mobile-applications).

**Comment by mlenkeit** [comment]
@MikeMcC399 can we close this issue because of #829?

**Comment by MikeMcC399** [comment]
This issue is now resolved. See previous https://github.com/corona-warn-app/cwa-documentation/issues/453#issuecomment-1027193110.
