### ISSUE TITLE
Pimp My CWA

### ISSUE THREAD

**Issue by RickorDD** [corona-warn-app/cwa-documentation#454]
regarding this article and UKW040 podcast...
https://www.zeit.de/digital/2020-08/corona-warn-app-coronavirus-eindaemmung-karl-lauterbach-henning-tillmann

Where is a good opportunity to discuss again how to make the CWA even cooler and the generation "app" which still wants to celebrate, but also thereby drives the infection back up. CWA as Gamification?

**Comment by Ein-Tim** [comment]
Hi, maybe you could close this Issue here and open a new one in the https://github.com/corona-warn-app/cwa-wishlist Repo and also give some more Information what Features Exactly you want.
