### ISSUE TITLE
Inconsistent number of risk encounters (on iOs 13.6.1)

### ISSUE THREAD

**Issue by NKlein96** [corona-warn-app/cwa-documentation#455]
Hello, the number of risk encounters in the notification window and in the app are different. The term "potential exposures" in the notification is equivalent to "risk encounters" in the app, isn't it? (See attached images)

Before, the two displays were always consistent. Yesterday I only had two risk encounters, I am confused which number is now true.

btw: Thanks for your work!

![00254d30-f9d0-4a1a-a414-ec330926a60a](https://user-images.githubusercontent.com/17847870/97712199-6bd28800-1abe-11eb-825d-87e5669b6316.jpg)

![346b0c93-b70a-46ee-9d43-4a39bb4aadda](https://user-images.githubusercontent.com/17847870/97712245-79880d80-1abe-11eb-9217-928eac76ec31.jpg)

**Comment by Ein-Tim** [comment]
Please see: https://github.com/corona-warn-app/cwa-app-ios/issues/1096 and close this Issue.
(This problem is solved with iOS 13.7 and above)
