### ISSUE TITLE
[Fix 1.9] Bad translation for roaming charges in EU under Transnational Exposure Logging

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#457]
## Where to find the issue
`interoperability_configuration_second_section`
https://github.com/corona-warn-app/cwa-app-android/blob/master/Corona-Warn-App/src/main/res/values-en/strings.xml
Line 1313

This text is shown in CWA Android using:
EXPOSURE LOGGING ACTIVE > Transnational Exposure Logging then scroll down just before "The following countries currently participate in transnational exposure logging:"

## Describe the issue

The final part of the final sentence in the English translation of `interoperability_configuration_second_section` makes no sense:

"The daily download of the list with the random IDs is usually free of charge for you – you will not be charged for the data used by the app in this context, **will roaming charges apply for this in other EU countries.**"

This is the complete parapgraph:

<string name="interoperability_configuration_second_section">"To do this, the app downloads a list, which is updated daily, of the random IDs of all users who have shared their random IDs via their own app. This list is then compared with the random IDs recorded by your smartphone. The daily download of the list with the random IDs is usually free of charge for you – you will not be charged for the data used by the app in this context, **will roaming charges apply for this in other EU countries.**"</string>

Compare to German text:

<string name="interoperability_configuration_second_section">Hierfür lädt die App täglich eine aktuelle Liste mit den Zufalls-IDs aller Nutzer herunter, die diese über ihre App geteilt haben. Diese Liste wird dann mit den von Ihrem Smartphone aufgezeichneten Zufalls-IDs  verglichen. Der tägliche Download der Liste mit den Zufalls-IDs ist für Sie kostenlos – Ihr Datenvolumen wird nicht belastet und es fallen im europäischen Ausland keine Roaming-Gebühren an.</string>
    

## Suggested change
"The daily download of the list with the random IDs is usually free of charge for you – you will not be charged for the data used by the app in this context, and no  roaming charges apply for this in other EU countries."

---
8 Dec 2020 UPDATE regarding next release:

With Android, the translation has been adapted as stated by you in your comment.
With iOS, the translation has not yet been adopted.

---
Internal Tracking ID: [EXPOSUREAPP-4092](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4092)

**Comment by Ein-Tim** [comment]
Related: 
Please don't forget to change the text here with 1.7.0 which huggers the frequency of Risk Checks (all 4 hours)

**Comment by dsarkar** [comment]
@MikeMcC399, could you please check that this issue persists with CWA version 1.6.1? Thanks.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@dsarkar 
The issue is still apparent in CWA Android 1.6.1. Nothing has been changed.

**Comment by dsarkar** [comment]
@MikeMcC399, now in 1.7.1 fixed?

**Comment by MikeMcC399** [comment]
@dsarkar 
> now in 1.7.1 fixed?

You keep asking me if it is fixed, but it is clear in
`interoperability_configuration_second_section`
https://github.com/corona-warn-app/cwa-app-android/blob/master/Corona-Warn-App/src/main/res/values-en/strings.xml
Line 1356
that it is not fixed:

<string name="interoperability_configuration_second_section">"To do this, the app downloads a list, which is updated daily, of the random IDs of all users who have shared their random IDs via their own app. This list is then compared with the random IDs recorded by your smartphone. The daily download of the list with the random IDs is usually free of charge for you – you will not be charged for the data used by the app in this context, **will roaming charges apply for this in other EU countries**."</string>
   
I have also confirmed on CWA 1.7.1 Android with the mobile device set to language English (United Kingdom). The same for English (United States).

Did you check with your translation team what they are doing about this error? The last sentence in English just doesn't make sense, unlike the equivalent German text which I included in the original issue posting https://github.com/corona-warn-app/cwa-documentation/issues/457 and which does make complete sense.

**Comment by dsarkar** [comment]
@MikeMcC399, We will forward this to the developers.  Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
STATUS UPDATE (8 Dec 2020) regarding next release:

With Android, the translation has been adapted as stated by you in your comment.
With iOS, the translation has not yet been adopted.

DS

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@dsarkar 
>With Android, the translation has been adapted as stated by you in your comment.

I can't see any change in:
https://github.com/corona-warn-app/cwa-app-android/blob/release/1.8.x/Corona-Warn-App/src/main/res/values-en/strings.xml

which still contains the incorrectly translated string:

<string name="interoperability_configuration_second_section">"To do this, the app downloads a list, which is updated daily, of the random IDs of all users who have shared their random IDs via their own app. This list is then compared with the random IDs recorded by your smartphone. The daily download of the list with the random IDs is usually free of charge for you – you will not be charged for the data used by the app in this context, **will roaming charges apply for this in other EU countries.**"</string>

It seems that the issue has not been corrected until the strings for the upcoming 1.9.x release which contains significantly re-written text under `interoperability_configuration_second_section`.

https://github.com/corona-warn-app/cwa-app-android/blob/release/1.9.x/Corona-Warn-App/src/main/res/values-en/strings.xml

<string name="interoperability_configuration_second_section">"To do this, the app downloads lists, which are updated daily, of the random IDs of all users who have shared their test results to warn others via their own app. This list is then compared with the random IDs recorded by your Android smartphone. The downloads of the lists of random IDs are usually free of charge for you. Specifically, this means that mobile network operators do not charge you for the data used by the app in this context, nor do they apply roaming charges for this in other EU countries. Please contact your mobile network operator for more information."</string>


Perhaps you could check if the corrected text in release/1.9.x could be backported to release/1.8.x?

**Comment by dsarkar** [comment]
@MikeMcC399, ok, hopefully will come back with news release/1.9.x and release/1.8.x soon. DS

**Comment by MikeMcC399** [comment]
Please ignore my comment about Version 1.8.x since the blog https://www.coronawarn.app/en/blog/2020-12-16-corona-warn-app-version-1-9/ says that Version 1.9 is being released, implying that Version 1.8 is being skipped for general release.

**Comment by Ein-Tim** [comment]
Seems fixed for iOS (v1.9.1):
![image](https://user-images.githubusercontent.com/67682506/102388843-9a56e480-3fd2-11eb-84a9-b1f86456b103.png)

**Comment by MikeMcC399** [comment]
Confirmed fixed in CWA Android 1.9.1.

**Comment by dsarkar** [comment]
@MikeMcC399, @Ein-Tim Thanks for feedback and closing. DS
