### ISSUE TITLE
Connection Details

### ISSUE THREAD

**Issue by harbourlad** [corona-warn-app/cwa-documentation#458]
## Your Question

* Documentation File:
* Line / Paragraph:
* Question:
Our employees use the CWA at their different mobile (IOS, Android) within our company WiFi and get an error message regarding the internetconnection. We suppose a firewall issue and now we want to allow all devices wirthin our Wifi to etsablish the neccessary connection. But we can't find any information about where the CWA wants to connect to. Are there one or more specific URL's or IP's for which we can create specific exception rules on the firewall in order to ensure the trouble-free functioning of the CWA on various end devices?

**Comment by Ein-Tim** [comment]
Hey @harbourlad, since I'm only a Community member I can't tell you very specific things but it seems like [custom SSL Certificats are not accepted by CWA](https://github.com/corona-warn-app/cwa-app-ios/issues/1117#issuecomment-687223851).

**Comment by harbourlad** [comment]
Yes - I also assume that it has something to do with intercepting SSL certificates. It would not be the first app that does not accept such a procedure on the part of our firewall. That's why I want to provide an exception - but I need to know **which endpoint the connection is against,** so I can create an exception for a connection against this endpoint

**Comment by heinezen** [comment]
Hey @harbourlad ,

I think you can find the endpoints you are looking for in [this documents](https://github.com/corona-warn-app/cwa-documentation/blob/master/backend-infrastructure-architecture.pdf). Check Section 3.2.5, there should be a full list of the domains.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@harbourlad 
You can start by checking that you can access the human-readable website https://www.coronawarn.app/en/ via WiFi.

**Comment by harbourlad** [comment]
Hi all,
I think my question is answered :-)
I added a Wildcardexception ***.coronawarn.app** and everything seems to work fine now - thank you very much.
