### ISSUE TITLE
Test status - data being retrieved in a loop

### ISSUE THREAD

**Issue by ci08** [corona-warn-app/cwa-documentation#461]
I uploaded a negative test on 16 Oct and until last week, it was displaying correctly in the app. However, it now says "Data being retrieved - Your result is being updated" and it keeps looping around. I assume the negative test result has been archived but now I cannot upload a new test as there is no way to break out of the loop.
App version is 1.6

**Comment by MikeMcC399** [comment]
Hi @ci08 

Are you using Android? If yes, there is a hot topic to be found under https://github.com/corona-warn-app/cwa-app-android/issues/1084. 

Again, if Android, you can try the workaround from https://github.com/corona-warn-app/cwa-app-android/issues/1084#issuecomment-719928037.

**Comment by ci08** [comment]
Yep, it is android. I will check those links, thanks!

**Comment by ci08** [comment]
I set the time on the phone back one day, then reset the app and switched time back to automatic update. It cleared the Data is being retrieved message and my exposures in the last 14 days remain.
Thanks for the help!

**Comment by MikeMcC399** [comment]
@ci08 
> I set the time on the phone back one day, then reset the app and switched time back to automatic update. It cleared the Data is being retrieved message and my exposures in the last 14 days remain.

It's good to hear that the workaround was successful, also on the latest version 1.6!

Would you like to close this issue now?

**Comment by ci08** [comment]
Yes, closing this ticket now. Hopefully a fix will be available in a future update!
