### ISSUE TITLE
Creating a honeypot to collect exposure information at a fixed site. Could it make sense?

### ISSUE THREAD

**Issue by Tobias333** [corona-warn-app/cwa-documentation#464]
At our university, entrance is currently through narrow gates to register people entering the buildings. Would it make sense to place Bluetooth enabled Android devices next to the gates to obtain statistical information on numbers and trends of corona-positive people passing through? What are the technical and privacy considerations relevant to such a project? Are there stats on how often a "positive" device has to be walked past for a receiver to obtain a "warning"?

I am asking as a private person pondering whether to suggest this to my university. It seems that my wife has recently picked up "low risk" warnings worth in the range of 5 or 10% of the daily number of positive diagnoses in our town, simply by waiting some time for a take-out at a heavily trafficked spot. This made me think that there might be some relevant public health information to be gleaned from placing some strategic honeypots. But given the design of its infrastructure, repurpusing the app in this way might be too expensive for the expected benefit.

**Comment by heinezen** [comment]
Hey @Tobias333 ,

We provide extensive technical documentation on the inner workings of the CWA in this repository ([Link](https://github.com/corona-warn-app/cwa-documentation#technical-documentation)). This should help you answer what technical considerations are relavant. The specific privacy considerations would depend on the practical implementation of the project and guidelines of your university, so we cannot comment on that.

> Are there stats on how often a "positive" device has to be walked past for a receiver to obtain a "warning"?

Documentation of the risk score/warning calculations can be found here: https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#risk-score-calculation

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@Tobias333 

If your question here is answered, please close this issue.

**Comment by Tobias333** [comment]
Oops, sorry. Not answered, of course, but given the fact that, because of lockdowns, there is minimal traffic at the organization I had in mind, this project has not been pursued. So I close it, thanks.
