### ISSUE TITLE
Exposure Logging is in false "restricted" state without internet connection

### ISSUE THREAD

**Issue by kbobrowski** [corona-warn-app/cwa-documentation#465]
Note: this is a different issue to corona-warn-app/cwa-app-android#491 and can be solved independently.

## Describe the bug

When there is no internet access exposure logging will go to "restricted" state, the same state which appears when Bluetooth is off. But even without internet access phones will still receive / send Bluetooth beacons, and they can be matched later on with Diagnosis Keys (once internet access is enabled again).

This looks like sub-optimal UI/UX design, and leads to following issues:

- a person without mobile data enabled might believe that it does not make sense to take the phone or turn on Bluetooth when going e.g. grocery shopping, since exposure logging is not active anyway without internet access
- a person taking a flight might be led to believe that it does not make sense to turn on Bluetooth (after both internet access and Bluetooth have been turned off by airplane mode), since without internet the app won't work anyway (as a side note - it's possible to safely switch on Bluetooth after airplane mode was activated - some people may not know about this, perhaps it'd be good to indicate it in the app as well)
- **user has no way to opt-out (stop transmitting BLE beacons) once phone has internet connection disabled**

## Expected behaviour

It should be clear for the user that even without internet access app is working (it just needs internet access from time to time), and it's still worth to always carry a phone / keep Bluetooth on even in a situations without internet access.

**Additionally, user should be able to opt-out at any time, regardless of whether internet access is enabled, as stated in privacy policy:**

> To withdraw your consent to the exposure logging feature, you can disable the feature
using the toggle switch in the App or delete the App.

## Possible Fix

Better UI/UX design with two separate states:
- state indicating if exposure logging is on (this requires Bluetooth)
- state indicating if exposure risk score is up-to-date (this requires internet)

---
Internal Tracking ID: EXPOSUREAPP-1572

**Comment by dsarkar** [comment]
Dear @ndegendogo, @kbobrowski, @Ein-Tim,

Any feedback regarding this issue on the CWA version 1.7.1?

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@dsarkar Seems fixed for me 👍

**Comment by ndegendogo** [comment]
@dsarkar same for me. I could no longer reproduce the contradicting and confusing messages with cwa 1.7.1

Thanks

**Comment by dsarkar** [comment]
Hi @ndegendogo, @kbobrowski, @Ein-Tim, @kbobrowsk, and community,

Thanks for the feedback and contributions. We will close this issue now.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
_Cross Link_

New Issue in the iOS Repo about this: https://github.com/corona-warn-app/cwa-app-ios/issues/1627

**Comment by ndegendogo** [comment]
@Ein-Tim IMO cwa-app-ios#1627 is not a duplicate but a different focus. See [more detailed explanations](https://github.com/corona-warn-app/cwa-app-ios/issues/1627#issuecomment-738666442)

**Comment by Ein-Tim** [comment]
@ndegendogo 

Sorry, don't wanted to say that your new Issue is a duplicate. Just wasted to point it out so if other people experience this they can find your Issue better 👍
