### ISSUE TITLE
Unnecessary delay in exposure notification due to delayed fetching of Diagnosis Keys?

### ISSUE THREAD

**Issue by kbobrowski** [corona-warn-app/cwa-documentation#466]
Current API allows for querying days on which Diagnosis Keys became available:

```bash
$ date +%Y-%m-%d
2020-06-13

$ curl https://svc90.main.px.t-online.de/version/v1/diagnosis-keys/country/DE/date
["2020-06-09","2020-06-10","2020-06-11","2020-06-12"]
```

Apps use this endpoint to [check if these dates are already in cache](https://github.com/corona-warn-app/cwa-app-android/blob/98218c7c01feb1cb0644e3032841157c59dcab40/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CachedKeyFileHolder.kt#L97), and if not to download Diagnosis Keys for missing days using endpoint:

```bash
$ curl https://svc90.main.px.t-online.de/version/v1/diagnosis-keys/country/DE/date/2020-06-12 --output diagnosis_keys_2020-06-12.zip
```

Let's assume a scenario where someone had contact with infected person. Infected person uploads Diagnosis Keys on 2020-06-12, but these Diagnosis Keys are bundled into package that is only available to download on 2020-06-13. This introduces a day of delay, during which a person who had contact with diagnosed person is unaware of this contact and is not able to self-isolate, potentially endangering people around.

Interestingly it seems to be possible to get Diagnosis Keys uploaded on current day, but only using hour API endpoint:

```bash
$ curl https://svc90.main.px.t-online.de/version/v1/diagnosis-keys/country/DE/date/2020-06-13     
<!-- error -->

$ curl https://svc90.main.px.t-online.de/version/v1/diagnosis-keys/country/DE/date/2020-06-13/hour
[3,8,10,12]

$ curl https://svc90.main.px.t-online.de/version/v1/diagnosis-keys/country/DE/date/2020-06-13/hour/12 --output diagnosis_keys_2020-06-13_12.zip
```

This endpoint seems to be only used in a function which is [marked to be dropped before release](https://github.com/corona-warn-app/cwa-app-android/blob/98218c7c01feb1cb0644e3032841157c59dcab40/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CachedKeyFileHolder.kt#L142). Functionality to fetch hours for current day existed, but it was removed in [this pull request](https://github.com/corona-warn-app/cwa-app-android/pull/185).

**Is there a reason not to continuously download Diagnosis Keys which are being made available during current day, and instead wait until package for complete day is ready?**

As far as I understand this would not introduce any privacy issues since they are already handled by upload mechanism [documented here](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#upload-schedule-for-diagnosis-keys), and would just let people know faster that they were exposed. Privacy of this solution can also be confirmed by looking at latest Diagnosis Key in each bundle, e.g. in a bundle from current day (2020-06-13, hour 12) latest Diagnosis Key has interval number 2653200, meaning it was generating RPIs yesterday:

```bash
$ TZ="utc" date -d@$((2653200 * 600)) +"%Y-%m-%d %H:%M"
2020-06-12 00:00
```
---

Internal Tracking ID:  EXPOSUREAPP-1567

**Comment by Ein-Tim** [comment]
CWA Version 1.7.0 (under Android: https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.7.0) and CWA Version 1.7.1 (under iOS: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.7.1) were released today which introduce key fetching all 4 hours (if the phone is connected to the internet via Wi-Fi)

**Comment by dsarkar** [comment]
Dear community,

Regarding the update to CWA 1.7: Please note that it is a staged rollout. Over the next two days, 100% of the users should have received the update.
  
We would appreciate very much your feedback regarding this issue over the next few days!

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by cfritzsche** [comment]
I am seeing background updates spaced 4 hours apart which is excellent. I didn't see yet if the hourly endpoint is checked though.

Thanks for finally making this work with all parties :-)

**Comment by ndegendogo** [comment]
@cfritzsche you have Android, yes?

On iPhone we can see more details in the ENF log.
So I can confirm that I see the hourly files accumulating over the day. And for full days in the past loading the daily files as before.
And, as you said, every 4-5 hours such a check.

Thanks!

**Comment by cfritzsche** [comment]
Nope, iOS here. Why do you ask?

**Comment by ndegendogo** [comment]
> Nope, iOS here. 

@cfritzsche did you have a look at your ENF log file? Either export it as json, or click through it directly in the settings.

What do I see here:
1) on first level I see the timestamps of checks. I see these timestamps every 4-5 hours.
2) next level I see the list of key files. I identify them by their hash value, or by the number of keys.
3) The first 14 have large number of keys, like: 22000 / 19000 / 9000. They follow the same pattern as the 14 files before cwa 1.7:
every day the oldest was dropped, 13 were same as yesterday, and a fresh file added.
4) after this follow more files with smaller number of keys, like: 190 / 1500 / or even 0. Number of these files increments with every hour.

So the pattern is like expected for hourly files of today, and daily files for the past 14 days.
I did not download the files manually to verify their hash values.

**Comment by cfritzsche** [comment]
Thanks @ndegendogo . Actually isn't it waste to keep checking the old dailies after the first check of the day? Can they still be added to? Then TSIs concerns over infrastructure load were correct after all, the same daily keys are now downloaded by the same devices much more often.

**Comment by ndegendogo** [comment]
> Actually isn't it waste to keep checking the old dailies after the first check of the day?

@cfritzsche well, this is same behaviour as before 1.7.
I did not monitor the behaviour with regard to **download**. My assumption is that the previously downloaded key files can (and probably are) cached on the device, so they need not contribute to load on the server infrastructure.

As for exact reasons why the same files are checked over and over again, I can only guess:
* the check is always performed with newest risk parameter configuration. If these parameters change, the risk assessment may yield a different result than before.
* the key files are packaged according to day of upload; **not** according to day of contact. 
If you assume that the risk formula has an accumulating part across contacts at the same time ( *I am not 100% sure about this one* ) - then it is **essential** for correct risk calculation that you include **all** available contacts of a given timeframe.

**Comment by cfritzsche** [comment]
@kbobrowski can't we close this issue now with 1.7.1 out?

**Comment by dsarkar** [comment]
Dear @kbobrowski, and community,

Thanks to all for contributing here. We think that this issue has been mitigated with the latest release of CWA 1.7.1. As @cfritzsche suggests, we are about to close this issue. Thanks again.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Dear all,

Thanks again, we will close this issue now.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by ndegendogo** [comment]
As a (well, it's not a *proof*, but let's call it:) an *anecdotical indication* how fast the key distribution part can be now, let me refer to [this ticket](https://github.com/corona-warn-app/cwa-app-ios/issues/1675#issue-762857168):

> She had a red encounter pushed on her app on Monday, 7th of December, after a colleague of hers was diagnosed with Covid. (Said colleague had first symptoms on saturday, 28th, got tested a week after and got her results on monday 7th). 

**This is how it should be!**
**Thank you!**  👍
