### ISSUE TITLE
Travelling in other countries

### ISSUE THREAD

**Issue by cvaldera** [corona-warn-app/cwa-documentation#467]
## What is missing

An explanation of what happens when someone goes to another country. Will the application interact only with other german mobile phones?
Should an international traveler install one application per country? 
## Why should it be included

Because there are people who travel a lot in different countries for personal / professional reasons
## Where should it be included

---
Internal Tracking ID: EXPOSUREAPP-2888

**Comment by dsarkar** [comment]
Dear @cvaldera,

I think your question is answered. I will close this issue now. Should you have more questions on this topic, please don't hesitate and re-open this issue. Thanks again for contributing.

Best regards,
DS

Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
The FAQ https://www.coronawarn.app/en/faq/#interoperability_countries has been recently updated, and continues to be updated as more countries join into "Transnational Exposure Logging".

Also the [Solution Architecture](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md) document in this repository includes a section [Cross Border Interoperability](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#cross-border-interoperability).
