### ISSUE TITLE
Is data traffic excluded from a user's data plan?

### ISSUE THREAD

**Issue by hansamann** [corona-warn-app/cwa-documentation#47]
I am just digging in and would love to hear if there are discussions with mobile operators to exclude the data consumed for retrieving the list of infected people/ids from their data plans. 

What is the expected daily data volume? What are ways to compress the data pulled by each device. I guess we cannot use a differential pull as no "known" ids shall be uploaded for privacy reasons. 

I really think this is an important topic. Many would immediately uninstall the app if it eats their data allowance.

**Comment by SebastianWolf-SAP** [comment]
Unfortunately, we can't comment on anything about things affecting third parties - such as mobile operators. But we'll forward this question to our partners at Robert Koch-Institut and the German Federal Government as they are the clients and can probably answer this.

The questions regarding data volume and related aspects will be covered by the Architecture Document which we will release soon.
