### ISSUE TITLE
Extend your bug report template with entry for cwa version

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-documentation#477]
## Avoid duplicates

* [ ] This issue has not already been raised before
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

Your current bug reporting template is well structured and has also entries for iOS version and device type of the user. Only an entry for cwa version is missing in that template. So many users forget to provide this very useful information.

## Suggested Enhancement

Add entry for cwa version in the section 'Technical details'

## Expected Benefits

Users reporting a bug will hopefully not forget to provide this information.

**Comment by Ein-Tim** [comment]
@ndegendogo 
This was solved by https://github.com/corona-warn-app/cwa-app-android/pull/1831 and https://github.com/corona-warn-app/cwa-app-ios/pull/1666
