### ISSUE TITLE
The 'Thank you' view does not disappear after quarantine 

### ISSUE THREAD

**Issue by raphaelbeckmann** [corona-warn-app/cwa-documentation#481]
I know several devices, both Android and iOS, of different persons that still show the 'Thank you' view even months after the quarantine. The view tells the people that they are infectious but actually they are not.

While showing this view after the end of the quarantine, the app does not seem to cause false alarms as I found out.

I expect the app to go back to normal mode after 14 days.

**Comment by Ein-Tim** [comment]
@raphaelbeckmann 

This is intended, please see this FAQ Entry: https://www.coronawarn.app/de/faq/#recovered

**Comment by raphaelbeckmann** [comment]
Thank you!

**Comment by Ein-Tim** [comment]
No problem.
If you consider this as solved you, as the author of this Issue, can go ahead and close it. 

Have a nice week and stay safe!
