### ISSUE TITLE
[F-Droid] Update is missing

### ISSUE THREAD

**Issue by Freudentaumel** [corona-warn-app/cwa-documentation#483]
Hi there,

I still have version 1.7.1.2.

When will I get the current version?

Best thanks
Gerhard

**Comment by Ein-Tim** [comment]
@Freudentaumel 
You are using Android, or? If yes, please open a Issue in the Android Repo: https://github.com/corona-warn-app/cwa-app-android/issues/new?labels=bug&template=01_bugs.md

Please also keep in mind that the rollout under Android is a staged rollout, so users will get the update in "waves"...
See: https://www.coronawarn.app/en/blog/2020-12-16-corona-warn-app-version-1-9/

So if you maybe could wait a little bit longer, I think this will solve itself...

**Comment by MikeMcC399** [comment]
@Freudentaumel 

Could you confirm whether your app is called CORONA CONTACT TRACING GERMANY or  CORONA WARN APP? This is from the text displayed at the top of the screen when you start the app.

Did you get the app from the Google Play Store or from F-Droid?

I have only seen the version 1.7.1.2 in the CCTG variant which is not supported here.

The Google Play Store app version is available from https://play.google.com/store/apps/details?id=de.rki.coronawarnapp .

**Comment by Freudentaumel** [comment]
I have installed the CORONA CONTACT TRACING GERMANY App from F-Droid.

**Comment by MikeMcC399** [comment]
@Freudentaumel 
>I have installed the CORONA CONTACT TRACING GERMANY App from F-Droid.

In that case you would need to address your question to the CCTG repository.

https://github.com/corona-warn-app/cwa-app-android/issues/1483#issuecomment-734491614 mentions https://codeberg.org/corona-contact-tracing-germany/cwa-android

You might want to try there. Good luck!
