### ISSUE TITLE
Confusing pop-up for "DO NOT ACTIVATE" during onboarding

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#486]
## Where to find the issue
The pop-up is displayed during onboarding, if "DO NOT ACTIVATE" is selected.

## Describe the issue
The wording of the pop-up is confusing because it mixes up referring to the state of activation and the state of deactivation. For example, is the sentence "You can deactivate this feature at any time" referring to the act of deactivation or deactivating the deactivation (double negative)?

The style of the pop-up for "DO NOT ACTIVATE" does not match the style of the "ACTIVATE" pop-up in terms of title, display case for action labels and wording of back label.

"BACK" and "DO NOT ACTIVATE" do not match the corresponding labels on the activate pop-up
"Cancel" and "Turn on".

## Steps to reproduce
1. Open CWA app
2. If onboarding already carried out, then reset app (three-dot overflow menu > Settings > Reset App and confirm)
3. Tap "LET'S GET STARTED"
4. Tap "NEXT"
5. Tap "DO NOT ACTIVATE"

![image](https://user-images.githubusercontent.com/66998419/102878340-5c314900-4448-11eb-9daa-ac1cd9e9a27f.png)

## Current strings

`onboarding_tracing_dialog_headline`
<string name="onboarding_tracing_dialog_headline">"Authorization"</string>
`onboarding_tracing_dialog_body`
<string name="onboarding_tracing_dialog_body">"This means the Corona-Warn-App cannot send or receive notifications about your COVID-19 risk status. You can deactivate this feature at any time."</string>
`onboarding_tracing_dialog_button_positive`
<string name="onboarding_tracing_dialog_button_positive">"Do Not Activate"</string>
`onboarding_tracing_dialog_button_negative`
<string name="onboarding_tracing_dialog_button_negative">"Back"</string>

## Suggested change
`onboarding_tracing_dialog_headline`
"Do not activate COVID-19 exposure notifications?"
`onboarding_tracing_dialog_body`
"This means the Corona-Warn-App cannot send or receive notifications about your COVID-19 risk status. You can activate exposure notifications later."</string>

Display the action labels in mixed cased:
`onboarding_tracing_dialog_button_positive`
<string name="onboarding_tracing_dialog_button_positive">"Do Not Activate"</string>
`onboarding_tracing_dialog_button_negative`
change from "Back" to "Cancel".    

## Environment
Corona-Warn-App Version: 1.9.1

---
PR https://github.com/corona-warn-app/cwa-app-ios/pull/1874 
Internal Tracking ID: [EXPOSUREAPP-4452](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4452) obsolete
Internal Tracking ID: [EXPOSUREAPP-4862](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4862) completed

**Comment by Ein-Tim** [comment]
@MikeMcC399 Is the behavior under iOS the same or why did you open this Issue here in the documentation repo. 
Let me know if I should test the behavior under iOS. 👍

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> Is the behavior under iOS the same or why did you open this Issue here in the documentation repo.
Let me know if I should test the behavior under iOS.

I assumed that iOS would have the same problem, because I found similar strings in the iOS repo, but I can't check it. It would be great if you could see what happens on iOS and add your comments. Many thanks! 👍

**Comment by Ein-Tim** [comment]
Okay, iOS generally behaves like Android: 
<img src="https://user-images.githubusercontent.com/67682506/102885022-fdbd9800-4452-11eb-8d3c-0b4e8f0d032e.png" width="300">




<img src="xxx" width="300">

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Thanks for the screen shots! iOS is better than Android in terms of consistency, however the terms used are also interchanged between Activate & Enable. Also I find the same sentence "You can deactivate this feature at any time" confusing in both iOS and Android.

**Comment by heinezen** [comment]
Hello everyone,

Thank you for the report. I brought this to the attention of the developers by creating Jira ticket EXPOSUREAPP-4452. We will see how we can improve this message in the future.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Fix for iOS: https://github.com/corona-warn-app/cwa-app-ios/pull/1874

Labled for 1.13.0

**Comment by Ein-Tim** [comment]
This fix is included in the first RC of version 1.13 under iOS: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.13.0-RC1

**Comment by MikeMcC399** [comment]
I verified the pop-up correction in CWA Android 1.13.2 in English and German. Here is a screenshot of the new English text:

![Do not activate](https://user-images.githubusercontent.com/66998419/110235879-ed399b80-7f32-11eb-8b11-a21fb1202eec.png)

According to @Ein-Tim and the screenshot in https://github.com/corona-warn-app/cwa-app-ios/pull/1874 it should also be fixed in iOS now.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Can confirm the fix under iOS:

<img src="https://user-images.githubusercontent.com/67682506/110236322-6934e300-7f35-11eb-9266-2c6e39b670e1.jpeg" width="300">

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim Thanks for checking.

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399 Thanks for all the contributions!
