### ISSUE TITLE
What happens after the "Vielen Dank"-Modus? How can I mark myself as "cured"?

### ISSUE THREAD

**Issue by MapeRiptide** [corona-warn-app/cwa-documentation#487]
Hello, 
Sorry I didn't find an answer to my question, so I'm opening up a new Issue.

First of all, thanks for this app. In my case it really helped and worked as advertised. I was tested positive, got the TeleTan and the Warnings did go out all my friends who where close with me during the last 14 days. With correct dates and count and everything. Perfect!

Now my App is stuck in the "Vielen Dank" - Modus (see screenshots) which I guess will stay like this for a while? I didn't find out how long. Will it return automatically into the "normal" mode after 14 days? Or do I need to to something, so that it recognizes that I'm cured? Do I have to put in a negative test? 

And sorry if this has been asked, I tried to look here and to google it but to no success.

Thanks, 
Max

![IMG_1440](https://user-images.githubusercontent.com/74463713/103007628-0934c000-4534-11eb-9735-441e2cd876d6.PNG)

**Comment by Ein-Tim** [comment]
Please see: https://www.coronawarn.app/de/faq/?search=gesund#recovered

**Comment by MapeRiptide** [comment]
Well, that was easy. I wonder why I didn't see it.. Thanks.

**Comment by dsarkar** [comment]
@Ein-Tim THANKS ! Merry Christmas!
