### ISSUE TITLE
User consent for notifying contacts

### ISSUE THREAD

**Issue by wuerzebesser** [corona-warn-app/cwa-documentation#49]
**Situation:**
It is planned to obtain user consent on sending IDs, activating bluetooth, push-notifications when using the app for the first time only. (E01.03, E01.04, E01.05)
Later, and in case of a positive test, user have to give another consent to notify (warn) their contacts. (E06.03)

**Resulting behaviour:**
This means that a user can use the app, but can still refuse to notify contacts in case of a positive test. (E06.03)
Just by having this option, I'd expect a certain fraction of users aborting the process at this step for whatever reasons. Please consider that the user has already entered his positive test result in the app at this stage, which probably shows his/her intention to notify (warn) all relevant contacts.

**Suggestion:**
Wouldn't it make sense that the user gives this consent already when starting the app for the first time? (Along with the other consents?)

**Comment by danielburkard** [comment]
Hi,

at least in the iOS framework (https://developer.apple.com/documentation/exposurenotification/enmanager/3583725-getdiagnosiskeys) it’s only possible to request the past exposure keys with the users consent. 

**Each time you call this method, the system presents an interface requesting authorization.
**

Kind regards,
Daniel

**Comment by wuerzebesser** [comment]
Thanks for the fast response.
Has this already been decided? It is only mentioned under the 'Discussion' section:

> **Discussion**
Each time you call this method, the system presents an interface requesting authorization.

Thanks and best regards,
Christian

**Comment by danielburkard** [comment]
In the apple documentation, discussion is not to be understood as something that needs debate or consideration.  

[How to read Apple’s developer documentation](https://www.hackingwithswift.com/articles/167/how-to-read-apples-developer-documentation)

> The Discussion section details specific usage notes for this method. This is – nearly always – the most useful part of each page, because here is where you’ll see things like “Don’t call this method” or “Be careful when…”

**Comment by wuerzebesser** [comment]
Thanks again for the excellent reply.
I'll then close this issue.
Thanks and best regards,
Christian
