### ISSUE TITLE
Non-working link to https://www.pepp-pt.org/ (404 error)

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#490]
## Where to find the issue
Documents in this repository:
- [README.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/README.md)
- [glossary.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/glossary.md)

## Describe the issue
The documents:
- [README.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/README.md)
- [glossary.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/glossary.md)

contain failing links to the web site https://www.pepp-pt.org/ for the organisation Pan-European Privacy-Preserving Proximity Tracing (PEPP-PT).

The web site https://www.pepp-pt.org/ responds with a 404 file not found error, followed by a message "Looks Like This Domain Isn't Connected To A Website Yet!" from https://www.wix.com/.

CI checks for pull requests on https://github.com/corona-warn-app/cwa-documentation have been showing a broken link in [README.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/README.md) and [glossary.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/glossary.md) to https://www.pepp-pt.org/ since November 11, 2020.

See for instance https://github.com/corona-warn-app/cwa-documentation/runs/1385337934 line 317
[✖] c → Status: 404

## Suggested change
In the files [README.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/README.md) and [glossary.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/glossary.md) either
- remove the link to https://www.pepp-pt.org/ completely or
- replace the link to https://www.pepp-pt.org/ by a link to https://github.com/pepp-pt/pepp-pt-documentation 

The GitHub repository https://github.com/pepp-pt/pepp-pt-documentation is online and the [last commit](https://github.com/pepp-pt/pepp-pt-documentation/commit/8ba05287c349318a03837fe374fd949e60d4eaf8) there was on June 10, 2020. The GitHub repository contains a link to the https://www.pepp-pt.org/ site. Using the link to the GitHub repository instead of directly linking to https://www.pepp-pt.org/ would give a solution to the failing website link whilst preserving the documentation of the link to the original website.

**Comment by MikeMcC399** [comment]
Proposed PR https://github.com/corona-warn-app/cwa-documentation/pull/494 fixes this issue.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks.
