### ISSUE TITLE
Workflow checks.yml does not run on PRs submitted from forks

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#495]
## Where to find the issue
[checks.yml](https://github.com/corona-warn-app/cwa-documentation/blob/master/.github/workflows/checks.yml) in [.github/workflows](https://github.com/corona-warn-app/cwa-documentation/blob/master/.github/workflows)

and results of running this script shown in 
[Action menu item](https://github.com/corona-warn-app/cwa-documentation/actions) for this [CWA Documentation GitHub repository](https://github.com/corona-warn-app/cwa-documentation/)

## Describe the issue

[checks.yml](https://github.com/corona-warn-app/cwa-documentation/blob/master/.github/workflows/checks.yml) warns too late and pull requests can be merged without a warning appearing before merging.

When viewing historical [GitHub Actions](https://github.com/corona-warn-app/cwa-documentation/actions) you can see many red X instead of green ✔️ . The red X indicating a return error code from running the [workflow script](https://github.com/corona-warn-app/cwa-documentation/blob/master/.github/workflows/checks.yml).

[checks.yml](https://github.com/corona-warn-app/cwa-documentation/blob/master/.github/workflows/checks.yml) has been failing for several months. The underlying bad hyperlinks and extra whitespace in *.md documents have now been mitigated (see https://github.com/corona-warn-app/cwa-documentation/issues/492) and Checks currently runs without error. To avoid this situation in the future it would be good to review the workflow for optimisation potential.

## Suggested change

Review workflow to add a check on pull_request.

The [checks.yml script](https://github.com/corona-warn-app/cwa-documentation/blob/master/.github/workflows/checks.yml) in this repo triggers `on: [push]` whereas the [build.yml script](https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/build.yml) in the [corona-warn-app/cwa-website repo](https://github.com/corona-warn-app/cwa-website) repo triggers `on: pull_request`, which seems to work better. There were previously also some issues related to a forked repo which @svengabr sorted out in https://github.com/corona-warn-app/cwa-website/pull/601.

---
Internal Tracking ID: EXPOSUREAPP-4494

**Comment by heinezen** [comment]
I think it only fails for non-members of the Corona-Warn-App organization on Github. We had the same issue in cwa-website where PRs from external branches would trigger the CI, but it didn't report back. In this repo, it doesn't seem to trigger at all, probably because the branches are also not in the same repo. 

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
I have added a Jira ticket (EXPOSUREAPP-4494) for this problem. Someone from the dev team will investigate this.

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@heinezen 
Thank you for creating the Jira ticket!

It is not the same issue as the website. It was actually failing independently of whether the pull was coming from a Member or from a Community Contributor fork, because the underlying tests, such as for broken links, were failing.

I fixed all these points, and checks.yml is not failing any more, however if a future push contained a error that caused a failure of checks.yml it would not show as an error until the pull request had been completed.

Here is an example of a successful run on a pull request from (my) fork.
https://github.com/corona-warn-app/cwa-documentation/pull/494 => 
https://github.com/corona-warn-app/cwa-documentation/commit/28786647b566fd3a5e0263ccb60d833769ab2c4d =>
https://github.com/corona-warn-app/cwa-documentation/runs/1625248702

**Comment by MikeMcC399** [comment]
The latest merged pull request has caused a commit to be pushed which fails the markdownlint check.

https://github.com/corona-warn-app/cwa-documentation/pull/493 =>
https://github.com/corona-warn-app/cwa-documentation/commit/d677db79959cc172a2b2ffe5d9d682282d84ea77 =>
https://github.com/corona-warn-app/cwa-documentation/runs/1634788545 (failed Linting markdown)

Whilst this issue (https://github.com/corona-warn-app/cwa-documentation/issues/495) is in the process of being investigated, I would suggest testing future planned submissions locally before submitting a pull request.

Similar to the instructions in https://github.com/corona-warn-app/cwa-website/blob/master/README.md#development
1. For non-Member users, fork repository.
2. Clone repository to a local git copy.
3. Install [Node.js](https://nodejs.org/en/) (which includes npm).
3. In the cwa-documentation directory and in a bash shell execute
`npm ci`
to install packages defined in package.json.
4. To run the tests markdownlint, checklinks and format-spelling, execute the following  in the same directory as above
`npm run test`

For users who have forked the https://github.com/corona-warn-app/cwa-documentation repository:
1. Go to Settings in forked repository i.e. `https://github.com/<GitHub_Username>/cwa-documentation/settings`
2. In Actions, select "Allow all actions" and then Save.

This will allow the forked `https://github.com/<GitHub_Username/cwa-documentation/blob/master/.github/workflows/checks.yml` to run and to show a green tick or red cross corresponding to the result of running `checks.yml` when a push is made to the fork.

**Comment by heinezen** [comment]
Should be fixed. See https://github.com/corona-warn-app/cwa-documentation/pull/512 :)

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
Thank you! 

I see that https://github.com/corona-warn-app/cwa-documentation/commit/6b896b01e1c92ed98fc43d499c747d3504376728 changed https://github.com/corona-warn-app/cwa-documentation/blob/master/.github/workflows/checks.yml to trigger 
`on: pull_request`
instead of 
`on: [push]`
