### ISSUE TITLE
Transparent Control off saved Data at anytime?

### ISSUE THREAD

**Issue by JPRuehmann** [corona-warn-app/cwa-documentation#50]
## Your Question

* Documentation File:
* Line / Paragraph:
* Question:
Will it be possible to transparently Control the saved Data (Send IDs and Received IDs) at anytime?

**Comment by SebastianWolf-SAP** [comment]
Yes, you will be able to en- or disable the functionality or the whole app at any time. It is explicitly mentioned in our scoping document (currently only in German, see https://github.com/corona-warn-app/cwa-documentation/blob/master/translations/scoping_document.de.md#nutzung-im-regelprozess) and also in the [Exposure Notification FAQ](https://covid19-static.cdn-apple.com/applications/covid19/current/static/contact-tracing/pdf/ExposureNotification-FAQv1.1.pdf) by Apple and Google. 

Please also see this FAQ for related aspect of data security and privacy of the Bluetooth keys as they are managed by the respective operating system. Moreover, we will outline more details how the operating systems and our apps will interact in the upcoming Architecture Document.

**Comment by JPRuehmann** [comment]
That is not what I am asking!
**I am asking if I can read the Data at any time.**
I had read the Documentation and the FAQs before im asking, but found nothing on that.
Thanks.

**Comment by niklas2810** [comment]
It would make no sense for you to read the cryptographic keys (from you or other people), as they contain no critical information.

Why would you want to access them?

**Comment by JPRuehmann** [comment]
First this is my thing if exactly this long List I want to be possible to read at any time.
If this makes sense is not your point of interest.
Or do you try to implement security by obscurity?
Than you can completely forget the App.

**Comment by ceedee666** [comment]
How is an open source development approach „security by obscurity“?

**Comment by niklas2810** [comment]
This has nothing to do with security by obscurity, as the list of IDs is not security-related. It would be an unnecessary feature, as this list - as I already pointed out - would bring no additional value to the user, but only expands development time and adds an additional, unnecessary button to the user interface. Therefore, I don't think that such a list would make sense. If you want to know how this list is generated, you can look it up in the specification. Seeing a list of random IDs just doesn't make sense to me. 

If you don't want to clarify your request that's okay, but then there's nothing to discuss about as well :smile:

**Comment by JPRuehmann** [comment]
If it is not security related why I can´t read it?
If it is neccessary or not is my thing.
I think it is Crucial to trust the App.

**Comment by JPRuehmann** [comment]
With this approach you will get 60% App usage guaranteed.

**Comment by niklas2810** [comment]
1. Because it would add unnecessary user interface which has to be developed by SAP (time=money).
2. You can look up how they are stored on GitHub. You don't need the app UI to validate this.
3. Most users won't care about or understand the implementation by Apple/Google, only an informed minority will bother. And this minority is also competent enough to go on GitHub and have a look there.

**Comment by danielburkard** [comment]
Hi,

by design of the frameworks from Apple and Google (and for privacy reasons), it is not possible for an app do get access to the identifiers a device has recorded. Access to identifiers the device has created is also restricted.

Kind Regards,
Daniel

**Comment by SebastianWolf-SAP** [comment]
Thanks for the clarification what you were referring to, @JPRuehmann. However, as @danielburkard mentioned, this requirement is in the domain of the libraries which are provided by Apple and Google. Please address this requirement to those two companies.
