### ISSUE TITLE
International hotline phone numbers in app

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#501]
## Your Question
According to https://github.com/corona-warn-app/cwa-website/issues/755 the international prefix has been removed from the technical and teleTAN hotline numbers (see for instance https://www.coronawarn.app/en/faq/#who_can_help).

What is happening with the phone numbers stored in the app?

In Android the overflow menu (three dots) > App Information > Technical Hotline
shows the phone number
+49 800 7540001

Similarly
Have you been tested? NEXT STEPS > no TAN yet? 
shows the phone number
+49 800 7540002

Related also to https://github.com/corona-warn-app/cwa-hotline/issues/5.

---
iOS PR https://github.com/corona-warn-app/cwa-app-ios/pull/1836
Android PR https://github.com/corona-warn-app/cwa-app-android/pull/2176

---
Internal Tracking ID: [EXPOSUREAPP-2566](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-2566) iOS
Internal Tracking ID: [EXPOSUREAPP-4677](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4677) Android

**Comment by dsarkar** [comment]
@MikeMcC399, yes, we are aware of the issue. Thanks. DS

**Comment by dsarkar** [comment]
Internal Tracking ID: EXPOSUREAPP-2566

**Comment by dsarkar** [comment]
+49 will be removed and wording will change slightly.

**Comment by dsarkar** [comment]
PR https://github.com/corona-warn-app/cwa-app-ios/pull/1836

**Comment by dsarkar** [comment]
Internal Tracking IDs:
[EXPOSUREAPP-2566](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-2566) iOS
[EXPOSUREAPP-4677](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4677) Android

**Comment by dsarkar** [comment]
Android PR https://github.com/corona-warn-app/cwa-app-android/pull/2176

**Comment by MikeMcC399** [comment]
In CWA 1.12.0 for Android this has been addressed.

To reproduce go through the following two sequences in the CWA app user interface:

- three-dot overflow menu > App Information > Technical Hotline shows phone number "0800 7540001"
- NEXT STEPS > No TAN yet? says "Call the nationwide hotline and request a TAN: 0800 7540002"

Both telephone numbers are now national telephone numbers as planned.

**Comment by ndegendogo** [comment]
So if I understsnd correctly these hotline numbers work only from Germany?
Is there also a way to get a TeleTAN from outside Germany? Or is that considered a cornercase and not supported?

**Comment by MikeMcC399** [comment]
@ndegendogo 
> So if I understsnd correctly these hotline numbers work only from Germany?
Is there also a way to get a TeleTAN from outside Germany? Or is that considered a cornercase and not supported?

The main topic for this is https://github.com/corona-warn-app/cwa-documentation/issues/502 and I asked more or less the same question as you did in https://github.com/corona-warn-app/cwa-documentation/issues/502#issuecomment-778251940.

**Comment by MikeMcC399** [comment]
If somebody would like to check that the phone numbers have been changed to local numbers in the iOS 1.12.x app I would go ahead and close this issue. I guess that the menus in iOS are identical to Android, except maybe that "NEXT STEPS" is in mixed case?


## Verification for Android

- overflow menu (three dots) > App Information > Technical Hotline
shows the phone number
0800 7540001

- Have you been tested? NEXT STEPS > no TAN yet?
shows the phone number
0800 7540002

**Comment by dsarkar** [comment]
@MikeMcC399 
@ndegendogo 

Yes, this is issue can be closed.
Both phone numbers shown as national numbers in iPhone

**Comment by dsarkar** [comment]
and we continue with  #502

**Comment by MikeMcC399** [comment]
@dsarkar 
Thank you for checking! Now closing, as suggested and agreed.
