### ISSUE TITLE
Questions on the downloaded keys

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-documentation#503]
I have two questions on the bundles of DEK keys that are distributed by the server.
1) There are two endpoints at the server, one with 'DE' and one with 'EUR'. What is the difference? They seem to distribute slightly different sets of keys.
Note: originally, I was thinking that the 'DE' endpoint distributes German-only keys, and the 'EUR' endpoint also from other countries. But the difference in their numbers seem too small for this assumption - or am I missing something?
2) Usually, the number of keys in the daily file matches the sum of all hourly files.
But yesterday (06 Jan 2021) there was a 'hickup' at the 'EUR' endpoint, and the number of keys did not match.
Why?

**Comment by ndegendogo** [comment]
I think I found now the answer to my first question [here](https://github.com/corona-warn-app/cwa-server#service-apis) in the specification file of the distribution service:
`/version/{version}/diagnosis-keys/country":` `"get":` *Get the origin country and the common package for which diagnosis keys are available. The common package contains all diagnosis keys from the origin country as well as the keys from the European Federation Gateway Service (EFGS).*
But this opens more questions:

3. Why are the differences between the `DE` package and the `EUR` package so small? Are there not more keys coming from the other European countries?
4. Are all German keys automatically federated to the EFGS, or is there some kind of filtering? (e.g. consent of the uploading user to the federation / information that said user has travelled / or similar)

**Comment by MikeMcC399** [comment]
@ndegendogo 
> 4. Are all German keys automatically federated to the EFGS, or is there some kind of filtering? (e.g. consent of the uploading user to the federation / information that said user has travelled / or similar)

There is no separate consent to share Diagnosis Keys to EFGS. If you consent to share, then you share to all participating countries.

![Consent when registering test](https://user-images.githubusercontent.com/66998419/103682650-72332380-4f89-11eb-9a35-ee89f6a96729.jpg)

I asked in https://github.com/corona-warn-app/cwa-website/issues/753 if there should be a new FAQ about this.

**Comment by thomasaugsten** [comment]
DE is for the old client before v1.5. After 1.5 the CWA is connected to EFGS and is loading the EUR package.
There are all EFGS keys included around 10.000 keys per day. In DE there are only the EFGS keys included where the origin country mark DE specific as country of interest for this key. Most of the country mark all EU countries as country of interest

**Comment by ndegendogo** [comment]
Thanks @thomasaugsten.

>  In DE there are only the EFGS keys included where the origin country mark DE specific as country of interest for this key.

So is this "country of interest" marked per key, or per country? Actually, I was expecting a higher number of keys from EFGS, especially as you mention that 

> Most of the country mark all EU countries as country of interest

**Comment by thomasaugsten** [comment]
Marked per key. EFGS key are in DE and EUR. EUR included special also not keys which are not marked for Germany

**Comment by ndegendogo** [comment]
I am just wondering. cwa currently shows 11 participating countries besides Germany.
The German numbers alone are roughly around 15000 - 40000 keys per day. The additional number from EFGS is mostly < 1000. 
Do the countries usually contribute **all** their keys to EFGS, or only those of persons that have travelled before?

**Comment by thomasaugsten** [comment]
The keys in DE are not only germany keys. Keys in DE are DE + EFGS key marked for DE. EUR are DE keys + all EFGS keys.
EUR- DE Keys are the EFGS keys not marked for DE.

**Comment by ndegendogo** [comment]
@thomasaugsten Thanks a lot - now the small difference makes perfect sense.

Any idea on the reason for the "hickup" on 06 Jan? On that day the sum of the hourly keys on the EUR endpoint was less than the daily count. The key numbers on DE endpoint were in line on that day.

**Comment by thomasaugsten** [comment]
No explanation for this

**Comment by ndegendogo** [comment]
ok, thanks. (Not really important, I was just curious).
Closing.
