### ISSUE TITLE
Is the data from the contact diary included in a backup?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#504]
## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Question has not already been asked in another issue

## Your Question
The data from the ENF itself is not stored in a backup, the user has to to do the onboarding again after restoring the backup. 
Is the data from the contact diary included in a backup? 
The user should definitely not lose all the manually added contacts & places from the last 14 days if they restore the backup or switch to a new device. 

---

## Related Issue

https://github.com/corona-warn-app/cwa-wishlist/issues/324

**Comment by MikeMcC399** [comment]
@Ein-Tim 

For Android:

https://github.com/corona-warn-app/cwa-app-android/blob/4f7664467cb9be280f39e5e61f9e0eb5f6063613/Corona-Warn-App/src/main/AndroidManifest.xml#L28
`        android:allowBackup="false"`
See https://developer.android.com/guide/topics/data/autobackup for explanation. I didn't look at this in detail, but it looks like there is no backup being done on Android.

**Comment by dsarkar** [comment]
@Ein-Tim No answer yet, stand by, please. Thanks.

**Comment by dsarkar** [comment]
@Ein-Tim Yes, I while ago I was told that they will come back with an answer, must have snowed under. Stand by, will come back to you (or somebody else from the team). Thanks.

**Comment by Ein-Tim** [comment]
@dsarkar 

Did you get an answer this time? 😄

**Comment by Ein-Tim** [comment]
Backup behavior of the app is in general very strange, I therefore close this issue in favor of https://github.com/corona-warn-app/cwa-wishlist/issues/500 & https://github.com/corona-warn-app/cwa-app-ios/issues/3626.
