### ISSUE TITLE
Corona Warn App and B1.1.7.

### ISSUE THREAD

**Issue by tibor** [corona-warn-app/cwa-documentation#507]
Hello,

the mutant variant B1.1.7. of Coronavirus has a much higher infection rate, meaning the needed amount of viral particles or timespan of a meeting can be much lower to cause an infection.

I'm wondering if the green/red alerts of the Corona Warn App are still reliable with the B1.1.7. variant, e.g. if a shorter timespan is enough to infect another person with B1.1.7. but the app would show only a green alert.

I think this topic is especially important, since only red alerts lead to a test that is paid by health insurances.

## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Question has not already been asked in another issue

## Your Question

* Source File:
* Line(s):
* Question:

**Comment by Ein-Tim** [comment]
I think we can close this in favor of https://github.com/corona-warn-app/cwa-wishlist/issues/328

**Comment by heinezen** [comment]
Hello @tibor ,

We have added FAQ entry https://www.coronawarn.app/en/faq/#mutation to address the topic. Adjustmets to the calculation are currently evaluated. We will use https://github.com/corona-warn-app/cwa-wishlist/issues/328 and the FAQ for notifying users about planned changes once they are ready to be implemented.

Best Regards,
CH

----
Corona-Warn-App Open Source Team
