### ISSUE TITLE
`ui_screens` folder needs update

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#508]
## Where to find the issue
https://github.com/corona-warn-app/cwa-documentation/tree/master/images/ui_screens

## Describe the issue
All screenshots in this folder are outdated.

## Suggested change
Update the screenshots.
After updating the separate screenshots, don't forget to update [ui_screens_android.png](https://github.com/corona-warn-app/cwa-documentation/blob/master/images/ui_screens/ui_screens_android.png) and [ui_screens_ios.png](https://github.com/corona-warn-app/cwa-documentation/blob/master/images/ui_screens/ui_screens_ios.png).

---
Internal Tracking ID: [EXPOSUREAPP-5625](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5625)

**Comment by Ein-Tim** [comment]
I suggest to wait with the update until statistics are included in the app.

**Comment by Ein-Tim** [comment]
Version 1.11 has been released. @dsarkar please remove the on hold label. Thanks.

**Comment by Ein-Tim** [comment]
We are seeing improvements to the UI in 1.13 again, so now it's up to you to decide when to update the screenshots.

**Comment by Ein-Tim** [comment]
@dsarkar 

Maybe you could clarify internally if it would be ok to just use the screenshots from https://www.coronawarn.app/en/screenshots/.

I could provide a PR which updates the folder with these screenshots. 

But: These screenshots don't show "a device" (like the screenshots now do), they really only are screenshots.

**Comment by dsarkar** [comment]
@Ein-Tim OK, nice idea actually. Will cross-check internally first. Thanks.

**Comment by dsarkar** [comment]
@Ein-Tim Actually, ui_screens does not provide much additional benefit compared to the new screenshots website (personal opinion). I would even suggest declaring https://github.com/corona-warn-app/cwa-documentation/tree/master/images/ui_screens obsolete with the implementation of https://www.coronawarn.app/en/screenshots/.

**Comment by MikeMcC399** [comment]
@dsarkar 

I would suggest to link to https://www.coronawarn.app/en/screenshots/ (not to copy).

One question is whether to leave the old images as a historical record and add some comment with a link to the current images.

https://github.com/corona-warn-app/cwa-documentation/blob/master/ui_screens.md explains a bit about the original decision making.

It would be simplest just to delete the old information and link to the new screenshots.

**Comment by dsarkar** [comment]
@MikeMcC399  @Ein-Tim 
Altogether:
- To be revised
  - https://github.com/corona-warn-app/cwa-documentation/tree/master/images/ui_screens
  - https://github.com/corona-warn-app/cwa-documentation/blob/master/ui_screens.md 

- New images available
  -   https://www.coronawarn.app/en/screenshots/  

- We will clarify if we need to keep the old images / text as a historical record 
  - if so: add some comments with a link to the current images
  - if not:  just to delete the old information and link to the new screenshots.

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-5625](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5625)

**Comment by Ein-Tim** [comment]
@dsarkar 

Problem:

https://github.com/corona-warn-app/cwa-documentation/blob/master/images/ui_screens/ui_screens_ios.png

is used in

https://github.com/corona-warn-app/cwa-app-ios#----corona-warn-app---ios.

These screens are also used in other places, like [here](https://github.com/corona-warn-app/cwa-documentation/blob/master/ui_screens.md).

**Comment by dsarkar** [comment]
@Ein-Tim OK. Thanks for the info. No problem. What we are gonna do: Just add an additional sentence, where appropriate that there are updated screenshots + [Link].

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim For the moment we keep the old ones for the history. So, just adding a sentence and link should do. We can clean up later if necessary.

**Comment by Ein-Tim** [comment]
@dsarkar 

I've opened https://github.com/corona-warn-app/cwa-app-ios/pull/2194 reg. the iOS README.md.
