### ISSUE TITLE
PrivateTracer

### ISSUE THREAD

**Issue by ReneHonig** [corona-warn-app/cwa-documentation#51]
I am one of the contributors to [PrivateTracer](https://privatetracer.org), a NL-based non-profit foundation with the goal to find out if a contact tracing app can be an effective tool in battling the COVID-19 virus and provide healthcare organisations with support in their contact tracing activities, that will allow our societies to be opened up responsibly. We have developed a fully open source end-end solution based on the DP-3T approach, hosted on [Gitlab](https://gitlab.com/privatetracer). 

We would be happy to share our code, learnings and experiences with your team.

**Comment by SebastianWolf-SAP** [comment]
Thank you for that information. However, this is not really an issue. Please see our [Contributing document](https://github.com/corona-warn-app/cwa-documentation/blob/master/CONTRIBUTING.md) how to engage with us. For your contact/cooperation request, I'd ask you to reach out to the team via the e-mail address corona-warn-app.opensource@sap.com.
