### ISSUE TITLE
Privacy notice incorrect description scanning QR code with no internet

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#510]
## Where to find the issue
Privacy notice 16 December 2020 for app version 1.10 and later
https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf (English)
https://www.coronawarn.app/assets/documents/cwa-privacy-notice-de.pdf (German)

6. Why is your data processed? 
b. Retrieving a test result 
Scanning the QR code

"As soon as your smartphone is connected to the internet, the app will transmit the hashed code number to the server system."

### Related issues
"Improved error message when no internet connection is available" https://github.com/corona-warn-app/cwa-app-android/issues/2062 from @not-a-feature EXPOSUREAPP-4569

## Describe the issue
The description:

"As soon as your smartphone is connected to the internet, the app will transmit the hashed code number to the server system." 

implies that if no internet connection is currently available that the app will store the QR code and forward it as soon as an internet connection does become available. That is however not a correct description of how the (Android) app works. If there is no internet connection, scanning the QR code immediately fails and the scanned data is discarded.

## Steps to reproduce

1. Activate flight mode to disable Wi-Fi and mobile networks
2. Open CWA > NEXT STEPS > Test with QR code
3. Tap ACCEPT
4. Position the QR code in the frame
5. Note message: "**Error**<br />Connection could not be established (597). Please try again."

Android Version: 10
App Version: 1.10.1

## Suggested change

---
In https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf (English)

Change
"**As soon as** your smartphone is connected to the internet, the app will transmit the hashed code number to the server system."
to
"Provided your smartphone is connected to the internet, the app will transmit the hashed code number to the server system."

---
In https://www.coronawarn.app/assets/documents/cwa-privacy-notice-de.pdf (German)

Change
"**Sobald Ihr Smartphone eine Verbindung zum Internet hat**, wird die gehashte Kennzahl von der App an das Serversystem übermittelt."
to
"Vorausgesetzt, Ihr Smartphone hat eine Verbindung zum Internet, wird die gehashte Kennzahl von der App an das Serversystem übermittelt."

---
Internal Tracking ID: [EXPOSUREAPP-4668](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4668)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks! 

---
Internal Tracking ID: [EXPOSUREAPP-4668](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4668)

**Comment by GisoSchroederSAP** [comment]
Meanwhile, this reported issue was evaluated by multiple parties. After final review with the lawers, the final call is: "Internet connection is a prerequisite for the scanning process, as the resulting data set get validated on the server side. This prerequisite is already documented properly and consistently.  The described implication cannot necessarily be derived from the current wording. Therefore, there is no necessity to change the wording in the privacy notice."

Subsequently, we will close this GitHub issue, and as well the respective internal JIRA tracking ID.

**Comment by GisoSchroederSAP** [comment]
From the above statement we hope the ruling is accepted. The related internal ticket as closed already.

**Comment by MikeMcC399** [comment]
@GisoSchroederSAP 

I haven't changed my opinion that the wording is misleading.

It's a legal document though, and the lawyers decide, so we leave it there. Thank you for responding.

**Comment by GisoSchroederSAP** [comment]
That's okay. I had a number of discussions about the proposed changes and even the alternative wording did not convince the other parties.
