### ISSUE TITLE
Clarify that the user doesn't have to select any countries for the EFGS and describe the 3 modes 

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#514]
## Current Implementation
The last sentence in https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#cross-border-interoperability reads:

>In order for the EFGS to function correctly, all users must specify their visited countries correctly (either manually or automatically).

The 3 modes of the EFGS, which are f.e described [here](https://news.sap.com/2020/10/eu-corona-gateway-live/) are not covered in the documentation at all.

## Suggested Enhancement
Clarify that the user does not have to select any countries (or similar steps in order for the EFGS to work). 
Also, I would suggest to cover the 3 modes of the EFGS inside of the documentation and also say which mode is used and why.

## Expected Benefits
Better understanding for everybody who reads the documentation.

---

## Related Issues
- https://github.com/corona-warn-app/cwa-wishlist/issues/344

**Comment by MikeMcC399** [comment]
@Ein-Tim 
https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#cross-border-interoperability needs to be corrected to align to https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf section 6c. **Warning others**

All Diagnosis Keys are submitted to EFGS and there is no additional information sent about countries visited, neither manually, nor automatically.

**Comment by Ein-Tim** [comment]
@dsarkar Will anyone take care of the documents? Or should I prepare a PR at least describing that the user does not have to select any countries?

**Comment by Ein-Tim** [comment]
@dsarkar I offer to provide a PR here, just let me know how you plan to proceed here.

**Comment by Ein-Tim** [comment]
The EFGS has been shut down and the CWA is no longer exchanging keys with apps from other countries. This issue is obsolete.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

The FAQs should probably be reviewed due to this change e.g. https://www.coronawarn.app/en/faq/results/#interoperability_countries.

It is only clear when you read the "small print" that there are no longer any countries participating.

**Comment by Ein-Tim** [comment]
@MikeMcC399 We are already working on updating the FAQ entry you linked to! I will also take care of updating the documentation reg. the EFGS in this repository (https://github.com/corona-warn-app/cwa-documentation/blob/main/solution_architecture.md#cross-border-interoperability).

**Comment by Ein-Tim** [comment]
Status update: I will provide a PR updating the documentation as soon as the FAQ entry has been updated (we're still working on that...).

**Comment by brianebeling** [comment]
@Ein-Tim Hey Tim, do you think a new issue would be good for the tasks you are working on? Otherwise we should perhaps reopen, although by the looks of it it might not be a fit

**Comment by Ein-Tim** [comment]
@brianebeling 

I already prepared a PR based on the texts we already discussed internally. I'm just waiting for the FAQ update so that I don't "leak" any information, so from my side: No need to re-open this issue, I can provide the PR at any time you tell me to.

**Comment by MikeMcC399** [comment]
@brianebeling / @Ein-Tim 

I will open a new issue to check the point that I raised. This issue here should not be re-opened. That would just be confusing.

**Comment by Ein-Tim** [comment]
- PR #946 provided
