### ISSUE TITLE
Questions on Exposure Windows / is caching possible?

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-documentation#519]
## Your Question

If I understand correctly, with the new improved risk calculation since ENF v2 (exposure window mode), the ENF performs matching of RPIs and then returns a list of "Exposure Windows" to cwa; these Exposure Windows have contact-related data (like estimation of distance and duration of the contact), and data describing the risk level of the related DEK key (like report type and days since onset of symptoms).

**Question 1:** Is it correct that such a single Exposure Window instance is always related to a single person / sender of the RPIs? 

**Question 2:** Is it correct that such an Exposure Window instance does *not* give the precise timestamp of the encounter?
Does it give at least the day / date of the encounter?

**Question 3:** Is it correct that such an Exposure Window is always the effect of a **single** key file? Or could it happen that e.g. each single file stays below a threshold, but a combination of files presented to ENF at the same call will exceed the threshold and is only then detected as an encounter / Exposure Window?

**Question 4:** Would the list of Exposure Windows be a meaningful intermediate result of the risk checking procedure that could be cached? At least as long as the risk calculation parameters don't change?

**And, finally:** could such a caching be used to mitigate / address issues like excessive background times or excessive battery usage of the risk calculation procedure?

**Comment by Ein-Tim** [comment]
Hey @ndegendogo 

Very good questions, thanks for rising them! 

Question 2 was answered some time ago in our [community slack](https://covidapps.slack.com/archives/C0194ML0MLN/p1610650200005200?thread_ts=1610647461.001000&cid=C0194ML0MLN);
There, @d4eken linked to [this](https://developers.google.com/android/reference/com/google/android/gms/nearby/exposurenotification/ExposureWindow#getDateMillisSinceEpoch()) google docs which says:

>Returns the epoch time in milliseconds the exposure occurred. This will represent the start of a day in UTC.

Hope this helps a bit, have a nice day

**Comment by ndegendogo** [comment]
> start of a day in UTC.

@Ein-Tim yes, this was also my understanding, thanks for confirmation.
This timestamp / day is essential if we consider caching of the exposure windows. Else cwa cannot discard exposure windows that are older than 14 days.

Hopefully the answers to my other questions work out that this is indeed a feasible idea ....

**Comment by mlenkeit** [comment]
@ndegendogo just happened to come across this...

> Question 1: Is it correct that such a single Exposure Window instance is always related to a single person / sender of the RPIs?

yes

> Question 2: Is it correct that such an Exposure Window instance does not give the precise timestamp of the encounter?
Does it give at least the day / date of the encounter?

yes and yes

> Question 3: Is it correct that such an Exposure Window is always the effect of a single key file? Or could it happen that e.g. each single file stays below a threshold, but a combination of files presented to ENF at the same call will exceed the threshold and is only then detected as an encounter / Exposure Window?

an Exposure Window always links to exactly one Diagnosis Key and a Diagnosis Key is in no more than one file.

> Question 4: Would the list of Exposure Windows be a meaningful intermediate result of the risk checking procedure that could be cached? At least as long as the risk calculation parameters don't change?

ENF does this kind of caching internally already.

> And, finally: could such a caching be used to mitigate / address issues like excessive background times or excessive battery usage of the risk calculation procedure?

I don't think so, ENF already optimizes internally.

**Comment by Ein-Tim** [comment]
@ndegendogo Has your question been sufficiently answered by @mlenkeit? If yes, I suggest to close this issue now.

**Comment by ndegendogo** [comment]
@Ein-Tim thanks for your reminder.
Yes, everything answered. And, moreover, cwa meanwhile leverages nicely the internal caching of exposure windows in ENF and saves a lot of runtime and battery.

Thanks to the dev team as well! 🎉🎉🎉

*closing as answered and resolved*
