### ISSUE TITLE
Question on cwa statistics numbers as published by RKI

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-documentation#520]
## Your Question

RKI publishes weekly statistics on cwa [here](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Archiv_Kennzahlen/WarnApp_KennzahlenTab.html)
I am a bit confused about these published numbers. The meaning is a bit unclear and confusing.

**Is here the correct place to ask such questions?** 
If not, where could I get more information? My current assumption is that these numbers are captured "somewhere" on a cwa server.

1) Are the numbers of users that have shared their keys from **Germany** ( = excluding keys from European federation gateway), or from **Europe** ( = including these keys from the gateway)?

2) In the last section of the data sheet two accumulated numbers are given how many users have shared their keys. These numbers are confusing and seem inconsistent. Or am I missing something?

a) Data sheet 2020-10-12, bottom left:
"Im Zeitraum vom 1. September bis 11. Oktober 2020 [...] haben sich 7922 Nutzerinnen und Nutzer dafür entschieden, ihr positives Testergebnis mit den anderen Nutzerinnen und Nutzern zu teilen."

b) same data sheet, bottom right:
"Seit dem Start der Corona-Warn-App haben insgesamt 10504 Nutzerinnen und Nutzer ihr positives Testergebnis geteilt."

c) Data sheet 2021-01-29, bottom left:
"Im Zeitraum vom 01. September 2020 bis 27. Januar 2021 [...] haben sich 222.486 Nutzerinnen und Nutzer dafür entschieden, ihr positives Testergebnis mit den anderen Nutzerinnen und Nutzern zu teilen."

d) same data sheet, bottom right:
"Seit dem Start der Corona-Warn-App haben insgesamt 227.985 Nutzerinnen und Nutzer ihr positives Testergebnis geteilt"

So when I calculate (b) - (a), I get the number of users that shared their keys before 01 Sept 2020 since begin of cwa - right?
10504 - 7922 = 2582 users

And now I calculate (d) - (c) and expect the same number - right?
227985 - 222486 = 5499 users

What am I missing here?

**Comment by dsarkar** [comment]
@ndegendogo ok, interesting. We will raise this internally. Thanks.

**Comment by Ein-Tim** [comment]
@dsarkar Is there an update available here? @ndegendogo Asked this question over a year ago and there was no answer provided.

**Comment by MikeMcC399** [comment]
@ndegendogo 

Your question was about the statistics published to https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Archiv_Kennzahlen/WarnApp_KennzahlenTab.html. The last statistics published there are from Oct 1, 2021.

In the meantime, the statistics are now published to https://www.coronawarn.app/de/analysis/ (and https://www.coronawarn.app/en/analysis/). On the German page it refers to a data problem:

"Teilungsverhalten: teleTANs
Anzahl der positiven Testergebnisse, die durch teleTAN-Eingabe validiert und in der Corona-Warn-App geteilt bzw. nicht geteilt wurden.
In den Anfangstagen der Erfassung (25. bis 31. August 2020) wurden Gesamtzahlen erfasst, die nicht nach „Geteilt“ und „Nicht geteilt“ stratifiziert sind. Dies führt bei den kumulativen Zahlen zu einer fortbestehenden Diskrepanz zwischen der Summe der Straten und der Gesamtzahl."

I don't know if that covers all the discrepancies which you mentioned.

The data has also been analysed and presented in various articles in the [Science Blog](https://www.coronawarn.app/en/science/) starting in June 2021.

There was also an error discovered in another area https://www.coronawarn.app/en/faq/results/#dashboard_pcr_tests regarding PCR test counts.

Do you think that this topic still needs to be investigated?

**Comment by ndegendogo** [comment]
@MikeMcC399 you are right.
The mentioned publications are meanwhile outdated / superseded by newer available data; and the given reason for the discrepancy sounds plausible.

Closing as answered.
