### ISSUE TITLE
Locations saved more than one time

### ISSUE THREAD

**Issue by tinic9** [corona-warn-app/cwa-documentation#521]
## Technical details

- Device name: Samsung Galaxy S20
- Android version: 11
- App version: 1.10.1

## Description
If you create a now location on the contact diary you can save one location more than one time in your locations list.

## Steps to reproduce the issue
1. Go to the contact dairy
2. Click on a day
3. Click on "Orte"
4. Click on "+ Ort"
5. Set a name for the location like "Berlin Hotel"
6. Click on "Speichern"
7. Click on "+ Ort"
8. Set a name for the location like "Berlin Hotel" (must be the same name as before)
9. Click on "Speichern"
10. Location is saved two times in the locations list

## Expected behaviour
Warning: Location already exists.

## Possible Fix
If-clause to check if a location has already been entered.

## Additional context
Error probably occurs on all devices.

---
Internal Tracking ID: [EXPOSUREAPP-4949](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4949)

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-4949](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4949)

**Comment by Ein-Tim** [comment]
@dsarkar I guess this is internally handled as a Story and has low priority, or?

**Comment by larswmh** [comment]
Closing this issue as the related internal ticket is set to `obsolete`.

Developer comment:

> This is a feature and not a bug. We agreed to not do any input validation and explicitly allow duplicate entries.
