### ISSUE TITLE
Does scanning the QR-Code increase my test-result privacy?

### ISSUE THREAD

**Issue by alanrick** [corona-warn-app/cwa-documentation#524]
I couldn't find anything in any of the FAQs about this....

If I am tested at a lab/doctor-surgery and I do not scan the qr-code,  someone else could scan that code into their CWA and receive my results. However, from my understanding of #475 , I believe that if I scan the qr-code into my CWA (and I'm online) then anybody getting their hands on the qr-code afterwards will **not** receive the result if they scan it after me.

Is that assumption correct?

Also, am I correct in assuming that either way, the doctor does not receive the test result, but the health authority will, providing I test positive?

I ask, because this could be an argument in favour of using the CWA.

**Comment by dsarkar** [comment]
HI @alanrick, 

> I believe that if I scan the qr-code into my CWA (and I'm online) then anybody getting their hands on the qr-code afterwards will not receive the result if they scan it after me.



the QR-code can only be scanned once.

**Comment by dsarkar** [comment]
> Also, am I correct in assuming that either way, the doctor does not receive the test result, but the health authority will, providing I test positive?

Will check internally.

**Comment by ndegendogo** [comment]
@alanrick my understanding of the process is that cwa introduces an *additional* reporting path (directly to you). But the other pathes are still there. So if you are tested at a doctor and he sends the famous form to the lab, then he will still get the result (in any case, positive or negative).

But I may be wrong with this understanding.

**Comment by alanrick** [comment]
Thanks @dsarkar . My doctor also confirmed they have my results stored in their files.
So the answer to this question is:
**Yes - Marginally.**
