### ISSUE TITLE
CWA seems to ignore the exposure logs/random IDs of a previous installation

### ISSUE THREAD

**Issue by Jens07** [corona-warn-app/cwa-documentation#525]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

If you uninstall the app, the reinstalled version of the app seems to ignore the exposure logs/random IDs of the previous installation. After the start of the app, it appears the gray window "UNBEKANNTES RISIKO - Da Sie Ihre Begegnungs-Aufzeichnung noch nicht lange genug aktiviert haben, konnten wir für Sie kein Infektionsrisiko berechnen." Here the screenshots of the start and the third day
![Day one](https://user-images.githubusercontent.com/68737429/88459131-3d2b8c80-ce93-11ea-85df-2ffebcd4b086.png)

![Day three](https://user-images.githubusercontent.com/68737429/88459134-43ba0400-ce93-11ea-97ce-bea032c6eeca.png)

## Expected behaviour

The app should register the entire exposure logs. You wrote in your own FAQs that the logs wont be deleted in the case of an uninstallation under iOS. See https://www.coronawarn.app/en/faq/#delete_random_ids. It seems paradoxical, if you mention that in the FAQ but the reinstalled app ignores the stored data.
## Steps to reproduce the issue

1. Uninstall the Corona-Warn-App
2. Reboot the iPhone
3. Reinstall the CWA
4. See the message in the gray window described above

## Technical details

- iOS Version: 13.6
- Device: iPhone 11
- CWA Version: 1.1.1

## Additional context

I didn't know that the problem with the missing background check was already discussed here corona-warn-app/cwa-app-ios#916 . So I contacted the official support of the telekom. After a reboot was not successful, the staff recommended me to un- and reinstall the app to reactivate the background check.

---
Internal Tracking ID: EXPOSUREAPP-1932

**Comment by Ein-Tim** [comment]
Related issue: https://github.com/corona-warn-app/cwa-wishlist/issues/8

**Comment by Ein-Tim** [comment]
This issue should be closed for two reasons 

a) the unknown risk status was removed from the app
b) the app now shows how long it is installed, it is correct that this counting starts again if the app is reinstalled.

@Jens07 Please close this issue.

**Comment by MikeMcC399** [comment]
It looks like this issue was logged for CWA on iOS.

My personal experience lately with CWA on Android is that a re-install picked up a red warning from a previous installation.

I does seem like this issue should be closed, also for the reasons given by @Ein-Tim in https://github.com/corona-warn-app/cwa-documentation/issues/525#issuecomment-1101382005.

**Comment by dsarkar** [comment]
Dear @Jens07, 

thanks for contributing here. Please see https://github.com/corona-warn-app/cwa-documentation/issues/525#issuecomment-1127988359 and https://github.com/corona-warn-app/cwa-documentation/issues/525#issuecomment-1101382005. We are closing this issue now. If necessary re-open or create a new issue. Best wishes, DS

---
Corona-Warn-App Open Source Team
