### ISSUE TITLE
Wrong localization of "über die Corona-Warn-App"

### ISSUE THREAD

**Issue by fynngodau** [corona-warn-app/cwa-documentation#526]
In the second statistics card, it says "über die Corona-Warn-App" in German, indicating that the warnings were transmitted *through* the app. This is incorrectly translated to English as "About":

https://github.com/corona-warn-app/cwa-app-android/blob/f82fbf7bd5634eb90f41434681fac82347d0d5d4/Corona-Warn-App/src/main/res/values-en/strings.xml#L1298

Other locales are probably also affected, at least they start with a capital letter while the German one doesn't. This issue is included in `release/1.11.x` and should probably be fixed before it is released.

This is where the string is placed, leading to confusion:

![image](https://user-images.githubusercontent.com/16943720/105839157-5bed1600-5fd1-11eb-9e47-7770978dbd6c.png)

---
Internal Tracking ID: [EXPOSUREAPP-4760](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4760)

PR corona-warn-app/cwa-app-android#2219 merged 1.11

**Comment by Ein-Tim** [comment]
Fix for iOS is in https://github.com/corona-warn-app/cwa-app-ios/pull/1976/files#diff-8fc5b852f1f89c8368223b1ab28939b0b01f90542347b91e9bdb1e678b289dcaR1626

**Comment by dsarkar** [comment]
@Ein-Tim Thanks!

**Comment by MikeMcC399** [comment]
It will be good to check for the string `statistics_card_submission_bottom_text` in
https://github.com/corona-warn-app/cwa-app-android/blob/release/1.13.x/Corona-Warn-App/src/main/res/values/strings.xml before 1.13.0 is released to make sure it has been corrected and is showing "through the Corona-Warn-App".

**Comment by Ein-Tim** [comment]
@MikeMcC399 And probably also in the 1.14 branch before releasing 1.14 😉

**Comment by MikeMcC399** [comment]
The CWA Android 1.13.2 release is showing correctly:
"through the Corona-Warn-App" at the bottom of the "Warnings by App Users" statistics tile.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for checking!
@fynngodau Thanks for reporting, would you like to close this issue?

**Comment by Ein-Tim** [comment]
@MikeMcC399 @dsarkar 

Confirm fixed for iOS too

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for cross-checking.

**Comment by heinezen** [comment]
Then we can close this issue :)

----
Corona-Warn-App Open Source Team
