### ISSUE TITLE
Contact Journal information not updated to 15 days

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#527]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy A5 (2017) SM-A520F
- Android version: 8.0.0
- First reported on App version: 1.12.0
- Reviewed as not fixed on App version: 2.16.2

## Describe the bug

The Contact Journal Information says:

<string name="contact_diary_onboarding_body">"Create an overview of your contacts in the last 14 days, so you’ll have a complete list at hand quickly if needed."</string> 

however since version 1.12.0 the number of days stored by the Contact Journal has been increased from 14 to 15 days. Version 1.11.0 stored 14 days.

![Keep track of your contacts](https://user-images.githubusercontent.com/66998419/107982531-80cb1c80-6fc4-11eb-8e1e-9112ccf1b04f.jpg)

## Steps to reproduce the issue

1. Tap "Journal" at bottom of screen
2. Note text "Create an overview of your contacts in the last 14 days, so you’ll have a complete list at hand quickly if needed." if this is the first time using the journal
3. Tap "OPEN JOURNAL"
4. If not the first time using, tap three-dot icon > Information and read text as noted in (2.) above.
5. In three-dot icon, tap Export Entries
6. Select Save to Drive, Save or use other sharing method
7. Read exported text "Kontakte der letzten 15 Tage ..."
8. To verify there are 15 days stored, examine the Contact Journal

Edit: Steps updated for changed UI in 1.13.2

## Expected behavior

The text 
"Create an overview of your contacts in the last nn days ..." should correspond to the number of days stored, which is 15.

## Possible Fix

Modify `values\contact_diary_strings.xml`
String `contact_diary_onboarding_body` to
"Create an overview of your contacts in the last *15* days ..."

and other supported languages accordingly.

## Additional context

The increase in the number of days stored in the Contact Journal updating from 1.11.0 to 1.12.0 from 14 to 15 days is not mentioned in the New Features / Release 1.12.0. Viewable through three-dot icon > New Features.

---
Internal Tracking ID: [EXPOSUREAPP-5156](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5156)
Internal Tracking ID: [EXPOSUREAPP-10331](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10331)

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-5156](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5156)

**Comment by andjeraj** [comment]
> ## Avoid duplicates
> 
> * [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
> 
> * [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
> 
> * [X] Bug is not already reported in another issue
> 
> 
> 
> ## Technical details
> 
> 
> 
> - Device name: Samsung Galaxy A5 (2017) SM-A520F
> 
> - Android version: 8.0.0
> 
> - App version: 1.12.0
> 
> 
> 
> ## Describe the bug
> 
> 
> 
> The Contact Journal Information says:
> 
> 
> 
> <string name="contact_diary_onboarding_body">"Create an overview of your contacts in the last 14 days, so you’ll have a complete list at hand quickly if needed."</string> 
> 
> 
> 
> however since version 1.12.0 the number of days stored by the Contact Journal has been increased from 14 to 15 days. Version 1.11.0 stored 14 days.
> 
> 
> 
> ![Keep track of your contacts](https://user-images.githubusercontent.com/66998419/107982531-80cb1c80-6fc4-11eb-8e1e-9112ccf1b04f.jpg)
> 
> 
> 
> 
> 
> ## Steps to reproduce the issue
> 
> 
> 
> 1. Scroll down to Contact Journal and tap "MANAGE JOURNAL"
> 
> 2. Note text "Create an overview of your contacts in the last 14 days, so you’ll have a complete list at hand quickly if needed." if this is the first time using the journal
> 
> 3. Tap MANAGE JOURNAL
> 
> 4. If not the first time using, tap three-dot icon > Information and read text as noted in (2.) above.
> 
> 5. In three-dot icon, tap Export Entries
> 
> 6. Select Save to Drive, Save or use other sharing method
> 
> 7. Read exported text "Kontakte der letzten 15 Tage ..."
> 
> 8. To verify there are 15 days stored, examine the Contact Journal
> 
> 
> 
> ## Expected behavior
> 
> 
> 
> The text 
> 
> "Create an overview of your contacts in the last nn days ..." should correspond to the number of days stored, which is 15.
> 
> 
> 
> ## Possible Fix
> 
> 
> 
> Modify `values\contact_diary_strings.xml`
> 
> String `contact_diary_onboarding_body` to
> 
> "Create an overview of your contacts in the last *15* days ..."
> 
> 
> 
> and other supported languages accordingly.
> 
> 
> 
> ## Additional context
> 
> 
> 
> The increase in the number of days stored in the Contact Journal updating from 1.11.0 to 1.12.0 from 14 to 15 days is not mentioned in the New Features / Release 1.12.0. Viewable through three-dot icon > New Features.
> 
> 
> 
> 
> 
> ---
> 
> Internal Tracking ID: [EXPOSUREAPP-5156](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5156)

**Comment by MikeMcC399** [comment]
@andjeraj 
Your post is a copy of the original report. Were you trying to add some information? If not, then perhaps you could delete your post as it looks like it was an accident.

**Comment by dsarkar** [comment]
@MikeMcC399 
Feedback: 

> This is the expected behavior. It shows correctly 14 days and additionally the current day. This was extended by one day as in the risk-history it is the same behavior (14 days + current day.

**Comment by MikeMcC399** [comment]
@dsarkar 
> This is the expected behavior. It shows correctly 14 days and additionally the current day. This was extended by one day as in the risk-history it is the same behavior (14 days + current day.

It just seems slightly inconsistent and confusing if in one place it says you can create an overview for **14** days and in another place it says that you are sharing the last **15** days.

---
![Keep track of your contacts](https://user-images.githubusercontent.com/66998419/107982531-80cb1c80-6fc4-11eb-8e1e-9112ccf1b04f.jpg)

---
![Share 15 Tage](https://user-images.githubusercontent.com/66998419/109396082-24ef8480-7930-11eb-8406-abef29614245.png)

---

**Comment by MikeMcC399** [comment]
@dsarkar 
When I revisited this issue I noticed that the Contact Journal onboarding / information screen is inconsistent on the same page. 14 days needs to be changed to 15 days. It says lower down that "Journal entries will be deleted automatically after 16 days.". That only makes sense together with a value of 15 days to keep entries active, not 14 days.

![Keep track of your contacts](https://user-images.githubusercontent.com/66998419/114047515-0616d300-988a-11eb-8dae-1c4b94c3d6fe.png)

**Comment by dsarkar** [comment]
@MikeMcC399 ok, I will forward this info to the internal ticket.

**Comment by MikeMcC399** [comment]
@dsarkar 
We didn't hear anything more back from you on this topic. In the screen from https://github.com/corona-warn-app/cwa-documentation/issues/527#issuecomment-815884939 the numbers only make sense if the number at the top is 14 days together with 15 days at the bottom, or 15 days at the top with 16 days at the bottom.

![Keep track of your contacts](https://user-images.githubusercontent.com/66998419/114047515-0616d300-988a-11eb-8dae-1c4b94c3d6fe.png)

If we can't agree about this, then I suggest that this issue is closed. It's all about whether the current day is counted or not, and I think that it is confusing in the text if the current day is not included at the top, but it is included at the bottom. Taken together with the export date, the app is naming 14 days, 15 days and 16 days all for the same thing.

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-10331](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10331)

**Comment by MikeMcC399** [comment]
@dsarkar 
This issue has the label Fix 2.14, however I cannot see any change.

I can't see any reference to EXPOSUREAPP-10331 anywhere else.

Was any change actually done, and if yes, what was the change?

**Comment by MikeMcC399** [comment]
@dsarkar 
This issue is still unresolved. I would submit a PR to fix it, but that is not recommended for translated text and I would only do it for Android, not for iOS.

For Android the fix would be in [values-de/contact_diary_strings.xml#L34-L35](https://github.com/corona-warn-app/cwa-app-android/blob/main/Corona-Warn-App/src/main/res/values-de/contact_diary_strings.xml#L34-L35)

Change `contact_diary_onboarding_body`

"Erstellen Sie eine Übersicht über Ihre Kontakte der letzten 14 Tage. ..."

to

"Erstellen Sie eine Übersicht über Ihre Kontakte der letzten 15 Tage. ..."

Other languages, including English would get changed through the translation process.

That would make it consistent with the text displayed on the same view
[values-de/contact_diary_strings.xml#L42-L43](https://github.com/corona-warn-app/cwa-app-android/blob/main/Corona-Warn-App/src/main/res/values-de/contact_diary_strings.xml#L42-L43)

`contact_diary_onboarding_functionality_fourth_section`

"Sie können hinzugefügte Personen und Orte jederzeit wieder aus dem Tagebuch löschen. Tagebuch-Einträge werden nach 16 Tagen automatisch gelöscht."

and with the text [values/contact_diary_strings_export.xml#L10-L11](https://github.com/corona-warn-app/cwa-app-android/blob/main/Corona-Warn-App/src/main/res/values/contact_diary_strings_export.xml#L10-L11)

`contact_diary_export_intro_one`

"Kontakte der letzten 15 Tage (%1$s - %2$s)"

which is used by the export entries function.

**Comment by MikeMcC399** [comment]
No change to this issue with label "Fix 2.15".

Checked on CWA Android 2.16.2.

![Keep track of your contacts](https://user-images.githubusercontent.com/66998419/114047515-0616d300-988a-11eb-8dae-1c4b94c3d6fe.png)

**Comment by Ein-Tim** [comment]
I'm planning to provide a PR for this under iOS. 

I would do the following changes:

"Erstellen Sie eine Übersicht über Ihre Kontakte der letzten **15** Tage. So haben Sie bei Bedarf schnell eine vollständige Liste zur Hand. Zusätzlich werden Ihnen hier Ihre Risiko-Begegnungen angezeigt."

and

"Sie können hinzugefügte Personen und Orte jederzeit wieder aus dem Tagebuch löschen. Tagebuch-Einträge werden nach **15** Tagen automatisch gelöscht."

Do you agree with this @MikeMcC399?

**Comment by MikeMcC399** [comment]
@Ein-Tim 

The 14 days in the text "Erstellen Sie eine Übersicht über Ihre Kontakte der letzten 14 Tage. ..." is definitely wrong. It contradicts the fact that there are 15 days visible in the Contact Journal. It should be changed to 15 days and I don't know why this has not already been done.

---

I believe that the 16 days in the following text is right and should not be changed. A developer should be consulted if you think this is wrong.

"Sie können hinzugefügte Personen und Orte jederzeit wieder aus dem Tagebuch löschen. Tagebuch-Einträge werden nach 16 Tagen automatisch gelöscht."

In Android there is a parameter which defines how old entries are deleted:

https://github.com/corona-warn-app/cwa-app-android/blob/release/2.16.x/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/contactdiary/retention/ContactDiaryRetentionCalculation.kt#L74-L79

    companion object {
        /**
         * Contact diary data retention in days 15+1
         */
        const val RETENTION_DAYS = 16
    }

Looking at the code it seems that 16 full days need to have elapsed before a contact journal entry is deleted, so an entry from Jan 1 would be deleted on Jan 18.

On Jan 18 the contact journal would be displaying Jan 4 to Jan 18 data inclusive. Data for Jan 2 and 3 is still stored but not displayed.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Ah, I see. Mh, to me it makes no sende that contact journal entries are stored longer than they are displayed.

Well, I think I'll first wait for feedback then.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

It is all a little unclear. The contact journal displays today and the previous 14 days making a total of 15 days. The text could be better worded to use the value 15 days unambiguously, for instance "Erstellen Sie eine Übersicht Ihrer Kontakte über einen Zeitraum von 15 Tage." or "Erstellen Sie eine Übersicht über Ihre Kontakte von heute und den vergangenen 14 Tagen.".

Keeping a full 16 days stored may make sense to ensure no needed data is lost if the time zone is changed, but I am guessing about the reason.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

The simple change of 14 days to 15 days is fine.

This agrees also with the export entries text, which says "Kontakte der letzten 15 Tage".

**Comment by MikeMcC399** [comment]
@dsarkar 

- The fix https://github.com/corona-warn-app/cwa-app-android/pull/4725 was added to [v2.17.0-RC2](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.17.0-RC2)

I checked CWA Android 2.17.1-RC0 and the text has been changed to 15 days in English and German.

Perhaps @Ein-Tim  could check the iOS release candidate as well? If iOS has also been successfully corrected you could update the label of this issue to `Fix 2.17`.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I confirmed that my PR https://github.com/corona-warn-app/cwa-app-ios/pull/4111 is part of the [2.17.0-RC3](https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.17.0-RC3).

Also, building the project locally shows the fixed text on the emulator. This should get fixed in version 2.17.x under iOS.

**Comment by MikeMcC399** [comment]
This was fixed in CWA 2.17.2.
The label Fix 2.14 is incorrect.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks!
