### ISSUE TITLE
Wie speichert man einen Eintrag im Kontakttagebuch?

### ISSUE THREAD

**Issue by DGrothe-PhD** [corona-warn-app/cwa-documentation#529]
Bei meinem Android-Handy erscheint kein Speicherbutton, wenn ich versuche, eine neue Person ins Kontakttagebuch einzutragen.

**Comment by dsarkar** [comment]
Hi @DGrothe-PhD,

maybe this helps: https://www.coronawarn.app/de/blog/2020-12-28-corona-warn-app-version-1-10/

If you have more questions, please, let us know.

**Comment by DGrothe-PhD** [comment]
Thanks for the link. However, it is different on my phone: In the screenshot in the link, the "Speichern" button is just above the keyboard, but on my phone it looks like this: (yellow ribbon added over older entry for privacy reasons)
![Screenshot_20210220-180618_Corona-Warn](https://user-images.githubusercontent.com/64636863/108604008-93ba6400-73ab-11eb-9b92-275080d6d019.jpg)
ut on my phone the "Speichern" button does not appear.

**Comment by Ein-Tim** [comment]
@DGrothe-PhD 

What happens when you press "OK"?

**Comment by DGrothe-PhD** [comment]
Thanks, pressing OK (tiny) works - but it's not obvious enough for me

**Comment by Ein-Tim** [comment]
I really don't know what the behavior on Androids should be, @dsarkar maybe transfer this to the Android repo for further investigation?

**Comment by MikeMcC399** [comment]
For Android German the keyboard shows "OK", for English it shows "Done". That may depend on exactly which Android keyboard is enabled though.

The screen shots and instructions on https://www.coronawarn.app/de/blog/2020-12-28-corona-warn-app-version-1-10/ seem to be from iOS, whereas the screen shots on https://www.coronawarn.app/en/blog/2020-12-28-corona-warn-app-version-1-10/ look like they are from Android.

**Comment by heinezen** [comment]
For me, the keyboard shows a blue checkmark instead of an OK button (Android 10). Maybe this needs an additional explanatory sentence in the blogpost.

@DGrothe-PhD If you are satisfied with the answers, you can close the issue :)

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
The layout on Android differs from the layout on iOS shown in https://www.coronawarn.app/de/blog/2020-12-28-corona-warn-app-version-1-10/ 

Here is an example on a Google Pixel 3a phone with Android 11:

![Contact Journal](https://user-images.githubusercontent.com/66998419/108693995-c759d300-74fe-11eb-852b-c5161aca6a53.jpg)

Google Pixel phones use the Gboard keyboard which offers the tick button ✅ to complete an entry.

Samsung phones use the Samsung keyboard with 🆗 (German) and Done (English).

**Comment by MikeMcC399** [comment]
It is now more obvious how to save the data for a person in CWA 1.14. In addition to the person's name, the data stored has new fields for telephone number and e-mail address. To store a new or edited person, there is a separate button, labelled "Speichern" in German or "Save" in English.

The screenshot below is again from a Google Pixel 3a phone with Android 11:

![Person speichern 1 14](https://user-images.githubusercontent.com/66998419/110930069-f8bd0600-8328-11eb-9441-e86f55033b9c.jpg)
