### ISSUE TITLE
How discrimination can be ruled out?

### ISSUE THREAD

**Issue by TomTeeJay** [corona-warn-app/cwa-documentation#53]
A landlord sets up several smartphones and positions them in his houses full of tenants. The device always stays on same location acting as static beacon in order to collect IDs of all his tenants. From time to time the landlord will conduct a test or claiming he as symptoms triggering exchange of IDs or recieving notifications of possible infected peoples on this devices.

a) how can the app prevent usage of many devices by a single user?
b) how can the app prevent abnormal usage with static positioned devices?
c) how can the app rule our discrimination of people, in this case the tenants of the landlord?

This scenario of course can be expanded to company owners tracing employees, shop owners etc.

**Comment by Leseratte10** [comment]
a) it can't. 
b) it can't
c) it can't

But any match the landlord would get might as well be any person walking by the house. I'm not seeing the point in these actions.

**Comment by tkowark** [comment]
As in previous issues, it would be great if you could wait for the architecture documentation. This will explain some more details, which hopefully answer many of your questions. If they are then still open, you are, of course, free to open up this issue, again.
