### ISSUE TITLE
Delayed statistics update Friday, Feb 26, 2021

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#532]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation). iOS was also affected.
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy A5 (2017) SM-A520F
- Android version: 8.0.0
- App version: 1.12.0

## Describe the bug

The statistics shown in the app were not refreshed on the morning of Friday, Feb 26, 2021. They still had the date-stamp 24 Feb 2021. For instance, the app showed Confirmed New Infections 11,869 instead of the updated figure 9.997.

This was noticed at 10:30 of Friday, Feb 26, 2021, which was already more than 2 hours after the RKI data was updated on https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Fallzahlen.html.

![CWA app statistics](https://user-images.githubusercontent.com/66998419/109281556-c38ac100-781c-11eb-82b9-9da38e2cee20.jpg)

Edit: At 12:00 of Friday, Feb 26, 2021 the statistics were updated in the app.

## Steps to reproduce the issue

Open app and scroll down to "Confirmed New Infections"

## Expected behavior

According to https://www.coronawarn.app/en/faq/#further_details the statistical data for the app is formatted every 15 minutes, so I would expect the data to mirror what is shown on the two other reference sites, which have already been updated earlier today.

---
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Fallzahlen.html

![RKI Fallzahlen](https://user-images.githubusercontent.com/66998419/109281960-385dfb00-781d-11eb-9019-9c136baea118.jpg)

---
https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4

![arcgis](https://user-images.githubusercontent.com/66998419/109282049-54619c80-781d-11eb-88bb-daf36ae63eb5.jpg)

---
Related: https://github.com/corona-warn-app/cwa-documentation/issues/533

Internal Tracking ID: [EXPOSUREAPP-5445](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5445)

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim Thanks. Internal Tracking ID: [EXPOSUREAPP-5445](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5445)

**Comment by MikeMcC399** [comment]
There is a generic answer to this issue from @GisoSchroederSAP in https://github.com/corona-warn-app/cwa-documentation/issues/533#issuecomment-788744237 so I will close this specific issue which is now only of historical interest.
