### ISSUE TITLE
Document details on data donation

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-documentation#534]
## Your Question

* Documentation File:
* Line / Paragraph:
* Question:

[Your blog](https://www.coronawarn.app/en/blog/2021-02-26-corona-warn-app-1-13-announcement/) has announced the upcoming version 1.13 of cwa with an optional feature to donate data.
Is there a documentation with more details on this data donation?
Which data do I donate / share when I opt-in to this feature?

---
Internal Tracking ID: [EXPOSUREAPP-5477](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5477)

**Comment by Ein-Tim** [comment]
Docs will follow soon in the https://github.com/corona-warn-app/cwa-ppa-server repository. 
Take a look at the files in [this](https://github.com/corona-warn-app/cwa-ppa-server/tree/main/docs) folder.

**Comment by ndegendogo** [comment]
> Docs will follow soon in the https://github.com/corona-warn-app/cwa-ppa-server repository.

@Ein-Tim Thanks. I was not aware that another repo was created for this.

> the ppa-server will only document how the PPAC works

I agree that the documents that are promised here are very important; they will show the concepts and mechanisms how our privacy will be preserved ...

> but not which data is donated

... but imo also the details on the donated data are important and should be specified and documented, for transparency reasons. I don't want to dig through the source code to find out.

*(And for sure there **is** a documentation somewhere, because I cannot imagine that RKI was **not** involved in that decision, and I don't believe that **they** dig through the source code)*

**Comment by dsarkar** [comment]
@ndegendogo We can expect some documentation on PPA this week.

**Comment by dsarkar** [comment]
@ndegendogo Internal Tracking ID: EXPOSUREAPP-5477

**Comment by Ein-Tim** [comment]
@ndegendogo 

See #540

**Comment by ndegendogo** [comment]
Thanks @Ein-Tim

**Comment by ndegendogo** [comment]
For documentation, I replicate the related info from the [solution architecture document](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md)

> metrics of the risk calculation, test result delivery, and key submission behavior.
For example, this includes the current risk level and date of the most recent encounter or whether a test has been registered, how long it took until the result was made available.

**Comment by MikeMcC399** [comment]
@ndegendogo 
The new [Privacy notice](https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf) for CWA Version 1.13 was published yesterday and it has a lot of detailed information about the data sharing and survey data.

5. What data is processed? 
e. Data sharing
f. Participation in a survey

6. Why is your data processed?
f. Data sharing
g. Surveys

This is the same information available in the app itself, if you have already updated to 1.13.

Also on the RKI page [Infektionsketten digital unterbrechen mit der Corona-Warn-App](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Warn_App.html) there is additional information, including a complete new section headed
**Fragen zur Evaluation der Corona-Warn-App**
with quite a lot of details.

**Comment by ndegendogo** [comment]
Thanks @MikeMcC399 for the links
