### ISSUE TITLE
Align info in statistic cards - key figures

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-documentation#536]
## Where to find the issue

statistic cards - key figures

## Describe the issue

EN
Android: Explanation of Statistics
iOS: Explanation of nationwide statistics

## Suggested change

use the same wording on both platforms: Explanation of nationwide statistics

**Comment by MikeMcC399** [comment]
In Android the string is `statistics_explanation_subtitle` in [strings.xml](https://github.com/corona-warn-app/cwa-app-android/blob/main/Corona-Warn-App/src/main/res/values/strings.xml)
<string name="statistics_explanation_subtitle">"Explanation of Statistics"</string>

It is already changed in the release/1.13.x branch
https://github.com/corona-warn-app/cwa-app-android/blob/a29bfd73a414e5f0b550c0cc1040275299029d57/Corona-Warn-App/src/main/res/values/strings.xml#L1486-L1487
to   <string name="statistics_explanation_subtitle">"Explanation of nationwide statistics"</string> so maybe you just need to wait for 1.13.x to be released? 😀

**Comment by dsarkar** [comment]
@MikeMcC399 Great! Thanks! ... will check iOS as well...

**Comment by MikeMcC399** [comment]
The CWA Android 1.13.2 release shows correctly
"Explanation of nationwide statistics".

Tap on the ℹ️ icon on any of the statistics tiles to display the informational text.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks!
