### ISSUE TITLE
Stale date on statistics display early in day

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#537]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy A5 (2017) SM-A520F
- Android version: 8.0.0
- App version: ~~1.12.0~~ 2.5.1

## Describe the bug

If a new day starts, the CWA is open and the statistics from the previous day such as Confirmed New Infections are being displayed, then the timestamp still shows "Yesterday" although the data is now from the day before yesterday.

## Steps to reproduce the issue

1. Open CWA late in the day e.g. after 18.00 and scroll down to Confirmed New Infections.
2. Confirm that a timestamp "Yesterday" is showing and make a note of the numbers.
3. Leave the app open and view the app again after midnight and before new data is available (perhaps before 03:00 or before 06:00?).
4. Note that the dates in the display have not changed.

## Expected behavior

If a new day starts and no new statistics are yet available for the new day, then the timestamp for the statistics, which can be a relative date (such as Yesterday, Up to Yesterday or Currently), should be updated appropriately, either by displaying an absolute date or a new relative date.

## Possible Fix

Trigger a refresh of the data display when a new day starts.

## Additional context

There is no user-facing documentation available about the architecture of the statistics infrastructure, so I cannot say where the infection data is pulled from or when the new day's data should be available to the app. 

I notice that the RKI dashboard on https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4 often shows a refresh timestamp of approx. 03:00 - 03:30.

The RKI page https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Fallzahlen.html typically shows a refresh timestamp of approx. 08:30

The Excel sheet linked to on https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Fallzahlen_Daten.html is however only refreshed on working days Monday - Friday.

---
Internal Tracking ID: [EXPOSUREAPP-5444](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5444) iOS Fix 1.14
Internal Tracking ID: [EXPOSUREAPP-5454](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5454) Android

**Comment by dsarkar** [comment]
Separate tickets now:

---
Internal Tracking ID: [EXPOSUREAPP-5444](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5444) iOS
Internal Tracking ID: [EXPOSUREAPP-5454](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5454) Android

**Comment by Ein-Tim** [comment]
This has been fixed for iOS (version 1.14.3), what about Android?

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim 

Internal Tracking ID: EXPOSUREAPP-5444 iOS - COMPLETED
Internal Tracking ID: EXPOSUREAPP-5454 Android - NOT YET COMPLETED

**Comment by Ein-Tim** [comment]
@dsarkar 

Okay thanks, so I would propose to move it back to the Android repo since it has nothing to do with iOS anymore, or?

**Comment by dsarkar** [comment]
@Ein-Tim Let's keep it here. The issue affects/affected both platforms.

**Comment by dsarkar** [comment]
@MikeMcC399 Development could not reproduce this issue anymore. I also will test this again. Did you observe this behaviour recently by chance? Thanks.

**Comment by MikeMcC399** [comment]
@dsarkar 
> Development could not reproduce this issue anymore. I also will test this again. Did you observe this behaviour recently by chance?

I haven't been paying much attention lately to the statistics tiles, so I would not have noticed even if this issue is still occurring. I assume that 2.6 is close to release, so I will go through the repro steps with 2.6 after it is released and then reply here again.

**Comment by dsarkar** [comment]
@MikeMcC399 ok, thanks for feedback. I will try with 2.5.1 tonight.

**Comment by MikeMcC399** [comment]
@dsarkar 
I could not reproduce with 2.5.1 and Android 11. I will check with Android 8 according to the original report.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for testing. Same here, could not reproduce on Android 10 and CWA 2.5.1.

**Comment by MikeMcC399** [comment]
@dsarkar 
The issue is still reproducible on Android 8 with CWA 2.5.1. The refresh of the date label in the statistics tile, after the system clock advances to a new day, is not happening.

---
In the evening of July 28, 2021 the incidence shows label `yesterday` (July 27, 2021) with the value 15.0

![Day 1 6 24PM](https://user-images.githubusercontent.com/66998419/127456881-e661c928-1913-475d-8280-d2709f17535b.jpg)

---
In the early hours of July 29, 2021 at 00:30 the incidence display has not changed. It still shows `yesterday`, even though the data is now from the day before yesterday.

![Day 2 12 30AM](https://user-images.githubusercontent.com/66998419/127457289-917968f1-9234-463d-93e9-5c0450cb240a.jpg)

---
After closing and re-opening CWA on July 29, 2021 at 00:33 the incidence display is now correctly labelled with the date Jul 27, 2021.

![Day 2 12 33AM](https://user-images.githubusercontent.com/66998419/127457414-85fd1623-d63d-448c-81ce-5de9c6243d46.jpg)

**Comment by MikeMcC399** [comment]
@dsarkar 
I checked again with the new version 2.6.1 on the same Android 8 device and I can no longer reproduce the issue.

Closing as fixed.
