### ISSUE TITLE
Mismatch between Consent legal text and "Share Data" button

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#538]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation). To be confirmed.
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Pixel 3a Emulator
- Android version: 11
- App version: 1.13.2 RC0 (Build Variant: deviceDebug)
Not yet fully resolved in 1.15.1.

## Describe the bug

The consent text on the Share Data screen refers to the "SHARE DATA" button using the term "Accept", which is not the label of the button.

## Steps to reproduce the issue

Set language to English (United Kingdom)

1. Install and open CWA
2. Tap LET'S GET STARTED
3. Tap NEXT
4. Tap DO NOT ACTIVATE (and confirm)
5. Tap NEXT
6. Tap NEXT
7. On Share Data screen scroll down to "Your Consent"
Note the text "By tapping on "Accept", you consent to the following:"
Note also that the buttons are labelled "SHARE DATA" and "DO NOT SHARE"

![Your consent to share data EN](https://user-images.githubusercontent.com/66998419/109328222-8133a500-7859-11eb-87a7-8b5a086521ef.png)

## Expected behavior

If the text says "By tapping on ...." then the name it uses should be the name used on the button to be tapped.

## Possible Fix

Change the label "Share Data" in [strings.xml](https://github.com/corona-warn-app/cwa-app-android/blob/release/1.13.x/Corona-Warn-App/src/main/res/values/strings.xml) to agree with the legal text "Accept". The string is named `onboarding_ppa_consent_donate_button`

Leave the string containing the text "By tapping on "Accept", you consent to the following:" to agree with the changed name of the button. This string is in [legal_strings.xml](https://github.com/corona-warn-app/cwa-app-android/blob/release/1.13.x/Corona-Warn-App/src/main/res/values/legal_strings.xml) and has the name `ppa_onboarding_privacy_information_body`

In addition the string `onboarding_ppa_more_info_decline_processing_text` contains the text "If you do not consent to this transfer of your data to a third country, please do not tap on “Accept”. You will still be able to use the app, but not the data donation sharing feature." This will be correct if the button label is changed.

## Additional context

In German the text says:
"Indem Sie "Datenspende" aktivieren, willigen Sie ein:" which does not explicitly refer to the name of the button name, which is "Daten Spenden". 

However, the German text in  `onboarding_ppa_more_info_decline_processing_text`  says "Wenn Sie mit der Drittlandsübermittlung nicht einverstanden sind, tippen Sie bitte nicht „Einverstanden" an. Sie können die App weiterhin nutzen, die Datenspende ist dann jedoch nicht möglich." and there is no button labelled "Einverstanden".

---
Internal Tracking ID: [EXPOSUREAPP-5443](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5443) Android
Internal Tracking ID: [EXPOSUREAPP-5455](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5455) iOS

**Comment by dsarkar** [comment]
iOS String: https://github.com/corona-warn-app/cwa-app-ios/blob/eb7c4c9839ccf37a1bd945d0154e5a3ef0335630/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings#L82

**Comment by MikeMcC399** [comment]
@dsarkar
> iOS 1.14 String: https://github.com/corona-warn-app/cwa-app-ios/blob/eb7c4c9839ccf37a1bd945d0154e5a3ef0335630/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings#L82

You identified another string, which I missed. I will go back and list all the places in Android that I think are affected.

**Comment by MikeMcC399** [comment]
Here are the string references below (with permalinks) for release/1.13.x

In both English and German there is a mismatch between the consent text and the button label.

**EN**
File | String name | Contents
--- | --- | ---
[legal_strings.xml](https://github.com/corona-warn-app/cwa-app-android/blob/a29bfd73a414e5f0b550c0cc1040275299029d57/Corona-Warn-App/src/main/res/values/legal_strings.xml#L19) | submission_consent_your_consent_subsection_tapping_agree | By tapping on “Accept”
[legal_strings.xml](https://github.com/corona-warn-app/cwa-app-android/blob/a29bfd73a414e5f0b550c0cc1040275299029d57/Corona-Warn-App/src/main/res/values/legal_strings.xml#L84) | ppa_onboarding_more_info_body | do not tap on “Accept”
[strings.xml](https://github.com/corona-warn-app/cwa-app-android/blob/a29bfd73a414e5f0b550c0cc1040275299029d57/Corona-Warn-App/src/main/res/values/strings.xml#L556) | onboarding_ppa_consent_donate_button | "Share Data"

**DE**
File | String name | Contents
--- | --- | ---
[legal_strings.xml](https://github.com/corona-warn-app/cwa-app-android/blob/a29bfd73a414e5f0b550c0cc1040275299029d57/Corona-Warn-App/src/main/res/values-de/legal_strings.xml#L18) | submission_consent_your_consent_subsection_tapping_agree |Durch Antippen von „Einverstanden“
[legal_strings.xml](https://github.com/corona-warn-app/cwa-app-android/blob/a29bfd73a414e5f0b550c0cc1040275299029d57/Corona-Warn-App/src/main/res/values-de/legal_strings.xml#L83) | ppa_onboarding_more_info_body |tippen Sie bitte nicht „Einverstanden“ an
[strings.xml](https://github.com/corona-warn-app/cwa-app-android/blob/a29bfd73a414e5f0b550c0cc1040275299029d57/Corona-Warn-App/src/main/res/values-de/strings.xml#L545) | onboarding_ppa_consent_donate_button | "Daten spenden"

**Comment by MikeMcC399** [comment]
It seems that the naming of the button has been changed in release/1.14.x so that the text now agrees with the button labelling:

**EN**
File | String name | Contents
--- | --- | ---
[legal_strings.xml](https://github.com/corona-warn-app/cwa-app-android/blob/d5def0f86f6e4484caaf22dca72d6f073e9d6884/Corona-Warn-App/src/main/res/values/legal_strings.xml#L19) | submission_consent_your_consent_subsection_tapping_agree | By tapping on “Accept”
[legal_strings.xml](https://github.com/corona-warn-app/cwa-app-android/blob/d5def0f86f6e4484caaf22dca72d6f073e9d6884/Corona-Warn-App/src/main/res/values/legal_strings.xml#L84) | ppa_onboarding_more_info_body | do not tap on “Accept”
[strings.xml](https://github.com/corona-warn-app/cwa-app-android/blob/d5def0f86f6e4484caaf22dca72d6f073e9d6884/Corona-Warn-App/src/main/res/values/strings.xml#L556) | onboarding_ppa_consent_donate_button | "Accept"

**DE**
File | String name | Contents
--- | --- | ---
[legal_strings.xml](https://github.com/corona-warn-app/cwa-app-android/blob/d5def0f86f6e4484caaf22dca72d6f073e9d6884/Corona-Warn-App/src/main/res/values-de/legal_strings.xml#L18) | submission_consent_your_consent_subsection_tapping_agree |Durch Antippen von „Einverstanden“
[legal_strings.xml](https://github.com/corona-warn-app/cwa-app-android/blob/d5def0f86f6e4484caaf22dca72d6f073e9d6884/Corona-Warn-App/src/main/res/values-de/legal_strings.xml#L83) | ppa_onboarding_more_info_body |tippen Sie bitte nicht „Einverstanden“ an
[strings.xml](https://github.com/corona-warn-app/cwa-app-android/blob/d5def0f86f6e4484caaf22dca72d6f073e9d6884/Corona-Warn-App/src/main/res/values-de/strings.xml#L545) | onboarding_ppa_consent_donate_button | "Einverstanden"

**Comment by dsarkar** [comment]
@MikeMcC399 Wow! OK, I will forward all this to the ticket for the devs. Many thanks.

**Comment by MikeMcC399** [comment]
@dsarkar 
Maybe the German screen is OK if it is read differently to the English one? I think the English texts are clearer, but probably the German texts are acceptable.

At the top it says
"Ihr Einverständnis" which corresponds to the label on the button "EINVERSTANDEN".

The text hasn't been changed in branch/2.0.x.

Do you think we should keep this open, or should we close it?

**Comment by dsarkar** [comment]
FYI PR: https://github.com/corona-warn-app/cwa-app-android/pull/3196

**Comment by MikeMcC399** [comment]
@dsarkar 
There is no change to related German text in Android branch [release/2.3.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.3.x) at this time.

**Comment by MikeMcC399** [comment]
This issue has not been addressed in the 2.3.2 release.

If the English text were to be translated into German (see above screen shots in https://github.com/corona-warn-app/cwa-documentation/issues/538#issuecomment-787947721), then the issue would be fixed.

**Comment by MikeMcC399** [comment]
@dsarkar 
Would you remove the Fix 2.3 label here?

**Comment by MikeMcC399** [comment]
The remaining issue described here was fixed in Android 2.6 by PR https://github.com/corona-warn-app/cwa-app-android/pull/3640.

**Comment by dsarkar** [comment]
Good morning @MikeMcC399,  iOS Fix 2.3 and Android Fix 2.6 apparently.
