### ISSUE TITLE
RAJKO ANDJELKOVIC ANDJERAJ

### ISSUE THREAD

**Issue by andjeraj** [corona-warn-app/cwa-documentation#539]

**Comment by Ein-Tim** [comment]
Hi @andjeraj 👋

It seems like this was an mistake or you wanted to open this issue somewhere else.
Please close this issue. 

If you have any questions or found bugs in the German Corona-Warn-App, feel free to open a new issue where you fill out the issue template. 

Thanks and stay safe!

**Comment by heinezen** [comment]
I don't think we'll get more information here...

@andjeraj If you have an issue or a question please consider making a new issue. I will close this one because there's no content in here.

----
Corona-Warn-App Open Source Team
