### ISSUE TITLE
Links to Bundespresseamt failing in npm checklinks

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#542]
## Where to find the issue
Checks carried out by
https://github.com/corona-warn-app/cwa-documentation/blob/master/.github/workflows/checks.yml
on pull_request

## Describe the issue

`npm run-script checklinks`
is failing at
```
[✖] https://www.bundesregierung.de/breg-de/bundesregierung/bundespresseamt → Status: 503
[✖] https://www.bundesregierung.de/breg-en/federal-government/federal-press-office → Status: 503
```

See log https://github.com/corona-warn-app/cwa-documentation/actions/runs/624187503.

According to https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
`503 `means Service Unavailable

## Suggested change

Both pages

- https://www.bundesregierung.de/breg-de/bundesregierung/bundespresseamt
- https://www.bundesregierung.de/breg-en/federal-government/federal-press-office

are displayed without error when manually accessed via Google Chrome.

I suggest monitoring the situation and if the error has not cleared by tomorrow, then report the error to BPA.

**Comment by MikeMcC399** [comment]
I checked https://www.bundesregierung.de/ with markdown-link-check and it also fails with an http 503 error.

There is something making the whole website of the Bundesregierung incompatible with markdown-link-check.

The links to  https://www.bundesregierung.de/ were not causing a problem in PR https://github.com/corona-warn-app/cwa-documentation/pull/523 from Feb 2, 2021 as shown by the log https://github.com/corona-warn-app/cwa-documentation/runs/1813934822. Something has changed in the last month to cause the check to fail.

**Comment by MikeMcC399** [comment]
The paragraph 

> The "Corona-Warn-App" logo is a registered trademark of The Press and Information Office of the Federal Government. For more information please see [bundesregierung.de](https://www.bundesregierung.de/breg-en/federal-government/federal-press-office).

in https://github.com/corona-warn-app/cwa-documentation/blob/master/README.md

and 

> Das "Corona-Warn-App"-Logo ist eine registrierte Wort-/Bildmarke des Presse- und Informationsamts der Bundesregierung. Weitere Informationen finden Sie unter [bundesregierung.de](https://www.bundesregierung.de/breg-de/bundesregierung/bundespresseamt).

in https://github.com/corona-warn-app/cwa-documentation/blob/master/translations/README.de.md

are causing the http error `503 Service unavailable` to be returned to the `markdown-link-check` which in turn causes the build check to fail.

I couldn't find out the reason for the failure. Both of the links work correctly when accessed manually.

If nothing is changed then all commits to this repository will continue to fail the Build (pull_request) checks in future. Unless somebody has a better idea, the Bundespresseamt (Presse- und Informationsamt der Bundesregierung) probably needs to be contacted for assistance.

**Comment by MikeMcC399** [comment]
@dsarkar 

I found the root cause. 😄 The Bundesregierung's website has implemented additional security.

When `markdown-link-check` executes an https GET request to https://www.bundesregierung.de/breg-en
the site returns https status code 503 (Service Unavailable) and it returns page data starting with 

`<!DOCTYPE html><html><head><title>Security Check</title>`

![image](https://user-images.githubusercontent.com/66998419/110646402-284c0100-81b7-11eb-8484-e6ec98961c34.png)

**Comment by MikeMcC399** [comment]
@dsarkar 

markdown-link-check allows disabling checks for parts of the text. I tested that this works and if you would like I can submit a PR to stop the link checking failing.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for analysing this issue. I will check internally if your fix will be accepted.

**Comment by MikeMcC399** [comment]
@dsarkar 
OK. I will submit a PR anyway, since I already did the work when I tested it.

If it is not acceptable, you can close it.
