### ISSUE TITLE
PHA public keys

### ISSUE THREAD

**Issue by ale5000-git** [corona-warn-app/cwa-documentation#543]
## Your Question
Hi,
where can I find the PHA public keys for a custom verification of the exposure key files provided by server?

**Comment by Ein-Tim** [comment]
Hey @ale5000-git 

Could you maybe let us know to which document/figure you're referring? Thanks.

**Comment by ale5000-git** [comment]
I'm referring to the verification of diagnosis keys, [this](https://github.com/microg/GmsCore/pull/1391/files).

**Comment by Ein-Tim** [comment]
Okay, I'm not into the microg implementation at all so I sadly can't help you any further here.
Any ideas @MikeMcC399?

**Comment by ale5000-git** [comment]
The problem isn't the implementation, is the public key that is missing.

**Comment by ale5000-git** [comment]
The problem isn't the implementation, is the public key that is missing.
The author was able to get the public key used by the Swiss app, it would be nice to have also the public key of the German app.

**Comment by Ein-Tim** [comment]
Okay. The distribution is documented here: https://github.com/corona-warn-app/cwa-server/blob/main/docs/DISTRIBUTION.md

**Comment by ale5000-git** [comment]
Thanks, I will look in that repo.
