### ISSUE TITLE
Release 2.0 & 2.1

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-documentation#544]
The following links should give some insights what is (probably) going to come in future CWA releases, since there is no roadmap published currently. 

Release 1.15 (Roll-out started 24.03.2021)
---
[EXPOSUREAPP-5499](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5499)

- Blog https://www.coronawarn.app/en/blog/2021-03-24-corona-warn-app-version-1-15.
- follow-on bug fix release
  - [iOS v1.15.2-RC0]( https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.15.2-RC1)
  - [Android v1.15.2-RC0](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.15.2-RC0).
- **iOS**
  - Translation PR: https://github.com/corona-warn-app/cwa-app-ios/pull/2089
  - Feature PR: https://github.com/corona-warn-app/cwa-app-ios/pull/2090
  - Translation Changes: https://github.com/corona-warn-app/cwa-app-ios/pull/2117
  - follow-on bug fix release 
- **Android**
  -  ...

---

Release 2.0 (Roll out 2.0.3 started 21.04.2021)
---
 [EXPOSUREAPP-5787](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5787)
EXPOSUREAPP-6554 2.0.3

- Draft documentation [event_registration.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/event_registration.md).
- Info screen PR
  - iOS EXPOSUREAPP-5590 https://github.com/corona-warn-app/cwa-app-ios/pull/2255 
  - Android EXPOSUREAPP-5571 https://github.com/corona-warn-app/cwa-app-android/pull/2666
  - iOS Wording changes for new version features 2.0 https://github.com/corona-warn-app/cwa-app-ios/pull/2372/files

Release 2.1
---
- [Info screen to announce new release features for 2.1](https://github.com/corona-warn-app/cwa-app-ios/pull/2370/files)

**Comment by Ein-Tim** [comment]
@dsarkar 
May I ask you (once again) to update this to reflect that CWA 1.15 was released yesterday and that the next version will be called 2.0 instead of 1.16?

Thank you! 🙂

**Comment by MikeMcC399** [comment]
I am struggling a little to understand the purpose of this issue!

**Comment by ndegendogo** [comment]
@MikeMcC399 try to follow the links to the PR.
In my understanding it gives us a preview on the features that we may expect in the upcoming version.

**Comment by dsarkar** [comment]
@Ein-Tim Indeed, 2.0 follows 1.15. 
@MikeMcC399 @ndegendogo Indeed, rough idea was to give some insights what is (probably) going to come, since there is no roadmap published currently.

**Comment by ndegendogo** [comment]
> Indeed, rough idea was to give some insights what is (probably) going to come, since there is no roadmap published currently.

@dsarkar and I appreciate this idea very much, indeed!

**Comment by MikeMcC399** [comment]
@dsarkar 
A couple of suggestions:
1. Add a sentence at the beginning of the issue to explain the purpose.
2. For 2.0 add a link to the draft documentation [event_registration.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/event_registration.md).
3. Since 1.15.1 is released, maybe link to the blog https://www.coronawarn.app/en/blog/2021-03-24-corona-warn-app-version-1-15.
4. For Android it looks like there may be a follow-on bug fix release [v1.15.2-RC0](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.15.2-RC0).

@ndegendogo @Ein-Tim @dsarkar 
Thanks for explaining to me!

**Comment by Ein-Tim** [comment]
> 4. For Android it looks like there may be a follow-on bug fix release v1.15.2-RC0.

iOS seems to become a version 1.15.2 too:
https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.15.2-RC1

**Comment by MikeMcC399** [comment]
@dsarkar 
2.0 is no longer a future release.

**Comment by Ein-Tim** [comment]
Now is 2.1 no longer a future release 😄

**Comment by ndegendogo** [comment]
Thanks for all these new amazing features.
👍😀

**Comment by heinezen** [comment]
Everything here has been releases :)

----
Corona-Warn-App Open Source Team
