### ISSUE TITLE
Discrepancy between iOS and Android app in the contact diary comment info screen

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#548]
## Where to find the issue

iOS [says](https://github.com/corona-warn-app/cwa-app-ios/blob/4f8de21027aebf3175626650f4756c904710c739/src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings#L1843):

"Write down ***additional circumstances of your encounter or stay here that could have an effect on your risk of infection***, for example, how close you were to other people ***and what you did*** (examples: “sat close together”, “played sports”, “little space”, “we sang”).
***These notes can help you refresh your memory later. If necessary, they will also let you warn the people you have been with at an early stage, as well as help the public health authorities trace potential chains of infection.***"

Android [says](https://github.com/corona-warn-app/cwa-app-android/blob/86f032656e1268690de179bdc5fd91510c2b8e45/Corona-Warn-App/src/main/res/values-en/contact_diary_strings.xml#L123):

"Write down ***the circumstances that could result in an increased risk,*** for example, how close you were to other people or things ***you did that could affect the air quality*** (examples: “sat close together”, “played sports”, “little space”, “we sang”).
***If you become infected, this information can also help the public health authority trace potential chains of infection.***"

**Same for German, iOS also differs from Android.**

## Describe the issue
The iOS and the Android app show different explanation in the `diary comment info screen`.

## Suggested change
Align the texts. 
IMHO, the one from Android sounds better. 

## Steps to reproduce (iOS)

1. Open the Contact Journal
2. Add a new person/place 
3. Click on the little "i"
4. Read the text, which differs from iOS to Android

Edit:
In the first post here I thought that the iOS text is wrong. But it isn't, so I edited this issue. 

---
Internal Tracking ID: [EXPOSUREAPP-5890](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5890)

**Comment by heinezen** [comment]
@Ein-Tim 

Thanks. I've added the info to Jira (ticket ID: [5890](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5890)).

I also slightly edited your comment to make the differences more visible. Additionally, I've removed the "You can enter notes here that will help you to better estimate your risk of infection." part because that is the same on both Android and iOS. On Android, the info message is just split into 2 parts.

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Thank you @heinezen!

**Comment by dsarkar** [comment]
@Ein-Tim FYI PR to correct Android text:
https://github.com/corona-warn-app/cwa-app-android/pull/2667

**Comment by Ein-Tim** [comment]
Thanks @dsarkar. Will they align the German version too?

**Comment by dsarkar** [comment]
@Ein-Tim OK, will have to check. Stand by.

**Comment by Ein-Tim** [comment]
@dsarkar 

Haha, that's embarrassing now...
I meant English. Sorry 😅🤪

**Comment by dsarkar** [comment]
@Ein-Tim I think the English text will be aligned via translation system, but I will cross-check.

**Comment by Ein-Tim** [comment]
Could somebody please confirm that this has been fixed under Android? Thanks!

**Comment by Ein-Tim** [comment]
I can see the change in https://github.com/corona-warn-app/cwa-app-android/blob/2d996435020bec87a949c4d24f91869dbcaace49/Corona-Warn-App/src/main/res/values-en/contact_diary_strings.xml#L134. 


Closing this as fixed.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks!
