### ISSUE TITLE
Inaccurate help for some 7-Day statistics trends

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#550]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue
This is a follow-on report from "Difference in trends for 7-day incidence and 7-day average" https://github.com/corona-warn-app/cwa-documentation/issues/528 posted by @nilsalex (clarified and closed). 
This issue is also related to "Suspicious downwards trend for 7-Day R Value" https://github.com/corona-warn-app/cwa-documentation/issues/535 (also clarified and closed).

## Technical details

- First reported on App version: CWA Android 1.14.3 and CWA iOS 1.14.4
- Reviewed unchanged in CWA Android 2.12.0-RC0

## Describe the bug

The help text for statistics does not correctly and unambiguously describe how the trends for the 7-Day Incidence and the 7-Day R Value are calculated.

![Key Figures Trend EN DE](https://user-images.githubusercontent.com/66998419/111198907-6898ee00-85c0-11eb-8e04-734bd3f61c11.jpg)

The information text for "Key Figures" says "The arrow direction indicates whether the trend is increasing, decreasing, or remaining steady – that is, demonstrates a deviation of less than 1% compared to the previous day or 5% compared to the previous week. The color indicates this trend as positive (green), negative (red), or neutral (gray). The trend compares the value from the previous day with the value from two days ago or, for the 7-day trends, the average value from the last 7 days with the average value from the 7 days prior to that."

Each of the values showing a trend has a label containing the text "7-Day" so it seems that all the trends should be calculated using the value from one week previously with a 5% band.

1. Confirmed New Infections, 7-Day Average: This follows the 5% rule correctly.
2. Warnings by App Users, 7-Day Average: 5% is consistent with the variable naming `appDownloads7daysTrend5percent` in [StatisticsJsonStringObject.java#L19](https://github.com/corona-warn-app/cwa-server/blob/22669f3cfdac909fe79d9f2bb99fd065ecfb124f/services/distribution/src/main/java/app/coronawarn/server/services/distribution/statistics/StatisticsJsonStringObject.java#L19).
3. 7-Day Incidence: The 5% rule is not being used for the 7-Day Incidence. For this statistical value the trend is calculated using the value from two days ago. See confirmation from @GisoSchroederSAP in https://github.com/corona-warn-app/cwa-documentation/issues/528#issuecomment-781462214.
4. 7-Day R Value: 5% is **not** consistent with the variable naming `sevenDayRvaluePublishedTrend1percent` in [StatisticsJsonStringObject.java#L73](https://github.com/corona-warn-app/cwa-server/blob/22669f3cfdac909fe79d9f2bb99fd065ecfb124f/services/distribution/src/main/java/app/coronawarn/server/services/distribution/statistics/StatisticsJsonStringObject.java#L73). Also confirmed in https://github.com/corona-warn-app/cwa-documentation/issues/535#issuecomment-799024445.

## Steps to show help

1. Open CWA and scroll down on the Start Screen to "Confirmed New Infections".
2. Tap the :information_source: icon on the top right of the tile to display the Information "Key Figures, Explanation of nationwide statistics", then scroll down to the Trend section.

## Expected behavior

The information text for "Key Figures" should correctly describe how the trend is calculated for all values. For 7-Day Incidence and 7-Day R Value  the text should make it clear that the trend calculation is based on comparing the value from the previous day with the value from two days ago using a 1% steady band.

Comparison<br>Value \ Steady band % | Daily<br>1% | Weekly<br>5%
--- | --- | ---
Confirmed New Infections<br>7-Day Average | | ✔️ 
Warnings by App Users<br>7-Day Average | | ✔️
7-Day Incidence | ✔️|
7-Day R Value | ✔️|

## Possible Fix

Change the description in the string `statistics_explanation_trend_text` from [Corona-Warn-App/src/main/res/values/strings.xml](https://github.com/corona-warn-app/cwa-app-android/blob/66055425822758f2575de50d7e82b371bb81370c/Corona-Warn-App/src/main/res/values/strings.xml#L1525) in Android and in the equivalent string in iOS.

It should be clear that the 7-Day Incidence and for the 7-Day R Value trend calculations use the comparison between the previous day and two days ago.

For Android, change the string `statistics_explanation_trend_text`:

**EN**
[strings.xml#L1525](https://github.com/corona-warn-app/cwa-app-android/blob/66055425822758f2575de50d7e82b371bb81370c/Corona-Warn-App/src/main/res/values/strings.xml#L1525)

from

"The trend compares the value from the previous day with the value from two days ago or, for the 7-day trends, the average value from the last 7 days with the average value from the 7 days prior to that."

to

"The trend compares the value from the previous day with the value from two days ago or, for the values labelled '7-day average' , the average value from the last 7 days with the average value from the 7 days prior to that."

**DE**
[strings.xml#L1511](https://github.com/corona-warn-app/cwa-app-android/blob/66055425822758f2575de50d7e82b371bb81370c/Corona-Warn-App/src/main/res/values-de/strings.xml#L1511)

from

"Der Trend vergleicht den Wert vom Vortag mit dem Wert von vor zwei Tagen bzw. für die 7-Tage-Trends den Mittelwert der letzten 7 Tage mit dem der vorausgegangenen 7 Tage."  

to

"Der Trend vergleicht den Wert vom Vortag mit dem Wert von vor zwei Tagen bzw. für die Werte, die als 7-Tage-Mittelwert bezeichnet sind, der Wert der letzten 7 Tage mit dem der vorausgegangenen 7 Tage." 

For iOS a similar change should be done.

## Additional context

See also [FAQ: Trend differences between 7-Day Average and 7-Day Incidence](https://github.com/corona-warn-app/cwa-website/issues/904) for a suggestion about modifying the FAQ entry https://www.coronawarn.app/en/faq/#further_details. This only deals with the 7-Day Incidence issue, not with the question about the 7-Day R Value.

---

Internal Tracking ID: [EXPOSUREAPP-5225](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5225) from https://github.com/corona-warn-app/cwa-documentation/issues/528

**Comment by MikeMcC399** [comment]
@GisoSchroederSAP confirmed in https://github.com/corona-warn-app/cwa-documentation/issues/535#issuecomment-799024445 about the 7-Day R-Value using the previous day as a comparison.

I have updated the original post to now include concrete text for a possible fix.

Where the help text in English refers to the "7-day trends" it does not mean all values labelled "7-Day", it means just the ones labelled "7-Day Average". The other two values, "7-Day Incidence" and "7-Day R Value" are also 7-day trends, but the trends for these two values are calculated based on comparison to the previous day, not to the previous week.

The help text problem can be solved by making the text more precise and by explicitly referring to the values according to their labels "7-Day Average". Only for the values with a label "7-Day Average" are the trends calculated by comparing to one week previously.

**Comment by GisoSchroederSAP** [comment]
Hi @MikeMcC399 ,
just for the records: Yes, we now have confirmation an deeper insight. Yes, the text on the information screen in the App need to be adjusted, we all agree.
However, one more "wording" in your last post: Let's please differentiate the _value_ from the _trend indicator_ (the arrow with color): **None** of the "7-Day Incidence" and the "7-Day R value" by themselves **are** trends, they are _values_, just calculated on a given day for a 7-day period.. The _trend_ for both metrics appears only out of the comparison to the values with the ones from the previous day, respectiveley.

So, I assume, we are back to the "naming convention"  - if someone reads "7-day ???" on different metrics this often is misleading to the understanding all those numbers reflect (the same) trends.

Anyway, we are working hard to document the FAQ and to adjust the App text blocks. Thanks for your continuous contribution here, this is much appreciated!!!

**Comment by MikeMcC399** [comment]
Hi @GisoSchroederSAP 

You are right of course that the values and the trends of the values are different entities. The values of the trends are not displayed in numerical terms only in color and arrow direction.

> So, I assume, we are back to the "naming convention" - if someone reads "7-day ???" on different metrics this often is misleading to the understanding all those numbers reflect (the same) trends.

That is exactly the problem, that the help text is open to wrong interpretation. The help text needs to be written so that there is a high likelihood that any normal reader will interpret it correctly.

> Anyway, we are working hard to document the FAQ and to adjust the App text blocks.

Good to hear! Thank you!

**Comment by MikeMcC399** [comment]
@GisoSchroederSAP 
I updated the original submission to make it clearer about values and trends of values.

**Comment by MikeMcC399** [comment]
The trend examples with icons were addressed through https://github.com/corona-warn-app/cwa-documentation/issues/659, however the problem with the text description in this issue (https://github.com/corona-warn-app/cwa-documentation/issues/550) remains unsolved.

**Comment by MikeMcC399** [comment]
The blog article https://www.coronawarn.app/en/blog/2021-08-05-statistictiles/ confirms in detail about how the trend comparisons are made for each of the values. 

There is still no change in the string `statistics_explanation_trend_text` in strings.xml, in the current or any future branch, so the in-app help is still not precise.

**Comment by MikeMcC399** [comment]
In Android [release/2.13.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.13.x) PR https://github.com/corona-warn-app/cwa-app-android/pull/4209 "Update info screen for statistics (EXPOSUREAPP-9837)" changes the help text:

https://github.com/corona-warn-app/cwa-app-android/blob/579f56aebf52d94aca81a477ffe21f459fe2a19a/Corona-Warn-App/src/main/res/values/strings.xml#L1485-L1486

`statistics_explanation_trend_text`
"The trend compares the value from the previous day with the value from two days ago (for the 7-day incidence, 7-day hospitalization incidence, COVID-19 patients in intensive care units, 7-day R value) or, for the 7-day trends, the average value from the last 7 days with the average value from the 7 days prior to that (for the 7-day mean value of confirmed new infections, warnings by app users, vaccine doses administered). The respective version of the data as initially published is used; subsequent updates are not taken into account.

The arrow direction indicates whether the trend is increasing, decreasing, or remaining steady – that is, demonstrates a deviation of less than 1% compared to the previous day or 5% compared to the previous week (taking decimal places into account). The color indicates this trend as positive (green), negative (red), or neutral (gray)."

---
This change resolves the issue for CWA Android in the planned 2.13 release.

It seems also that the issue has already been resolved for CWA iOS in the 2.12 release (see https://github.com/corona-warn-app/cwa-app-ios/pull/3585).

**Comment by MikeMcC399** [comment]
This issue was resolved in Android in the 2.12.2 release, however there is a remaining formatting issue logged in https://github.com/corona-warn-app/cwa-app-android/issues/4280.

It should be fully resolved in the 2.13 release.

**Comment by MikeMcC399** [comment]
The formatting issue in https://github.com/corona-warn-app/cwa-app-android/issues/4280 has been resolved with the release of CWA Android 2.13.2.

This issue can now be closed.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for the feedback. Foreared to the internal ticket as well.
