### ISSUE TITLE
[2.0] Will it be possible to create QR-Codes on the website?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#554]
## Your Question
* Documentation File: none
* Line / Paragraph: none
* PR: (only one) https://github.com/corona-warn-app/cwa-app-ios/pull/2218
* Question: 

Will it be possible to create QR codes via the Corona-Warn-App [website](https://www.coronawarn.app/de/)? 
I think this would be quite practical if you want to print the QR code, etc.

**Comment by vaubaehn** [comment]
@Ein-Tim : About printing: this should be possible from app, too, if you have a printing-enabled OS (plug-in or natively)

**Comment by Ein-Tim** [comment]
@vaubaehn 

Yeah, you're right, but think about printers that are connected via cable and not via Wi-Fi (yeah, this is still used in the year 2021 😁).

**Comment by vaubaehn** [comment]
@Ein-Tim 

> but think about printers that are connected via cable and not via Wi-Fi

you're also right - this will probably the most common use case in a professional environment/location/venue, like an office building or a shop or so.

**Comment by thomasaugsten** [comment]
This is not planned in the first version. But you can forward the qr-code poster with the OS share dialog

**Comment by Ein-Tim** [comment]
Thanks @thomasaugsten, moving this to the wishlist: https://github.com/corona-warn-app/cwa-wishlist/issues/399
