### ISSUE TITLE
App and backend prototype implementing blind signatures

### ISSUE THREAD

**Issue by togermer** [corona-warn-app/cwa-documentation#56]
We want to contribute a mechanism for health authorities to report positive tests with minimal effort, so that app users get notified without any delay. To facilitate this we build an app and backend prototype that also implement the authorization mechanism. It uses blind signatures so that only authorized users can upload their tracking keys, while it is still impossible to link user identities to their keys.

We describe our approach in more detail at https://github.com/think-cell/corona where you can also find our app / backend prototype. We would be glad if used (parts of) this as the basis for your reporting mechanism.

**Comment by raethlein** [comment]
Thank you very much for offering us the support / pointing us to your solution. We will mark the resource accordingly so that our development teams could have a look if needed.
