### ISSUE TITLE
How and where to get tested? | Wie und wo kann man sich testen lassen?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#569]
The following list, ordered by region, shall assist to find information regarding SARS-CoV-2 ("COVID"-, "CORONA"-virus) and test-practices/centers. 
The testing centers, which are mentioned on the sites the table below links to, don't have to be connected to the Corona-Warn-App system.
You can find an overview over rapid antigen test centers, which are connected to the Corona-Warn-App, on [map.schnelltestportal.de](https://map.schnelltestportal.de).
This list is maintained by the community and everybody is invited to contribute in expanding this list.
To do so, just write a comment in this issue and we'll add your contributiton to the list.

---

Die folgende, nach Regionen geordnete, Liste soll dabei helfen, Informationen zu SARS-CoV-2 ("COVID"-, "CORONA"-Virus) und Test-Praxen/Zentren zu finden. 
Die Testzentren, die auf den in der Tabelle unten verlinkten Seiten genannt werden, müssen nicht mit dem Corona-Warn-App-System verbunden sein.
Eine Übersicht über Antigen-Schnelltestzentren, die mit der Corona-Warn-App verbunden sind, finden Sie auf [map.schnelltestportal.de](https://map.schnelltestportal.de).
Diese Liste wird von der Community gepflegt und jeder ist eingeladen sich daran zu beteiligen diese Liste zu erweitern.
Um sich daran zu beteiligen, schreiben Sie einfach einen Kommentar in diesem Issue und wir werden die Liste um Ihren Beitrag erweitern.

| Region (DE/EN) | Links |
| --- | --- |
| Deutschland/Germany | [Patientenservice 116117: Corona-Test](https://www.116117.de/de/coronavirus.php#content753) |
| Bayern/Bavaria | [Kassenärztliche Vereinigung](https://www.kvb.de/service/patienten/coronavirus-infektion/) |
| Baden-Württemberg/Baden-Württemberg  | [Kassenärztliche Vereinigung]( https://www.kvbawue.de/index.php?id=1102)
| Berlin/Berlin | [Kassenärztliche Vereinigung](https://www.kvberlin.de/fuer-patienten/corona/covid-19-praxen) |
| Brandenburg/Brandenburg | [Kassenärztliche Vereinigungen](https://www.kbv.de/html/themen_49345.php) & [Coronaportal des Landes Brandenburg](https://corona.brandenburg.de/corona/de/) |
| Bremen/Bremen| [Senatorin für Gesundheit](https://www.gesundheit.bremen.de/gesundheit/corona/corona_ambulanz-32720) |
| Hamburg/Hamburg | [Kassenärztliche Vereinigung](https://www.kvhh.net/de/praxis/verordnung/corona-informationen-fuer-praxen-1/testungen-auf-sars-co-v-2.html) |
| Hessen/Hessen | [Hessisches Ministerium für Soziales und Integration](https://www.corona-test-hessen.de ) |
| Mecklenburg-Vorpommern/ Mecklenburg-West Pomerania | [Kassenärztliche Vereinigung](https://www.kvmv.de/patienten/patienteninformationen/coronavirus) |
|Niedersachsen/Lower Saxony | [Kassenärztliche Vereinigung](https://www.kvn.de/Patienten/Coronavirus/Grundlegendes+zur+Testung+von+Patienten+und+zu+den+Praxisabläufen.html) |
| Nordrhein-Westfalen/North Rhine-Westphalia | [Die Landesregierung Nordrhein-Westfalen](https://www.land.nrw/corona)	|
| Rheinland-Pfalz/Rhineland-Palatinate | [Kassenärztliche Vereinigung](https://www.praxisfinder-rlp.de/corona-anlaufstellen/tabelle) |
| Saarland/Saarland | [Kassenärztliche Vereinigung](https://www.kvsaarland.de/patienteninformationen-coronavirus) |
| Sachsen/Saxony | [Landesportal](https://www.coronavirus.sachsen.de/coronatests-in-sachsen-9448.html) |
| Sachsen-Anhalt/Saxony-Anhalt | [Kassenärztliche Vereinigung](https://www.kvsa.de/praxis/verordnungsmanagement/coronavirus/fieberambulanzen_fiebersprechstunden_testpraxen.html) |
| Schleswig-Holstein/Schleswig-Holstein | [Landesportal](https://www.schleswig-holstein.de/DE/Schwerpunkte/Coronavirus/Allgemeines/TeststationenKarte/teststationen_node.html) |
| Thüringen/Thuringia | [Kassenärztliche Vereinigung](https://www.kv-thueringen.de/corona-test) |

**Comment by di-sc** [comment]
The link for Schleswig-Holstein is not working. I'm getting a 404.

> Schleswig-Holstein/Schleswig-Holstein	[Kassenärztliche Vereinigung](https://www.kvsh.de/coronavirus#c6910)

**Comment by howa-husum** [comment]
Dieser Link scheint für SH der aktuelle zu sein

https://www.schleswig-holstein.de/DE/Schwerpunkte/Coronavirus/Allgemeines/TeststationenKarte/teststationen_node.html

**Comment by Ein-Tim** [comment]
Thanks @di-sc & @howa-husum, I fixed this.

**Comment by MikeMcC399** [comment]
According to https://www.coronawarn.app/en/blog/2021-06-24-cwa-version-2-4/ a rapid test partner search is available on https://map.schnelltestportal.de/.

**Comment by Ein-Tim** [comment]
@MikeMcC399 Thanks. I'll update the OP of this issue to reflect that it's intended to help finding PCR-testing sites.

**Comment by Ein-Tim** [comment]
I would like to discontinue this issue, as the websites we are linking to in the OP have mostly changed from COVID-19 testing exclusive information to more general health information. I therefore provided PR https://github.com/corona-warn-app/cwa-website/pull/3406 which removes this issue from the FAQs. If it is merged, I'll close this issue.

**Comment by Ein-Tim** [comment]
- PR https://github.com/corona-warn-app/cwa-website/pull/3406 has been merged, I'm officially discontinuing this issue now!
