### ISSUE TITLE
[Feature Request] QR code scanner for IDs of (indoor) locations

### ISSUE THREAD

**Issue by medienintegration** [corona-warn-app/cwa-documentation#57]
Virologists point out that the virus appears to spread in over 40% of the infections caused by aerosols, which can remain in the air for up to several hours in closed rooms. I think it could be helpful to create a possibility for restaturants, hairdressers etc. to be part of the tracing process without using a Bluetooth device, e.g. with the help of QR codes.

Guests would scan the respective QR code when entering and leaving such a store and the app would rate the transmitted IDs as contacts. If it turns out that an employee has tested positive for Corona, the IDs would be uploaded to the backend server as infected and all guests who have been in this room in e.g. the past 2 weeks (or five days before the onset of symptoms) will be informed by the app.

Such a solution would require a server that provides IDs based on a public url for the participating shops / locations.

**Comment by tkowark** [comment]
Thanks a lot for your proposal. In the initial version, the app scope will adhere to the [scoping document](./scoping_document.md). 

But, of course, we welcome discussion and ideas around potential future functionality and leave this issue open for others to discuss and refine the idea.

**Comment by egandro** [comment]
We used QR Codes in a lot of projects. 

It can be trolled by a simple photo :)

So you need somehow signed NFC stickers to gain a minimum of security.

- You need a direct contact to NFC stickers (this creates a new hotspot!)
- NFC can also be copied...

I see no possibility implementing this using customer cell phones.

**Comment by medienintegration** [comment]
The possibility of misuse with an insecure technology such as QR codes should of course be considered and evaluated. Perhaps this discussion will help developing a robust concept, possibly with the involvement of health authorities or 'Ordnungsämter' who regularly check the QR codes used.

**Comment by TomTeeJay** [comment]
Thank you @medienintegration. I second this. There are already a lot of 2nd thoughts and well-known Show-Stopper. You have one job, do it accordingly and stop mixing functions.Its very easy to understand:

**With the mixing of functions the discrimination of non-App users increases.** 

 It's also horrific how complexity is increased. 

I also recall this prematurely closed and not understood issue (https://github.com/corona-warn-app/cwa-documentation/issues/23)

But of course I could miss the point, that this could be the strategy right from the beginning. To integrate as much as possible in order to nudge as many as possible. 

Let me say this very clearly: This will not work!

**Comment by sventuerpe** [comment]
@TomTeeJay 

> **With the mixing of functions the discrimination of non-App users increases.**
> 
> It's also horrific how complexity is increased.

On the one hand I agree that things should be kept simple and focused. On the other hand, this project has skipped design exploration and is taking an arbitrarily set approach. It should not surprise us that alternative approaches keep popping up in various forms. This project lacks a design rationale.

**Comment by MalteJ** [comment]
@medienintegration 
Sorry, until the BLE approach is not proven to be ineffective/broken we cannot concentrate on different solutions. I have to close this issue. Feel free to re-open as soon as there is an indication the BLE approach does not work in your sketched environment. But I am pretty sure you have described a perfect setting for BLE contact tracing 😉 

Malte

**Comment by sventuerpe** [comment]
@MalteJ Could the idea of @medienintegration be implemented as a protocol extension based on BLE? Imagine a location participating in contact tracing with its own device(s). If an infected person has visited the location recently, this location becomes exposed and if locations are distinguishable from persons one could in this case notify secondary contacts. 

I have not thought this through – some form of authentication and location-binding will probably be needed and one will have to analyze the privacy implications – but dismissing the entire idea without much discussion seems premature to me.

**Comment by medienintegration** [comment]
@MalteJ I understand that the focus should be on developing the core function. However, the point is not that the BLE approach is ineffective / broken, but that scenarios are conceivable that could save valuable time with the help of QR codes (or stationary devices). In other scenarios, the BLE approach would just not work (simple example: I am in the barber shop with 2 employees and another customer in one room - and I am the only one who has installed the app).

@sventuerpe Actually, stationary BLE devices were my first idea, but after a discussion with a friend, she had the idea with the QR codes, which I find much less problematic. As you mentioned, stationary devices would have to be authenticated. In addition, they should not leave the place, otherwise they would trigger a myriad of "contacts". But maybe someone has an idea for a working solution.

**Comment by darkdragon-001** [comment]
Another situation where the current approach fails, is a chef in a kitchen with access to the meal of a customer but behind a Bluetooth impenetrable barrier (metal kitchen walls, far distance, ...)
