### ISSUE TITLE
Will the log upload be part of the version 2.0 release?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#572]
## Your Question

* Question: 
The log upload was planned to be part of the 1.15 release (see f.e.: https://github.com/corona-warn-app/cwa-app-android/pull/2525 - milestone 1.15). 
For reasons unknown to me, the feature didn't made it into the final version (see: https://github.com/corona-warn-app/cwa-app-android/pull/2580).

Currently, when building the https://github.com/corona-warn-app/cwa-app-ios/tree/release/2.0.x branch locally, I can't see this feature anywhere. Will it be part of version 2.0?

**Comment by dsarkar** [comment]
@Ein-Tim We will try to get an answer.

**Comment by thomasaugsten** [comment]
It is moved to 2.1 because of the high workload for the v2.0

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Thanks for the clarification!

**Comment by Ein-Tim** [comment]
@thomasaugsten Is it still planned for version 2.1 or now for 2.2?

**Comment by Ein-Tim** [comment]
From PRs I saw that it'll be part of version 2.2.
