### ISSUE TITLE
The Corona-Warn-App was installed n ago

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#573]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 3a emulator
- Android version: 11
- App version: 1.15.2

## Describe the bug

The text "days" is missing in the detailed risk information screen, "Period logged" section about how long ago the app was installed, when the locale is set to English. The equivalent German text is correct.

## Steps to reproduce the issue

1. Set device locale to English (United Kingdom)
2. If CWA was installed for longer than 14 days, do a new install of CWA ~~or reset app~~
3. Open CWA, ensure Exposure Logging is active
4. Tap right arrow of risk card
5. Scroll down to "Period Logged"
6. Note the text "The Corona-Warn-App was installed 0 ago."

![Period logged day missing](https://user-images.githubusercontent.com/66998419/113578822-b3d47880-9623-11eb-8681-40ab5cb1171e.jpg)

## Expected behavior

The risk detailed information screen, "Period logged" should show the text:

"The Corona-Warn-App was installed n **days** ago" including the word "days" if the app has been installed during the last 14 days.

## Possible Fix

For Android in the string `risk_details_information_body_period_logged_assessment_under_14_days` 
"The Corona-Warn-App was installed %s ago. Your risk of infection is calculated for the periods during which exposure logging was active. If you have encountered other people and exposure logging was active, your risk of infection is calculated."

"The Corona-Warn-App was installed %s ago."
should be changed to:
"The Corona-Warn-App was installed %s days ago."

For released version v1.15.2:
https://github.com/corona-warn-app/cwa-app-android/blob/c05959b0f0b772d174e3ace55a7811831e889709/Corona-Warn-App/src/main/res/values/strings.xml#L313

The string is also unchanged in release candidate v2.0.0-RC0

https://github.com/corona-warn-app/cwa-app-android/blob/ab4d8ba6685ce20b4b3368abb4e84c3a54f6c9b3/Corona-Warn-App/src/main/res/values/strings.xml#L313

## Additional context

Android and iOS versions seem to use the same string so the text files for both operating systems should be reviewed and corrected.

---
Internal Tracking ID: [EXPOSUREAPP-6205](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6205)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks.  Internal Tracking ID: [EXPOSUREAPP-6205](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6205)

**Comment by MikeMcC399** [comment]
For Android:

PR https://github.com/corona-warn-app/cwa-app-android/pull/2793 fixed https://github.com/corona-warn-app/cwa-app-android/blob/release/2.0.x/Corona-Warn-App/src/main/res/values/strings.xml

PR https://github.com/corona-warn-app/cwa-app-android/pull/2790 fixed https://github.com/corona-warn-app/cwa-app-android/blob/release/2.0.x/Corona-Warn-App/src/main/res/values-en/strings.xml

**Comment by MikeMcC399** [comment]
This issue has been fixed in CWA Android 2.0.3.

![image](https://user-images.githubusercontent.com/66998419/115546513-6acc2780-a2a5-11eb-8973-579840285038.png)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks!
