### ISSUE TITLE
Ermittlungszeitraum text grammar for installation older than 14 days

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#574]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 3a emulator
- Android version: 11
- App version: 1.15.2 (also present in release/2.0.x branch)

## Describe the bug

In the text:

"Wenn die Risiko-Ermittlung zu Zeiten in denen sie andere Personen getroffen haben aktiv war, kann die Berechnung des Infektionsrisikos für diesen Zeitraum erfolgen."

there are commas missing and "sie" is not capitalized to refer to the second person plural.

## Steps to reproduce the issue

1. Set device locale to Deutsch (Deutschland)
2. Open CWA on device where the app was installed more than 14 days ago.
3. Ensure that "RISIKO-ERMITTLUNG AKTIV" is showing
4. Tap right-arrow in risk status tile (showing Risiko)
5. Scroll down to "Ermittlungszeitraum" and note the text in the last paragraph.

Below for comparison, the text on the left from a device where the app was installed more than 14 days ago, and on the right from a device where the app was installed more recently.

![Ermittlungszeitraum grammar](https://user-images.githubusercontent.com/66998419/113582790-19773380-9629-11eb-8411-a52dd44519c1.jpg)

## Expected behavior

The text should be grammatically correct.

## Possible Fix

This concerns the string `risk_details_information_body_period_logged_assessment_over_14_days`  https://github.com/corona-warn-app/cwa-app-android/blob/25a18cfd65783846e8df84b21cbf305fc6298434/Corona-Warn-App/src/main/res/values-de/strings.xml#L311

https://mentor.duden.de/ suggests adding commas, and changing "sie" to "Sie" leads to:

"Wenn die Risiko-Ermittlung zu Zeiten, in denen Sie andere Personen getroffen haben, aktiv war, kann die Berechnung des Infektionsrisikos für diesen Zeitraum erfolgen."

This however seems a little awkward. Please consider using instead the longer text from `risk_details_information_body_period_logged_assessment_under_14_days` https://github.com/corona-warn-app/cwa-app-android/blob/25a18cfd65783846e8df84b21cbf305fc6298434/Corona-Warn-App/src/main/res/values-de/strings.xml#L309

"Das Infektionsrisiko wird für Zeiträume berechnet, in denen die Risiko-Ermittlung aktiv ist. Wenn Sie andere Personen getroffen haben und die Risiko-Ermittlung aktiv war, wird Ihr Infektions-Risiko berechnet."

## Additional context

I found the same string in the iOS repository, so I assume the issue affects both Android and iOS.

---
Internal Tracking ID: [EXPOSUREAPP-6204](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6204)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. Internal Tracking ID: [EXPOSUREAPP-6204](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6204)

**Comment by dsarkar** [comment]
PR https://github.com/corona-warn-app/cwa-app-android/pull/2747

**Comment by dsarkar** [comment]
PR iOS  https://github.com/corona-warn-app/cwa-app-ios/pull/2364

**Comment by MikeMcC399** [comment]
The issue is resolved in CWA Android 2.0.3.

![image](https://user-images.githubusercontent.com/66998419/115543305-846b7000-a2a1-11eb-93ae-fd1a70edd974.png)

I will leave this issue open temporarily in case there is any feedback from the iOS implementation, although I assume that due to https://github.com/corona-warn-app/cwa-app-ios/pull/2364 the issue is also fixed in the iOS release.

**Comment by Ein-Tim** [comment]
Confirm fixed under iOS too.

**Comment by MikeMcC399** [comment]
Thanks to @Ein-Tim for iOS checking.

Now closing.

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim Thanks!
