### ISSUE TITLE
Bug template missing

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#575]
Please add a bug template to this repository.

https://github.com/corona-warn-app/cwa-app-android/blob/main/.github/ISSUE_TEMPLATE/01_bugs.md includes the text

`* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)`

however there is no category of new item corresponding to an iOS / Android bug in the documentation repository. The nearest is "Documentation issue" and this template does not lend itself to reporting a software bug.

**Comment by Ein-Tim** [comment]
FYI: The iOS template doesn't include the text quoted by you
I'll open an issue in the iOS repo requesting to match iOS and Android issue templates.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> FYI: The iOS template doesn't include the text quoted by you
I'll open an issue in the iOS repo requesting to match iOS and Android issue templates.

Strange that it is one-sided. Thank you for noticing and taking action. 👍🏻

**Comment by Ein-Tim** [comment]
Templates are matched now: https://github.com/corona-warn-app/cwa-app-ios/pull/2348

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> Templates are matched now

It seems that the updated iOS templates will get activated when v2.0 is released since the changes haven't been merged into the default branch.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Yeah, but that's probably ok, or?  Sorry for highjacking this issue.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Perhaps you should merge into the default branch https://github.com/corona-warn-app/cwa-app-ios/tree/release/2.1.x ?

I don't want to get actively involved in PRs for iOS, since I don't have an iOS device and I try to stay away from iOS problems unless they also affect Android, so you are not "hijacking" anything here. I had no plans to address the issue myself. You noticed the issue and you have taken action on it.

As far as the bug template in this repository (https://github.com/corona-warn-app/cwa-documentation) is concerned, I prefer to let the Open Source Team decide how they want to handle it. I would not have the privileges to add a new template in any case.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Is the default branch the one that decides which templates are used or is it the main branch? 

When I opened the PR the default branch was `release/2.0.x` so they've changed this during my PR waited for review...

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> Is the default branch the one that decides which templates are used or is it the main branch?

It would be best if you check with the people responsible for the iOS repository.

**Comment by heinezen** [comment]
Added in https://github.com/corona-warn-app/cwa-documentation/pull/620
