### ISSUE TITLE
Unclear text on "Your Consent" screen after scanning a QR code

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#576]
## Where to find the issue
Inside  of the app's submission flow, see "Steps to reproduce the issue".

## Steps to reproduce the issue

**Please note that these are the steps on an iOS Device with CWA version 1.15.2.**

1. Open the Corona-Warn-App
2. Click "Next Steps" on the "Have you been tested?" box
3. Click on "Test with QR Code"
4. Tap on "Accept" 
5. Click on "Share Once"
6. Scan a QR Code with a pending test result
7. Scroll to the bottom
8. Click on "Consent "Warn others" granted"

## Describe the issue
The app shows [this](https://user-images.githubusercontent.com/67682506/113866121-35a3dd80-97ad-11eb-9292-8ef718723d13.jpeg) screen after registering a QR code and doing the steps described above. It says 

"Consent

If you have tested positive for coronavirus, the app will share your test result in order to warn other users whom you have encountered." 

If the user now deactivates the toggle on the top ("Warn Others"), the app still shows the same text. The user could think that the app will still automatically share the test result, although he revoked his consent or never gave it.

## Suggested change
Change the text to something like 
EN: "By enabling "Warn Others" above, you consent to the following:" 
DE: "Indem Sie oben "Andere warnen" aktivieren, willigen Sie ein:"

This is how the consent is formulated in the "Data Donation" settings.

## Screen recording

https://user-images.githubusercontent.com/67682506/113782963-4e6fad00-9733-11eb-8182-e53f87af93a6.mp4

## Additional Information

This affects both, English and German.

**English** string in the **iOS** repository (`release/2.0.x`): https://github.com/corona-warn-app/cwa-app-ios/blob/cbff9d62deae78370f4e912b62fd901252f78226/src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.legal.strings#L46

**German** string in the **iOS** repository (`release/2.0.x`): https://github.com/corona-warn-app/cwa-app-ios/blob/cbff9d62deae78370f4e912b62fd901252f78226/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings#L46

**English** string in the **Android** repository (`release/2.0.x`): https://github.com/corona-warn-app/cwa-app-android/blob/ae87cd41a1d48531dae0c749d8406632501d432f/Corona-Warn-App/src/main/res/values/legal_strings.xml#L27

**German** string in the **Android** repository (`release/2.0.x`): https://github.com/corona-warn-app/cwa-app-android/blob/ae87cd41a1d48531dae0c749d8406632501d432f/Corona-Warn-App/src/main/res/values-de/legal_strings.xml#L26

---
Internal Tracking ID: [EXPOSUREAPP-6232](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6232)

**Comment by dsarkar** [comment]
@Ein-Tim Thanks. Internal Tracking ID: [EXPOSUREAPP-6232](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6232)

**Comment by dsarkar** [comment]
@Ein-Tim They have been looking into this issue already. Feedback:

> This is the text which was agreed with the customer, the lawyers and BfDI. It should be clear for the user if he gave his consent or not. If he get's back to the previous screen, it's again clearly stated if consent was given or not.

We suggest closing this issue. Thanks anyway for contributing!

**Comment by Ein-Tim** [comment]
Interesting decision, I don't understand it, since every other "data privacy text" in the app has such a formulation, but okay...

Closing this, thanks @dsarkar!

**Comment by dsarkar** [comment]
@Ein-Tim Thanks a lot anyway!
