### ISSUE TITLE
Inaccuracy in data privacy note for version 2.1

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#584]
## Where to find the issue
In the data privacy note for version 2.1, introduced with [this](https://github.com/corona-warn-app/cwa-app-ios/pull/2457) PR (iOS).

## Describe the issue
The PR https://github.com/corona-warn-app/cwa-app-ios/pull/2457 changed the privacy note to say that iOS 12.5 was the iOS version which introduced the ENF. However, that's not true since Apple only back ported the ENF to iOS 12.5, but iOS 13.0 - 13.4 never had the ENF.
See also https://www.coronawarn.app/de/faq/#ios135.

## Suggested change
Change the privacy note to make clear that iOS 13.0 - 13.4 didn't ever had the ENF.

**Comment by tcfos** [comment]
The app store description of CWA says: "Requires iOS 12.5 or later". The CWA terms of use say: "The App uses the COVID-19 Exposure Notification System implemented by Apple in iOS and Google in Android. This is only available in iOS version 12.5 and upwards [...]".
Both descriptions are not precise wrt. 13.0 – 13.4, but this is a minor inaccuracy.

**Comment by Ein-Tim** [comment]
Okay, agreed. Closing this. Thanks @tcfos!
