### ISSUE TITLE
Outdated risk calculation diagram

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#586]
## Where to find the issue

https://github.com/corona-warn-app/cwa-documentation/blob/master/images/risk_calculation/risk_calculation_enf_v2_overview.pdf 

## Describe the issue

According to https://www.coronawarn.app/en/blog/2021-04-16-corona-warn-app-risk-calculation-further-improved/ dated April 16, 2021 the risk calculation has been changed:

"For app users, this means: Previously, an encounter between two people had to last at least 13 minutes in order to be considered for an encounter with an increased risk (red tile). Now, the app considers encounters of at least 9 minutes. Thus, encounters that represent an actual relevant contact with COVID-19 infected persons can be detected even more accurately and represented accordingly in the app as a warning about an encounter with increased risk"

https://github.com/corona-warn-app/cwa-documentation/blob/master/images/risk_calculation/risk_calculation_enf_v2_overview.pdf  dated 17.03.2021 is therefore now out of date.

## Suggested change

1. Change the 13 minute limit to 9 minute limit in https://github.com/corona-warn-app/cwa-documentation/blob/master/images/risk_calculation/risk_calculation_enf_v2_overview.pdf.

2. Also monitor the implementation of the documentation update from https://github.com/corona-warn-app/cwa-documentation/issues/453.

3. Revise the FAQ entry https://www.coronawarn.app/en/faq/#encounter_19_calc by linking to any updated and correct documentation and diagrams, should they become available.

---
Internal Tracking ID: [EXPOSUREAPP-6547](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6547)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. Internal Tracking ID: [EXPOSUREAPP-6547](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6547)


---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
<img width="748" alt="image" src="https://user-images.githubusercontent.com/1409741/115143246-6d7d1180-a046-11eb-81ba-d995d6dcf82d.png">

**Comment by MikeMcC399** [comment]
@heinezen 
> corona-warn-app/cwa-website#1222 removes the links from the FAQ. I've added a reminder in the initial post to add them back once the PDFs are updated.

That seems a reasonable step. Most users will not be concerned with the exact details of the risk calculation. Those few users who do want all the details should not be given out-of-date information, if this can be avoided.

**Comment by MikeMcC399** [comment]
The PDF diagram [images/risk_calculation/risk_calculation_enf_v2_overview.pdf ](https://github.com/corona-warn-app/cwa-documentation/blob/master/images/risk_calculation/risk_calculation_enf_v2_overview.pdf) carries the date/timestamp 17.03.2021, 14:25.

The diagram [images/solution_architecture/risk_calculation.svg](https://raw.githubusercontent.com/corona-warn-app/cwa-documentation/master/images/solution_architecture/risk_calculation.svg) carries a date/timestamp 23.08.2021, 10:30.

The later diagram has been partially updated to use 9 minutes instead of 13 minutes.

![image](https://user-images.githubusercontent.com/66998419/151024067-ee78ad4d-1678-401d-94a9-dcd6d9a93f2b.png)

On the left-hand side it still shows a 13 minute threshold though:

![image](https://user-images.githubusercontent.com/66998419/151023771-35013371-2503-4bb4-b281-0207c1e2d79f.png)

The diagrams in svg and PDF format should both be corrected and re-published.

**Comment by MikeMcC399** [comment]
The contents of both the following files has been corrected and they now carry a timestamp 25.01.2022, 18:00:

- PDF diagram [images/risk_calculation/risk_calculation_enf_v2_overview.pdf ](https://github.com/corona-warn-app/cwa-documentation/blob/master/images/risk_calculation/risk_calculation_enf_v2_overview.pdf)

- SVG format diagram [images/solution_architecture/risk_calculation.svg](https://raw.githubusercontent.com/corona-warn-app/cwa-documentation/master/images/solution_architecture/risk_calculation.svg)
