### ISSUE TITLE
Abbreviation CWA confuses

### ISSUE THREAD

**Issue by alanrick** [corona-warn-app/cwa-documentation#588]
## Technical details

- iPhone
- iOS 14.4.2
- App version: 2.03

## Describe the bug
The "what's new" section starts off by referring to the "CWA". The response of a friend who'd reinstalled the app as a consequence of my pressure asked **"what the * is a CWA?"**

## Steps to reproduce the issue
![image](https://user-images.githubusercontent.com/7034358/115683626-ee921c80-a356-11eb-8e49-61042066ddbf.jpeg)

## Expected behaviour

Assume users are non-experts since the app only needs to run in the background in most cases. 

## Possible Fix

Suggestion:
_The CWA now enables..._
-->
_This App now enables..._

## Additional context
Difficult to check if this is a duplicate as searching for CWA on GitHub produces loads of false positives.  Incidentally, searching my iPhone for _CWA_ did not discover this App.

---
Internal Tracking ID: [EXPOSUREAPP-6643](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6643)

**Comment by Ein-Tim** [comment]
@dsarkar 

I assume yes. This particular case can't be fixed unless there's a hot fix/patch version of CWA version 2 released. But it can be avoided in the next versions.
