### ISSUE TITLE
Clarification regarding Event Registration and durability of QR-Codes

### ISSUE THREAD

**Issue by MaZderMind** [corona-warn-app/cwa-documentation#589]
## Where to find the issue
The Document [event_registration.md](https://github.com/corona-warn-app/cwa-documentation/blob/d55bbdc/event_registration.md) states at time of reading under *Profiling of Venues*, that 
> The proposed solution publishes warnings on CDN. A warning consists of the hashed ID of a venue and a time interval.

furthermore it states under *QR Code Structure*, that

> The ID of a venue is derived as the SHA-256 hash of the concatenated byte representation of the string CWA-GUID and the byte representation of the Protocol Buffer message QRCodePayload. The cryptographicSeed adds sufficient entropy so that any modifications to the QR code result in a unique ID.

It also states under *Profiling of Venues*, that

> To mitigate the risk, CWA encourages owners to regularly generate new QR codes for their venues. The more frequent QR codes are updated, the more difficult it is to keep a central database with venue data up-to-date.

## Describe the issue
Considering the Sentences above, Venues might consider to rotate their QR-Codes very frequently, for example our Sinage System will display a different QR-Code every couple minutes, because an updated Code is generated via https://github.com/MaZderMind/cwa-qr and it will contain a different cryptographicSeed. This is in line with the encouragement quoted above.

However, the quoted Sentences also suggest that this will result in a different Venue-ID for people checking in with different QR-Codes, which would, judging from the quotes cited above, result in different Check-Ins using QR-Codes with different cryptographicSeeds to not be counted as the same Event.

## Suggested change
If my assumption above would be correct, I would suggest to clarify the sentence under *Profiling of Venues* regarding how often a QR-Code should be changed at maximum and that this action will result of a different Event ID.

If my assumption is incorrect, I would guess that the Sentence regarding the contents of the Event-ID or another of the quoted Sentences needs clarification.

**Comment by MaZderMind** [comment]
Poking @thomasaugsten because he already hinted in this direction in https://github.com/corona-warn-app/cwa-wishlist/issues/399#issuecomment-824610365

**Comment by thomasaugsten** [comment]
I specified this in the documentation. The important fact is a new QR-Code should only regenerated when no visitor is in the location or event.

**Comment by MaZderMind** [comment]
Thank you very much, this indeed clarifies the Situation.
