### ISSUE TITLE
Please open source pretty early to gain trust

### ISSUE THREAD

**Issue by kheinz57** [corona-warn-app/cwa-documentation#59]
Open source way before publishing would help to build up trust which ist the most important thing for the app. At least that is what I think. Do others have different experiances? Does an uncomplete app destry trust? In which steps should the code published?

**Comment by tkowark** [comment]
Hi @kheinz57, we will publish more documentation and source code soon (as in: a couple of days) in this Org and of course, before the app is released.

**Comment by feinstaub** [comment]
Is it possible to have this ticket open as long as the code is not yet released?

**Comment by tkowark** [comment]
We already have #61 open for these purposes
