### ISSUE TITLE
Link structure for other contact tracing apps

### ISSUE THREAD

**Issue by ZengineChris** [corona-warn-app/cwa-documentation#590]
## Link structure for other contact tracing apps

I followed the documentation [here](https://github.com/corona-warn-app/cwa-documentation/blob/master/event_registration.md) and end up with this URL:

```` bash
https://checkin.uninow.com/N74-62-PG-R7-3#/CWA1/CAESKwgBEhBHZWJ1cnRzdGFnc2ZlaWVyGglNYWdkZWJ1cmco872EhAYwgNqEhAYadggBEmCDAszMTXne1DAA5_YxmhRdd_NZN2VKl9L32Jl9-ZybE4b2eNIrhFOKYU4XAOHq3RPLDxdHTW6ANiO24rCOO4rj06HzcVZy3pel58-L1KSPG-_PneL2BoyZQRz3qlu2hoAaEIl9MOnm2oxyxXUdBqkB_wkiBAgBEAs

````

The payload in this URL is from a QR Code generated by the CWA app. Before I tested this payload I have tried different others generated with the proto definition from the same documentation page. 

I generated different QR codes with this link and always get an `INVALID_URL`error from the app. 
Did I miss something? Or is there a way to get a more detailed error message?

**Comment by thomasaugsten** [comment]
Yes every host needs to whitelist via remote config for the app.
Please send a short explanation about your app and distribution in german to:
thomas.augsten@sap.com

**Comment by ZengineChris** [comment]
Thank you for your quick response @thomasaugsten

**Comment by ZengineChris** [comment]
Any updates on this?

**Comment by floscher** [comment]
@thomasaugsten Has the [Luca app](https://luca-app.de/) already requested whitelisting of their app?

Their latest version added support for reading QR codes like this:
![grafik](https://user-images.githubusercontent.com/3904348/116578243-8375b680-a911-11eb-8c0c-01fee0c690ae.png)
(encodes https://app.luca-app.de/webapp/81d9e1db-7050-4557-b1ca-a9e4fe899bd9#e30/CWA1/CAESLAgBEhNEb2xvcmVzIGN1bHBhIHV0IHNpGhNOb3N0cnVkIE5hbSBpZCBlbGlnGnYIARJggwLMzE153tQwAOf2MZoUXXfzWTdlSpfS99iZffmcmxOG9njSK4RTimFOFwDh6t0Tyw8XR01ugDYjtuKwjjuK49Oh83FWct6XpefPi9Skjxvvz53i9gaMmUEc96pbtoaAGhDL1rYQOi3Bh_YYps7XagWYIgcIARAIGIQF )

At the moment the CWA displays "Invalid URI - no matchedDescriptor"

As far as I know they so far do not generate these QR codes that are compatible with CWA, but are planning to do so as soon as the new versions of their apps are rolled out to more people. See also https://gitlab.com/lucaapp/android/-/issues/32

**Comment by thomasaugsten** [comment]
Yes they also requested a whitelisting but so far no app is whitelisted.

**Comment by vaubaehn** [comment]
@thomasaugsten @mlenkeit 
Maybe it would be helpful to add to https://github.com/corona-warn-app/cwa-documentation/blob/master/event_registration.md that for interoperability apps need to be whitelisted

**Comment by Ein-Tim** [comment]
FYI here: https://github.com/corona-warn-app/cwa-server/pull/1362/commits/a7b80cb2d1b68231e7250d54408f3ba486751ff9

**Comment by vaubaehn** [comment]
@floscher Luca seems to be whitelisted from CWA 2.1 on: https://github.com/corona-warn-app/cwa-server/pull/1362/commits/a7b80cb2d1b68231e7250d54408f3ba486751ff9
So, after that it's up to Luca when they finisch iOS and web frontend for interoperability

**Comment by floscher** [comment]
Great, thanks for the update.

**Comment by Ein-Tim** [comment]
@thomasaugsten 

The commit is actually part of the PR https://github.com/corona-warn-app/cwa-server/pull/1362 which isn't even merged yet, so nothing actually changed already. Sorry for the confusion (:

**Comment by Ein-Tim** [comment]
Any updates reg. Luca here? According to their [release notes on version 1.6.7. (Android)](https://gitlab.com/lucaapp/android/-/blob/dev/CHANGELOG.md#release-167) they added compatibility with CWA in this version. Seem like it's now up to the CWA to decide when this will work? 
The PR https://github.com/corona-warn-app/cwa-server/pull/1362 which includes https://github.com/corona-warn-app/cwa-server/commit/a7b80cb2d1b68231e7250d54408f3ba486751ff9 which would allowlist Luca is stuck in a draft PR...

**Comment by MikeMcC399** [comment]
There also has not been any response to the issue "List third-party apps approved for Event Registration" https://github.com/corona-warn-app/cwa-website/issues/1189 which also could provide clarity to users and app owners.

**Comment by Diapolo** [comment]
Yesterday I tried my first Luca QR-Code with CWA, which obiously didn't work... please make this working ASAP :). "Invalid URI - no matchedDescriptor" needs to go away :-D.

**Comment by dsarkar** [comment]
Hi all,

This is work in progress. My understanding is that the CWA itself is prepared from the technical point of view already, the corresponding functionalities have been implemented.  However, the decision when this goes life is up to further stakeholders. 

Best wishes, DS

---
Corona-Warn-App Open Source Team
related Internal Ticket ID: EXPOSUREBACK-1209

**Comment by floscher** [comment]
@Ein-Tim @Diapolo 

Two things need to happen for this to work:
* on the CWA side: the commit https://github.com/corona-warn-app/cwa-server/commit/a7b80cb2d1b68231e7250d54408f3ba486751ff9 mentioned [above](#issuecomment-830125296) needs to be merged: https://github.com/corona-warn-app/cwa-server/pull/1362
* on the luca side: the webapp for venue owners has to generate the new QR code format. The luca apps are compatible with the new QR code format, but the venue owners currently have no way to generate the new QR codes. They probably treat this as a low priority, because venue owners might not be that happy, that all QR codes need to be replaced. And the scanning errors happen in the CWA app, so the average user will blame the CWA for the incompatibility.

**Comment by jucktnich** [comment]
@floscher the venue owners should replace the codes every 24hours, so that shouldn't be a problem

**Comment by floscher** [comment]
@jucktnich AFAIK that recommendation is for CWA codes and not for the "old" luca app codes. So the luca venue owners are not used to changing their codes that often.

Also at the moment even re-generating daily wouldn't help, because the webapp produces the wrong (old) format and yields the same code every day.

**Comment by jucktnich** [comment]
@floscher it would be helpful in every case. But let's hope Luca is implementing this... aren't the paid with tax money 🧐

**Comment by floscher** [comment]
Luca has announced that the next version of their webapp for venue owners will allow the generation of QR codes that are compatible with CWA: https://gitlab.com/lucaapp/android/-/issues/32#note_584559489

**Comment by MikeMcC399** [comment]
See also the request "List third-party apps approved for Event Registration" https://github.com/corona-warn-app/cwa-website/issues/1189 asking for a list of apps to be published on the website https://www.coronawarn.app/.

**Comment by floscher** [comment]
FYI luca now offers the new QR code format for download:
![grafik](https://user-images.githubusercontent.com/3904348/119676560-3a485200-be3e-11eb-894a-5affd088ed0f.png)

There are ongoing discussions in order to prevent deanonymization of CWA users: https://github.com/corona-warn-app/cwa-server/pull/1362#issuecomment-848567767

**Comment by ArneBab** [comment]
> FYI luca now offers the new QR code format for download:
Is it the default?

**Comment by mumlax** [comment]
> Is it the default?

According to a luca-maintainer yes: https://gitlab.com/lucaapp/web/-/issues/17#note_585094457

**Comment by floscher** [comment]
> > Is it the default?
> 
> According to a luca-maintainer yes: https://gitlab.com/lucaapp/web/-/issues/17#note_585094457

Yes, can confirm. It even resets the switch to enabled every time the page is opened again or reloaded :thumbs_up:

**Comment by Ein-Tim** [comment]
Update regarding "luca":

https://github.com/corona-warn-app/cwa-server/pull/1362#issuecomment-882052293 says:

> The feature has a good progress. We hope we can finish the feature soon.

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-website/pull/2041

**Comment by dsarkar** [comment]
https://www.coronawarn.app/de/faq/#check_in_luca

**Comment by floscher** [comment]
FYI, luca is now whitelisted, so luca-codes generated on or after 26th of May 2021 can now be scanned by CWA (as well as the CCTG fork). corona-warn-app/cwa-server#1594 is now deployed in production.

**Comment by dsarkar** [comment]
@ZengineChris FYI
- Blog **EN** https://www.coronawarn.app/en/blog/2021-11-09-cwa-luca-qr-codes/
- Blog **DE** https://www.coronawarn.app/de/blog/2021-11-09-cwa-luca-qr-codes/
- FAQ **EN** https://www.coronawarn.app/en/faq/#check_in_luca
- FAQ **DE** https://www.coronawarn.app/de/faq/#check_in_luca

**Comment by jkrwdf** [comment]
FYI: While with my CWA Android 2.13.2 I can successfully check in using the example QR Code from https://github.com/corona-warn-app/cwa-documentation/issues/590#issuecomment-829349393 (which is also recognized from Luca), QR codes generated on my device for a "Private Meeting" do not work ("Kein geeigneter QR-Code"). Maybe this distinction should also be mentioned, or is this a bug?

**Comment by dsarkar** [comment]
@jkrwdf Thanks for your comment. This is not a bug, it is not possible. We will add this to the FAQ. Thanks again. Best wishes, DS 

---
Corona-Warn-App Open Source Team

**Comment by floscher** [comment]
> FYI: While with my CWA Android 2.13.2 I can successfully check in using the example QR Code from [#590 (comment)](https://github.com/corona-warn-app/cwa-documentation/issues/590#issuecomment-829349393) (which is also recognized from Luca), QR codes generated on my device inside the Luca App for a "Private Meeting" do not work in CWA ("Kein geeigneter QR-Code"). Maybe this distinction should also be mentioned, or is this a bug?

Good point. Any QR code that is generated in the luca app itself has a different format and is not compatible with the CWA!
Only those codes that businesses generate in the web interface at https://app.luca-app.de/login are compatible with the CWA.
Both QR codes that you can generate inside the luca-App ("Meinen QR-Code anzeigen" and "Privates Treffen erstellen") are incompatible with the CWA.

**Comment by Ein-Tim** [comment]
@floscher 

I suggest you open an issue in the website repo so that this does not get lost. You can then also provide a PR.

**Comment by Ein-Tim** [comment]
@ZengineChris

Has your initial question been answered? This issue was „misused“ for the whole luca topic, so before closing it, I think it‘s important to get an answer from you (-:

**Comment by floscher** [comment]
> @floscher
> 
> I suggest you open an issue in the website repo so that this does not get lost. You can then also provide a PR.

Thanks @Ein-Tim : corona-warn-app/cwa-website#2056 . If it isn't already fixed by then, I'll provide a PR later.

**Comment by floscher** [comment]
@dsarkar Do you know, what limitations there are for third-party apps to handle the CWA payload?

In particular, I assume they are not allowed to sync it via the internet (i.e. their servers) between different devices of their users. Are apps allowed to store the CWA payload, as long as it remains on the user's device? Or would storage on their server be permissible e.g. when done in an encrypted form with a private key of the user?

This question arose when luca released their new app, which they claim cannot offer the CWA compatible codes because of limitiations to what they can do with the CWA payload: https://twitter.com/patrick_hennig/status/1469078176408215559

**Comment by ZengineChris** [comment]
> @ZengineChris
> 
> Has your initial question been answered? This issue was „misused“ for the whole luca topic, so before closing it, I think it‘s important to get an answer from you (-:

Basically, yes.We contacted Thomas to get on the whitelist with our app. The link structure is therefore clear.
