### ISSUE TITLE
Strange wording in Check-Ins submission flow

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#593]
## Where to find the issue
iOS DE: https://github.com/corona-warn-app/cwa-app-ios/blob/208cab582a1b8da71f19f61c42e1a940412ebda7/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L2368

iOS EN: https://github.com/corona-warn-app/cwa-app-ios/blob/208cab582a1b8da71f19f61c42e1a940412ebda7/src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings#L2293

Android DE: https://github.com/corona-warn-app/cwa-app-android/blob/c740b0e9e80537dc54eea0b7b6e44b2583723013/Corona-Warn-App/src/main/res/values-de/strings.xml#L1992

Android EN: https://github.com/corona-warn-app/cwa-app-android/blob/c740b0e9e80537dc54eea0b7b6e44b2583723013/Corona-Warn-App/src/main/res/values-en/strings.xml#L1999

I think all other languages are also affected.

## Describe the issue
The wording "Checked in near you" is misleading since everybody will be warned who checked in with me, regardless if he was near me or not.

## Suggested change

Change
"Warn others who checked in near you. Your personal data will not be shared." 
to 
"Warn others who checked in with you. Your personal data will not be shared." 
& 
Change
"Skipping will not warn any contacts who checked-in near you."
to 
"Skipping will not warn any contacts who checked in with you."

And German: 
Change
"Teilen Sie Ihre Check-ins, um andere zu warnen, die in Ihrer Nähe waren. Ihre Identität bleibt geheim." 
to
"Teilen Sie Ihre Check-ins, um andere zu warnen, die mit Ihnen eingecheckt waren. Ihre Identität bleibt geheim."
&
Change
"Dadurch werden andere nicht gewarnt, die in Ihrer Nähe waren."
to
"Dadurch werden andere nicht gewarnt, die mit Ihnen eingecheckt waren."

## Additional information
I can provide a PR for this under iOS.

---
Internal Tracking ID: [EXPOSUREAPP-7155](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7155)

**Comment by dsarkar** [comment]
@Ein-Tim  Thanks. Internal Tracking ID: [EXPOSUREAPP-7155](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7155)

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-ios/pull/2676

**Comment by Ein-Tim** [comment]
Although I cannot confirm this fix, this should be fixed in version 2.3.

Closing as fixed.
