### ISSUE TITLE
Documentation about rapid testing?

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#595]
## Background

According to https://www.coronawarn.app/en/blog/2021-03-31-corona-warn-app-test-integration/

"The federal government's Corona-Warn-App is getting another important feature. In the future, the app will integrate rapid COVID-19 tests. Users can save the confirmation of their test in the app and add them to the contact diary. In addition, anyone who tests positive for COVID-19 through a rapid test will also be able to warn contacts via the Corona-Warn-App in the future."

~~and~~

~~"The rapid test-function is supposed to be available in the second half of April. SAP and Deutsche Telekom will provide further information on the details here soon."~~

## Your Question

Can we expect the document [Solution Architecture](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md) in this repository to be updated with information about the integration of rapid COVID-19 tests? Will there also be a separate document similar to the one posted for the new functionality of [Event Registration](https://github.com/corona-warn-app/cwa-documentation/blob/master/event_registration.md)?

~~If the planning data "to be available in the second half of April" is still true, then it means that the functionality will be released by the end of this week (April 30, 2021).~~

See https://www.coronawarn.app/en/blog/2021-05-02-corona-warn-app-version-2-1/ announcing "Project team integrates rapid COVID-19 tests into Corona-Warn-App version 2.1" being released today, May 2, 2021.

**Comment by dsarkar** [comment]
@MikeMcC399 See also https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki

**Comment by MikeMcC399** [comment]
@dsarkar 
Thanks for the pointer to German-language documentation for providers of rapid testing.

I was hoping for English-language documentation which also covers how data is transferred, stored and deleted, especially concerning Personally identifiable information (PII).

**Comment by MikeMcC399** [comment]
This is related to https://github.com/corona-warn-app/cwa-documentation/issues/587 however I would like to keep this one open even if there is overlap with #587, because this question is quite specific.

**Comment by MikeMcC399** [comment]
@dsarkar 

Apart from this issue, there is no obvious link to the rapid test documentation in this repository. Also the repository https://github.com/corona-warn-app/cwa-quicktest-onboarding is not in the list of repositories in the [cwa-documentation README.md file](https://github.com/corona-warn-app/cwa-documentation/blob/master/README.md). That should be fixed if this repository has the role of a central place for documentation and if users can expect to be able to find rapid test documentation by referencing the contents of this repository.

If there is no English language documentation being produced for rapid testing, I would suggest:
- creating a dummy document in https://github.com/corona-warn-app/cwa-documentation, such as `rapid-testing.md`, which contains links to any other existing documentation on the subject, like https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki.
- adding the repository https://github.com/corona-warn-app/cwa-quicktest-onboarding to the list of repositories in https://github.com/corona-warn-app/cwa-documentation/blob/master/README.md.

**Comment by MikeMcC399** [comment]
I will not follow this question further, since:

- https://github.com/corona-warn-app/cwa-documentation/blob/master/README.md now links to https://github.com/corona-warn-app/cwa-quicktest-onboarding and 
- https://www.coronawarn.app/en/ links to https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki.

There seems to be no English-language documentation for rapid testing published. It also seems that the [Solution Architecture](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md) is not being updated as new functionality is added to CWA.
