### ISSUE TITLE
Typo in antigen_strings

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#597]
## Where to find the issue

In the release/2.1.x branch under development:

https://github.com/corona-warn-app/cwa-app-android/blob/release/2.1.x/Corona-Warn-App/src/main/res/values/antigen_strings.xml

https://github.com/corona-warn-app/cwa-app-android/blob/9f61dd1386cb763b71a487f769da49507e132512/Corona-Warn-App/src/main/res/values/antigen_strings.xml#L129-L130
`coronatest_negative_antigen_result_first_info_body`

<string name="coronatest_negative_antigen_result_first_info_body">"The test result is displayed her for 48 hours. The app also creates an entry in your contact journal."</string>

## Describe the issue

There is a typo in the sentence "The test result is displayed **her** for 48 hours."

## Suggested change

In https://github.com/corona-warn-app/cwa-app-android/blob/9f61dd1386cb763b71a487f769da49507e132512/Corona-Warn-App/src/main/res/values/antigen_strings.xml#L129-L130

string name `coronatest_negative_antigen_result_first_info_body`

"her" should be "here"
"The test result is displayed here for 48 hours."

**Comment by Ein-Tim** [comment]
Link to iOS-Code: https://github.com/corona-warn-app/cwa-app-ios/blob/0cba5003eb2a4482515fd8f41e881448790a0430/src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings#L685

**Comment by MikeMcC399** [comment]
The issue is still present in [v2.1.2-RC0](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.1.2-RC0) which was tagged today:

https://github.com/corona-warn-app/cwa-app-android/blob/8687a6e4bb510cc5b6e82e16af85b32d7c88e87d/Corona-Warn-App/src/main/res/values/antigen_strings.xml#L130.

`coronatest_negative_antigen_result_first_info_body` says:

`"The test result is displayed her for 48 hours."`

In the above `"her"` should be `"here"`.

That would then be a correct translation of the equivalent German string:
`"Das Test-Ergebnis wird 48 Stunden hier angezeigt."`

**Comment by Ein-Tim** [comment]
Fix for iOS: https://github.com/corona-warn-app/cwa-app-ios/pull/2596/files#diff-8fc5b852f1f89c8368223b1ab28939b0b01f90542347b91e9bdb1e678b289dcaL685

**Comment by MikeMcC399** [comment]
https://github.com/corona-warn-app/cwa-app-android/pull/3034 fixes this issue in Android https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.1.2-RC2

**Comment by Ein-Tim** [comment]
There's also a PR which fixes this for version 2.1 on iOS: https://github.com/corona-warn-app/cwa-app-ios/pull/2598

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Thanks for the information! Although https://github.com/corona-warn-app/cwa-app-ios/pull/2598 is not yet merged, I think we can close this issue, since the software version it concerns has not yet been released.
