### ISSUE TITLE
Dialog to enter preferred smartphone carrying position of user

### ISSUE THREAD

**Issue by SchwertAs** [corona-warn-app/cwa-documentation#60]
## Where to find the issue
New requirement

## Describe the issue
The distance between two smartphones is not everytime the same as the distance between noses or mouths of two persons. To calculate the real distance as exactly as possible the application needs a hint, where the user normally wears his smartphone. 

## Suggested change
Therefore a dialog needs to be created to enter this information and also a corresponding User-story

**Comment by tkowark** [comment]
Thanks @SchwertAs for the suggestion. 

If we'd collect this parameter, the [Exposure Notification API](https://www.google.com/covid19/exposurenotifications/) from Apple/Google needs to be extended to take it into consideration for contact detection and [risk scoring](https://developer.apple.com/documentation/exposurenotification/enexposureconfiguration), first. Hence, this cannot be implemented from our developers for the Corona-Warn-App.
