### ISSUE TITLE
Device (running on Android 8.0.0) requires restart every 24 hours for correct Bluetooth service since app was installed

### ISSUE THREAD

**Issue by lastRoach** [corona-warn-app/cwa-documentation#600]
As title states, since I installed the app my phone (CAT S41) running on Android 8.0.0 has Bluetooth connectivity issues. None of my devices (car, headphones,...) recognize my phone after more than 24 hours after the latest restart of the phone.

This is not only annoying as I'm not used to constantly restart my phone (that's but a habit and it's slowly changing), but it also raises a concern that my phone's Bluetooth might not be working correctly after 24 hours resulting in flawed interactions with other devices using the app.

Could not find anything by googling or here in the issues, so I figured it might be worth opening an issue.
If that's just my phone: tough luck.
But if it's a greater issue it might be worth looking into.

**Comment by lastRoach** [comment]
Wrong category, re-opening in cwa for Android os

**Comment by MikeMcC399** [comment]
reposted to https://github.com/corona-warn-app/cwa-app-android/issues/3043
