### ISSUE TITLE
Missing details in English privacy policy translation

### ISSUE THREAD

**Issue by fynngodau** [corona-warn-app/cwa-documentation#601]
For version 2.1, the German privacy policy contains these sentences under point 11 ("Werden Ihre Daten in Länder außerhalb der EU übermittelt?" / "Is your data transferred to countries outside the EU?"):

> Für die Schweiz hat die EU einen Angemessenheitsbeschluss erlassen, in dem die Angemessenheit
>    des Datenschutzniveaus festgestellt wird (Art. 45 DSGVO). Daneben können die aktuellen
>    Positiv-Listen unabhängig vom Aufenthaltsort des Nutzers (etwa im Urlaub oder auf
>    Geschäftsreise) abgerufen werden. 

It is missing in the most recent English version of the privacy policy. Older versions contained this translation, which is now gone:

> The EU has issued an adequacy decision for Switzerland, which
>    determines the adequacy of the level of data protection in the country (Art. 45 GDPR). In
>    addition, please note that users can retrieve the latest positive lists regardless of where they
>    are (even if they are abroad on holiday or on a business trip, for example).

* Android DE: https://github.com/corona-warn-app/cwa-app-android/blob/bebc8beceea3d5f25533f646015a993495676bf2/Corona-Warn-App/src/main/assets/privacy_de.html#L1039-L1042
* Android EN: https://github.com/corona-warn-app/cwa-app-android/blob/bebc8beceea3d5f25533f646015a993495676bf2/Corona-Warn-App/src/main/assets/privacy_en.html#L1011-L1014
* iOS DE: https://github.com/corona-warn-app/cwa-app-ios/blob/c0eb3a373b9bb7439581ba69808d3d2ce4ad3eb6/src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html#L926
* iOS EN: https://github.com/corona-warn-app/cwa-app-ios/blob/c0eb3a373b9bb7439581ba69808d3d2ce4ad3eb6/src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html#L907

----
Internal Tracking-ID: [EXPOSUREAPP-7274](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7274)

**Comment by Ein-Tim** [comment]
FYI PR: https://github.com/corona-warn-app/cwa-app-ios/pull/2733 under iOS targeting the `release/2.3.x` branch.

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/3221 Android

**Comment by MikeMcC399** [comment]
@fynngodau 
https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf for CWA 2.3 contains the paragraph

"The EU has issued an adequacy decision for Switzerland, which determines the adequacy of
the level of data protection in the country (Art. 45 GDPR). In addition, please note that users
can retrieve the latest positive lists regardless of where they are (even if they are abroad on
holiday or on a business trip, for example)."

This text is also part of the paragraph in the release/2.3.x branch , see https://github.com/corona-warn-app/cwa-app-android/blob/e7513fe5f56b258e3ebf9f701b64292da065cfd6/Corona-Warn-App/src/main/assets/privacy_en.html#L1228-L1240 and it displays on the CWA Android 2.3.3 released  version.

The PDF version starts a new page and a new paragraph with the sentence, 
"In addition, the confirmation of the authenticity of your app may involve the transfer of data to
a country outside the EU. " which differs from how the text is presented in the Android app where it all appears as one paragraph. I don't know why there would be this difference, but I don't think it needs a separate issue opening about it.

I haven't checked iOS (not my area of interest), but at least Android looks OK. 👍🏻

**Comment by heinezen** [comment]
Fixed in CWA release 2.3

----
Corona-Warn-App Open Source Team
