### ISSUE TITLE
Describe process to allowlist third-party Event Registration apps

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#602]
## Where to find the issue

**Event Registration**
https://github.com/corona-warn-app/cwa-documentation/blob/master/event_registration.md

**QR Code Compatibility with Other Contract Tracing Apps in Germany**
https://github.com/corona-warn-app/cwa-documentation/blob/master/event_registration.md#qr-code-compatibility-with-other-contract-tracing-apps-in-germany

## Describe the issue

The section [QR Code Compatibility with Other Contract Tracing Apps in Germany](https://github.com/corona-warn-app/cwa-documentation/blob/master/event_registration.md#qr-code-compatibility-with-other-contract-tracing-apps-in-germany) in the document [Event Registration - event_registration.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/event_registration.md) says:

"Note: QR codes that are generated by other contact tracing apps must be allowlisted individually per app (based on the hostname in the QR code) before they can be scanned and are accepted by CWA."

It does not describe how a third party, who wishes their app to be whitelisted, could request this.

This follows on from https://github.com/corona-warn-app/cwa-documentation/pull/599#issuecomment-830653760.

## Suggested change

Describe in the document [event_registration.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/event_registration.md)  how a third party can contact the Open Source Team to allowlist their app (and QR code) and include any other additional relevant information for a prospective third party.

**Comment by MikeMcC399** [comment]
@mlenkeit 
As we discussed back in May 2021, I opened a separate issue for this point. 

The document hasn't been updated since then and there is no indication about what an interested third party should do to start the process.

Perhaps add the e-mail address corona-warn-app.opensource@sap.com from https://www.coronawarn.app/en/community/ to the document?

**Comment by thomasaugsten** [comment]
I think the email CoronaWarnApp@rki.de fits better for this subject
