### ISSUE TITLE
Multiple Check-Ins for the same Event (QR-Code) are possible

### ISSUE THREAD

**Issue by jkrwdf** [corona-warn-app/cwa-documentation#604]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only (cannot identify, have only Android)
* [X] Bug is not already reported in another issue

## Describe the bug
I can check-in multiple times to the same event, represented by its QR code. 
This is obviously not sensible and could be avoided.
See attached screenshot. 

![image](https://user-images.githubusercontent.com/5329491/115878965-70fb0900-a449-11eb-98c2-3f8a8cec756b.png)

## Steps to reproduce the issue
Create QR code on one device. 
Check in multiple times using another device.

## Expected behaviour
I think, re-scanning the same QR code while a check-in for the same QR code is still active should update the existing check-in and prolong its check-in time by the "default check-in time" of the event. 

Example: Default check-in time is 2 hours. 
I checked in 1 hour ago. I now check in again. 
Result: I still have only one active checkin, and it will automatically check out two hours from now.

Less good would be an error message "You are already checked in here".

**Comment by dsarkar** [comment]
@jkrwdf @vaubaehn @Ein-Tim 
I suggest, if you liked to, to you create wishlist items on this topic. Thanks.

**Comment by Ein-Tim** [comment]
@dsarkar The https://github.com/corona-warn-app/cwa-documentation/labels/in%20review is applied here for 11 months, what was the conclusion of the review? Will this be fixed / the behavior changed? If not, I suggest to close this issue here and point @jkrwdf to open an enhancement request in the https://github.com/corona-warn-app/cwa-wishlist repository.

**Comment by jkrwdf** [comment]
Closing as suggested.
