### ISSUE TITLE
Deactivate emojis, etc. for Rapid Test Profile

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#605]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 12 Emulator
- iOS version: 14.5
- App version: 2.2.0 (9)

## Describe the bug

You can enter emojis into the following fields:

- "First Name"
- "Last Name"
- "Street and House Number"
- "City"
- "E-Mail Adress"

## Steps to reproduce the issue

1. Open the Corona-Warn-App
2. Click on "Next Steps" 
3. Click on "Create Rapid Test Profile"
4. Enter Emojis or other special letters (§, %, etc.) into the fields mentioned above

## Expected behaviour

You can only enter "normal" characters into the fields. 

## Possible Fix

Validate the input.

## Additional context

I think that this is a priority issue since the Luca app got recently "shitstormed" for the option to enter any characters into the address field during their register process, so to prevent bad PR for this new feature I suggest to fix this ASAP.

---
Internal Tracking ID: [EXPOSUREAPP-7147](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7147) iOS
Internal Tracking ID: [EXPOSUREAPP-8108](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8108) Android

**Comment by dsarkar** [comment]
@fynngodau @Ein-Tim Thanks. Internal Tracking ID: [EXPOSUREAPP-7147](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7147)


---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
In fact, I can see, that there is no input validation at all (like birthday can only be numbers, e-mail address has to include a @, etc.)

**Comment by ndegendogo** [comment]
I agree that emojis are not expected to be used in names field. However, the set of valid characters should **not** be limited to pure ASCII letters. In Germany, we have Umlauts. Many people have accents in their names. And people from other cultures can have most of the Unicode letters. If you don't want to exclude / discriminate these people, it will be not easy to specify the "allowed" or "forbidden" letters.

**Comment by Ein-Tim** [comment]
@ndegendogo 

I agree with you there, but let's also agree to:
- Deactivate emojis
- Force the date of birth to be all numbers
- Force the date of birth to be in the past 

Or do you think there could be any problems with this?

**Comment by jucktnich** [comment]
@Ein-Tim you can also just paste letters into birth date

**Comment by DerVogel2020** [comment]
In the android app, I cannot paste letters, since the format dd.mm.yy is not satisfied.
But a date in the future is possible to select.

**Comment by jucktnich** [comment]
Oh sorry, there's an input validation there for birthday, you can paste it, but it stays nil if you save the profile

**Comment by ndegendogo** [comment]
@Ein-Tim [sure](https://github.com/corona-warn-app/cwa-documentation/issues/605#issuecomment-841317383) 😅

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-7147](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7147) iOS
Internal Tracking ID: [EXPOSUREAPP-8108](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8108) Android

**Comment by dsarkar** [comment]
FYI PR iOS https://github.com/corona-warn-app/cwa-app-ios/pull/3018

**Comment by dsarkar** [comment]
FZI PR Android https://github.com/corona-warn-app/cwa-app-android/pull/3597

**Comment by Ein-Tim** [comment]
I can confirm that this has been fixed with version 2.5 on iOS 14.6. 
The only flaw I see is that you can paste non-number characters into the "Telefonnummer" field, but I think this is negligible here.

Can someone under Android confirm the fix?

**Comment by ndegendogo** [comment]
@Ein-Tim well ...  non-number characters can be valid in a phone number ... think of the '+' at the beginning of an international number ... and the number block on my phone has also buttons for '#' and '*'

**Comment by Ein-Tim** [comment]
@ndegendogo 

You're absolutely right, but I can paste letters in there... I don't know phone numbers with letter 😉
I should have been clearer with which non-number characters I mean, sorry.

**Comment by dsarkar** [comment]
@ndegendogo @Ein-Tim I confirm, that on Android/Galaxy A21s emojis cannot be introduced in the RAT profile. 

Regarding the phone numbers: I can only use some specific characters apart from numbers, but I do not get the keyboard for the letters. This might be a specific function of this phone.

Anyway, I suggest closing this issue regarding emojis as fixed.

**Comment by Ein-Tim** [comment]
Yes, I also consider this as fixed. The other issue with the letters in the phone number is negligible here. 

Thank you @dsarkar for confirming the fix under Android. 

Closing as fixed.

**Comment by dsarkar** [comment]
Thanks everybody.

**Comment by Ein-Tim** [comment]
FYI: https://github.com/corona-warn-app/cwa-app-android/pull/3764 from a community contributor will improve the inout validation under Android even more.

**Comment by marcauberer** [comment]
> FYI: [corona-warn-app/cwa-app-android#3764](https://github.com/corona-warn-app/cwa-app-android/pull/3764) from a community contributor will improve the input validation under Android even more.

New pr: https://github.com/corona-warn-app/cwa-app-android/pull/3771
