### ISSUE TITLE
Regressions in privacy policies

### ISSUE THREAD

**Issue by fynngodau** [corona-warn-app/cwa-documentation#610]
There's a regression in the latest update of the German privacy policy: "nach 14 Tagen" turned into "nach 14 Tage".

* Android DE: https://github.com/corona-warn-app/cwa-app-android/blob/9ec222a431340917834e831cc60edd14fa062d27/Corona-Warn-App/src/main/assets/privacy_de.html#L188
* iOS DE: https://github.com/corona-warn-app/cwa-app-ios/blob/864d7600553b70beb6de94d624d22abda16ed44b/src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html#L321

**This has been fixed for 2.3**, e.g. here: https://github.com/corona-warn-app/cwa-app-android/blob/57b2d7a195b97e3bf77d59104fabae8a85b77984/Corona-Warn-App/src/main/assets/privacy_de.html#L189

---

In the English policy, the wrong parenthesis are now used:

> a. Consent to “exposure logging”

turned into

> a. Consent to "exposure logging"

* Android EN: https://github.com/corona-warn-app/cwa-app-android/blob/b4bf87fc7f0229ae950532632cd33edfcd93255b/Corona-Warn-App/src/main/assets/privacy_en.html#L1120
* iOS EN: https://github.com/corona-warn-app/cwa-app-ios/blob/864d7600553b70beb6de94d624d22abda16ed44b/src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html#L936

**This has been fixed for 2.3** in https://github.com/corona-warn-app/cwa-app-android/pull/3221#discussion_r635236283 and https://github.com/corona-warn-app/cwa-app-ios/pull/2733.

---

Here's another, Android-specific regression that is worth its own ticket: https://github.com/corona-warn-app/cwa-app-android/issues/3166

---

Side note: there's a small inconsistency in the reference "5.g. und 6.g.". According to other occurrences, it should be "5 g. und 6 g.". **This has been fixed for version 2.3.**

* Android DE: https://github.com/corona-warn-app/cwa-app-android/blob/9ec222a431340917834e831cc60edd14fa062d27/Corona-Warn-App/src/main/assets/privacy_de.html#L271
* iOS DE: https://github.com/corona-warn-app/cwa-app-ios/blob/864d7600553b70beb6de94d624d22abda16ed44b/src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html#L376

The English version also sometimes, but rarely uses a non-breaking space in between digit and letter:

>     (see Section 6&nbsp;e.)

---

If you would like my feedback on your privacy policy updates *before* you merge them in, feel free to ping me. Actually that would be much less work for me than to open new issues each time I find something. I need to manually review every change anyhow for CCTG

Previous: #601, https://github.com/corona-warn-app/cwa-app-android/issues/2841

----
Internal Tracking-ID: [EXPOSUREAPP-7274](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7274)

**Comment by heinezen** [comment]
@fynngodau 

Thanks. I've reported the issues to the developers.

> If you would like my feedback on your privacy policy updates before you merge them in, feel free to ping me. Actually that would be much less work for me than to open new issues each time I find something. I need to manually review every change anyhow for CCTG

Regarding this, it might be worth to have a general discussion about involvement of the community and where and how we can improve outside contributions. Stay tuned.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
FYI the second case mentioned will be fixed by https://github.com/corona-warn-app/cwa-app-ios/pull/2733 under iOS in version 2.3

**Comment by dsarkar** [comment]
FYI, second item, Android : PR https://github.com/corona-warn-app/cwa-app-android/pull/3221

**Comment by fynngodau** [comment]
I determined that all almost issues I highlighted are indeed going to be fixed with the 2.3 update, at least for Android.
