### ISSUE TITLE
Incorrect Notifications status in Settings when risk notification off

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#611]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug applies to Android and iOS
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Pixel 3a emulator
- Android version: 11
- First reported on App version: 2.2.1
- Reviewed and confirmed not fixed on App version: 2.11.2

## Describe the bug

If the notifications setting "Your risk of infection changed" is set to Off, the Settings overview shows Notifications set to "On".

## Steps to reproduce the issue

1. In CWA Start Screen, tap three-dot symbol
2. Tap "Settings"
3. Tap "Notifications"
4. Set "Your risk of infection changed" to Off, and ensure that "Status of your coronavirus test" is set to On
5. Tap back arrow, top-left
6. Notice that Notification shows on and there is no indication that the notification for risk of infection has been disabled.

---
![image](https://user-images.githubusercontent.com/66998419/118252066-a8892e00-b4a8-11eb-9a0b-78b025c88128.png)

---
![image](https://user-images.githubusercontent.com/66998419/118251951-80013400-b4a8-11eb-9627-91ef5f706ef0.png)

## Expected behavior

If "Notifications - Your risk of infection" is set to Off, then the Settings overview should not show On.

## Possible Fix

Since there are two different notification settings:

1. Your risk of infection changed
2. Status of your coronavirus test

The "On" status should only be shown if both settings are "On". If one of them is "Off", then the overall status could be shown as "Partially On". (If both sub-settings are "Off" then the overview status is correctly shown as "Off".)

Also, the overview text only lists "Allow automatic notifications of your COVID-19 risk status". It does not specifically mention notification of the "Status of your coronavirus test" and the text is not generic enough to cover both cases. This also should be reviewed.

---
Internal Tracking ID: [EXPOSUREAPP-7285](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7285)

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-7285](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7285)

**Comment by MikeMcC399** [comment]
Version 2.12.0-RC0 handles setting notifications through Android notifications settings, therefore the steps to reproduce in this issue no longer fit.

It may be possible to close this issue when 2.12.x is released.

**Comment by MikeMcC399** [comment]
This issue was already solved by a change of the UI in the release 2.12.

See also FAQ https://www.coronawarn.app/en/faq/#notification_settings.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for the feedback.

**Comment by dsarkar** [comment]
Forwarded to internal ticket and closed.
