### ISSUE TITLE
Cannot view exact error report before submitting

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#614]
## Avoid duplicates

* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Affects Android and iOS
* [ ] Bug is not already reported in another issue
This is a follow-on from https://github.com/corona-warn-app/cwa-documentation/issues/612 and Internal Tracking ID: [EXPOSUREAPP-7292](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7292).
It is related also to "Stop Error Analysis after sending it" https://github.com/corona-warn-app/cwa-wishlist/issues/523.

## Technical details

- Device name: Google Pixel 3a emulator
- Android version: 11
- First reported on App version: 2.2.1
- Reviewed as not yet fixed on App version: 2.15.1

## Describe the bug

It is not possible to view the exact contents of an error report before it is sent. It is only possible to preview a snapshot from some time before the error report is submitted. During and after previewing a log, the error analysis continues to capture log data, so that when the error report is sent it will likely contain later data than the snapshot that the user was able to view.

## Steps to reproduce the issue

1. In CWA Start Screen, tap three-dot icon
2. Tap "App Information", tap "Error Reports"
3. Tap "START"
4. Wait until "Recording Active" is shown
5. Tap "SHARE AND CONTINUE"
6. Select "Drive", tap "Save"
7. Monitor display of Recording Active and note that Current size increases over time
8. Tap "SEND ERROR REPORT"
9. Tap "AGREE AND SEND"
Note that even after sending the error report "Recording Active" is still shown.

![image](https://user-images.githubusercontent.com/66998419/118269920-95358d00-b4bf-11eb-90ec-b7ca96cd8265.png)

## Expected behavior

In App Information > Error Reports, the text (from string `debug_log_privacy_card_container_section_two`) says:

"Initially, only you will have access to the error report. You can then decide whether to send the error report to the technical support team, whether to save the error report on your smartphone first, or whether to stop and erase the recorded information. **If you first save the error report locally, this will give you the opportunity to view the error report yourself before submitting it to support.**"

![image](https://user-images.githubusercontent.com/66998419/118269316-e1340200-b4be-11eb-9d6e-206d04e89e65.png).

The text suggests that a user should be able to freeze the contents of an error report, view it, then send it.

The expected behavior is that this should in fact be possible.

## Possible Fix

- Introduce a means to stop logging without deleting the log.

---
Internal Tracking ID: [EXPOSUREAPP-7373](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7373)

**Comment by dsarkar** [comment]
@MikeMcC399  Thanks. Internal Tracking ID: [EXPOSUREAPP-7373](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7373)

**Comment by ndegendogo** [comment]
What is the planned proceeding with this issue? 
Actually, it is common practice for an error report that I get the opportunity to review the report before I decide to send it. 
I don't like to be forced to trust blindly ...

**Comment by heinezen** [comment]
@ndegendogo There are no concrete plans for when this will be fixed yet. Internally, it has been reassigned as a feature request. There are proposals to redesign the UI for error reports to mitigate this issue.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Probably the priority of this 11 month report is still low, or?
