### ISSUE TITLE
How many vaccination certificates can be registered in the Corona-Warn-App

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#618]
## Your Question
The article https://www.aerzteblatt.de/nachrichten/123791/Digitaler-Impfnachweis-So-bekommen-bereits-vollstaendig-Geimpfte-den-CovPass shared by @vaubaehn in our Community Slack says that it'll be possible to register more than one vaccination certificate in the CovPass app. Now I wondered if CWA will also support more than one vaccination certificate in the app?

## Related issue:

- #615

**Comment by vaubaehn** [comment]
The subtitle of @Ein-Tim 's question could also be:
Please provide a technical documentation of the Vaccination Pass feature in the documentation repo (although I know, that during the current implantation process there may still be many changes...) ;-)

**Comment by thomasaugsten** [comment]
CWA allows to register your own vaccination certificates. The number of certificates is not limited. Because we are not able to persist a consent of other people to save their vaccination certificate we limit the number of person to one.

**Comment by Ein-Tim** [comment]
@thomasaugsten Thank you for answering. 

Closing as answered.

**Comment by vaubaehn** [comment]
@thomasaugsten 
Dear Thomas, thanks for your response. I guess the CWA team is also not too happy about this.
Do you have any insight, how the CoVApp will handle this? Should be the same problem?
And isn't this a general problem of the Digital Green Certificate for all apps in EU?

**Comment by thomasaugsten** [comment]
The app is different because the purpose/Zweck of the app is different and also there is no age limitation.

**Comment by vaubaehn** [comment]
Ok, I think I understand.

**Comment by vaubaehn** [comment]
@thomasaugsten 
One last remark about this: The reason for not allowing more than one person's VPass inside CWA should be promoted carefully before the release of 2.3. I think there are many people out there who will expect to store more VPasses, and who will be disappointed and probably complain like "they never learn anything better... we already saw this issue with the PCR tests, RATs, and now they're continuing with VPasses..." and throw all their dirt...
You don't deserve this!

**Comment by DerVogel2020** [comment]
This limitation should be noticed to the Gesundheitsministerium. At https://www.bundesgesundheitsministerium.de/coronavirus/faq-covid-19-impfung/faq-digitaler-impfnachweis.html it says:

Wie werden die digitalen Impfnachweise von Kindern gespeichert?

Digitale Impfnachweise von Kindern oder Partnern können zusammen auf einem Smartphone gespeichert werden.

**Comment by thomasaugsten** [comment]
This is correct for the official Impfnachweis App covPass. Only CWA has the age limitation
