### ISSUE TITLE
Please clarify use of "Device attestation API"

### ISSUE THREAD

**Issue by mh-** [corona-warn-app/cwa-documentation#62]
## What is missing
The recently published open source reference implementation of an [Exposure Notifications 
server](https://github.com/google/exposure-notifications-server) includes the use of a "device attestation API", such as the [SafetyNet Attestation API](https://developer.android.com/training/safetynet/attestation). 
The purpose would obviously be to validate TEKs, i.e. prevent hacked devices from reporting fake TEKs as Diagnosis Keys. 
The [SafetyNet ToS](https://developer.android.com/training/safetynet/attestation#safetynet-tos) state that this "works by collecting hardware and software information, such as device and application data (...), and sending that data to Google for analysis". I think that's fine in general, but the corona-warn-app should either _not_ invoke this API, or at least _not only_ when a user has been infected, but independently of this - so that the device data cannot be linked to this sensitive information.
What is missing is a clear statement about not using such API, or if it's used, how and when.

## Why should it be included
Including this information increases the trust that privacy is really preserved.

**Comment by tkowark** [comment]
Thanks for pointing to that issue. As with #68, please check again once we‘ve published the Android source code whether such calls are included and reopen if necessary.

**Comment by mh-** [comment]
At the moment it seems that Device Attestation [will not be used within cwa](https://github.com/corona-warn-app/cwa-server/issues/82), which I think is good.
If you do decide otherwise in the future, please consider this comment: https://github.com/google/exposure-notifications-server/pull/404#issuecomment-632093897

**Comment by mh-** [comment]
The recently published [Security Overview](https://github.com/corona-warn-app/cwa-documentation/blob/master/overview-security.md) mentions 

   "Identify clients with features such as SafetyNet attestation or similar" 

multiple times. 
While SafetyNet is not currently included in the current Android source code, I would still like to ask you to please clarify whether you intend to use it for the production app (and if not, correct the Security Overview document).
