### ISSUE TITLE
NOTICE file - Contributors seem to be outdated

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#622]
## Where to find the issue
https://github.com/corona-warn-app/cwa-documentation/blob/master/NOTICE

## Describe the issue
The contributors in the NOTICE file do not reflect all contributors anymore. There are some more contributors who added or changed files (see https://github.com/corona-warn-app/cwa-documentation/graphs/contributors).

## Suggested change
The new contributors should be included. Please note that there are some contributors who only fix files, it has to be decided wether these should also be included. 
Also, we could remove the list of contributors from their and just link to https://github.com/corona-warn-app/cwa-documentation/graphs/contributors.

**Comment by heinezen** [comment]
`NOTICE` is standardized by the Apache License. The file is not mandatory, but other projects that built on top of this repo must include it. Removing the list is not practical in my opinion because it may already be icluded somewhere else.

The best long-term solution would be to add a CI check that tests if a PR author/comitter is in the list of contributors.

> Please note that there are some contributors who only fix files, it has to be decided wether these should also be included.

I would consider fixes as contributions, not matter how small. 


----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@heinezen The CI check would be a good idea! Do you have any idea what we could use for this?

**Comment by heinezen** [comment]
@Ein-Tim I've thought about it and the best way is probably a custom script that reads in all usernames in `NOTICE` and checks if the authors of PR commits are already in there (and then it complains when they are not). We might need to change the format in `NOTICE` slightly for better parseability. I'll see what I can do about it.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@dsarkar Could I get an update on this issue, please? Maybe @heinezen already prepared a script/a white paper before leaving the Open-Source-Team? I'm sadly not skilled enough to built such a workflow.

**Comment by Ein-Tim** [comment]
- I provided PR https://github.com/corona-warn-app/cwa-documentation/pull/943 which fixes this issue
