### ISSUE TITLE
Syntax error in Nutzungsbedingungen html

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#623]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug probably affects Android and iOS. Only Android tested so far.
* [X] Bug is not already reported in another issue

## Technical details

- App version: release/2.3.x
- Android Studio version: 4.2.1 (also with 4.1.3)

## Describe the bug

terms_de.html "Nutzungsbedingungen" shows syntax error
Element a is not closed :79
https://github.com/corona-warn-app/cwa-app-android/blob/e65ccf44fb169cd47b3bf1fe553ef13ed1b48e54/Corona-Warn-App/src/main/assets/terms_de.html#L70

`<a name="_Hlk41947003">`

in the following:

```
<p>
    Bitte lesen Sie diese Nutzungsbedingungen sorgfältig. Diese
    Nutzungsbedingungen regeln Ihre Nutzung der Corona-Warn-App einschließlich
    der Nutzung zukünftiger Versionen (Patches, Updates und Upgrades) („<strong>App</strong>“) und
    der Nutzung weiterer Dienste („<a name="_Hlk41947003"><strong>CWA-Dienste</strong>“), die
    derzeit oder
    zukünftig vom RKI im Zusammenhang mit der App bereitgestellt werden. Sie
    können diese Nutzungsbedingungen jederzeit in der App unter
    „App-Informationen“ und unter https://www.coronawarn.app/assets/documents/cwa-eula-de.pdf
    abrufen. Die separate Datenschutzerklärung (siehe unter „App-Informationen“
    und unter https://www.coronawarn.app/assets/documents/cwa-privacy-notice-de.pdf
    ) ist nicht Bestandteil dieser Nutzungsbedingungen. Bitte lesen Sie dennoch
    auch die Datenschutzerklärung sorgfältig.
</p>
```

## Steps to reproduce the issue

1. Open Corona-Warn-App/src/main/assets/terms_de.html in Android Studio
2. Press F2 to go to error

## Expected behavior

terms_de.html should not show a syntax error in Android Studio.

## Possible Fix

- Remove html tag `<a name="_Hlk41947003">` or
- Change html tag `<a name="_Hlk41947003">` to `<a id="_Hlk41947003">`

## Additional context

In Android, the anchor reference `"_Hlk41947003"` is only present in the file Corona-Warn-App/src/main/assets/terms_de.html. It is not included in the corresponding terms_en.html nor in terms_tr.html. Perhaps there is some hidden use of this tag? It seems though that it is unnecessary.

On iOS the reference is used in the German and Turkish files, but not in the English terms of use file. I don't have an iOS development environment, so somebody else would need to check if it is an issue in iOS.

---
Internal Tracking ID: [EXPOSUREAPP-7421](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7421)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks.

---
Internal Tracking ID: [EXPOSUREAPP-7421](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7421)
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
PR https://github.com/corona-warn-app/cwa-app-android/pull/3263

**Comment by MikeMcC399** [comment]
F2 in Android Studio says:
"No errors found in this file" when viewing Corona-Warn-App/src/main/assets/terms_de.html of release/2.3.x

Problem is verified as fixed, so closing this issue.
