### ISSUE TITLE
Impossible to copy the error report ID

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#624]
EDIT Corona-Warn-App Open Source Team

On Android you can already long press the ID and copy&paste it like normal text.
Or you can tap the entry to copy it including message, dates and ID.

---

## Current Implementation
You cannot copy the ID of an error report.

## Suggested Enhancement
Make it possible to copy the ID. A long tap on the ID should bring up "Copy Report ID" and the ID gets saved to your clipboard.

## Expected Benefits
Easier to write the ID here since you can just copy paste it and don't have to share a picture, etc.

---
Internal Tracking ID: [EXPOSUREAPP-7420](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7420)

**Comment by dsarkar** [comment]
@Ein-Tim Thanks. Let's consider this as a bug, therefore moved to documentation repository.


---
Internal Tracking ID: [EXPOSUREAPP-7420](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7420)
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@dsarkar / @Ein-Tim 
Would you consider making this more general?

## Ease of use of error report ID

- error report ID should be displayed immediately after submitting report
- error report ID should be displayed in larger readable text (on Android it is quite small)
- error report ID should be able to be copied

**Comment by dsarkar** [comment]
Good morning @MikeMcC399!

We have another internal ticket:


>  error report ID should be displayed immediately after submitting report

 This is covered in Internal Tracking ID: [EXPOSUREAPP-7377](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7377)   **ID hard to find** 
  

> - Expected result:
>   - A notification after sending the error report that it was successfully submitted and show the corresponding ID (and where to find it later)
>   - List error reports in a more prominent way
  

> error report ID should be displayed in larger readable text (on Android it is quite small)

I will add this also to this ticket. 


Thnaks

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim FYI There is another Ticket:  Internal Tracking ID: EXPOSUREAPP-7429: show latest error reports on the top of the list

**Comment by vaubaehn** [comment]
By the way: on Android it seems to be possible to copy the id with long press (Android 6, LG G4, CWA 2.4.3). It copies a bit more than necessary, but it least it worked for me once.

**Comment by dsarkar** [comment]
Quoting @d4rken:

> On Android you can already long press the ID and copy&paste it like normal text.

**Comment by dsarkar** [comment]
@vaubaehn Ah sorry! I didn't see your comment! You already posted the long-press solution.

**Comment by Ein-Tim** [comment]
Then this should probably be moved to the iOS repo.

**Comment by d4rken** [comment]
> By the way: on Android it seems to be possible to copy the id with long press (Android 6, LG G4, CWA 2.4.3). It copies a bit more than necessary, but at least it worked for me once.

You can long press the ID to get normal text selection, or tap the whole entry and all of it's text will be copied to your clipboard.

**Comment by Ein-Tim** [comment]
This has become an iOS only issue and should be moved to the iOS repository.

**Comment by Ein-Tim** [comment]
Although the bug reported in the OP of this issue has never been fixed under iOS, I'm closing this issue now as the CWA project went into ramp-down mode and I therefore don't expect this issue to be fixed anymore.
