### ISSUE TITLE
In which states does the rapid test proof feature comply with legal requirements?

### ISSUE THREAD

**Issue by ferdinand** [corona-warn-app/cwa-documentation#628]
## What is missing

I cannot find any information on which states accept the CWA as proof of a negative rapid corona test. The Berlin regulation requires a specification of the test site. Accordingly, I assume that the CWA is not a valid proof. Is that correct?

## Why should it be included

Users should not have to search forever on their state's website only to find nothing there.

## Where should it be included

At least in the FAQ of the website. Better would be in the app as well.

**Comment by Ein-Tim** [comment]
To give a little update about this: 

The EU Digital Test Certificate will also include the name of the test center. You can request this certificate In-App for PCR & Rapid Antigen Test starting at version 2.4.
The normal RAT proof feature is not changed and still doesn't include the name of the testing site. 

So: 
EU Digital Test Certificate ✅
RAT Proof Feature in-App ❌

**Comment by Ein-Tim** [comment]
I suggest to close this issue now, as the app now includes a different text:

"To verifiably prove the result displayed here, an EU Digital Covid Certificate is required. If you requested a digital test certificate when you registered your test and the testing point supports the issuing of digital certificates, you can find your digital test certificate using the link specified above. You will also find the certificate on the “Certificates” tab.\nPlease also find out about the criteria for recognition and validity of test certificates in the context of the purpose for which you need proof."

This means that there is no proof feature in the app anymore.

FYI @ferdinand
