### ISSUE TITLE
Rapid Test Profile: Date of birth can be in the future

### ISSUE THREAD

**Issue by FlightMS** [corona-warn-app/cwa-documentation#631]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 11
- iOS version: iOS 14.5.1
- App version: 2.2.1

## Describe the bug

The date of birth in the Rapid Test Profile can be set to be in the future.

## Steps to reproduce the issue

1. Open Rapid Test profile
2. Edit date of birth and scroll in the future

![DateOfBirth2050](https://user-images.githubusercontent.com/82420268/117959375-3c79bf00-b31c-11eb-9ed5-08e82712623d.png)

## Expected behaviour

The date of birth can be set only for the past. Also the minimun allowed age to use the app should be considered.

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-7224](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7224) Android & iOS
Internal Tracking ID: [EXPOSUREAPP-7293](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7293)

**Comment by marcauberer** [comment]
This was fixed for Android in [this pr](https://github.com/corona-warn-app/cwa-app-android/pull/3771). On iOS it might still be possible to set dob to the future though ...

**Comment by marcauberer** [comment]
Alright 👍🏼 
Can we close this issue then?

**Comment by Ein-Tim** [comment]
@marcauberer 

I would suggest to wait for feedback from somebody using Android, just to make sure that the implementation there works (as expected) too. 🙂

**Comment by marcauberer** [comment]
@Ein-Tim the internal ticket is already confirmed.

**Comment by Ein-Tim** [comment]
Okay, then I leave it to you @marcauberer to close this (-:

**Comment by marcauberer** [comment]
Will close it as soon as v2.7 is out ...

**Comment by MikeMcC399** [comment]
@marcauberer 
2.7 was released on August 16, 2021 See https://www.coronawarn.app/en/blog/2021-08-16-cwa-version-2-7/

I can confirm in CWA Android 2.7.1 that it is no longer possible select a date of birth for a date in the future.

Based also on the https://github.com/corona-warn-app/cwa-documentation/issues/631#issuecomment-899388995 from @Ein-Tim, it should be possible to close this issue. @FlightMS might also like to double-check.

**Comment by FlightMS** [comment]
I can also confirm, that it‘s not possible to set a birth date in future anymore.

Thanks to all!
