### ISSUE TITLE
Vaccination Certificate QR-Code not working

### ISSUE THREAD

**Issue by roskaboska** [corona-warn-app/cwa-documentation#633]
Hello :)

today I tried to scan the QR Code for my vaccine verification but i was shown this following error: 

`This QR Code is not valid vaccination certificate. (VC_PREFIX_INVALID).`

I have two QR codes on my verification document and both don't work. My verification document is 100% true. 

My device is an iPhone 11 with iOS 14.6. 

I have the latest Corona-Warn-App Version from the AppStore. 

Thank you in advance! 

Best regards

**Comment by Ein-Tim** [comment]
Hello, please see https://www.coronawarn.app/de/faq/#vac_cert_invalid.

**Comment by roskaboska** [comment]
Thank you! Didn't see this FAQ in the app.

**Comment by Ein-Tim** [comment]
@roskaboska 

It's not yet in the app. The team will release a hot fix soon which improves the error message.
