### ISSUE TITLE
Contact journal info text has to be extended to reflect that tests are shown in the journal now

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#635]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 12 Pro Emulator
- iOS/Android version: iOS 14.5
- App version: 2.4.8 (0) (iOS)

## Describe the bug

The info screen that is shown when a user opens the contact journal the first time or clicks on the 3 dots in the right corner and then on "Information" does not reflect that the contact journal also shows registered tests there now (this is a feature of version 2.4).

Screenshot from iOS:
<img src="https://user-images.githubusercontent.com/67682506/121711556-05452c00-cadb-11eb-8411-460b89f904db.png" width="300">

## Steps to reproduce the issue

1. Build the app based on the `release/2.4.x` branch
2. Click on "Journal" in the tab bar
3. Click on the 3 dots in the right corner if you have used the contact journal before
4. Click on "Information"
5. See that there is no mention of the tests that are shown in the contact journal

## Expected behaviour

There should be a mention that the contact journal now also shows registered tests.

## Possible Fix

Add the texts.

## Additional context

Please check if this is valid for Android too.

----
Internal Tracking-ID: [EXPOSUREAPP-7971](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7971)

**Comment by heinezen** [comment]
@Ein-Tim 

Thanks. The devolopers are informed and will take a look at this.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
This is still a valid issue on version 2.20.

**Comment by Ein-Tim** [comment]
Although this is still a valid issue with version 3.0 installed, I'm closing this issue now, as the CWA project went into ramp-down mode. I therefore don't expect this issue to be addressed anymore.
