### ISSUE TITLE
DCC: Sanitize (Transcode/Encode/Store) scanned CBOR/JSON data strictly according to ehn-dgc-schema

### ISSUE THREAD

**Issue by vaubaehn** [corona-warn-app/cwa-documentation#637]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [x] Bug is not already reported in another issue

## Technical details
- Device name: n/a
- iOS/Android version: n/a
- App version: 2.3.2

## Describe the bug
For the time being, some authorities already issuing DCCs in Europe are not strictly following the [ehn-dgc-schema](https://github.com/eu-digital-green-certificates/ehn-dgc-schema) when encoding certificate data. Wallet apps, such as CWA 2.3.2 iOS may however successfully scan, import and store such DCCs, when their scanning/validating algorithm is relaxed/lenient enough. Other wallet apps, such as CWA 2.3.2 Android or CovPass App 0.160.3 Android may crash while scanning or refuse to import these certificates. Verfying apps, such as CovPassCheck App 0.160.3 Android may also refuse presented DCCs as invalid.

For a current issue, see https://github.com/corona-warn-app/cwa-app-android/issues/3417 .
When investigating this issue, it became obvious that CWA 2.3.2 on iOS can successfully import a certificate with an invalid data field according to ehn-dgc-schema. When from this data set a QR code is generated in CWA iOS, to be presented to a verifier app - or in this case, CWA Android as a scanning/wallet app, CWA Android crashes due to the invalid data field. This means, that CWA iOS did not sanitize the scanned data, but stored and encoded them for QR code generation, exactly as they were scanned.
To enable CWA _Android_ to also import/store DCCs with diverging data field contents according to the standard schema, a PR was introduced to make parsing data more lenient (https://github.com/corona-warn-app/cwa-app-android/pull/3418).

**Which consequences does this have practically?** 
Wallet apps, that are able (lenient/relaxed enough) to store DCCs with invalid data fields and that generate QR codes with the exactly same scanned data, can cause bad surprises at border control, when the verifier app is strictly applying the standard schema to the QR code. While the traveller thinks, he presents a valid DCC, he is rejected at border control, because the verifier app does not accept it.

## Steps to reproduce the issue
1. Craft your own DCC where some data fields are deverging from the standard schema, e.g., add a timestamp to your date of birth, like: 1968-31-12T23:59:59+2 (but with a vaild PKI signature, for sure ;) )
2. Scan this with CWA 2.3.2 **iOS** - and see everything is imported fine.
3. Scan this with CWA 2.3.2 **Android** - and see app crashing.
4. Pack your iOS device, travel by plane to any EU country.
5. Present your DCC QR code from your iOS device at border control, and experience all the things that might happen now...

## Expected behaviour
There could be two options:
1. All wallet apps and also CWA refuse to scan DCCs with invalid data fields/types. OR:
2. All wallet apps MUST sanitize scanned data (CBOR/JSON) to meet the ehn-dgc-schema.

## Possible Fix
According to the options above:
1. Regression of PR https://github.com/corona-warn-app/cwa-app-android/pull/3418 and make sure that also CWA iOS is not accepting DCCs with invalid data fields. OR:
2. Implement a sanitzing algorithm to both CWA iOS and Android, transcode/store data strictly according to ehn-dgc-schema.

## Additional context
What will result from the proposed fixes?
1. Some EU countries need to correct their issuing IT solutions/apps for invalid data fields. Citizens of these countries need to exchange their already obtained DCCs with corrected ones, or they may experience problems at border control. OR:
2. Any EU citizen with an already issued DCC containing invalid data fields will not perceive any problem. The invalid data fields are sanitized to correct data, a valid QR code will be generated and can be presented at border control without any issue,

**Comment by thomasaugsten** [comment]
It is planned with the acceptance rules that all EU wallet app has to check the json schema before importing the DCC

**Comment by vaubaehn** [comment]
@thomasaugsten
> It is planned with the acceptance rules that all EU wallet app has to check the json schema before importing the DCC

You mean strictly according to ehn-dgc-schema?
Would this mean in the case of https://github.com/corona-warn-app/cwa-app-android/issues/3417 , that https://github.com/corona-warn-app/cwa-app-android/pull/3418 needs to be rolled back and CWA iOS would need to be more strict on importing DCCs?

**Comment by thomasaugsten** [comment]
The official schema will be adjusted to deviance of the real DCC. We will double check the schema validation in iOS

**Comment by vaubaehn** [comment]
This means, also all Verifier Apps need to be adjusted to the extended schema (if data is not sanitized). Which in result means, that it may take a while longer, until the system works fully...

**Comment by Ein-Tim** [comment]
Please forgive me for joking (I usually don't do this), but

> 4. Pack your iOS device, travel by plane to any EU country.
> 5. Present your DCC QR code from your iOS device at border control, and experience all the things that might happen now...

sounds very realistic, I will do that now, please give me some time... 😉

**Comment by vaubaehn** [comment]
@Ein-Tim At least there is a good chance that your DCC (you already have one?!) is in line with the schema...
Good luck with your 6s 😉 and enjoy your vacation! 🍹 🌴

**Comment by vaubaehn** [comment]
Ok. I think, my proposal to sanitize data is not working:
When we're sanitizing data, the certificate's signature will become invalid when later generating a nicer QR code, right?
Can someone confirm?

**Comment by vaubaehn** [comment]
Though it was an interesting trip through this subject, it finally led to nowhere.
Only two options:
1. adjust the schema and accordingly ALL apps/IT, or
2. restrict wallet apps to only scan/import according to the current schema.

As 2) is the politically not so beautiful solution, 1) seems the only way to go.
And I go into the week-end now. @thomasaugsten and @Ein-Tim : thanks for sharing and have a nice week-end also!

**Comment by vaubaehn** [comment]
Just for reference, and for the interested reader:
In line with @thomasaugsten 's explanations, an updated and freshly released ehn-dcc-schema is available here:
https://github.com/ehn-dcc-development/ehn-dcc-schema
Looks like regex-patterns are introduced to make the deviations to the original schema possible.
