### ISSUE TITLE
How can COVID recovered and one time vaccinated people get their digital vaccination certificate?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#639]
## Your Question
As the title says, there are quite many people out there who recovered from a COVID infection and now got vaccinated one time. They have the same status as normally vaccinated people, but it seems like there is currently no way yet to request a digital certificate. Or am I missing something?

## Additional information

If this was asked anywhere (not only in the CWA GitHub, but also for example https://github.com/Digitaler-Impfnachweis, https://github.com/ehn-dcc-development or https://github.com/eu-digital-green-certificates) before, please point me to this issue.
If you know another, more suitable place where to ask this, please let me know!
Thank you!

**Comment by MikeMcC399** [comment]
@Ein-Tim 
I expect this is for the next version, although the FAQ doesn't describe specifically recovery + vaccination.

https://www.bundesgesundheitsministerium.de/coronavirus/faq-covid-19-impfung/faq-digitaler-impfnachweis.html

**Kann man auch im digitalen Impfnachweis speichern, dass man bereits infiziert war oder negativ getestet wurde?**

Auch negative Tests oder eine durchgemachte Infektion werden sich zukünftig in der CovPass App und auch CWA in der nächsten Entwicklungsstufe (bis Ende Juni) als Testzertifikat bzw. Genesenenzertifikat hinterlegen lassen. Eine durchgemachte Infektion wird mittels eines PCR-Test-Ergebnisses dokumentiert.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Okay, thank you for the source! Do you know if there is any (legal) difference between only recovered and recovered + one time vaccinated?

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> Okay, thank you for the source! Do you know if there is any (legal) difference between only recovered and recovered + one time vaccinated?

Check out https://www.bundesanzeiger.de/pub/publication/x6tHxtuQ0pora3FnUEG/content/x6tHxtuQ0pora3FnUEG/BAnz%20AT%2008.05.2021%20V1.pdf?inline

Verordnung
zur Regelung von Erleichterungen und Ausnahmen von Schutzmaßnahmen
zur Verhinderung der Verbreitung von COVID-19
(COVID-19-Schutzmaßnahmen-Ausnahmenverordnung – SchAusnahmV)
Vom 8. Mai 2021

I'm not a lawyer, so I have to leave it to you to interpret what you read. 🙂

**Comment by Ein-Tim** [comment]
Thank you again, @MikeMcC399!

I'll close this in favor of https://github.com/Digitaler-Impfnachweis/certification-apis/issues/94.
