### ISSUE TITLE
Are there full api calls

### ISSUE THREAD

**Issue by jucktnich** [corona-warn-app/cwa-documentation#640]
## Your Question

* Documentation File:
* Line / Paragraph:
* Question:
Is there a documentation with the full api calls?

**Comment by MikeMcC399** [comment]
@jucktnich 
> Is there a documentation with the full api calls?

I don't know exactly what you are looking for here. Is this question specific for Android or iOS? Which API are you interested in? The main one which CWA uses is the GAEN (Google Apple Exposure Notification) API.

Perhaps you could give an example or explain what you want to do with the information when (if) you get it?

**Comment by jucktnich** [comment]
I meant with the CWA servers

**Comment by MikeMcC399** [comment]
@jucktnich 
> I meant with the CWA servers

Perhaps you are looking for https://github.com/corona-warn-app/cwa-server/blob/main/README.md#service-apis ?

**Comment by jucktnich** [comment]
Sorry for the late answer. Yes something like this but with all calls not only from the app, f.e. the the verification-Server

**Comment by MikeMcC399** [comment]
@jucktnich 
If your question is answered, you may like to close this issue.
