### ISSUE TITLE
Why does the CWA manipulate the certificate QR code and what data is added/changed?

### ISSUE THREAD

**Issue by treysis** [corona-warn-app/cwa-documentation#641]
The QR code in the CWA is different from the printout and the CovPass-app. CovPass shows the same code as on the paper printout. How and why does CWA alter the QR code?

Needless to say, the CWA's QR is still accepted when scanning with CovPassCheck.

**Comment by thomasaugsten** [comment]
The CWA use a different error correction as the paper Printout to follow the EU guidelines. The content is the same

**Comment by treysis** [comment]
Thanks for the info. It's correct. I used a QR code reader on both codes, the contained data string is identical.

**Comment by Ein-Tim** [comment]
@treysis 

If your question is answered, please close this issue.

**Comment by heinezen** [comment]
Closed because the question is answered.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
> CovPass shows the same code as on the paper printout. 

I just scanned a dcc and the QR-Code shown in CovPass is definitely not the one which is printed on the paper. Just to add that here.

**Comment by treysis** [comment]
@Ein-Tim Interesting. Is this QR the same as in the CWA now? Or do you have 3 different codes? Maybe the code for the paper printout has changed in the last days? I still get the same QR in CovPass if I scan my printout, and the "enhanced" QR with the CWA.

**Comment by Ein-Tim** [comment]
@treysis I now have 3 different codes, since the QR-Codes in CWA and CovPass are different to. The vaccination certificate was downloaded from the Bavarian Impfportal (https://impfzentren.bayern/citizen/), so it's a a PDF.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> The vaccination certificate was downloaded from the Bavarian Impfportal (https://impfzentren.bayern/citizen/), so it's a a PDF.

Good to know about this! It wasn't planned to be available until tomorrow (June 25, 2021).
