### ISSUE TITLE
App not clear which format vaccination certificate acceptable

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#643]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
bug relates to FAQ article https://www.coronawarn.app/en/faq/#vac_cert_invalid
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 3a emulator
- Android version: 11
- App version: 2.4.1-RC2

## Describe the bug

The introduction to scanning certificates does not clearly describe that only EU compatible vaccination certificates can be successfully scanned. Instead users are scanning QR codes that they received after being vaccinated, before the new format was introduced, and they receive the app error 'This QR code is not a valid vaccination certificate. (VC_PREFIX_INVALID)'.

## Steps to reproduce the issue

1. On Start Screen, tap "Certificates"
2. Read text on screen "Add Certificates"
3. Tap "CONTINUE"
4. Read tile "Add Digital Proof of Vaccination"

![Add Certificates](https://user-images.githubusercontent.com/66998419/122807998-8f0bab00-d2cc-11eb-8f01-2942776c77d3.jpg)

![Certificates](https://user-images.githubusercontent.com/66998419/122808011-916e0500-d2cc-11eb-8595-423ee4c791e1.jpg)

## Expected behavior

The app should be clear about what type of digital proof of vaccination it can accept.

## Possible Fix

Add text to the screens leading up to the QR-Code Scan so that the user is able to recognize if the QR-Code they plan to scan is likely to be accepted by the app. If the app is only able to scan in an "EU Digital Covid Vaccination Certificate", then this term should explicitly appear in the text.

## Additional context

The document https://ec.europa.eu/health/sites/default/files/ehealth/docs/covid-certificate_paper_guidelines_en.pdf shows an EU example of a typical EU Digital Covid Vaccination Certificate in paper and digital form.

---
Internal Tracking ID: [EXPOSUREAPP-8029](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8029)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks! Internally tracked.


---
Internal Tracking ID: [EXPOSUREAPP-8029](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8029)
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
The certificate specification https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-certificates_v1_en.pdf describes in "4.2.2 QR 2D Barcode" that "..the base45 encoded data (as per this specification) SHALL be prefixed by the Context Identifier string "HC1:"."

To check if you are scanning a compatible code, use a regular QR reader to see if the QR code starts with HC1:

There is an example on https://github.com/Digitaler-Impfnachweis/certification-apis/blob/master/examples/README.md

**Comment by MikeMcC399** [comment]
In CWA Android 2.5.0-RC3 (not yet released) I see the improved text.

Certificates > three-dot symbol > Information

"Add your EU digital COVID certificates in the app. This will enable you to prove your vaccination protection, a negative test result, or your recovery from an infection with the app."

"You can add EU digital COVID vaccination certificates, COVID test certificates, and COVID certificates of recovery in the app."

When 2.5.x is released, the texts above will solve the issue reported here. 👍🏻

**Comment by dsarkar** [comment]
Thanks @MikeMcC399.
