### ISSUE TITLE
Open source the "Schnelltestpartnersuche" website

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#646]
## Where to find the issue
n/a

## Describe the issue
There is now the website https://map.schnelltestportal.de (it has been announced in https://www.coronawarn.app/en/blog/2021-06-24-cwa-version-2-4/), wehre you can search for all RAT partners on a map. Sadly, this website is not (yet) open source.

## Suggested change
Please open source it! (-: 

----
Internal Tracking-ID: [EXPOSUREAPP-8124](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8124)

**Comment by heinezen** [comment]
@Ein-Tim 

Thanks for the request. I've forwarded he request to Jira. T-Systems is responsible here, so let's see what they and the RKI have to say.

----
Corona-Warn-App Open Source Team

**Comment by rugk** [comment]
Oh yes, and not using Google Maps would be another good thing. E.g. https://umap.openstreetmap.fr/en/ or https://switch2osm.org/ shows good alternatives that are also free to use (no license fee as [Google now let's you pay](https://cloud.google.com/maps-platform/pricing/)…

**Comment by dsarkar** [comment]
@rugk Thanks for the proposal, forwarded to internal ticket.

**Comment by Ein-Tim** [comment]
https://github.com/corona-warn-app/cwa-map-public-frontend has just been published. I will take a look at it later on and then close this issue if my suggestion has been implemented sufficiently.

**Comment by Ein-Tim** [comment]
I decided that https://github.com/corona-warn-app/cwa-map-public-frontend fulfills this request.

Therefor closing this issue.

**Comment by dsarkar** [comment]
Good morning @Ein-Tim, Thanks for following up.

**Comment by Ein-Tim** [comment]
@dsarkar 

For sure! Good morning to you too!
