### ISSUE TITLE
Why not using Luca-QR-Codes currently in field?

### ISSUE THREAD

**Issue by gitbrueck** [corona-warn-app/cwa-documentation#649]
## Your Question

* Documentation File:
* Line / Paragraph:
* Question:

**Comment by DerVogel2020** [comment]
Can you please explain your question a little bit more?

**Comment by Ein-Tim** [comment]
Here's the answer: https://github.com/corona-warn-app/cwa-documentation/issues/590#issuecomment-852881800

More information can also be found here: https://github.com/corona-warn-app/cwa-server/pull/1362

**Comment by Ein-Tim** [comment]
Can we close this @gitbrueck? 

You can monitor the situation reg. luca in this threads:
- https://github.com/corona-warn-app/cwa-documentation/issues/590
- https://github.com/corona-warn-app/cwa-server/pull/1362

**Comment by dsarkar** [comment]
@gitbrueck FYI https://www.coronawarn.app/de/faq/#check_in_luca
