### ISSUE TITLE
Journal sorting of places or people with Umlaut is out of order

### ISSUE THREAD

**Issue by jancborchardt** [corona-warn-app/cwa-documentation#650]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Fairphone 3+, iPhone 11
- iOS/Android version: Android 10, iOS 14.6
- App version: 2.3.4.1

## Describe the bug

In the list of people an places, entries e.g. starting with an Umlaut are sorted all the way on the bottom. This is unexpected especially since it’s an app focused on Germany.

## Steps to reproduce the issue

![Screenshot_20210427-192829_Corona_Tracing](https://user-images.githubusercontent.com/925062/123622007-0c26ab00-d80c-11eb-971f-cb97bd47ab73.png)

1. Go to Journal
2. Click on any day
3. Add a new person or place e.g. starting with an "Ä"
4. See how it is sorted all the way on the bottom

## Expected behaviour

Ä is sorted after or with A, Ö is sorted after or with O, Ü after/with U, ß after/with s/ss.
Ideally this would also extend to other languages e.g. with the Polish Ł.

## Possible Fix

For Android, I assume the fix will need to be in the same place as where @PhilippNowak96 fixed the sorting of people and places to be case insensitive https://github.com/corona-warn-app/cwa-app-android/pull/2017/files

I couldn’t find a similar pull request for iOS so I’m not sure there.

----
Internal Tracking-ID: [EXPOSUREAPP-8280](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8280) Android
Internal Tracking-ID: [EXPOSUREAPP-8177](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8177) iOS

**Comment by MikeMcC399** [comment]
@jancborchardt 

Probably the app should sort according to DIN 5007-1 for the German locale (see https://de.wikipedia.org/wiki/Alphabetische_Sortierung). The simplest is Variante 1 (like your suggestion). Variante 2 is better for lists of names, but may be overkill for the application of the CWA contact journal.

**Comment by jancborchardt** [comment]
Yes, 1 seems perfectly fine for this case. I assume Java might have some sort of locale check which could do this automatically, but I don't know.

**Comment by heinezen** [comment]
@jancborchardt 

Thanks for reporting. I've forwarded the report to the developers wher it will be investigated now. I also included @MikeMcC399 's suggestion.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
PR: https://github.com/corona-warn-app/cwa-app-ios/pull/3136

**Comment by Ein-Tim** [comment]
@jancborchardt Can you pleas recheck if this is still an issue?

**Comment by mtwalli** [comment]
Android PR: https://github.com/corona-warn-app/cwa-app-android/pull/5419 targeting 2.26.0

**Comment by Ein-Tim** [comment]
@mtwalli Thank you! Could you please create & apply the `Fix 2.26` label to this issue? Thanks!

**Comment by mtwalli** [comment]
@Ein-Tim ,  I don’t have access to this repo. I will ask around who can grant me access now. Unfortunately @dsarkar left the project

**Comment by Ein-Tim** [comment]
@mtwalli Yeah, the information that the CMs are away for some time came through to us, thanks! It would be great if you and the other devs could get access to this repo so that you can at least apply labels to issues & close fixed issues, to at least keep a minimal housekeeping effort going.

**Comment by MikeMcC399** [comment]
@jancborchardt 

I checked with CWA Android 2.26.0 on Android 10 and now "Ährensache" is sorted at the top (after "Aachen" and before "Apotheke").

Perhaps you would like to check for yourself and close this issue if you are satisfied?

**Comment by mtwalli** [comment]
@MikeMcC399  Thanks for checking and confirming the fix. 
@jancborchardt  I'm closing the issue, feel free to re-open if you can produce it
