### ISSUE TITLE
Would it be ok to use your issue templates at CovPass?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#652]
## Your Question

Would it be ok to use your issue templates at https://github.com/Digitaler-Impfnachweis? 
I'm thinking about contributing there with a PR which adds issues templates, and would like to use yours. For sure I would adapt them so that they match the project structure there and remove references to the CWA project.

Pinging @SebastianWolf-SAP here, since he initially committed the issue templates.

**Comment by dsarkar** [comment]
@Ein-Tim I thinks yes, but I will cross check.

**Comment by GisoSchroederSAP** [comment]
Agreed! We are already on the way to sync and consolidate - using similar/same templates makes this even easier, thanks!

**Comment by Ein-Tim** [comment]
@GisoSchroederSAP @dsarkar 

Thank you! I'll open my PR in the iOS repo there and see how they respond.

**Comment by heinezen** [comment]
@Ein-Tim 

The issue templates are covered by the repository license (Apache 2.0). Since CovPass uses the same license, it shouldn't be an issue to reuse them there.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Thank you for all your feedback here. I'll now wait for feedback of the maintainers over at CovPass, and if they decide to use the issue templates, I'll also provide PRs for the other repos.

My question here has been answered, so I'll close this as answered.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks.
