### ISSUE TITLE
Error message scanning vaccination, test and recovery certificates only refers to vaccination certificates

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#653]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy A5 (2017) SM-A520F
- Android version: 8.0.0
- App version: 2.5.0-RC3 (pre-release version)

Also affects iOS.

## Describe the bug

When a scan error occurs scanning an EU digital COVID certificate, the error message refers only to a vaccination certificate. Starting with the upcoming 2.5.x release , "You can add EU digital COVID vaccination certificates, COVID test certificates, and COVID certificates of recovery in the app." and these three types of certificates are all scanned in the same place.

The error message is:

"This QR code is not a valid vaccination certificate.

For more information about how to receive your vaccination certificate, please see our FAQ page. (VC_PREFIX_INVALID)"

The error message also links to the FAQ article https://www.coronawarn.app/en/faq/#vac_cert_invalid which is specific to vaccination certificates.

## Steps to reproduce the issue

1. Tap "Certificates" in the bottom menu bar
2. Tap "ADD CERTIFICATE"
3. Scan any QR code which is not a valid EU digital COVID certificate such as the following QR code which contains the text "DE12345678"

![QR Code DE12345678](https://user-images.githubusercontent.com/66998419/105467552-25905d80-5c96-11eb-8408-b4835ee6d61f.png)

![image](https://user-images.githubusercontent.com/66998419/124126617-24503180-da7b-11eb-8f6c-8448c00464ad.png)

## Expected behavior

If the scan is looking for EU digital COVID vaccination certificates, COVID test certificates or COVID certificates of recovery and none of these certificates are recognized by the scan then the error message should not assume that the user was trying to scan a vaccination certificate. They could have been trying to scan in a test or a recovery certificate.

## Possible Fix

- Make the error message more generic to cover also test and recovery certificates
- The prefix "VC" in the code "VC_PREFIX_INVALID" makes it look like a vaccination error. Perhaps this should also be changed?
- Either link to a new FAQ article which describes the error for the three different types of certificates which can be scanned or update the existing FAQ article https://www.coronawarn.app/en/faq/#vac_cert_invalid to cover the three different cases. (A new FAQ article would be easier to handle.)

---
Internal Tracking ID: [EXPOSUREAPP-8216](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8216) iOS
Internal Tracking ID: [EXPOSUREAPP-8226](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8226) Android

**Comment by Ein-Tim** [comment]
@dsarkar 

May we get the internal Tracking-ID here? 

Thank you!

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim Thanks.

---
Internal Tracking ID: [EXPOSUREAPP-8216](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8216)
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
I believe this error is shown if the QR code does not start with the prefix "HC1:" as defined in the certificate specification https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-certificates_v1_en.pdf describes in "4.2.2 QR 2D Barcode" that "..the base45 encoded data (as per this specification) SHALL be prefixed by the Context Identifier string "HC1:".".

Therefore the error message and link to FAQ should say that the QR code is not a valid Health Certificate (rather using the name Vaccination Certificate which is a subset of Health Certificates).

Also it would be helpful for troubleshooting if the FAQ explained that the error message XX_PREFIX_INVALID means that the characters "HC1:" are missing from the start of the QR code. Technical users might like to just check with a regular QR code reader to see what text is being read and if the QR code does start with the characters "HC1:" or not.

**Comment by dsarkar** [comment]
FYI PR iOS https://github.com/corona-warn-app/cwa-app-ios/pull/3070

**Comment by dsarkar** [comment]
VC_PREFIX_INVALID was changed to HC_PREFIX_INVALID. The text is generic and fits all types of certificates.

**Comment by MikeMcC399** [comment]
@dsarkar 
Is there a PR for Android as well, or is that still pending?

**Comment by dsarkar** [comment]
@MikeMcC399 My understanding is that it is still pending.

**Comment by dsarkar** [comment]
---
Internal Tracking ID: [EXPOSUREAPP-8216](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8216) iOS
Internal Tracking ID: [EXPOSUREAPP-8226](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8226) Android

**Comment by dsarkar** [comment]
Android PR with new link https://github.com/corona-warn-app/cwa-app-android/pull/3612

**Comment by MikeMcC399** [comment]
@dsarkar 
> Android [corona-warn-app/cwa-app-android#3612](https://github.com/corona-warn-app/cwa-app-android/pull/3612)

The merged PR only partially solves the issue:

---
Other strings in the file https://github.com/corona-warn-app/cwa-app-android/blob/release/2.5.x/Corona-Warn-App/src/main/res/values-de/vaccination_strings.xml still need to be changed:

https://github.com/corona-warn-app/cwa-app-android/blob/d08d828f219ed0bedb5a4903ee78b60c3a7bda4d/Corona-Warn-App/src/main/res/values-de/vaccination_strings.xml#L98-L99

```
    <!-- XTXT: Vaccination QR code scan error message-->
    <string name="error_vc_invalid">Dieser QR-Code ist kein gültiges Impfzertifikat.\n\nWeitere Informationen zum Erhalt Ihres Impfzertifikats finden Sie in den FAQ.</string>
```

https://github.com/corona-warn-app/cwa-app-android/blob/d08d828f219ed0bedb5a4903ee78b60c3a7bda4d/Corona-Warn-App/src/main/res/values-de/vaccination_strings.xml#L109-L110

```
    <!-- XBUT: Text for invalid vaccination certificate error button, linking to FAQ-->
    <string name="error_button_vc_faq">FAQ zu Impfzertifikaten</string>
```

---
The FAQ article https://www.coronawarn.app/de/faq/#hc_prefix_invalid has not yet been created.
https://github.com/corona-warn-app/cwa-app-android/blob/d08d828f219ed0bedb5a4903ee78b60c3a7bda4d/Corona-Warn-App/src/main/res/values-de/vaccination_strings.xml#L111-L112

```
    <!-- XTXT: Explains user about vaccination certificate: URL, has to be "translated" into english (relevant for all languages except german) - https://www.coronawarn.app/en/faq/#vac_cert_invalid -->
    <string name="error_button_vc_faq_link">https://www.coronawarn.app/de/faq/#hc_prefix_invalid</string>
```

**Comment by dsarkar** [comment]
@MikeMcC399 See https://github.com/corona-warn-app/cwa-app-android/pull/3617

**Comment by MikeMcC399** [comment]
@dsarkar 
Thanks for the follow up! It works now on Android 2.5.x in German. For English we have to wait for the translation.

The FAQ article still needs to be created.

**Comment by MikeMcC399** [comment]
@dsarkar 

The text in English is now correct.

![image](https://user-images.githubusercontent.com/66998419/124722041-f1d68680-df09-11eb-8d65-01beeffd468e.png)

**Comment by MikeMcC399** [comment]
https://github.com/corona-warn-app/cwa-website/issues/1462 opened for missing FAQ article.

Closing this issue, since the issue as reported is fixed, and the problem was in a pre-release version.
