### ISSUE TITLE
Where to report feature requests or bugs that affect both CovPass and CWA or that are conceptual issues

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#654]
## Your Question
Where should the community report feature requests, bugs or conceptual issues that affect both CovPass & CWA?

I'm thinking about issues like https://github.com/corona-warn-app/cwa-wishlist/issues/573 & https://github.com/corona-warn-app/cwa-wishlist/issues/574

**Comment by jucktnich** [comment]
I guess in the dcc overview

**Comment by heinezen** [comment]
Best practice would probably be to create issues in both organization's repositories (i.e. CWA and https://github.com/Digitaler-Impfnachweis).

**Comment by Ein-Tim** [comment]
@heinezen 

Okay. Would you like to add this to the wishlist issues I linked to above?

**Comment by Ein-Tim** [comment]
I consider this as solved but would like to ask the community managers to clearly communicate this in the respective issues that are opened here, in the https://github.com/coronawarnapp organization.

Closing as answered.
