### ISSUE TITLE
Rapid Test Profile - ä, ü, ö & ß are not correctly shown after QR-Code scan

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#656]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation) - Can't check
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 6s
- iOS version: 14.6
- App version: 2.2.1

## Describe the bug

The characters ä, ü, ö and ß are not shown to the user correctly.

## Example

| QR-Code | Data shown in CWA | Actual Result |
| --- | --- | --- |
| ![IMG_AF03A2E5E4A1-1](https://user-images.githubusercontent.com/67682506/120871665-89a82400-c59c-11eb-9d89-7ee3e19c4176.jpeg) | ![IMG_25007B55AA0A-1](https://user-images.githubusercontent.com/67682506/120871689-a3e20200-c59c-11eb-9f28-1659a6ea6a04.jpeg) |![IMG_937CD3D0A10F-1](https://user-images.githubusercontent.com/67682506/120871695-a9d7e300-c59c-11eb-90ce-413238fd66b8.jpeg) |

## Steps to reproduce the issue

1. Open the Corona-Warn-App
2. Scroll down to the "Register your Test" box & click on "Next Steps
3. Click on "Create Rapid Test Profile"
4. Enter the data, include one (or more) of the characters mentioned above
5. Once you have entered all data Click on "Save"
6. Scan the QR-Code with the native iOS camera app
7. See that the characters are not shown correctly. 

## Expected behaviour

The data shown & entered in the CWA should be the data that is stored into the QR-Code.

## Additional information

Please check if this is a problem under Android too. 

---
Internal Tracking ID: [EXPOSUREAPP-7282](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7282)

**Comment by heinezen** [comment]
We have received more reports for Android in the stores as well, so it's confirmed the issue exists for both OSs. Therefore, I've moved the issue to cwa-documentation.

----
Corona-Warn-App Open Source Team
