### ISSUE TITLE
Which use has the start and end time of an event?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#657]
## Your Question
When creating a QR-Code for an event, either via https://www.coronawarn.app/en/eventregistration/ or via the app, you can select the event type "Event". For this type, a start and an end time is required.
After some testing, it doesn't really get clear to me when or if this end and start time is relevant at all. 

At least the end time is not used as a time where everyone checks out - for this the default check in time is used.

**Comment by vaubaehn** [comment]
@Ein-Tim 
> At least the end time is not used as a time where everyone checks out - for this the default check in time is used.

When the default check out time is set to 00:00, would then the end time be used for check out? At least I'd expect that.

For me check in and out time makes sense for a regular meeting, for example:
The regular meeting of the CWA community club takes place on Monday from 20:00 to 22:00. Default check out time should be set to 00:00.
We'll meet in front of the meeting room at 19:50, already checking in and having a beer together, before the session starts.
At 20:00 we're entering the room, but we're already checked in.
At 22:00 the session finishes, and CWA should check us out automatically.

That's how I'd expect it to work...

**Comment by Ein-Tim** [comment]
@vaubaehn 

Under iOS I don't find a way to set the default check out time to 0 minutes, besides of creating an event which starts now and ends now. 
In all other cases the length of the event is just ignored and the default check out time is used.

The 0 minutes thing seems to be an issue under Android: https://github.com/corona-warn-app/cwa-app-android/issues/2950

**Comment by vaubaehn** [comment]
Hi @Ein-Tim , please see also https://github.com/corona-warn-app/cwa-app-android/issues/2950#issuecomment-879943467

**Comment by Ein-Tim** [comment]
Maybe @thomasaugsten could bring some light into the darkness here? 

If not, please mirror this question to JIRA @dsarkar, so that a suitable answer is delivered. :D

Thank you!

**Comment by Ein-Tim** [comment]
This issue was opened more than 1 1/2 years ago and wasn't answered. The question itself is still valid, though. But, as the CWA project went into ramp-down mode, I'm not interested in an answer to this question anymore. I'm therefore closing this issue now.
