### ISSUE TITLE
Wrong value in the contact journal

### ISSUE THREAD

**Issue by Jens07** [corona-warn-app/cwa-documentation#660]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 11
- iOS/Android version: iOS 14.6
- App version: 2.5.1

## Describe the bug
The contact journal offers for each person an entry if the contact was more or less than 15 minutes. But this differentiation is overvalued due to the virus mutations.

## Steps to reproduce the issue
1. Go to the journal
2. Choose a specific date
3. Create a new entry for an existing person

## Expected behaviour
There should be a differentiation if the contact was more than 10 minutes or less.

## Possible Fix
The current recommendations of the Robert-Koch-Institut for the identification of contact persons should be observed. See https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Kontaktperson/Management.html for further details.

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-8827](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8827) obsolete
Internal Tracking ID: [EXPOSUREAPP-8923](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8923) 
Internal Tracking ID: [EXPOSUREAPP-7137](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7137)
Internal Tracking ID: [EXPOSUREAPP-9236](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9236) Android
Internal Tracking ID: [EXPOSUREAPP-9290](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9290) iOS

**Comment by Ein-Tim** [comment]
Closely related to: https://github.com/corona-warn-app/cwa-app-android/issues/3039

**Comment by Jens07** [comment]
I am astonished. The failure is obvious and it seems very easy to fix. But nobody cares 🤔

**Comment by dsarkar** [comment]
@Jens07 Thanks for contributing here. Basically you are suggesting to reduce the 15 min to 10 min in the contact journal? 

---
Corona-Warn-App Open Source Team

**Comment by Jens07** [comment]
> Basically you are suggesting to reduce the 15 min to 10 min in the contact journal? 

It is NOT my suggestion! It is the official recommendation of the Robert Koch-Institut. It's the publisher of the CWA itself. See https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Kontaktperson/Management.html;jsessionid=28E073D7406A159FB8017533A59EA9F0.internet101?nn=2386228#doc13516162bodyText10

It seems very strange for me if the RKI uses an outdated value in his app.

**Comment by dsarkar** [comment]
@Jens07 Thanks for your feedback. We will raise this issue internally.

**Comment by dsarkar** [comment]
@Jens07 Thanks again for contributing here. This issue had been brought forward to the RKI and is considered valid. In a future release this issue will be addressed. New Internal Tracking ID: [EXPOSUREAPP-8923](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8923)


---
Corona-Warn-App Open Source Team

**Comment by vaubaehn** [comment]
Hi @dsarkar , just one technical proposal:
If not already implemented, the addressed value for the contact journal could be added to the app config. Just in case there may be more adaptations in the future (due to different virus variants), changes could easily be made by altering the remote app config instead of hardcoding the value and pushing a new app release.
Cheers, v.

**Comment by dsarkar** [comment]
@vaubaehn I will forward your idea to the internal ticket. Thanks.

**Comment by Ein-Tim** [comment]
FYI: iOS PR: https://github.com/corona-warn-app/cwa-app-ios/pull/3502 changes "15 min" to "10 min".
