### ISSUE TITLE
What will happen go DCC w/o a valid signature in version 2.7?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#662]
## Your Question
It [seems](https://github.com/corona-warn-app/cwa-app-ios/pull/3194) like version 2.7 will prevent users from adding certificates without a  valid signature to the app. 
If a user has already imported certificates w/o a valid signature, will they be removed or will they just stay in the app?

**Comment by thomasaugsten** [comment]
The certificate will shown as invalid without QR-Code like expired certificates.

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Thanks for the quick answer.

Closing as answered.
