### ISSUE TITLE
Wrong (exchanged) issue and expiry dates in RAT-certificate

### ISSUE THREAD

**Issue by benlorenz** [corona-warn-app/cwa-documentation#668]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Xiaomi Mi 10 Lite 5G
- iOS/Android version: 11
- App version: CWA 2.5.1

## Describe the bug

RAT-Test taken on July 23 (sample collection according to the certificate 2021-07-23T09:03:30Z).
A RAT-certificate was generated using a link from the test booking platform with the CWA app. CovPass Check claims "Zertifikat ungueltig" even though the test was just a some hours ago (other check apps also fail, an Austrian one with "zeitlich abgelaufen"). A development build of CWA 2.7 claims "Technisches Ablaufdatum: Gueltig bis 23.07.21".

Decoding the QR-Code (I don't want to post that here as it contains personal information) with https://github.com/ehn-dcc-development/ehn-sign-verify-python-trivial gives the following anonymized output:
```
KID in the unprotected header.
Signature           : 9v3FozjKAUo= @ ES256
Correct signature againt known key (kid=9v3FozjKAUo=)
Issuer              : DE
Experation time     : 1627031908
Issued At           : 1627204708
Health payload      : {
    "dob": "XXXX-XX-XX",
    "nam": {
        "fn": "Xxxxx",
        "fnt": "XXXXX",
        "gn": "Xxxxxx",
        "gnt": "XXXXXX"
    },
    "t": [
        {
            "ci": "URN:UVCI:V1:DE:D7GA1FONW8XWCRHHH95TES6KU8",
            "co": "DE",
            "is": "Robert Koch-Institut",
            "ma": "1604",
            "sc": "2021-07-23T09:03:30Z",
            "tc": "Löwen-Apotheke",
            "tg": "840539006",
            "tr": "260415000",
            "tt": "LP217198-3"
        }
    ],
    "ver": "1.3.0"
}
```
(I repeated that decoding also with some other tools, but always got to the same results)

According to this the expiration time `1627031908` is 2021-07-23T09:18:28 UTC, which does match the CWA 2.7 output.
And the issue date `1627204708` is 2021-07-25T09:18:28 UTC, i.e. in the future.
It seems that the expiration date and issue date in the the certificate are exchanged, making the RAT certificate invalid from the start.

## Steps to reproduce the issue

I don't really know, it probably involves going to some "Löwen-Apotheke" but I have not tried to look up any details of the test-provider but this should be possible using the IDs from the certificate.
It did happen to two people who were tested at the same provider.

## Expected behaviour

The RAT-certificate should validate with CovPass Check and other apps

## Possible Fix

I don't really know where exactly all the data is generated, but even if it is supplied by the test center there could be some validation that at least expiration > issuedAt.

## Additional context

That certificate was not obtained by (or for) me but was reported in the CCTG community channel (#cctg:bubu1.eu on matrix).

**Comment by benlorenz** [comment]
The test center seems to be using the `EcoCare` provider for generating the certificate. The URL for importing it into CWA was generated at https://web.prod.ndident.com/web/dashboard.

**Comment by thomasaugsten** [comment]
For issues with covpass please use the dedicated repo
https://github.com/Digitaler-Impfnachweis/covpass-ios/issues

**Comment by benlorenz** [comment]
The issue I described is not an issue with CovPass but with a wrong (already expired) RAT-certificate that was given the user by CWA. I just mentioned CovPass because that is the recommended way to such a certificate.

As I laid out the dates in the certificate are wrong, any software that will do a proper validation should refuse that certificate.
For example a future CWA 2.7 version:
![image](https://user-images.githubusercontent.com/1437056/126859990-f6c0ab04-bb5f-458b-8897-976bb8705ddf.png)

**Comment by thomasaugsten** [comment]
The certificates are signed by digitaler Impfnachweis not by cwa or the Apotheke 

https://github.com/Digitaler-Impfnachweis/certification-apis

**Comment by thomasaugsten** [comment]
@benlorenz you can also provide me the QR code. I can forward this

Thomas.augsten@sap.com

**Comment by benlorenz** [comment]
I have sent the QR code, thanks for forwarding this!

**Comment by apfarr** [comment]
Hi all, I'm also affected by a similar issue. I described my problem in 
https://github.com/corona-warn-app/cwa-website/issues/1648
and now discovered this tread.

**Comment by Ein-Tim** [comment]
Hey @benlorenz Can this issue be closed now?

**Comment by benlorenz** [comment]
I guess so, yes. I would hope that ecocare or whoever was responsible for this has fixed it in the meantime but I have no way to check (I only analyzed and forwarded it for someone else). If anyone encounters this again we can reopen the issue.

**Comment by Ein-Tim** [comment]
@benlorenz Thanks! You as the author should see a "Close issue" button, which you can press to close this issue.
