### ISSUE TITLE
Spelling / Grammar mistake (?)

### ISSUE THREAD

**Issue by hija** [corona-warn-app/cwa-documentation#669]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone SE 2
- iOS version: iOS 14.7
- App version: 2.5.1 (1)

## Describe the bug

When clicking on the information button for the fully vaccinated people the explanation for the statistics appear.  For fully vaccinated people there is written (in German) "Anzahl der an das RKI übermittelten Personen, die die alle notwendigen Impfdosen erhalten haben." 

I think, there is one "die" (German article) too much. "Anzahl der an das RKI übermittelten Personen, die alle notwendigen Impfdosen erhalten haben." is better to understand.

## Steps to reproduce the issue

1. The app has to use the German localization
2. Go to main page
3. Scroll down to statistics area
4. Click on the information icon (i) in the upper right corner of any statistic tile
5. Scroll down until you can read "Vollständig geimpfte Personen"

## Expected behaviour

Text should be "Anzahl der an das RKI übermittelten Personen, die alle notwendigen Impfdosen erhalten haben."

## Possible Fix

Change Localizable Strings:

iOS: https://github.com/corona-warn-app/cwa-app-ios/blob/5dc34e76d49d1430c840a8afcd5b6272b82fc1e5/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L2075

Android: https://github.com/corona-warn-app/cwa-app-android/blob/63df24be9d2bc1bfb324325d79b1c8b0f8606f4d/Corona-Warn-App/src/main/res/values-de/strings.xml#L1637

P.S. for traceability: I posted this issue first [here](https://github.com/corona-warn-app/cwa-app-ios/issues/3243) but it was suggested that I report this issue here.

/e: Just checked and the issue is still existing in the lastest RCs.

**Comment by MikeMcC399** [comment]
@hija 
The text seems to be fixed already in the next planned version of Android in the [release/2.6.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.6.x) branch.

https://github.com/corona-warn-app/cwa-app-android/blob/fc7c1bd7377a9db04cb50abc06588c1d93400041/Corona-Warn-App/src/main/res/values-de/strings.xml#L1519-L1520

```
    <!-- XTXT: Statistics number of fully vaccinated people text -->
    <string name="statistics_fully_vaccinated_people_text">"Anzahl der an das RKI übermittelten Personen, die alle notwendigen Impfdosen erhalten haben."</string>
```

**Comment by hija** [comment]
Ohhh... Looks like I accidentally changed back to another branch when I searched in the repository for "die die alle".
Thank's for pointing that out, @MikeMcC399. I assumed Android and iOS were using the same Localization strings :)

I just checked again and for iOS it's not fixed in 
* [v2.6.1-RC0](https://github.com/corona-warn-app/cwa-app-ios/blob/v2.6.1-RC0/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L2075)
* [release 2.7.x](https://github.com/corona-warn-app/cwa-app-ios/blob/release/2.7.x/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L2075)
* And not in the current App Store version, since I wouldn't see the mistake otherwise

**Comment by Ein-Tim** [comment]
I'll provide a PR for this, just to make sure this gets fixed under iOS in version 2.6 too.

**Comment by hija** [comment]
Okay, the edit has been merged. Thank you :)

**Comment by dsarkar** [comment]
@hija  Thanks for contributing.
