### ISSUE TITLE
[Business Rules Validation]Denmark Missing in Map of Europe in Information Screen

### ISSUE THREAD

**Issue by vaubaehn** [corona-warn-app/cwa-documentation#673]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug affects both Android **and** iOS ~- not 100% sure, but I strongly assume so.~
* [x] Bug is not already reported in another issue - it was kind of, but maybe not taken too serious yet? 🤷‍♂️ 

## Technical details

- Device name: Should be all
- iOS/Android version: any applicable for CWA
- App version: 2.6.1

## Describe the bug
🇩🇰 is somehow missing in the map of Europe:
![Screenshot_2021-07-29-13-57-00~2](https://user-images.githubusercontent.com/68376758/127501243-249539e2-7318-4be7-a695-4bc588916d54.png)

Eventhough Denmark is member of EU and connected to EU-DGC-Gateway...

## Steps to reproduce the issue

1. Go to 'Certificate Tab'
2. Select certificate
3. Press button 'Check Validity' ("Gültigkeit prüfen")
4. Press (i)
5. See map of Europe in information screen, without 🇩🇰 .

## Expected behaviour

I don't want to fall into the Skagerrak when I pass the border near Flensburg ... 

## Possible Fix

Tell the map creating tool used by the creative artists to include 🇩🇰 .

## Additional context

/cc: @harambasicluka - now official 😉 -> https://github.com/corona-warn-app/cwa-app-android/pull/3753#issuecomment-883527356

## Even more additional context

I didn't check thoroughly if more countries are missing in the map - but at first glance, everything seems to be complete except 🇩🇰

**Comment by jucktnich** [comment]
iOS the same ➜ you can delete the not 100% sure ;)

**Comment by MikeMcC399** [comment]
@jucktnich 
> you can delete the not 100% sure ;)

Perhaps you replied to the wrong issue? There is nothing to delete in this issue.

**Comment by jucktnich** [comment]
@MikeMcC399 he writes:
> Bug affects both Android and iOS - not 100% sure, but I strongly assume so.
I mean he can remove the part, that he's not 100% sure.

**Comment by MikeMcC399** [comment]
@jucktnich 
Thanks for the quotes. Now I understand!

**Comment by vaubaehn** [comment]
@jucktnich @MikeMcC399 

> > Bug affects both Android and iOS - not 100% sure, but I strongly assume so.
> 
> I mean he can remove the part, that he's not 100% sure.

I adapted accordingly 😄

**Comment by vaubaehn** [comment]
@dsarkar Did you already find someone, who you could assign this issue to, and mirror it in jira accordingly? 😉 
It's a funny issue, but should be solved so as not to upset our neighbors ...

**Comment by dsarkar** [comment]
@vaubaehn Yep, that is a funny one. Internal Tracking ID: [EXPOSUREAPP-8828](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8828)

**Comment by dsarkar** [comment]
Apparently, WIP and Denmark will be shown on the map finally! ;-)

**Comment by vaubaehn** [comment]
> Apparently, WIP and Denmark will be shown on the map finally! ;-)

They will be so happy! And my feet will stay dry when heading to north 😉

**Comment by Ein-Tim** [comment]
FYI: iOS PR fixing this: https://github.com/corona-warn-app/cwa-app-ios/pull/4004

**Comment by vaubaehn** [comment]
Already?! 🎉 
And I missed the missing Czech border 😮

**Comment by dsarkar** [comment]
FYI Android PR https://github.com/corona-warn-app/cwa-app-android/pull/4591

**Comment by Ein-Tim** [comment]
Confirm fixed in version 2.16 under iOS: 
<img src="https://user-images.githubusercontent.com/67682506/149986598-80b60837-8c74-4bfc-8a3c-4cd0581e45b6.jpeg" width="300">

**Comment by MikeMcC399** [comment]
The map is also fixed in CWA Android 2.16.2 so this issue can be closed.

**Comment by vaubaehn** [comment]
@MikeMcC399 Thanks for the hint!

🎉 

Closing, as Denmark and Czech Republic are again part of the European continent!
