### ISSUE TITLE
Business Rules - Spain - passes with 1/2 vaccination certificate

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#675]
## Technical details

- Device name: Samsung Galaxy A5 (2017) SM-A520F
- Android version: 8.0.0
- App version: 2.6.1

## Describe the bug

With a 1/2 vaccination certificate (incomplete series) the validity check for Spain passes instead of failing.

https://reopen.europa.eu/en/from-to/DEU/ESP however says:
COVID-19 Vaccination Certificate. Valid 14 days after receiving the **complete** regimen

## Steps to reproduce the issue

1. Scan in 1/2 vaccination certificate
2. CHECK VALIDITY
3. Select Country Spain / Date 1 Aug 2021 12:00
4. Result is "Your certificate is valid in the selected country"
"2 rules of the destination country were reviewed successfully.

## Expected behavior

Since the series is incomplete (1 of 2 doses and the 2nd dose is not documented) the validation should fail.

## Possible Fix

Examine the Spanish business rules.

## Additional context

```
2021-07-30T17:24:59.875Z I/CertLogicEngineWrapper: Rule VR-ES-0002 1.0.0 has resulted in PASSED.
2021-07-30T17:24:59.875Z I/CertLogicEngineWrapper: Rule VR-ES-0003 1.0.0 has resulted in PASSED.
```

**Comment by thomasaugsten** [comment]
I forwarded this finding. The important rule VR-ES-0001 is in the test data but not on the rule gateway.

**Comment by vaubaehn** [comment]
Hi @thomasaugsten (and possibly @carballAcc ?)
could also please have a look at
TR-ES-0003 and
TR-ES-0004:
They're both for validity of sample collection of NAA-Test, but 0003 is "not older than 48 hours" and 0004 is "not older than 72 hours", so rule TR-ES-0004 is obsolete.

Is there a good platform where these issues could be reported?

**Comment by carballAcc** [comment]
Good morning, rule VR-ES-0001 has been restored and TR-ES-004 has been corrected. Thank you all

**Comment by thomasaugsten** [comment]
Thanks @carballAcc  for fixing this issue so fast.

**Comment by vaubaehn** [comment]
@carballAcc
Thanks for your reply!

@thomasaugsten @MikeMcC399 
The updated rules for ES are already in PROD, but will take effect from 05.08.2021 on.
Just in case someone else stumbles over ES...

**Comment by MikeMcC399** [comment]
@vaubaehn 
Thanks for the information about date of introduction of the fix.

@thomasaugsten 
We have usually left issues open until a fix is in production or an app version with the fix has been released, otherwise users tend to open duplicate issues. Also I have no way of verifying the fix at this time, so for me the issue is still open.

**Comment by vaubaehn** [comment]
@MikeMcC399 

> Also I have no way of verifying the fix at this time

I added some interesting information a minute ago:
https://covidapps.slack.com/archives/C0194ML0MLN/p1627991943008300?thread_ts=1627556597.041700&cid=C0194ML0MLN
