### ISSUE TITLE
Assumed country of departure for "Check Validity"?

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#676]
## Your Question

What does the result of "Check Validity" in CWA mean? Is it assuming that the traveller is coming from Germany? Or are the results independent of the Country of Departure?

CWA only gives the choice of Country of Destination. There is no choice about the Country of Departure.

Under "Travel Plan" on the website https://reopen.europa.eu/en (and app Re-open EU) there is a choice for:
- Country of departure
- Country of destination

Maybe this should be an enhancement request to add the choice of "Country of departure" to CWA?

**Comment by vaubaehn** [comment]
Hi @MikeMcC399 ,
as far as I understand the process, CWA checks the stored certificates against the business rules of other  countries. So, implicitly the country of departure is determined by the country in which you took your certificate.
E.g., if you took a vaccination in Spain,  the CoD will be Spain, no matter whether you travel from Germany or a different country.

**Comment by MikeMcC399** [comment]
@vaubaehn 
> there may be special restrictions for several countries in the country of arrival (like arriving from a virus variant country), and this is not taken into account when checking the certificate. Maybe this should be pointed out better in CWA's explaining texts?

Although the function called is "CHECK VALIDITY" I thought that the app would check for other restrictions like you mention. It looks like it really only checks the certificates and it does not cover other points at all.

The headline, if the check is successful, says "A COVID certificate is valid proof for travel within the EU." It could be though that additional tests or quarantine are necessary on arrival, and the text is very general about this point. It just says "Additional rules and restrictions may apply in individual regions."

I think that the text should be made more explicit. Something like:

You are strongly advised to check https://reopen.europe.eu/en for additional restrictions.

That is if the app is unable to display those additional points.

**Comment by dsarkar** [comment]
@vaubaehn  @MikeMcC399 I have been asking internally: It is not implemented in the business rules to check from which country you depart. I.e. if you travel from country A to country B, the validity of a certificate determined by the business rules is independent of country A. Therefore, with the current scheme it cannot be mapped if you come from a high incidence or virus mutation region, for example.

**Comment by MikeMcC399** [comment]
@dsarkar 
Thanks for answering the question!

I will close this issue now.
