### ISSUE TITLE
Luca QR codes Not valid

### ISSUE THREAD

**Issue by dherrman1** [corona-warn-app/cwa-documentation#677]
Hi there,

Until now ist is Not possible to  use the check-in function with a Luca based QR code.
Is this a bug (most likely not, as i can not any documentation), or is there a plan to get this feature working?

BR 
Detlef

**Comment by MikeMcC399** [comment]
@dherrman1 

I suggest you follow the progress of the issue https://github.com/corona-warn-app/cwa-documentation/issues/590 "Link structure for other contact tracing apps" which discusses the Luca app.

**Comment by dsarkar** [comment]
@dherrman1 Thanks for the question. This is also discussed, as @MikeMcC399 already mentioned, in #590. We suggest therefore to continue discussion there and close this issue.

**Comment by dherrman1** [comment]
Thanks MikeMcC299.

**Comment by dherrman1** [comment]
Closed, Issue is described in #590

**Comment by dsarkar** [comment]
@dherrman1 FYI https://www.coronawarn.app/de/faq/#check_in_luca
