### ISSUE TITLE
Android needs to be based on Reference Design

### ISSUE THREAD

**Issue by quaddy-services** [corona-warn-app/cwa-documentation#68]
To avoid not wanted / not working code fragments the Android App should base on

"Exposure Notifications API: Android Reference Design"

which can be found here:
https://github.com/google/exposure-notifications-android

**Comment by tkowark** [comment]
Rest assured that the Android app team is monitoring these repos closely. But please bear with us a couple more days until the source code will be made available (and continued to be developed on Github) to check for any issues directly in the code.
