### ISSUE TITLE
Question on free of charge corona tests after 11 October 2021 if CWA shows a high risk warning

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#684]
## Your Question
The federal government decided to stop the provision of free public testing with effect from 11 October 2021 ([Source](https://www.bundesregierung.de/resource/blob/656632/1950174/93e22e944e165b106f56406b3de0dfa9/2021-08-10-mpk-beschluss-corona-en-data.pdf?download=1)).
Now the question rises what happens if the Corona-Warn-App shows a high risk encounter (red tile). Will the user have to pay for the corona test himself or will this still be free of charge? 
I know this might not be the best place to ask, but maybe this issue finds his way to the RKI and from there to the BMG? 

## Additional information
This issue is based on a question from a Twitter user: https://twitter.com/SocialMarketEco/status/1425737498425233415?s=20

**Comment by vaubaehn** [comment]
@Ein-Tim 
> I know this might not be the best place to ask

I think 'here' is a rather good place to ask, because many people may have that question in mind, and it would be good to validate or adapt CWA in-app information as well as FAQ.
