### ISSUE TITLE
Is there a Wallet function for negative Antigen tests of children?

### ISSUE THREAD

**Issue by Belboz64** [corona-warn-app/cwa-documentation#685]
Hi,

this is  possibly just a documentation issue, or maybe the functionality is actually missing, I do not know.

Example Use Case:
- Family XYZ wants to go to Italy. 
- 3 children above 6, which are not vaccinated.
- Italy requires EU Digital COVID Certificates for all 3 children, so all 3 children undergo Antigen testing 1 day before departure. 
- Family XYZ has only 1 mobile.

What now? From the documentation it appears you can only register 1 Antigen test result, but familiy X needs to be able to show 3 test results at the border if asked.

The only workaround I can think of (and which we actually use) is to use one mobile per child and install the CWA on 3 different mobiles.

Is there any other way?

Thanks!

**Comment by jucktnich** [comment]
You can import certificates of multiple persons into the CWA since version 2.5

**Comment by Ein-Tim** [comment]
To answer your question:

No, there is no wallet function to store more than one PCR & rapid antigen test at the same time.

The workaround in the above mentioned example would probably be:
1. Register the first test and create the EU digital COVID certificate from it
2. Remove the first test - the EU digital COVID certificate will stay in the app
3. Register the second test and create the EU digital COVID certificate from it
4. Remove the second test - the EU digital COVID certificate will stay in the app
5. Register the third test and create the EU digital COVID certificate from it

**Comment by Ein-Tim** [comment]
Related issue:

https://github.com/corona-warn-app/cwa-wishlist/issues/109

**Comment by MikeMcC399** [comment]
@Belboz64 
Here are the links to the documentation:

https://www.coronawarn.app/en/faq/#rat_multiple_rat says:
Can I save/manage multiple rapid antigen tests?
No, only one rapid test can be registered in the app at a time.

https://www.coronawarn.app/en/blog/2021-07-12-cwa-version-2-5/

"Deutsche Telekom and SAP’s project team have released version 2.5 of the Corona-Warn-App, in which users who have recovered from COVID-19 can integrate a digital certificate that serves as official proof for their recovery. Whether vaccinated, recovered, or tested, users can now manage all types of certificates in one place in their Corona-Warn-App. Users can manage certificates both for themselves and for others, such as children."

---

We should probably take a look at improving the FAQs for this case. Thanks for bringing it up.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Do you want to take care of this reg. the FAQs? If not I can do this, you've done quite much in the last days (-:

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> Do you want to take care of this reg. the FAQs? If not I can do this, you've done quite much in the last days (-:

I will submit an website issue for this. I will not have much time next week, so you are welcome to submit a PR to resolve. It may need some input from the Open Source Team in addition.

**Comment by Belboz64** [comment]
@Ein-Tim

That seems to be answer, thanks a lot!

> However, as @jucktnich said, if you can get the EU digital COVID certificates from another place and not only through the app, you can register all certificates in the "Certificates" tab of the app.

Well, it appears there is no other way, which (IMHO) is actually a bit strange. E. g. I can visit a pharmacy, present my vacccination book and get a piece of paper with the EU Certificate, which I then can import into CovPass and CWA (or I can just use the printout if I have no mobile). Very easy. However if I visit the very same pharmacy and get tested, I have to jump through multiple hoops to get the EU Certificate.

**Comment by Ein-Tim** [comment]
> Well, it appears there is no other way, which (IMHO) is actually a bit strange. E. g. I can visit a pharmacy, present my vacccination book and get a piece of paper with the EU Certificate, which I then can import into CovPass and CWA (or I can just use the printout if I have no mobile). Very easy. However if I visit the very same pharmacy and get tested, I have to jump through multiple hoops to get the EU Certificate.

Mh, I'd say that's not that strange since the pharmacy can save work that way. They are "outsourcing" the certificate creation process.

**Comment by Ein-Tim** [comment]
Has your question been answered @Belboz64? If yes, please close this issue.

**Comment by Belboz64** [comment]
Thanks!
