### ISSUE TITLE
Certificate exams...

### ISSUE THREAD

**Issue by Jo-Achim** [corona-warn-app/cwa-documentation#686]
Hi, everyone,

I would definitely like to refer to an article in c't 18/2021, page 32 (08/14/2021) with the title "Big Tohuwabohu", in which, among other things, the certificate examination in the CWA is addressed.

I think that should be responded to! Be it, if correct, with corresponding changes in the CWA or otherwise in relation to the c't editorial team.

Cross reference: [Diskussion über öffentliche Wahrnehmung der App | Discussion about public perception of the app](https://github.com/corona-warn-app/cwa-wishlist/issues/352#issue-797677685).

PS: If the above c't content is already subject of other topics, please give us a hint.

**Comment by MikeMcC399** [comment]
@Jo-Achim 

I don't have an Abo for c't and the article https://www.heise.de/select/ct/2021/18/2121113553886728854  is not completely shown. It starts with:

"Großes Tohuwabohu

Wie Methoden auf Siebtklässlerniveau den digitalen Impfnachweis ausbremsten
Über eine Woche lang konnten deutsche Apotheken keine digitalen Impfnachweise ausstellen, mitten in der Urlaubssaison. Auslöser war die Enthüllung von Sicherheitsforschern, die zeigten, wie leichtsinnig der Apothekerverband DAV mit Zugangsanträgen umging. Inzwischen steht ein neues Portal bereit – mit neuen Problemen."

Maybe the article is based on what is written in https://www.heise.de/news/Digitale-Corona-Impfzertifikate-Was-bisher-falsch-lief-6156971.html?

**Comment by Jo-Achim** [comment]
@MikeMcC399,

yes, roughly and quickly, the contents of the articles are identical.

The article I mentioned (c't 18/2021) also mentions the known problems with the 'certificate examination' with regard to entry rules, etc.
I think it would be useful to read this article as well; innovations that are to come with CWA 2.7 cannot be read here.

However, it is also pointed out here: "In addition to the comparison with the photo ID, the verification of a digital certificate also includes a validity check by a qualified authority such as CovPass Check." ("Zur Verifikation eines digitalen Zertifikates gehört neben dem Abgleich mit einem Lichtbildausweis zwingend die Gültigkeitskontrolle durch eine qualifizierte Instanz wie CovPass Check.") So far so good.
Nevertheless, it seems to me - also with regard to the similar QR code representations (keyword: 'blue background') - that a corresponding clarification or separation of 'CWA' and 'CovPass' / 'CovPass Check' may be necessary. Because this no longer seems to be recognizable for every CWA user. In other words: many CWA users will have the impression that the CWA is sufficient as proof of vaccination (instead of CovPass).
The tenor of the article should reinforce this impression!?

So it seems to me that an expert should look at this... 

In this sense, Joachim.

**Comment by Jo-Achim** [comment]
**Update:**
With reference to the article I mentioned above in c't 18/2021, a negative point mentioned there (Abschnitt "Fake-Zertifikate für jeden" / section "Fake certificates for everyone") seems to have been dealt with the publication of CWA 2.7; see: [Corona-Warn-App Version 2.7 zeigt technisches Ablaufdatum an und prüft Zertifikate automatisch auf Echtheit](https://www.coronawarn.app/de/blog/2021-08-16-cwa-version-2-7/) or [Corona-Warn-App Version 2.7 shows technical expiration date and automatically checks certificates for authenticity](https://www.coronawarn.app/en/blog/2021-08-16-cwa-version-2-7/).

**Comment by Ein-Tim** [comment]
@Jo-Achim 

Can this issue be closed?

**Comment by Jo-Achim** [comment]
Thanks @Ein-Tim. Closed.
