### ISSUE TITLE
Risk assessment description not up to date

### ISSUE THREAD

**Issue by OlympianRevolution** [corona-warn-app/cwa-documentation#687]
## Where to find the issue
https://github.com/corona-warn-app/cwa-documentation/blob/bbf59fa9d9256e44b8134970f91e92cc0c8c02a9/cwa-risk-assessment.md

## Describe the issue
The numbers presented here are no longer up to date. I think both dB and time thresholds as well as computation methods have changed

## Suggested change
Align information to reality. IE 9 minutes not 15 and I think also the dB values have changed

**Comment by OlympianRevolution** [comment]
The md file no longer matches the drawing at https://github.com/corona-warn-app/cwa-documentation/blob/master/images/risk_calculation/risk_calculation_enf_v2_overview.pdf

**Comment by MikeMcC399** [comment]
@OlympianRevolution 
There is a long-standing issue (around 10 months old) regarding the risk assessments documents not being maintained.

See https://github.com/corona-warn-app/cwa-documentation/issues/453.

**Comment by OlympianRevolution** [comment]
Duplicate with #453
