### ISSUE TITLE
Add missing stakeholders

### ISSUE THREAD

**Issue by sventuerpe** [corona-warn-app/cwa-documentation#69]
## What is missing

Add the following stakeholders:

- Local health authorities
- Coronavirus test centers
- Responsible system operator

## Why should it be included

Important requirements originating from these stakeholders need to be considered. 

- Local health authorities are responsible for contact tracing, quarantine orders, and follow-up actions. For automated contact tracing to be as effective as possible, their efforts need to be integrated with whatever CWA does. Their needs are apparently being ignored so far. Local health authorities also likely play a role in the handling of test results, supervision of testing and general pandemic management. 
- Coronavirus test centers need to enter test results into the system so that app users can be notified about their results. The current scoping document covers only the output side but gives not the slightest hint how test results get into the system in the first place. There are very likely specific requirements pertinent to the input side such as identity and access management, integration with existing processes and systems, and so on.
- The whole system will have a responsible operator in one way or the other. This operator, in their own right or on behalf of, e.g., the RKI needs to monitor the operation of the system, identify problems and detect abuse, report metrics such as false alarm rates and compliance rates after notification, etc. 
 
## Where should it be included

This information belongs in the scoping document, later in the backlog.

**Comment by jarjarbentley** [comment]
We appreciate this suggestion and will be in touch early next week with more comments. Best regards,
JB
Your Corona Warn-App Open Source Team

**Comment by sventuerpe** [comment]
@jarjarbentley No need to hurry. Enjoy your weekend, I am sure you deserve it.

**Comment by christianbrb** [comment]
@sventuerpe 😊👍🏻

I would call them users instead of stakeholders.

**Comment by aeisenbach** [comment]
Hi @sventuerpe, thank you for this suggestion. We already drafted additional user stories from these perspectives and will add them to the documentation in the next days. BR, Andreas

**Comment by jensmuehlner** [comment]
As @aeisenbach from the Scoping-Team confirmed, they will add additional user stories to the documentation in the next days, taking yours into account. Therefore we might close this issue and look at it again after the document is updated, ok?
