### ISSUE TITLE
Event Registration: Are symptoms taken into account?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#690]
## Your Question
Are the onset of symptoms (CWA 1.5) took into account if a user is warned because of an event they visited? 

https://www.coronawarn.app/en/faq/#check_in_qr_warning says in "What is the procedure in case of a positive result?
Does everyone who scanned the same Event QR code get a warning?
What exactly needs to happen in this new feature for users who have checked into a specific location to be warned through the app?": "[…] Depending on the epidemiological situation, the warning is displayed in one of two versions: 'low risk' (green tile) or 'high risk' (red tile)."
 
In the paragraph afterwards: "How is the risk determined?
When do I receive a low-risk warning (green tile), when do I receive a high-risk warning (red tile)?"  it is said: "The calculation of the risk depends on whether and for how long a user's attendance overlaps with the attendance of a person who later tested positive about (sic!) COVID-19."

Now the question is: The "epidemiological situation" mentioned in the first paragraph, is this only the duration of the contact or also the onset of symptoms?

**Comment by mlenkeit** [comment]
@Ein-Tim we derive _Transmission Risk Level_ (TRL; i.e. the infectiousness) based on the symptom information provided by the user when warning others. The TRL is attached to both diagnosis keys and event check-in warnings and also considered by both parts of the risk calculation.

**Comment by Ein-Tim** [comment]
@mlenkeit 

Okay, so in praxis it means that if (for example) I was checked in to an event for half an hour with a later positive person, but according to the symptoms that the user entered when sharing their positive test result, they were not yet infectious, I won't get a warning?

**Comment by mlenkeit** [comment]
@Ein-Tim each selection on the UI is represented by a different TRL matrix. If that other person selected _No symptoms_, it's mapped to `[4, 4, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]` (left most TRL set to the Diagnosis Keys of today). In the end, both TRL and the overlap (plus some time buffer to take aerosole decay into consideration) are fed to the risk calculation.

**Comment by Ein-Tim** [comment]
@mlenkeit 

Okay, thanks, I understand. 

Closing as answered.
