### ISSUE TITLE
Outdated documentation: Check all documentation, mark outdated documentation as outdated and start updating it

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#694]
## Where to find the issue

| Documentation description | Link | Outdated (my POV)? |
|---|---|---|
| **Documentation Repository** | | |
| Fraunhofer IIS - API testing | https://github.com/corona-warn-app/cwa-documentation/blob/master/2020_06_24_Corona_API_measurements.pdf | **Yes** - Fraunhofer did more testing |
| Backend Infrastructure Architecture documentation - Markdown file | https://github.com/corona-warn-app/cwa-documentation/blob/master/backend-infrastructure-architecture.md | **No** |
| Backend Infrastructure Architecture documentation - PDF | https://github.com/corona-warn-app/cwa-documentation/blob/master/backend-infrastructure-architecture.pdf| **Yes** - New features were added to the app which require a server (e.g. DCC retrieval) |
| How does the Corona-Warn-App identify an increased risk? | https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md| **Yes** - see #453 |
| Versioning | https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-versioning.md | **No** |
| Event Registration documentation | https://github.com/corona-warn-app/cwa-documentation/blob/master/event_registration.md| **No** - Not at the moment, has to be updated once on behalf warning has been released |
| Glossary | https://github.com/corona-warn-app/cwa-documentation/blob/master/glossary.md | **Yes** - Terms are missing (e.g. ENF/ENS, DCC, RAT, etc.) |
| Security Overview | https://github.com/corona-warn-app/cwa-documentation/blob/master/overview-security.md| I'd say **Yes** - the document [says](https://github.com/corona-warn-app/cwa-documentation/blame/master/overview-security.md#L15) "[…] will be updated regularly.", however, there was no update to this document for over a year now |
| Scoping document | https://github.com/corona-warn-app/cwa-documentation/blob/master/scoping_document.md| I'm not sure about this document |
| Solution architecture | https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md| **Yes** - The document [says](https://github.com/corona-warn-app/cwa-documentation/blame/master/solution_architecture.md#L7) that "[…] further technical details on the individual components, the security concept, and the data protection concept are provided at a later date." however, these details were never provided since 15 months. |
| Transmission Risk - R Markdown file | https://github.com/corona-warn-app/cwa-documentation/blob/master/transmission_risk.Rmd| I don't feel qualified enough to make any statement about this document|
| Transmission Risk - PDF | https://github.com/corona-warn-app/cwa-documentation/blob/master/transmission_risk.pdf| I don't feel qualified enough to make any statement about this document |
| Transmission Risk - BIB file | https://github.com/corona-warn-app/cwa-documentation/blob/master/transmission_risk_references.bib| I don't feel qualified enough to make any statement about this document |
| Screenshots of the UI | https://github.com/corona-warn-app/cwa-documentation/blob/master/ui_screens.md| **Yes** - Was already marked as outdated |

## Describe the issue

Many documentation documents are (partly) outdated and have to be updated!

## Suggested change

1. Mark outdated documentation as outdated
2. Begin updating the documentation

## Additional information

For some documents, I was not sure about whether they are outdated or not. I'm happy to hear feedback from more qualified community members about the status of these documents!

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Many of the links in this document are incorrect and cause a 404 error e.g. 
`https://github.com/corona-warn-app/cwa-documentation/blob/master/backend-infrastructure-architecture.pdf%C2%A0`

It looks like you have some hex figures at the end of the links.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I can reproduce this issue! It seems like this is a GitHub issue, when viewing the links in editor mode, everything is correct: 
![Bildschirmfoto 2022-01-25 um 18 30 04](https://user-images.githubusercontent.com/67682506/151028341-bebb84ff-bc03-4c47-9c18-ba8710011a4e.png)

**Comment by MikeMcC399** [comment]
@Ein-Tim 

The character `%C2%A0` is a `nbsp`.

Try deleting the spaces after each link and re-adding them. It may be a copy & paste issue.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Fixed, thanks!

**Comment by Ein-Tim** [comment]
I added the list of the OP to https://github.com/corona-warn-app/cwa-documentation/issues/667#issuecomment-1101365050. Closing this issue in favour of #667.
