### ISSUE TITLE
App is missing the "Erklärung zur Barrierefreiheit" which is mandatory in apps from public authorities since 23. June 2021

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#697]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Not important
- iOS/Android version: Not important
- App version: 2.7.1

## Describe the bug

A Twitter user made me aware of the fact that CWA is missing the "Erklärung zur Barrierefreiheit" which has to be included in apps published from public authorities (like the RKI) since 23. June 2021. 
This is a requirement based on the „Behindertengleichstellungsgesetz“ (BGG) (§ 12b Abs. 3) and the „Barrierefreie-Informationstechnik-Verordnung“ (BITV).
Looking at the SafeVac-App from the PEI, I can see that they have have this "Erklärung zur Barrierefreiheit" in their app. 

## Steps to reproduce the issue

Search the app for the "Erklärung zur Barrierefreiheit", you won't find one.

## Expected behaviour

To make sure the app is compliant with current laws, I suggest to include this "Erklärung zur Barrierefreiheit" in the app as soon as possible.

## Possible Fix

Add the "Erklärung zur Barrierefreiheit".

## Additional context

Please let me know if this might not affect CWA for what reason whatsoever. 

---
Internal Tracking ID: [EXPOSUREAPP-11129](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11129) obsolete
Internal Tracking ID: [EXPOSUREAPP-11968](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11968) Android
Internal Tracking ID: [EXPOSUREAPP-11986](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11986) iOS

**Comment by Ein-Tim** [comment]
@dsarkar Could we maybe get this mirrored to JIRA?

**Comment by rugk** [comment]
Still no mirror and some months old. Compliance anyone?

**Comment by Ein-Tim** [comment]
Cc @dsarkar & @larswmh 

This could be from interest for the legal department.

**Comment by larswmh** [comment]
Hi @Ein-Tim, thanks for your report. We have created an internal ticket and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-11129](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11129)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
PR iOS: https://github.com/corona-warn-app/cwa-app-ios/pull/4270

**Comment by Ein-Tim** [comment]
PR Android: https://github.com/corona-warn-app/cwa-app-android/pull/4880

**Comment by Ein-Tim** [comment]
@dsarkar Can you apply the `Fix 2.19` label here?

**Comment by MikeMcC399** [comment]
There is now an "Accessibility Statement by the Robert Koch Institute and the Federal Ministry of Health" published to 

- https://www.coronawarn.app/en/accessibility/#android
- https://www.coronawarn.app/en/accessibility/#ios
- https://www.coronawarn.app/de/accessibility/#android
- https://www.coronawarn.app/de/accessibility/#ios

in English / German and for Android / iOS respectively.

**Comment by Ein-Tim** [comment]
Thank you @MikeMcC399!

I'll leave this issue open until version 2.19 is released.

**Comment by Ein-Tim** [comment]
I can confirm that the iOS version 2.19.0 of CWA includes a link to the "Barrierefreiheitserklärung".


As soon as I get the update under Android, I'll check there and report back here.

**Comment by Ein-Tim** [comment]
I can confirm that the Android version 2.19.0 of CWA includes a link to the "Barrierefreiheitserklärung".

I am closing this issue as fixed in version 2.19.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Would you mind giving your opinion if the German text on https://www.coronawarn.app/de/accessibility/ is correct grammar?

"Diese Erklärung zur Barrierefreiheit gilt für Version 2.17 der Corona-Warn-App (Android) des Robert Koch-Instituts und Bundesministerium für Gesundheit."

or should it be

"... des Robert Koch-Instituts und Bundesministeriums für Gesundheit." or
"... des Robert Koch-Instituts und des Bundesministeriums für Gesundheit."

per https://www.duden.de/deklination/substantive/Ministerium.

Sorry if this is slightly off-topic. I would open a new issue if you think this needs to be corrected.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

> Would you mind giving your opinion if the German text on https://www.coronawarn.app/de/accessibility/ is correct grammar?

For sure!

> "... des Robert Koch-Instituts und des Bundesministeriums für Gesundheit."

I think this is what sounds best! The first one without "des" before "Bundesgesundheitsministeriums" would also be possible, if I'm not mistake, but it does not sound as good as the second one.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Thank you for your advice (as you know, I am not a native German speaker). I will put the second alternative straight into a new PR.
