### ISSUE TITLE
Add user story: Proof of notification

### ISSUE THREAD

**Issue by sventuerpe** [corona-warn-app/cwa-documentation#70]
## What is missing

Add the following user story to the scoping document and the backlog:

As an at-risk user of the CWA I want to obtain a proof that the app has warned me so that I have a valid excuse for missed obligations such as showing up for work or complying with summons by courts or authorities.

## Why should it be included

After having received a notification from the app that they had contact with an infected person, users of the app are supposed to self-isolate immediately and voluntarily. High compliance rates are required for the app to be successful. It is therefore necessary to remove any obstacles that might prevent users from complying with recommendations. Conflicting obligations can become a strong motivation for non-compliance.

As an alternative, one could pass a regulation that allows anyone to claim self-isolation without proof. This would, however, be rather easy to abuse in a variety of ways. 

## Where should it be included

Scoping document and backlog

**Comment by MalteJ** [comment]
As soon as you have brought this through Bundestag and Bundesrat we are happy to add a user story for this 🙂 
The scoping documentation is meant as an immediate requirements catalog for the app. We cannot add such a feature which has no legal backing.

Malte

**Comment by sventuerpe** [comment]
Wait a second, I am the one missing a legal backing. What will happen when the app warns me to self-isolate and I have conflicting obligations? Even if this is to be decided elsewhere and not within the development team, I would appreciate such issues to be documented and brought to the attention of whoever is responsible for resolving them. Do you have a channel that can be used to this end? If not, what else do you propose?

**Comment by fealXX** [comment]
> What will happen when the app warns me to self-isolate and I have conflicting obligations?
Talk to a medical professional and/or your local Gesundheitsamt.

**Comment by MalteJ** [comment]
Engage in a public discussion or contact your Abgeordneter. But please do not discuss this here on GitHub - this is for development only 🙂 
And yes, calling your Gesundheitsamt as soon as you know you are infected is a good idea ;)
By the way, the app is not the only channel that is used to provide your test result. The Gesundheitsamt will be informed also, but they will react a little bit slower. So if you get an alert in the app you can be sure that your Gesundheitsamt will also get the info that you are infected.

**Comment by sventuerpe** [comment]
I was thinking of notified contacts, not recipients of test results. 

I understand that once the CWA is available I can at any time contact a doctor or health authority, claim without any proof to have received a notification from the app about recent contact with an unidentified infected person, and obtain paperwork that allows me to stay at home until my own test result arrives regardless of any obligation that I may otherwise have. 

(a) Is this correct?
(b) How much time does usually pass from visiting a test center until the result is available?

**Comment by MalteJ** [comment]
a) I don't see a legal basis for that at the moment.
b) about 2-3 days

**Comment by sventuerpe** [comment]
@MalteJ Sleep it over. We do not have to resolve this tonight.

**Comment by sventuerpe** [comment]
@fealXX 

1. How does a doctor or health authority distinguish true (according to recorded information) exposed persons from those calling for other motives? Will there be a case ID or something? 
2. How many dishonest callers reporting as exposed would it take to overload health authorities?

**Comment by sventuerpe** [comment]
Let me add some background information and feel free to correct me if CWA is based on different assumptions.

According to [this reporting](https://www.swr.de/swraktuell/rheinland-pfalz/infektionsketten-rp-100.html) by public TV station, SWR, on current contact tracing practice:

- An exposed person has to go into quarantine for two weeks („Das bedeutet, dass sie zwei Wochen das Haus nicht verlassen dürfen, auch nicht zum einkaufen. Kinder dürfen während dieser Zeit nicht in die Schule oder in die Kita.“).
- Exposed persons are _not_ usually tested unless they develop symptoms („Automatisch getestet wird man als Kontaktperson nicht.“) so they have no way to shorten their quarantine.
- Health authorities stay in touch with and monitor each person sent into quarantine („Ab Beginn der Quarantäne werden die Kontaktpersonen alle zwei bis drei Tage vom Gesundheitsamt kontaktiert.“)
- A person forced to pull out of their normal life for two weeks needs documentation, which they receive from the health authority under the current contact tracing regime („Für den Arbeitgeber wird die Quarantäne attestiert.“)

I understand CWA aims to amend this established system with a kind of self-service mode and I understand this to be the principal purpose of the whole system.

I am missing a clear, comprehensive and thought-out explanation of what is going to happen after an exposed person has been notified through their app instance and how the needs of this person as well as those of the health authorities are met in various cases. Thus far I see a lot of handwaving instead.

**Comment by akuckartz** [comment]
> Exposed persons are not usually tested unless they develop symptoms

... which is a problem but can not be solved by tracing apps.

**Comment by MalteJ** [comment]
RKI and/or BMG will provide guidance to the infected user via the app. They will provide texts for this.
