### ISSUE TITLE
more certificate import possibilities 

### ISSUE THREAD

**Issue by Trendmaker** [corona-warn-app/cwa-documentation#700]
Hi,

unfortunately my rear camera is not able to focus any more. In the app i cannot switch to the front camera. Would it be possible to implement a import function for the digital certificate with just using the file? You load the certificate on your smartphone and then you can import it locally without camera?

Thanks in advance 
Dennis

**Comment by Ein-Tim** [comment]
Hi @Trendmaker 👋

We already have an issue for this suggestion, it is: https://github.com/corona-warn-app/cwa-wishlist/issues/389.
Currently the `Fix 2.11` label is applied to this issue, so there is a chance that we will see this feature with version 2.11. 

I would suggest you close this issue and monitor https://github.com/corona-warn-app/cwa-wishlist/issues/389 for any updates on this.

Thanks and have a nice weekend.

**Comment by Trendmaker** [comment]
Iam sorry didn't found that before. 

Thanks!!!
