### ISSUE TITLE
Validity check not respecting §2 Absatz 3 Buchstabe b SchAusnahmV (Single vaccination after positive test)

### ISSUE THREAD

**Issue by fdellwing** [corona-warn-app/cwa-documentation#704]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Motorola One
- Android version: 10
- App version: 2.7.1

## Describe the bug

As of §2 Absatz 3 Buchstabe b SchAusnahmV a person that was previously tested positive and got a single vaccination shot, is considered fully vaccinated from the day of the shot. Currently the CWA does not respect this and shows that the certificate is valid in 14 days. It also says this if you check the validity for Germany:

![IMG-20210826-WA0003](https://user-images.githubusercontent.com/22813377/130977020-b3f7de77-1401-4d34-8a9e-9c247cccbe1e.jpg)

## Additional context

https://www.gesetze-im-internet.de/schausnahmv/__2.html

---
Internal Tracking ID: [EXPOSUREAPP-9344](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9344)

**Comment by Ein-Tim** [comment]
Just to be sure (because a Twitter user asked): Will such an certificate show as valid when scanned with CovPassCheck?

**Comment by Ein-Tim** [comment]
Just to make sure (because a Twitter user asked): Will such a certificate be shown as valid in CovPassCheck? No, or @mlenkeit?

**Comment by mlenkeit** [comment]
@Ein-Tim  it should, once the rule is active. After all, CovPassCheck uses the same business rules to check the vaccination certificate as CWA.

**Comment by mlenkeit** [comment]
Btw, the updated business rule `VR-DE-0003` is now in production with `ValidFrom: '2021-10-03T00:00:00Z'`

**Comment by fdellwing** [comment]
Thanks a lot for your awesome work :)

**Comment by Ein-Tim** [comment]
@fdellwing 

I guess you can't confirm that this has been fixed since regardless of this change your certificate is valid now as more than 14 days have passed since your vaccination.

However, a Twitter user confirmed that this has been fixed: https://twitter.com/surfguard/status/1444587448361799680?s=21

Would you like to close this issue? 

Have a nice Sunday!

**Comment by fdellwing** [comment]
Alright, gonna close this then :)

**Comment by dsarkar** [comment]
Dear @fdellwing @Ein-Tim and community, thanks for reporting and contributing here. Best, DS 

---
Corona-Warn-App Open Source Team
