### ISSUE TITLE
Certificate validation translation error for no Business Rules

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#705]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS. For specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue
First seen in https://github.com/corona-warn-app/cwa-app-android/issues/4053.

## Technical details

- Device name: Samsung Galaxy A5 (2017) SM-A520F
- Android version: 8.0.0
- First reported on App version: 2.9.0
- Verified not yet fixed on App version: 2.17.2

## Describe the bug

The text "Entering <Country> on <date/time>, validated on <date/time>" is used even when the check of a certificate against the Business Rules of a country fails.

According to https://dictionary.cambridge.org/dictionary/english/validate, validate means
"to make something officially acceptable or approved, especially after examining it"

If the check fails, then the certificates weren't validated, they were only checked or examined. Validate can only be used if the checks succeed.

Also it is contradictory to say in one line
"Entering <Country> on <date/time>, **validated** on <date/time>"
followed by
"Your certificate **could not be validated**"

"Validated" and "... could not be validated" are mutually exclusive states.

## Steps to reproduce the issue

Edit: Updated for UI change in 2.12.x release.

1. Set locale to English (United States)
2. Tap "Certificates" tab, tap "Scan" button in lower navigation bar and scan in any EU digital COVID CERTIFICATE
3. Tap "CHECK VALIDITY FOR TRAVEL"
4. Select a country which is known not to provide Business Rules yet e.g. Italy
5. Accept the default Date and time, tap "CHECK"
6. Note the contradictory texts:<br>"Entering Italy on <date/time>, validated on <date/time>"<br>"Your certificate could not be validated".

![image](https://user-images.githubusercontent.com/66998419/132953806-2903cf34-4249-48d4-8b7e-deb39d93f9be.png)

## Expected behavior

The English text resulting from a certificate validity check should not say that entry was validated if the result of the check was invalid.

## Possible Fix

For Android, in [covid_certificate_strings.xml](https://github.com/corona-warn-app/cwa-app-android/blob/main/Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml) "validation_rules_result_valid_result_country_and_time"

<string name="validation_rules_result_valid_result_country_and_time">"Entering %1$s on %2$s, validated on %3$s"</string>

change the verb from "validated" to "examined" or another word which does not imply a successful result of a check.

For iOS, change equivalent string.

---
Internal Tracking ID: [EXPOSUREAPP-10059](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10059)

**Comment by ale5000-git** [comment]
Rules for Italy are here: https://get.dgc.gov.it/v1/dgc/settings

**Comment by MikeMcC399** [comment]
@ale5000-git 
> Rules for Italy are here: https://get.dgc.gov.it/v1/dgc/settings

Thanks for the information! Currently there are no rules for Italy used by Corona-Warn-App. If they do become available to the app, then I will have to update my repro steps, because Italy was just being used as an example here to demonstrate an English translation problem.

**Comment by dsarkar** [comment]
@MikeMcC399 The word had been changed from "validated" to "verified".

**Comment by MikeMcC399** [comment]
@dsarkar 

>  The word had been changed from "validated" to "verified".

I see the changed word in CWA Android 2.15.1. "Verified" however means the same as "validated", so I don't believe the issue is resolved.

https://dictionary.cambridge.org/dictionary/english/verify

"to prove that something exists or is true, or to make certain that something is correct:"

I had suggested "examined". Other synonyms which do not imply a successful outcome would be "checked", "inspected" or "reviewed". These would fit into the message:

"Entering Italy on <date/time>, examined on <date/time>"
"Entering Italy on <date/time>, checked on <date/time>"
"Entering Italy on <date/time>, inspected on <date/time>"
"Entering Italy on <date/time>, reviewed on <date/time>"

**Comment by dsarkar** [comment]
@MikeMcC399 

This issue was discussed internally with  English translator:  "verify" is not considered as an  issue as it says "to prove that something exists or is true, or to make certain that something is correct:".

E.g. from New York City app:
![image](https://user-images.githubusercontent.com/1409741/153923237-6e034427-2dd9-49cf-b681-524ef9d03fff.png)

(see https://apps.apple.com/us/app/nyc-covid-safe/id1565213506)
They use "verify" in regards of vaccination.

**Comment by dsarkar** [comment]
@MikeMcC399 OK, I see. I will forward it.

**Comment by MikeMcC399** [comment]
@dsarkar 

> OK, I see. I will forward it.

Thank you! It is a minor point, so if it requires too much effort to sort it out, then please feel free to drop it.

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399 I understand the issue, however, the internal ticket has been closed. I think, as @MikeMcC399 suggests, we can drop this one, it is a minor thing. Changing wording inside the app, will take some effort, not only in the code, but also approval from the stakeholders. So I would suggest closing this one as a minor issue. Thanks!

**Comment by MikeMcC399** [comment]
Closing.

Minor unresolved issue.

@dsarkar 
Thanks for following up.
