### ISSUE TITLE
Is the development team aware of disappearing certificates after updates?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#706]
## Your Question
On Twitter, one iOS and one Android user complaint that their certificates disappeared after the update to version 2.9: https://twitter.com/HashtagGrump/status/1436742751966699521?s=20 & https://twitter.com/GerdKurschner/status/1436282626243973135?s=20

Is the development team aware of this bug? Are they investigating on the root cause?

**Comment by thomasaugsten** [comment]
We aware of this situation the user shall write an email to 
corona-warn-app.opensource@sap.com 
With details of the used device and a screenshot of the empty certificate tab if tab is still present.

**Comment by Ein-Tim** [comment]
@thomasaugsten Okay thanks for the answer, I will transfer this to the users on Twitter. 

Closing as answered.
