### ISSUE TITLE
Repository description and README do not mention use for app bugs of iOS and Android

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#707]
## Where to find the issue

- "About" text in repository https://github.com/corona-warn-app/cwa-documentation
- [README.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/README.md)

## Describe the issue

The "About" text for this repository is set to:

"Project overview, general documentation, and white papers."

This does not mention the use of the repository for handling bugs which affect both iOS and Android operating systems, as described in [ISSUE_TEMPLATE/02_bugs.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/.github/ISSUE_TEMPLATE/02_bugs.md)

```
* [ ] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
```

The [README.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/README.md) file contains no mention either of the use of the [repository issue list](https://github.com/corona-warn-app/cwa-documentation/issues) to track not only documentation issues, but also app issues affecting both iOS and Android.

## Suggested change

- Update the description for this repository which appears under "About" so that it covers "app bugs common to both iOS and Android" (this has to be done by the Open Source Team due to permissions needed).
- Update the [README.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/README.md) file of this repository with a new section describing how the repository is used to submit and track app bugs which are common to both iOS and Android operating system environments.
- Update the README files of both iOS and Android repositories with an explicit cross-reference to the documentation repository as a place to report and track issues affecting both iOS and Android apps.

**Comment by Ein-Tim** [comment]
This issue is open for ca. 6 months now and there was no comment from the Open-Source-Team at all. Please let us know how you plan to proceed with this issue.
