### ISSUE TITLE
Is it possible for testing points of business tests („Betriebstests“) to connect to the CWA quick test portal?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#708]
## Your Question
On Twitter, the question was asked whether it's possible for testing points in businesses to connect to the CWA quick test infrastructure. 

https://www.coronawarn.app/en/rat-partner/ says:

"A prerequisite for linking your rapid tests to the Corona-Warn-App is that the test is performed under supervision. This means that no results from so-called lay tests may be transmitted. **In addition, it must be ensured that your test center is officially registered with the local health authority and meets the associated requirements.**"

So I'm not sure at the moment whether it's possible or not for testing points in businesses (exclusive for the employees) are able to connect to the rapid antigen test infrastructure of the Corona-Warn-App.

**Comment by dsarkar** [comment]
@Ein-Tim Please, could you suggest the twitter user to contact registrierung.labore.pandemietest@t-systems.com. Thanks.


---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@dsarkar 

They already did this and the response was no, that's not possible. 
However, we now wondered why the "Bundeskanzleramt", mentioned in the blog Post [Project team integrates rapid COVID-19 tests into Corona-Warn-App version 2.1](https://www.coronawarn.app/en/blog/2021-05-02-corona-warn-app-version-2-1), is able to be connected then. 

But if the "last" word here has the team at registrierung.labore.pandemietest@t-systems.com, then that's fine for me & I'll close this issue.

**Comment by Ein-Tim** [comment]
@dsarkar 

Do I interpret the 👍 right as the last word has mailto:registrierung.labore.pandemietest@t-systems.com? 🙂

**Comment by dsarkar** [comment]
@Ein-Tim I will ask internally.

**Comment by Ein-Tim** [comment]
@dsarkar Thanks!

**Comment by Ein-Tim** [comment]
@dsarkar Is there an update available here?

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Since the registration process is closed to new test stations, I guess that this question is now obsolete.

See https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki.

**Comment by Ein-Tim** [comment]
@MikeMcC399 You're right, it's still sad that I wasn't able to get an answer here. Closing.
