### ISSUE TITLE
Certificate dates of birth show different and sometimes wrong formats

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#710]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [ ] Bug is not already reported in another issue
Related to Android issue https://github.com/corona-warn-app/cwa-app-android/issues/4112.

## Technical details

- Android version: Android 11
- First reported in App version: 2.10.1
- Confirmed also present in App version: 2.17.2

## Describe the bug

- CWA mixes up the format in which it displays dates of birth from certificates, sometimes using `yyyy-mm-dd` format and sometimes attempting to apply locale specific formats. 
- ~~On Android this has led to formatting errors (see https://github.com/corona-warn-app/cwa-app-android/issues/4112).~~ now resolved.

## Steps to reproduce the issue

Set locale to English (United Kingdom)

In CWA 2.6.1 (last version which allows importing without correct signature)
1. Tap "Certificates" tab, (tap "CONTINUE" if necessary), tap "+ CERTIFICATE"
2. Scan https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/DE/2DCode/png/1.png
3. Scroll down to Geburtsdatum / Date of Birth (YYYY-MM-DD)
4. Note "1964-08-12"
5. Tap back arrow
6. Scroll down to "Born 12.08.1964"

Update to CWA 2.15.1
1. Tap "Certificates" tab 
2. Tap certificate of Erika Mustermann
3. Scroll down to "Erika Mustermann, Born 08/12/1964"
4. Note this is the wrong format for English (United Kingdom) and it is a different format used to display the date of birth in the the detailed certificate view

![Erika dob](https://user-images.githubusercontent.com/66998419/134407477-d424f5ac-05c1-4ad6-89e8-9b6a378567eb.png)

## Expected behavior

CWA should show certificate dates of birth in a consistent format. This should be either:
- YYYY-MM-DD (with label showing the format) or
- format according to the device's local, which may for instance be `dd.mm.yyyy`, `dd/mm/yyyy` or `mm/dd/yyyy`

Date of birth on printed EU digital COVID Certificates is shown always in the format `yyyy-mm-dd`.

## Possible Fix

EU Digital COVID Certificates may use different date of birth field contents, for instance:

"1979-04-14",
"1950",
"1901-08",
""

are all valid examples.

To solve the issue that certificate dates of birth may not contain all fields: year, month and day, use the format YYYY-MM-DD in all places where certificate dates of birth need to be displayed.

Also, to increase consistency, the field should be labelled:
- "Date of Birth (YYYY-MM-DD)" instead of "Born" (EN) and
- "Geburtsdatum (YYYY-MM-DD)" instead of "geboren" (DE).

This should be implemented for Android and iOS.

## Additional information

CovPass-App (Version 1.165.6 Android) uses YYYY-MM-DD formatting and the above suggested labelling for date of birth in all places and independently of the device's locale.

---
Internal Tracking ID: [EXPOSUREAPP-9220](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9220)

**Comment by MikeMcC399** [comment]
@dsarkar 
Could you get this assigned an internal ID please? The bug in https://github.com/corona-warn-app/cwa-app-android/issues/4112 needs to be solved (Internal Tracking ID: [EXPOSUREAPP-9595](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9595)) but it might be better to just generally use YYYY-MM-DD for certificate's date of birth formatting and this needs to be considered separately.

**Comment by larswmh** [comment]
Closing this issue as the related internal ticket is set to `obsolete`.

Developer comment:

> Since all dates now come from the DCC, all dates are now displayed the same.

**Comment by MikeMcC399** [comment]
@larswmh 
> Developer comment:
>
>> Since all dates now come from the DCC, all dates are now displayed the same.

This is not true. You can see this on the published screenshots https://www.coronawarn.app/en/screenshots/#android_invalid_certificate

On the left-hand side the date of birth is shown as "Born 01/01/1942" and on the right-hand side it shows "1989-12-12". Two different formats are being used.

(Incidentally this also means that these example screenshots are inconsistent because even if a different format is used, the actual date of birth should be the same.)

![image](https://user-images.githubusercontent.com/66998419/173796866-932d03c0-e620-4e92-aea5-6ba69c29ad12.png)

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Remember that under iOS the way date formats are shown is dependent on the users setting.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
It's the same on Android. In any case two different formats are being used to display dates of birth on the same device and different screens.
