### ISSUE TITLE
Missing capitalization for some sentences in the "Certificates" area

### ISSUE THREAD

**Issue by jkrwdf** [corona-warn-app/cwa-documentation#715]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 3 XL
- iOS/Android version: Android 11
- App version:2.10.1

## Describe the bug

There is an inconsistent use of capitalization or non-capitalization of the first word in some standalone-sentences in the "Certificates" area. In the screenshots below, I demonstrate the cases which I consider incorrect and compare them to similar cases in other areas of the CWA and of CovPass as reference. 

## Steps to reproduce the issue

This screen shows the result of a tap onto a QR code in the "Certificates" area to show the persisted certificates of the person.

![image](https://user-images.githubusercontent.com/5329491/135526418-d85d4587-c0b6-46d8-abcd-ef8125d79bbf.png)

I claim that all the marked letters should be UPPER-case and it should be: 

- Geimpft am ...
- Letzte Impfung vor ...
- Geboren ...

You may say that this is just one opinion and that the design team of CWA decided differently.

However, I can demonstrate that other locations of CWA do upper casing for comparable items. 

For example, in the details of a single certificate, we find this: 

![image](https://user-images.githubusercontent.com/5329491/135526712-565fd104-9216-45f5-9320-7db0eb666c01.png)

Here we have "Gültig bis ..."

Or here, a quick-test result: 

![image](https://user-images.githubusercontent.com/5329491/135527032-79e6421b-3c33-4048-931c-573ed87e5202.png)

"Durchgeführt am ..." with upper case. 

If we look at our "competition" in CovPass, we find:

![image](https://user-images.githubusercontent.com/5329491/135527182-34fac8c8-2294-431f-a44a-9c6a6fbcb2d0.png)

"Geimpft am ..." with upper case.

## Expected behaviour

Consistent use of upper-case sentence start for all standalone-sentences. 

To explain what I mean with "Standalone"-sentence, here an example where the use of lower-case is accepted: 

![image](https://user-images.githubusercontent.com/5329491/135527440-8e9b7f87-69a0-4d6f-912f-19daf5573fc4.png)

The "geboren" is here a direct addition to my name, separated by a comma. 

Or here

![image](https://user-images.githubusercontent.com/5329491/135527608-6567b67f-bb83-447d-ab1f-b045b8d1b03e.png)

where we also have a single sentence, just broken up to multiple lines: "Bis gestern ... bestätigte Neuinfektionen ...".

---
Internal Tracking ID: [EXPOSUREAPP-9781](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9781)

**Comment by dsarkar** [comment]
Hi @jkrwdf Thanks for the report. Internal Tracking ID: [EXPOSUREAPP-9781](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9781). Best, DS 

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Android PRs:

- https://github.com/corona-warn-app/cwa-app-android/pull/4196
- https://github.com/corona-warn-app/cwa-app-android/pull/4197

**Comment by Ein-Tim** [comment]
I can confirm that version 2.13 has fixed this issue.

Here is a screenshot of the Corona-Warn-App version 2.13.1 running on an iPhone 6s with iOS 15.1.

<img src="https://user-images.githubusercontent.com/67682506/140178856-7c586f82-132d-447b-a947-df0bcb5c6b18.jpeg" width="300">

As you can see, version 2.13 changed all the incorrect lower case letters to upper case.

**Comment by jkrwdf** [comment]
Thanks for the preview.

As Android user, I will have to wait a couple of days for review on my platform, I will close the issue thereafter.

**Comment by jkrwdf** [comment]
Hi, 

CWA 2.13.2 for Android just arrived on my Google Pixel 3 XL, and unfortunately I have to kindly ask for rework here.

**Issue 1**

The "Letzte Impfung vor..." for Android is still lower case:

![image](https://user-images.githubusercontent.com/5329491/140622885-c25c0c94-2568-4c50-a648-bbc362a870ee.png)

(for iOS, @Ein-Tim demonstrated above that it has been capitalized).

**Issue 2**

The only location where a lower-case "geboren" was valid, the RAT test details, has now also been capitalized:

![image](https://user-images.githubusercontent.com/5329491/140622904-ff75d640-aa8d-43fd-89eb-6d8bb56df969.png)

I explicitly mentioned this occurrence of a valid lower capitalization already in my initial issue description. Search for this text: "To explain what I mean with "Standalone"-sentence, here an example where the use of lower-case is accepted:"

I therefore feel not guilty for this "excess", but ask you to revert this (single) one.

**Comment by jkrwdf** [comment]
Hi, 

yesterday I had the chance to add a fresh vaccination to the CWA, and I see there that for the special case "Letzte Impfung heute" the "L" has been successfully capitalized, while next days "letzte Impfung vor 1 Tag" still is lower case. The same applies to the then final "letzte Impfung vor ... Tagen".

See the green and red marks in the following screenshot. 

![image](https://user-images.githubusercontent.com/5329491/144372370-a1b96f68-2a8c-4839-90d5-89f2d33dd585.png)

Give me an "L"...

jkrwdf

**Comment by dsarkar** [comment]
@Ein-Tim Thanks, is that the only missing capitalisation you found? We will re-open the internal ticket.

**Comment by Ein-Tim** [comment]
(@dsarkar It wasn't me 😉 It was @jkrwdf)

**Comment by jkrwdf** [comment]
Hello @dsarkar , 

this is @jkrwdf speaking, the other one with the six letter user name.

No, further _missing_ capitalizations I did not see. 

In https://github.com/corona-warn-app/cwa-documentation/issues/715#issuecomment-962505875 I annotated that due to the capitalization of "Geboren" for the start-of-line usages, the "geboren" in the in-line-usage for test results has now also been capitalized (likely those two UI locations used the same text-symbol reference) and that this one should be lower-cased again. 
I leave it to the developers assessment whether this was intentional or a side-effect and will not make my issue closing depending on it. 

Best,
@jkrwdf

**Comment by Ein-Tim** [comment]
PR: https://github.com/corona-warn-app/cwa-app-android/pull/4466

**Comment by dsarkar** [comment]
Hi @jkrwdf, thanks for your feedback, very much appreciated! Best, DS

**Comment by jkrwdf** [comment]
Closing after review in CWA 2.15.1
