### ISSUE TITLE
Luca QR Code as CWA check-in code _ when will it be possible

### ISSUE THREAD

**Issue by viisauksena** [corona-warn-app/cwa-documentation#719]
hey,
since tomorrow (15.10.2021) it will be allowed in Baden Württemberg to Check-In via the CWA - and also fullfill the Data-record-requirements - which is awesome.

in the [Luca Backend](https://gitlab.com/lucaapp/web/-/blob/master/CHANGELOG.md#1111-2021-05-25) its possible to mark new QR Codes (Luca) as CWA-compatible. 
`1.1.11 (2021-05-25)
locations: feat: checkout users from tables
locations: feat: checkout single users from locations
locations: feat: generate qr codes compatible with CWA`

**But as far as i know this is not yet allowed.
is there any info when this will be available? is there any chance to push this if possible?**

related found infos/links:
https://gitlab.com/lucaapp/android/-/issues/32
https://github.com/corona-warn-app/cwa-documentation/blob/295f6c64cfd4a258629ce85377592cc6784ec457/event_registration.md#qr-code-compatibility-with-other-contract-tracing-apps-in-germany-draft
https://github.com/corona-warn-app/cwa-server/pull/1362#issuecomment-882052293

---
Internal Tracking ID: [EXPOSUREAPP-9030](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9030)

**Comment by floscher** [comment]
@viisauksena To answer your question: It is now possible to scan luca-QR-codes with the CWA. At least if the luca-QR-code was generated on or after 26th of May 2021. Older QR codes would have to be regenerated.

**Comment by dsarkar** [comment]
@viisauksena FYI
- Blog **EN** https://www.coronawarn.app/en/blog/2021-11-09-cwa-luca-qr-codes/
- Blog **DE** https://www.coronawarn.app/de/blog/2021-11-09-cwa-luca-qr-codes/
- FAQ **EN** https://www.coronawarn.app/en/faq/#check_in_luca
- FAQ **DE** https://www.coronawarn.app/de/faq/#check_in_luca
