### ISSUE TITLE
Source Code Corona App

### ISSUE THREAD

**Issue by Fustorxx** [corona-warn-app/cwa-documentation#72]
Sehr geehrte Damen und Herren,

Zu allererst möchte ich meine Missgunst für die Arbeit der Telecom oder SAP an dem Projekt beteuern. Mal abgesehen von den Abhänggkeit, das Spiel der Bundesregierung mit großen Unternehmen (Beispiel: DFS und die Telekom, Büschel und die BOSCH etc...-> versteckte Projektkosten ohne Ausschreibung), wäre es für die Telekom ganz leicht die Mobilfunkdaten(IMSI) mit der Corona App zu korrelieren! Da will ich mal etwas anderes erklärt bekommen. Es reicht ja schon aus die IP des Corona APP Servers und des jeweiligen Smartphones zu wissen. Ganz easy wenn man Mobilfunkanbieter ist!

Sie haben doch sicherlich bereits angefangen Code zu schreiben! Ich würde mir von einem Open Source Projekt, bezahlt von der Regierung, also auch von mir, gerne den kompletten Verlauf der Code Änderungen zu gemüte führen, von Beginn an! Falls sie bisher nicht GIT verwendet haben, das ist ja bekanntlich kein Problem, es gibt genügend Konverter! 

Bitte checken sie den Code zügig ein, bevor sie hier zahllos mit Dokumenten prallen!
In den Medien wird genannt das dasder Source code verfügbar ist mit einem Link hier her, aber ich finde keinen Source Code...Das ist keine Demokratie!

Mit freundlichen Grüßen

Fuß, Sebastian

**Comment by tkowark** [comment]
Duplicate of #61
