### ISSUE TITLE
"Hinweise" section on DCC validity check screen includes outdated bullet point

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#721]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Not relevant
- iOS/Android version: Not relevant
- App version: 2.11

## Describe the bug

The "Hinweise" section on the DCC validity check result screen includes an outdated bullet point:
"Um die Echtheit eines Zertifikats sicherzustellen, wird jedes Zertifikat mit einer digitalen Signatur ausgestellt. **Diese Signatur wird nur in einer Prüf-Anwendung validiert.**"

The sentence "Die Signatur wird nur in einer Prüf-Anwendung validiert." is not true. The Corona-Warn-App also verifies the signature, see [Corona-Warn-App Version 2.7 shows technical expiration date and automatically checks certificates for authenticity](https://www.coronawarn.app/en/blog/2021-08-16-cwa-version-2-7/).

Here's a screenshot:

<img src="https://user-images.githubusercontent.com/67682506/137502425-57fa5a06-a1a9-4e3f-9b70-a16e11cc4c14.jpeg" width="300">

## Steps to reproduce the issue

1. Open the Corona-Warn-App
2. Click on the "Certificates" tab
3. If you have not yet added a certificate to the app, add one now by clicking "Zertifikat hinzufügen" (under iOS) or "+ Zertifikat" under Android.
4. Select a certificate
5. Click "Gültigkeit prüfen" (under iOS) or "GÜLTIGKEIT PRÜFEN" (under Android)
6. Select "Deutschland" from the list of countries
7. Select the current date and time
8. Click on "Prüfen" (iOS) or "PRÜFEN" (Android)
9. Scroll down to the "Hinweise" section
10. Note the 3rd bullet point which includes the wrong statement

## Expected behaviour

The app should not make untrue statements.

## Possible Fix

Correct the sentence.

---
Internal Tracking ID: [EXPOSUREAPP-10566](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10566) iOS
Internal Tracking ID: [EXPOSUREAPP-10784](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10784) Android

**Comment by MikeMcC399** [comment]
@Ein-Tim 

In CWA Android release/2.11.x the strings are from `validation_start_note_point_3` in `covid_certificate_strings.xml`.

---
(EN)
"To ensure the authenticity of certificates, each certificate is issued with a digital signature. A validation app merely validates this signature."

(DE)
"Um die Echtheit eines Zertifikats sicherzustellen, wird jedes Zertifikat mit einer digitalen Signatur ausgestellt. Diese Signatur wird nur in einer Prüf-Anwendung validiert."

---
Apart from the issue which you pointed out in the German text, the English sentence "A validation app merely validates this signature." is not a correct translation of the German sentence "Diese Signatur wird nur in einer Prüf-Anwendung validiert.".

**Comment by Ein-Tim** [comment]
@MikeMcC399

Thank you for the reference to the strings!

> Apart from the issue which you pointed out in the German text, the English sentence "A validation app merely validates this signature." is not a correct translation of the German sentence "Diese Signatur wird nur in einer Prüf-Anwendung validiert.".

I also noticed this.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for reporting. Internal Tracking ID: [EXPOSUREAPP-10566](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10566)

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> > Apart from the issue which you pointed out in the German text, the English sentence "A validation app merely validates this signature." is not a correct translation of the German sentence "Diese Signatur wird nur in einer Prüf-Anwendung validiert.".
> 
> I also noticed this. Would you like to open a new issue for this?

I didn't previously see your question / suuggestion from last month about opening a new issue, however if the German text is corrected, the English text will be changed anyway, so I don't think that a separate issue is necessary. It all doesn't make much sense the way it is currently worded.

**Comment by dsarkar** [comment]
@Ein-Tim Good morning! This has been implemented in 2.14. Do you want to confirm the fix and close this issue? Thanks.

**Comment by Ein-Tim** [comment]
@dsarkar I can confirm the fix under iOS, however, Android still incldues the outdated bulletpoint if I'm not mistaken.

**Comment by dsarkar** [comment]
@Ein-Tim I cant confirm the fix, see screenshots below (CWA 2.14.1). Do you have a screenshot were you can confirm the fix?

![image](https://user-images.githubusercontent.com/1409741/143858870-5f711a05-dbc4-4043-acae-c647a29aa191.png)

**Comment by MikeMcC399** [comment]
@dsarkar 
There has been no change made to Android in this respect. Even the strings in the next version [release/2.15.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.15.x) are the same as the ones quoted in https://github.com/corona-warn-app/cwa-documentation/issues/721#issuecomment-944360992.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for your feedback. I will re-open the internal ticket.

**Comment by Ein-Tim** [comment]
@dsarkar 

Sorry, I was not exact in my comment above. It seems like this will be fixed in version 2.14.2 under iOS, see https://github.com/corona-warn-app/cwa-app-ios/pull/3841, which was merged into `release/2.14.x` after 2.14.1 was released.

Anyways, as @MikeMcC399 said, this wasn't fixed under Android and there is no fix in sight.

So this is not yet fixed under iOS and not fixed under Android.

**Comment by dsarkar** [comment]
@Ein-Tim ok, thanks!

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-10566](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10566) iOS
Internal Tracking ID: [EXPOSUREAPP-10784](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10784) Android

**Comment by Ein-Tim** [comment]
I can confirm that the outdated bullet point was removed in version 2.15, so under iOS, this issue is no longer existent. I can't check the status under Android yet, because I did not receive the update yet.

**Comment by Ein-Tim** [comment]
This is fixed under both, iOS and Android. Closing.
