### ISSUE TITLE
"Exposure check failed" card: "Restart" button does nothing if the device is not connected to the internet

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#722]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 6s & Huawei P Smart 2019
- iOS/Android version: iOS 15.0.2/Android 11
- App version: 2.11.1 (iOS) 2.11.2 (Android)

## Describe the bug

The button "Restart" (iOS) / "RESTART" (Android) on the "Exposure check failed" card does not do anything.

Here are two screen recordings:

https://user-images.githubusercontent.com/67682506/137533002-90d1ab1d-a80c-49ad-acac-07ea4de217e8.MP4

https://user-images.githubusercontent.com/67682506/137533029-9555822d-8d11-4765-af3d-45d561ae761e.mp4 

## Steps to reproduce the issue

1. Open the Corona-Warn-App without an active internet connection
2. Check in to an event
3. Close the app
4. Open the app
5. See the "Exposure check failed" card with the "Restart" button
6. Click on "Restart"/"RESTART"
7. See that the button does nothing

## Expected behaviour

The "Restart"/"RESTART" button should either do something or present an error message

## Possible Fix

If https://github.com/corona-warn-app/cwa-app-ios/issues/3188 would be fixed this sowed probably be fixed too.

## Related Issues
- https://github.com/corona-warn-app/cwa-app-ios/issues/3188
- https://github.com/corona-warn-app/cwa-wishlist/issues/662

---
Internal Tracking ID: [EXPOSUREAPP10998-](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10998)

**Comment by dsarkar** [comment]
@Ein-Tim Thanks. Internal Tracking ID: [EXPOSUREAPP10998-](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10998)

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-ios/pull/4017

**Comment by Ein-Tim** [comment]
The behavior of the iOS app was aligned to the behavior of the Android app. 

https://user-images.githubusercontent.com/67682506/149987976-d6d12286-6f0e-48a4-bfe9-df4114546c21.mp4

Not a real great improvement IHMO, a pop up screen which informs why the check failed (missing connection to the internet) is still not shown.

**Comment by Ein-Tim** [comment]
I will follow up with another issue. This one is closed as resolved.
