### ISSUE TITLE
„Risk of infection“ section in „Overview“ does not mention how a risk of infection is calculated for check-ins

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#723]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR / Huawei P Smart 2019
- iOS/Android version: 15.0.2 / 10
- App version: 2.11.1 / 2.11.2

## Describe the bug

The "Risk of Infection" section on the "Overview" screen does not mention that one can also get shown an increased risk of infection because of check-ins.

Here's a screenshot:
![image](https://user-images.githubusercontent.com/67682506/137591711-33e51453-7179-4cc1-8860-11647e9a9464.jpeg)

## Steps to reproduce the issue

1. Open the Corona-Warn-App
2. Click on the "i" icon in the top right corner
3. Read through the section "Risk of Infection"
4. See that there is no mention of check-ins

## Expected behaviour

The app should also inform how a risk of infection is calculated based on check-ins

## Possible Fix

Add an explanation text.

---
Internal Tracking ID: [EXPOSUREAPP-11246](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11246)

**Comment by larswmh** [comment]
Thanks for your suggestion @Ein-Tim. Internal Tracking ID: [EXPOSUREAPP-11246](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11246)

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@Ein-Tim FYI

https://github.com/corona-warn-app/cwa-app-android/pull/4913

https://github.com/corona-warn-app/cwa-app-ios/pull/4302

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thank you! I checked under iOS and it includes the same text as Android now!

Therefore I'm closing this issue as fixed now.

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim Thanks for the feedback. I forwarded the fix CONFIRMed to internal ticket.
