### ISSUE TITLE
"Risk of Infection" paragraph on Low Risk detail card does not mention Check In based risk calculation

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#725]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR / Huawei P Smart 2019
- iOS/Android version: 15.0.2 / 10
- App version: 2.11.1 / 2.11.2

## Describe the bug

The "Risk of Infection" section on the low risk detail card does not mention how the risk of infection is calculated based on check-ins.

Here's a screenshot:
![83F845BD-860F-468F-A6B0-B09386B498BB_1_201_a](https://user-images.githubusercontent.com/67682506/137601540-863a2ec0-0ebd-4a7f-838f-d63fc53821e3.jpeg)

## Steps to reproduce the issue

1. Open the Corona-Warn-App
2. Click on the green "Low Risk" card
3. Scroll all the way down
4. Read through the "Risk of Infection" paragraph

## Expected behaviour

The paragraph should also mention how a risk of infection is calculated based on check-ins.

## Possible Fix

Add an explanation.

---
Internal Tracking ID: [EXPOSUREAPP-13529](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13529)

**Comment by Ein-Tim** [comment]
@dsarkar Will this issue at least be mirrored to JIRA, if not addressed, soon?

**Comment by Ein-Tim** [comment]
Please mirror this issue to JIRA now.

**Comment by larswmh** [comment]
Thanks for your report @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-13529](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13529)

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> The "Risk of Infection" section on the low risk detail card does not mention how the risk of infection is calculated based on check-ins.

The explanation you asked for is not in the "Risk of Infection" section, however it is now explained in the "Period Logged" section. above the "Risk of Infection" section.

![image](https://user-images.githubusercontent.com/66998419/177699340-466afdb6-d510-4149-80eb-7de2780d2e5a.png)

I couldn't check with version 2.11.1 / 2.11.2 which you mentioned, since this version forces an update when started. I did however look at 2.12.2 and in this version there was no description of check in data being using for exposure logging in the low risk detail card.

Your issue was addressed later on in the 2.23 version (in a slightly different way). Would you like to cross-check in the current version? It looks like you could close this request.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I'm on version 2.24.1 under iOS and I am not seeing this text. So it seems like this was not addressed under iOS:

<img src="https://user-images.githubusercontent.com/67682506/177707520-cf79ea91-e383-4d60-81fb-f424b1f39e39.png" width="300">

@dsarkar Could you clarify, please?

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Sorry that I didn't check on the screenshots page!

https://www.coronawarn.app/en/screenshots/#ios_cards is missing the text which shows on https://www.coronawarn.app/en/screenshots/#ios_cards.

This is clear from the images:

- https://www.coronawarn.app/assets/screenshots/2-24/en/ios/no2en.png
- https://www.coronawarn.app/assets/screenshots/2-24/en/android/TracingDetailsFragment_tracing_low_risk_with_one_encounters_3.png

iOS should be aligned to Android.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

> Sorry that I didn't check on the screenshots page!

No problem! As the screenshot page also tends to be somehow out off date, it was good that you commented here!

I am thinking about providing a PR for this under iOS. It shouldn't be necessary to get approval from RKI anymore, as they already approved the text, which is now live in the Android app.

**Comment by MikeMcC399** [comment]
- See https://github.com/corona-warn-app/cwa-app-ios/pull/4665 for resolution in 2.25.

**Comment by dsarkar** [comment]
@Ein-Tim Text in iOS also mentions now Check-Ins, see OP of PR mentioned by @MikeMcC399 or https://user-images.githubusercontent.com/22373291/178715707-12efb0e1-1d1d-480e-8630-f90fb6cfe45b.png

**Comment by Ein-Tim** [comment]
@dsarkar Will close this issue as soon as the version with the texts is released.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

The screenshot https://www.coronawarn.app/assets/screenshots/2-25/en/ios/no2en.png in the https://www.coronawarn.app/en/screenshots/#ios_cards section shows the corrected text for CWA iOS 2.25.

**Comment by Ein-Tim** [comment]
Indeed this issue was fixed with version 2.25. Closing.
