### ISSUE TITLE
Dumb / Feature Phones~

### ISSUE THREAD

**Issue by Petschko** [corona-warn-app/cwa-documentation#73]
## Your Question
* Documentation File: N/A
* Line / Paragraph: N/A
* Question:

Whats about people with Dumb & Feature-Phones? What when people don't take their phone always with them (Or don't have a Phone like many older ones?)? 

I see to many issues in this app idea... (Beside from the idea of total surveillance)

**Comment by tkowark** [comment]
Thanks for your question!

The current scope covers only Android and iOS Phones that support the Exposure Notification Framework.

Regarding the „Total Surveillance“ aspect, I can only recommend the DP3T comic mentioned in #21 for general explanations of the concept.
