### ISSUE TITLE
Missing date for deletion from recycle bin

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#731]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy A52 5G SM-A526B/DS
- Android version: 11
- App version: pre-release branches release/2.13.x and release/2.14.x

Also affects iOS.

## Describe the bug

After deleting a certificate and viewing the recycle bin it is not possible to find out when a certificate will be deleted. There are no dates related to deletion shown in the display.

## Steps to reproduce the issue

1. Open CWA
2. Tap "Scan" button and scan in a certificate, for example, a vaccination certificate
3. Tap three-dot symbol and select "Remove Certificate", confirm "REMOVE CERTIFICATE"
4. On Status screen tap three-dot symbol and select "Recycle bin"
5. Note the message that elements will be deleted automatically after 30 day. View the certificate and note that the date when the certificate was removed is not shown, neither is a planned date for deletion from the recycle bin shown.

![CWA Recycle bin](https://user-images.githubusercontent.com/66998419/139433704-ed5b15e4-6b2e-4b09-bef7-cea15d5b1b7d.jpg)

## Expected behavior

The behavior of the app should be predictable. Without a concrete deletion date, the app is not predictable. The recycle bin should show for each item when it is planned to be deleted automatically.

## Possible Fix

Add a date for planned deletion to each item in the recycle bin.

---
Internal Tracking ID: [EXPOSUREAPP-10260](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10260) obsolete
Internal Tracking ID: [EXPOSUREAPP-10125](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10125) iOS
Internal Tracking ID: [EXPOSUREAPP-10766](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10766) Android

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim Thanks. 
Internal Tracking ID: [EXPOSUREAPP-10260](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10260)

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399 Additionally, for tests the date of the test or the date of registration of the test will be shown, see PR https://github.com/corona-warn-app/cwa-app-android/pull/4601

**Comment by Ein-Tim** [comment]
FYI: https://github.com/corona-warn-app/cwa-app-ios/pull/4055 says:

**Comment by MikeMcC399** [comment]
@dsarkar 

Do you still think that Fix 2.16 is the right label for this issue? Or should it be 2.17?

**Comment by dsarkar** [comment]
FYI PRs 
https://github.com/corona-warn-app/cwa-app-android/pull/4667 
corona-warn-app/cwa-app-ios#4055

**Comment by MikeMcC399** [comment]
I verified that this enhancement works in CWA 2.17.2 Android. The deletion date is also formatted correctly for English (United States), English (United Kingdom) and Deutsch (Deutschland) locales.

If somebody can confirm that this also works on iOS, then we can close this issue. (@Ein-Tim ?)

**Comment by Ein-Tim** [comment]
I can confirm that this was implemented in version 2.17 and works as intended under iOS.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Thanks for the confirmation! So I will now close.
