### ISSUE TITLE
iOS app shows 1/2 certificate with a blue background color, Android app with a grey background (if 2/2 certificate is not also stored in the app)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#733]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR/Huawei P Smart 2019
- iOS/Android version: 15.1/10
- App version: 2.12.1/2.12.2

## Describe the bug

The detail view of an EU digital COVID-19 vaccination certificate where the certificate is not the final one of a series (= "1/2" certificate) is shown with a grey background, but only under Android. 
iOS shows the certificate with a blue background.

| Android | iOS |
|---|---|
|  <img src="https://user-images.githubusercontent.com/67682506/140168264-18103a4c-2f75-414f-a6df-714bbcfd6b15.jpg" width="300"> |  <img src="https://user-images.githubusercontent.com/67682506/140168279-1ca1d4ea-1664-452c-8a5e-750e53636bf1.jpeg" width="300"> |

## Steps to reproduce the issue

1. Delete all stored certificates from the app
2. Click on the universal QR code scanner
3. Scan a "1/2" EU digital COVID-19 certificate 
4. See that iOS shows the imported certificate with a blue background color while Android shows the certificate with a grey background color

## Expected behaviour

Both apps should use the same background color for a "1/2" certificate if it's the only one stored in the app.

## Additional context

The behavior of the apps align when importing the "2/2" certificate (iOS also shows the "1/2" certificate with a grey background color).

## Related issues
- https://github.com/corona-warn-app/cwa-app-android/issues/4200
- https://github.com/corona-warn-app/cwa-app-android/issues/3927

---
Internal Tracking ID: [EXPOSUREAPP-10332](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10332)

**Comment by dsarkar** [comment]
@Ein-Tim Thanks. Internal Tracking ID: [EXPOSUREAPP-10332](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10332)

**Comment by dsarkar** [comment]
@Ein-Tim Do you have screenshots you could upload?

**Comment by Ein-Tim** [comment]
@dsarkar 

For sure. As these are my own certificates, I had to blur the QR code:

| Android | iOS |
|---|---|
|  <img src="https://user-images.githubusercontent.com/67682506/140168264-18103a4c-2f75-414f-a6df-714bbcfd6b15.jpg" width="300"> |  <img src="https://user-images.githubusercontent.com/67682506/140168279-1ca1d4ea-1664-452c-8a5e-750e53636bf1.jpeg" width="300"> |

I have also added these screenshots to the OP.

**Comment by dsarkar** [comment]
@Ein-Tim thanks for the screenshots

**Comment by dsarkar** [comment]
forwarded to internal ticket.

**Comment by Ein-Tim** [comment]
@dsarkar Will this issue be addressed soon?

**Comment by Ein-Tim** [comment]
Fix for this: https://github.com/corona-warn-app/cwa-app-android/pull/5209

Reopening until 2.23 is released.
