### ISSUE TITLE
Grooming of DCC Rules Master-Excel

### ISSUE THREAD

**Issue by BrittaTSI** [corona-warn-app/cwa-documentation#734]
Reaction to comments on Master-Excel from RKI.

2Do:
Wording
- [x] check wording for rules and translations
- [x] change incorrect translations to fit German version

Deeplinks
- [x] check deeplinks to rule JSONs
- [x] add correct deeplink to JSON for TR-DE-0005

Change rules
- [x] check possibility in version of CERTLOGIC that is used in apps that are currently in the field to change "+180d" to "+6m" and "+365d" to"+1year"

Result: it is not possible to make these changes as they are not compatible with the CERTLOGIC versions used in older versions of the CWA

CERTLOGIC

- [x] check who specified CERTLOGIC engine version as "2.0.1"
- [x] check which value is correct and change Excel accordingly

**Comment by Ein-Tim** [comment]
@BrittaTSI 

Could we get a bit context on this issue, please? 
To which document(s) do you refer?

Thank you & have a nice evening!

**Comment by BrittaTSI** [comment]
Hi @Ein-Tim, this refers to the (non-public) Excel-Sheet that is used by RKI, BMG, SAP and T-Systems to manage the Acceptance, Validation and Booster Notification rules for Digital Covid Certificates that are used by the CWA, CovPass Check, etc. e.g. to check if your vaccination or test certificate is valid in Germany or in the future also to inform you that you might be eligible for a booster shot.
We have made a lot of changes to the rules during the process of defining and updating so we need to do some grooming to eliminate some minor inconsistencies. 
Unfortunately the issue does not really not fit properly into any of the repositories we are using so I chose "cwa-documentation" because it was the least inappropriate, so to speak. ;-)
I hope this answers your question?
A nice evening to you, too!

**Comment by pkern** [comment]
Is the resulting JSON ruleset actually publicly available?

**Comment by BrittaTSI** [comment]
@pkern - Upon request from RKI/BMG the JSON is also stored in a private repository. Please mind that DCC rule management is not a direct part of the Corona-Warn-App project.

**Comment by MikeMcC399** [comment]
@BrittaTSI 

I don't believe it makes sense to track issues in this GitHub repository if the objects it concerns are not visible in this repository.

Perhaps you could find somewhere else, non-public, to do your tracking for this?

**Comment by Ein-Tim** [comment]
@BrittaTSI Hey Britta, did you think about placing this issue in another repository, or maybe the issue you describe in the OP was already fixed? Thanks for the feedback!

**Comment by BrittaTSI** [comment]
@Ein-Tim - thank you for the comment. This issue is indeed fixed and I will close it here.
