### ISSUE TITLE
Notification information text regarding booster info contains confusing technical data, and this in inconsistent format

### ISSUE THREAD

**Issue by jkrwdf** [corona-warn-app/cwa-documentation#737]
## Where to find the issue
The notification regarding booster. 
See screenshot.

![image](https://user-images.githubusercontent.com/5329491/140469866-add8c014-11d1-4d27-8e1f-0917f2c15751.png)

## Describe the issue
1. Showing the technical rule identifier is confusing for the regular user. 
2. The same rule is printed in two different formats in the same text ("DE-BNR-0110" vs "BNR-DE-0110").

## Suggested change
1. Eventually you can hide the technical details behind a "Technical Information" button/link/excursus/...
2. Harmonize the format.

**Comment by MikeMcC399** [comment]
@jkrwdf 
You did not say whether the screenshot is from Android or iOS. I'm guessing Android and maybe you could confirm?

There is an equivalent screenshot from iOS on https://www.coronawarn.app/de/blog/2021-11-04-cwa-booster-notification/ which shows only `BNR-DE-0110` displayed and only in one place, so it looks like this is a problem on Android only.

The actual screenshot is:

![Benachrichtigung-70](https://www.coronawarn.app/assets/img/blog/2021-11-04-booster-notifications/benachrichtigung-70.png)

and I would guess that it is iOS because the label "Gültigkeit prüfen" is in mixed-case.

**Comment by jkrwdf** [comment]
Yes, this is on Android. 

I always seem to pick the wrong repo ;-) My issues I open for Android are regularly cross-platform, which those which I definitely assume to be cross-platform are platform specific. Argh!

**Comment by MikeMcC399** [comment]
@jkrwdf 
> What speaks for the "documentation" repo still: Issue 1, which also appears in iOS as per your screenshot.

I agree. The rule names should be consistent across iOS and Android. 
There are two issues you have described, so I would wait to see what @dsarkar responds.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

> I agree. The rule names should be consistent across iOS and Android.

They are. However, @jkrwdf shared a screenshot where the text says 
"Da sie laut Ihrer gespeicherten Zertifikate dieser Personengruppe angehören [...]"

and the screenshot you shared says:

"Da sie laut Ihrer gespeicherten Zertifikate **bald** dieser Personengruppe angehören [...]

I checked on my iPhone XR & on a Huawei P Smart 2019 with the same certificate, the text is:
"Da sie laut Ihrer gespeicherten Zertifikate **bald** dieser Personengruppe angehören [...]

and the rule is DE-BNR-0100 on both iOS & Android.

**Comment by mlenkeit** [comment]
@jkrwdf thanks for opening the ticket! It's an unfortunate typo in the shared rule description. That's also why it occurs on iOS and Android.

**Comment by MikeMcC399** [comment]
@mlenkeit 
Are the booster rules visible anywhere on GitHub?

**Comment by mlenkeit** [comment]
@MikeMcC399 no, they are not at the moment.

Regarding inconsistencies: as @Ein-Tim mentioned, there is `BNR-DE-0100` and `BNR-DE-0200` with _bald_/_soon_ in the text and then there's `BNR-DE-0110` and `BNR-DE-0210` without _bald_/_soon_.

**Comment by vaubaehn** [comment]
Personally, I find the rule number to be displayed extremely helpful for debugging reasons. Not putting it into the text and having it displayed at the bottom in a less prominent way could be better UX, though.

**Comment by Jo-Achim** [comment]
Another two points to both screenshots above:

1. Behind the word "Impfstatus", the screenshots show a 'red point'. 
In CWA 2.13.2 under Android 11, there is no 'red point'!
2. I remember in the past (CWA 2.12?) there was a second 'red marker' in the first certificates screen in conjunction with the "Impfstatus" 'red point'. This 'red marker' is missing too (CWA 2.13.2). 
Looking in CovPass 1.12.0, the little 'red point' is still there (inside the shield-symbol).

**Comment by jkrwdf** [comment]
Looking again at the message today, the content has changed:

![image](https://user-images.githubusercontent.com/5329491/141737156-0d6f3679-2773-4f69-a0ed-c8aa022056bd.png)

The rule number is now presented at both locations with the same ID ("BNR-DE-0110"). 
But still, the label is different ("Regel" (without colon) vs. "Regel-ID" (with colon)), this double appearance is weird, and still I consider this number as inappropriate in this text body, but see it at the very bottom as a single piece of information, eventually prepended by some "Technical Information" text (which in future may be enriched with further data, maybe the date when the rule data were last updated.

BTW: The fact that although the last vaccination is only 50 days old but this text is still present is an issue which is already addressed in another issue. No need for action here.

**Comment by Ein-Tim** [comment]
@jkrwdf I just rechecked and IMO the situation has improved here and this issue can be closed:

| iOS | Android |
|---|---|
| ![IMG_EC3A46D26314-1](https://user-images.githubusercontent.com/67682506/163859728-a3543cc6-94d5-4df1-a122-a21bae5f9439.jpeg) | ![Screenshot_20220418_205138_de corona tracing](https://user-images.githubusercontent.com/67682506/163859737-d8c7abe6-c980-4188-87c9-54be90bab595.jpg) |

**Comment by jkrwdf** [comment]
Very well. Thanks. Closing.
