### ISSUE TITLE
Outdated statistics numbers for cwa warnings

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-documentation#738]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 8
- iOS/Android version: iOS 14.4.1
- App version: 2.12.1

## Describe the bug

Today my statistics tile for "number of warning persons" shows outdated numbers - as of Nov 02.
But today is Nov 05, so I would expect numbers from Nov 04.
Note: yesterday I had indeed different numbers, but today they have fallen back somehow ...

## Steps to reproduce the issue
- open cwa
- scroll down to the statistics tiles
- scroll sidewards to the tile that shows numbers for warning persons
- see outdated numbers. The date is given as 02 Nov.

## Expected behaviour

Current numbers as of yesterday.

## Additional context

![E3DC8F7B-6FEF-4DEC-AC9E-074DF388C3E1](https://user-images.githubusercontent.com/6118267/140536918-8ff87955-3106-45bd-a2b3-ffcb61f62a8b.png)

**Comment by MikeMcC399** [comment]
It's the same last date on https://www.coronawarn.app/de/analysis/ in the Graph "Teilungsverhalten" (Nov 2, 2021)

I wondered at first why the app showed a figure 3315 and the web showed a higher figure 3992. Reading the help, it seems that the app reports numbers based on PCR tests, whereas the web doesn't differentiate between PCR and rapid tests, except that teleTANs are only for PCR tests.

![Teilungsverhalten](https://user-images.githubusercontent.com/66998419/140539387-e54ec67e-e176-40eb-ae78-8ce11bd76511.jpg)

**Comment by ndegendogo** [comment]
fixed!
