### ISSUE TITLE
Missing information about constraints on deliverables

### ISSUE THREAD

**Issue by kbobrowski** [corona-warn-app/cwa-documentation#74]
## What is missing

Document which describes constraints imposed on SAP / Telekom developers (if there are any such constraints), e.g.:
- decentralized approach
- dependence on Google / Apple API
- all code released as open-source
- means of distributing the app
- etc.

Additional information about who exactly is the author of each constraint (e.g. some government body / SAP decision / joint SAP-government decision) would improve the transparency of the project.

## Why should it be included

It seems that a lot of discussion arises from the confusion as to what constraints were imposed on SAP / Telekom developers in terms of architecture. I could not find it in currently published documents (please correct me if I skipped something), and I'm only able to get this information from SAP employees responses in corresponding issues. Perhaps including a document like this would prevent future confusions and allow for easier on-boarding of community developers due to clear task scope.

Additional benefit is that anyone who has some doubts about any of the architectural decisions would be able to raise an issue using proper public channel corresponding to proper organization / authority.

## Where should it be included

Could be a short separate document listing all architectural constraints on deliverables.

**Comment by eaglerainbow** [comment]
> Could be a short separate document listing all architectural constraints on deliverables.

So far, I hoped to find that also in the upcoming architecture document (at least I understood that this would be made available in a timely manner as well). So, in short: Not necessarily to be a separate document. But knowing the "driving forces" of an architecture may significantly help to understand the latter.

**Comment by HolgerMayer** [comment]
I somehow didn’t find information on how QR codes are generated by doctors. For a successfull rollout it is necessary that the supporting QR-Code generation is available either at testing labs (preferable) or at the doctors office.

**Comment by jensmuehlner** [comment]
This issue is close to #66 , right? I suggest to look at them as one. But under the time constraints in the team right now it might be suitable to come back to that little later. Partly it even might already been answered in the readme 
https://github.com/corona-warn-app/cwa-documentation/blob/master/README.md

**Comment by kbobrowski** [comment]
@jensmuehlner I think it's close to #66, perhaps one document could clarify both. Totally understand time constraints, would be great if it is clarified sometime down the road :)

**Comment by SebastianWolf-SAP** [comment]
As already outlined in #66, we took the question really seriously and asked the German Federal Government to get a proper response.

The answer is now available [in our FAQ on our website](https://www.coronawarn.app/en/faq/), please check the new entries in the "General" section. 

Please get back to us in case you need additional details or if something is not clear.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by kbobrowski** [comment]
@SebastianWolf-SAP thanks a lot for providing comprehensive answer!
