### ISSUE TITLE
Scanning luca QR code with CWA results in "undefined"

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#741]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details
- Device name: iPhone 6s & Huawei P Smart 2019
- iOS/Android version: 15.1 & 10
- App version: 2.13.1 & 2.13.2

## Describe the bug
Scanning a luca QR code with the CWA results in this:

<img src="https://user-images.githubusercontent.com/67682506/140971402-01c8c5fb-975f-407a-b172-92737c7a5380.jpeg" width="300">

## Steps to reproduce the issue
1. Scan a luca QR code with the CWA
2. See that everything is "undefined"

## Expected behaviour
The CWA should show the information taken from the luca QR code.

## Additional context
Is this what happens if one scans a luca QR code which was generated before 25.05.2021?

**Comment by JonasDeichelmann** [comment]
In the Luca App the QR Code is working correctly.

**Comment by thomasaugsten** [comment]
We also saw Luca codes like this. But there is really the word undefined encoded. If you decode the base64 part after /CWA1/  you can see this.

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Ah okay...

Than this is an issue on luca side and I will close this issue.

**Comment by Ein-Tim** [comment]
FYI: There's an issue for this in the luca GitLab now: https://gitlab.com/lucaapp/cwa-event/-/issues/1

**Comment by viisauksena** [comment]
there is also the related issue, where Luca uses hardcoded 120 min for the QR Codes, 
even if you choose other timings for the QR Code related location/event. This is bogus for short shopping in bakerys or longer workshops/workdays.
see: https://gitlab.com/lucaapp/web/-/blob/master/services/locations/src/utils/qrCodeData.js
(there is also the undefined part)

**Comment by MikeMcC399** [comment]
See also https://gitlab.com/lucaapp/web/-/issues/31 "undefined in QR Codes erzeugt" where it says:

"... wir haben den Fix hierfür schon vorbereitet und er ist im nächsten Release.
Das Release 2.5 ist momentan noch in der QA Phase und wird getestet.
Sobald die Tests positiv abgeschlossen sind, werden wir den Fix mit deployen ..."
