### ISSUE TITLE
Maintenance of the cwa-wishlist repository

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#746]
## Your Question
* Question: The https://github.com/corona-warn-app/cwa-wishlist repository seems to be unmaintained at the moment.
The majority of the issues, which were created in the https://github.com/corona-warn-app/cwa-wishlist repository since Aug 19, 2021 were not mirrored to JIRA (with the exception of https://github.com/corona-warn-app/cwa-wishlist/issues/628, https://github.com/corona-warn-app/cwa-wishlist/issues/635, https://github.com/corona-warn-app/cwa-wishlist/issues/646 & https://github.com/corona-warn-app/cwa-wishlist/issues/678).
Issues created before Aug 19, 2021 were mostly mirrored to JIRA, with some exceptions (not labeled with the `mirrored-to-jira` label).

Will there be an effort to mirror all the issues created since Aug 19, 2021 (and the once which were not labeled with he `mirrored-to-jira` label) to JIRA?

**Comment by dsarkar** [comment]
@Ein-Tim Yes, we will catch up with this.

**Comment by Ein-Tim** [comment]
@dsarkar 

Okay, thanks for the answer!
