### ISSUE TITLE
Booster Notification is send repeatedly on every day

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#747]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR / Huawei P Smart 2019
- iOS/Android version: 15.1 / 10
- App version: 2.13.1 / 2.13.2

## Describe the bug

The Corona-Warn-App sends the booster notification repeatedly on every day since this feature was activated on November 4, 2021.

## Steps to reproduce the issue

1. Add the certificate from "Bettino Craxi", which was leaked & created illegitimate, from https://github.com/denysvitali/covid-cert-analysis/blob/master/RESULTS.md#samplesbettino-craxitxt, to your Corona-Warn-App.
2. Wait for some time and get the first booster notification
3. Click on the booster notification -> it disappears
4. Wait for 24h or a bit longer
5. See that the booster notification is send again

## Expected behaviour

The booster notification should only be send one time and not every day. 

## Additional context

As the certificates are checked [once a day](https://github.com/corona-warn-app/cwa-app-android/issues/4334#issuecomment-964897290) against the booster notifications, I guess the booster notification is send every time this check has finished.

I would expect a notification to be send only if something changed.

---
Internal Tracking ID: [EXPOSUREAPP-10548](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10548) iOS
Internal Tracking ID: [EXPOSUREAPP-10232](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10232) Android

**Comment by dsarkar** [comment]
@Ein-Tim This happens on both iOS and Android? There will be a fix for Android.

**Comment by Ein-Tim** [comment]
@dsarkar 

Yes, confirm. I saw this behaviour on my iPhone XR as well as on my iPhone 6s.

**Comment by dsarkar** [comment]
@Ein-Tim FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/4383

**Comment by Ein-Tim** [comment]
@dsarkar Thanks ￼for the link to the PR in the Android repo!
Will you still mirror this to JIRA to make sure an iOS dev looks at it?￼

**Comment by Ein-Tim** [comment]
Twitter report on this: https://twitter.com/aggrocoach/status/1461303534641635332?s=21

He get's the notification all 3 days...

**Comment by dsarkar** [comment]
@Ein-Tim Thanks. There will be a fix for Android. This user is using iOS or Android?

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-10548](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10548) iOS
Internal Tracking ID: [EXPOSUREAPP-10232](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10232) Android

**Comment by Ein-Tim** [comment]
@dsarkar 

> This user is using iOS or Android?

Sadly the user did not answer to my question where I asked this. The Tweet was send from an iPhone, so I guess he uses an iPhone.

**Comment by Ein-Tim** [comment]
This seems to have been fixed in version 2.14.

Closing as fixed.

**Comment by dsarkar** [comment]
Good morning @Ein-Tim! Thanks for the feedback. We had actually a few similar reports.
