### ISSUE TITLE
[DE] Video über die Corona Warn App - Bitte um Feedback

### ISSUE THREAD

**Issue by UsefulVid** [corona-warn-app/cwa-documentation#749]
https://youtu.be/gcK5voPBB0U
Bevor ich das video veröffentliche würde ich mich über Feedback bzw Korrektur freuen :)
Danke an die Entwickler für die tolle Arbeit!

**Comment by Ein-Tim** [comment]
@UsefulVid 

Thanks for sharing, however, I can't watch the video as it shows as private.

**Comment by UsefulVid** [comment]
> 
> 
> @UsefulVid
> 
> Thanks for sharing, however, I can't watch the video as it shows as private.

Already fixed :)

**Comment by Ein-Tim** [comment]
@UsefulVid 

This looks good to me in general! Thanks for making this video!

I suggest you add a link to the official [Blog](https://www.coronawarn.app/de/blog/) to the info box or mention it in the video. Also, the Twitter account @coronawarnapp can be recommended. 👍

I'd suggest to wait for feedback from some other community members (-: 

Thanks again!

**Comment by alanrick** [comment]
Nice 👍 
3:30 Bluetooth only _moderat_ energy drain. I believe _negligible_.

It’s missing my favourite feature - locate test centers nearby, and get the results back as soon the test has concluded, even if you’re already on you’re way to the party/cinema/match/date….
I‘m a 2G+ fan - and tests are free again.

**Comment by UsefulVid** [comment]
> It’s missing my favourite feature
Perhaps topic for an extra video :)
Thanks for your feedback, video will go online

**Comment by alanrick** [comment]
Definitely. Go for it 👌

**Comment by rugk** [comment]
> and get the results back as soon the test has concluded

Hmm that is already possible with connected test centres, at least for RATs which are evaluated this fast.

**Comment by Ein-Tim** [comment]
Ah, btw, is it necessary to leave this issue open @UsefulVid?
