### ISSUE TITLE
As a user of the app, after sending the pseudonymized IDs, I want to know how many persons I have warned.

### ISSUE THREAD

**Issue by saggl** [corona-warn-app/cwa-documentation#75]
## Your Question

* Documentation File: scoping_document.md
* Line / Paragraph: Triggering a Warning
* Question:
Would it be cool to know how many people I warned ?
Maybe:
"| E06.07 | As a user of the app, after sending the pseudonymized IDs, I want to know how many persons I have warned."

**Comment by tkowark** [comment]
Thanks for your question, @saggl !

With the decentralized approach that will be implemented in this project (https://github.com/corona-warn-app/cwa-documentation#about-this-project) this is not possible, as the number of contacts is not exposed through the API (see also #32). And even if this information is available through the OS, you would only know the number of exposure events and not be able to tell how many unique users those belonged to.

**Comment by niklas2810** [comment]
I don't think that this is possible to implement due to privacy-related issues that would be caused by such a feature.
