### ISSUE TITLE
Fraud seems too easy

### ISSUE THREAD

**Issue by schlichtanders** [corona-warn-app/cwa-documentation#752]
## Your Question
Recently I've become aware of the corona warnapp scan feature with which you can scan other person's certificates. My first thought was that I simply can see whether they are valid or not, however coronawarnapp added them straight away to my own certificates. 

This is worries me very much for some time now. With this it is extremely simple to do certificate fraud by just "checking" someone else certificate. Sure it seems that this was possible beforehand (which itself seems like a serious limitation of the certificate protocol). But being part of the official Corona Warnapp, this get's way to easy for my taste.

An alternative solution seems simple, that restaurants and co check the passport in addition, however I asked on a couple of official places and it seems that this is only something the police can do. Restaurants and every company is just fine with asking "please show me your 3G certificate" and if the person then shows something invalid, it is not the Restaurant's fault any longer, but an issue for the police. As you can imagine, I've never seen the police doing any check like that, so this is seriously corrupting the system.

Hence I want to suggest to turn off the feature to add other person's certificate to your own smartphone.

**Comment by dsarkar** [comment]
Good morning @schlichtanders.

Thanks for your contribution.

- It is indeed possible to scan and import certificates of other persons. This was a much desired feature, for example, a typical use case is a family: One person carries in the CWA "wallet" the certificates if his kids and his partner.
- The scan function is not a check function, it is a import functionality.
- In order to check the validity, in Germany the CovPassCheck-App should be used.


---
Corona-Warn-App Open Source Team

**Comment by schlichtanders** [comment]
thank @dsarkar for the super fast response.

> The scan function is not a check function, it is a import functionality.

I definitely misunderstood this one

> It is indeed possible to scan and import certificates of other persons. This was a much desired feature, for example, a typical use case is a family: One person carries in the CWA "wallet" the certificates if his kids and his partner.

I can understand that for certain group of persons it is convenient to have multiple certificates on one app. However the security perspective is very important to an app like coronawarnapp, way more important than some wish for convenience.

Hence I assume you had a security check while discussing that feature, but have you also considered how easy it is to do fraud with coronawarnapp now and how well the fraud is hidden given our current check-system?

If not, I would suggest to re-evaluate the use-cost-ratio of this feature.

**Comment by dsarkar** [comment]
@schlichtanders All features are evaluated also in terms of threads, of course. Any report of misuse is taken seriously.

So you have knowledge of occurrences, where in public places, restaurants, etc. the Corona-Warn-App has been used to check certificates instead of the official verifier app, which is the CovPassCheck-App in Germany?

If so, please, drop us an email to corona-warn-app.opensource@sap.com.

**Comment by schlichtanders** [comment]
there seems to be a slight misunderstanding.

I myself confused the scan app initially which is how I realized that you can easily add other peoples certificates.
The thread is not about confusing the warnapp and the covpasscheck app. 

The thread is about people using this for document fraud. Please can you confirm you understood the thread of such fraud?

**Comment by Ein-Tim** [comment]
@schlichtanders 

Could you please elaborate a bit what you mean with "document fraud"?

**Comment by MikeMcC399** [comment]
@schlichtanders

Your question has some parallels to one I asked in https://github.com/corona-warn-app/cwa-website/issues/1995 "Can I legally use CWA to verify another person's 2G/3G status?". That question has not been answered yet.

**Comment by schlichtanders** [comment]
Let me summarize again the risk I see.

## Summary of Fraud thread I see

Currently in Germany, to the best of my knowledge, restaurants and co are not obliged to control passports in addition to certificates. Instead that is the responsibility of the police, however the police only very very rarely does additional checks (I've never seen them actually).

With the current feature of corona warnapp that you can add (multiple) certificates by just scanning other peoples certificate, it is very simple for people to fake a certificate in order to get access to some 2G or similarly protected event.

You can even copy another persons id without the other person recognizing it, just say "can I check you 3G certificate?".

## Additional Thoughts about the technical reason

Thinking about it, this has nothing to do with the ability to add multiple certificates. People who would do this fraud won't have a certificate and hence just copy the first one.

The issue is rather that you can copy from someone else's coronawarnapp. You don't need the official qr code you got from the doctor.

## Ideas how to make coronawarnapp more fraud-resistant

Two thoughts come to my mind about how to prevent this in future:
1. I guess currently the qr code from the doctor's certificate is just copied. Instead, if the qr code allows for it, you could add a tag "coronawarnapp" to it, and check when scanning whether you are reading from another coronawarnapp. If so, don't add it, but report that you need to use an official doctor's print.

2. If the qr code does not allow for adding a tag, you could still use the surrounding corona warnapp ui elements as a tag. That is much harder to do, but still because security is really important here, I would ask with insistence for implementing it.

**Comment by Ein-Tim** [comment]
@schlichtanders 

I understand the risk you see, however, this problem does not only affect the Corona-Warn-App but all wallet apps storing EU digital COVID certificates.

So if something like this should be implemented, then on EU level and not only in the Corona-Warn-App.

**Comment by jucktnich** [comment]
@schlichtanders ive actually independently from you Heard about people who thought the same way (checking codes with CWA), so if you don't mind, I would open an issue at the eu dcc repo.

**Comment by jucktnich** [comment]
Here is what i would post>

## Problems### 1 - good intentPeople try to verify DCCs with their wallet apps. This leads to an unwanted list of all visitors, their DoBs, vaccination status, etc.### 2 - bad intentPeople try to get valid DCCs to sell/donate(to harm the system) them on platforms like Telegram or RaidForums.## Solutions### only for problem 1Add a 'Do not Import' mark on DCCs displayed in the wallet app (wallet apps should get an export feature without this mark).This could look something like this:'''HC3-dni:payload'''### for both problemsWhen the certificate is created, the server creates a private/public key pair. The public key + the signature of the certificate get encrypted by the privat key of the server. The private key and the encrypted(public key + signature) are added at the end of the DCC.When the certificate is now scanned by a wallet app, and the wallet app should show the DCC, the wallet app encrypts an end of life date (like five minutes later or so) + the dcc (without the encrypted public key + private key of course). The app now adds the encrypted public key to the end like this:'''HC4-dni:certificate-private-key-encrypted(end of life date + dcc) + server-private-key encrypted(certificate public key + signature)'''An verifyer app now encrypts the certificate public key, uses it to decrypt the rest of the dcc, checks the end of life date and checks if the signature matches the dcc.

**Comment by schlichtanders** [comment]
> @schlichtanders
> 
> I understand the risk you see, however, this problem does not only affect the Corona-Warn-App but all wallet apps storing EU digital COVID certificates.
> 
> So if something like this should be implemented, then on EU level and not only in the Corona-Warn-App.

I full heartly disagree. If Corona-Wan-App can enhance the barrier against fraud in Germany by adding a tag like I described, this will still be a huge step towards credibility and against wide-spread fraud.

Even if you could use other apps, Corona-Warn-App is *the* app used in Germany, so adding a feature here will already have wide reach.

**Comment by schlichtanders** [comment]
> ### 2 - bad intent
> People try to get valid DCCs to sell/donate(to harm the system) them on platforms like Telegram or RaidForums.

nice one that you can even sell them. Haven't thought about that. The emotional barrier to buy a certificate is certainly higher than just copying one yourself.

Hence, I would definitely add the threat  that people can just use it for themselves fraudulently.

-------------------------

### 1 - good intent
People try to verify DCCs with their wallet apps. This leads to an unwanted list of all visitors, their DoBs, vaccination status, etc.

### 2 - bad intent I
People try to get valid DCCs to participate in events or locations where they are not allowed to join, or to join only with too big of extra effort.

### 3 - bad intent II
People try to get valid DCCs to sell/donate(to harm the system) them on platforms like Telegram or RaidForums.

**Comment by schlichtanders** [comment]
> ### for both problems
> When the certificate is created, the server creates a private/public key pair. The public key + the signature of the certificate get encrypted by the privat key of the server. The private key and the encrypted(public key + signature) are added at the end of the DCC.When the certificate is now scanned by a wallet app, and the wallet app should show the DCC, the wallet app encrypts an end of life date (like five minutes later or so) + the dcc (without the encrypted public key + private key of course). The app now adds the encrypted public key to the end like this:'''HC4-dni:certificate-private-key-encrypted(end of life date + dcc) + server-private-key encrypted(certificate public key + signature)'''An verifyer app now encrypts the certificate public key, uses it to decrypt the rest of the dcc, checks the end of life date and checks if the signature matches the dcc.

I haven't understood how this can help against the fraud

**Comment by Ein-Tim** [comment]
> I full heartly disagree. If Corona-Wan-App can enhance the barrier against fraud in Germany by adding a tag like I described, this will still be a huge step towards credibility and against wide-spread fraud.

> Even if you could use other apps, Corona-Warn-App is the app used in Germany, so adding a feature here will already have wide reach.

I disagree. Changing the content of the QR code can lead to wrong "Not valid" check when checking a German certificate with this extension with a check app from another country.
This HAS to be implemented on EU level.

**Comment by jucktnich** [comment]
@schlichtanders this would help, cause the certificate displayed by the wallet app is only valid for e.g. 5mins. There's no way to use the certificate after this timeperiod

**Comment by jucktnich** [comment]
https://github.com/ehn-dcc-development/hcert-spec/issues/107

**Comment by schlichtanders** [comment]
thank you for the explanation. Understood.

**Comment by schlichtanders** [comment]
> I disagree. Changing the content of the QR code can lead to wrong "Not valid" results when checking a German certificate with this extension with a check app from another country.

Hi. Sure if this would be the case, I would probably agree. It just seems an open question, and from my general technical experience, I guess that if it is possible to add one tag/mark, it is also possible to add another one, without them interfering with one another.

I really don't know how you come to the conclusion that this should be impossible. Please cite sources. 

> Also, we have to keep the signature in mind here. We can't add this the signature protected content of the certificate as this would break the signature.

I don't know about the technical site of things. Please elaborate what you think would go wrong when adding a custom tag/mark to the code. Borrowing from @jucktnich let's say we would use something like the mentioned '''HC3-dni:payload''' as the mark.

> Also, how would you implement this? Only for newly created certificates or via app update to already created once?

The approach I made is to stop reading certificates from Corona-Warn-App. That would naturally apply for new scans and not for old certificates.

**Comment by jucktnich** [comment]
@Ein-Tim @schlichtanders adding a tag in the JSON like @schlichtanders should work, since a new key value pair shouldn't affect readers not supporting it. But you'd need a more complex way transporting the code from the doctor into your CWA (which wouldn't work with not supporting apps) and it would only work on new codes.
My way would need supporting verifier apps, but not new certificates, old ones should still work.

**Comment by Ein-Tim** [comment]
@schlichtanders 

Don't get me wrong, I also see your problem. I just think it's a bit more complex and definitely needs alignment on EU level. I will follow along @jucktnich's proposal.

I'm no expert in this area, sorry 😅

**Comment by mlenkeit** [comment]
@schlichtanders thanks for creating the issue. We understand the problem and share your concerns. As some have stated already, such a change would need to be aligned on EU level.

**Comment by schlichtanders** [comment]
Hi @mlenkeit I am very surprised about these strong believes in impossibilities. Can you explain why you think there is no other way but EU Level?

**Comment by mlenkeit** [comment]
> Hi @mlenkeit I am very surprised about these strong believes in impossibilities. Can you explain why you think there is no other way but EU Level?

@schlichtanders it's definitely not impossible 😉 But the QR codes are supposed to be interoperable across EU member states. If Germany decided to change the way the data is represented on the QR codes, then apps from other EU member states wouldn't be able to scan they anymore and that would defy the idea of interoperability.

**Comment by bedo2991** [comment]
I personally got to see 2 people doing this to check certificates (either because of ignorance or because of laziness).
Even though this is more a social engineering issue (you should rather always check that your certificate really gets scanned with the CovPassCheck app), I'd be for making the importing of many different QR codes through the Corona Warn app more "difficult".

For example:
- Allow importing any number of certificates belonging to one person (checking the name/birthday)
- Limit the number of people (not certificates) who can be stored on 1 device
- Show a warning about the CovPassCheckApp / don't allow to import different persons within a given time frame.

**Comment by Ein-Tim** [comment]
Is this issue here still necessary? Or can we continue in https://github.com/ehn-dcc-development/hcert-spec/issues/107?

**Comment by schlichtanders** [comment]
> If Germany decided to change the way the data is represented on the QR codes, then apps from other EU member states wouldn't be able to scan they anymore and that would defy the idea of interoperability.

that is  depending on the technical implementation of the QR code and might be true or might not be true, but certainly is not self-explaining. Please understand that this kind of answer appears quite opinionated, surprising because I explicitly asked for background information instead of opinions. 

@mlenkeit See for instance your own explanation in the external comment https://github.com/ehn-dcc-development/hcert-spec/issues/107#issuecomment-972591119 - it has so much more technical detail. I like it very much. 

Maybe the reason is that as soon as you know so much about a topic, it gets hard to see what is enough self-explaining for others.

**Comment by schlichtanders** [comment]
> Is this issue here still necessary? Or can we continue in [ehn-dcc-development/hcert-spec#107](https://github.com/ehn-dcc-development/hcert-spec/issues/107)?

I am happy to stop discussing here, as the other discussion is much more to the point with concrete technical aspects.

Still, I would still leave this ticket open, because as of now the new approach is simply not implemented. If the new approach is implemented in corona-warn-app, that for me would be the natural time to close this ticket.

**Comment by mlenkeit** [comment]
As some of you might have spotted, an initial step to address this is taken with https://github.com/corona-warn-app/cwa-app-android/pull/4513 and https://github.com/corona-warn-app/cwa-app-ios/pull/3961, which will probably be part of 2.15. This will restrict the number of distinct people for which certificates can be added and there's a threshold for that, once exceeded, a warning is displayed whenever a certificate for a new person is scanned. Both threshold and maximum are subject to configuration and initial values are not yet finalized.

See also https://twitter.com/coronawarnapp/status/1468928375683227651

We are also evaluating further adjustments when scanning a certificate and we are of course considering the different suggestions that have been made here on GitHub. But as usual, no promises that any further changes will be done here or not.

**Comment by Ein-Tim** [comment]
FYI: https://github.com/corona-warn-app/cwa-app-android/pull/4502#issuecomment-990303506 says:

> this [= a "Do Not Import" flag in the QR code to prevent accidentally importing certificates again] is also coming soon , wait for it.

So seems like there is indeed a way to keep compatibility and still add this feature!

**Comment by Ein-Tim** [comment]
Sadly there was never any visible progress on a DNI flag, which @mtwalli _announced_ in https://github.com/corona-warn-app/cwa-app-android/pull/4502#issuecomment-990303506. 

@mlenkeit Can probably elaborate what blocked this feature or if it is till in the pipeline? 

Else I guess what we have now (the pop up asking to not use CWA to verify certificates from other persons) is the best solution.

**Comment by mlenkeit** [comment]
> Sadly there was never any visible progress on a DNI flag, which @mtwalli _announced_ in [corona-warn-app/cwa-app-android#4502 (comment)](https://github.com/corona-warn-app/cwa-app-android/pull/4502#issuecomment-990303506).
> 
> @mlenkeit Can probably elaborate what blocked this feature or if it is till in the pipeline?
> 
> Else I guess what we have now (the pop up asking to not use CWA to verify certificates from other persons) is the best solution.

@Ein-Tim there were concerns that such a technically compatible/non-breaking change to DCCs may conflict with the EU guidelines as to how much freedom member states have to deviate from the EU specification. That's why DNI flag is currently not pursued further and we have settle for the popup.

**Comment by Ein-Tim** [comment]
@mlenkeit 

Thanks for your feedback! In this case the pop-up is the best we have and this issue should probably be closed!
@schlichtanders

**Comment by larswmh** [comment]
Closing this issue as suggested, thanks for your contributions.

---
Corona-Warn-App Open Source Team
