### ISSUE TITLE
Retrieve list of revoced location-ids

### ISSUE THREAD

**Issue by chscheiber** [corona-warn-app/cwa-documentation#753]
## Your Question

* Discussion: https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/19#issuecomment-966123865
* Question:<br>
In above linked comment @oliver-steinbrecher mentions how the revoking of specific DCCs works for Germany. I am currently working on a custom DCC validation and I was not able to find the source for the list of location-ids. <br>Is this list of revoked location ids publicly available and if so where can I find it?

**Comment by arnebr** [comment]
Hi Christoph,
I looked in the CovPass Code, it seems that the the locations are hardcoded at the moment. 
 Please see: https://github.com/Digitaler-Impfnachweis/covpass-ios/blob/8ebcb284504c22d40235435cd609409163221ca9/Source/CovPassCommon/Sources/CovPassCommon/Repository/VaccinationRepository.swift#L360

Another open approach, but 4 months old and not in master, has been made via the business rules. https://github.com/eu-digital-green-certificates/dgc-business-rules-testdata/tree/feat/de-invalidation-rule/DE/IR-DE-0001

Hope it helps!

Greetings from Hamburg

**Comment by arnebr** [comment]
additional to my comment above, it seems that the invalidation is sending a push to affected users it's done via the BoosterNotification rules published here: https://distribution.dcc-rules.de/bnrules/b75771eb841a3e17205d590170ff30dd5998299cd67af72ce508f3d57062eda8

**Comment by chscheiber** [comment]
Thanks a lot for your valuable input @arnebr!

Not really the most elegant way to revoke certificates, but let's see how this will evolve.
