### ISSUE TITLE
Fehlercode 500

### ISSUE THREAD

**Issue by Katrinnn711** [corona-warn-app/cwa-documentation#755]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name:
- iOS/Android version:
- App version:

## Additional context

Fehlercode 500 beim registrieren eines PCR Tests

---
Internal Tracking ID: [EXPOSUREAPP-10665](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10665)

**Comment by thomasaugsten** [comment]
Passiert der Fehler beim registrieren oder beim aktualisieren des Testergebnisses

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Ich habe diesen Fehler bereits in https://github.com/corona-warn-app/cwa-testresult-server/issues/109 berichtet. Leider habe ich noch kein Feedback erhalten.

**Comment by Katrinnn711** [comment]
Beim registrieren. Da wird man ja gefragt ob man ein Testzertifikat anfordern will oder „Nein danke“.
Egal was ich von beiden drücke es kommt „Fehler 500 es ist ein Verbindungsfehler aufgetreten - Versuchen Sie es erneut“

**Comment by thomasaugsten** [comment]
@Katrinnn711 Hast du zwischen 12:30 und 14:15 versucht den Test das erste mal zu registrieren?
Wir werden morgen im Laufe des Tages daran arbeiten, dass du den Test registrieren kannst.

**Comment by Katrinnn711** [comment]
Tatsächlich ja. Gegen 13:15 Uhr wollte ich meinen Test registrieren. Supi, dann warte ich ab. Danke

**Comment by dsarkar** [comment]
@Katrinnn711 Guten Morgen, konnte der Test inzwischen registriert werden?

---
Corona-Warn-App Open Source Team

**Comment by Katrinnn711** [comment]
Leider nein. Der Fehler taucht weiterhin auf

**Comment by dsarkar** [comment]
@Katrinnn711 Danke für das Feedback. Wir leiten das weiter.

**Comment by Katrinnn711** [comment]
Bekomme ich denn trotzdem irgendwie heraus wie mein Testergebnis ist?

**Comment by Ein-Tim** [comment]
@Katrinnn711 

Wenn du bei deinem Hausarzt/deiner Hausärztin getestet wurdest kannst du mal dort anrufen.
Wenn bei einer Teststelle am besten mal auf deren Website nach einer Kontkatmöglichkeit suchen.

**Comment by thomasaugsten** [comment]
Eigentlich sollte das Testergebnis unabhängig von der CWA dir immer mitgeteilt werden

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-10665](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10665)

**Comment by Jo-Achim** [comment]
@Katrinnn711: 
Das Ergebnis meines **Schnelltests** hatte ich per E-Mail bekommen. 
Das Ergebnis meines **PCR-Tests** konnte ich entweder durch das "Scannen Sie diesen QR-Code" in die CWA bekommen **_oder_** 
gemäß eines 2. Blatts (das mir beim Test ausgehändigt wurde) über die Web-Seite [Diagnosticum](https://www.diagnosticum.eu/) bzw. [https://www.diagnosticum.eu/fuer-patienten/covid/](https://www.diagnosticum.eu/fuer-patienten/covid/) mit Hilfe von Auftragsnummer oder dem 43-stelligen Code unter dem QR-Code. 
Möglicherweise war es bei Dir aber ein anderer Dienstleister.

**Comment by Katrinnn711** [comment]
Danke, ich probiere es mal. 
Meinen Arzt habe ich kontaktiert. Dort liegt noch kein Ergebnis vor und ich werde auch nicht informiert .. um 13 Uhr haben die nämlich Feierabend 😒
Mal abwarten!

**Comment by Katrinnn711** [comment]
Habe mein Ergebnis jetzt über die App „mein Laborergebnis“ erhalten. Gott sei Dank endlich negativ allerdings funktioniert das über die CWA immer noch nicht.

**Comment by dsarkar** [comment]
@Katrinnn711 Danke erst mal für die Rückmeldung. Wir geben verfolgen das Problem weiterhin.

**Comment by thomasaugsten** [comment]
@Katrinnn711  Can you please retry the scanning

**Comment by Katrinnn711** [comment]
Funktioniert! Danke!

**Comment by dsarkar** [comment]
@Katrinnn711 Danke für das Feedback.

**Comment by Ein-Tim** [comment]
@dsarkar I suggest to close this issue now.

**Comment by MikeMcC399** [comment]
It seems that this issue has been resolved and should be closed.
