### ISSUE TITLE
How many test results / -certificates can CWA process for one person at the same time?

### ISSUE THREAD

**Issue by Jo-Achim** [corona-warn-app/cwa-documentation#756]
I only remember one quick test result and one PCR test result / certificate at the same time!?

If that is correct: Against the background of the tightening of the corona protective measures, for example towards 2G + (i.e. recovery or vaccination plus test) or the requirements for daily (quick) tests, the CWA must be able to handle several (same) tests at the same time.
Or be set so that a newer test of the same type automatically replaces the older test.

## Your Question

Is it given that the CWA can handle multiple test results / test requirements (rapid or PCR tests) for one person at the same time?
Or is it ensured that the above scenarios can be handled by the CWA?

**Comment by MikeMcC399** [comment]
This is also related to open issues 
https://github.com/corona-warn-app/cwa-website/issues/1626
https://github.com/corona-warn-app/cwa-wishlist/issues/518

**Comment by Ein-Tim** [comment]
@Jo-Achim 

The answer is in https://www.coronawarn.app/de/faq/#rat_multiple_rat (DE) and https://www.coronawarn.app/en/faq/#rat_multiple_rat (EN).

**Comment by Jo-Achim** [comment]
Thanks for your information.

But the links are mostly about tests from family members to be saved on a (main) owner's smartphone. So for example for his children etc. Right?

I was more concerned with the main owner of the phone, who may soon have to have several tests carried out a week or even daily tests - and who sensibly wants or needs to get the test results into the CWA.

**Comment by Ein-Tim** [comment]
This issue should be closed now, see [Corona-Warn-App Version 2.21 now allows test management for family members](https://www.coronawarn.app/en/blog/2022-04-19-cwa-2-21/).
