### ISSUE TITLE
Confusing English explanation for trend icons

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#757]
## Technical details

- App version: 2.13.3 and later versions up to [release/2.15.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.15.x)

## Describe the bug

The English language informational text in "Explanation of Statistics" shown above the trend icons "The following trends can be shown:" sounds like these are the only icons which can be shown and this is not true.

The German language text "Beispiele für die angezeigten Trends:" is much clearer that the icons are only examples.

English | German
--- | ---
![Trend EN](https://user-images.githubusercontent.com/66998419/143017307-da810306-a291-4b21-b62f-04cbee5fac24.png) | ![Trend DE](https://user-images.githubusercontent.com/66998419/143017316-115686d2-ca93-41d8-aeb9-396c53bbd6ae.png)
![Vaccination EN](https://user-images.githubusercontent.com/66998419/143017232-afc701f6-423e-4a3a-a72a-18a61641b077.png) | ![Vaccination DE](https://user-images.githubusercontent.com/66998419/143017274-e2c21d3c-3a0c-47ee-805d-4934fa8a161f.png)

## Steps to reproduce the issue

Using Android, with locale set to English:

1. Open CWA
2. On Status screen scroll down to "7-Day Incidence"
3. Scroll right to "Vaccine Doses Administered"
4. Note the trend icon
5. Tap the "i" icon to display information text
6. Scroll down to the "Trend" section
7. Note the explanation concerning the trend icons

## Expected behavior

Present accurately understandable information for trend icons in English.

For "Vaccine Doses Administered" if the trend is upwards then a green upwards-arrow is shown, however the information text in English seems to contradict that a green upwards-arrow could be shown.

## Possible Fix

Translate the German text "Beispiele für die angezeigten Trends:" into English as:

"Examples of trends shown:"

instead of:

"The following trends can be shown:"

This affects the string `statistics_explanation_trend_icons_title` in `Corona-Warn-App\src\main\res\values\strings.xml` in Android. The same text is also used in iOS.

## Additional context

This is a follow on from the issue https://github.com/corona-warn-app/cwa-documentation/issues/659 "Wrong arrow explanation for vaccination stats" and the https://github.com/corona-warn-app/cwa-documentation/issues/659#issuecomment-889061159.

---
Internal Tracking ID: [EXPOSUREAPP-10831](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10831)

**Comment by larswmh** [comment]
Hi @MikeMcC399, thanks for your report. We have created an internal ticket and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-10831](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10831)

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
- This issue was resolved by PR https://github.com/corona-warn-app/cwa-app-android/pull/4497 in Android [release v2.15.1](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.15.1) released on Dec 20, 2021.

The suggested text "Examples of displayed trends" is now used.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Would you like me to cross check under iOS?

**Comment by MikeMcC399** [comment]
@Ein-Tim
You are always welcome to check the state on iOS. I will leave the issue open for the moment, although I assume the text was also changed by the translation team on iOS as well.

**Comment by MikeMcC399** [comment]
Text was changed for iOS as seen in repository.
