### ISSUE TITLE
Can CWA (CovPass / CovPassCheck) handle booster vaccinations with another vaccine (cross vaccination)?

### ISSUE THREAD

**Issue by Jo-Achim** [corona-warn-app/cwa-documentation#758]
## Your Question
On the occasion of the current situation / questions it would be interesting whether the CWA can basically use a different vaccine as a booster compared to the basic immunization? Keyword: (3 of 3).

It would also be interesting to know whether cross-vaccination in other EU countries, documented with the CWA or CovPass, is recognized?

## Background to the questions:
The reasons for these questions are the above-mentioned 'current situation / questions' as well as obviously existing studies that show that basic immunization (2x vaccine X) plus a booster with vaccine Y leads to better overall immunity.
Source: https://www.morgenpost.de/vermischtes/article233668453/corona-imendung-kreuzimörderung-impfstoff-booster.html

In the frame under the heading "Booster vaccinations: cross vaccination or the same vaccine?":
> The booster vaccination must now pick up speed. What works best? Switching works best! Moderna for BionTech vaccinated, BionTech for Moderna vaccinated, and Moderna for J&J vaccinated pic.twitter.com/TKYp8A4Gxv
>     - Karl Lauterbach (@Karl_Lauterbach) October 22, 2021
>
> Image in the Twitter link: 
> 
![Kreuz-Booster-Impfungen](https://user-images.githubusercontent.com/21124877/143052796-8102d66e-3737-493f-8d4b-ec30ae864fb8.jpg)

**Comment by Jo-Achim** [comment]
Oh, thank you, @Ein-Tim. Question answered.
I remembered problems with different vaccines.

But ok, then I'll close again immediately.

**Comment by Ein-Tim** [comment]
> I remembered problems with different vaccines.

Do you know which problems? CWA/CovPass don't do any kind of check whether one person received the same vaccine for all vaccinations, or similar. They are just storing the certificate as it was issued.

**Comment by Jo-Achim** [comment]
Wasn't there a problem with "first vaccination with Astra", "second vaccination with mRNA"? Or was it "Janssen" (Johnson & Johnson)?
It may be that at that time it was only about the correct numbering of the certificates; so 1 of 2 and 2 of 2.
In principle, this would of course also be possible with cross vaccinations if the booster (3 of **_3_**) does not match the previous scheme (1 of **_2_** and 2 of **_2_**).

**Comment by Ein-Tim** [comment]
@Jo-Achim 

Do you refer to the problem which is described in this FAQ entry: https://www.coronawarn.app/en/faq/#vac_booster_jj

**Comment by Jo-Achim** [comment]
Yes, the problem was probably in the back of my mind.
Because with regard to my last answer with vaccinations 2 out of **_2_** and now 3 out of **_3_**, a possibly existing problem should not be limited to cross vaccinations, but also be for the booster vaccination with the same vaccine.

(Otherwise we'll see that soon.)
