### ISSUE TITLE
Bluetooth connection on Android and iOS

### ISSUE THREAD

**Issue by EvilWatermelon** [corona-warn-app/cwa-documentation#759]
## Your Question

Why is it not necessary to have bluetooth active on iOS but on Android it needs to be active?

**Comment by Ein-Tim** [comment]
@EvilWatermelon What leads you to the conclusion that you don't have to activate Bluetooth on iOS? CWA needs Bluetooth to work, try switching it out via settings. If you press on the Bluetooth symbol in the iOS control center, you're not actually switching off Bluetooth, for more information see https://www.coronawarn.app/en/faq/#ios_logging_bt

**Comment by EvilWatermelon** [comment]
Ah okey I didn't know that Bt is still active in system settings.

**Comment by jucktnich** [comment]
See also here:
![image](https://user-images.githubusercontent.com/73582096/143263413-3e8c0b52-3979-4e31-b905-759dc69b0380.jpeg)
