### ISSUE TITLE
Repository update to Node v16 (or lock to Node v14)

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#763]
## Describe the issue

This repository uses GitHub `ubuntu-latest` which is planned to update by default to nodejs `lts/gallium` (node v16.13.0, npm v8.1.0) on Nov 29, 2021.

This is not a breaking change for the [cwa-documentation](https://github.com/corona-warn-app/cwa-documentation) repository, however the current [package-lock.json](https://github.com/corona-warn-app/cwa-documentation/blob/master/package-lock.json) contains  `"lockfileVersion": 1` which is not compatible with npm v8 which uses `"lockfileVersion": 2`.

The repository [cwa-website](https://github.com/corona-warn-app/cwa-website) is however constrained **not** to migrate to node v16. It must stay with node v14 due to compatibility issues with npm packages used in the website repository.

### Allow default to change to node v16

If no action is taken to set the node version for [cwa-documentation](https://github.com/corona-warn-app/cwa-documentation), then it will automatically update to v16. In this case `package-lock.json` would need to be rebuilt and committed to the repository.

The disadvantage would be that anybody working on both the repositories [cwa-documentation](https://github.com/corona-warn-app/cwa-documentation) and [cwa-website](https://github.com/corona-warn-app/cwa-website) would need to use and switch between different node versions v14 and v16.

### Lock cwa-documentation to current node v14

Locking [cwa-documentation](https://github.com/corona-warn-app/cwa-documentation) to node v14 would give it the same environment as [cwa-website](https://github.com/corona-warn-app/cwa-website). This would make it much simpler for anybody contributing to both repositories.

## Suggested change

Use the option to lock the [cwa-documentation](https://github.com/corona-warn-app/cwa-documentation) to current node v14 using the Long Term Support version `lts/fermium`.

Add
```
- uses: actions/setup-node@v2
  with:
      node-version: 'lts/fermium'
```
to [checks.yml](https://github.com/corona-warn-app/cwa-documentation/blob/master/.github/workflows/checks.yml) in a similar way as was done in PR https://github.com/corona-warn-app/cwa-website/pull/2106 for the [cwa-website](https://github.com/corona-warn-app/cwa-website) repository.

## Additional context

See also https://github.com/corona-warn-app/cwa-website/issues/2098 "GitHub new default Nodejs 16 will break deploy starting Nov 29, 2021" and PR https://github.com/corona-warn-app/cwa-website/pull/2106.

GitHub Announcement in https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md.

**Comment by MikeMcC399** [comment]
I have opened PR #764 to lock the repository to v14 which will override the planned default change that is supposed to take effect on or after Nov 29, 2021.

I think this makes sense, but please give feedback if there are reasons not to do this.

It seemed to work well for the cwa-website repository in any case.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for pointing out the issue. Yes, I agree with you, it will be more practical to lock it to the same node v14 for both repositories.

**Comment by MikeMcC399** [comment]
@dsarkar / @mtb77 
Thanks to you both for reviewing and merging PR #764 which has resolved this issue!

## Verification

Test push logged in https://github.com/corona-warn-app/cwa-documentation/actions/runs/1530970425 succeeded and confirmed correct operation.

```
Run actions/setup-node@v2
  with:
    node-version: lts/fermium
    always-auth: false
    check-latest: false
    token: ***
Attempt to resolve LTS alias from manifest...
Found in cache @ /opt/hostedtoolcache/node/14.18.1/x64
```

and later in the logs:

```
Run npm install

> spawn-sync@1.0.15 postinstall /home/runner/work/cwa-documentation/cwa-documentation/node_modules/spawn-sync
> node postinstall

added 510 packages from 262 contributors and audited 510 packages in 7.251s

91 packages are looking for funding
  run `npm fund` for details

found 10 vulnerabilities (9 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

where there is no longer an issue of `npm WARN old lockfile` being reported.

**Comment by dsarkar** [comment]
@MikeMcC399 Many thanks to you, also for the final feedback.
