### ISSUE TITLE
Die Schnelltest Karte für Bonn stimmt vorne und hinten nicht

### ISSUE THREAD

**Issue by ChristopherG84** [corona-warn-app/cwa-documentation#769]
Laut der Karte für Schnelltest die in der App Verlinkt sind, gibt es für "53173, Bonn - Bad Godesberg" 3 Testzentren:
https://map.schnelltestportal.de/
Mindestens eines davon ist mitlerweile zu.

Laut der Karte der von der Internetseite der Stadt Bonn, gibt is 10:
https://www.bonn.de/themen-entdecken/gesundheit-verbraucherschutz/informationen-zu-coronavirus-testungen.php
Die Karte von Bonn ist definitiv Vertrauenswürdiger.

Irgendwo läuft hier etwas bei der Synchronisation ganz gewaltig schief. So schief, es wäre besser es gäbe den Link überhaupt nicht! Dann würde ich nämlich auf google suchen und tatsächlich die brauchbare Karte finden - statt mich von dem Link in der App in die Irre führen zu lassen.

![Corona Warnapp Karte](https://user-images.githubusercontent.com/16683863/143891692-0f7b9f38-32f4-44ae-a290-09f387e65f0f.JPG)
![Stadt Bonn Karte](https://user-images.githubusercontent.com/16683863/143891711-7143c01c-512b-4be3-9b2b-0838d90fb1cb.JPG)

**Comment by Ein-Tim** [comment]
@ChristopherG84 

1. Auf map.schnelltestportal.de werden, soweit ich weiß, nur Teststellen angezeigt, die an die CWA angeschlossen sind. So kann es zu dieser Diskrepanz zwischen map.schnelltestportal.de und der Seite der Stadt Bonn kommen.
2. Wenn eine Teststelle nicht mehr existiert, kannst du diesen Fehler wie folgt direkt auf der Seite melden:
	1. Klicke auf die Teststelle
	2. Klicke auf "Fehler melden" 
	3. Klicke auf "Teststelle geschlossen"

**Comment by dsarkar** [comment]
@ChristopherG84 Siehe auch den FAQ Artikel https://www.coronawarn.app/de/faq/#test_result_issues.
CC @Ein-Tim

**Comment by Ein-Tim** [comment]
There was no visible progress on this issue in the last 5 months, so I guess it staled. Please provide an update to let us know how you plan to proceed here.

**Comment by Ein-Tim** [comment]
I recommend to close this issue in favour of the issue mentioned by @MikeMcC399 above.

**Comment by dsarkar** [comment]
@ChristopherG84 Thanks again for reporting. As suggested by @MikeMcC399 and @Ein-Tim, the proper place to discuss and report issues regarding the Schnelltestportal is the repository mentioned here https://github.com/corona-warn-app/cwa-documentation/issues/769#issuecomment-1189299553. We will close this issue in favour of https://github.com/corona-warn-app/cwa-map-public-frontend/issues/19, please, report/follow there. Thanks again. Best wishes, DS


---
Corona-Warn-App Open Source Team

Issue monitored in Internal Tracking ID: [EXPOSUREAPP-13535](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13535)
