### ISSUE TITLE
PRIO: Registering tests is not possible

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#772]
We're attempting to register a RAT in the app, this fails with Internet connection offline, although the phone is connected to the internet.

Same for PCR tests

---
Internal Tracking ID: [EXPOSUREAPP-10936](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10936)

**Comment by Ein-Tim** [comment]
@dsarkar One moment.

**Comment by Ein-Tim** [comment]
Android: 
![image](https://user-images.githubusercontent.com/67682506/144894218-862278ca-e610-4ef9-9695-272bed2cee76.png)

iOS:

**Comment by dsarkar** [comment]
@Ein-Tim Many thanks!

**Comment by Ein-Tim** [comment]
This issue is fixed for me. I'll leave it open for clarification and a detailed comment what happened.

**Comment by Ein-Tim** [comment]
@mlenkeit 

Can we expect a short statement from your side or the team responsible for the server why the incident happened and what will be done to prevent it in the future? 

This would be great, thank you!

**Comment by Ein-Tim** [comment]
Seems like we won't get an explanation for this. Closing.
