### ISSUE TITLE
Are new event IDs downloaded if exposure logging is turned off?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#773]
## Your Question
If the user has check ins and deactivates exposure logging, are new event IDs still downloaded or is this stopped, just as the download of DKs?
I did not find an answer to this question in the documentation reg. the event-registration.

**Comment by viisauksena** [comment]
by active Testing we can confirm that qr code checkin are testet against downloaded risk-contacts.
but the main window stays white - even while the text changed to - you have x risk contacts.

expected behaviour would be that the cwa turns red as usual , which would be normal (and correct) behaviour in this case.

**Comment by Ein-Tim** [comment]
@viisauksena 

I can confirm this, screenshot follows (tested on Android device).

@thomasaugsten what do you think?

@dsarkar can we get this mirrored to JIRA?

**Comment by Ein-Tim** [comment]
Screenshots (Android):

![image](https://user-images.githubusercontent.com/67682506/149492827-5fb4b7fe-6a3a-4991-b9f8-527200e9081b.jpeg)!

[image](https://user-images.githubusercontent.com/67682506/149492836-80e899d8-cc2e-4df5-bbb4-e23b2a1b909b.jpeg)

**Comment by Ein-Tim** [comment]
@dsarkar Could you please mirror this issue to JIRA?

**Comment by Ein-Tim** [comment]
This issue was opened more than 1 year ago and wasn't answered. The question itself is still valid, though. But, as the CWA project went into ramp-down mode, I'm not interested in an answer to this question anymore. I'm therefore closing this issue now.
