### ISSUE TITLE
Booster recommended although already added in App

### ISSUE THREAD

**Issue by idoodler** [corona-warn-app/cwa-documentation#774]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 13 Pro
- iOS/Android version: 15.2 RC
- App version: 2.14.1

## Describe the bug

I have a certificate for my first two vaccinations digitalized by a local pharmacy. I also have a certificate for my booster shot (8 days ago) issued by my local vaccination center. I first was confused that i have two certificates and that those aren't merged, but anyway.

Today morning I checked the app and saw a booster recomendation on my first certificate. It states that no booster can be found for me. As this app is very privacy concerned I assume it is checking all my local certs. This check did not work in my case.

## Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/6825153/145351364-bf542faf-804d-45ff-93a0-b0f8ac64deb8.png)

## Expected behaviour
I would expect that the certificates get merged, or that i only get shown the "more valuable" one. Also the check should have seen my booster certificate

## Additional context
The first cert shows two out of two. The second one shows three out of three.

**Comment by idoodler** [comment]
I just noticed that my name is written the wrong way around:/ maybe thats the issue here.

![image](https://user-images.githubusercontent.com/6825153/145352299-3a25b68c-0e86-4449-a446-346bf8c2517c.jpeg)

**Comment by Ein-Tim** [comment]
@idoodler 

Yes the name is the problem. See also https://github.com/corona-warn-app/cwa-wishlist/issues/705

**Comment by idoodler** [comment]
Thanks, I will at my local vaccination center to correct my certificate.

**Comment by dsarkar** [comment]
@idoodler Thanks for participating here. @Ein-Tim Thanks for clarifying the issue!

---
Corona-Warn-App Open Source Team

**Comment by idoodler** [comment]
Just FYI I simply went to a pharmacy, showed them my national ID and the yellow WHO vaccination booklet and I got a correct certificate. 

Thanks for your great work 👍
