### ISSUE TITLE
What does the CWA show if multiple later positive tested people were met on the same day?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#779]
## Your Question
* Question: If I met multiple later positive tested persons on the same day & they then share their infection through the CWA, what does my app show? "Exposures on 1 day with increased risk"? 
If yes, is there a way to distinguish between an exposure with increased risk because you met one later positive tested person & you met multiple later positive tested people?

**Comment by mlenkeit** [comment]
> * Question: If I met multiple later positive tested persons on the same day & they then share their infection through the CWA, what does my app show? "Exposures on 1 day with increased risk"?

@Ein-Tim yes, CWA will show "Exposures on 1 day with increased risk". There is no way to reliably count the number of distinct people with ENF v2, which is why we deliberately decided not to show any such numbers...

>   If yes, is there a way to distinguish between an exposure with increased risk because you met one later positive tested person & you met multiple later positive tested people?

... so the answer is no 😉

**Comment by Ein-Tim** [comment]
@mlenkeit 

Okay, thanks for the fast answer!
