### ISSUE TITLE
DCC Ticketing: What data is shared with the server in the process?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#780]
## Your Question
When the newly introduced DCC ticketing feature is used, I've understand it this way:
1. User scans a QR-Code
2. App recognizes the QR-Code, knows from whom (which organization issued the QR-Code) & downloads the rules from this organization
3. The certificate is locally checked against the rules & **only** the result is send to the issuer of the QR-Code.

During this whole process, CWA **does not** send any personal details (like the name or date of birth) to any central server, or?

**Comment by MikeMcC399** [comment]
@Ein-Tim

There is some information about this in the updated privacy notice for CWA 2.15.

- https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf (EN)
- https://www.coronawarn.app/assets/documents/cwa-privacy-notice-de.pdf (DE)

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thanks for the pointer! I read the paragraphs 6k and 5k, and am still not 100% sure what data exactly is transferred to the server and what is only processed locally. 

Maybe you know?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
I only know what's in the document. Sorry.

**Comment by Ein-Tim** [comment]
No reason to say sorry @MikeMcC399!

Maybe @thomasaugsten could shine a light on this?

**Comment by thomasaugsten** [comment]
You can find a detailed Description under "Buchungsdaten" in the privacy notes.
The flow is you book a ticket and ticket creator need a proof you full-fill the 3G rules on this ticket date. 
The ticket creator provides a QR-Code with a booking id and a validation service. 
You will scan the qr-code and the CWA will check if this ticket creator and the validation service is whitelisted via RKI.
If yes you have to consent the validation, then you will see the requirements (3G, 2G) and name of the ticket owner via the validation service. You can select a certificate and submit this certificate to the validation service. 
The validation service will check the requirements against the certificate without persisting any data. 
After the check the validation service will return to the ticket creator 3G full-filled yes or no for this date without any additional information.

**Comment by raphaelm** [comment]
Does the validation service compare the name received from the ticketing service with the one from the certificate? How does this matching work? For example, I have certificates with different subsets or spellings of my given names. Currently, without this feature, this comparison is always done by a human it never was a problem, but it seems like ot could be one now?

**Comment by thomasaugsten** [comment]
The validation service check the ICAO/maschinenlesbaren Name of the certificate and the provided name by the ticketing service. 
If the name on your test/vaccination certificates are not matching with your ticket name no auto validation is possible you will fallback to non automated process provided by the ticketing service.

It is similar to process when your passport name is not matching with your boarding pass name

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Okay, thanks for the answer, so, the validation service get's my certificate and checks whether the requirements are met. 

Then, after the check, the result is submitted to the ticket creator. The result is either YES all requirements are met or NO, there are requirements which weren't met.

Correct?

**Comment by Ein-Tim** [comment]
@raphaelm 

The spelling thing you mention is definitely a problem, see https://www.coronawarn.app/en/blog/2021-12-20-cwa-2-15/, which says:

"Users should make sure that the name in the certificate they want to use for verification is EXACTLY the same as the name they entered in the booking system. If this is not the case, they will not be able to select the corresponding certificate in the Corona-Warn-App.

For example, if users have entered their first and middle names in their certificate, they should also enter both names when booking tickets. If they only enter one name, the CWA will not be able to recognize that it is the same person."

**Comment by Ein-Tim** [comment]
@thomasaugsten 

In https://www.coronawarn.app/en/blog/2021-12-20-cwa-2-15/ it says:
"Please notice: the certificates remain on the user's own smartphone and are not stored in the validation system at any time."

This does not seem to be in accordance with your answer, or? The certificate (data) leaves the phone and is send to the validation server, or?

**Comment by Ein-Tim** [comment]
Okay no wait, the blog is just really confusing. 

First it says: "For this purpose, it [=the certificate] is temporarily transmitted in encrypted form to the validation service."

and then, just under the picture, it says: 
"Please notice: the certificates remain on the user's own smartphone and are not stored in the validation system at any time."

What's the validation system? It's not the validation service, or? Is it the system the validation service rund on?

**Comment by mlenkeit** [comment]
> What's the validation system? It's not the validation service, or? Is it the system the validation service runs on?

@Ein-Tim yes, it's the validation service.

---

The official [specification from the EU](https://ec.europa.eu/health/sites/default/files/ehealth/docs/covid-certificate_traveller-onlinebooking_en.pdf) that was implemented is publicly available. Note that only Chapter 3 is implemented by CWA. Other Chapters are primarily relevant for verifier apps. Also note that CWA has implemented additional security mechanisms that are not explicitly mentioned in the spec, such as allowlists or certificate pinning.

**Comment by Ein-Tim** [comment]
@mlenkeit 

Then the blog post is really confusing. I guess this will be improved soon?

Thanks for the reference to the EU documentation, I will take a look at Chapter 3 later on.

**Comment by MikeMcC399** [comment]
@mlenkeit 

Would it be possible to get the [Documentation README](https://github.com/corona-warn-app/cwa-documentation/blob/master/README.md) updated to include a list of external specifications which CWA is following, such as the [Guidelines on the use of Digital Covid Certificates in traveller and online booking scenarios](https://ec.europa.eu/health/sites/default/files/ehealth/docs/covid-certificate_traveller-onlinebooking_en.pdf) which you quoted?

Ideally the [Solution Architecture document](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md) would cover all these aspects.

**Comment by thomasaugsten** [comment]
The blog post has now an improved wording.

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Thanks, my initial question has been answered, so closing here.

**Comment by vaubaehn** [comment]
Related/Cross-reference:
https://github.com/corona-warn-app/cwa-app-ios/pull/3847#issuecomment-970460742
