### ISSUE TITLE
How to implement the new check-in function for booking tickets

### ISSUE THREAD

**Issue by derweili** [corona-warn-app/cwa-documentation#781]
In the latest blog article, a new check-in function for booking tickets is described.
The blog article shows this new process from the end-users perspective.

I would like to use this function for my event online shop, so I searched the documentation on how to implement this functionality, but I did not find any information about this.

Where can I find information about this?

---
Internal Tracking ID: [EXPOSUREAPP-11110](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11110)

**Comment by Ein-Tim** [comment]
Hi @derweili 

Does https://www.t-systems.com/de/en/newsroom/news/corona-validation-service-475486 help you?

**Comment by MikeMcC399** [comment]
@derweili 

https://github.com/corona-warn-app/cwa-documentation/issues/780#issuecomment-998553495 quoted the document [Guidelines on the use of Digital Covid Certificates in traveller and online booking scenarios](https://ec.europa.eu/health/sites/default/files/ehealth/docs/covid-certificate_traveller-onlinebooking_en.pdf) saying that Chapter 3 is implemented in CWA. That may be useful as background reading only.

I also raised this question in 
- https://github.com/corona-warn-app/cwa-website/issues/2218

**Comment by dsarkar** [comment]
@derweili Thanks for raising this issue.
Internal Tracking ID: [EXPOSUREAPP-11110](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11110)

---
Corona-Warn-App Open Source Team

**Comment by derweili** [comment]
Thank you all for this information. So I suspect there is currently no public validation service, unlike the one for event OR codes (https://www.coronawarn.app/de/eventregistration/), right?

As I understand the App only implements the Wallet/Client Functionality described in chapter 3 (see @MikeMcC399 comment) while the the validation service is a payed feature build by t-systems (@Ein-Tim )?

Is this correct?

**Comment by MikeMcC399** [comment]
@derweili

The German FAQ section [Zertifikatprüfung bei Buchungen](https://www.coronawarn.app/de/faq/#val_service) was updated today and the article [Fragen und Antworten zur Zertifikatsprüfung bei Ticketbuchungen](https://www.coronawarn.app/de/faq/#val_service_basics) includes the text:

"**Welche Unternehmen bieten bereits einen DCC-Validierungsservice an?**

Erster Anbieter ist T-Systems. Das Modell ist bewusst marktoffen gestaltet und lässt mehrere verschiedene Anbieter zu. Die Überprüfung von Zertifikaten leistet einen wichtigen Beitrag im Kampf gegen die Pandemie. Mit Wettbewerb wollen wir eine möglichst schnelle Verbreitung von Validierungs-Diensten unterstützen."

This doesn't however provide any contact information or instructions about how to integrate with it.

**Comment by GisoSchroederSAP** [comment]
I'm going to clarify the contact details for participation and integration of the validation service. The results will then be added to the existing communication in FAQ and/or blog.

**Comment by MikeMcC399** [comment]
@GisoSchroederSAP 

I see that there was an update to the blog https://www.coronawarn.app/en/blog/2021-12-20-cwa-2-15/ today:

**Important update from January 10, 2022:** The Europe-wide requirements for online verification services have already been in place since October 2021. In Germany, **no provider of an online verification service has been approved yet.**

**Comment by Ein-Tim** [comment]
FYI: https://github.com/corona-warn-app/cwa-website/issues/2218#issuecomment-1094809124 

There is no validation service provider available anymore, which makes this question de-facto obsolete. 

The community managers (@dsarkar) should decide how to proceed with this issue, I suggest to close it.

**Comment by larswmh** [comment]
Closing as suggested, internal ticket is set to `obsolete`.
