### ISSUE TITLE
Prepare for EU change reg. booster vaccination certificates after 1/1 basic vaccination (2/1) which will come into effect on 01.02.2022

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#784]
### This is an informational issue.

---

The EU decided that booster vaccinations should be certified as 2/1 starting from 01.02.2022 instead of, how it's handled currently, 2/2. 

See https://ec.europa.eu/commission/presscorner/detail/en/ip_21_6837 which says:

"In addition, today the Commission has also adapted the rules for the encoding of vaccination certificates. This is necessary to ensure that vaccination certificates showing completion of the primary series can always be distinguished from vaccination certificates issued following a booster dose.

Boosters will be recorded as follows:

- 3/3 for a booster dose following a primary 2-dose vaccination series.
- **2/1 for a booster dose following a single-dose vaccination or a one dose of a 2-dose vaccine administered to a recovered person**." 

CWA should be adapted so that it works properly with those certificates (i.e. not show "Impfung 2 von 1", the validity check for Germany needs to be adjusted, etc.).

This is an informational issue, feel free to move it to the wishlist or wherever you think it fits best.

---
Internal Tracking ID: [EXPOSUREAPP-11143](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11143) obsolete
Internal Tracking ID: [EXPOSUREAPP-11274](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11274) iOS
Internal Tracking ID: [EXPOSUREAPP-11272](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11272) Android

Internal Tracking ID: [EXPOSUREBACK-2030](https://jira-ibs.wbs.net.sap/browse/EXPOSUREBACK-2030)
Vaccination Rule VR-DE-0003: 2of1 Biontec not valid immediately

**Comment by larswmh** [comment]
Thanks for your report @Ein-Tim. Internal Tracking ID: [EXPOSUREAPP-11143](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11143)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
PR 2 

iOS: https://github.com/corona-warn-app/cwa-app-ios/pull/4101

**Comment by Ein-Tim** [comment]
CWA has been made ready for this change in version 2.17. Closing this issue.

**Comment by shurkanTwo** [comment]
Hey @Ein-Tim,
so the CWA is only made ready for this change but will not yet support the 2/1 notation in version 2.17?

**Comment by Ein-Tim** [comment]
@shurkanTwo Sorry, I wasn't clear. Yes, it supports these types of certificates in version 2.17!

**Comment by shurkanTwo** [comment]
@Ein-Tim 
that's awesome, thx!
I just wanted to make sure, also because this adjustment is not mentioned in the news, i.e. here: https://www.bundesregierung.de/breg-de/suche/corona-warn-app-version-2-17-2002274

Will this also work for certificates that have been issued already?

**Comment by Ein-Tim** [comment]
@shurkanTwo 

Certificates which have been issued as 2/2 will have to be reissued from a pharmacy or a doctor as a 2/1 certificate. There is no automatic reissuing process in the app.

**Comment by thomasaugsten** [comment]
But the process is planned in the apps no need to go to the pharamacies.
https://github.com/Digitaler-Impfnachweis/certification-apis/pull/219

**Comment by shurkanTwo** [comment]
@Ein-Tim 
okay good to know. It's near to impossible to find any information on the internet regarding this. Are the pharmacies able to do this already? Last time I asked one about 3 weeks ago, they were not yet.

@thomasaugsten 
That sounds like a nice feature! Do you know already when it will be available in the app approx.?

**Comment by Ein-Tim** [comment]
> Are the pharmacies able to do this already?

Yes, since yesterday the updated schema is available in the issuance portal.

**Comment by Ein-Tim** [comment]
@mlenkeit 

I'm reopening here as when checking a 2/1 certificate against validity in Germany this leads to an error. The rules need to be updated.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

The [Twitter link](https://twitter.com/KlausThaler8/status/1489969924768518149?s=20&t=ltDstdVg8dJVr7QQKHiHwA) which you posted shows rules for Spain being tested, not rules for Germany.

If this is a problem for rules from Spain it would be better to have a separate issue opened.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thanks! I asked the user to also test for Germany.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Okay, for Germany there was no problem with 2/1 but there is another problem: https://twitter.com/KlausThaler8/status/1490327234036613122?s=20&t=rORBZ9N54fitPtTZbsPpLQ

2/1 can either mean the end of the "Grundimmunisierung" (one vaccination after J&J) or Booster after vaccination after recovery.
Thus, the German check currently shows a waiting time of 14 days in this case.

**Comment by shurkanTwo** [comment]
@vaubaehn 
I can confirm, that 3/1 is the booster certificate that you get at a pharmacy when recovered + 1 vaccination + booster vaccination. (in Germany)

**Comment by Ein-Tim** [comment]
@shurkanTwo 

What certificates did you get for the first vaccination after your recovery?

**Comment by shurkanTwo** [comment]
@Ein-Tim 
I originally got a 1/1 certificate for my first vacc after recovery. I have not renewed that one yet.
It just came to my mind after I left the pharmacy, that they probably can also replace that one with a 2/1 certificate. Will ask them to do that at the end of the week.

They told me, that they have a list wich explains which number combination means what. And they said 2/1 is the first vacc after recovery and 3/1 is  supposedly the booster.

**Comment by vaubaehn** [comment]
> @Ein-Tim I originally got a 1/1 certificate for my first vacc after recovery. I have not renewed that one yet. It just came to my mind after I left the pharmacy, that they probably can also replace that one with a 2/1 certificate. Will ask them to do that at the end of the week.
> 
> They told me, that they have a list wich explains which number combination means what. And they said 2/1 is the first vacc after recovery and 3/1 is supposedly the booster.

@thomasaugsten 
Do you also have such a list like mentioned above? If yes, could you share it with us? That would be great help in supporting the community and possibly take off a small load from your shoulders.

**Comment by Ein-Tim** [comment]
@shurkanTwo 

> And they said 2/1 is the first vacc after recovery and 3/1 is supposedly the booster.

This contradicts what @mlenkeit wrote in https://github.com/corona-warn-app/cwa-app-android/pull/4764#issuecomment-1027039946

cc @vaubaehn

**Comment by vaubaehn** [comment]
> @shurkanTwo
> 
> > And they said 2/1 is the first vacc after recovery and 3/1 is supposedly the booster.
> 
> This contradicts what @mlenkeit wrote in [corona-warn-app/cwa-app-android#4764 (comment)](https://github.com/corona-warn-app/cwa-app-android/pull/4764#issuecomment-1027039946)
> 
> cc @vaubaehn

Yes, agree.
I think there's much confusion right now.

**Comment by shurkanTwo** [comment]
@vaubaehn 
I will ask them if it were possible to take a pocture of that list.
I also found this which supports my statement, though the source is doubtful: https://www.apotheke-adhoc.de/nachrichten/detail/apothekenpraxis/neue-nummerierungsregeln-fuer-impfzertifikate-3-x3-x/

@Ein-Tim
yes that is contradictory. Will give you an update after I went to the pharmacy again (today).

**Comment by vaubaehn** [comment]
@shurkanTwo 
Thanks very much for your support!
Yes, the source that you referenced appears to be doubtful, but they seem to be quite close on what is going on in pharmacies. They also provided rather good information to pharmacies when the vaccination certificates had been introduced.
So I think the information they provide currently with regard to combinations of immunizations and their notation is valid.

But that would mean, there are currently wrong 2/1 detections in CWA, and some code in the CCL repo also looks suspicious (it seems not only affect the code for testing)

**Comment by shurkanTwo** [comment]
@vaubaehn @Ein-Tim 
I was at the pharmacy just now.
Unfortunately they were not willing to give out their list for me to take a picture of.

They said that they received that lsit from the "Apotheken Kammer". And the work together with the RKI. Is there no way to directly communicate with the RKI or "Apotheken Kammer"?
I mean how else can the CWA be developed properly if not based on the primary source 😅 I hope there is some connection, but I don't know as I am very new in this community :)

**Comment by shurkanTwo** [comment]
@Ein-Tim @vaubaehn 
Whereas this site states that 2/1 is already certifying the booster: https://www.abda.de/aktuelles-und-presse/pressemitteilungen/detail/neue-eu-regeln-fuer-digitale-zertifikate-genesene-mit-auffrischungsimpfung-koennen-status-leichter-nachweisen/

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREBACK-2030](https://jira-ibs.wbs.net.sap/browse/EXPOSUREBACK-2030)
Vaccination Rule VR-DE-0003: 2of1 Biontec not valid immediately

**Comment by vaubaehn** [comment]
@shurkanTwo 
Yes, the information from ABDA differs from Apotheke adhoc. But it looks like, what happened to your certificates is in line with information from Apotheke adhoc.

I think the basic problem is, that there may be different understandings/rules between EU states what counts as a booster (so here a booster is 3/1 while in the common EU understanding it _might_ be 2/1) and the EU press release about the 2/1 notation was not clear at all and leaves too much space for different interpretations.

If I have a chance to visit my pharmacy this week, I'll also try to get that information paper as a copy. Maybe it helps when I tell them "Ich weiß, es klingt verrückt, aber eine Kopie von dem Papier könnte bei der Entwicklung der Corona-Warn-App helfen..." :wink:

**Comment by vaubaehn** [comment]
@dsarkar or does your team have such a guideline we're talking about in above comments?

**Comment by dsarkar** [comment]
@vaubaehn Trying to get hold of it.

**Comment by vaubaehn** [comment]
@dsarkar you're the best ❤️

**Comment by shurkanTwo** [comment]
@vaubaehn 
I just got a reply from the "Stellvertretender Pressesprecher of the ABDA – Bundesvereinigung Deutscher Apothekerverbände e.V.".
He states that 2/1 means having received 2 shots. And therefore is the booster certification for recovered persons.

3/1 would mean that 3 shots have been received.

I also told him that some pharmacies seem to have different information on this.

**Comment by vaubaehn** [comment]
@shurkanTwo 
Thanks for sharing - and the response shows, that we're in a kind of desperate situation, as different entities have different interpretations of the notation, although it should everywhere the same since one week...
Let's hope we (as in "the community" but also as in "the stakeholders of the CWA") will receive a valid and applicable guideline soon.

**Comment by shurkanTwo** [comment]
@dsarkar @Ein-Tim @vaubaehn 
Have you heard any news regarding this thread? :)

**Comment by Ein-Tim** [comment]
I'm unsure whether this issue can be closed now. What are the remaining problems? Is the validity check showing the correct information in the meantime (no waiting period)?

**Comment by Ein-Tim** [comment]
I will close this issue now. Please open a new one for any remaining issues.
