### ISSUE TITLE
Warning appears when adding the certificates from more than 3 persons to the app

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#786]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 6s / Huawei P Smart 2019
- iOS/Android version: 15.2 / 10
- App version: 2.15.1

## Describe the bug

With version 2.15.1, there is now a person limit for certificates. This means, that only a limited amount of certificates from different persons can be stored in the app. The limit is 20, at the moment. This works as intended.

However, there is also a warning which should be shown always if a user has stored more than 10 persons in their app. 

The variable (10) is configured here:

https://github.com/corona-warn-app/cwa-server/blob/4560eb4f1273f2b6e87aea03c0f8ae74dee539d0/services/distribution/src/main/resources/application.yaml#L129

However, in reality, the app always warns if a user has more than 3 certificates stored in the app. 

Here are videos from iOS & Android :

https://user-images.githubusercontent.com/67682506/147660470-17c49ecd-06cd-4d0d-9168-18892a2fe02b.mp4

https://user-images.githubusercontent.com/67682506/147660487-9ff07db0-8289-4a0a-830a-fe77e5c462c4.mp4

## Steps to reproduce the issue

1. Remove all stored certificates from the app
2. Add 3 certificates from different persons to the app
3. When scanning the 4th certificate from another person, see the warning

## Expected behaviour

The warning should only be displayed when more than 10 certificates from different persons are stored on the device.

## Ping 

@dsarkar We talked about this here: https://github.com/corona-warn-app/cwa-server/pull/1630#discussion_r775663519

---
Internal Tracking ID: [EXPOSUREAPP-11125](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11125)

**Comment by MikeMcC399** [comment]
This feature is so far undocumented (apart from being announced on Twitter). See https://github.com/corona-warn-app/cwa-website/issues/2217.

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399 Internal Tracking ID: [EXPOSUREAPP-11125](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11125)

**Comment by MikeMcC399** [comment]
Running Android  Corona-Warn-App-2.15.1-RC3-deviceForTesters-debug.apk with PROD environment shows Remote Config Data:

- dcc-person-count-max = 20
- dcc-person-warn-threshold = 4

So, this is either a documentation or a server-side issue.
The app looks like it is doing as instructed.

**Comment by Ein-Tim** [comment]
@MikeMcC399 Yes, I also assume that actually another config is used and the values on GitHub were not updated.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
So the issue is that the branch 
https://github.com/corona-warn-app/cwa-server/tree/main does not represent the production state of the server which provides the data for 
https://svc90.main.px.t-online.de/version/v2/app_config_android

and the deployment process from [cwa-server](https://github.com/corona-warn-app/cwa-server) to the [CDN access point](https://svc90.main.px.t-online.de/version/v2/app_config_android) is not documented in https://github.com/corona-warn-app/cwa-server.

The feedback is missing about whether there is an intentional difference in the parameter on GitHub compared to the one served to the app.

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399 

I got feedback: This is intentional and not a bug.

**Comment by Ein-Tim** [comment]
@dsarkar 

Okay, thanks. I will then follow up with an issue in the https://github.com/corona-warn-app/cwa-server repository, addressing this inconsistency. 

Closing as answered.

**Comment by Ein-Tim** [comment]
https://github.com/corona-warn-app/cwa-server/issues/1672 opened.
