### ISSUE TITLE
Prepare CWA for Omicron...

### ISSUE THREAD

**Issue by Jo-Achim** [corona-warn-app/cwa-documentation#787]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- App version:  2.15.1

## Describe the bug

I'll try a short version ...

**Current situation:** In many countries around the world, the number of new cases of infection reported every 24 hours is increasing very dramatically; For December 28, 2021, over 312,000 new infections were reported from the USA, from UK: 129,000, France: 179,000 and so on. (Source: [worldometer](https://www.worldometers.info/coronavirus/).)
If the related reports are correct, the virus variant "Omikron" is more and more responsible for these numbers.

**Discussion:** Among other things, we had discussed under [Adjust to new contagious mutations](https://github.com/corona-warn-app/cwa-wishlist/issues/328#issuecomment-986262478) about framework conditions and limitations of the CWA with regard to 'contact tracing' possibilities (Bluetooth / BLE / Apple / Google ENF). The main reason was that the 5-minute time grid in which the CWA anonymously searches for other smartphones nearby could be far too long for Omicron, because the virus transmission / infection can take place much faster with Omicron than with the previous virus variants; incl. Delta.

**Outlook:** It can hardly be assumed that Omikron will avoid Germany. It is also at least very questionable whether a possible lower 'severity of the course of the Omicron infection' makes the faster spread of the virus 'more manageable' / 'easier' for us, our health system, the economy, etc.
That means we will soon have similar numbers of new infections as we are already seeing them in other countries.

**Question:** How do we get _before_ the 5th wave? What can we do effectively?

**Answer:** We can wait until Apple and Google have found a solution to the 5-minute grid problem and the CWA is at least as good as before.
But when will that be? And is that enough?

**My answer:** no!
Therefore I would like to - explicitly take up my suggestion in the wish list [Check-In / -Scan: Suggestion for functional expansion and flexibility ...](https://github.com/corona-warn-app/cwa-wishlist/issues/713) again.
Knowing full well that this is also not a solution in the ideal sense. But it is a step in the right direction, because with the effective use of the already existing CWA functionalities "**Are you planning an event?**", "**Scanning**" and "**Check-in**" ("**Sie planen eine Veranstaltung**?", "**Scannen**" und "**Check-in**"), all options are available to defuse the "5 minutes time grid problem"!
(I had already added helpful extensions etc. in the links above and below.)

Provided, of course, that the CWA indeed can also carry out a risk classification solely on the basis of the place and time in which people were there and issue corresponding "increased risk" warnings if people who later tested positive were also present there.

**The best comes at the end:** The risk assessment in the CWA would even be able to evaluate temporal overlaps. So to warn even people who did not meet directly, but were 'only' present in close proximity (time-delayed).
Keyword: virus aerosol transmissions.

A corresponding suggestion, also against the background [[CWA vs. Luca]: Promotion of the CWAs "Check-in" functionality ...](https://github.com/corona-warn-app/cwa-wishlist/issues/690), I have already passed it on to the RKI and the Federal Ministry of Health - even if the timing between the years may not be ideal and the recipients may no longer be able to cope with the flood of information and inquiries. ;-)

With this in mind, may we achieve the best.

------------

PS from December 30th, 2021: [Coronavirus in Germany - Number of Omikron cases rises to 16,748 - within one day 28 percent more](https://www.tagesspiegel.de/wissen/coronavirus-in-deutschland-zahl-der-omikron-faelle-steigt-auf-16-748-binnen-eines-tages-28-prozent-mehr/25560996.html).

---
Internal Tracking ID: [EXPOSUREAPP-11342](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11342)

**Comment by Jo-Achim** [comment]
I do not want to go into any further details about the current new corona infections (in Germany and across the EU); the current values can be read in many ways and in various media.
And obviously the German Federal Health Minister Prof. Dr. Lauterbach - after all, as a medical specialist - considers the ending of the pandemic with Omicron for naive.

Therefore I would like to refer to [Event Registration - Summary](https://github.com/corona-warn-app/cwa-documentation/blob/master/event_registration.md) (from CWA-Documentation) as a supplement and underpinning my post above.

**Comment by larswmh** [comment]
Thanks for your report @Jo-Achim. We've added this to the internal ticket that was already created for your mentioned wishlist issue. Internal Tracking ID: [EXPOSUREAPP-11342](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11342)

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@Jo-Achim 

There is a blog statement published on Jan 11, 2022 ["Wird die CWA an die Omikron-Variante angepasst?"](https://www.coronawarn.app/de/blog/2022-01-11-cwa-omikron/) (currently only available in German) which discusses the question of adapting the app to the Omicron variant including the problem of reducing the sampling frequency.

**Comment by Ein-Tim** [comment]
If there are no plans to adjust CWA to Omicron, I suggest to close this issue now.

**Comment by MikeMcC399** [comment]
According to https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/Wochenbericht/Wochenbericht_2022-11-03.pdf?__blob=publicationFile 

"Aktuell ist die VOC Omikron die in Deutschland dominierende SARS-CoV-2-Variante. Andere Varianten, wie die VOC Delta und zuvor die VOC Alpha, wurden vollständig verdrängt (siehe Abbildung 24)."

so, as @Ein-Tim already wrote, unless some additional changes need to be done, then the issue should be closed.
