### ISSUE TITLE
Problematic English translation of "Genesenenzertifikat" to "Certificate of Recovery"

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#789]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

Related to PR https://github.com/corona-warn-app/cwa-website/pull/2263.

## Technical details

- App version: 2.5.1 to 2.15.1 and pre-release 2.16

## Describe the bug

The German term "Genesenenzertifikat" has been translated into English as "Certificate of Recovery" which uses a different grammatical construction compared to the translations of "Impfzertifikat" and "Testzertifikat". This is problematic when making lists or describing certificates in the English-language FAQs https://www.coronawarn.app/en/faq/. 

### App translations

German | English translation
--- | ---
Impfzertifikat | Vaccination Certificate
Testzertifikat | Test Certificate
Genesenenzertifikat | Certificate of Recovery

### Comparison to Privacy Notice

The [Privacy Notice for 2.15](https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf) does not use the term "Certificate of Recovery" at all, instead the document refers to:

- recovery certificate
- COVID recovery certificate
- digital COVID recovery certificate

so the use of the term "Certificate of Recovery" in the app is an anomaly.

## Steps to reproduce the issue

View screenshot pages:

- https://www.coronawarn.app/en/screenshots/#android_recovery_certificate (EN)
- https://www.coronawarn.app/de/screenshots/#android_recovery_certificate (DE)

and compare to:

- https://www.coronawarn.app/en/screenshots/#android_vaccination_certificate (EN)
- https://www.coronawarn.app/de/screenshots/#android_vaccination_certificate (DE)

- https://www.coronawarn.app/en/screenshots/#android_test_certificate (EN)
- https://www.coronawarn.app/de/screenshots/#android_test_certificate (DE)

## Expected behavior

The translation to English of the German term "Genesenenzertifikat" should use the same grammatical construction as the translation of the other two certificate types "Impfzertifikat" and "Testzertifikat" and so should be translated as "Recovery Certificate".

(The other alternative would be to rename the other two certificate types to be called "Certificate of Vaccination" and "Certificate of Test". That would be consistent, but it would also make it more complicated, so this is not a preferred solution.)

## Possible Fix

For Android, in `Corona-Warn-App/src/main/res/values/covid_certificate_strings.xml`
change "Certificate of Recovery" to "Recovery Certificate" for strings `recovery_certificate_details_title` and `recovery_certificate_name` and in other text strings where the term is used.

Similarly for iOS.

## EU naming

The EU has used both terms "Certificate of Recovery" and "Recovery Certificate" in their documentation.
https://ec.europa.eu/health/ehealth/covid-19_en uses the term "Recovery Certificate" whereas the document https://ec.europa.eu/health/sites/default/files/ehealth/docs/covid-certificate_paper_guidelines_en.pdf shows the term "Certificate of Recovery". This seems to demonstrate that both terms are acceptable and that using the term "Recovery Certificate" in the CWA app would not conflict with the usage by the EU.

---
Internal Tracking ID: [EXPOSUREAPP-11137](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11137)

**Comment by larswmh** [comment]
Hi @MikeMcC399, thanks for your report. We have created an internal ticket and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-11137](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11137)

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
I am withdrawing this bug report after researching the legal texts from the EU and Germany. The EU legal definition is "Certificate of recovery", however when the term is used together with vaccination and test certificates, it is secondarily referred to as "recovery certificate".

So the use of the term "Certificate of recovery" in the app cannot be viewed as a translation error if this is the legal term used in the [Regulation (EU) 2021/953](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32021R0953).

Reference text | German | English
--- | --- | ---
[IfSG](https://www.gesetze-im-internet.de/ifsg/BJNR104510000.html) | "COVID-19-Genesenenzertifikat" | -
[Verordnung (EU) 2021/953 ](https://eur-lex.europa.eu/legal-content/DE/TXT/HTML/?uri=CELEX:32021R0953) | "Genesungszertifikat" | -
[Regulation (EU) 2021/953](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32021R0953) | - | "Certificate of recovery"<br>or in lists<br>"recovery certificate"

- I have submitted a new issue to request that the [Privacy Notice](https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf) aligns with the legal definition and use of the term "Certificate of Recovery" in the app. See https://github.com/corona-warn-app/cwa-documentation/issues/802.

Side note: the term used in the German and EU legal texts differ from each other:
- "Genesenenzertifikat" in texts from Germany and 
- "Genesungszertifikat" in the EU text.

In German CWA uses the term from the German legal document [IfSG](https://www.gesetze-im-internet.de/ifsg/BJNR104510000.html) i.e. "Genesenenzertifikat".

## References

The DSFA (Datenschutz-Folgeabschätzung) for CovPass App (see https://github.com/corona-warn-app/cwa-website/issues/2289) refers to two legal documents which define certificates. These are:
- [IfSG](https://www.gesetze-im-internet.de/ifsg/BJNR104510000.html) in German
- [Verordnung (EU) 2021/953 ](https://eur-lex.europa.eu/legal-content/DE/TXT/HTML/?uri=CELEX:32021R0953) in German and
- [Regulation (EU) 2021/953](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32021R0953) in English

### German Legal Document

- [Gesetz zur Verhütung und Bekämpfung von Infektionskrankheiten beim Menschen (Infektionsschutzgesetz - IfSG)](https://www.gesetze-im-internet.de/ifsg/BJNR104510000.html) § 22 Impf-, Genesenen- und Testdokumentation, COVID-19-Zertifikate<br>
In IfSG § 22 (6) the certificate is referred to as "COVID-19-Genesenenzertifikat".

### EU Legal Documents

- [Verordnung (EU) 2021/953 des Europäischen Parlaments und des Rates vom 14. Juni 2021 über einen Rahmen für die Ausstellung, Überprüfung und Anerkennung interoperabler Zertifikate zur Bescheinigung von COVID-19-Impfungen und -Tests sowie der Genesung von einer COVID-19-Infektion (digitales COVID-Zertifikat der EU) mit der Zielsetzung der Erleichterung der Freizügigkeit während der COVID-19-Pandemie (Text von Bedeutung für den EWR)](https://eur-lex.europa.eu/legal-content/DE/TXT/HTML/?uri=CELEX:32021R0953)<br>
Verordnung (EU) 2021/953 Artikel 7 defines the "Genesungszertifikat".

- [Regulation (EU) 2021/953 of the European Parliament and of the Council of 14 June 2021 on a framework for the issuance, verification and acceptance of interoperable COVID-19 vaccination, test and recovery certificates (EU Digital COVID Certificate) to facilitate free movement during the COVID-19 pandemic (Text with EEA relevance)](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32021R0953)<br>
Regulation (EU) 2021/953 Article 7 defines the "Certificate of recovery".<br>
In the title of the document, and in other lists, the certificate is alternatively referred to as "recovery certificate". See for instance Article 1 - Subject matter:
<br>"This Regulation lays down a framework for the issuance, verification and acceptance of interoperable COVID-19 vaccination, test and recovery certificates (EU Digital COVID Certificate) for the purpose of facilitating the holders’ exercise of their right to free movement during the COVID-19 pandemic."

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for the research, will forward it to the internal ticket.
