### ISSUE TITLE
Functionality for other Operating systems -> Keep it open

### ISSUE THREAD

**Issue by JoHarrison** [corona-warn-app/cwa-documentation#79]
It looks like it can be an important help to support the contagion of the new dissease!
However, after reading some news articles about politicians wanting to grant people, who will be using the app, benefits compared to others, who are not using the app, I was wondering, on what Operating Systems the app will be able to be used?
As war as media mentioned it, again only iOS and Andriod, but what about users of other Operatind systems, e.g. Ubuntu Touch, SailfishOS, FirefoxOS?
If this App gives basically can define your civil rights in society, it must be independent!
Please give a statement, how to fix this issue! Thank you!

**Comment by tkowark** [comment]
Thanks for your question. Please take a look at #5  for answers.

**Comment by kbobrowski** [comment]
@JoHarrison it would be possible to fix it by re-implementing Google/Apple Exposure Notification API. If there is no undocumented behavior there it should be possible based on specification. Then it would be easy to fork CWA and deploy it on other systems, but I guess it would have to be a community effort.

**Comment by SebastianWolf-SAP** [comment]
Please understand that we can't keep it open as we clearly communicated the scope of this project. However, the community is strong as always, at least a developer on SailfishOS has started something quite a while ago: https://github.com/llewelld/harbour-contrac

**Comment by JoHarrison** [comment]
> Please understand that we can't keep it open as we clearly communicated the scope of this project. However, the community is strong as always, at least a developer on SailfishOS has started something quite a while ago: https://github.com/llewelld/harbour-contrac

Dear Mr. Wolf,
I can understand the scope of the project given to you, but I cannot understand, that the scope is defined like this from companies SAP and Telekom.
Additionally, I cannot understand that the root cause for not having a open system is the policy of companies Google and Apple and that the politic is letting them get away with this. Its a shame!
Thankfully we have this community giving a small hope for keeping democratic processes alive!
