### ISSUE TITLE
No push notification after multiple different high risk exposures?

### ISSUE THREAD

**Issue by nelsininho** [corona-warn-app/cwa-documentation#791]
## Your Question
* Documentation File: https://github.com/corona-warn-app/cwa-app-ios/blob/main/docs/architecture-overview.md
* Line / Paragraph: [Exposure Risk Level Calculation](https://github.com/corona-warn-app/cwa-app-ios/blob/main/docs/architecture-overview.md#exposure-risk-level-calculation)
* Question: The documentation of the iOS app mentions that local push notifications only occur after a risk level change. However, I almost missed another high risk exposure within the 14 days of a first exposure, since I did not get any push notification. I only saw it by chance, when I opened the app and read, that there were 2 instead of 1 days of exposure. Would it be possible to avoid this by sending out local push notifications on every high risk exposure instead of only when the risk level changes?

**Comment by Ein-Tim** [comment]
FYI [CWA 2.20: Corona-Warn-App Available in Ukrainian Language](https://www.coronawarn.app/en/blog/2022-03-30-cwa-2-20/) includes the sentence:
"Furthermore, the CWA now notifies users when the date of the last encounter with increased risk on the red tile has changed. Previously, users were not notified again if they had another, more recent encounter with increased risk after a risk encounter."

So yes, there is another push notification if there is another increased risk exposure detected. 

Please close this issue @nelsininho.
