### ISSUE TITLE
Question on "2G+" badges in version 2.16

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#797]
## Your Question

With version 2.16, CWA will start to show badges which rules (3G, 3G+, 2G, 2G+) are fulfilled by the certificates the user has stored on their devices. 
Reg. the 2G+ bade, there is one big open question:
How to handel people who received a booster shot?
According to https://www.bundesregierung.de/breg-de/aktuelles/testpflicht-bei-2g-plus-1991544 they do not need to get tested, if their booster vaccination happened more than 14 days ago (and they do not want to visit a medical place).
The 2G+ badge should therefore also be shown if a booster is added to the app and it's older than 14 days.
However, this does not seem to be implemented currently. Why?

## Ping

@mlenkeit

**Comment by mlenkeit** [comment]
> Why?

@Ein-Tim the Sprint/iteration where we built that feature closed on Dec 15, the day on which the statement was published 😉

There are discussions going on as to what extend this should be incorporated in CWA, especially considering that boosters cannot reliably be detected by inspecting an individual certificate (e.g. recovery > vaccination > booster, or booster after vaccination with Janssen) but as usual, we cannot make any promises.

**Comment by Ein-Tim** [comment]
@mlenkeit 

> the Sprint/iteration where we built that feature closed on Dec 15, the day on which the statement was published 😉

Ah, okay 😁

Regarding your other arguments, yes, boosters can't be reliable detected, however, IHMO the badge could still be shown if "3/3" certificate is in the app.

Regarding the different local rules: If this is really the case I have just one word for this: **Don't** 😅
If local regulations are different, we shouldn't even start to implement anything here, as these regulations might change. 

Thanks for the answer Maximilian, hope you had a good start in 2022! Thanks for your work! 

Closing.

**Comment by Jo-Achim** [comment]
Is it correct that, for example, a digital vaccination certificate (DCC) with the content "3/3" or "2/1" must always be a booster vaccination? (See: [Vorschriften für die Kodierung](https://ec.europa.eu/commission/presscorner/detail/de/ip_21_6837).)

If yes... I have to express a little disappointment here regarding CWA v2.17.2. Although I had already recognized the difficulties and general conditions regarding programming [here](https://github.com/Digitaler-Impfnachweis/covpass-android/issues/139#issuecomment-1030600726), for example. 

I think no matter which 'all-encompassing' solutions regarding "2G+" or similar are in the pipeline, the current version of the CWA would have deserved an evaluation and display of "2G+" by now. And if only as a temporary workaround for the particularly simple cases; e.g. with vaccination certificates "3/3" or "2/1".
After determining "2G" in the algorithm, this would only have required an additional check as to whether a "3/3" or "2/1" can be found in the currently used DCC. I'll leave it open in terms of effort, whether a one-liner or three-liner would have been sufficient.

With the help of the new info card "People with booster vaccination" (until February 4th, 2022) 54.2% or 45,062,243 people, it is possible to estimate how many people could have possibly benefited from this workaround.
