### ISSUE TITLE
"Exposure check failed" without internet connection despite previous successful check

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#800]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Not relevant
- OS version: Not relevant
- App version: Any since 2.0

## Describe the bug

When offline, the Corona-Warn-App always shows the "Exposure check failed card", even if the last exposure check was successful.

https://user-images.githubusercontent.com/67682506/126082796-488b505e-ede9-4b71-b27b-b26cb2e5c428.mp4

## Steps to reproduce the issue (iOS)

1. Open the Corona-Warn-App with active internet connection
2. Check in to an event
3. Click on "Exposure Logging Active"
4. Switch off internet
5. Tap "Back"
6. See that the CWA shows the "Exposure check failed" card
7. Click on "Exposure Logging Active"
8. Turn on internet
9. Tap "Back
10. See that the CWA shows the normal risk card again

## Steps to reproduce the issue (Android)

1. Open the CWA with active internet connection
2. Check in to an event
3. See the normal risk card
4. Close the CWA completely 
5. Disconnect from the internet
6. Open the CWA
7. See the "Exposure Check Failed" card

## Expected behaviour

The "Exposure check failed" card should only be shown if the exposure check really failed.

----
Internal Tracking-ID: [EXPOSUREAPP-13383](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13383) Android
Internal Tracking-ID: [EXPOSUREAPP-8483](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8483) iOS Fixed 2.24

**Comment by Ein-Tim** [comment]
I just rechecked and this issue persists. We are talking about a UI issue here, I understand the points @thomasaugsten brought up above but I still think that the apps behavior is very confusing to the normal user.

**Comment by Ein-Tim** [comment]
The team really has to find a solution to this bad UX...

**Comment by Ein-Tim** [comment]
I can confirm that this has been fixed in version 2.24 under iOS, I will check Android as soon I receive the update on the device.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Did you try this out on CWA Android 2.24 with a check-in stored? I am still getting the error.

I don't see the logic of showing an error message only when there is a check-in stored. The app should just show the last update time with no error.

If no updates are possible for a longer time, then the deadman's notification should kick in (currently 36 hours - see [DeadmanNotificationTimeCalculation.kt#L49](https://github.com/corona-warn-app/cwa-app-android/blob/4da28266535565e900d1668eb0b9204340a729db/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/deadman/DeadmanNotificationTimeCalculation.kt#L49)).

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I can confirm that, while the issue is fixed under iOS, it is **not fixed** under Android.

Android needs to be aligned to iOS now.

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim Affirm: 
Internal Tracking-ID: [EXPOSUREAPP-13383](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13383) Android - not yet fixed
Internal Tracking-ID: [EXPOSUREAPP-8483](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8483) iOS - fixed 2.24

**Comment by mtwalli** [comment]
Android PR : https://github.com/corona-warn-app/cwa-app-android/pull/5411 targeting 2.26

**Comment by MikeMcC399** [comment]
A new label "Fix 2.26" needs to be created and added to this issue.

**Comment by Ein-Tim** [comment]
I currently don't have access to my Android device, but as soon as I get back home I'll test if this bug is fixed successfully with version 2.26.

**Comment by Ein-Tim** [comment]
This has been fixed for Android with version 2.26.
