### ISSUE TITLE
Booster vaccination should be shown as such, not 2/2 for Janssen.

### ISSUE THREAD

**Issue by SoftwareApe** [corona-warn-app/cwa-documentation#801]
## Current Implementation
With Janssen, Booster is shown as 2/2. In some states (e.g. BW) 2G+ means no need to have a test certificate.

With Janssen the Booster gets easily confused with the final normal vaccination. This makes it necessary to explain everywhere that the first vaccination was Janssen, thus showing 1/1, and therefore 2/2 is the booster.

## Suggested Enhancement
Since we don't know how many boosters there are going to be it doesn't make sense to show x/y.

Instead it should be 1st booster, 2nd Booster, ...

## Expected Benefits
Less hassle explaining things. Less confusion. Less interaction with people.

---
Internal Tracking ID: [EXPOSUREAPP-11143](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11143)

**Comment by dsarkar** [comment]
Transferred to documentation repository. 
Internal Tracking ID: [EXPOSUREAPP-11143](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11143)

**Comment by haskamp-1** [comment]
Willkommen im Leben!

Was passiert, wenn Sie abends vor einem Lokal dem Türsteher drohen, die Polizei zu rufen? Richtig! Sie werden ausgelacht. Aber reinkommen werden Sie niemals im Leben. Vielleicht klappt es tagsüber im Schwimmbad, aber das nimmt doch abstruse Züge an!

@dsarkar Und was spricht dagegen "geboostert in HH, NS, SL usw." hinzuschreiben? Kann ja in den Zertifikatdetails stehen. Da muss mir niemand mit "spricht gegen EU-Regeln" kommen. Aktuell ist es ganz einfach: Türsteher gucken auf "3/3" und sonst nichts. Basta.

Und Auftrag hin oder her. Es muss doch lebensnah sein! Und als IT-Berater (was ich bin), kann man den Kunden auch mal einen Vorschlag machen. Oder wird sowas pauschal immer abgelehnt? Wenn ja, dann würde ich gerne die konkrete Person genannt bekommen, so dass ich als dies dem Vorgesetzten direkt melden kann.
Oder verdient man mehr Geld, wenn man erst auf die Anforderung wartet anstatt mal selbst was zu sagen?!

Was ich sicher sagen kann: Als Entwickler der App würde ich mir Mühe geben die User-Akzeptanz zu erhöhen. So sind doch alle Seiten unzufrieden. Und mich mit einem Türsteher oder Kellner oder sonstigen Kassenmitarbeiter anzulegen ist doch unnötig und ärgerlich. Und das kann doch mal ganz easy durch die App-Entwickler vermieden werden.

Viele Grüße
Heinrich Haskamp

**Comment by dsarkar** [comment]
@haskamp-1 

I hope you don't mind switching to English here on GitHub. 

Rest assured that the development team is in very close contact with all the stakeholders. The issue described here is indeed, let's say, quite annoying in real life, as you and many others expressed already. We forward all these concerns, and the importance to find practical solutions to the stakeholders. 

In a first step, as you can read in the above mentioned FAQ, only recently on an EU level the scheme of the DCC has been adopted because of the issue described here.

**Comment by ElpadoCan** [comment]
@haskamp-1  you are right, messing with the bouncer is definitely not ideal. Anyway, make sure to check that JJ+booster is really considered 2G+, because here in Bavaria the Ministry of Health goes around saying that it is not 2G+ even though the law says the opposite. A total mess.

**Comment by SoftwareApe** [comment]
Luckily the omicron wave is going to be over next month and then we can maybe go back to our normal lives, because waiting for the UX to improve seems to really be less likely.

**Comment by ElpadoCan** [comment]
> Luckily the omicron wave is going to be over next month and then we can maybe go back to our normal lives, because waiting for the UX to improve seems to really be less likely.

To be honest, it doesn't matter much, at least in Bavaria they now changed the rules and JJ + 1 dose doesn't count as boostered. To me, it is still against the law and I hope that some lawyers will have a really good time soon with this mess of the pandemic.

**Comment by SoftwareApe** [comment]
@ElpadoCan Bavaria isn't the world. We could have the proper UX showing boostered, maybe with a * linking to the Paul Ehrlich Institute, and at least most of Germany would have a solution. that's satisfactory. 

My point was rather facetious that the pandemic is now faster with Omicron than the CWA development. So we can hope that by end of February this whole thing is unnecessary because it's finally declared as endemic.

Switzerland and Spain are a bit ahead of us here in recognizing that the whole effort is pointless with Omicron's infection rates.

**Comment by ElpadoCan** [comment]
@SoftwareApe not considering JJ + 1 dose as "boostered" is a STIKO recommendation, it will soon be applied to all Germany, as haskamp-1 pointed out it is already applied in Hamburg. I agree the app could be better in this case and I hope it will be. Even if it will be finally declared as endemic, vaccine passports will still be required. Probably forever.

**Comment by jfhaecker** [comment]
Unfortunately the vision of having a digital and cryptographically secured check-in process with flexible rulesets seems to be wishful thinking. I hope there will be a learning curve on stakeholders site.
Thx for the transparency. Good job.

**Comment by Ein-Tim** [comment]
@ElpadoCan 

I suggest you take a look at https://www.bundesgesundheitsministerium.de/service/gesetze-und-verordnungen/vo-aend-covid-19-schausnahmv-und-coronavirus-einreisev

**Comment by ElpadoCan** [comment]
> @ElpadoCan 
> 
> I suggest you take a look at https://www.bundesgesundheitsministerium.de/service/gesetze-und-verordnungen/vo-aend-covid-19-schausnahmv-und-coronavirus-einreisev

Thanks, but I knew it was just a question of time, having a law doesn't make me feel better. What annoys me is that as a JJ vaccinated person I didn't do anything wrong and as soon as I could I got a second dose of mRNA vaccine as recommended. However now it turns out that following recommendation is not enough because I have to wait March to get a third dose and be considered boostered. Will any institution tell me what I did wrong? Or what should I have done instead? Maybe I should have predicted the future a get a second shot earlier than I did? But then, they have to tell me how? I took the first opportunity I got, I went to one of those "open day" for vaccination. If I had waited the official appointment I would still be waiting. This is total nonsense and I don't understand how people can be fine with it.

**Comment by DerVogel2020** [comment]
> @ElpadoCan 
> 
> I suggest you take a look at https://www.bundesgesundheitsministerium.de/service/gesetze-und-verordnungen/vo-aend-covid-19-schausnahmv-und-coronavirus-einreisev

There is only a change to the isolation rule for vaccinated people, not to the recommendation of the PEI, which is, as I see, the "official" definition of "geboostert".

**Comment by DerVogel2020** [comment]
Yes that's very annoying. Until Thursday you were "boostered" now, I
You're not🤨 (and me too).
But that's not part of the app development but political😲

**Comment by Ein-Tim** [comment]
With the change I informed about via https://github.com/corona-warn-app/cwa-documentation/issues/801#issuecomment-1000950410 this issue is fixed and should be closed @SoftwareApe.
