### ISSUE TITLE
"Recovery certificate" term in Privacy Notice (EN)

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#802]
## Where to find the issue

[Privacy Notice](https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf) - English language

## Describe the issue

The [Privacy Notice](https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf) (EN) uses the terms:

- recovery certificate
- COVID recovery certificate
- digital COVID recovery certificate

whereas the CWA app uses the term "Certificate of recovery". See [Certificate of Recovery screenshot](https://www.coronawarn.app/assets/screenshots/2-15/en/android/RecoveryCertificateDetailsFragment_recovered.png) from CWA Android 2.15.

![CWA 2 15 Certificate of Recovery](https://user-images.githubusercontent.com/66998419/148693324-8150e694-83c5-41c1-ba06-523d5b9adcb3.png)

The term "Certificate of recovery" is legally defined by the [Regulation (EU) 2021/953 of the European Parliament and of the Council of 14 June 2021 on a framework for the issuance, verification and acceptance of interoperable COVID-19 vaccination, test and recovery certificates (EU Digital COVID Certificate) to facilitate free movement during the COVID-19 pandemic (Text with EEA relevance)](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32021R0953) in Article 7. In lists however, the document also alternatively refers for instance in Article 1 - Subject matter to "recovery certificates" as in the text "COVID-19 vaccination, test and recovery certificates (EU Digital COVID Certificate)" similar to the use on the title page of the Regulation itself.

- This issue follows on from https://github.com/corona-warn-app/cwa-documentation/issues/789.

## Suggested change

In the [Privacy Notice](https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf) use the term "Certificate of recovery" when individually referring to this type of certificate. (When referring to the certificate in lists, leave the term as "recovery certificate".)

- Change the sentence "The creation and confirmation of recovery certificates is based on Art. 9(2)(g) GDPR in conjunction with Sect. 22(6) IfSG." to "The creation and confirmation of certificates of recovery is based on Art. 9(2)(g) GDPR in conjunction with Sect. 22(6) IfSG."

- In section 5 i "Data about your recovery (data in the COVID recovery certificate)" change title to "Data about your recovery (data in the COVID certificate of recovery)". In the text of this section change references to "certificate of recovery".

- In section 6 h. "Digital COVID certificates" change from "COVID recovery certificate" to "COVID certificate of recovery".

## Related changes

- https://github.com/corona-warn-app/cwa-website/pull/2491

---
Internal Tracking ID: [EXPOSUREAPP-11242](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11242)

**Comment by larswmh** [comment]
Thanks for your report @MikeMcC399. Internal Tracking ID: [EXPOSUREAPP-11242](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11242)

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
The upcoming 2.19 privacy notice has not been changed to align the term "recovery certificate" to "certificate of recovery" as used in the app.

See document https://github.com/corona-warn-app/cwa-website/blob/release/2.19/src/assets/documents/cwa-privacy-notice-en.pdf.

**Comment by dsarkar** [comment]
@MikeMcC399 I will check if this issue will be addressed.

**Comment by MikeMcC399** [comment]
@dsarkar 
>  I will check if this issue will be addressed.

I didn't hear back from you and 2.21 has now been released.

**Comment by larswmh** [comment]
@MikeMcC399 thanks for your patience. We've received feedback that this won't be fixed. Closing as suggested in a https://github.com/corona-warn-app/cwa-documentation/issues/802#issuecomment-1088668892

**Comment by MikeMcC399** [comment]
@larswmh 

Thanks for taking the time to ensure that this issue was clarified, even if no change will be made.
