### ISSUE TITLE
Duplicate "." at the end of a sentence

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#803]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [ ] Bug is not already reported in another issue There were PRs attempting to fix this: https://github.com/corona-warn-app/cwa-app-ios/pull/4058 & https://github.com/corona-warn-app/cwa-app-ios/pull/4035

## Technical details

- Device name: Not relevant
- iOS/Android version: Not relevant
- App version: 2.15.1

## Describe the bug

There are two "." at the end of these strings:

- iOS:

https://github.com/corona-warn-app/cwa-app-ios/blob/d22b0e4512f41d8eea27ffd90c109ba6564eb2c3/src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings#L119 

- Android: 

https://github.com/corona-warn-app/cwa-app-android/blob/a1110d3d0906273936ef1db7e8024ec581f8dfbc/Corona-Warn-App/src/main/res/values/strings.xml#L261

## Steps to reproduce the issue

Should be clear. Read the text.

## Expected behaviour

Only one ".".

## Possible Fix

Remove one ".".

## Pings

FYI @marcussc, @mtwalli, @matthiasdiener & @krichly

---
Internal Tracking ID: [EXPOSUREAPP-11251](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11251)

**Comment by larswmh** [comment]
Thanks for your report @Ein-Tim. Internal Tracking ID: [EXPOSUREAPP-11251](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11251)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Fixed with https://github.com/corona-warn-app/cwa-app-android/commit/1634e94b53af8ad3fa7cfc7e1ee123ca02d66bf4 for Android.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

The fix may be on its way, but it hasn't reached the release/2.16.x branch yet. See

https://github.com/corona-warn-app/cwa-app-android/blob/release/2.16.x/Corona-Warn-App/src/main/res/values/strings.xml#L258-L259

    
    <string name="risk_details_behavior_body_stay_home">"If possible, please go home and stay at home and avoid any encounters outside of your own household.."</string>

Perhaps check again later today or tomorrow?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

The fix was just merged: 

- https://github.com/corona-warn-app/cwa-app-android/pull/4677
- https://github.com/corona-warn-app/cwa-app-ios/pull/4066

**Comment by Ein-Tim** [comment]
Closing this issue now, as it was fixed in version 2.16.
