### ISSUE TITLE
[Little Bug] Info cards related to "7-Day-Incidence", wrong useage of units ...

### ISSUE THREAD

**Issue by Jo-Achim** [corona-warn-app/cwa-documentation#804]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- App version:  2.15.1

## Describe the bug
The data on the “Local… 7-day incidence” and the information on the “7-day incidence (nationwide)” are likely to be incorrect. For example, they are currently specified in the context of “353.0 **Neuinfektionen** / **new infections**”. See:

![7-Tage-Inzidenz, Dimension](https://user-images.githubusercontent.com/21124877/148927178-aa67b685-b1a2-477b-a0ec-f24b6d41843d.jpg)

## Steps to reproduce the issue

1. Open CWA
2. Go to the Info-cards (see Screenshot).

## Expected behaviour

Correctly, however, "Neuinfektionen" / “new infections” should either be supplemented with “per 100,000”. 
_Or better_ according to wikipedia section ["7-Tage-Inzidenz" / "7-day incidence"](https://de.wikipedia.org/wiki/Inzidenz_(Epidemiologie)):
> “The seven-day incidence or 7-day incidence is a **_dimensionless_**, statistical indicator for new infections that have been proven and registered by laboratory diagnostics in the past 7 days based on an arithmetical 100,000 inhabitants. ... ",

the dimension would have to be omitted - here the "Neuinfektionen" / "new infections".

Incidentally: The explanations in the 3-point menu are sufficient to leave out the "Neuinfektionen" / "new infections" dimension. 

## Additional context

Even if this correction can be described as a minor matter, these linguistic / conceptual errors are widespread and should be avoided for the purpose of conceptual precision and comprehensibility and to avoid misinterpretations.

We all endeavor to write briefly due to a lack of time or a limitation in the number of info lines. You can see where this is going from the information from NINA.
First of all, anyone who has been vaccinated “against something” is vaccinated. In contrast to the "against something" unvaccinated.
In connection with Corona, the term “fully vaccinated” was therefore initially introduced in order to create a demarcation in the sense of a complete basic immunization. In the course of time, however, the word "fully" has been completely omitted and those responsible assume that - in context with Corona - everyone knows that "vaccinated" now means "fully vaccinated". But that can't actually be the case! Or?
Pointed out this incorrect use of the term to the BKK (Federal Office for Civil Protection and Disaster Assistance) returns only a 'thank you - we passed this on to the dpa (German Press Agency), because the texts come from there'.
Nice, then sitting on one hand 'term illiterates' and on the other hand responsible who also do not get along with word meanings in the German language!?

Summery: Please pay attention to the correct and complete use of terms. "The German language is a difficult language." ;-)

---
Internal Tracking ID: [EXPOSUREAPP-11259](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11259)

**Comment by larswmh** [comment]
Thanks for your report @Jo-Achim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-11259](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11259)

---
Corona-Warn-App Open Source Team

**Comment by KathrinLuecke** [comment]
Hi @Jo-Achim,
I wouldn't say that "Neuinfektionen" is wrong here, it's just a shortened representation of what is explained when you click on the "i":
"Gesamtzahl der bestätigten Neuinfektionen der letzten 7 Tage (nach Meldedatum) pro 100.000 Einwohner".
Don't you think this is sufficient?

**Comment by Jo-Achim** [comment]
Hi @KathrinLuecke,

no, I think the statement, e.g. "353.0 new infections" as an indication of a 'dimensionless' incidence is wrong here.
It is correct after clicking on "i" because the dimension "per 100,000 inhabitants" is added correctly.

In this respect, I stand by the suggestion to correct this.

**Comment by KathrinLuecke** [comment]
@Jo-Achim I understand your point. I'll discuss this today with the colleagues.

**Comment by KathrinLuecke** [comment]
@Jo-Achim I've discussed this with the colleagues and learned that it was a conscious decision to leave out "per 100,000 inhabitants". Mainly this was because of the space restrictions - adding this would take up space, and in addition it was assumed that the term "7-Tage-Inzidenz" is known by most people, so they know that the numbers shown on the tiles refer to 100,000 inhabitants. If not, they can look it up via the i-button. So we will not change this.

**Comment by Jo-Achim** [comment]
Sorry, @KathrinLuecke.

It is **NOT** about adding "per 100,000 inhabitants" to the tile shown in the screenshot above! It is clear that this takes up unnecessary space.

The point is to simply **omit the word "new infections" / "Neuinfektionen"**, since an incidence is dimensionless. As a result, even more space would be created.

**Comment by KathrinLuecke** [comment]
@Jo-Achim Not sure I understand this. If we just show the number, how should people know what it refers to? And then we would also need to skip "Hospitalisierungen". So we would just have two numbers on the tile without any indication what they refer to.

**Comment by Jo-Achim** [comment]
@KathrinLuecke.

It is fundamentally wrong to give a dimension when the value is dimensionless. And it is therefore also wrong to give a wrong dimension. (Sorry, I'm a specialist.) See: ["7-Tage-Inzidenz" / "7-day incidence"](https://de.wikipedia.org/wiki/Inzidenz_(Epidemiologie)).

> If we just show the number, how should people know what it refers to? 
>>  ...they can look it up via the i-button.


> And then we would also need to skip "Hospitalisierungen". So we would just have two numbers on the tile without any indication what they refer to.

On closer inspection: yes and yes; either right or not at all. 
Where the change from "Until yesterday x,y hospitalizations" ("Bis gestern x,y Hospitalisierungen") could be changed to "Until yesterday hospitalizations: x,y" ("Bis gestern Hospitalisierungen: x,y"). 
And details for both cases "...they can look it up via the i-button".

**Comment by Jo-Achim** [comment]
@KathrinLuecke,

I personally would find the solution more correct.

**Comment by Jo-Achim** [comment]
PS: 
With regard to hospitalizations ("Hospitalisierungen"), one could also use the term hospitalization rate ("Hospitalisierungsrate").

**Comment by KathrinLuecke** [comment]
Hi @Jo-Achim,
we've discussed this again, also with colleagues from RKI, and there was no consent on changing the wording on the inzidence tiles. We will keep them as they are.
Best regards,
Kathrin Luecke

**Comment by Jo-Achim** [comment]
Hi @KathrinLuecke, 
mh, ok, I'll close then.
