### ISSUE TITLE
Android and IOS have different risks

### ISSUE THREAD

**Issue by dustinla** [corona-warn-app/cwa-documentation#805]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- Device name:
Oneplus 6T (A6013)
Iphone 12 (MGJA3ZD/A)
- iOS/Android version:
Android 10 / OxygenOS 10.3,12
Iphone 15.2
- App version:
Android 2.15.1
Iphone2.15.1 (2)

## Describe the bug
Different risk levels for different devices and operating systems. 
Both devices were in the same bag, but had different risks.
The Android device did not even show a risk on 02.01.22, but the Iphone did. 
The Iphone showed a higher risk on 05.01.22 and the Android device showed a lower risk.
It seems to be an error in the calculation/sensitivity of the Bluetooth 

Oneplus 6T:
![Android](https://user-images.githubusercontent.com/42574834/149013739-9eab7121-f10a-47c0-9ba6-9a0020457b98.jpg)
Iphone 12:
![Iphone](https://user-images.githubusercontent.com/42574834/149013759-e38f77cb-2968-4bfe-b16f-f534eee23bb4.jpg)

## Expected behaviour

Both show the same risks.

**Comment by Ein-Tim** [comment]
This is actually mentioned in the FAQ: [Dissimilar indication of risk status](https://www.coronawarn.app/en/faq/#dissimilar_indication_of_risk_status)

**Comment by dustinla** [comment]
My mistake. I did not find it in the FAQ. Thanks for the clarification.
