### ISSUE TITLE
Booster rules not updated to STIKO 16th recommendation

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#806]
## Technical details

- Booster rules from https://distribution.dcc-rules.de/bnrules
- Applies to App versions (iOS and Android): 2.10 and later

## Describe the bug

Booster rules used by the app are out of date and do not reflect the 16th STIKO recommendations as published in [Epidemiologisches Bulletin 2 2022](https://www.rki.de/DE/Content/Infekt/EpidBull/Archiv/2022/Ausgaben/02_22.pdf?__blob=publicationFile).

For instance BNR-DE-0100, valid until 2030-06-01 says:

"The Standing Committee on Vaccination (STIKO) recommends that all persons who are 70 and over and who have not had a proven case of the coronavirus (SARS-CoV-2) have a booster shot if they obtained their base vaccination more than six months ago."

BNR-DE-0300 says:

"The Federal Ministry of Health recommends that all persons who have not had a proven case of the coronavirus (SARS-CoV-2) and who obtained their base vaccination more than six months ago arrange a vaccination appointment or discuss the benefits of getting a booster shot with their doctor."

Compare this to the "**Beschluss der STIKO zur 16. Aktualisierung der COVID-19-Impfempfehlung** "... Wie das Epidemiologische Bulletin 2/2022 ausführt, kann die Auffrischimpfung mit einem mRNA-Impfstoff für Personen ≥18 Jahre bereits ab dem vollendeten 3. Monat nach Abschluss der Grundimmunisierung verabreicht werden. ..."

## Steps to reproduce the issue

Either scan available certificates into CWA and view the news output by the app or view the rules.

To view all rules run the following script in a Bash terminal:
```
for i in $(wget -qO- https://distribution.dcc-rules.de/bnrules | jq '.[].hash' | tr -d '"')
do
   echo $i 
   wget -qO-  https://distribution.dcc-rules.de/bnrules/$i | jq .
done
```

## Expected behavior

1. The rules used by CWA should correspond to the official recommendations published by the STIKO. See [RKI's website](https://www.rki.de/DE/Content/Infekt/Impfen/ImpfungenAZ/COVID-19/Impfempfehlung-Zusfassung.html).
2. For example, BNR-DE-0100 or equivalent should apply to 18 year-olds and older, not only to 70 year-olds and older.
3. BNR-DE-0100 and other rules should recommendation a 3 month wait, not a 6 month wait.
4. BNR-DE-0300 should be removed or combined with other rules, since it is not a STIKO recommendation, it is a BMG recommendation. In the meantime the STIKO recommendation already covers this situation.

## Possible Fix

Review all rules provided on https://distribution.dcc-rules.de/bnrules for conformity with the official STIKO recommendations published in [Epidemiologisches Bulletin 2 2022](https://www.rki.de/DE/Content/Infekt/EpidBull/Archiv/2022/Ausgaben/02_22.pdf?__blob=publicationFile). 

## Additional context

- See also https://github.com/corona-warn-app/cwa-documentation/issues/754.

## Reference

1. [STIKO-Empfehlung zur COVID-19-Impfung](https://www.rki.de/DE/Content/Infekt/Impfen/ImpfungenAZ/COVID-19/Impfempfehlung-Zusfassung.html):<br>
"**Beschluss der STIKO zur 16. Aktualisierung der COVID-19-Impfempfehlung**<br>
Die STIKO ändert ihre Empfehlung zur COVID-19-Auffrischimpfung hinsichtlich des Impfabstandes. Wie das Epidemiologische Bulletin 2/2022 ausführt, kann die Auffrischimpfung mit einem mRNA-Impfstoff für Personen ≥18 Jahre bereits ab dem vollendeten 3. Monat nach Abschluss der Grundimmunisierung verabreicht werden. Personen, die eine labordiagnostisch gesicherte SARS-CoV-2-Infektion durchgemacht haben, sollen bis auf weiteres eine einmalige COVID-19-Impstoffdosis im Abstand von mindestens 3 Monaten zur Infektion erhalten. Wegen des höheren Risikos für einen schweren COVID-19-Verlauf sollen ältere oder vorerkrankte Personen bei den Auffrischimpfungen unbedingt bevorzugt berücksichtigt werden.<br>
Dieser Artikel wurde am 21.12.2021 online vorab veröffentlicht."

2. The [Epidemiologisches Bulletin 2 2022](https://www.rki.de/DE/Content/Infekt/EpidBull/Archiv/2022/Ausgaben/02_22.pdf?__blob=publicationFile) published on Jan 13, 2022.

---
Internal Tracking ID: [EXPOSUREAPP-11340](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11340)

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Do you want to have two issues on a very similar topic or can we merge #754 and this issue?

I can adapt the OP of #754 to be more general & to inform about the fact that CWA BNR are out of date and don't reflect the latest recommendation changes.

**Comment by larswmh** [comment]
Thanks for your report @MikeMcC399. Internal Tracking ID: [EXPOSUREAPP-11340](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11340)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@larswmh Would it make sense to also mirror #754 to JIRA?

**Comment by larswmh** [comment]
> @larswmh Would it make sense to also mirror #754 to JIRA?

I have added your issue to the same internal ticket, thanks for the reminder.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> Do you want to have two issues on a very similar topic or can we merge #754 and this issue?
> 
> I can adapt the OP of #754 to be more general & to inform about the fact that CWA BNR are out of date and don't reflect the latest recommendation changes.

#754 is a question and this issue is a bug report
#754 covers the general issue across each new recommendation published by STIKO
This issue is specifically about the 16th STIKO recommendation.

I don't recommend to merge.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Okay, I think they could be merged, but how you like. (-:
I adapted the OP anyways.

**Comment by MikeMcC399** [comment]
@dsarkar / @larswmh 

Do we know who is responsible for updating the booster rules?
Why they are out of date?
If it is planned to update them?
And if so, when they will be updated?

We seem to be quite in the dark on this topic.

**Comment by MikeMcC399** [comment]
Whilst we are waiting for some feedback on the plans to implement the booster rules used by CWA based on the STIKO 16th recommendation, the 17th recommendation was published today. See [Beschluss der STIKO zur 17. Aktualisierung der COVID-19-Impfempfehlung](https://www.rki.de/DE/Content/Infekt/EpidBull/Archiv/2022/03/Art_02.html).

**Comment by MikeMcC399** [comment]
- I believe this issue is now superseded by issue #814 regarding the STIKO 17th recommendation, however I will leave this one open until there is some feedback.

**Comment by MikeMcC399** [comment]
- There has not been any feedback on this issue so far, so now closing this issue in favour of #814.
