### ISSUE TITLE
Adapt CWA to new COVID-19-Schutzmaßnahmen-Ausnahmenverordnung

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#807]
[Verordnung zur Änderung der COVID-19-Schutzmaßnahmen-Ausnahmenverordnung und der Coronavirus-Einreiseverordnung](https://www.bundesanzeiger.de/pub/publication/yW2hBRkcEPpvCQIb8IT/content/yW2hBRkcEPpvCQIb8IT/BAnz%20AT%2014.01.2022%20V1.pdf?inline) from 14. January 2022 made changes to the [Verordnung zur Regelung von Erleichterungen und Ausnahmen von Schutzmaßnahmen zur Verhinderung der Verbreitung von COVID-19 (COVID-19-Schutzmaßnahmen-Ausnahmenverordnung - SchAusnahmV)](https://www.gesetze-im-internet.de/schausnahmv/BJNR612800021.html). 
The changes came into effect on 15.01.2022.

The changes can be found in an easy & understandable way here: https://www.bundesgesundheitsministerium.de/service/gesetze-und-verordnungen/vo-aend-covid-19-schausnahmv-und-coronavirus-einreisev.

I don't feel qualified enough to make statements about what this means for CWA (e.g. if this means that one shot after J&J is no longer a booster), but what's sure is that the recovery status will only last for 3 months now, see also https://www.welt.de/vermischtes/article236274326/Corona-RKI-verkuerzt-Genesenenstatus-auf-drei-Monate.html.

@dsarkar @thomasaugsten @mlenkeit I think it would make sense to raise this issue ASAP, so that the legal department can make sure CWA does not make false statements. I guess the Sprint for 2.16 is closed, but maybe a hot fix is possible? 

---
Internal Tracking ID: [EXPOSUREAPP-11451](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11451)

**Comment by thomasaugsten** [comment]
The publisher is aware of the situation. Do you see any statements in the CWA which are wrong at the moment?

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Okay thanks! Recovery certificates are shown as valid for 6 months, however, they should only be valid 3 months.

**Comment by thomasaugsten** [comment]
This is encoded in the certificate. For adjustments either it needs new business rules or reissuing of the certificates

**Comment by Ein-Tim** [comment]
@thomasaugsten Ah yes, right. I guess new business rules will come anyways, as CovPassCheck needs to reject recovery certificates which certify an infection which took place more than 3 months ago.
Maybe a booster notification can be created to inform about this? 

I don't see any other statements which are wrong, besides this statement: 

https://github.com/corona-warn-app/cwa-app-ios/blob/a91392a6aaa3ec1cfdda4b107d82327776ba8a9d/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L3053 

> Es handelt sich hier um einen Impfstoff, bei dem nur eine Impfdosis erforderlich ist oder um eine Impfung für Genesene, die nur eine Impfdosis benötigt.

There are no vaccines which only require one dose atm, so this should be removed. Do you want me to provide a PR for this under iOS?

**Comment by thomasaugsten** [comment]
The topic is much more complex I don’t think it is enough to change this text line

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Exactly, this is why I opened this issue, so that the team makes sure everything is correct. Maybe you can mirror it to JIRA or link a ticket where these things are tracked?

**Comment by MikeMcC399** [comment]
The RKI reference page for the regulations on [Fachliche Vorgaben des RKI für COVID-19-Genesenennachweise](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Genesenennachweis.html) is updated and says:

"c) das Datum der Abnahme des positiven Tests darf höchstens 90 Tage zurückliegen"

Nothing published so far that I have seen addresses existing Genesenenzertifikate (Certificates of Recovery). These contain the field `r/du: Certificate valid until` which the EU json spec allows to be up to 180 days after the positive test.  Is there "Bestandsschutz" for existing certificates or does the new regulation affect these certificates as well?

I could not find any website which has already been updated to the 90 day rule. 
- https://reopen.europa.eu/en/map/DEU/7001 still lists 6 months
- https://www.zusammengegencorona.de/
- https://www.coronawarn.app/en/faq/#glossary_validity

Is the software used by doctors, pharmacies, etc. to generate certificates of recovery already changed to limit new certificates to 90 days of validity?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thanks for your comment! I really appreciate it! 

Would you like to open a new issue in the cwa-website repo reg. https://www.coronawarn.app/en/faq/#glossary_validity?

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> Would you like to open a new issue in the cwa-website repo reg.

I would wait for some clarification from the product owner how they will handle this change. It may need a blog announcement. Business rules, the app and the website could all be affected.

**Comment by Ein-Tim** [comment]
@MikeMcC399 Yeah, you're right!

**Comment by MikeMcC399** [comment]
There are a couple of places in the Android 2.16 app where 180 days is hard-coded. It seems that RKI can change the parameters on https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Genesenennachweis.html at any time, without notice. The app on the other hand is not set up to follow this dynamically as far as I can see.

**Comment by Ein-Tim** [comment]
@MikeMcC399 It would definitely make sense to have this as dynamic values. These can be adjusted much faster.

**Comment by larswmh** [comment]
Thanks for your report @Ein-Tim. Internal Tracking ID: [EXPOSUREAPP-11451](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11451)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
It gets more complex:
https://www.mdr.de/nachrichten/sachsen/corona-genesen-nachweis-ablauf-doppelt-geimpft-100.html:

> "Die Ablauffrist von drei Monaten gilt nur für ungeimpfte Personen", stellte das RKI auf Nachfrage von MDR SACHSEN klar. "Das liegt daran, dass doppelt geimpfte und genesene Personen einen besseren Immunschutz haben als ungeimpfte Genesene." Trotzdem empfehle die Ständige Impfkommision (STIKO) auch geimpften Genesenen die Booster-Impfung nach drei Monaten.

I think this is not what is written on https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Genesenennachweis.html, or am I wrong?

**Comment by Ein-Tim** [comment]
@thomasaugsten 

> Do you see any statements in the CWA which are wrong at the moment?

One J&J shot is shown as "2G" but it should be shown as nothing 😅

**Comment by MikeMcC399** [comment]
[Streit um Genesenenstatus: "Lauterbach behält Drei-Monats-Regel bei"](https://www.n-tv.de/politik/Lauterbach-behaelt-Drei-Monats-Regel-bei-article23085874.html) reports about political discussions regarding the length of validity of certificates of recovery for international travel (180 days) and for national use in Germany (90 days).

**Comment by Ein-Tim** [comment]
FYI: https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/97#issuecomment-1032259634

**Comment by mlenkeit** [comment]
> FYI: [Digitaler-Impfnachweis/covpass-ios#97 (comment)](https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/97#issuecomment-1032259634)
> 
> I guess this will be a new business rule and also affect CWA, or?

This will be reflected in CCL for now.

**Comment by Ein-Tim** [comment]
@mlenkeit

Okay, thanks. CCL isn't live yet, is it?

**Comment by mlenkeit** [comment]
> @mlenkeit
> 
> Okay, thanks. CCL isn't live yet, is it?

@Ein-Tim not yet, will be part of 2.18.

**Comment by Ein-Tim** [comment]
So, for the record: The entry rules for Germany have been updated to reflect that the recovery status is only valid for 90 days, see https://distribution.dcc-rules.de/rules/DE/71b10c1d78bcdd9e0f27afb6368a4a086d6d558616a1cd890765f6b1178d3325.

However, in contradictory to CovPass, CWA still shows "Genesenenzertifikat gültig bis..." while CovPass shows "Genesenenzertifikat höchstens gültig bis..." which makes more sense. 

| CWA | CovPass |
|---|---|
|![IMG_3490](https://user-images.githubusercontent.com/67682506/155378823-c1819a7a-6fc5-44c0-910d-41b8083ca702.jpeg)|![IMG_3491](https://user-images.githubusercontent.com/67682506/155378826-3f160cc5-e68d-43cf-ab1e-86dc3e8ba604.jpeg)|

**Comment by thomasaugsten** [comment]
We are working on an alignment for 2.20

**Comment by thomasaugsten** [comment]
The CWA is planning to remove the "gültig bis" text in the Detail view this is only visible in the pdf export.

**Comment by Ein-Tim** [comment]
@thomasaugsten Ah yes, I saw PRs for this! This definitely improves the situation!

**Comment by MikeMcC399** [comment]
@Ein-Tim 

The regulations changed again on March 18, 2022.

- https://www.bgbl.de/xaver/bgbl/start.xav#__bgbl__%2F%2F*%5B%40attr_id%3D%27bgbl122s0466.pdf%27%5D__1647763312928
- https://www.bgbl.de/xaver/bgbl/start.xav#__bgbl__%2F%2F*%5B%40attr_id%3D%27bgbl122s0478.pdf%27%5D__1647763393530

I don't know if this means that there are changes needed for CWA but it seems that the regulations are no longer dependent on the content of the RKI and PEI websites. The link you quoted (https://www.gesetze-im-internet.de/schausnahmv/BJNR612800021.html) has not yet edited the changes into the document.

**Comment by Ein-Tim** [comment]
Thank you @MikeMcC399 

I don't think the new regulations changed something which is needs adjustment in the CWA.
I'm only leaving this issue open until version 2.20 is released, so that I can verify the changed wording for recovery certificates ("Gültig bis" is changed to "Positiver Test vom").

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> I don't think the new regulations changed something which is needs adjustment in the CWA.

I don't know if that is true. The new `§ 22a Impf-, Genesenen und Testnachweis bei COVID-19; COVID-19-Zertifikate; Verordnungsermächtigung` of the  [Infektionsschutzgesetz - IfSG](https://www.gesetze-im-internet.de/ifsg/BJNR104510000.html) changed on March 18, 2022 is quite complicated and has some built in changes which come into effect on Oct 1, 2022.

I suggest anyway not to try to follow the new changes in this issue. If necessary there should be a new issue opened, otherwise it will be very difficult to follow.

I checked by the way in the pre-release of Android 2.20 and I can see the changes for certificates of recovery, which you are waiting for, already implemented.

**Comment by Ein-Tim** [comment]
> I suggest anyway not to try to follow the new changes in this issue. If necessary there should be a new issue opened, otherwise it will be very difficult to follow.

Agreed! I'll close this issue when 2.20 is released.

> I checked by the way in the pre-release of Android 2.20 and I can see the changes for certificates of recovery, which you are waiting for, already implemented.

Thank you!

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> Agreed! I'll close this issue when 2.20 is released.

I don't have a certificate of recovery to test with so unfortunately I can't assist with checking.

**Comment by Ein-Tim** [comment]
I have one and can confirm that this has been changed.

Closing.
