### ISSUE TITLE
Still "2G" with 3rd vaccination

### ISSUE THREAD

**Issue by FlightMS** [corona-warn-app/cwa-documentation#808]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 11
- iOS/Android version: 15.2.1
- App version: 2.16.1

## Describe the bug

In the vaccination overview I got the information that I met all requirements for "2G" but recently I've got my thrid vaccination and from now I met all requirements for "2G+" without an additional test. So it should be the same information in CWA aswell.

## Steps to reproduce the issue

![1](https://user-images.githubusercontent.com/82420268/149751715-e9d79d6b-a5b6-4139-a3c5-906b9f948e80.jpg)

1. Open CWA
2. Scan three certs
3. Open tab "Certificates"
4. Check "Status Nachweis"

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-11401](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11401)
Corona-Warn-App Open Source Team

**Comment by DerVogel2020** [comment]
This is not yet implemented. See the blog post to the current release 2.16: "Das Projektteam arbeitet bereits daran, dass die CWA in Zukunft Zertifikate von Auffrischimpfungen entsprechend einbezieht"

**Comment by Jo-Achim** [comment]
However, [this screenshot](https://www.coronawarn.app/de/screenshots/#android_certificates) is currently a bit misleading: 

![Screenshot_20220117-125325_Corona-Warn_2](https://user-images.githubusercontent.com/21124877/149767288-7b84b172-b37d-4e2a-ac56-5d2cabea47ba.jpg)

**Comment by Ein-Tim** [comment]
@Jo-Achim Why?

**Comment by Ein-Tim** [comment]
@DerVogel2020 & @FlightMS 

See also #797.

**Comment by dsarkar** [comment]
---
Internal Tracking ID: [EXPOSUREAPP-11401](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11401)
Corona-Warn-App Open Source Team

**Comment by Jo-Achim** [comment]
@Ein-Tim wrote: 
> @Jo-Achim Why? It's obvious that this person has stored a vaccination certificate and a test certificate in the app.

Ok, so the 2G+ hint is only partially working at the moment.

But hadn't we / you already listed rules in connection with the additional information "booster" on how a "booster" could be derived from the different vaccination combinations? Keywords: 3/3, 2/1, etc. 
Or am I wrong?

**Comment by Ein-Tim** [comment]
@Jo-Achim 

It is possible for the app to detect boosters (3/3 is a booster, 3/2 is also a booster, 2/1 is also a booster). However, as written in #797, this feature just didn't make it into the sprint.

With politics changing rules nearly weekly, we reach the limits of what can be done with agile software development. Either everything is made a server variable, so that it only needs server updates in the future, or we need someone who can predict the future, so that the app can keep up with politics (-;

**Comment by Jo-Achim** [comment]
> @Jo-Achim
> 
> It is possible for the app to detect boosters (3/3 is a booster, 3/2 is also a booster, 2/1 is also a booster). However, as written in #797, this feature just didn't make it into the sprint.
> 
> With politics changing rules nearly weekly, we reach the limits of what can be done with agile software development. Either everything is made a server variable, so that it only needs server updates in the future, or we need someone who can predict the future, so that the app can keep up with politics (-;

I think the answer is simple from my point of view: server variables.
I'm just afraid that the changeover to this will not be so easy at first and the necessary scope of updates will increase.

**Comment by dsarkar** [comment]
@FlightMS 

- See FAQ:
  - DE https://www.coronawarn.app/de/faq/#admission_policy
  - EN https://www.coronawarn.app/e/nfaq/#admission_policy
  - **DE** 
   > Wird bei 2G+ meine Auffrischimpfung berücksichtigt? 
   Laut Beschluss der Gesundheitsminister*innen von Bund und Ländern müssen Geimpfte oder Genesene, die eine Auffrischimpfung (Boosterimpfung) erhalten haben, bei einer 2G+-Regelung momentan keinen aktuellen Test vorlegen. Die Corona-Warn-App berücksichtigt diese Regelung in der Statusanzeige derzeit noch nicht. Bei vorhandenem Impf- oder Genesenenzertifikat und Zertifikat der Auffrischimpfung zeigt sie nicht den Status 2G+ an, sondern 2G. Das Projektteam arbeitet bereits daran, dass die Corona-Warn-App in Zukunft Zertifikate von Auffrischimpfungen entsprechend einbezieht.
  - **EN** 
  > Will 2G+ take my booster vaccination into account?
  > According to a decision by the federal and state health ministers, vaccinated or recovered persons who have received a booster vaccination are currently not required to submit a current test in the case of a 2G+ regulation. The Corona-Warn-App does not currently reflect this regulation in the status display. If a vaccination or recovery certificate and booster vaccination certificate are available, it will not display a 2G+ status, but will display 2G. The project team is already working on ensuring that the Corona-Warn-App will include certificates of booster vaccinations accordingly in the future.

- See also the blog article:
  - DE https://www.coronawarn.app/de/blog/2022-01-17-cwa-2-16/
  - EN https://www.coronawarn.app/en/blog/2022-01-17-cwa-2-16/
  - EN
  >2G+ with booster vaccination: According to the decision of German federal and state health ministers, vaccinated or recovered people who have received a booster vaccination do not have to provide a test certificate under a 2G plus arrangement. The CWA does not yet take this rule into account in the status display. This means that if a user has a vaccination or recovery certificate and a booster vaccination certificate, it does not display the status 2G+ yet. The project team is already working to ensure that the CWA includes booster vaccination certificates accordingly in the future.
  - DE
  >2G+ mit Auffrischimpfung: Geimpfte oder Genesene, die eine Auffrischimpfung (Boosterimpfung) erhalten haben, müssen laut Beschluss der Gesundheitsminister*innen von Bund und Ländern bei einer 2G-Plus-Regelung momentan keinen aktuellen Test vorlegen. Die CWA berücksichtigt diese Regelung in der Statusanzeige derzeit noch nicht. Das heißt, bei vorhandenem Impf- oder Genesenenzertifikat und Zertifikat der Auffrischimpfung zeigt sie noch nicht den 2G+-Status an. Das Projektteam arbeitet bereits daran, dass die CWA in Zukunft Zertifikate von Auffrischimpfungen entsprechend einbezieht.

Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by smares** [comment]
I don't understand how the 2G, 2G+, 3G, 3G+ feature went live without considering boosted people. Now every time I enter a restaurant or location that requires 2G+, I must explain how the CWA is wrong and that I actually do fulfill the 2G+ requirements. This was previously not the case because it was up to the person doing the check to judge if I fulfill 2G+, but now an official app says 2G only.

**Comment by Hanashi** [comment]
This is a critical bug. Why is this not fixed with the last version on wednesday?

**Comment by sznowicki** [comment]
Same here. According to [this document](https://www.hessen.de/sites/hessen.hessen.de/files/2021-12/21-12-16-auslegungshinweise_coschuv.pdf) I comply with 2G+ rule (1 Johnson dose + 1 Pfizer booster), yet people often don't understand it when I show my certs.

If the app shows 2G+ it would be a good proof when getting into restaurants and so on.

**Comment by DerVogel2020** [comment]
According to the mentioned document, yes.
But it seems that it is out of date since RKI and PEI changed their mind (last weekend) and after one JJ vaccination you need a second one (either JJ or mRNA) to be "vollständig geimpft".
So for 2G+ you need a test or a third vaccination.

**Comment by sznowicki** [comment]
> According to the mentioned document, yes.
> But it seems that it is out of date since RKI and PEI changed their mind (last weekend) and after one JJ vaccination you need a second one (either JJ or mRNA) to be "vollständig geimpft".
> So for 2G+ you need a test or a third vaccination.

Can you post some link?

**Comment by Ein-Tim** [comment]
Please check back with version 2.18, see: [CWA 2.18: Improving the display of the G status in the Corona-Warn-App](https://www.coronawarn.app/en/blog/2022-02-23-cwa-2-18).

I suggest closing this issue.

**Comment by FlightMS** [comment]
Yes - closed

**Comment by Di0gene** [comment]
I have the same issue. Why was this issue closed w/o being solved??

**Comment by BastianZim** [comment]
It’s fixed in the newest version. You’ll need to update your app to 2.18.1.

**Comment by Ein-Tim** [comment]
If you don't see version 2.18 yet, it is currently in staged rollout: https://www.coronawarn.app/en/faq/#release_time
