### ISSUE TITLE
User Story - git clone and build 

### ISSUE THREAD

**Issue by ArnoldSchiller** [corona-warn-app/cwa-documentation#81]
I know, all questions about the code will be closed, because it came 3 days ago. But regardless, it seems to me that only Google Play and IOS are planned in the user story. Neither Fdroid nor any OpenSource-OS - especially a privacy-critical audience is converting the phone to other operating systems. All you need is a git clone and build to test the app for exotics. This does not seem to be planned according to the documentation. At the moment it is not possible to test it in an early stage, because there is no code to be found far and wide. Will there be other support or will it be limited to the mainstream?

**Comment by tkowark** [comment]
Thanks for your question.

Regarding code, please see #61 
Regarding F-Droid Support, please look at #5

**Comment by ArnoldSchiller** [comment]
Oh I reading both. Aber irgendwie scheint das die neue Methode zu sein, einfach alles als Dublicate zu markieren. Hatte drei Tage gewartet und mein Rant lasse ich jetzt nicht in Englisch los. Tatsächlich wollte ich den Code, wenn er denn irgendwann mal verfügbar sein sollte auf android-x86 und auf meinem Raspi ausprobieren. Das wird wohl nie was werden.

**Comment by tkowark** [comment]
As said earlier, the code will be available, we just cannot give exact dates for the publication.

And regarding the second point: as stated in the architecture document and mentioned in the linked issues, our solution relies on the Exposure Notification Framework created by Google and Apple and hence the code will not run on platforms where this is not available.
