### ISSUE TITLE
Display 2G+ fails because standardization of the name leads to different results for vaccination certificates and test certificates

### ISSUE THREAD

**Issue by masema67** [corona-warn-app/cwa-documentation#810]
## Avoid duplicates
* [X ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)

## Technical details
- Device name: Google Pixel 4a 5G
- iOS/Android version: Android 12
- App version: 2.16.2

## Describe the bug
Standardization of the name leads to different results for vaccination certificates and test certificates with identical name display

There are no special characters in any part of my name.

Vaccination Certificate Displayed Name/First Name: AAAAAAA, BBBBBB – CCCCCCCCC DDDDD
Certificate of Vaccination Standard Name: AAAAAAA<<BBBBBB<<<CCCCCCCCC<DDDDD
Test Certificate 1 displayed Name/First Name: AAAAAAA, BBBBBB – CCCCCCCCC DDDDD
Test Certificate 1 Standard Name: AAAAAAA<<BBBBBBCCCCCCCCCDDDDD
Test Certificate 2 displayed Name/First Name: AAAAAAA, BBBBBB–CCCCCCCCC DDDDD
Test certificate 2 Standardized name: AAAAAAA<<BBBBBBCCCCCCCCCDDDDD

"Welcher Status wird Ihnen aktuell angezeigt?"
2G beim Impfzertifikat, 3G beim Testzertifikat
"Welchen Impfstatus und welche gültigen Zertifikate haben Sie aktuell in der App hinterlegt?" 
Impfstatus: "Sie haben nun alle derzeit geplanten Impfungen erhalten. Ihr Impfschutz ist vollständig" 
Impfzertifikate: 1 von 2 sowie 2 von 2

Update:
Test Certificate 3 displayed Name/First Name: AAAAAAA, BBBBBB>>>CCCCCCCCC>DDDDD
Test certificate 3 Standardized name: AAAAAAA<<BBBBBB>>>CCCCCCCCC>DDDDD
Test Certificate 4 displayed Name/First Name: AAAAAAA, BBBBBB<<<CCCCCCCCC<DDDDD
Test certificate 4 Standardized name: AAAAAAA<<BBBBBB<<<CCCCCCCCC<DDDDD

Test certificate 4 worked and 2G+ is displayed!!!

## Steps to reproduce the issue

see above

## Expected behaviour

The app should display 2G+ but fails

**Comment by Ein-Tim** [comment]
Is this related to https://github.com/Digitaler-Impfnachweis/certification-apis/issues/209?

**Comment by masema67** [comment]
> Is this related to [Digitaler-Impfnachweis/certification-apis#209](https://github.com/Digitaler-Impfnachweis/certification-apis/issues/209)?

I don't think so, this seems to be a real flaw in computing the standardized name

**Comment by Ein-Tim** [comment]
@masema67 

Exactly so maybe you have such a vaccination certificate where the standardized name is not correct?

**Comment by masema67** [comment]
> @masema67
> 
> Exactly so maybe you have such a vaccination certificate where the standardized name is not correct?

nope, the standardized name in the vaccination certificate is exactly the same as in my German ID card - the flaw is connected with the test certificate - see description above.
I managed now to manipulate my name now in such a way that 2G+ is displayed - but it works only if I enter already the standardized name for the test certificate

**Comment by masema67** [comment]
strange, no one seems to feel responsible for this bug even so it must highly affect a lot of users!

**Comment by Ein-Tim** [comment]
I don't encounter this bug.

**Comment by Ein-Tim** [comment]
@masema67 

Test centers are responsible to correctly enter the standardized name / to have a correct implementation of translating the "normal" to the standardized name.
I suggest you get in touch with the test center.

cc @thomasaugsten

**Comment by masema67** [comment]
> @masema67
> 
> Test centers are responsible to correctly enter the standardized name / to have a correct implementation of translating the "normal" to the standardized name. I suggest you get in touch with the test center.
> 
> cc @thomasaugsten

Are you sure that the test center software is normalizing / standardizing the name and not the CWA?
May you happen a link to that rule?
If so, and it concerns various test centers in Hamburg, I will try to contact them.

**Comment by masema67** [comment]
> I don't encounter this.
> 
> I have a RAT and a vaccination certificate stored in my app & they are grouped together nicely!

Ahh, interesting - another idea is that it has to do with double, triple first names, separated partly with a hyphen

**Comment by Ein-Tim** [comment]
@masema67 

> Are you sure that the test center software is normalizing / standardizing the name and not the CWA?
May you happen to have a link to that rule?

I suggest you read through https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki.

**Comment by masema67** [comment]
> @masema67
> 
> > Are you sure that the test center software is normalizing / standardizing the name and not the CWA?
> > May you happen to have a link to that rule?
> 
> I suggest you read through https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki.

Thank you!

**Comment by Ein-Tim** [comment]
@dsarkar could you forward this?

cc @thomasaugsten

**Comment by thomasaugsten** [comment]
What is the rat provider doing wrong?
He is mixing up first and last name in the standardized  name or adding to much < in the name
Can you give an example with a fake name please.

**Comment by masema67** [comment]
> testapp24.de
The error is connected with the spaces and hyphens in the first name, these are not respected and all is written in one word and not separated by "<"
Example:
Last name: Madonna
First names: Lenina – Sebastian Gunter
Displayed in the vaccination certificate:
Madonna, Lenina – Sebastian Gunter
Standardized name in the vaccination as well as in German ID (Personalausweis): 
MADONNA<<LENINA<<<SEBASTIAN<GUNTER
Standardized name in testapp24.de:
MADONNA<<LENINASEBASTIANGUNTER
When you enter in testapp24.de as first name (with "<":
Lenina<<<Sebastian<Gunter
And leave the last name unchanged
the following name is displayed: Madonna, Lenina<<<Sebastian<Gunter
and the standardized name is correctly displayed as
MADONNA<<LENINA<<<SEBASTIAN<GUNTER

Hope it helps

**Comment by thomasaugsten** [comment]
We informed testapp24 via TSI

**Comment by vaubaehn** [comment]
@thomasaugsten 
Thank you. Related to quality assurance of Abnahmetest, I will re-raise an issue related to ICAO in the quicktest-repo.

@masema67 
Maybe you can try a RAT again soon with testapp24.de? If it then works for you (grouping is correct), you may close this issue.
Thanks for your report.

**Comment by petrosit** [comment]
Hi, a fix is being developed now and show be available by latest end of this week.

**Comment by vaubaehn** [comment]
Hi @petrosit , great, nice to hear, thank you.

**Comment by petrosit** [comment]
> Hi @petrosit , great, nice to hear, thank you.

Should be fixed now :) Br

**Comment by masema67** [comment]
Today the test shows the correct standardized name and 2G+ is displayed.
