### ISSUE TITLE
Add a log entry with new cwa version info after a cwa update

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-documentation#811]
## Avoid duplicates
* [ ] This enhancement request has not already been raised before
* [ ] Enhancement request is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

The current error log starts with the configuration, like cwa version number, iOS version, device type.
This is very helpful.
However, the logging can be active during cwa updating to a newer version.
And in this case the new version number is not logged, which can be confusing or misleading.

## Suggested Enhancement

In case of cwa updating to a new version, add a log entry with the new version info.
Ideally in a similar format like the original entry, so it will be easy to find.

## Expected Benefits

Less confusion and clearer info when reading / analysing a long error log.

Note: I don't know the current Android implementation; but can imagine that this idea is also applicable for Android.
If this is true, feel free to move the ticket accordingly.

---
Internal Tracking ID: [EXPOSUREAPP-11560](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11560)

**Comment by larswmh** [comment]
Thanks for your report @ndegendogo. I have moved this issue to another repository, as this is applicable to both Android and iOS. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-11439](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11439)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Is there any update on this 3 months old issue available?

**Comment by ndegendogo** [comment]
For iOS it is resolved!
In my log file I see entries like:

932932 Debug 2022-04-04T06:16:35Z
932933 [ENA/HomeTableViewController.swift:737] [showDeltaOnboardingIfNeeded(completion:)]
932934 Start onboarding.
932935 
932936 Debug 2022-04-04T06:16:35Z
932937 [ENA/DeltaOnboardingProtocols.swift:23] [isFinished]
**932938 Check, if 2.20ENA.DeltaOnboardingNewVersionFeatures is already finished or not needed (current onboarding version = 2.19.1...**
932939 
932940 Debug 2022-04-04T06:16:35Z
932941 [ENA/DeltaOnboardingProtocols.swift:26] [isFinished]
932942 DeltaOnboarding 2.20ENA.DeltaOnboardingNewVersionFeatures already presented? false.

For Android I cannot tell...

**Comment by Ein-Tim** [comment]
I will check when 2.21 under Android.

**Comment by Ein-Tim** [comment]
I just received 2.21 but somehow the app stopped logging after the update. Maybe @MikeMcC399 could cross check here:

1. Start logging on version 2.20
2. Update to version 2.21
3. Let us know if the log still runs after the update

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I checked for the CWA Android update from version 2.19.2 to 2.20.3

Running CWA 2.19 shows
`I/CWADebug: CWA version: 2190201 (no commit hash)`
Updating to CWA 2.20
`I/CWADebug: CWA version: 2200300 (no commit hash)`

If in your case the app stopped logging, that would be a separate issue. I expect it will be another 48 hours or so before I have access to the released 2.21 Android version.

**Comment by MikeMcC399** [comment]
@ndegendogo 

I think this issue can be closed. Thanks for opening this issue. It was a good request / suggestion!

**Comment by Ein-Tim** [comment]
Thanks @MikeMcC399!

**Comment by ndegendogo** [comment]
Closing as fixed.

**Comment by dsarkar** [comment]
@ndegendogo @MikeMcC399 @Ein-Tim thanks for the feedback. CONFIRM forwarded to internal ticket.
