### ISSUE TITLE
Johnson is now two-dose-vaccine

### ISSUE THREAD

**Issue by jmw168** [corona-warn-app/cwa-documentation#812]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [ ] Bug is not already reported in another issue

## Describe the bug

In the CWA app, Johnson is still treated as a one-dose-vaccine. But at federal level and serveral, if not all states, it is now categorized as a two doese vaccine: https://www.pei.de/DE/newsroom/dossier/coronavirus/coronavirus-inhalt.html?nn=169730&cms_pos=3 This should be changed because it's causing massive confusion, when it says in the app it fulfils 2G but it says in the law it doesn't fulfil 2G.

## Possible Fix

change status of Johnson in the app e.g. here: https://github.com/corona-warn-app/cwa-app-android/blob/main/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/vaccination/core/VaccinationCertificate.kt

---
Internal Tracking ID: [EXPOSUREAPP-11454](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11454)

**Comment by Ein-Tim** [comment]
See also #807.

**Comment by larswmh** [comment]
Thanks for your report @jmw168. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-11454](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11454)

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
The legal reference for this is the:

[Verordnung zur Regelung von Erleichterungen und Ausnahmen von Schutzmaßnahmen zur Verhinderung der Verbreitung von COVID-19 (COVID-19-Schutzmaßnahmen-Ausnahmenverordnung - SchAusnahmV)](https://www.gesetze-im-internet.de/schausnahmv/BJNR612800021.html) 
Stand: Zuletzt geändert durch Art. 1 V v. 14.1.2022 BAnz AT 14.01.2022 V1

in § 2 Begriffsbestimmungen 3. where the definition is delegated to

[www.pei.de/impfstoffe/covid-19](https://www.pei.de/impfstoffe/covid-19) and currently this website says:

Impfstoff | Anzahl Impfdosen für die vollständige Impfung
--- | ---
COVID-19 Vaccine Janssen<br>Zul.-Nr EU/1/20/1525 | 2

Thanks to @Ein-Tim in https://github.com/corona-warn-app/cwa-documentation/issues/807 for the legal link and for raising the issue also for the website in https://github.com/corona-warn-app/cwa-website/issues/2345.

**Comment by NotTheEvilOne** [comment]
Please be aware that this change is most likely illegal and should be reverted as soon as possible until final decision of an authorized party like the  European Medicines Agency is done.

The unauthorized change of validity of the PEI is being dissent by one court so far. See [1]. More will most likely follow. Furthermore its a discrepancy to all other European Countries and the decision of the European Medicines Agency [2].

[1] https://www.berlin.de/gerichte/verwaltungsgericht/presse/pressemitteilungen/2022/pressemitteilung.1178438.php
[2] https://www.ema.europa.eu/en/medicines/human/EPAR/covid-19-vaccine-janssen

**Comment by MikeMcC399** [comment]
§ 2 of [COVID-19-Schutzmaßnahmen-Ausnahmenverordnung - SchAusnahmV](https://www.gesetze-im-internet.de/schausnahmv/BJNR612800021.htm) before March 18, 2002 gave the authority of determining vaccination status to http://www.pei.de/impfstoffe/covid-19. That authority is removed from the website of the Paul-Ehrlich-Institut and instead [SchAusnahmV](https://www.gesetze-im-internet.de/schausnahmv/BJNR612800021.htm) refers to a new "§ 22a Impf-, Genesenen und Testnachweis bei COVID-19; COVID-19-Zertifikate; Verordnungsermächtigung" in the updated [Infektionsschutzgesetz - IfSG](https://www.gesetze-im-internet.de/ifsg/BJNR104510000.html).

I can't see any specific mention of Johnson & Johnson's "COVID-19 Vaccine Janssen" in the current regulations.

I don't know how this works with local federal state regulations. Perhaps somebody has investigated this point?

**Comment by Ein-Tim** [comment]
I think this issue has been resolved and should be closed now @jmw168.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

This should be tracked in a new issue IMO.

**Comment by jmw168** [comment]
> I think this issue has been resolved and should be closed now @jmw168.

I belive so. I can see, that the whole meachism got outsourced to a server-based approach but I can't identify where the server exactly is and if it is fixed there. In my understanding the responsibility for the "who is vaccinated" got outsurced to the authorities, therfore it if fixed for this repository.

I would be happy if someone could explain me, where I can find the data now, but this is no matter of this issue.

**Comment by Ein-Tim** [comment]
> I would be happy if someone could explain me, where I can find the data now, but this is no matter of this issue.

The best starting point is probably https://github.com/corona-warn-app/cwa-app-ccl
