### ISSUE TITLE
Different texts under iOS and Android (Align Android to iOS)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#813]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: not relevant
- iOS/Android version: not relevant
- App version: 2.16.2

## Describe the bug

iOS uses this text:

https://github.com/corona-warn-app/cwa-app-ios/blob/ffda2284b9bcb5beef08657288221c087b645247/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L126

> Lassen Sie sich testen, auch wenn Sie keine Symptome haben. Bei einer Warnung über ein erhöhtes Risiko ("Rote Kachel") haben Sie Anspruch auf einen kostenlosen Test. Abhängig von den örtlichen Regelungen kann Ihr Anspruch auf einen kostenlosen Antigen-Schnelltest beschränkt sein. Wir regen an, einen PCR-Test durchführen zu lassen, vor allem, wenn der Test kostenlos ist.

Android uses this text:

https://github.com/corona-warn-app/cwa-app-android/blob/658f702021dfce94278be40fdf9c43f386574ec3/Corona-Warn-App/src/main/res/values-de/strings.xml#L274

> Lassen Sie sich testen, auch wenn Sie keine Symptome haben. Bei einer Warnung über ein erhöhtes Risiko („Rote Kachel“) haben Sie Anspruch auf einen kostenlosen Test. Dies muss nicht notwendigerweise ein PCR-Test sein.

## Steps to reproduce the issue

1. Get a red warning under both, iOS and Android
2. Read the texts
3. See that the texts differ between iOS and Android

## Expected behaviour

iOS and Android should use the same text.

## Possible Fix

Use the text from the iOS implementation in Android too. 

---
Internal Tracking ID: [EXPOSUREAPP-11513](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11513)

**Comment by MikeMcC399** [comment]
On a related point, the screenshot in the iOS German section for CWA 2.16 shows the wrong text, because in fact it is a screenshot from Android.

See https://www.coronawarn.app/de/screenshots/#ios_cards is linked to https://www.coronawarn.app/assets/screenshots/2-16/de/android/high_risk_2.png

**Comment by larswmh** [comment]
Thanks for your report @Ein-Tim. Internal Tracking ID: [EXPOSUREAPP-11513](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11513)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
PR fixing this: https://github.com/corona-warn-app/cwa-app-ios/pull/4121

iOS will be aligned to Android.

**Comment by Ein-Tim** [comment]
This has been fixed. Closing.
