### ISSUE TITLE
Booster rules not updated to STIKO 17th recommendation

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#814]
## Technical details

- Booster rules from https://distribution.dcc-rules.de/bnrules
- Applies to App versions (iOS and Android): 2.10 and later

## Describe the bug

Booster rules used by the app do not reflect the 17th STIKO recommendations as published in [Epidemiologisches Bulletin 3 2022](https://www.rki.de/DE/Content/Infekt/EpidBull/Archiv/2022/Ausgaben/03_22.pdf?__blob=publicationFile).

## Steps to reproduce the issue

Either scan available certificates into CWA and view the news output by the app or view the rules.

To view all rules run the following script in a Bash terminal:
```
for i in $(wget -qO- https://distribution.dcc-rules.de/bnrules | jq '.[].hash' | tr -d '"')
do
   echo $i 
   wget -qO-  https://distribution.dcc-rules.de/bnrules/$i | jq .
done
```

## Expected behavior

The rules used by CWA should correspond to the official recommendations published by the STIKO. See [RKI's website](https://www.rki.de/DE/Content/Infekt/Impfen/ImpfungenAZ/COVID-19/Impfempfehlung-Zusfassung.html).

## Possible Fix

Review all rules provided on https://distribution.dcc-rules.de/bnrules for conformity with the official STIKO recommendations published in [Epidemiologisches Bulletin 3 2022](https://www.rki.de/DE/Content/Infekt/EpidBull/Archiv/2022/Ausgaben/03_22.pdf?__blob=publicationFile).

## Additional context

- See also https://github.com/corona-warn-app/cwa-documentation/issues/754 and
- https://github.com/corona-warn-app/cwa-documentation/issues/806

## Reference

1. [STIKO-Empfehlung zur COVID-19-Impfung](https://www.rki.de/DE/Content/Infekt/Impfen/ImpfungenAZ/COVID-19/Impfempfehlung-Zusfassung.html):<br>
"Am 20.1.2022 ist die 17. Aktualisierung der COVID-19-Impfempfehlung erschienen. Darin empfiehlt die STIKO die Auffrischimpfung für 12- bis 17-jährige Kinder und Jugendliche mit dem mRNA-Impfstoff Comirnaty (30 μg), in einem Zeitfenster von 3 bis 6 Monaten nach der abgeschlossenen Grundimmunisierung. Die STIKO empfiehlt außerdem die Optimierung der Grundimmunisierung mit einem mRNA-Impfstoff nach vorausgegangener Impfung mit der COVID-19 Vaccine Janssen und auch hier eine 3. Impfstoffdosis (Auffrischimpfung) im Abstand von mindestens 3 Monaten zur 2. Impfstoffdosis mit einem mRNA-Impfstoff."

2. The [Epidemiologisches Bulletin 3 2022](https://www.rki.de/DE/Content/Infekt/EpidBull/Archiv/2022/Ausgaben/03_22.pdf?__blob=publicationFile) published on Jan 20, 2022.

---
Internal Tracking ID: [EXPOSUREAPP-11340](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11340)

**Comment by larswmh** [comment]
Thanks for your report @MikeMcC399. We have added this information to the same internal ticket that we used for the 16th recommendation.
Internal Tracking ID: [EXPOSUREAPP-11340](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11340)

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@larswmh 

Thank you. Can you give some indication of the plans?

**Comment by larswmh** [comment]
@MikeMcC399 

We will ask internally about when implementation is planned.

**Comment by MikeMcC399** [comment]
@larswmh 
> We will ask internally about when implementation is planned.

What was the result of your internal question?

**Comment by MikeMcC399** [comment]
- Question also asked in https://github.com/Digitaler-Impfnachweis/covpass-android/discussions/185.

**Comment by MikeMcC399** [comment]
The current booster rules on https://distribution.dcc-rules.de/bnrules contain no rules for holders of a Certificate of Recovery.

The [Epidemiologisches Bulletin 3 2022](https://www.rki.de/DE/Content/Infekt/EpidBull/Archiv/2022/Ausgaben/03_22.pdf?__blob=publicationFile) contains recommendations in Table 5 on page 18 (Empfehlung zur Durchführung der Grundimmunisierung und Auffrischimpfung bei unterschiedlichen Impfanamnesen und nach durchgemachter SARS-CoV-2-Infektion bei Immungesunden (Stand: 20.01.2022)) which includes a recommendation for vaccination after 3 months following an infection.

It would be important to activate such a rule in CWA, also with regard to the shortening of validity of Certificate of Recovery from 180 days to 90 days by the German government regulations and RKI promulgations which took effect on Jan 15, 2022. 

- See [www.rki.de/covid-19-genesenennachweis](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Genesenennachweis.html).
- See also https://github.com/corona-warn-app/cwa-website/issues/2409 for list of references.

**Comment by GisoSchroederSAP** [comment]
@All, we are working on a statement about the approach to planning and implementing features in the app. Please keep in mind that our objective is to stay as up-to-date as possible with the app. However, development (including testing) will always lag behind the current decision-making process.
So, yes, we are aware that the released version may not always reflect national and/or regional rulings or dynamically changing decisions and recommendations of the authorities. 
However, we will use the momentum and we are on track to cover the ongoing legislative amendments with the next versions of the app.

Please remain patient.

**Comment by MikeMcC399** [comment]
The [STIKO-Empfehlung zur COVID-19-Impfung](https://www.rki.de/DE/Content/Infekt/Impfen/ImpfungenAZ/COVID-19/Impfempfehlung-Zusfassung.html) has been updated:<br>
"Am 15.2.2022 ist die 18. Aktualisierung der COVID-19-Impfempfehlung erschienen. Darin empfiehlt die STIKO nach abgeschlossener COVID-19-Grundimmunisierung und erfolgter 1. Auffrischimpfung eine 2. Auffrischimpfung mit einem mRNA-Impfstoff für besonders gesundheitlich gefährdete bzw. exponierte Personengruppen.
Alternativ zu den bereits empfohlenen COVID-19-Impfstoffen empfiehlt die STIKO zur Grundimmunisierung gegen COVID-19 den Impfstoff Nuvaxovid von Novavax für Personen ≥18 Jahre mit 2 Impfstoffdosen im Abstand von mindestens 3 Wochen".

Closing this issue, which explicitly refers to the 17th recommendation, since it is now obsolete. The 18th recommendation is now current.

- The more general issue https://github.com/corona-warn-app/cwa-documentation/issues/754 remains unaddressed.

**Comment by MikeMcC399** [comment]
@GisoSchroederSAP 
> we are working on a statement about the approach to planning and implementing features in the app.

- I don't understand how app features are relevant to the booster rules which are not part of the app. Issue #754 is basically unanswered for the last 3 months and without an explanation it is difficult to understand why no updates have been made during this time to the booster rules which are used by both CWA and CovPass. Perhaps the Open Source Team could follow up in #754?
