### ISSUE TITLE
Fully vaccinated statistics display in app

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#816]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue
* See also discussion https://github.com/corona-warn-app/cwa-documentation/issues/815

## Technical details

- App version: 2.16.2 and earlier versions

## Describe the bug

RKI has changed the term they use on the page [Digitales Impfquotenmonitoring zur COVID-19-Impfung](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquoten-Tab.html). Now they are using the term "Grundimmunisiert" where a couple of days ago the graph was labelled "vollständig geimpft".

App Screenshot:

![Vollständig geimpft](https://user-images.githubusercontent.com/66998419/150545277-a36a7d99-230d-4251-8813-9de13ae8411c.png)

[RKI website](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquoten-Tab.html):

![RKI Impfquotenmonitoring](https://user-images.githubusercontent.com/66998419/150545252-9462b3ad-9598-458d-9adb-170d6dfc8eff.jpg)

The CWA app and the RKI statistics pages should be aligned in the use of terms.

## Steps to reproduce the issue

1. Open CWA
2. Scroll down to statistics tiles
3. Scroll right to "People Who Are Fully Vaccinated" (EN) or "Vollständig geimpfte Personen"

See also
- https://www.coronawarn.app/en/screenshots/#android_stats
- https://www.coronawarn.app/en/screenshots/#ios_stats
- https://www.coronawarn.app/de/screenshots/#android_stats
- https://www.coronawarn.app/de/screenshots/#ios_stats

## Expected behaviour

Terms used by the app should conform to how RKI uses the term "grundimmunisiert"

## Possible Fix

Change the app to use the term "grundimmunisiert" and equivalent agreed English language term instead of "vollständig geimpft".

---
Internal Tracking ID: [EXPOSUREAPP-11520](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11520)

**Comment by larswmh** [comment]
Thanks for your report @MikeMcC399. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-11520](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11520)

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
Screenshot added above.

**Comment by Jo-Achim** [comment]
In this context, please also think about the necessary text change behind the "i" (key figures - explanation of the statistics). 

--------

With cross-reference to [Add new statistic tile: Booster Shots administered](https://github.com/corona-warn-app/cwa-wishlist/issues/685#issue-1057737215)...
The question would be, whether the then available data may also allow conclusions to be drawn about the _respectively_ 'fully vaccinated' persons and whether this should be shown on an (additional) statistical card. 
However, I refer to [Legal term definition "Vollständig geimpft" (FAQ from RKI)](https://github.com/corona-warn-app/cwa-documentation/issues/815#issue-1110479265).

**Comment by MikeMcC399** [comment]
- PR https://github.com/corona-warn-app/cwa-app-ios/pull/4156 for iOS
- PR https://github.com/corona-warn-app/cwa-app-android/pull/4760 for Android

Both are included in their respective 2.18.0 milestones.

**Comment by Ein-Tim** [comment]
I can confirm that this has been fixed with version 2.18 under iOS.

**Comment by MikeMcC399** [comment]
Fixed in CWA Android 2.18.1

EN text: "People Who Have Basic Immunization"
DE text:  "Grundimmunisiert"

Thanks to @Ein-Tim for checking on iOS.

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim Thanks for reporting and feedback.
