### ISSUE TITLE
CWA uses wrong validity periods for tests (48h instead of 24h for RATs & 72h instead of 48h for PCRs)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#819]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Not important
- iOS/Android version: Not important
- App version: 2.16.2

## Describe the bug

The Corona-Warn-App uses wrong validity periods for tests at the moment.

The app shows RATs as valid for 48h instead of 24h and PCR for 72h instead of 48h.

## Steps to reproduce the issue

1. Add a PCR test certificate & RAT to the CWA
2. See when the RAT shows as invalid on the "Status" screen
3. See when the PCR test is no longer used for the 2G+ status on the "Certificates" screen

## Expected behaviour

CWA should use the correct values

## Possible Fix

Adjust the logic.

## Source

https://www.zusammengegencorona.de/informieren/alltag-und-reisen/aktuelle-regelungen/ states:
> Die sogenannte 3G-Regel steht für „geimpft, genesen oder getestet“. Wer nicht vollständig geimpft ist oder nicht als genesen gilt (mehr dazu hier) muss in bestimmen Fällen entweder einen **negativen Schnelltest (maximal 24 Stunden alt)** oder einen **negativen PCR-Test (maximal 48 Stunden alt)** vorlegen.

---
Internal Tracking ID: [EXPOSUREAPP-10853](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10853)

**Comment by dsarkar** [comment]
@Ein-Tim this validity periods are correct for entering Germany form another country, and the business rules reflect this currently. Do we have a wishlist item, to distinguish entry rules and "internal national" rules? If not, would you open an issue in the wishlist repo?

**Comment by dsarkar** [comment]
@Ein-Tim Or I transfer this to wishlist and you re-write this as a new user story?

**Comment by Ein-Tim** [comment]
@dsarkar 

PCR tests for entry are only allowed to be 48h, see https://www.auswaertiges-amt.de/de/quarantaene-einreise/2371468#content_2. 

So this should definetely be adjusted, do you agree with me?

Regarding RAT: I think it makes no sense to use the rules for entering Germany for the Corona-Warn-App, as you only get a QR code to register the test in the Corona-Warn-App inside of Germany. 

So, in conclusion: This is a bug and **not** an enhancement request.

**Comment by dsarkar** [comment]
@Ein-Tim Reg. PCR, agreed, business rules should be adopted. Reg. RAT: However we call it, there is a difference in the rules when entering a country and when accessing venues within a country. The business rules reflect "travel validity" to enter a country, and these rules are applied by verifier apps, like the CovPassCheck-App. There are no "business rules" defined for use within a country, but only entering. A possible approach to solve this, could be changing what is displayed in the CWA.

**Comment by Ein-Tim** [comment]
@dsarkar 

> Reg. PCR, agreed, business rules should be adopted

Okay, have you mirrored this to JIRA so that it can be adopted soon? This would be nice, thanks!

> Reg. RAT: However we call it, there is a difference in the rules when entering a country and when accessing venues within a country. The business rules reflect "travel validity" to enter a country, and these rules are applied by verifier apps, like the CovPassCheck-App. There are no "business rules" defined for use within a country, but only entering. A possible approach to solve this, could be changing what is displayed in the CWA.

Yeah, you're right. I will think of this and open a new issue when I found solution.

**Comment by alanrick** [comment]
Just to add that to enter Portugal the RAT validity is **48 hours.** I'm not sure what other countries require, so I'd prefer text, rather than the test result disappearing.

**Comment by Ein-Tim** [comment]
Relaxed issue #855 opened.

**Comment by Ein-Tim** [comment]
@alanrick 

The change would only be that test DCCs are not used as standard after 24h anymore and indeed we have to think about how the tile on the "Status" tab should be handled.

**Comment by Jo-Achim** [comment]
I have to agree with @Ein-Tim a little bit. The analogous statement of 'Your test result (quick test) is no longer displayed because it is older than 48 hours' is irritating. And if the CWA is actually a national app and quick tests are only valid for 24 hours in Germany... the question is whether at least textual reference to different national / international validity should be added. 

If I have understood the above statements correctly, the corresponding text in the following example and context could possibly read:
> Quick test
> Test is no longer up-to-date
> Your rapid test is older than 24 hours national / 48 hours international and is no longer displayed here. 

In other texts and contexts, "24 hours national / 48 hours international" could possibly help further.

**Comment by Ein-Tim** [comment]
@mlenkeit Is there any update available here? Will this be fixed soon? Is the RKI fine with it's own apps not applying the rules it makes? I can't imagine this.

**Comment by thomasaugsten** [comment]
On the business rules we have no influence
For the G Status the longer validity was chosen because in some states are accepting the longer validity-

**Comment by Ein-Tim** [comment]
@thomasaugsten You mean some federal states?

**Comment by Ein-Tim** [comment]
@thomasaugsten Mh, okay, that's strange because all sites from the federal government spoke about 24h as validity time. Has this issue been brought to RKIs attention and they agreed to it?

**Comment by svengabr** [comment]
I have just checked the linked Jira issue.

Jira Ticket is flagged as:
Resolution: `Wont Fix`
Status: `Obsolete`

Developer comment:
> Closing the issue as its not related to the App

Unfortunately, no additional information was added to this Jira ticket.

**Comment by Ein-Tim** [comment]
I am still not fine with the closing of this issue. Please reopen it @svengabr & @dsarkar.

**Comment by sapcoder123** [comment]
@Ein-Tim Issue reopened

**Comment by Ein-Tim** [comment]
Thanks @sapcoder123!

**Comment by Ein-Tim** [comment]
This issue seems obsolete and has become stale.
