### ISSUE TITLE
cwa-schnelltest-onboarding@t-systems.com no reaction

### ISSUE THREAD

**Issue by celevra** [corona-warn-app/cwa-documentation#820]
sorry to use this Platform for this kind of problems, but i see no other way to contact the right person

we need to get access to the api for fasttests. We have written to cwa-schnelltest-onboarding@t-systems.com on the 5th januar, these are 20 Days now....
We need to get in prodaction with our app, it could not be that we have to wait that long to sign the contracts and get an api key....

how to proceed?

regards

Philipp Zeitschel

**Comment by Ein-Tim** [comment]
@dsarkar I suggest to move this issue to https://github.com/corona-warn-app/cwa-quicktest-onboarding.

FYI @ilya-smirnov-berlin

**Comment by celevra** [comment]
thanks, i will do that

**Comment by dsarkar** [comment]
@celevra  @Ein-Tim  indeed, I was just about to suggest that.


Best wishes, DS

---
Corona-Warn-App Open Source Team
