### ISSUE TITLE
Fehlerhafte Reisegültigkeit nach frischer Drittimpfung

### ISSUE THREAD

**Issue by dexX7** [corona-warn-app/cwa-documentation#821]
Wenn ein Zertifikat einer kürzlichen Drittimpfung, die weniger als 14 Tage alt ist, auswählt und dann eine Reisegültigkeit für beispielsweise Spanien auswählt, dann wird das Zertifikat fälschlicherweise als nicht akzeptiert ausgewertet, da das letzte Zertifikat nicht älter als 14 Tage ist. Fehlercode: VR-ES-0003 (1.0.0).

Wenn ein älteres Zertifikat mit einer gültigen, vollständigen, Impfung auswählt wird, die älter als 14 Tage ist, beispielsweise das Zertifikat der zweiten Impfung, ist die Prüfung korrekt.

Ich vermute, dass Spanien eine Regel hat, dass 14 Tage nach einer vollständigen Impfung vergehen müssen.

In der aktuellen Version wird zwar das Alter der letzten Impfung geprüft, nicht beachtet wird jedoch, dass es auch einen früheren korrekten Impfstatus gibt, nämlich von der zweiten Impfung.

---
Internal Tracking ID: [EXPOSUREAPP-11552](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11552)
[Business rules] [ES] VC 9 month validity from 1 Feb 2022 on.

Internal Tracking ID: [EXPOSUREAPP-11134](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11134)
[Business rules] [ES] Spain does not accept 3/3 DCCs for 14 days

**Comment by dsarkar** [comment]
@vaubaehn Thanks a lot for the comments, Spain has been contacted from what I can see in the internal ticket.

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-11552](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11552)
[Business rules] [ES] VC 9 month validity from 1 Feb 2022 on.


Internal Tracking ID: [EXPOSUREAPP-11134](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11134)
[Business rules] [ES] Spain does not accept 3/3 DCCs for 14 days

**Comment by thomasaugsten** [comment]
ES Update 
https://github.com/eu-digital-green-certificates/dgc-business-rules-testdata/pull/103

**Comment by Ein-Tim** [comment]
I think this issue has been fixed, or?

**Comment by Ein-Tim** [comment]
It seems like https://timokoenig.github.io/eu-dcc-rules/?ruleset=eu-dcc-rules&country=ES&rule=VR-ES-0005 still causes problems: https://twitter.com/TheAndi95/status/1516049707994390530?s=20&t=mgjDZUsscDeya6oeLzvEiQ

**Comment by dsarkar** [comment]
@dexX7 @Ein-Tim This issue has been fixed. Thanks for reporting. We are closing this issue now. Should it be necessary, please re-open or create a new issue. Best wishes, DS

---
Corona-Warn-App Open Source Team
