### ISSUE TITLE
First and last name in EU test certificate are swapped

### ISSUE THREAD

**Issue by karlbeecken** [corona-warn-app/cwa-documentation#824]
## Technical details

- Device name: iPhone 12
- iOS version: iOS 15.2.1
- App version: 2.16.2

## Describe the bug

Whenever I register a test (be it an antigen test or a PCR test), the first and last name in the eu certificate are swapped and thus the 2G+ status will not be shown correctly, instead there are two certificates: one 2G for the vaccination (which is wrong, because I'm boostered, but that's another issue) and one seperate with 3G(+) for the test.

## Steps to reproduce the issue

1. be vaccinated and have the certificate imported in your CWA
2. get tested and import the test certificate

![image](https://user-images.githubusercontent.com/32744028/151130597-aadfac6b-29a6-4284-a122-4010a3432819.png)
![image](https://user-images.githubusercontent.com/32744028/151130632-6aa1ad4e-a2bb-4af5-b1e8-6921673e2562.png)

## Expected behaviour

I expect the CWA to be resilient to a certain degree to swapped first and last names. I got tested in several private and the Berlin state owned test centers, and all swapped the first and last name.

## Possible Fix

There are imo two possible fixes:
1. improve the UI for the test centers so that this swap doesn't happen (i.e. swap first and last name field, because everyone expects the first name first and the last name second today)
2. improve the resilience of the CWA to this mistake, for example do cross-checking of first and last names in the certificates and not only compare first to first and last to last

Ideally also be resilient to test certificates that only include the first first name (i.e. my full name is Karl Felix Beecken, but I always never use the Felix name, but in the vaccination certificate it is included. Using the standardized name it should be possible to strip the second, third... first names away and check only the first as most people only use their first)

**Comment by Ein-Tim** [comment]
I'm unsure whether this "names switched" case is considered with the improved certificate assignment of CWA 2.19 (see blog post[CWA 2.19 improves the assignment of certificates to persons]( https://www.coronawarn.app/en/blog/2022-03-16-cwa-2-19/)).

Maybe @thomasaugsten could quickly clarify?

**Comment by thomasaugsten** [comment]
Improved certificate assignment includes switched first and lastname

**Comment by Ein-Tim** [comment]
Thanks @thomasaugsten!

I suggest to close this issue now @karlbeecken.
