### ISSUE TITLE
master and main branches?

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#826]
Is it deliberate to have a [main](https://github.com/corona-warn-app/cwa-documentation/tree/main) branch in this repository in addition to the default branch [master](https://github.com/corona-warn-app/cwa-documentation/tree/master)?

Some of the repositories in this organisation have updated their default branch from `master` to `main`, for example [cwa-app-android](https://github.com/corona-warn-app/cwa-app-android), but it's not usual to have both names actives in one repository. Having both branch names active may cause human errors. (Changing the default branch on the other hand has tended to break links from other repositories in the past.)

**Comment by Ein-Tim** [comment]
`main` seems to lag behind `master` at the moment.

**Comment by svengabr** [comment]
I can speak on behalf of [cwa-website](https://github.com/corona-warn-app/cwa-website), we are now planning to rename `master` to `main` once the team has finished their current work that should go live today.

**Comment by MikeMcC399** [comment]
@svengabr 
> I can speak on behalf of [cwa-website](https://github.com/corona-warn-app/cwa-website), we are now planning to rename `master` to `main` once the team has finished their current work that should go live today.

You refer to [cwa-website](https://github.com/corona-warn-app/cwa-website). I was asking for this repository [cwa-documentation](https://github.com/corona-warn-app/cwa-documentation). So now I am confused about what actions are planned to be take and where. Could you clarify if the changes are to be done on [cwa-website](https://github.com/corona-warn-app/cwa-website) on [cwa-documentation](https://github.com/corona-warn-app/cwa-documentation) or on both?

**Comment by svengabr** [comment]
Sorry for the confusion.

I just made sure `master` is up to date with main and deleted main. I will tell the organizational admin to rename `master` to `main` so the default branch in cwa-documentation will be `main` in the future.

**Comment by Ein-Tim** [comment]
This will break so many links I shared... Or is this covered by GitHubs automatic redirect system?

**Comment by svengabr** [comment]
This is covered by Github, they will automatically redirect /master to the new default Branch.

Here is some information:
https://github.com/github/renaming

**Comment by Ein-Tim** [comment]
@svengabr 

Nice, then I welcome this change very much!

**Comment by svengabr** [comment]
Closing this issue for now, if you have any more thoughts please let me know.

**Comment by MikeMcC399** [comment]
- Issue https://github.com/corona-warn-app/cwa-documentation/issues/827 submitted regarding links broken by renaming default branch.
