### ISSUE TITLE
Renaming default branch master to main causes dead links

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#827]
## Where to find the issue

https://github.com/corona-warn-app/cwa-documentation/blob/main/ui_screens.md

## Describe the issue

When viewing https://github.com/corona-warn-app/cwa-documentation/blob/main/ui_screens.md the screenshots in the section [Screen Descriptions](https://github.com/corona-warn-app/cwa-documentation/blob/main/ui_screens.md#screen-descriptions) are not accessible. Clicking on any of the "Android" or "iOS" links produces a 404 error.

- See https://github.com/corona-warn-app/cwa-documentation/issues/826.

## Steps to reproduce

Open [Screen Descriptions](https://github.com/corona-warn-app/cwa-documentation/blob/main/ui_screens.md#screen-descriptions) in a web browser.
Click on the Android link in the first list entry and note the GitHub 404 error message.

To troubleshoot:

On local clone of https://github.com/corona-warn-app/cwa-documentation
```
git switch main
npm run checklinks
```

```
FILE: ./ui_screens.md
ERROR: 8 dead links found!
[✖] https://github.com/corona-warn-app/cwa-documentation/raw/master/images/ui_screens/android/cwa_onboarding_android.png → Status: 404
[✖] https://github.com/corona-warn-app/cwa-documentation/raw/master/images/ui_screens/ios/cwa_onboarding_ios.png → Status: 404
[✖] https://github.com/corona-warn-app/cwa-documentation/raw/master/images/ui_screens/android/cwa_home_android.png → Status: 404
[✖] https://github.com/corona-warn-app/cwa-documentation/raw/master/images/ui_screens/ios/cwa_home_ios.png → Status: 404
[✖] https://github.com/corona-warn-app/cwa-documentation/raw/master/images/ui_screens/android/cwa_detail_android.png → Status: 404
[✖] https://github.com/corona-warn-app/cwa-documentation/raw/master/images/ui_screens/ios/cwa_detail_ios.png → Status: 404
[✖] https://github.com/corona-warn-app/cwa-documentation/raw/master/images/ui_screens/android/cwa_risk_calculation_android.png → Status: 404
[✖] https://github.com/corona-warn-app/cwa-documentation/raw/master/images/ui_screens/ios/cwa_risk_calculation_ios.png → Status: 404
n
```

## Suggested change

In https://github.com/corona-warn-app/cwa-documentation/blob/main/ui_screens.md change links from `master` to `main`.

**Comment by MikeMcC399** [comment]
PR https://github.com/corona-warn-app/cwa-documentation/pull/828 submitted to resolve the issue.

**Comment by svengabr** [comment]
@MikeMcC399 thank you very much for the provided report and fix!
