### ISSUE TITLE
Text-description of red alerts 

### ISSUE THREAD

**Issue by Trcgn100** [corona-warn-app/cwa-documentation#830]
Hi everyone,

I might have a rather easy question. I tried to look the answer up but no such luck. 

What is the difference when it comes to these red alerts?

![E75C6A4F-0EE0-4049-BC7A-7B1061C869E3](https://user-images.githubusercontent.com/98661264/151672052-53b7ff9e-500e-4917-933b-72e4525f6d15.jpeg)
![C2D9D8C5-B2ED-4925-90C3-89A0991EBA3F](https://user-images.githubusercontent.com/98661264/151672053-13a1ec8f-04e2-487a-ac15-99a51a685e4c.jpeg)

I do not understand the difference between those two? Can someone please explain?
Thank you very much.

**Comment by Ein-Tim** [comment]
In https://www.coronawarn.app/en/blog/2020-12-16-corona-warn-app-version-1-9/ it says:
 
> If a user had multiple encounters with a high risk (red), he or she will see the date when the latest high-risk encounter took place. In addition, the epidemiological risk assessment is now even more accurate. Now, multiple - individually considered - low-risk encounters (green) can lead to an increased risk (red): depending on infectivity, 15-30 minutes of low-risk encounters (green) can result in an increased-risk encounter (red). Furthermore, users can now see the number of days on which they had an encounter with a high or low risk instead of the number of encounters. With the change to ENF 2.0, it is no longer a single encounter that is decisive for the risk assessment, but the sum of the risk minutes per day. **Thus, even several short encounters can lead to an increased risk.**

Does this help you?

**Comment by Trcgn100** [comment]
> In https://www.coronawarn.app/en/blog/2020-12-16-corona-warn-app-version-1-9/ it says:
> 
> > If a user had multiple encounters with a high risk (red), he or she will see the date when the latest high-risk encounter took place. In addition, the epidemiological risk assessment is now even more accurate. Now, multiple - individually considered - low-risk encounters (green) can lead to an increased risk (red): depending on infectivity, 15-30 minutes of low-risk encounters (green) can result in an increased-risk encounter (red). Furthermore, users can now see the number of days on which they had an encounter with a high or low risk instead of the number of encounters. With the change to ENF 2.0, it is no longer a single encounter that is decisive for the risk assessment, but the sum of the risk minutes per day. **Thus, even several short encounters can lead to an increased risk.**
> 
> Does this help you?

Thank you for your very quick reply. I am not sure I understand fully. So the first red alert is a sum of green encounters and the second red alert I posted means sum of red encounters?

**Comment by Ein-Tim** [comment]
@Trcgn100 

The red risk from Friday is because you had multiple encounters which were all not above the threshold for a red warning, but summarized together these encounters were above the threshold. 

The red risk from Monday is because you had one encounter which was above the threshold for a red warning.

**Comment by Trcgn100** [comment]
> @Trcgn100
> 
> The red risk from Friday is because you had multiple encounters which were all not above the threshold for a red warning, but summarized together these encounters were above the threshold.
> 
> The red risk from Monday is because you had one encounter which was above the threshold for a red warning.

@Ein-Tim 
Ok, thank you so much for explaining it that detailed. 

I don’t want to unnerve you but let me ask another question please: 
Could it be, that the red alert that says - as you explained - I had multiple encounters which were all not above the threshold for a red warning, but summarized together these encounters were above the threshold, could it be that this was THE SAME person? That I saw that person for x minutes in the morning, y minutes in the afternoon and z minutes at night?

**Comment by Ein-Tim** [comment]
@Trcgn100

> Could it be, that the red alert that says - as you explained - I had multiple encounters which were all not above the threshold for a red warning, but summarized together these encounters were above the threshold, could it be that this was THE SAME person? That I saw that person for x minutes in the morning, y minutes in the afternoon and z minutes at night?

This question is answered in the FAQ entry [Are risk encounters with the same person counted several times a day?](https://www.coronawarn.app/en/faq/#encounter_same_person).
So yes, this is possible.

**Comment by Trcgn100** [comment]
> @Trcgn100
> 
> > Could it be, that the red alert that says - as you explained - I had multiple encounters which were all not above the threshold for a red warning, but summarized together these encounters were above the threshold, could it be that this was THE SAME person? That I saw that person for x minutes in the morning, y minutes in the afternoon and z minutes at night?
> 
> This question is answered in the FAQ entry [Are risk encounters with the same person counted several times a day?](https://www.coronawarn.app/en/faq/#encounter_same_person). So yes, this is possible.

@Ein-Tim 
Thank you bunches!!!

**Comment by Ein-Tim** [comment]
@Trcgn100 

For sure! If you are satisfied with my answers, please close this issue! 

Have a nice evening!
