### ISSUE TITLE
Add Transmission Risk Level examples to Risk Calculation in Solution Architecture

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#832]
## Where to find the issue

The following document:

CORONA-WARN-APP SOLUTION ARCHITECTURE
[MOBILE APPLICATIONS](https://github.com/corona-warn-app/cwa-documentation/blob/main/solution_architecture.md#mobile-applications)
Risk Calculation

## Describe the issue

The Risk Calculation section in the [CORONA-WARN-APP SOLUTION ARCHITECTURE](https://github.com/corona-warn-app/cwa-documentation/blob/main/solution_architecture.md) document describes how the app calculates a risk score so that it is able to tell the user if they have been at risk of infection.

The blog post [Behind the scenes of the Corona-Warn-App](https://www.coronawarn.app/en/blog/2020-12-30-cwa-behind-the-scenes/) from December 30, 2020 links to a [video](https://youtu.be/TIXsOIrp1dg) and to a copy of the [slides](https://www.coronawarn.app/assets/documents/cwa-rc3.pdf) used in the presentation.

The [video](https://youtu.be/TIXsOIrp1dg) and [slides](https://www.coronawarn.app/assets/documents/cwa-rc3.pdf) contain some information which is missing from the [Solution Architecture](https://github.com/corona-warn-app/cwa-documentation/blob/main/solution_architecture.md) document. For instance, the table of TRL levels based on "Days since Onset of Symptoms" is missing in the Solution Architecture document. There are also no example calculations given in the Solution Architecture document.

## Suggested change

Either link the [Solution Architecture](https://github.com/corona-warn-app/cwa-documentation/blob/main/solution_architecture.md) document to the [presentation slides](https://www.coronawarn.app/assets/documents/cwa-rc3.pdf) and [video](https://youtu.be/TIXsOIrp1dg) or add the information directly into the [CORONA-WARN-APP SOLUTION ARCHITECTURE](https://github.com/corona-warn-app/cwa-documentation/blob/main/solution_architecture.md) document.

Since the presentation and video are no longer completely up-to-date in terms of the details, it would need some comment about what has changed if this material is simply linked in.

## Additional information

- This issue is related to the deprecation of the outdated document [How does the Corona-Warn-App identify an increased risk?](https://github.com/corona-warn-app/cwa-documentation/blob/main/cwa-risk-assessment.md) as proposed in PR https://github.com/corona-warn-app/cwa-documentation/pull/829.

**Comment by MikeMcC399** [comment]
- PR #845 is starting to address this issue.

**Comment by AnonymousUserUse** [comment]
Is this issue addressed?
By the way, I do not think the information in the presentation from December 30, 2020 is up to date. Only transmission risk level >=3 is counted now.

**Comment by MikeMcC399** [comment]
@AnonymousUserUse 

> Is this issue addressed?

No. See the open PR https://github.com/corona-warn-app/cwa-documentation/pull/845 from @mlenkeit. I suspect that this issue is low in the current order of priorities.

**Comment by mlenkeit** [comment]
@MikeMcC399 I think it is complete now with the merge of #845. If not, please re-open.

@AnonymousUserUse the [Solution Architecture](https://github.com/corona-warn-app/cwa-documentation/blob/main/solution_architecture.md) is updated now with the missing information. If you're just interested in the changes, you can take a look [here](https://github.com/corona-warn-app/cwa-documentation/pull/845/files#diff-3f7db7dcbbe3f82518600babf7728a09cb266192053db341366f0a3ca62f22fd).

**Comment by MikeMcC399** [comment]
@mlenkeit 

Thanks you for the follow up. Issue closure is fine. 👍🏻
