### ISSUE TITLE
Booster Certificate is not selected as latest 

### ISSUE THREAD

**Issue by Uzlopak** [corona-warn-app/cwa-documentation#837]
I got today my booster. My first vaccine was Johnson and Johnson. Second was biontech and third one was moderna. 

Went to the Apotheke and got my new QR Code. On the paper it says now 3/1 vaccinations received. Scanned it and my 2/2 cert was still the active used one. Needed to delete my old certs to get the last cert to be active.

The PTA said, that the software to generate the QR Codes was updated yesterday. They now show 3/1 for the one shot J&J and 3/2 for the vaccines which need to have two shots. 

This is total BS. They changed the format. My wife has on cert from last month 3/3. when you start to vaccinate with a two shot vaccine and got your first shot, you got last year 1/2. Now they switched it. Seems really really odd. 

I am going now to another Apotheke to figure out if this is true. Or the PTA just did it wrong. Even on the paper cert it says Erstimpfung/ Wiederimpfung. So I think it had to be 1/3 and not the other way round. But still this makes it not possible to determine if the cert is a booster or not. Only if the cert is kind of versioned....

So confusing and so bad...

**Comment by Uzlopak** [comment]
Ok. Other PTA confirmed it. The first number is the relevant one... 

So yeah...

**Comment by Ein-Tim** [comment]
If you were vaccinated with J&J, you receive the following certificates (as of the change yesterday):

1/1 cert for the first vaccination with J&J
2/1 for the first vaccination with another vaccine
3/1 fir the second vaccination with another vaccine

**Comment by Ein-Tim** [comment]
The latest version can deal with these type of certificates. Please install version 2.17.1.

**Comment by Uzlopak** [comment]
I have 2.16. there is no 2.17.1. do I have to apply to some beta program like for Whatsapp to also get the latest version available?

**Comment by Uzlopak** [comment]
Sry, I realize now that I created the issue in the wrong repo.

**Comment by Ein-Tim** [comment]
@Uzlopak 

> I have 2.16. there is no 2.17.1 available at the Google play store. do I have to apply to some beta program like for Whatsapp to also get the latest version available?

No, sorry, version 2.17.1 is currently in staged rollout: https://www.coronawarn.app/en/faq/#release_time
