### ISSUE TITLE
Outdated links in transmission_risk document

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#838]
## Where to find the issue

- https://github.com/corona-warn-app/cwa-documentation/blob/main/transmission_risk.Rmd and
- https://github.com/corona-warn-app/cwa-documentation/blob/main/transmission_risk.pdf

## Describe the issue

Some links in the document [Epidemiological Motivation of the Transmission Risk Level](https://github.com/corona-warn-app/cwa-documentation/blob/main/transmission_risk.pdf) from the CWA Team, dated 2020-10-12 are outdated.

### Document body

The link [CWA Architecture](https://github.com/corona-warn-app/cwa-documentation/blob/main/solution_architecture.md#risk-score-calculation) is supposed to go to the anchor `#risk-score-calculation` which no longer exists, so the document is opened at the top.

### Literature section

The link [Apple, and Google. 2020a. “Exposure Notifications Android Api Documentation V1.3.2.” 2020.](https://static.googleusercontent.com/media/www.google.com/en/covid19/exposurenotifications/pdfs/Android-Exposure-Notification-API-documentation-v1.3.2.pdf) produces a 404 error.

## Suggested change

In general it needs to be decided whether this document is frozen or should be updated.

If it is to be updated, then the following changes could be considered:

1. Change links to https://github.com/corona-warn-app/cwa-documentation/blob/main/solution_architecture.md#risk-score-calculation to use the renamed anchor `#risk-calculation`.

2. The document [Apple, and Google. 2020a. “Exposure Notifications Android Api Documentation V1.3.2.” 2020.](https://static.googleusercontent.com/media/www.google.com/en/covid19/exposurenotifications/pdfs/Android-Exposure-Notification-API-documentation-v1.3.2.pdf) is no longer available online and has been replaced by the web documentation on https://developers.google.com/android/exposure-notifications/exposure-notifications-api.

**Comment by MikeMcC399** [comment]
It would be good for the Open Source Team to comment how this should be handled, for instance:

- no change
- add a note at the beginning or end of the document about the revised links
- integrate the changes into the document and reissue with a new version date

**Comment by ahodzic2** [comment]
@MikeMcC399 

Is this still needed, would like to assist if there has been any update on how to approach this.

**Comment by MikeMcC399** [comment]
@ahodzic2 
>  if there has been any update on how to approach this.

Thank you for your offer. There is no update. If there had been an update, then it would have been posted here.

There will be no progress unless the Open Source Team (of which I am not a member) responds to the issue and gives an opinion. Lack of comment so far means no change.

**Comment by ahodzic2** [comment]
@MikeMcC399 Understood!

@dsarkar - Are you able to provide input on how you see fit to proceed?

**Comment by svengabr** [comment]
I will discuss this internally

**Comment by GisoSchroederSAP** [comment]
I'll take over this issue and discuss with the PO and DEV team lead. 
Will post the decision and further steps here as soon as I have news.
