### ISSUE TITLE
Signon,  Identity Infrastructure Service

### ISSUE THREAD

**Issue by tacurran** [corona-warn-app/cwa-documentation#84]
## Why should it be included
ORY Kratos is a new software archetype Identity Infrastructure Service. Traditional identity systems - sometimes referred to as Identity and Access Management (IAM), Identity Management (IdM), Identity Provider (I(d)P), or IDaaS (Identity as a Service) - have shortcomings that highlight the main differences between ORY Kratos and other systems.

ORY Kratos solves identity on the network. It is not a on-device, for instance mobile phones, user database. In Ory Kratos there is always an exchange of credentials. In the case of web applications and identity:

Username + Password -> Cookie, Token, ...
Email + Password -> Cookie, Token, ...
Passwordless login -> Cookie, Token, ...

Even for alternative use cases for example mobile, browser, or native application there is either a cookie, which accesses the application directly through the browser, or a token that accesses the application using a programmatic client via an API. While it is nowadays common - but bad practice - to use tokens for "Single Page Apps" or apps running on the client-side browser, there is no real difference between these two approaches as both represent a set of credentials valid for a certain domain or a number of domains.

## Where should it be included
Once the team decides on an architecture for identity infrastructure, we would contribute a proposal in a PR.

**Comment by tkowark** [comment]
Hi @tacurran, thanks for the proposal. The main premise of the concept is exactly that users do not have to identify themselves. But, of course, you are invited to contribute PRs wherever your technology might seem fit.
