### ISSUE TITLE
Plans for a redesign? 

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#841]
## Your Question
Are there plans to redesign the app in the next month? Because on https://www.ux-design-awards.com/de/gewinner/2022-1-379-corona-warn-app there are many photos with very good looking CWAs (even better than the one on my phone) 😉

No, to stop being a fool: Are there plans to redesign the CWA in the way shown in the link above? Because if, this would be important to know for the Community so that community contributors don't create UX issues which are design depended anymore or shift their focus on other areas.

**Comment by mlenkeit** [comment]
Parts of it, such as the universal QR code scanner, have already been implemented/realized. Whether a redesign of the home screen / status tab will come is not yet decided.

**Comment by Ein-Tim** [comment]
Ok thanks @mlenkeit!

**Comment by Ein-Tim** [comment]
@mlenkeit Congrats for winning the design award, btw :D

**Comment by mlenkeit** [comment]
> @mlenkeit Congrats for winning the design award, btw :D

The credit goes to our team of designers, not to me 😉 But I'll pass it on to them, thank you 👍
