### ISSUE TITLE
"3 of 1" certificate not used in a series of "1 of 1", "2 of 2" and "3 of 1"

### ISSUE THREAD

**Issue by smares** [corona-warn-app/cwa-documentation#842]
My mom just received her 3rd vaccine after being vaccinated with Janssen (displayed as "1 of 1") and Comirnaty (displayed as "2 of 2"). The 3rd vaccination certificate was created as being "3 of 1". CWA keeps using the 2nd certificate and the icon that appears next to the third certificate is a shield filled with 50%. Is this a bug in the app or is the certificate faulty?

---
Internal Tracking ID: [EXPOSUREAPP-11634](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11634)

**Comment by thomasaugsten** [comment]
I assume the vaccination date of the 3 of 1 was in less than 14 days?
This display issue will be fixed in the next version. This version will be release tomorrow  or on Saturday.

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Was this fixed in version 2.17.2 under Android?

**Comment by dsarkar** [comment]
@Ein-Tim I think yes: https://github.com/corona-warn-app/cwa-app-android/pull/4764

**Comment by Ein-Tim** [comment]
@dsarkar This PR only talks about the 2/1 case so I'm uncertain.

**Comment by dsarkar** [comment]
@Ein-Tim ok, I will check.

**Comment by thomasaugsten** [comment]
This is fixed in 2.17.2 and also the detection of 2/1 as booster is intended.

**Comment by dsarkar** [comment]
@smares Could you check with latest version 2.17.2. Thanks for your feedback!

Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by smares** [comment]
Works as intended now. 😄

**Comment by dsarkar** [comment]
@smares Thanks for the feedback!

Best wishes, DS

---
Corona-Warn-App Open Source Team
