### ISSUE TITLE
Problems with DCC entry validity check due to new notation (3/1, 2/1)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#849]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Describe the bug

For both Spain as well as Austria, the entry validity check delivers strange results when checking a vaccination with the new notation.

Twitter report Austria: https://twitter.com/MichaelRieger/status/1491010814085853186?s=20&t=L81tZbVNnNzjPH0q3m46HA
Twitter report Spain: https://twitter.com/KlausThaler8/status/1489969924768518149?s=20&t=L81tZbVNnNzjPH0q3m46HA
## Steps to reproduce the issue

1. Get a vac. cert with the new DCC booster notation
2. Check the validity in CWA against Spain or Austria
3. See the wrong result

## Expected behaviour

The correct result should be shown. The entry rules need to be updated from these countries. 

## Additional context

1. I created this issue so that it can be forwarded to the Austrian/Spain team. 
2. Probably also other countries are affected. 
---
Internal Tracking ID: [EXPOSUREAPP-11765](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11765)

**Comment by svengabr** [comment]
Internal Tracking ID: EXPOSUREAPP-11765

**Comment by svengabr** [comment]
Hey, @Ein-Tim thanks for the report. I have created a ticket and assigned it accordingly.

**Comment by jkrwdf** [comment]
Eventually this here is the same class of issue: The 4/4 certificate of my mother from Sunday (2022-FEB-20) is not accepted from the travel check function for "France" today (2022-FEB-22) with the error that "With not Jansen vaccine, a finished vaccination course is considered protective earliest from 7 days after the date of last vaccination".

**Comment by Ein-Tim** [comment]
@jkrwdf I guess France hasn't adapted their rules to 4. vaccinations.

**Comment by MikeMcC399** [comment]
There is a nice community-based UI to view all EU rules. See https://timokoenig.github.io/eu-dcc-rules.
Kudos to @timokoenig 👍🏻

**Comment by Ein-Tim** [comment]
Austria was also fixed.
