### ISSUE TITLE
Version 2.18 shows "1G" in case of a booster. Why isn't 2G+ shown?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#851]
## Your Question
I used an Emulator to test the behavior of version 2.18 in regard of booster vaccinations. Importing a 3/3 certificate, leads to the status "1G".
As the status "1G" is not widely known, wouldn't it make more sense to show 2G+? Or is this impossible, due to the different regulations in the different federal states?

---
Internal Tracking ID: [EXPOSUREAPP-11773](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11773)
Internal Tracking ID: [EXPOSUREAPP-11803](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11803)

**Comment by Ein-Tim** [comment]
@thomasaugsten Will it be explained in the app? Only explaining it in a blog post won't reach all users. Only a hint in the app can help here.

**Comment by thomasaugsten** [comment]
The connected FAQ Link will have all information

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Okay, agreed.

**Comment by Ein-Tim** [comment]
I suggest to think about the wording "1G" again, as e.g. in the Netherlands this mens that all guests have to be tested, and that's it.
See [Niederlande: Regierung kündigt weitreichende Corona-Lockerungen an](https://www.rnd.de/politik/corona-niederlande-kuendigt-lockerungen-an-1g-fuer-clubs-und-veranstaltungen-2YD6NGP4W4BHXAAHBOWJHCY7IM.html)

@thomasaugsten / @mlenkeit 

Imagine the situation where a similar situation comes up here in Germany. Then we have the total chaos, 1G in the app has a total different meaning and this would confuse everybody.

**I strongly suggest to not invent new G-Statuses but rather use the already known status names!**

**Comment by Ein-Tim** [comment]
@mlenkeit Did you think about the term "1G" again? Maybe even discussed it with the RKI?

**Comment by dsarkar** [comment]
@Ein-Tim Will come back to you.

**Comment by thomasaugsten** [comment]
This is correct

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Okay thanks!

Thank you for taking the feedback from the community into consideration! ❤️

Closing this issue.
