### ISSUE TITLE
[Business-Rules] Validity check not working according to 2G rules

### ISSUE THREAD

**Issue by mejmo** [corona-warn-app/cwa-documentation#853]
The app does not do certificate verification for Austria correctly. They have completely different 2G rules, so in the app it shows the certificate is valid for Austria but it is not because last vaccination was more than half a year ago. Please fix, I consider this as quite critical because it can spoil travel plans.

**Comment by MikeMcC399** [comment]
This issue should be closed.

**Comment by larswmh** [comment]
Closing as suggested
