### ISSUE TITLE
version 2.16.2 - 2G+ when vaccinated and recovered

### ISSUE THREAD

**Issue by betomoretti** [corona-warn-app/cwa-documentation#854]
## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Question is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Question has not already been asked in another issue

## Your Question

* Source File: N/A
* Line(s): N/A
* Question: 
Will the app show 2G+ for people that have a valid vaccination cycle plus a valid recovery certificate? I tried to find the answer but I only could find info about the booster. I'm sorry if this has been answered already. I took a look [to the blog post](https://www.coronawarn.app/en/blog/2022-01-17-cwa-2-16/) but It didn't clarify this case. Based on [this](https://www.hamburg.de/corona-schutzimpfung/15781988/quarantae-isolation-test/#marker02) information, it should be shown as 2G+. But I might be wrong.
Thanks a lot!

**Comment by dstango** [comment]
I'd be very much for this feature, though AFAIK vaccinated & recovered being considered equivalent to 2G+ is handled differently on a German Federal Land basis. I think e.g. NRW and Niedersachsen consider it equivalent to 2G+, while Berlin doesn't. But my information about Berlin might be outdated ... anyhow: if there were local differences, the CWA would have to take into account the current location.

**Comment by mlenkeit** [comment]
> This will probably be fixed in version 2.18, or @mlenkeit?

@Ein-Tim yes, 2.18 should correctly interpret a recovery certificate that follows vaccination certificates, according to the regulations of the Bundesministerium für Gesundheit. Note that the regulations might differ from that in some federal states of Germany.

**Comment by dstango** [comment]
@mlenkeit will it also respect the opposite order? Recovery followed by vaccination?

**Comment by mlenkeit** [comment]
> @mlenkeit will it also respect the opposite order? Recovery followed by vaccination?

@dstango yes, that one too.

**Comment by Ein-Tim** [comment]
@mlenkeit 

By detecting if there are vac certs. with "1/1" & then either "2/2" or "2/1", I assume? Or is this relying on the existence of a recovery certificate.

**Comment by mlenkeit** [comment]
> @mlenkeit
> 
> By detecting if there are vac certs. with "1/1" & then either "2/2" or "2/1", I assume? Or is this relying on the existence of a recovery certificate.

@Ein-Tim we use as much information as possible and as little as necessary 😉

Examples:

- if there's 1/1 and 2/2, we know that 2/2 is a booster shot after a recovery vaccination. However, note that CovPassCheck might not be able to identify this situation with a single scan of 2/2.
- if there is a recovery certificate and 2/2, we know that 2/2 is a booster shot after a recovery vaccination. However, note that CovPassCheck might not be able to identify this situation with a single scan of 2/2.
- 2/1 is recognizable on its own, even with a single scan via CovPassCheck

**Comment by Ein-Tim** [comment]
@mlenkeit

Okay, I assumed this. Thanks!

**Comment by Ein-Tim** [comment]
Please check back with version 2.18, see: [CWA 2.18: Improving the display of the G status in the Corona-Warn-App](https://www.coronawarn.app/en/blog/2022-02-23-cwa-2-18).

I suggest closing this issue.

**Comment by dsarkar** [comment]
@betomoretti Thanks for reporting here. Please see comment https://github.com/corona-warn-app/cwa-documentation/issues/854#issuecomment-1048830124.

Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by betomoretti** [comment]
Thank you!

Regards
