### ISSUE TITLE
DCC entry check for Germany shows PCR tests as valid even though the tests are older than 48h

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#855]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR
- iOS/Android version: 15.3
- App version: 2.17.1

## Describe the bug

The DCC "Check travel validity" feature of the Corona-Warn-App and the CovPass-App shows PCR tests as valid for entry of Germany, although the test is older than 48h. 

This is contradictory to the information on https://www.auswaertiges-amt.de/de/quarantaene-einreise/2371468#content_2.

So, in consequence **CWA shows certificates as valid for entering Germany, although they are not valid!**

## Steps to reproduce the issue

1. Import a PCR test into the app
2. Check for it's validity to entry Germany more than 48h but not longer than 72h ago
3. See that CWA states the certificate is valid

## Expected behaviour

The CWA should not declare certificates as valid for entry although they are not. 

## Possible Fix

Change the validity from max. 72h to max. 48h.

## Additional context

This is related to #819.

**Comment by thomasaugsten** [comment]
Yes I think so because the CovPassCheck is doing the entry checks

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Okay, I will transfer the issue to the CovPass-Team. If they change the rules for CovPassCheck, will the entry rules also change automatically, or?

**Comment by thomasaugsten** [comment]
This is correct all apps using the same rules

**Comment by Ein-Tim** [comment]
Okay thank you @thomasaugsten! Enjoy the evening!
