### ISSUE TITLE
App shows "Änderung Ihres Risikostatus" even though a positive test is registered and the risk status is not visible to the user

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#856]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Not relevant
- iOS/Android version: Not relevant
- App version: 

## Describe the bug

The app shows the "Änderung Ihres Risikostatus" pop-up, which is shown when the last increased risk encounter was more than 14 days ago, even if a positive test is registered. 
This makes no sense, as the user is not able to see their risk status.

<img src="https://user-images.githubusercontent.com/67682506/154113071-4b422214-18cf-4afc-a16d-f97049d4085c.jpeg" width="300">

## Steps to reproduce the issue

1. Get an encounter with increased risk
2. Register a positive test in the app
3. Wait until 14 days since the encounter have passed
4. See the message

## Expected behaviour

The "Änderung Ihres Risikostatus" pop-up should not be shown if a positive test is registered in the app. 

## Related issue
- https://github.com/corona-warn-app/cwa-wishlist/issues/777

## Additional context

This report is based on the feedback I received from a user on Twitter: https://twitter.com/bext0n/status/1493611763484483589?s=20&t=1ISQbqjOZikD6pn5BrY80Q

---
Internal Tracking ID: [EXPOSUREAPP-11969](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11969)

**Comment by larswmh** [comment]
Thanks for your report @Ein-Tim. We have created an internal ticket for it and will raise this topic internally. 
Internal Tracking ID: [EXPOSUREAPP-11969](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11969)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
iOS PR fixing this: https://github.com/corona-warn-app/cwa-app-ios/pull/4336

**Comment by Ein-Tim** [comment]
Android PR: https://github.com/corona-warn-app/cwa-app-android/pull/4938

**Comment by Ein-Tim** [comment]
This has already been fixed in version 2.20.
