### ISSUE TITLE
Risikobegegnungen mit falschen Ortsangaben

### ISSUE THREAD

**Issue by GeorgBisseling** [corona-warn-app/cwa-documentation#857]
Samsung Galaxy S8
Android 9 (Pie), API Level 28, Patch 2021-04-01
CWA 2.4.2

Es werden Risikobegegnungen für fünf aufeinanderfolgende Tage an einem Ort (Restaurant) angezeigt, an dem das Smart-Phone zuletzt vor einigen Monaten war. Die Meldungen sind also definitiv fehlerhaft.

Wenn ich mich recht ensinne, wurde am 21. oder 22. August 2021 in diesem Restaurant ein Veranstaltungskode gescannt.

---
Internal Tracking ID: [EXPOSUREAPP-11619](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11619)

**Comment by dsarkar** [comment]
@Ein-Tim Thanks. Forwarded to internal ticket. Internal Tracking ID for FAQ: [EXPOSUREAPP-11949](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11949)

Enjoy Sunday, DS

**Comment by dsarkar** [comment]
FYI https://github.com/corona-warn-app/cwa-app-android/pull/4904

**Comment by MikeMcC399** [comment]
Is this issue now resolved with the release of CWA 2.20?

See https://www.coronawarn.app/en/blog/2022-03-30-cwa-2-20/

![image](https://user-images.githubusercontent.com/66998419/163538675-20e8a043-965b-49b7-8597-1dfdb23b3f01.png)

**Comment by larswmh** [comment]
As there was no further activity in this issue, we are now going to close this issue. Thanks for your contributions.

---
Corona-Warn-App Open Source Team
