### ISSUE TITLE
Adapt CWA to new EU regulations which are in effect now

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#858]
* [X] None of the other issue templates apply to this issue.
* [x] This issue affects iOS & Android.

### This is an informational issue.

--- 

According to https://ec.europa.eu/info/sites/default/files/commission_delegated_regulation_amending_regulation_eu2021_953.pdf, recovery certificates shall also be issued if a positive rapid antigen test result is present.

The Corona-Warn-App should be adapted as soon as possible.

**Comment by Ein-Tim** [comment]
If there is no adjustment in the CWA needed, please let me know and close this issue.

**Comment by thomasaugsten** [comment]
We don't see any adjustments. 
Recovery certificates are not issued by the CWA.

**Comment by Ein-Tim** [comment]
@thomasaugsten 

For sure they are not issued by CWA but there is also no check or similar whether the recovery certificate is issued based on a positive PCR test in the app, or?

**Comment by thomasaugsten** [comment]
There is no connection between recovery certificates and positive test results

**Comment by Ein-Tim** [comment]
@thomasaugsten 

You're right I thought that there is a field for which test was used in the recovery certificate but actually there isn't.

Thank you & enjoy the evening!
