### ISSUE TITLE
How to view G rules (status proof)?

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#860]
[CWA 2.18: Improving the display of the G status in the Corona-Warn-App](https://www.coronawarn.app/en/blog/2022-02-23-cwa-2-18/) announced the introduction of a rule engine for determination of G status which is also listed in the FAQ [General information about the status proof display](https://www.coronawarn.app/en/faq/#admission_policy).

There is no mention of this change in this [cwa-documentation](https://github.com/corona-warn-app/cwa-documentation) repository.

**Where are the G rules stored and how can they be viewed?**

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for asking, will try to get an answer.

**Comment by MikeMcC399** [comment]
@dsarkar 
> will try to get an answer.

Thank you very much!

It would be great to see a page for the "G rules" similar to https://timokoenig.github.io/eu-dcc-rules from @timokoenig which displays the EU rules in a user-friendly way.

**Comment by dsarkar** [comment]
@MikeMcC399 
Not easy to read:

Functions
https://github.com/corona-warn-app/cwa-app-ccl/tree/main/lib/ccl/functions


Rules
https://github.com/corona-warn-app/cwa-app-ccl/blob/main/lib/ccl/functions/__analyzeDccWallet.js


Tests
https://github.com/corona-warn-app/cwa-app-ccl/tree/main/test/fixtures/ccl

**Comment by MikeMcC399** [comment]
@dsarkar 
Thank you very much for the pointers! I agree that this is not easy to read and interpret!

**Comment by MikeMcC399** [comment]
I knew about the existence of the new [cwa-app-ccl](https://github.com/corona-warn-app/cwa-app-ccl) repository. I wonder why it isn't listed in the [cwa-documentation README](https://github.com/corona-warn-app/cwa-documentation#readme) together with the list of other project repositories?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thanks for the reminder!

I will update the table later today.

**Comment by Ein-Tim** [comment]
@MikeMcC399 FYI PR: #863
