### ISSUE TITLE
Automatische Löschung abgelaufener Zertifikate

### ISSUE THREAD

**Issue by jetrca** [corona-warn-app/cwa-documentation#861]
Servus,

Ich würde mir die Möglichkeit wünschen, abgelaufene Zertifikate automatisch zu löschen, da meine App so langsam von Schnelltests überquillt. Wo wäre der Ort für eine derartige Featureanfrage?

Danke voraus für die Erläuterung!

**Comment by Ein-Tim** [comment]
Hi @jetrca 

Der richtige Ort für Feature-Anfragen ist hier: https://github.com/corona-warn-app/cwa-wishlist

**Comment by jetrca** [comment]
Danke für die Info.
Ich hoffe, ich habe es richtig gemacht:

https://github.com/corona-warn-app/cwa-wishlist/issues/812

> Hi @jetrca
> 
> Der richtige Ort für Feature-Anfragen ist hier: https://github.com/corona-warn-app/cwa-wishlist
