### ISSUE TITLE
DCC reissue feature: Why is it necessary to store the hash for one year?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#862]
## Your Question

* PR: https://github.com/corona-warn-app/cwa-app-ios/pull/4271
* Question: Why is such a long time storage (1 year) of the generated hash necessary? Could you elaborate what abuse scenario this prevents?

**Comment by thomasaugsten** [comment]
I think the reissue service is the right place for this question because the CWA is not saving the hash
https://github.com/Digitaler-Impfnachweis/certification-apis/issues

**Comment by Ein-Tim** [comment]
@thomasaugsten Okay, thanks! So it was not a decision by the CWA team to store the hash for one year but rather form the team over https://github.com/Digitaler-Impfnachweis?

**Comment by thomasaugsten** [comment]
It is a joined decision from stakeholder and the developing teams to match the requirements and to prevent misusage

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Okay, thanks.
