### ISSUE TITLE
CWA meldet keine Risikobegegnung, trotz hinterlegtem positivem PCR-Test und dauerhaftem Kontakt

### ISSUE THREAD

**Issue by Servior1** [corona-warn-app/cwa-documentation#864]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 12 (Gerät1) / iPhone 11 Pro Max (Gerät2)
- iOS version: iOS15.3
- App version: 2.18.1

## Describe the bug

PCR-Test:
- Probeentnahme: 28.02.22.
- Ergebnis am 01.03. erhalten -> Positiv
- Ergebnis in der App an Gerät1 hinterlegt.

CWA an Gerät 2 meldet keinerlei Risikobegegnung, trotz deutlichem Kontakt (gleicher Haushalt, Lebensgefährtin). Geräte liegen teils nur wenige Zentimeter auseinander und das über Stunden hinweg.

Risikoermittlung an beiden Geräten ist aktiviert.

## Steps to reproduce the issue

CWA an Gerät2 öffnen. Risikoermittlung prüfen. Letzte Aktualisierung: Heute gegen 11:36 Uhr.

## Expected behaviour

CWA sollte an Gerät2 rot anzeigen, da Kontakt vorhanden.

## Additional context

**Comment by Ein-Tim** [comment]
War Gerät 2 auch schon vor dem melden der Infektion auf Gerät 1 mit Gerät 1 in Kontakt?

**Comment by dsarkar** [comment]
@Servior1 Thanks for your report, please, see question in comment https://github.com/corona-warn-app/cwa-documentation/issues/864#issuecomment-1056842358

Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by Servior1** [comment]
Keine Ahnung ob bzw. wann meine Mail ankommt, daher nochmal direkt als Kommentar.

Risikoermittlung an Gerät2 wurde erst am Sonntag oder Montag aktiviert, vorher fehlten noch Einstellungen in iOS. An Gerät1 ist die Ermittlung seit Einrichtung von ein paar Wochen aktiv.
Die beiden Geräte sind aber dauerhaft in Kontakt, da wir beide zuhause sind.

**Comment by Ein-Tim** [comment]
@Servior1 Die CWA warnt nur rückwirkend, wenn auf Gerät 2 also erst nach dem Teilen des positiven Ergebnisses auf Gerät 1 die Risiko-Ermittlung aktiviert wurde, gibt es auf Gerät 2 keine Warnung. 

Wenn Gerät 1 jetzt schon gewarnt hat und weiterhin Kontakt mit Gerät 2 hat, gibt es keine Warnung mehr für diesen Kontakt.

>  Kann man herausfinden wann die Ermittlung aktiviert wurde? Dann könnte ich den Zeitpunkt genauer nennen.

Du kannst mal in den iOS-Einstellungen schauen was dort der frühste Zeitpunkt ist: 

`Einstellungen` ➡️ `Begegnungsmitteilungen` ➡️ `Status von Begegnungsaufzeichnungen` ➡️ `Begegnungsüberprüfungen`

**Comment by Servior1** [comment]
Die Ermittlung wurde in jedem Fall vor dem teilen des Ergebnis aktiviert, somit müsste müsste Gerät2 doch warnen?
Das Ergebnis stand erst am 01.03. zur Verfügung. Die Ermittlung war am 28.02. allerdings schon aktiv.

Verstehe ich dies nun korrekt?
Wenn ich am 01.03. meinen Test als positiv in der App hinterlege, am 02.03. hätte ich nun einen Kontakt, so meldet die App bei meiner Kontaktperson niemals etwas?

**Comment by Ein-Tim** [comment]
> Wenn ich am 01.03. meinen Test als positiv in der App hinterlege, am 02.03. hätte ich nun einen Kontakt, so meldet die App bei meiner Kontaktperson niemals etwas?

Korrekt, so ist es auch wenn das Gesundheitsamt die Kontaktnachverfolgung macht.

> Die Ermittlung wurde in jedem Fall vor dem teilen des Ergebnis aktiviert, somit müsste Gerät2 doch warnen?

Der Prozess ist hochkomplex, wurde auf Gerät 1 der Beginn der Symptome angegeben?

**Comment by Ein-Tim** [comment]
> Ja, Beginn der Symptome (Samstag) habe ich angegeben.

Okay, und der Samstag war ja auch der erste Kontakt vor dem positiven Ergebnis mit Gerät 2, oder?

> Irgendwie hört sich die CWA damit ziemlich nutzlos an. Gerade wenn ich ansteckend bin, sollte die App doch einen Zeitraum über den positiven Befund hinaus warnen. Nur weil Quarantäne angeordnet ist, hält sich halt nicht jeder daran.

Leider ist das nicht möglich, dafür müsste der Nutzende alle 5 Tage manuell bestätigen, dass eine neue Warnung ausgeführt werden soll.

**Comment by Servior1** [comment]
Korrekt, die Geräte „kennen“ sich nun schon mehrere Wochen.
Nur die Risikoermittlung war an Gerät2 nicht zu Ende eingerichtet. Grundsätzlich war die App allerdings installiert.

**Comment by MikeMcC399** [comment]
Is there anything further which can be done on this issue? If not, it should probably be closed.
