### ISSUE TITLE
Offensichtliche Asymmetrie bei der Risikoermittlung iOS und Android / expected behavior?

### ISSUE THREAD

**Issue by ts-mz** [corona-warn-app/cwa-documentation#865]
Die CWA im Android Gerät meldet eine Begegnung mit erhöhtem Risiko für den vergangenen Samstag.  Die CWA im iOs-Gerät meldet dagegen nichts. Beide Geräte befanden sich am betreffenden Tag maximal für die Dauer eines Toilettenbesuchs außer Sichtweite, also eine Dauer weit unterhalb der zeitlichen Risikoschwelle für erhöhtes Infektionsrisiko - sofern diese nicht kürzlich deutlich gekürzt wurde. Während der einzigen möglichen Begegnung oberhalb der zeitlichen Schwelle (Nebentisch Café außen, 3-4m Entfernung) lagen beide Geräte nebeneinander.

## Expected behaviour

Symmetrisches Verhalten von iOS und Android CWA - entweder eine rote Kachel auf beiden Geräten oder keine rote Kachel auf beiden Geräten.

**Comment by Ein-Tim** [comment]
Schau mal hier: https://www.coronawarn.app/de/faq/#dissimilar_indication_of_risk_status

**Comment by ts-mz** [comment]
Ah. Danke.

**Comment by dsarkar** [comment]
@Ein-Tim @ts-mz We are preparing more FAQ articles, which hopefully explain/cover this type of questions.
