### ISSUE TITLE
In which circumstances will the user be able to update their certificate in the CWA?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#867]
## Your Question
If I understood correctly from PRs & the text which is in the latest `release/2.19.x` branches in the https://github.com/corona-warn-app/cwa-app-android & https://github.com/corona-warn-app/cwa-app-ios repository, the user will only be able to reissue their certificate, if they have received a booster certificate with old notation/schema.
However, the question arises if the user will be able to also request reissuing of their certificates if it technically expires soon/is already expired? Or will there even be other circumstances where the user will be able to start the reissuing process?

**Comment by thomasaugsten** [comment]
He is not able to request a reissuing for expired certificates at the moment. Please contact the reissue service provider about planned feature in the future.
