### ISSUE TITLE
Certificate grouping implementation differs between iOS & Android

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#869]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR / Huawei P Smart 2019
- iOS/Android version: 15.4 / 10
- App version: 2.19.0 / 2.19.0

## Describe the bug

The certificate grouping feature has a different implementation under iOS & Android.
While iOS does not show the second name, Android does.

## Steps to reproduce the issue

1. Add a certificate with only only fore- & surname
2. Add another certificate for the same person with forename, middle name & surname
3. See that under iOS only fore- & surname are shown
4. See that under Android fore-, middle & surname are shown

## Expected behaviour

The implementation should not differ between iOS and Android

## Possible Fix

Align iOS to Android.

## Additional context

I can provide certificates via Mail if wished.

---
Internal Tracking ID: [EXPOSUREAPP-12300](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12300)

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for reporting

**Comment by mlenkeit** [comment]
@Ein-Tim do I understand this report correctly, that the grouping itself works consistently across iOS and Android, but that only the name that is displayed for the "group" differs?

**Comment by Ein-Tim** [comment]
@mlenkeit

Yes, this is what I am experiencing.

**Comment by mlenkeit** [comment]
Ok, understood. This behavior is indeed not clearly defined, we'll take a look at it.

**Comment by svengabr** [comment]
I have just checked the linked Jira issue.

Jira Ticket is flagged as:
Resolution: `Wont Fix`
Status: `Obsolete`

Developer comment:
> As there is no way to decide whats wrong or right, we decided to keep the current behaviour for both OS
