### ISSUE TITLE
Glossary of Terms additions neccessary

### ISSUE THREAD

**Issue by HolgerMayer** [corona-warn-app/cwa-documentation#87]
## What is missing
The difference between teleTan and Tan Should be described in more detail

Missing terms:
Diagnosis keys
Registration Token
Score Parameter
AES 
CTR

## Why should it be included
If one reads an unkown term in the documentation he or she should easily get a definition from the glossary that is clear and concise

## Where should it be included
Glossary

**Comment by eykkny** [comment]
Thank you for the proposal @HolgerMayer. That is exactly what we added yesterday. Please find the glossary here: https://github.com/corona-warn-app/cwa-documentation/blob/master/glossary.md

We would be happy if the community would help to fill the list.

**Comment by SebastianWolf-SAP** [comment]
Fixed with commit 75263146a2e407a5ae4ad10327ec8de9233164d5. Please let us know in case we need to extend the glossary even more or if any explanation is not correct.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
