### ISSUE TITLE
DCC validity check: Wrong entry rules for Malta

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#873]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Not important
- iOS/Android version: Not importan
- App version: Not important

## Describe the bug

The DCC entry validity check uses wrong rules for Malta. It rejects all certificates as invalid if they are older than 90 days, however, according to https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/eu-digital-covid-certificate_en the validity period of 270 days is binding.
Malta also states that the 270 days is actually the rule (see https://deputyprimeminister.gov.mt/en/health-promotion/covid-19/Documents/Standards_vaccine_certificate_validity_100322_clean.pdf).

## Steps to reproduce the issue

Should be clear, you have to use a certificate of a person which is older than 18 years.

## Expected behaviour

Malta should have rules which complies with the actual rules set by the country. 

## Possible Fix

Relay this to Malta.

## Additional context

Is there any good place to report such issues? The CWA repos seem to be the wrong place, IMO.

**Comment by thomasaugsten** [comment]
Unfortunately MT has not the prod BR as test data uploaded but you can see the latest uploader. But I'm not sure if this repo is the correct one for an issue
https://github.com/eu-digital-green-certificates/dgc-business-rules-testdata/tree/main/MT

**Comment by Ein-Tim** [comment]
@thomasaugsten 

I just need an advice where to report such issues then, where they not only lay around without being touched but where Malta actually takes a look at the problem.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I can reproduce this issue with a 2/2 vaccination certificate. It is failing rule VR-MT-0010 (1.0.0) on CHECK VALIDITY FOR TRAVEL on CWA Android 2.19.1. See https://timokoenig.github.io/eu-dcc-rules/?ruleset=eu-dcc-rules&country=MT&rule=VR-MT-0010 for the rule.

"EN: Verification Datetime must be less than 90 days after vaccination of 2nd dose for age >18"

With a 3/3 booster vaccination certificate, the test passes for Malta and I get a green tick.

You should probably revise your problem description if you can confirm that a 3/3 certificate works.

> IHMO

I translate to IMHO.

**Comment by thomasaugsten** [comment]
My advice is to use the dgc busines rules testdata repo and tag the person which created the test data for MT.

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Issue opened: https://github.com/eu-digital-green-certificates/dgc-business-rules-testdata/issues/105

I'll close this issue here now, however, if there is no feedback in the next 2 weeks, I'll reopen it.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Did you try with a 3/3 certificate?

Was it rule VR-MT-0010 (1.0.0) which failed for you? You did not mention this rule in https://github.com/eu-digital-green-certificates/dgc-business-rules-testdata/issues/105. A screenshot might have been helpful.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I'll extend the report later this evening, I'm quite busy, sorry!

**Comment by MikeMcC399** [comment]
@Ein-Tim 
The rules are aligned to https://deputyprimeminister.gov.mt/en/health-promotion/covid-19/Pages/travel.aspx

For Adults aged 18 years and over:

- primary schedule  with last dose administered not more than 3 months previously OR 
- primary schedule1 and booster with last dose of booster administered not more than 9 months previously

**Comment by Ein-Tim** [comment]
@MikeMcC399 

So you think the rules Malta has on https://reopen.europa.eu/de/from-to/DEU/MLT are wrong?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> So you think the rules Malta has on https://reopen.europa.eu/de/from-to/DEU/MLT are wrong?

I think I misread the information. The text I quoted was only for "A valid vaccine certificate issued by the Maltese Authorities is defined as follows: " Unfortunately the page is not well formatted.

Go ahead and see what the Maltese representative has to say. I think you are right that a EU 2/2 vaccination certificate should be sufficient for 270 days, except if it is a Maltese certificate, in which case a booster may be necessary, so they would need to add this exception for EU non-Maltese vaccination certificates to their rules.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

- I see that https://github.com/eu-digital-green-certificates/dgc-business-rules-testdata/issues/105 has been closed.

An important part of this exchange is that it highlights there is no clear support path for issues with EU travel rules. That would be another issue though.

**Comment by Ein-Tim** [comment]
> An important part of this exchange is that it highlights there is no clear support path for issues with EU travel rules. That would be another issue though.

Yep, I'm getting in touch with @dslmeinte to find a solution for this problem.

**Comment by Ein-Tim** [comment]
As always: Thanks for all your support, Mike! I really appreciate it! 👍
