### ISSUE TITLE
Out of date information in the app reg. entitlement to free corona test with increased risk encounter(s)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#877]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Not relevant
- iOS/Android version: Not relevant
- App version: 2.19.1 / 2.19.2

## Describe the bug

The CWA includes this sentence: 
"Please get tested, even if you don’t have any symptoms. **If you get a warning of increased risk (“red tile”), you are entitled to a test free of charge. It does not necessarily have to be a PCR test.**"

However, with the new "Erste Verordnung zur Änderung der Coronavirus-Testverordnung Vom 11. Februar 2022" there actually is no special entitlement by law anymore, should the Corona-Warn-App show red.

## Steps to reproduce the issue

1. Get an increased risk encounter
2. Tap on the increased risk tile 
3. Scroll down
4. See the outdated text

## Expected behaviour

The app should not make outdated statements.

## Possible Fix

Change the text.

---
Internal Tracking ID: [EXPOSUREAPP-13209](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13209)

**Comment by Ein-Tim** [comment]
I provided a PR under iOS which fixes this issue: https://github.com/corona-warn-app/cwa-app-ios/pull/4391

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Please check also:

https://www.coronawarn.app/en/faq/results/#vac_cert_red_warning "How to behave if I am recovered, partially or completely vaccinated, but receive a red warning in the Corona-Warn-App?"

"In case of an increased risk warning (red tile), you are entitled to a free test. This does not necessarily have to be a PCR test."

---

https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Warn_App.html also vaguely mentions a free test:

"Bei der kostenlosen Testung ..." in the section about a red warning in the app.

**Comment by Ein-Tim** [comment]
FYI: @marcussc informed me in https://github.com/corona-warn-app/cwa-app-ios/pull/4391#issuecomment-1080834789 that there will be a general overhaul of the "Handlungshinweise" section in the app. Thus my PR was closed.

I'm fine with that, as long as the rework of this section in the app will come somewhat soon.

**Comment by svengabr** [comment]
As Marcus already mentioned, the team is currently working on an overhaul of this topic. Unfortunately, no information can be shared here at the moment.

Everyone has the possibility to get free rapid tests until the end of May. The increased risk encounter screen texts will not be changed until the team is finished with the overhaul.

**Comment by Ein-Tim** [comment]
@svengabr Wouldn't it make more sense to leave this issue open until the text has been corrected?

**Comment by Ein-Tim** [comment]
@svengabr Could you please reopen this issue until the problem is addressed?

**Comment by Ein-Tim** [comment]
@dsarkar Please, can this issue be re-opened until it was actually addressed?

**Comment by Ein-Tim** [comment]
@dsarkar @svengabr 

Dear Team, it has been two months since the risk card overhaul has been promised. Since then we did not see any movement on this issue.

Could you please check for which version this overhaul is planned and if there is no fixed version yet cross check if it the PR I provided two months ago would be accepted when provided now.

**Comment by larswmh** [comment]
Thanks for your report @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-13209](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13209)

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Hi @Ein-Tim, 

as far as I understand it, users with a red card in the CWA should in general get a RAT.

See e.g.: https://www.zusammengegencorona.de/testen/die-nationale-teststrategie/ (May 11, 2022)
![image](https://user-images.githubusercontent.com/1409741/170991937-052d6ae0-d164-4ac3-9e15-7d77d987ab9a.png)

**Comment by Ein-Tim** [comment]
@dsarkar 

Hey, thanks for the feedback! Yes, they should get a RAT, but they have no legal entitlement to this, or am I mistaken? They just have to use their entitlement of a "Bürgerstest".

**Comment by MikeMcC399** [comment]
I also commented on this same issue in https://github.com/corona-warn-app/cwa-website/issues/2607.

https://www.bundesgesundheitsministerium.de/coronavirus/nationale-teststrategie/faq-covid-19-tests.html#c23926

![image](https://user-images.githubusercontent.com/66998419/170996274-238879ea-4b27-4522-a39f-55831f7f33a1.png)

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399 So your suggestion would be to be more specific un the app and to mention the entitlement of a test in the sense of "Bürgertest"?

**Comment by dsarkar** [comment]
@Ein-Tim Maybe I don't get it: A Bürgertest is free, if you go to the doctor, my understanding is that the test is free.

The issue here is rather of being more precise. (?)

**Comment by Ein-Tim** [comment]
@dsarkar Yeah, right. Because right now the text "Bei einer Warnung über ein erhöhtes Risiko ("Rote Kachel") haben Sie Anspruch auf auf einen kostenlosen Test." says that you are entitled to a free test **because of** the CWA, although your entitlement to a free test has nothing to do with the CWA.

**Comment by MikeMcC399** [comment]
The full DE text, also in CWA Android [release/2.23.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.23.x) from `risk_details_increased_risk_faq_link_text`
https://github.com/corona-warn-app/cwa-app-android/blob/b70569c8e1fe4fa4e26d37e2bbb7e4ff7acead13/Corona-Warn-App/src/main/res/values-de/strings.xml#L275-L276

"Lassen Sie sich testen, auch wenn Sie keine Symptome haben. Bei einer Warnung über ein erhöhtes Risiko („Rote Kachel“) haben Sie Anspruch auf einen kostenlosen Test. Dies muss nicht notwendigerweise ein PCR-Test sein."

![high_risk_2](https://user-images.githubusercontent.com/66998419/171019595-cb5aeee8-ecb4-4ddf-9886-f95f9d3cf919.png)

**Comment by MikeMcC399** [comment]
This is such a central theme to CWA that it should be better explained. At least as well as on the website of the BMG, although maybe it is not necessary to quote exactly the legal paragraphs.

For instance:

"Lassen Sie sich testen, auch wenn Sie keine Symptome haben. Sie haben Anspruch auf eine kostenfreie Antigen-Schnelltestung (Bürgertestung). Fällt der Antigen-Schnelltest positiv aus, haben Sie Anspruch auf einen kostenlosen PCR-Test zur Bestätigung des Schnelltestergebnisses. Bei Vorliegen von COVID-19-spezifischen Symptomen kann im Rahmen der Krankenbehandlung durch einen Arzt/eine Ärztin auch direkt ein PCR-Test veranlasst werden."

**Comment by larswmh** [comment]
Closing this issue as its related internal ticket was set to `obsolete`.

Developer comment:
> People are still entiteled for a free antigen test. Therefore the sentance is still correct.

**Comment by Ein-Tim** [comment]
Mh, the sentence is incorrect in my opinion, and it has been fixed on the website. But your call here.

**Comment by MikeMcC399** [comment]
@larswmh 
> Developer comment:
>
>>People are still entiteled for a free antigen test. Therefore the sentance is still >>correct.

The fact that people are still entitled to a free test does not make the sentence "Bei einer Warnung über ein erhöhtes Risiko („Rote Kachel“) haben Sie Anspruch auf einen kostenlosen Test." correct.

The sentence implies that a red warning of its own right gives entitlement to a free test and it is therefore misleading. If the sentence were changed to "Sie haben Anspruch auf einen kostenlosen Test." i.e. remove the text "Bei einer Warnung über ein erhöhtes Risiko („Rote Kachel“)" it would be correct and not misleading.

- See also discussion in PR https://github.com/corona-warn-app/cwa-website/pull/2921

§6 (3) Leistungserbringung of [TestV](https://www.gesetze-im-internet.de/coronatestv_2021-10/) was changed on Feb 12, 2022, see https://www.buzer.de/gesetz/14991/al164025-0.htm

![image](https://user-images.githubusercontent.com/66998419/173530812-a27f9d1b-2556-4016-8059-b0c6ea14ec5e.png)

**Comment by larswmh** [comment]
@Ein-Tim @MikeMcC399 thanks for your feedback. Forwarding this to the internal ticket and will let you know once there's an update.

**Comment by Ein-Tim** [comment]
@larswmh 

Please reopen this issue.

**Comment by larswmh** [comment]
@Ein-Tim @MikeMcC399 

Developer comment:
> Issue was discussed in today's RKI call. Feedback: While the finding is in general correct, RKI's interpretation is still that people with a red risk card should get a free antigen test. As there is anyhow some changes in regards to free of charge antigen tests expected in the next months, we dont't do any changes now.

Closing this issue again accordingly, but thank you for your insistence. This is a more informative conclusion.

**Comment by MikeMcC399** [comment]
@larswmh 

§19 [TestV](https://www.gesetze-im-internet.de/coronatestv_2021-10/) says:

"(1) Diese Verordnung tritt am 11. Oktober 2021 in Kraft; sie tritt am 30. Juni 2022 außer Kraft."

Is it clear what the status will be on July 1, 2022? Will it be extended, changed or allowed to expire?

**Comment by Ein-Tim** [comment]
@svengabr & @dsarkar & @larswmh 

Please reopen this issue and bring to the attention of PO & stakeholders ASAP. Tests won't be free of charge anymore beginning next month! App needs to be changed!

**Comment by MikeMcC399** [comment]
This issue is continued in #903.
