### ISSUE TITLE
How can I use the qr-code validator endpoint on a third-party app.

### ISSUE THREAD

**Issue by farhadnowzari** [corona-warn-app/cwa-documentation#879]
Hello everyone,

Thanks for everyone's effort on this app.

We have to develop an application in which the users have to verify their Corona certificate documents.

Now either they will upload these documents or will scan their qr-code.

The question I have is that, How to integrate the `validator` APIs into our app or if for security reasons it is not allowed is there an iFrame for the scanner which we can use inside a webpage?

**Comment by MikeMcC399** [comment]
@farhadnowzari 

Nobody has respond here so far and I think that is probably because you are in the wrong repository. I can't say for sure, but you may have more luck if you place your question in https://github.com/Digitaler-Impfnachweis/certification-apis/discussions.
