### ISSUE TITLE
SARS-COV-2 mutations and immunity

### ISSUE THREAD

**Issue by HolgerMayer** [corona-warn-app/cwa-documentation#88]
## Where to find the issue

Concept 

## Describe the issue
Missing case reinfection with a new strain of Sars-Cov-2

The information system should be enabled to handle different SARS-COV-2 variants.
There have been cases, where a person with a SARS-COV-2 infection recovered and then reinfected himself. There are also several known mutated variants.

Therefore a diagnose key should include or at least be prepared to carry a version id for the virus.

Scenario:
Bob has been infected. Anne has been infected too. Both have recovered. Now Bob catches a mutated infection. Anne either doesn‘t use the app anymore or ignores a message because she thinks she recovered. 
With a version system she could be informed that she  got reinfected with a different strain.

## Suggested change

At least prepare the interfaces so that a version can be set even if this functionality will be implemented later or this will be an upgrade nightmare later on.

**Comment by SebastianWolf-SAP** [comment]
All involved parties (Apple, Google, us...) try to minimize the amount of data which is collected and processed to the absolute minimum. This also includes the format of the temporary exposure/diagnosis keys. We simply work with the format as it is currently defined in the Exposure Notification Framework. As we want to keep avoiding unnecessary data we won't engage in upfront discussions with Apple/Google about additional fields which _might_ be needed in the future. 

Moreover, as this a very volatile environment, incompatible changes will happen anyway and we are aware of the fact that we need to handle them when they actually happen.

Consequently, we will close this issue. Thank you for your understanding!
SW
Corona Warn-App Open Source Team
