### ISSUE TITLE
Documentation not updated to 14->10 days reduction in CWA 2.20

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#882]
## Where to find the issue
Many documents in this repository are affected.

## Describe the issue
With version 2.20 the apps do only consider the last 10 and not the last 14 days anymore. However, there was no update of the documents in this repo with the 2.20 release. 

## Suggested change
Review each document, which was not deprecated, and update the documents if necessary.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Could you give an example? In many cases the GAEN API still handles 14 days of data although CWA from 2.20 onwards only uses 10 of those days.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

E.g. in https://github.com/corona-warn-app/cwa-documentation/blob/main/solution_architecture.md#pcr-tests-retrieval-of-lab-results-and-verification-process:
"The TAN is used as authorization in the HTTP header of the POST request for upload of the diagnosis keys of the last 14 days to the Corona-Warn-App Server (Figure 3, step 14)."

Although I'm not sure if the app still uploads 14 days and the server omits everything older than 10 days?

**Comment by thomasaugsten** [comment]
Still uploading 14 days

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Is [this](https://github.com/corona-warn-app/cwa-documentation/blob/main/solution_architecture.md#data-retention) statement still true:

"The data on all involved servers is only retained as long as required. Diagnosis Keys will be removed from the Corona-Warn-App Server when they refer to a period of more than 14 days ago."

**Comment by thomasaugsten** [comment]
This is still correct

**Comment by Ein-Tim** [comment]
@thomasaugsten Is the server also still offering all data from the last 14 days to download? Or is there some sort of filtering which filters out all DKs which are older than 10 days?

**Comment by thomasaugsten** [comment]
The server is filtering out TRL 1 and 2 and only provide key package files of the last 10 days.
A 10 day old key package can also include a 14 day old key if the TRL is higher as 2
