### ISSUE TITLE
Booster recommendation different placement under iOS & Android

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#883]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR / Huawei P Smart 2019
- iOS/Android version: 15.4.1 / 10
- App version: 2.20.3 / 2.20.4

## Describe the bug

The booster recommendation is placed differently between iOS & Android.

| Android | iOS |
|---|---|
| ![Android CWA](https://user-images.githubusercontent.com/67682506/162566518-8400844e-2bf6-42ab-91a5-972f90605376.jpeg) | ![iOS CWA](https://user-images.githubusercontent.com/67682506/162566522-0fd930d0-892d-40d5-a10a-969d9907ed3f.jpeg) |

## Steps to reproduce the issue

1. Open the Corona-Warn-App
2. Tab on "Certificates"
3. Scan a certificate which yields a booster recommendation
4. See where the booster recommendation box is placed

## Expected behaviour

The booster recommendation should be placed at the same spot.

## Possible Fix

Align iOS to Android.

---
Internal Tracking ID: [EXPOSUREAPP-12723](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12723) duplicates
Internal Tracking ID: [EXPOSUREAPP-12438](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12438)

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for reporting! Enjoy your Sunday!

**Comment by Ein-Tim** [comment]
iOS PR: https://github.com/corona-warn-app/cwa-app-ios/pull/4538

**Comment by Ein-Tim** [comment]
Confirm fixed under iOS with 2.23.1.

Closing as fixed.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for the feedback. Forwarded to the internal tickets as CONFIRMED.
