### ISSUE TITLE
Swiss flag on "Transnational exposure logging" screen

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#884]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR / Huawei P Smart 2019
- iOS/Android version: 15.4.1 / 10
- App version: 2.20.3 / 2.20.4

## Describe the bug

On the transnational exposure logging screen, the Swiss flag is still visible, although Swiss is not listed as active anymore. 

## Steps to reproduce the issue

1. Open the app
2. Click on "Exposure logging active"
3. See the Swiss flag below the EU flag on "Transnational Exposure Logging"
4. Tap on "Transnational Exposure Logging"
5. See the Swiss flag at the very top of the screen

## Expected behaviour

The Swiss flag should not be visible if Swiss does not participate in the transnational exposure logging anymore. 

## Possible Fix

Remove the Swiss flag.

---
Internal Tracking ID: [EXPOSUREAPP-12776](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12776)

**Comment by MikeMcC399** [comment]
- https://github.com/corona-warn-app/cwa-website/issues/2737 contains some official references, including:

"Das Verbindungssystem zum Austausch der privaten Schlüssel des PT-Systems mit einem entsprechenden ausländischen System wird weiterbetrieben, solange dies zur Erfüllung staatsvertraglicher Verpflichtungen der Schweiz erforderlich ist; der Datenaustausch zwischen dem Backend-System zur Verwaltung von Annäherungsdaten und dem Verbindungssystem wird eingestellt."

Currently Switzerland states they are "temporarily suspended".

**Comment by dsarkar** [comment]
Feedback: It was explicitly decided to keep the Swiss Flag in, because Swizerland is currently only disabled and might be enabled again in autumn.
