### ISSUE TITLE
Question on closing of registration process for testing stations

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#888]
## Your Question
I have a question regarding the closing of the registration process for testing stations, which was announced via https://github.com/corona-warn-app/cwa-registrierung/commit/db7ec076dc37175c7805b75c5b335cd04f0ee2f0.

Does this only affect registration of RAT testing stations or also PCR testing stations?

---
Internal Tracking ID: [EXPOSUREAPP-13062](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13062)

**Comment by dsarkar** [comment]
Hi @Ein-Tim, your question was forwarded.

**Comment by Ein-Tim** [comment]
@thomasaugsten I'm sure you know that. Maybe you could quickly clarify?

**Comment by Ein-Tim** [comment]
@dsarkar Is there an update on this issue available?

**Comment by dsarkar** [comment]
@Ein-Tim I will ask that question again internally.

**Comment by Ein-Tim** [comment]
The question itself, which I asked in the OP of this issue, is still valid, but, as the CWA project went into ramp-down mode, I'm not interested in an answer to this question anymore. I'm therefore closing this issue now.
