### ISSUE TITLE
Will it be possible to renew "1/2" certificates? and other questions on renewal of certificates

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#889]
## Your questions

1. Will it be possible to renew "1/2" certificates?
This does not seems senseful to me, as the certificate is not valid anyways.

2. Why should the user renew "2/2" if they have a "3/3" certificate? Same goes for renewing "3/3" certificates if one has a "4/4" certificate.
As a user, CWA always selects the certificate with the highest priority and defaults to this. If I have the following certificates in my app:
- "1/2"
- "2/2"
- "3/3"
CWA will default to the 3/3 one. For me as the user, it is not relevant if the 2/2 certificate or 1/2 certificate expires. So why should the app offer to renew these certificates in this situation?

## Background

CWA 2.23 will offer a feature to renew certificates, see e.g. https://github.com/corona-warn-app/cwa-app-ios/pull/4533.

## Ping

@mlenkeit, as he seems to be responsible for CCL and this renewal of certifies will be performed via CCL.

**Comment by thomasaugsten** [comment]
The app will offer you an renewal for your 
latest vaccination certificate when it will expire in the next 28 days.
recovery certificate when it will expire in the next 28 days

**Comment by Ein-Tim** [comment]
@thomasaugsten But only for the latest one, so e.g. not the 2/2 one if I also have a 3/3?

**Comment by thomasaugsten** [comment]
Correct only your latest

**Comment by Ein-Tim** [comment]
@thomasaugsten Good to know, thanks!

**Comment by Ein-Tim** [comment]
Actually, reopening.

@thomasaugsten Did the team adjust the texts in the app? Looking at the screenshots on https://www.coronawarn.app/en/screenshots/#ios_invalid_certificate it seems like the app will show the hint to get a new digital certificate. Will this also be shown on expiring certificates which are not the currently used ones?
Because this would be confusing.


---


Ich Wechsel mal schnell zu Deutsch um sicherzugehen das wir uns verstehen.

Momentan (Version 2.22) zeigt die CWA mir an, dass ich mich darum bemühen soll einen neuen digitalen Nachweis ausstellen zu lassen, wenn mein 2/2 Zertifikat entweder abgelaufen ist oder bald abläuft.
Dieser Hinweis wird angezeigt obwohl ich auch ein 3/3 Zertifikat in der App habe, was noch gültig ist. 

Wird dieser Text geändert? Weil was du sagst widerspricht dem ja, oder sollte sich der Nutzende trotzdem um ein neues Zertifikat bemühen, die App bietet ihm aber keine Neuausstellung an? Das würde ja nicht so viel Sinn machen.

**Comment by thomasaugsten** [comment]
Der Text wurde angepasst
https://github.com/corona-warn-app/cwa-app-ios/blob/39e858a9e3e1500317889c84bdbd25b297a76218/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L3337

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Thanks for your answer! Hopefully, this is clear enough for the user.
I'd recommend to add another sentence like:
"Wenn dies nicht ihr aktuell verwendetes Zertifikat ist, müssen Sie nichts weiter tun."

What do you think? Else it's a bit unclear to the user what to do, IMO.

**Comment by Ein-Tim** [comment]
Closing in favour of https://github.com/corona-warn-app/cwa-app-ios/pull/4556.
