### ISSUE TITLE
Inconsistent naming

### ISSUE THREAD

**Issue by HolgerMayer** [corona-warn-app/cwa-documentation#89]
## Where to find the issue

Figure_1.svg and Figure_6.svg

## Describe the issue
Figure_1 : Corona-Warn-App (CWA)
Figure_6 : mobile all in one application...

In several other figures it is just mobile app.

## Suggested change

Use one specific name (CWA is better then mobile app). It is the same as with variable names. The name should be consistent and describe what it does.

**Comment by tklingbeil** [comment]
Note that the label in figure 9 needs to remain as it is, as it only describes the architecture from generic perspective.
