### ISSUE TITLE
Contributions from the community

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#890]
Dear Corona-Warn-App-Team, dear Open-Source-Team.

First of all, I want to make clear that this issue is **not** a personal attack against anyone! I appreciate the work the Open-Source-Team does and can only imagine the workload @svengabr, @dsarkar & @larswmh have! You're great guys, keep it up.

But still, there is something I find really annoying. Let's dive into this.

### 1. Assessing issues

On 18. Apr. 2022 I opened the PR https://github.com/corona-warn-app/cwa-app-ios/pull/4458 in the https://github.com/corona-warn-app/cwa-app-ios repository. This PR was intended to address https://github.com/corona-warn-app/cwa-documentation/issues/578 which I opened on 07. Apr. 2021, so more than one year before I opened the PR.
The PR was rejected, as the team considers the texts as correct. This is fine, I understand that there may be things the community considers as an issue, but the team does not (e.g. [this](https://github.com/corona-warn-app/cwa-documentation/issues/884)).
However, as the issue https://github.com/corona-warn-app/cwa-documentation/issues/578 was opened more than a year ago, I would expect that there is an internal process to look at incoming issues, asses them, and if irrelevant/wont fix get this information back to GitHub & close the corresponding issue after explanation.

After the PR was closed I wrote [this](https://github.com/corona-warn-app/cwa-app-ios/pull/4458#issuecomment-1102382032) comment in the PR, as a response to @dsarkar telling me that the PR won't be merged. 

> Thank you for the response. Such information would be nice in the issue, which stayed open without any feedback for over a year. If an issue is open, in general it can be tackled by someone from the community and the work done should not be lost. In this case it is only a minor change, and I'm fine with closing this PR now. But there are bigger issues, which might also be addressed by the community because the issue is open and there is no information on the issue to not work on it.
>
> I will open a new issue discussing how issues should be tackled by the community and how the communication between the team and the community can be improved so that there is no work done by the community, which then has to be rejected.
>
> EDIT: I won't open an issue and will see how things evolve :D

In response, @dsarkar wrote in [this](https://github.com/corona-warn-app/cwa-documentation/issues/578#issuecomment-1102392449) comment: 
> […] in order to avoid working on a PR that might be rejected, you can ping me or another Corona-Warn-App Open Source Team member and we will try to get feedback from the dev team […]

That sounded good to me, however, I still [responded](https://github.com/corona-warn-app/cwa-documentation/issues/578#issuecomment-1102403472) that I think issues should be closed/assessed/fixed continuously, and not only when someone from the community comments on it or provides a PR.

@dsarkar [answered](https://github.com/corona-warn-app/cwa-documentation/issues/578#issuecomment-1103983232) that some issues snow under, especially if they are not critical. Ok, that's totally understandable!

So, that's my first point: **Assess incoming issues on a regular basis, and not only mirror them to JIRA and let them sit there until you have to act, because e.g. the community provides a PR.**

---

### 2. Communication between the community and the team

Now the second point, something that is not understandable. Following @dsarkar's [comment](https://github.com/corona-warn-app/cwa-documentation/issues/578#issuecomment-1102392449) to ping him or another Corona-Warn-App Open Source-Team member to get feedback on an issue before providing a PR, I did exactly this. 
In https://github.com/corona-warn-app/cwa-website/issues/1319, an issue opened on 31.05.2021 by @dsarkar, I offered via https://github.com/corona-warn-app/cwa-website/issues/1319#issuecomment-1098042184 to provide a PR. @dsarkar responded that this is appreciated, nice sounds good.
In https://github.com/corona-warn-app/cwa-website/issues/1319#issuecomment-1099994038 I presented my plan on what to do, to get feedback from the community & the team.
After @MikeMcC399 [pointed](https://github.com/corona-warn-app/cwa-website/issues/1319#issuecomment-1100002029) [out](https://github.com/corona-warn-app/cwa-website/issues/1319#issuecomment-1100130651) why my plan may not be a good one, @MikeMcC399 and I came to the conclusion that we could not continue on this issue without feedback from the team.
That was on 15. Apr. 2022, so ca. 1 1/2 months ago.
In 1 1/2 months, nobody from the team came back to the issue, not even after 4 pings from @molarya1 & me ([1](https://github.com/corona-warn-app/cwa-website/issues/1319#issuecomment-1101598627), [2](https://github.com/corona-warn-app/cwa-website/issues/1319#issuecomment-1105719557), [3](https://github.com/corona-warn-app/cwa-website/issues/1319#issuecomment-1114210985), [4](https://github.com/corona-warn-app/cwa-website/issues/1319#issuecomment-1133940182)).

That's only one case, you might think. Yeah, this might be only one case, but at the very same time, a similar behavior can be seen in https://github.com/corona-warn-app/cwa-website/issues/2751. After the community assessed the situation together with the Open Source-Team, @MikeMcC399 [asked a good question](https://github.com/corona-warn-app/cwa-website/issues/2751#issuecomment-1113334921) on how to continue reg. the luca stand by, as it seems to have 0 influence on CWA users. Mikes comment is meanwhile one moth old, nobody ever responded to it, not even after I pinged @dsarkar three times ([1](https://github.com/corona-warn-app/cwa-website/issues/2751#issuecomment-1123330445), [2](https://github.com/corona-warn-app/cwa-website/issues/2751#issuecomment-1130391813), [3](https://github.com/corona-warn-app/cwa-website/pull/2757#issuecomment-1125885590)).

So, my second point is **If you want the community to contribute to this project, you have to work with it.** Ignoring them until they go away is not a very intelligent move, as community members take workload off the team. If, for any reasons whatsoever, you're currently not able to assess the situation of an issue, comment this on the issue so the community does not feel ignored.

I really like the Corona-Warn-App, I love the great community, the open development process where community feedback is taken seriously and as a community member I have the feeling to be heard! Please take the two points I pointed out above as feedback where there is still room for improvements. **Again: This is not an attack against anyone! This is not something personally but just something which disturbs my work on this project.**

Thanks and have a nice Sunday.

**Comment by MikeMcC399** [comment]
@dsarkar announced on Aug 4, 2022 in https://github.com/corona-warn-app/cwa-app-ios/issues/4602#issuecomment-1205004898 that the team of @svengabr, @dsarkar & @larswmh would only be looking sporadically in August 2022. Since that time there have been no further posts from them. In practice this has meant that some inputs from the community have been picked up and actioned whereas other postings have not.

It would be good to hear what the future plans for the app are. Der Spiegel reported that the contract runs until the end of 2022 and BMG would like to extend to end of May 2023.

The Bundesregierung wrote in [Zwei Jahre Corona-Warn-App: Erfolgreich und Vielfältig](https://www.bundesregierung.de/breg-de/suche/2-jahre-corona-warn-app-2041346) about the success of the app. Considerung the high numbers of downloads already reached (> 46 Million according to https://www.coronawarn.app/en/analysis/) there should still be an active community management in place until the app reaches end-of-life and is declared obsolete.

Hoping to hear back from a community management team soon again!

**Comment by Ein-Tim** [comment]
This issue is obsolete, and I'm closing it now.
