### ISSUE TITLE
Contact Journal: Do not show "Do you really want to remove this person/place?" warning when person/place is not used in the contact journal

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#892]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: not important
- iOS version: not important
- App version: 2.7.2

## Describe the bug

The warning "Do you really want to remove this person? If you remove this person, all the entries for that person will be removed from your journal." is shown when a user attempts to delete a person, even if the person is not used in the contact journal. Same goes for places. This does not make sense & is confusing.

https://user-images.githubusercontent.com/67682506/129937916-b37fc068-102f-45f5-8568-ddb5e9326a27.MP4

## Steps to reproduce the issue

1. Open the Corona-Warn-App
2. Click on the "Journal" tab
3. Click on todays date
4. Create a new person via the "Add Person" button
5. Deselect the person 
6. Navigate back using the "Back" button
7. Click on the 3 dots in the right corner
8. Click on "Edit People"
9. Click on the red -
10. Click on "Delete"
11. Read the text of the warning pop up

## Expected behaviour

The warning should only be shown when a person is used in the journal.

## Possible Fix

Adapt the logic or change the text of the notification to something like "If you remove a person, you can not use it again in your journal again. If this person is currently used in your journal, all the entries for that person will be removed."

## Additional context

Please check the behavior under Android.

----
Internal Tracking-ID: [EXPOSUREAPP-9082](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9082)

**Comment by svengabr** [comment]
@Ein-Tim 

Jira issue labeled as `wont-fix`

> Expected behaviour
> 
> The warning should only be shown when a person is used in the journal.
> 
> I don't agree since the Person might be reused in the future and we want to protect the user from deleting a person/place. If we wouldn't have to protect the user from such mistakes we wouldn't have needed the recycle bin.
