### ISSUE TITLE
Conflicting advice for non-current vaccination certificate renewal

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#899]
## Technical details

- Android version: Android 12
- App version: 2.23.2
(The issue is also present in [v2.24.0-rc.1](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.24.0-rc.1).)

This issue also affects iOS.

## Describe the bug

When a vaccination certificate has a Technical Expiration Date in the zone for renewal (28 days before expiry) the following texts are displayed:

- "If this is not the certificate you currently use, it does not have to be extended and no action is required on your part."
- "Please make sure to get a new digital certificate in time."

The second sentence providing advice is contradictory to the first statement. In the case of no action is required, then the user should not be instructed to get a new certificate.

## Steps to reproduce the issue

In CWA Android:

1. Tap Scan button and scan a 1/2 vaccination certificate which expires in the next 28 days
2. Tap back arrow
3. Tap scan button and scan a 2/2 vaccination certificate (with expiry date more than 28 days into the future)
4. Tap back arrow
5. Tap Certificates
6. Tap right arrow
7. Scroll down to Vaccination 2 of 2 and note that it is marked as "Currently used certificate"
8. Scroll down to Vaccination 1 of 2 and tap on tile
9. Read the text underneath the QR code which includes the sentence "If this is not the certificate you currently use, it does not have to be extended and no action is required on your part."
10. Scroll further down the page and note the text "Please make sure to get a new digital certificate in time."

![Expiry less than 28 days](https://user-images.githubusercontent.com/66998419/173330748-2ef15496-defc-4dd2-84b8-d15b41a2dcd7.jpg)

## Expected behavior

The app should not advise "Please make sure to get a new digital certificate in time" for a  vaccination certificate which is not marked as  "Currently used certificate".

## Possible Fix

Suppress the layout "Technical Expiration Date" with the text "Please make sure to get a new digital certificate in time." if a vaccination certificate is not the latest in a series of vaccinations.

---

Internal Tracking ID: [EXPOSUREAPP-13343](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13343) Android
Internal Tracking ID: [EXPOSUREAPP-13403](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13403) iOS

**Comment by Ein-Tim** [comment]
iOS PR: https://github.com/corona-warn-app/cwa-app-ios/pull/4628

**Comment by larswmh** [comment]
Closing this issue as it was fixed with yesterday's update to version 2.24 on both operating systems.

**Comment by MikeMcC399** [comment]
@larswmh 
> Closing this issue as it was fixed with yesterday's update to version 2.24 on both operating systems.

Were you able to check with the CWA 2.24 Android version from the Google Play Store? I have not received this yet, which is the reason that I had not closed the issue so far.
