### ISSUE TITLE
To contribute to this project I am forced to share my behavioral data with Microsoft

### ISSUE THREAD

**Issue by TomTeeJay** [corona-warn-app/cwa-documentation#9]
To contribute to this project I am forced to register to Microsoft/ GitHub and create an account and I am forced to share my behavioral data. Microsoft knwo what system and dev tools I am using or at which times I am working and with whom I am connected or for which projects I am interested.

This is not Privacy by Design and Default. Is SAP or Telekom not fit and capable to run an own instance of GitLab or Gitea? Every small Developer can do this. Big projects like GNOME do this aswell. Why not SAP or Telekom?

**Comment by SergejKembel** [comment]
Cry me a river.

**Comment by remuslazar** [comment]
@TomTeeJay this is ridiculous, GitHub being the de-facto standard for open source collaboration. Every serious developer in this world does already have an account on GitHub. And, to be honest, I do trust GitHub/Microsoft more than I will trust the "own instance" approach.

I don't want to be rude but, nobody forces you to collaborate here so, well..

**Comment by raethlein** [comment]
Hey @TomTeeJay , thanks for raising your concerns. In our opinion, GitHub is a well-established and respected platform to maintain open-source projects. In case somebody does not want to create a GitHub account, it is possible to reach us via mail at corona-warn-app.opensource@sap.com
