### ISSUE TITLE
Use Corona-Warn-Server instead of Corona-Warn-App-Server

### ISSUE THREAD

**Issue by HolgerMayer** [corona-warn-app/cwa-documentation#90]
## Where to find the issue

Complete Project documentation.
Especially visible in figure_7.svg

## Describe the issue

Corona-Warn-App-Server is not unambiguous 
Example figure 7 Is the corona Warn App Database on the server or on the phone? It should be on the server but why is it not called Corona Warn Server Database?

An does the App-server run on the iPhone like App suggests.

No we got a 
Corona-Warn-Server with a Corona-Warn-Server-Database

and a Corona-Warn-App

## Suggested change
Rename (now -early- lower cost) Corona-Warn-App-Server to Corona-Warn-Server

**Comment by tklingbeil** [comment]
The name of the overall project is "Corona-Warn-App" (the "-App" is a fixed part of the project name - not just of the application). Thus, the components need to be named accordingly (i.e. stay as they are).

**Comment by HolgerMayer** [comment]
The you should at least try to make a clear distinction by using the acronyms with the appendix App or Server even it is from a language point of view not really nice. 

CWA-App
CWA-Server
CWA-Server-Database

Now your even able to later add new client platforms i.e. for doctors with a clear naming schema.
