### ISSUE TITLE
Error report log contains entries older than 14 days

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#901]
## Describe the bug

The list of submitted error reports includes reports which have been submitted more than 14 days ago.

"The error reports are automatically deleted after 14 days" according to https://www.coronawarn.app/en/faq/results/#error_log so like the exposure logs, I would expect to see error report logs only to show the last 14 days. 

## Expected behaviour

There is no value to keep a record of the older log submissions if the data has been deleted. The error report log should only show error reports which have been submitted in the last 14 days.

## Possible Fix

Purge error reports log entries on the app side, not just the server side, after 14 days.

## Additional context

- See https://github.com/corona-warn-app/cwa-app-android/issues/5296 for example showing old error logs.

<img alt="" width="300" src="https://user-images.githubusercontent.com/67682506/175134382-ee555f1a-3bfc-499b-b78d-0c40ea4c6f11.jpg">

---
Internal Tracking ID: [EXPOSUREAPP-13445](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13445)

**Comment by thorbenkuro** [comment]
@MikeMcC399 Thank you for reporting this issue! We created an internal ticket.
Internal Tracking ID: [EXPOSUREAPP-13445](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13445)

@Ein-Tim Thank you for the input on iOS!
