### ISSUE TITLE
Unclear number of repeat tests advised after red tile

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#906]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [ ] Bug is not already reported in another issue
Follows on from https://github.com/corona-warn-app/cwa-documentation/issues/903#issuecomment-1172563460

## Technical details

- App version: 2.24.1

## Describe the bug

The advice given to users with a red tile (increased risk) is:

"Please get tested, for example, with a rapid antigen test, or use self-tests - preferably several times, taking a test every two days. If a test is positive, take a PCR test to confirm the result."

According to the dictionary [several](https://dictionary.cambridge.org/dictionary/english-german/several) means "more than one or two, but not a great many". If no test returns a positive result, it is left to the user to decide how often they should test.

![red test guidelines](https://user-images.githubusercontent.com/66998419/177563625-16950801-9a5c-44c8-aa5b-20c219fc0ca7.png)

## Expected behavior

- If the app advises a user to repeat an antigen test every two days, it should also advise when to stop testing. The current wording suggests that tests should be repeated for an unclear number of times if no test returns a positive result. It would be better if more concrete advice could be given about when to stop testing.

## Related issue

- ~~The linked FAQ article [Red Card? How to go through Corona testing](https://www.coronawarn.app/en/faq/results/#red_card_how_to_test)  is not aligned to the app and does not cover repeat testing.~~<br>**Fixed**: see https://github.com/corona-warn-app/cwa-website/pull/3014.

---
Internal Tracking ID: [EXPOSUREAPP-13569](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13569)

**Comment by ndegendogo** [comment]
Related questions, although not in the focus of this ticket:

1) the current "test verordnung" covers a RAT at a test center (where I contribute 3 EUR on my own) when I have a red cwa warning.
Question: does it cover also these recommended multiple / several tests, or do I get one (the first) for three EUR, and do the following as self-tests?

2) the current "test verordnung" covers a PCR for free after a positive RAT. 
Question: Do I get this free PCR also after a positive self-test?

**Comment by ndegendogo** [comment]
Note: my above questions show that the current test verordnung is very ambiguous.
Please be aware that it is very hard (if not impossible) to give clear, specific advice based on such an ambiguous Verordnung ...

**Comment by Ein-Tim** [comment]
@ndegendogo 

The answer to your second question can be found here: https://www.bundesgesundheitsministerium.de/coronavirus/nationale-teststrategie/faq-covid-19-tests.html

![image](https://user-images.githubusercontent.com/67682506/177972775-22e69ed1-562b-4faa-ad93-e203208196da.jpeg)

**Comment by MikeMcC399** [comment]
See also [Besteht ein Anspruch auf einen PCR-Test, wenn die Corona-Warn-App eine Warnmeldung anzeigt?](https://www.bundesgesundheitsministerium.de/coronavirus/nationale-teststrategie/faq-covid-19-tests.html#c23926).

**Comment by MikeMcC399** [comment]
Still no feedback about how long to continue testing after a red tile?

**Comment by dsarkar** [comment]
@MikeMcC399 I will try to get an answer, thanks.
