### ISSUE TITLE
App might send 3 push notifications when a certificate is deleted

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#910]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 6s / Huawei P Smart 2019
- iOS/Android version: 15.5 / 10
- App version: 2.24.1 / 2.24.2

## Describe the bug

When I deleted the "3/3" certificate from my app, the app sends the following notifications: 

| Android | iOS |
|---|---|
| <img src="https://user-images.githubusercontent.com/67682506/178812651-1117da94-ab4a-4ecf-bd2d-60b00e2e0c85.jpg" width="300"> | <img src="https://user-images.githubusercontent.com/67682506/178812690-11db8d81-c60e-4d2a-bb52-de94b72a9388.jpeg" width="300"> |

## Steps to reproduce the issue

1. Open the CWA
2. Have a "2/2", which expires soon & a "3/3" certificate in the app
3. Delete the "3/3" certificate from the app
4. Note that the app sends 3 push notifications

## Expected behaviour

I would not expect the app to send me 3 push notifications for an action I did. While the app is totally right to display the red news dot on the "Certificates" tab & also to show that "There is news about your certificates", I don't think it is intended that the app sends push notifications for something that happens in foreground?

## Possible Fix

Change the logic. 

---
Internal Tracking ID: [EXPOSUREAPP-13625](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13625)

**Comment by dsarkar** [comment]
Good morning @Ein-Tim ! Thanks for reporting. I guess this bug is reproducible, correct?

**Comment by Ein-Tim** [comment]
@dsarkar 

Yep. I can also provide a video via mail if wished.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

The notifications are drawing attention to a change of status that is not visible until the user revisits the certificate detail page. After deleting the 3/3 certificate on Android, the app shows

(3) There is news about your certificates.

- Proof of Status has changed (to 2G). It was previously 2G+.
- Renew Certificates appears
- Note on Booster Vaccination

This is the way that the background checks on certificates work. If you scan in a 2/2 vaccination certificate which is about to expire, then you will get 2 notifications. If you then scan in a 3/3 vaccination certificate, you will get one more notification.

After scanning in the certificates, then deleting the 3/3 certificate you get another 3 notifications.

I can imagine an enhancement request to consolidate the notifications, so you only get a maximum of one notification for one user action. In other words, when you scan in the soon-to-expire 2/2 vaccination certificate you would only get one notification, and when you delete the 3/3 certificate you would only get one notification.

I guess it would be a major design change though to suppress the notifications if they are based on a user action.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thanks for the detailed description why this happens. I know that this is how it was implemented, and is thus correct, but as you can read in the OP I would not expect an app to inform me about an action I did myself thorough 3 (!) push notifications, which, if tapped on, all prompt me to the same screen.

I like your idea to consolidate the notifications, so that only 1 notification is send.
However, I still think the app should not send a push notification at all. As I deleted the certificate in the app, it is totally OK that the app shows that there is now 3 news reg. my certificates, etc., but sending a push notification is too much IMO.

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this bug to be fixed anymore. I'm therefore closing this issue.
