### ISSUE TITLE
2nd booster for 60+ from STIKO 21st recommendation

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#914]
STIKO announced their recommendation for people aged 60 and older to get a second booster vaccination. Previously the recommendation was for 70+. See [Pressemitteilung der STIKO zur 21. Aktualisierung der COVID-19-Impfempfehlung](https://www.rki.de/DE/Content/Kommissionen/STIKO/Empfehlungen/PM_2022-08-18.html) from Aug 18, 2022.

"Zu 1. "Indikationserweiterung für eine weitere COVID-19-Auffrischimpfung"
Personen ab dem Alter von 60 Jahren sowie Personen im Alter ab 5 Jahren mit einer Grunderkrankung gemäß bestehender STIKO-Empfehlung sollen eine weitere Auffrischimpfung erhalten, wenn sie bislang drei immunologische Ereignisse hatten, z.B. Grundimmunisierung plus 1. Auffrischimpfung oder Grundimmunisierung plus SARS-CoV-2-Infektion. Als immunologisches Ereignis wird eine COVID-19-Impfung bzw. eine SARS-CoV-2-Infektion gezählt, sofern entsprechende Abstände der geltenden STIKO-Empfehlung eingehalten werden".

In the past the booster rules used by CWA have not been updated to follow the STIKO recommendations (see for instance https://github.com/corona-warn-app/cwa-documentation/issues/814). It would still be beneficial if the rules were adapted and made to be up to date.

**Comment by thomasaugsten** [comment]
This is not directly CWA related because the CWA cannot influence the topic. But @BrittaTSI is already working on this to publish an according BNR as soon as possible.

**Comment by MikeMcC399** [comment]
It is quite untransparent how much of the STIKO recommendations are implemented in the rules used by CWA and what version of the STIKO updates are used by CWA.

Looking at the community website https://timokoenig.github.io/eu-dcc-rules/?ruleset=de-bn-rules from @timokoenig I can't see the recommendation for 2nd booster vaccination of 70+ which was included in the [20th update of the STIKO recommendations](https://www.rki.de/DE/Content/Infekt/EpidBull/Archiv/2022/Ausgaben/21_22.pdf?__blob=publicationFile) from May 25, 2022.

**Comment by thomasaugsten** [comment]
The CWA is using the BNR from 
https://distribution.dcc-rules.de/bnrules/
Better readable on 
https://timokoenig.github.io/eu-dcc-rules/?ruleset=de-bn-rules&country=DE

The CWA has no influence on which BNR are requested by the contracting entity.

**Comment by BrittaTSI** [comment]
Hi @MikeMcC399, thank you for reaching out!

It is always the decision of the BMG if a STIKO recommendation is to be turned into a Booster Notification Rule for CWA and CovPass and if so, when it should become active. As you have probably seen in the news lately, there have been a lot of discussions at BMG and RKI about which recommendations to issue, especially about the age of the people that should get the second booster. 

Based on yesterday's STIKO decision we are working on a new Booster Notification Rule (BNR-DE-0400) for a 2nd booster for 60+ that will go live in the next couple of days. The part about the "Grunderkrankung" you have cited above will not be covered, however, as it is not technically possible for the apps to single out these persons.

**Comment by MikeMcC399** [comment]
@BrittaTSI 

Thank you for the good news about the new BNR-DE-0400! I understand that the app can only base the information on certificates stored on the device, so I completely understand about not being able to include other illnesses.

**Comment by MikeMcC399** [comment]
@BrittaTSI / @thomasaugsten 

> The CWA has no influence on which BNR are requested by the contracting entity.

> It is always the decision of the BMG if a STIKO recommendation is to be turned into a Booster Notification Rule for CWA and CovPass and if so, when it should become active.

Since the BNRs are shared by CWA and CovPass, is there a better place than this CWA repository to raise issues / questions on the Booster Notification Rules?

**Comment by Ein-Tim** [comment]
- FYI PR https://github.com/corona-warn-app/dcc-rule-translation/pull/7

**Comment by BrittaTSI** [comment]
@MikeMcC399 - there is no shared repository that I am aware of.
The BNRs are requested by BMG and implemented by T-Systems' CWA team with contributions of IBM. By request of BMG the repositories we use for this process are kept private.

**Comment by MikeMcC399** [comment]
DE-BNR-400 is implemented and live since Sep 1, 2022.

The rule can be read independently of the app via https://timokoenig.github.io/eu-dcc-rules/?ruleset=de-bn-rules&country=DE&rule=BNR-DE-0400

This issue is therefore resolved.
