### ISSUE TITLE
App includes note that health authority will ask for list of contacts

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#916]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone XR / Huawei P Smart 2019
- iOS/Android version: 16.0 / 10 
- App version: 2.25

## Describe the bug

The CWA still includes the following text after submitting a positive test result:

"You will be asked by your public health authority to create a list of people you have had contact with. This should include all people with whom you have had close contact with (less than 2 meters, face-to-face conversation) for over 10 minutes in the two days before you became ill. You can use your contact journal for this: simply export the entries and then print them out or send them via e-mail."

As health authorities stopped tracing contacts quite some time ago, they don't ask for any contact lists anymore. The statement in the CWA is very out of date. 

## Steps to reproduce the issue

1. Warn others via the app
2. Read the texts

I can't currently provide exact steps, but will add them as soon as possible. 

## Expected behaviour

The text should be removed or replaced by a note which recommends to the user to contact their contact persons themselves. 

## Possible Fix

Remove or replace the text.

## Additional information

Link to the text in the iOS repo: 

English 1: https://github.com/corona-warn-app/cwa-app-ios/blob/4cbf7579f2dd3e04adf03cc7ab16359b31d0f73f/src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings#L673

English 2: https://github.com/corona-warn-app/cwa-app-ios/blob/4cbf7579f2dd3e04adf03cc7ab16359b31d0f73f/src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings#L1760

German 1: https://github.com/corona-warn-app/cwa-app-ios/blob/4cbf7579f2dd3e04adf03cc7ab16359b31d0f73f/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L688

German 2: https://github.com/corona-warn-app/cwa-app-ios/blob/4cbf7579f2dd3e04adf03cc7ab16359b31d0f73f/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L1810

---
Internal Tracking ID: [EXPOSUREAPP-14134](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14134) Android
Internal Tracking ID: [EXPOSUREAPP-14168](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14168) iOS

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Good point!

https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Kontaktperson/Management.html shows:

![image](https://user-images.githubusercontent.com/66998419/188321753-2c91c4f3-2b64-4de1-9dec-19d78316cc83.png)

Kontaktpersonen-Nachverfolgung (KP-N) bei SARS-CoV-2-Infektionen, Stand 14.1.2022, außer Kraft seit 2.5.2022
Bitte beachten: Die Empfehlungen des RKI zur Kontaktpersonen-Nachverfolgung bei SARS-CoV-2-Infektionen sind ab dem 2.5.2022 nicht mehr gültig. Die derzeit geltenden Empfehlungen des Bundes zu Isolations- und Quarantäneregelungen sind abrufbar unter [www.rki.de/covid-19-absonderung](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Quarantaene/Absonderung.html?nn=13490888).

**Comment by Ein-Tim** [comment]
Will someone asses this issue? @sapcoder123 / @GisoSchroederSAP

**Comment by GisoSchroederSAP** [comment]
We will verify the conclusion above with certain health authorities to get clearance for removal the respective text blocks in the CWA.
Thanks for pointing out.

**Comment by Ein-Tim** [comment]
@GisoSchroederSAP 

Did you already hear back from the health authorities?

**Comment by GisoSchroederSAP** [comment]
Yes, I did, sorry for delay of this update: 
The statement above "_You will be asked by your public health authority to create a list of people you have had contact with._" is still valid, but could be updated to "_You might be asked by your public health authority to create a list of people you have had contact with._"
The answer is very clear: There is still contact tracing happening, up to the limit of the authoritie's capacity. You cannot enforce or rely on this interrogation for each and every location, but: Better be prepared.

So, I suggest, we rather update the section than removing it completely. What do you think?

**Comment by Ein-Tim** [comment]
@GisoSchroederSAP 

> So, I suggest, we rather update the section than removing it completely. What do you think?

Sounds good. Although I'm a bit surprised by this answer, as @MikeMcC399 pointed out [above](https://github.com/corona-warn-app/cwa-documentation/issues/916#issuecomment-1236366896) that the even RKI doesn't have any suggestions for manual contact tracing anymore...

**Comment by dsarkar** [comment]
@Ein-Tim FYI https://github.com/corona-warn-app/cwa-app-android/pull/5655

**Comment by dsarkar** [comment]
@Ein-Tim FYI https://github.com/corona-warn-app/cwa-app-ios/pull/4860

**Comment by Ein-Tim** [comment]
@GisoSchroederSAP 

Hey Giso, sorry to bother you again! I really suggest that the text is removed, as first federal states are starting to end obligatory isolation after a positive test. I don't really think that, with this in mind, health authorities will still collect lists for manual contact tracing. 

So again, you may want to ask some health authorities about this, or just decide to remove the text.
If you want to do the latter, let me know, and I can provide a PR for iOS.

---

@dsarkar (I'm not sure if you're still actively involved in this project or if you're just on vacation) / @brianebeling 
Please re-name the 2.29 label to 3.0. Thanks!

**Comment by brianebeling** [comment]
Whoops, changing the labels didn't go as planned.
---
@Ein-Tim @dsarkar will most likely be back in a few weeks. If you have any specific questions or topics I can forward them to him.

**Comment by Ein-Tim** [comment]
Re-Ping @GisoSchroederSAP

**Comment by Ein-Tim** [comment]
Hey @GisoSchroederSAP, please take a look at https://github.com/corona-warn-app/cwa-documentation/issues/916#issuecomment-1334183047! Thank you!

**Comment by Ein-Tim** [comment]
@MikeMcC399 

> The text at the moment leaves it open about what a local public health authority might request. I think that is good enough at the moment. It is not incorrect to say that it is a possibility that you will be asked to provide a list, even if it is unlikely.

Maybe it would make sense to rather open an issue asking to re-formulate all the texts taking into account the new situation? But to be honest, the only change I'd recommend is simply dropping bullet point 2 & 3. They are not wrong, that's right. But it doesn't make sense to inform all positive tested people in the CWA about the possibility that the health authority may ask for a contact list, if they only do so in very special cases or in some states in no cases at all.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Thanks for your link to the [CWA 3.0 announcement by BMG on Twitter](https://twitter.com/BMG_Bund/status/1601146184537583617) via Slack.

We now know that CWA 3.0 is targeted for release on Jan 18, 2023, so there will not be any text changes published in the app for at least 5 weeks.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

That's right. Maybe it would make sense to monitor the situation for e.g. 2 more weeks and see if other federal states drop the isolation requirement and then re-asses this issue?

**Comment by Ein-Tim** [comment]
This has been sufficiently fixed and I'm closing this issue now.
