### ISSUE TITLE
iOS TestFlight?

### ISSUE THREAD

**Issue by capsload2** [corona-warn-app/cwa-documentation#92]
## Your Question

* Documentation File:
* Line / Paragraph:
* Question: is there a iOS Testflight Build available yet?

**Comment by raethlein** [comment]
Hey @capsload2, thanks for the question. As of now, Testflight builds will only be available for the project team and the RKI.

Corona Warn-App Open Source Team

**Comment by capsload2** [comment]
Would be really great now that 13.5 is published to open up the doors to some more users.

**Comment by tkowark** [comment]
Thanks for all your questions regarding TestFlight Builds. We'll let you know as soon as there are any changes to the answer the @raethlein already provided.
