### ISSUE TITLE
App can't consider cases where no certificate of recovery can be issued because of the 180 days limit

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#920]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [ ] Bug is not already reported in another issue - It was, see https://github.com/corona-warn-app/cwa-app-ccl/issues/45

## Technical details

- Device name: not relevant
- iOS/Android version: not relevant
- App version: not relevant

## Describe the bug

CWA currently can't consider cases in which a certificate of recovery can't be issued because the positive test was taken more than 180 days ago. 

## Steps to reproduce the issue

1. Get tested positive
2. Wait 180 days
3. Attempt to obtain a certificate of recovery

## Expected behaviour

CWA (and CovPass) should be able to consider these cases. 

## Possible Fix

Remove the 180 days limit.

## Additional context

This issue is a follow up to https://github.com/corona-warn-app/cwa-app-ccl/issues/45.

---
Internal Tracking ID: [EXPOSUREAPP-14023](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14023)

**Comment by MikeMcC399** [comment]
I believe this could only be resolved by a change to the IfSG law.

**Comment by thomasaugsten** [comment]
It is still in discussion how to handle this limit

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Did something evolve here?

**Comment by thomasaugsten** [comment]
Yes we expecting soon a decision on this topic

**Comment by Ein-Tim** [comment]
@thomasaugsten It would be quite interesting to know what decision was made? Maybe you can still share it with us here. Regardless, I'm closing this issue now, as DCCs are hardly relevant anymore & the CWA project went into ramp-down mode.
