### ISSUE TITLE
Questions on definition on in-app statistic terms

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#922]
## Your Question
The app includes the following statistics reg. vaccination:
- "People Who Have Received at Least One Vaccine Dose"
- "People Who Have Basic Immunization"
- "People Who Have Received a Booster Vaccination"

How is "Basic Immunization" & "Booster Vaccination" defined here?

"Basic Immunization" = 2 vaccinations?
"Booster Vaccination" = at least 3 vaccinations?

I'm asking because these terms were not changed, although the IFSG now requires 3 vaccinations to be "Fully vaccinated", however, I think that the terms used for the in-app statistics are used according to definition of the RKI.

Please clarify this here on GItHub, but also consider adding that to the information text in the app.

ping @mlenkeit & @GisoSchroederSAP

**Comment by MikeMcC399** [comment]
@Ein-Tim 

If you look at the German app display you will find the terms defined by STIKO, for instance in the latest document https://www.rki.de/DE/Content/Infekt/EpidBull/Archiv/2022/Ausgaben/40_22.pdf?__blob=publicationFile

which are the medical definitions, not the legal definitions.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thank you! However, it isn't that clear in English, or am I mistaken?

**Comment by MikeMcC399** [comment]
@Ein-Tim 

>  it isn't that clear in English, or am I mistaken?

It's clear to me in German what the term "Grundimmunisiert" in the app means and in turn I take it that "Basic Immunization" is a translation of "Grundimmunisiert" so I understand that as well.

You are however entitled to ask for an official definition (not just an opinion from my side) and if there is confusion about what the terms mean, then the FAQ articles: 

- https://www.coronawarn.app/en/faq/results/#further_details and
- https://www.coronawarn.app/de/faq/results/#further_details

could be expanded to explain officially and more exactly.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Your answer definitely helps to understand, thank you!

I still think that should be made clearer in the app itself, either by explaining the terms or referring to STIKO.

I'll wait for an official response here. (:

**Comment by MikeMcC399** [comment]
@Ein-Tim 

You can find more explanation and the same figures on the BMG website https://impfdashboard.de/ (English version on https://impfdashboard.de/en/).

**Comment by GisoSchroederSAP** [comment]
I think, it's a valid idea to publish at least in our glossary the agreed official definition. Maybe even in the app (or a link to the glossary).
By the way: The "Fachwörterbuch Infektionsschutz" gives another translation: 
![image](https://user-images.githubusercontent.com/69585203/197364393-42bf340c-2a83-46f9-970b-de1224383ff6.png)

**Comment by GisoSchroederSAP** [comment]
As far as I understand the current concept, there is a clear distinction between _primary immunization_ (basic immunization) and "fully vaccinated". While the primary immunization term is associated with the (medical) vaccination scheme, the "fully vaccinated" ruling is a definition of the legal authorities.

**Comment by MikeMcC399** [comment]
https://impfdashboard.de/ also leads to the definition on 
https://github.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland#erkl%C3%A4rung-zum-merkmal-impfstatus

"Erklärung zum Merkmal Impfstatus

Die Gesamtzahl mindestens einmal Geimpfter (min1) umfasst alle Meldungen, für die in den Daten des DIM die Impfserie 1 angegeben ist. Als Impfserie 1 gelten Erstimpfungen mit den in Deutschland zugelassenen und verfügbaren Impfstoffen. Nicht enthalten sind Impfungen von Personen, die erstmalig in Deutschland geimpft wurden, zuvor aber von einer SARS-CoV-2 Infektion genesen sind oder bereits eine Impfung im Ausland erhalten hatten. Diese gelten direkt als grundimmunisiert.
Darüber hinaus gelten alle Personen als grundimmunisiert (gi), für die in den Daten des DIM die Impfserie 2 angegeben ist. Darunter zählen Zweitimpfungen in Deutschland und Impfungen nach Genesung.
Als Personen mit erster bzw. zweiter Auffrischimpfung (boost1, boost2) gelten Personen, die eine oder zwei weitere Impfungen nach abgeschlossener Grundimmunisierung erhalten haben. Diese werden mit Impfserie 3 bzw. 4 gemeldet. Auch für die Auffrischungsimpfungen gilt, dass diesen eine Impfung im Ausland vorrangegangen sein kann und in den Daten somit keine vorhergehende Impfserie 1 und Impfserie 2 gemeldet wurde.

Ziel des Impfquotenmonitorings ist es, eine Aussage zum Impfschutzniveau auf Bevölkerungsebene zu treffen. Die Datenerhebung folgt dieser Perspektive. Da vom DIM keine Daten zum Genesungsstatus oder bestehenden Impfungen im Ausland erhoben werden, ist in der Datenauswertung keine Aussage oder Berücksichtigung diesbezüglich möglich."

---

The legal status "Fully vaccinated" is not used on the statistics tiles, so it does not need to be explained in the context of the statistics.

**Comment by Ein-Tim** [comment]
Thanks to both of you, @MikeMcC399 & @GisoSchroederSAP.

I guess it would be good, if we can agree that the statistic tiles use the terms defined by STIKO/RKI, to add explanations reg. this to
a) the app itself (most desirable option for the user as the information can be accessed without leaving the app)
b) to the blog https://www.coronawarn.app/en/blog/2021-08-05-statistictiles/ (middle way - the information wouldn't be directly available in the app but the blog post is linked to at the bottom of the statistics information screen)
c) to the CWA website Glossary (IMO the worst way, as the user would have to access the FAQ page & search for the terms themselves)

What option do you prefer? 

Should we continue this discussion in a wishlist issue, as the question I asked in the OP was answered?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> 
> (suggest) ... to add explanations reg. this to 
>a) the app itself (most desirable option for the user as the information can be accessed without leaving the app) 

Agreed, however this would take several weeks to implement.

> b) to the blog https://www.coronawarn.app/en/blog/2021-08-05-statistictiles/ (middle way - the information wouldn't be directly available in the app but the blog post is linked to at the bottom of the statistics information screen) 

It was already stated in https://github.com/corona-warn-app/cwa-website/issues/2102#issuecomment-1180033793 that blog articles should not be changed. This is a topic on its own to move the blog information somewhere else and update it.

> c) to the CWA website Glossary (IMO the worst way, as the user would have to access the FAQ page & search for the terms themselves)

This would probably be helpful to have a source of reference regarding the term definitions.

> What option do you prefer?

I suggest another option:

- Add "The [COVID-19 vaccination dashboard](https://impfdashboard.de/en/) provides further detailed information about vaccination statistics" to the section on https://www.coronawarn.app/en/faq/results/#further_details which lists vaccinations.

![image](https://user-images.githubusercontent.com/66998419/197385202-44b5f9df-39e4-4893-8889-9724d84e71f7.png)

- Add "Unter dem [COVID-19 Impfdashboard](https://impfdashboard.de/) finden Sie weitere Details zu den Impfstatistiken" to https://www.coronawarn.app/de/faq/results/#further_details

If you think that is a good idea, you are welcome to open an issue / PR to make the change on the website.

**Comment by Ein-Tim** [comment]
@MikeMcC399 This seems like a good idea. The FAQ entry is directly linke to in the app.

I will do the following:
1. Close this issue
2. Open a wishlist issue requesting the details from https://impfdashboard.de/en/ to be added to the in-app statistics explanations
3. Open a website issue requesting to add the sentence "The [COVID-19 vaccination dashboard](https://impfdashboard.de/en/) provides further detailed information about vaccination statistics" to the FAQ entry https://www.coronawarn.app/en/faq/results/#further_details
4. Open a website issue requisition to add the following terms to the glossary
	1. People vaccinated at least once
	2. People who have basic immunization
	3. People who have received booster vaccinations
	and their corresponding German terms.
