### ISSUE TITLE
Communication channels' security between app and servers

### ISSUE THREAD

**Issue by tgianko** [corona-warn-app/cwa-documentation#93]
The current design does not yet describe the communication channels' security properties between the app and the servers.

Based on the current design, it seems that the messages (i) GUIDs registration, (ii) checking for results, (iii) Uploading diagnosis key, and (iv) TAN and token retrieval are sensitive data items that should be protected from passive/active attackers. Also, intermediary entities such as CDN nodes and in-path web caches should not be allowed to access the content of messages too.

This could be solved with TLS and client-side certificate pinning/DANE with a few tweaks. 

1.  Use pinning/DANE for the domain names of the backend server handling messages (i-iv)

2. When downloading diagnosis keys, the app can use system CAs to validate TLS certificates. However, if the backend service for the messages (i-iv) and the one for downloading keys use the same domain name, the CDNs supporting the distribution of diagnosis keys may be able to decrypt the TLS connections for messages (i-iv) too, defeating the purpose of pinning/DANE. A way to solve that is using different domain names and certificates for the download of keys and messages (i-iv).

**Comment by tklingbeil** [comment]
Of course, all communication channels will be properly secured.

In the [specification for the Server implementation](https://developer.apple.com/documentation/exposurenotification/setting_up_an_exposure_notification_server), the use of signing for the payload is also required, so of course this will be done (see **Sign Downloads with the Latest Registered Certificate**). 

There will be dedicated documentation artefacts for the *Technical Security Concept*
and *Data Privacy Concept* (as mentioned in the README.md).

**Comment by tkowark** [comment]
Thanks for brining up this important question, @tgianko . Would be great if you can review the upcoming documentation that tklingbeil mentioned and reopen this one or open another issue, in case there are still possible weaknesses in the security of communication channels.
