### ISSUE TITLE
my certificate does not validate for France

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-documentation#932]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 13 Pro
- iOS version: 15.4.1
- App version: 2.28.0(7) / CCL version 3.4.0

## Describe the bug
Today I got my 4th vaccination together with my certificate. The certificate states the product as "Comirnaty", and the manufacturer as "Biontech". See image.
But when I check its validity for France, the check fails with the error message:
"Only vaccines in the allowed
valueset that have been approved by
the French Authority (Pfizer,
Moderna, Astra Zeneca, Janssen,
Novavax, Covishield, R-covi, Covid
19 Vaccine and some clinical trials)."

## Steps to reproduce the issue

- get a vaccination certificate with data like "Comirnaty / Biontech" (but not Pfizer) 
- check validity of certificate for France
## Expected behaviour
certificate should be shown as valid.
The app (or the French policy rules ?) should know that pfizer is not different from Biontech vaccination.

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-14307](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14307)

**Comment by MikeMcC399** [comment]
The app checks are out of sync with the regulations.

https://reopen.europa.eu/en/map/FRA/7001 says:

![image](https://user-images.githubusercontent.com/66998419/201035829-617b807b-9344-4425-827e-0078fedb4d52.png)

**Comment by thomasaugsten** [comment]
France is using an external variable which is only available in the france app. We will inform France about the issue.

**Comment by MikeMcC399** [comment]
If France no longer has any rules to apply (see https://reopen.europa.eu/en/map/FRA/7001), then the French rules used in the app should be replaced by something like the Swiss rule:

https://timokoenig.github.io/eu-dcc-rules/?ruleset=eu-dcc-rules&country=CH&rule=GR-CH-0002

"EU/EFTA citizens and their family members, irrespective of their nationality, have rights of free movement. Entry to the country is currently possible without pandemic-related measures."

**Comment by thomasaugsten** [comment]
We also give this information to the French colleagues.

**Comment by thomasaugsten** [comment]
France is already investigating this and has still the possibility to this checks depending on the visited countries of the user.

**Comment by ndegendogo** [comment]
Wow - thanks for investigating and taking action! 👍👍

**Comment by ndegendogo** [comment]
Can you tell / find out if France plans to make these missing "external variables" available to cwa in future?

Alternatively I would suggest that cwa policy rule engine should check for such missing external variables, and in that case regard the rules as "incomplete" - check not possible (like is currently done if no rule is available for a country, like Portugal).

**Comment by MikeMcC399** [comment]
- Since this is a general problem for multiple EU countries, I have opened a new issue #933.

**Comment by larswmh** [comment]
Thanks for your feedback. We have some news regarding this issue.
Business Rules are provided by the issuing country and not something we can fix in the CWA. As soon as the country provides the missing business rules, they will also fix the behavior in the app.

**Comment by thomasaugsten** [comment]
Problem from France side should be fixed
