### ISSUE TITLE
"Check Validity for Travel" fails for many EU countries with lifted restrictions

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#933]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [ ] Bug is not already reported in another issue<br>reported for France in https://github.com/corona-warn-app/cwa-documentation/issues/932

## Technical details

- Device name: Samsung Galaxy A52 5G (SM-A526B/DS)
- iOS/Android version: Android 12
- App version: 2.28.3

## Describe the bug

According to https://reopen.europa.eu/en the following countries have lifted COVID-19 travel entry restrictions. "Check Validity for Travel" fails with a 1/2 certificate despite there being no restrictions for the countries marked as "fail" in the table below:

| Country     | Check result |
| ----------- | ------------ |
| Austria     | fail         |
| Croatia     | fail         |
| Cypress     | fail         |
| Czechia     | fail         |
| Estonia     | pass         |
| Finland     | fail         |
| France      | fail         |
| Germany     | pass         |
| Ireland     | fail         |
| Latvia      | fail         |
| Lithuania   | fail         |
| Luxembourg  | fail         |
| Malta       | fail         |
| Netherlands | fail         |
| Poland      | fail         |
| Romania     | pass         |
| Slovakia    | fail         |
| Slovenia    | fail         |
| Switzerland | pass         |

## Steps to reproduce the issue

1. Scan one 1/2 vaccination certificate and ensure that no other certificates are stored.
2. Tap "Certificates"
3. Tap right-arrow
4. Scroll down to "Check Validity for Travel"
5. Select the country to check and tap "Check"

### Example for France

![image](https://user-images.githubusercontent.com/66998419/201081063-b29a15b0-fbfb-4c34-b998-d136828a314c.png)

If there are no rules for entry, then no certificate should cause a failure message.

https://reopen.europa.eu/en/map/FRA/7001
![image](https://user-images.githubusercontent.com/66998419/201079086-e331d76f-08ff-40ea-a729-5d81f6e716b5.png)

## Expected behavior

The results of "Check Validity for Travel" should agree with the details from https://reopen.europa.eu/en. The following countries should show the message "Your certificate is valid for entry into the selected country" independently of any actual certificate stored, since COVID-19 travel entry restrictions have been lifted. The result should not show the message "Your certificate is not valid for entry into the selected country" since the certificate is irrelevant if there are no restrictions in place.

| Country     | Check result |
| ----------- | ------------ |
| Austria     | fail         |
| Croatia     | fail         |
| Cypress     | fail         |
| Czechia     | fail         |
| Finland     | fail         |
| France      | fail         |
| Ireland     | fail         |
| Latvia      | fail         |
| Lithuania   | fail         |
| Luxembourg  | fail         |
| Malta       | fail         |
| Netherlands | fail         |
| Poland      | fail         |
| Slovakia    | fail         |
| Slovenia    | fail         |

## Possible Fix

Country rules should be updated in alignment to the information on https://reopen.europa.eu/en.

## Additional context

See https://timokoenig.github.io/eu-dcc-rules/?ruleset=eu-dcc-rules for convenient display of rules.

---
Internal Tracking ID: [EXPOSUREAPP-14312](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14312)

**Comment by MikeMcC399** [comment]
A secondary point, which would need to be a new enhancement request issue, is that the app does not allow to check entry rules if there are no certificates stored. It makes the assumption that certificates are always necessary to enter a country. This is no longer generally true for EU countries.

A workaround for EU countries is to look up the country travel rules on the https://reopen.europa.eu/en website with a browser. 

For other countries, https://www.auswaertiges-amt.de/de/ReiseUndSicherheit/reise-und-sicherheitshinweise is a useful starting point to discover current COVID regulations.

**Comment by Ein-Tim** [comment]
Thanks for this issue Mike, I also wanted to open it!

**Comment by larswmh** [comment]
Thanks for your report @MikeMcC399. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-14312](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14312)

---
Corona-Warn-App Open Source Team

**Comment by brianebeling** [comment]
Thanks for your feedback. We have some news regarding this issue.
Business Rules are provided by the issuing country and not something we can fix in the CWA. As soon as the country provides the missing business rules, they will also fix the behavior in the app.

**Comment by MikeMcC399** [comment]
@brianebeling 

Is there an EU instance which coordinates the maintenance of the Business Rules? Has the CWA Open Source Team alerted the organisation(s) responsible that there is an issue?

**Comment by thomasaugsten** [comment]
We forwarded this to IBM and they will discuss this in the EU

**Comment by MikeMcC399** [comment]
@thomasaugsten 

Thank you for passing on the issue to IBM. The issue is also reproducible on CovPass.

Since the issue is not unique to CWA I will close the issue here.
