### ISSUE TITLE
Maintenance Costs 

### ISSUE THREAD

**Issue by danielehrhardt** [corona-warn-app/cwa-documentation#936]
ok, I would like to start a discussion here because I have the feeling that far too little attention is paid to the topic.  

I often read that the maintenance costs and also the development of the Corona Warn App seem to be extremely expensive.  

I wonder if there is a controlling that checks such expenditure for correctness and also for plausibility. 

The app will probably operate in the OTC this is also significantly more expensive than competitors but the costs that are called here are absolutely disproportionate.

I would like someone from the internal team to make it their task to shed light on this topic and be more transparent.  

Several hundred million euros of tax money are wasted here.  It also looks like the German government has no idea about it and it's still new territory.  since the government is obviously being ripped off here, something must be done about it.  I ask for your help to pay more attention to the topic in order to create more transparency.  it really can't go on like this.

**Comment by brianebeling** [comment]
Thank you for your interest in the project management of the Corona-Warn-App. While we think cost is an important factor in this project, we are not qualified to make political or financial statements via GitHub. This is primarily a place to voice concerns regarding software-development and work together on the open-source parts of the project, like the website or Android and iOS app.

This is a complex project with many participants and in this case we do not have the means to provide you with a satisfying answer. The best place for you to inquiry more detailed information is the [Bundesministerium für Gesundheit](https://www.bundesgesundheitsministerium.de/), like Mike explained in more detail already.

We are always open for suggestions regarding the repositories visible in this GitHub Project. Please keep in mind that GitHub is not a political - but a technical - platform and we are not the controlling instance.

**Comment by GisoSchroederSAP** [comment]
> > @danielehrhardt Maybe you could elaborate what you want this thread to be? A place for discussion where interested community members can make suggestions on how maintenance coasts can be reduced?
> > Or do you only want to get answers from the team on why the coasts are that high?
> 
> Both!
> 
> TBH i have spoken to a few colleagues and in no world under any circumstances can such a cost be justified.
> 
> We need to Stop what is happening here.

@danielehrhardt, first of all: Thanks for opening the discussion about a topic that is neither new nor does it touch the right audience. 
Let me briefly explain. 
As already mentioned above, the community here more or less in GitHub discusses doucments, source coding, functional descriptions and other representations related to the product. From the Open Source perspective you mal also address personal interests in project management, financing/cost, ethics and politics here, but I am afraid, this will not result in the expected answers.
On the other hand, I'd like to point out, that your phrase "_Several hundred million euros of tax money are wasted here._ " is just a statenment, that is not yet proven, right? Personally, you may _feel_ that the money was wasted, but: Can you prove it?
Did you make a calculation about effectiveness of the solution? (BTW, did you read the [Science Blog](https://www.coronawarn.app/de/science/) articles about the functions and results of the Corona Warn App?

An educated judgment would have to compare how much it would have cost to provide the same performance and results with different resources than the CWA - only then you can decide whether money was wasted or perhaps even saved, right?

Think about the engagement of Bundeswehr soldiers in the health authorities. Even with this strong staffing support, the municipal and federal structures were unable to scale and handle the volume of infections in a timely manner to break infections chains or just to warn risk contacts - in contrast to the app.

We totally agree, that the discussion about cost, investment of money is important, as the government has an important role and an interest in a strong health system. But as mentioned above, the discussion should be _fair_ in the sense of judgment. Whenever possible, you should consider _all_ aspects and not only the _amount_ of the costs. Besides that, you need to break down the whole investment: software development, operating, hotline/support, maintenance, communication and marketing, community handling - they all need to be paid somehow, right? Which one of these activities do you think is wasted?

On the other hand, you are probably well aware of the EU initiatives with respect to the _preparedness_ that are in place since months. Also, the DARP [Deutscher Aufbau- und Resilienzplan](https://www.bundesfinanzministerium.de/Content/DE/Standardartikel/Themen/Europa/DARP/deutscher-aufbau-und-resilienzplan.html) published

**Comment by danielehrhardt** [comment]
> > > @danielehrhardt Maybe you could elaborate what you want this thread to be? A place for discussion where interested community members can make suggestions on how maintenance coasts can be reduced?
> > > Or do you only want to get answers from the team on why the coasts are that high?
> > 
> > Both!
> > 
> > TBH i have spoken to a few colleagues and in no world under any circumstances can such a cost be justified.
> > 
> > We need to Stop what is happening here.
> 
> @danielehrhardt, first of all: Thanks for opening the discussion about a topic that is neither new nor does it touch the right audience. 
> Let me briefly explain. 
> As already mentioned above, the community here more or less in GitHub discusses documents, source coding, functional descriptions and other representations related to the product. From the Open Source perspective you mal also address personal interests in project management, financing/cost, ethics and politics here, but I am afraid, this will not result in the expected answers.
> On the other hand, I'd like to point out, that your phrase "_Several hundred million euros of tax money are wasted here._ " is just a statenment, that is not yet proven, right? Personally, you may _feel_ that the money was wasted, but: Can you prove it?
> Did you make a calculation about effectiveness of the solution? (BTW, did you read the [Science Blog](https://www.coronawarn.app/de/science/) articles about the functions and results of the Corona Warn App?)
> 
> An educated judgment would have to compare how much it would have cost to provide the same performance and results with different resources than the CWA - only then you can decide whether money was wasted or perhaps even saved, right?
> 
> Think about the engagement of Bundeswehr soldiers in the health authorities. Even with this strong staffing support, the municipal and federal structures were unable to scale and handle the volume of infections in a timely manner to break infections chains or just to warn risk contacts - in contrast to the app.
> 
> We totally agree, that the discussion about cost, investment of money is important, as the government has an important role and an interest in a strong health system. But as mentioned above, the discussion should be _fair_ in the sense of judgment. Whenever possible, you should consider _all_ aspects and not only the _amount_ of the costs. Besides that, you need to break down the whole investment: software architecture, development, operating, data privacy and security, hotline/ user support, maintenance, communication and marketing, community handling on GitHub and the app stores - they all need to be paid somehow, right (even this discussion here)? Which one of these activities do you think is wasted?
> 
> On the other hand, you are probably well aware of the [EU initiatives](https://ec.europa.eu/commission/presscorner/detail/en/speech_22_2709) with respect to the _preparedness_ that are in place since months. Also, the DARP [Deutscher Aufbau- und Resilienzplan](https://www.bundesfinanzministerium.de/Content/DE/Standardartikel/Themen/Europa/DARP/deutscher-aufbau-und-resilienzplan.html) published by the Bundesministerium für Finanzen points to the importance of investments in that area. You might disagree here. Do you think, it's wrong to be prepared for the future?
> 
> @danielehrhardt, I'd like you to re-think and clearly name your intention: Do you expect a detailed transparency about the cost break-down, please address those questions to the government based on the IFG (Informationsfreinheitsgesetz) once you consumed the recently released [Drucksache 20/4631](https://dserver.bundestag.de/btd/20/046/2004631.pdf). Here on GitHub you will not find anybody that _can_ answer your questions in depth. 
> However, if you want to start a public discussion about the overall sense or non-sense of a digital tool like the CWA, I certainly will challenge "your few colleagues" with the remark: "_TBH i have spoken to a few colleagues and in no world under any circumstances can such a cost be justified._" and will ask them to prove/to back up this statement with reliable facts and figures. 
> Still, I have serious doubts, **this** discussion will be succeed here. 
> 
> Overall, thanks for your voice, @danielehrhardt. As already mentioned by @brianebeling, this topic is complex and has many levels, many stakeholders and many experts involved. Obviously, new _specific suggestions_ to for cost reduction are always welcome! Any questions beyond the technical implementation and Open Source principles I kindly ask you to address to the proper channel.
> 
> Thank you.
> 
> 
> 

I personally believe that the Corona Apps made sense and it was good that they existed or still exist.  I also didn't want to badmouth the work of you or your team or all the people involved.  I am concerned that extremely large amounts of money are being used here without considering other offers or making a tender.  I don't have to prove anything here either, because 220 million euros are so extremely high that there is definitely another way.  I know software development costs money and marketing and support costs money too.  nevertheless I think that the money is handled much too easily here, probably this is a general problem which I can't confirm, of course. 

I come from software development and everything that goes with it.  and therefore I can not understand how such costs should be justified.  since more and more money is being spent here and I didn't know who to turn to effectively, I came up with the idea of ​​doing this in GitHub, because I believe that many other software developers share the same opinion as me.  

But I'm already realizing that I'm not up to this topic and don't want to invest my time in it, I'll end this topic for myself and Germany should just keep doing it the way they do it.  

I am disappointed that 50 million can suddenly become 70 million.  money is being handled far too carelessly here, but I see now why wo fix this.

**Comment by GisoSchroederSAP** [comment]
So, agreed, we _all_ come from the software development. Still, there are some significant differences I want to address:

- This is a special situation where the context is internationally set. The Corona Warn App is integrated in European (if not even world-wide) activities. 
- You may have experience in software development, and many software developers as well - but may I ask: How many projects addressed multiple million of users internationally with a 24/7 service? How many of you software addressed government, authorities, economy, public services and millions of individuals at the same time?
(Sidefact: Even for me with 34 yeras of professional software development, this was the first time of a project with this impact and dimensions.)
- You still look for the full amount of money, but do not split the amount into the different areas - I did neither, so don't worry: But the question is still valid: Can you name exactly _where_ the money was wasted? Tha would at least allow to address the right  persons.
- Regarding the investigation whether or not "_the money is handled much too easily here_" you may think about the "Bundesrechnungshof", who may double-check the finances of government projects like this, right?

Finally, we all have the feeling this is a lot of money - and it is! Still, if you or somebody else claims this money is wasted, this only works out with facts and figures. We cannot or must not compare from our personal experience if the scope, if the context, if the dimensions are not comparable. That's all I'm saying.

Anyway, I hope, you'll get the answers you are looking for. But we cannot helpout here, I'm sorry. We do not have the insights in the contracts and in the financial details.

**Comment by danielehrhardt** [comment]
> So, agreed, we _all_ come from the software development. Still, there are some significant differences I want to address:
> 
> - This is a special situation where the context is internationally set. The Corona Warn App is integrated in European (if not even world-wide) activities. 
> - You may have experience in software development, and many software developers as well - but may I ask: How many projects addressed multiple million of users internationally with a 24/7 service? How many of you software addressed government, authorities, economy, public services and millions of individuals at the same time?
> (Sidefact: Even for me with 34 yeras of professional software development, this was the first time of a project with this impact and dimensions.)
> - You still look for the full amount of money, but do not split the amount into the different areas - I did neither, so don't worry: But the question is still valid: Can you name exactly _where_ the money was wasted? Tha would at least allow to address the right  persons.
> - Regarding the investigation whether or not "_the money is handled much too easily here_" you may think about the "Bundesrechnungshof", who may double-check the finances of government projects like this, right?
> 
> Finally, we all have the feeling this is a lot of money - and it is! Still, if you or somebody else claims this money is wasted, this only works out with facts and figures. We cannot or must not compare from our personal experience if the scope, if the context, if the dimensions are not comparable. That's all I'm saying.
> 
> Anyway, I hope, you'll get the answers you are looking for. But we cannot helpout here, I'm sorry. We do not have the insights in the contracts and in the financial details.

I honestly want to say thank you for the discussion.
