### ISSUE TITLE
Is there a "quarantine" period for uploaded DKs?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#937]
## Your Question
* Documentation File: https://github.com/corona-warn-app/cwa-server/blob/main/docs/DISTRIBUTION.md
* Line / Paragraph: https://github.com/corona-warn-app/cwa-server/blob/main/docs/DISTRIBUTION.md#available-profiles

The following table in the referenced document above includes a description of a profile `demo`:

### Available Profiles

Profile                       | Effect
------------------------------|-------------
`demo`                        | Includes incomplete days and hours into the distribution run, thus creating aggregates for the current day and the current hour (and including both in the respective indices). When running multiple distributions in one hour with this profile, the date aggregate for today and the hours aggregate for the current hour will be updated and overwritten. This profile also turns off the expiry policy (Keys must be expired for at least 2 hours before distribution) and the shifting policy (there must be at least 140 keys in a distribution).

It says: "Keys must be expired for at least 2 hours before distribution". Taking this into account, I have two questions:
1. Is this actually the live configuration of the server?
2. How does this actually work?
This is how I always thought it worked:

Device uploads DKs at 10:00 pm (all keys of the past 14 days are uploaded, the key from today will be uploaded as soon as the day is over) -> Server receives the keys -> Keys are put into "quarantine" for two hours before distribution (no download by client apps possible) -> 2 hours pass, the keys go out of "quarantine" and can be downloaded by client apps

But I think this is actually wrong and it should be like this:
Device uploads DKs at 10:00 pm (all keys of the past 14 days are uploaded, the key from today will be uploaded as soon as the day is over) -> Server receives the keys -> All keys can instantly be downloaded by client apps, as no keys were uploaded that aren't older than 2 hours

Can you confirm or correct this statement? Thank you!

**Comment by Ein-Tim** [comment]
@thomasaugsten / @mlenkeit Could you share an answer, please? (-:

**Comment by mlenkeit** [comment]
@Ein-Tim as the profile name suggests, this is a demo profile with settings that are not in production.

The way it works is rather something like this:
Device uploads DKs at 10:00 pm (all keys of the past 14 days are uploaded, ~~the key from today will be uploaded as soon as the day is over~~ _including the key from today_) -> Server receives the keys -> _the keys of the past 14 days are included in the next day/hour package -> 2 hours pass, the key from today is included in the next day/hour package.

I hope this helps to clarify the question!

Happy holidays, Max

**Comment by Ein-Tim** [comment]
@mlenkeit 

That answers the question very well! Thank you, Max, and have relaxing & happy holidays!
