### ISSUE TITLE
Transnational Exposure Logging states Germany (still) participates

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-documentation#947]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue
    See also https://github.com/corona-warn-app/cwa-website/issues/3416 and https://github.com/eu-federation-gateway-service/efgs-federation-gateway/issues/306

## Technical details

- Device name:  Samsung Galaxy A52 5G (SM-A526B/DS)
- Android version:  13
- App version: 3.1.1

## Describe the bug

Transnational Exposure Logging shows:

"The following countries currently participate in transnational exposure logging:
Germany"

According to https://www.coronawarn.app/en/faq/results/#interoperability_countries

'The "Interoperability Gateway" (European Federation Gateway Service; EFGS) was deactivated EU-wide in February 2023. There is no more exchange of warnings via the gateway and the Corona-Warn-App will therefore no longer report warning messages triggered in apps from other countries.'

This is inconsistent.

## Steps to reproduce the issue

1. With Exposure Logging Active, tap on this line on the "Status" page of the app
2. Tap on Transnational Exposure Logging
3. Note that it lists Germany (and only Germany)

## Expected behaviour

If the Gateway has been shut down, then the app should not state that Germany is still participating.

**Comment by MikeMcC399** [comment]
I don't know if this also affects CWA on iOS, however since it is a more general issue I added it here.

The FAQ information is now correct in any case, since issue https://github.com/corona-warn-app/cwa-website/issues/3416 is resolved.

**Comment by Ein-Tim** [comment]
I raised this issue internally and will come back to you tomorrow.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Does this issue also affect iOS?

**Comment by Ein-Tim** [comment]
@MikeMcC399 Yes

**Comment by Ein-Tim** [comment]
No decision on this one yet, please stand by!

**Comment by Ein-Tim** [comment]
Due to the upcoming end of the development of the CWA, it was decided that this will not be changed anymore. 
The corresponding screens anyway won't be shown anymore after a certain date in the near future (you can find out more details in the corresponding PRs in the app repositories).

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Thank you for relaying the decision. I understand this with my knowledge about the ramp-down plans that can be discovered by reading PRs for the unreleased next version.

Most users will however not have received this information, so https://www.coronawarn.app/en/faq/results/#end_of_development needs to have some dates added to it.

**Comment by Ein-Tim** [comment]
@MikeMcC399 We are already working on both updating the FAQs and showing a notice in the app, as you can probably tell from the PRs. Looking at https://github.com/corona-warn-app/cwa-app-ccl/pull/134, you can also find out the corresponding date :)
