### ISSUE TITLE
Why did the app show that only two people warned on Sunday (09.04.23)?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#949]
## Your Question
Yesterday, on Monday 10.04.2023, the CWA showed that there were only 2 people warning via the app on Sunday, 09.04.2023. Is that actually correct, because looking at the "Sharing behavior" graph on https://www.coronawarn.app/en/analysis/, I'd say this must be an error in the in-app statistics, right?

**Comment by mlenkeit** [comment]
@Ein-Tim you're right, something seems to be inconsistent with the source data of the cart.

While the Gesamt/Total chart shows only 2 people:
![image](https://user-images.githubusercontent.com/2060790/231119033-f37192eb-52a8-49b3-a77e-57253781f6a2.png)

... the chart for "Warnen ohne TAN" shows the correct number:
![image](https://user-images.githubusercontent.com/2060790/231119746-3254de1b-23d6-4962-8173-04ddcbf0c28d.png)

We'll take a look...

**Comment by Ein-Tim** [comment]
Okay, turns out: This was an issue in the data from that day, and it has been fixed now. Thanks @mlenkeit!

**Comment by Ein-Tim** [comment]
I'm re-opening this issue as it occurs again. The app shows that only 7 people warned yesterday - that's wrong.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I don't see any issue on https://www.coronawarn.app/en/analysis/. Could you post a screenshot and mark the error?

**Comment by Ein-Tim** [comment]
@MikeMcC399 The problem is not visible anymore. Yesterday evening, at around 22:30h, I looked at the in-app statistics section and the app displayed that only 7 people warned on Wednesday. 

I also informed the respective team about the issue, and we now know the cause for the confusion and will make sure that, in the future, the statistic is always up-to-date and includes all available data.
