### ISSUE TITLE
Bandwith Estimation and Spread of Traffic

### ISSUE THREAD

**Issue by TomTeeJay** [corona-warn-app/cwa-documentation#95]
There is a difference between 60 Mio of considered active users and 30 Mio clients in your technical documentation regarding bandwith estimation (https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#runtime-environment-hosting).

1. What's the difference between "active users" and "clients"?
2. Does the intended spread of the traffic imply any factors to the creation of Registration Tokens?

**Comment by tklingbeil** [comment]
1. Those are basically the same. One (60 million users) is a "best case" scenario (from a epidemiological perspective, i.e. as many users as possible), while the other (30 million users) is the number we continued to work with.

2. No. The interaction when retrieving test results etc. is not artificially spread. Those things just happen when they happen and we'll have to deal with the load. The spread only applies to the background download of diagnosis keys of others.

**Comment by TomTeeJay** [comment]
Thank you for your rapid answer. May I suggest to make this more clear in the documentation? As pessimist I also would work with the higher epidemiologists' estimation than with the lower one.

**Comment by egandro** [comment]
> while the other (30 million users) is the number we continued to work with.

Can you please put this number somewhere in the documentation as a very dominant factor - that you - currently estimate 30 mio active users?


Given this number - and the fact that we have a scanning interval of 5 minutes - and the chapter "Limitations" in the architecture document, we can make now a very educated guess on the estimated effectiveness of this app (as mentioned in #25)

**Comment by tkowark** [comment]
I hope that @tklingbeil answered the question and we'll try to make it clearer in future versions. If you have suggestions of how to fix this, we're always happy to accept Pull Requests for that!
