### ISSUE TITLE
Certificate & Journal info text refer to features unavailable in hibernation state

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-documentation#950]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects both Android **and** iOS, for specific issues / questions that apply only to one operating system, please raise them in the respective repositories:
    * [Android repository](https://github.com/corona-warn-app/cwa-app-android)
    * [iOS repository](https://github.com/corona-warn-app/cwa-app-ios)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Not important
- iOS/Android version: Not important
- App version: 3.2.1 (iOS) / 3.2.0 (Android)

## Describe the bug

Both the iOS and the Android app and both the "Certificates" & "Journal" tabs refer to unavailable features, which are not available in hibernation state, in their respective info screens.

| Certificates info screen | Journal info screen |
|---|---|
| <img src="https://user-images.githubusercontent.com/67682506/235713791-a102865c-27dc-439c-b76a-02e67517e6f0.PNG" width="300"> | <img src="https://user-images.githubusercontent.com/67682506/235713946-2d37578c-ff92-454f-9b10-aab48c524d4f.PNG" width="300"> | 
| | <img src="https://user-images.githubusercontent.com/67682506/235713952-87aae5ff-2486-4abc-ac46-2f455d3da76d.PNG" width="300"> |

## Steps to reproduce the issue

1. Open the CWA on version 3.2.1 or 3.2.0
2. Click on the Certificates or Journal tab 
3. Click on the info button/3 dots in the right-hand coroner, in case of the Journal tab, tap on "Information"
4. Read through the texts

## Expected behaviour

The information in the app should not refer to unavailable features.

## Possible Fix

For the certificates info screen the word "Add" could be replaced by "Store" or similar, but definitely the text should be changed so that it reflects that you can't add any new certificates.
For the journal info screen, the references to the showing of risky encounters should be removed.

---
Internal Tracking ID: [EXPOSUREAPP-15164](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-15164)

**Comment by MikeMcC399** [comment]
@Ein-Tim 

There are other places in the app where the texts are now inconsistent:

- About the App
- Terms of Use

so I have to assume it was a deliberate decision not to re-work all the texts and not an oversight or mistake.

The Data Privacy is however accurate and describes exactly the status from May 1, 2023 onwards.

**Comment by Ein-Tim** [comment]
@MikeMcC399 I'm unsure what is intentional and what not.
As soon as I get more information, I'll make sure to let you know what's the plan.

**Comment by Ein-Tim** [comment]
I am closing this issue: 

On the project side, it was considered acceptable not to revisit and adapt all text passages to the sleep mode, since both the announcement of the sleep mode and the "Thank you!" text on the "Status" tab explained in a prominent place and in sufficient form which functions are still available in the app and which are not. Accordingly, there are no plans to adjust these texts in the future.
