### ISSUE TITLE
Assumed/required properties of identifiers

### ISSUE THREAD

**Issue by noleti** [corona-warn-app/cwa-documentation#96]
## What is missing

The documentation mentions a number of identifiers: GUID, registration token, TAN, teleTAN. It currently does not always specify assumed properties such as:
- length (in bit)
- entropy/distribution
- whether they could contain direct PII (e.g. GUID)
- whether they could potentially be predicted (i.e. is GUID a counter which is incremented for each test?)
- whether they must be only used once (nonce-like), or if they could repeat eventually
- Who will have access to the identifiers (and who cannot have access)
- Lifetime of the identifiers in the app and backend (partially done, e.g. for TANs)

## Why should it be included

- All of the listed identifier will be used to authenticate users accessing public resources. 
- The difficulty of abusing the identifiers for impersonation or DoS attacks depends on the difficulty for the attacker to fabricate authentic identifiers. 
- In addition, the lifetime and access to the identifiers is relevant for privacy reasons. 
- There are also usability aspects, e.g. the length end representation of the teleTAN (decimal, with checksum, base56).
## Where should it be included

- I would suggest either a short description when each identifier is introduced, or a separate discussion of security-related properties.

**Comment by tklingbeil** [comment]
Thank you for your feedback! There will be dedicated documentation artefacts for the *Technical Security Concept* and *Data Privacy Concept* (as mentioned in the README.md).

There, the aspects mentioned above will definitely be handled.

**Comment by tkowark** [comment]
Thanks for suggesting these additions, @noleti . Please have a look at the upcoming documentation that tklingbeil mentioned and reopen this one or create a new issue if there are still inaccuracies regarding identifier properties
