### ISSUE TITLE
Minor: web-safe fonts in svg figures

### ISSUE THREAD

**Issue by noleti** [corona-warn-app/cwa-documentation#97]
This one is minor, wanted to provide feedback nevertheless: figures are (at least in github) embedded as SVG directly. Fonts that are currently used include "Helvetica Neue". For systems without those fonts installed, the rendering in the browser (and other applications) will be impacted. 

Example rendering on my machine (vanilla Ubuntu 18.04)
![test](https://user-images.githubusercontent.com/6284775/82327816-3ee25b00-99df-11ea-9279-cd6599d4cde4.png)
 
## Where to find the issue

Any of the svg images (e.g., https://github.com/corona-warn-app/cwa-documentation/raw/master/images/solution_architecture/figure_1.svg?sanitize=true)

## Describe the issue

- see above, svg is rendered with incorrect spacing due to localy missing font.

## Suggested change

- It seems that normally the font would be provided by the hosting page, not sure how this works in github.
- Embed the images as PNG (in addition to having the svg sources here)
- Embed the font directly (quick googling suggests https://github.com/BTBurke/svg-embed-font or  https://vecta.io/nano). 

---
Internal Tracking ID: EXPOSUREAPP-2964

**Comment by tkowark** [comment]
Thanks for that input. We'll have a look and try to fix that

**Comment by jn4kr** [comment]
also affecting standard manjaro linux and whonix installs.

possible workaround for the moment: Open the svg in a (firefox) tab and highlight the text in question. The highlighted characters will then at least not overlap anymore.

**Comment by Ein-Tim** [comment]
I think this, now nearly two year old, issue was never addressed. It makes no sense to leave issues open for two years without any process on them. I suggest to either fix this issue or apply the https://github.com/corona-warn-app/cwa-documentation/labels/wontfix label here and close it.

**Comment by dsarkar** [comment]
Dear community, 

this issue became stale. A simple solution would be to offer alternatively PNG images. However, we are closing this issue now; should you consider that this should be fixed, please re-open. Thanks.

Best wishes, DS

---
Corona-Warn-App Open Source Team
